### ISSUE TITLE
Winget crashes on fresh-installed Win11

### ISSUE THREAD

**Issue by gosukretess** [microsoft/winget-cli#3740] opened 2023-10-07 07:24 UTC
### Brief description of your issue

I have laptop with freshly installed Windows 11 Home. I wanted to install all applications I need using winget but it just crashes. Microsoft Store opens and looks to work fine. Typing "winget" returns help info, but trying to run anything like "winget list" or "winget install" crashes the application.

### Steps to reproduce

Just type "winget list".

### Expected behavior

Display the list of installed apps.

### Actual behavior

Literally does nothing. 

Data from EventLog:
```
[-](https://github.com/microsoft/winget-cli/issues/new?assignees=&labels=&projects=&template=Bug_Report.yml#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/microsoft/winget-cli/issues/new?assignees=&labels=&projects=&template=Bug_Report.yml#) <System>
  <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" /> 
  <EventID>1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2023-10-07T07:13:29.9558597Z" /> 
  <EventRecordID>1277</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="2736" ThreadID="7464" /> 
  <Channel>Application</Channel> 
  <Computer>MyComputerName</Computer> 
  <Security UserID="S-1-5-21-3254547872-1551346651-3222648452-1002" /> 
  </System>
[-](https://github.com/microsoft/winget-cli/issues/new?assignees=&labels=&projects=&template=Bug_Report.yml#) <EventData>
  <Data Name="AppName">winget.exe</Data> 
  <Data Name="AppVersion">1.17.2203.10001</Data> 
  <Data Name="AppTimeStamp">622a8652</Data> 
  <Data Name="ModuleName">WindowsPackageManager.dll</Data> 
  <Data Name="ModuleVersion">1.17.2203.10001</Data> 
  <Data Name="ModuleTimeStamp">622a8613</Data> 
  <Data Name="ExceptionCode">c0000005</Data> 
  <Data Name="FaultingOffset">0000000000089bf3</Data> 
  <Data Name="ProcessId">0x1a64</Data> 
  <Data Name="ProcessCreationTime">0x1d9f8edc5bef96d</Data> 
  <Data Name="AppPath">C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.17.10691.0_x64__8wekyb3d8bbwe\winget.exe</Data> 
  <Data Name="ModulePath">C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.17.10691.0_x64__8wekyb3d8bbwe\WindowsPackageManager.dll</Data> 
  <Data Name="IntegratorReportId">213df970-33ca-472c-83d4-feb9f5e42379</Data> 
  <Data Name="PackageFullName">Microsoft.DesktopAppInstaller_1.17.10691.0_x64__8wekyb3d8bbwe</Data> 
  <Data Name="PackageRelativeAppId">winget</Data> 
  </EventData>
  </Event>
```

Log file after typing "winget list":
```2023-10-07 09:22:22.336 [CORE] WinGet, version [1.2.10691], activity [{96D8EB40-111B-4F72-8B41-58995576AF1A}]
2023-10-07 09:22:22.337 [CORE] OS: Windows.Desktop v10.0.22621.2361
2023-10-07 09:22:22.337 [CORE] Command line Args: "C:\Users\Kapu\AppData\Local\Microsoft\WindowsApps\winget.exe" list
2023-10-07 09:22:22.337 [CORE] Package: Microsoft.DesktopAppInstaller v1.17.10691.0
2023-10-07 09:22:22.337 [CORE] IsCOMCall:0; Caller: winget-cli
2023-10-07 09:22:22.342 [CLI ] WinGet invoked with arguments: 'list'
2023-10-07 09:22:22.342 [CLI ] Found subcommand: list
2023-10-07 09:22:22.342 [CLI ] Leaf command to execute: root:list
2023-10-07 09:22:22.342 [CLI ] Executing command: list
2023-10-07 09:22:22.352 [REPO] GetCurrentSourceRefs: Source named 'microsoft.builtin.desktop.frameworks' from origin Default is hidden and is dropped.
2023-10-07 09:22:22.352 [REPO] Default source requested, multiple sources available, adding all to source references.
2023-10-07 09:22:22.352 [REPO] Adding to source references msstore
2023-10-07 09:22:22.352 [REPO] Adding to source references winget
2023-10-07 09:22:22.353 [REPO] Source past auto update time [5 mins]; it has been at least 28277722 mins
```

### Environment

```shell
Windows Package Manager v1.2.10691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2361
Package: Microsoft.DesktopAppInstaller v1.17.10691.0
```

**Comment by MichaelReiserSAP** [comment] 2023-10-07 07:27
WinGet v1.2.10691 will not work anymore you first have to update to v1.6.2771

**Comment by mdanish-kh** [comment] 2023-10-07 07:37
Duplicate of #3704;

- Related to https://github.com/microsoft/winget-cli/issues/3652

Please upgrade to the latest version of WinGet from either MS Store / [GitHub Releases](https://github.com/microsoft/winget-cli/releases) / this URL https://aka.ms/getwinget

**Closed** 2023-10-07 07:37 UTC
Labels: Needs-Triage

**Comment by gosukretess** [comment] 2023-10-07 07:40
Thanks for the reply. I tried updating, but from MSStore I click "Update" and nothing happens (I can install other apps, this one just does not work). I used the Github release, I tried the link from aka.ms - when I run msixbundle file I got error that app package cannot be opened because:
`
Installation of this application package using the Application Installer is not supported because it uses some limited capabilities.
` (I translated it from polish so may not be 100% correct with english version of error). I tried to run this from admin command prompt but still getting the same error.

**Comment by mdanish-kh** [comment] 2023-10-07 07:48
What do you get if you download the msixbundle file and run:

`Add-AppxPackage -Path .\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle`

from the terminal?

**Comment by gosukretess** [comment] 2023-10-07 07:53
Wow, when run using your command from terminal it completed successfully. And looks like it upgraded.
```
Windows Package Manager v1.6.2771
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2361
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.2771.0
```

Thank you!
