### ISSUE TITLE
Is there a way to ignore upgrading the specified software？

### ISSUE THREAD

**Issue by ron159** [microsoft/winget-cli#996] opened 2021-05-27 02:14 UTC
# Description of the new feature/enhancement

I want to use `winget upgrade -all` to quickly upgrade all the applications on my system that need to be upgraded, but for some software I want to keep the old version.
Is it possible to set a list where the softwares above can be ignored by the command. Like what is provided by pamac on manjaro.

**Comment by denelon** [comment] 2021-05-27 02:17
@ron159,

Thank you for the suggestion. This appears to be a duplicate of #476 Pin a package. Be sure to add your 👍 to that issue.

**Comment by denelon** [comment] 2021-05-27 02:17
Duplicate of #476

**Closed by denelon** 2021-05-27 02:17 UTC
Labels: Issue-Feature

**Comment by ron159** [comment] 2021-05-27 02:26
> @ron159,
> 
> Thank you for the suggestion. This appears to be a duplicate of #476 Pin a package. Be sure to add your 👍 to that issue.
THX

**Comment by ron159** [comment] 2021-05-27 02:26
> @ron159,
> 
> Thank you for the suggestion. This appears to be a duplicate of #476 Pin a package. Be sure to add your 👍 to that issue.

THX
