### ISSUE TITLE
Winget: adding new repository

### ISSUE THREAD

**Issue by MXP2095onetechguy** [microsoft/winget-cli#815] opened 2021-03-21 02:56 UTC
I want to see the ability to add new repository(you don't have to implement it)
# Description of the new feature/enhancement
you can add new software repository similar to winget-pkg

# Proposed technical implementation details (optional)
adding this command: winget addrep [the url of the repository]
using the command above with the url you want, you can add third party repository

**Comment by jedieaston** [comment] 2021-03-22 18:08
I think this is a duplicate of #118 (as well as a few others I'm sure).

**Comment by denelon** [comment] 2021-03-22 20:41
The command is `winget source add`

```
PS C:\Users\denelon> winget source add -?
Windows Package Manager v0.2.10771 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Add a new source. A source provides the data for you to discover and install packages. Only add a new source if you trust it as a secure location.

usage: winget source add [-n] <name> [-a] <arg> [[-t] <type>]

The following arguments are available:
  -n,--name  Name of the source
  -a,--arg   Argument given to the source
  -t,--type  Type of the source

More help can be found at: https://aka.ms/winget-command-source
PS C:\Users\denelon>
```

**Comment by denelon** [comment] 2021-03-22 20:41
Duplicate of #118

**Closed by denelon** 2021-03-22 20:42 UTC
Labels: Issue-Feature, Needs-Triage
