### ISSUE TITLE
Can't install anything, from any source

### ISSUE THREAD

**Issue by fluffynuts** [microsoft/winget-cli#2123] opened 2022-04-26 11:26 UTC
### Brief description of your issue

Everything I've tried to install via winget, even from different sources, has led to an error like this:
![image](https://user-images.githubusercontent.com/4669340/165289714-aae82b0c-3126-4286-af6f-291ece03ab87.png)

I've tried disabling antivirus (eset) altogether, no difference. If I go find the installer in my temp folder and double-click it, it runs just fine. I've tried running winget as a regular user and as administrator.

I have to assume I'm missing something fairly basic?

### Steps to reproduce

`winget install slcaktechnologies.slack` or `winget install discord.discord` or `winget install discord --source msstore`

### Expected behavior

I expected the installer to run

### Actual behavior

Installer is blocked

### Environment

```shell
Windows Package Manager (Preview) v1.3.692-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.613
Package: Microsoft.DesktopAppInstaller v1.18.692.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links               
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by jedieaston** [comment] 2022-04-26 14:52
I'm guessing no, but are you in a corporate environment where your IT people might have messed with your security settings?

**Comment by jedieaston** [comment] 2022-04-26 22:23
Something to try would to be to reset your "internet zone settings", as sometimes they get flipped around to where you can't run exes from certain directories that are downloaded from the internet.

In the Start Menu, search for "Internet Options", then in that window, click security, then click "Reset all zones to default level". then click okay. If that doesn't work, I can tell you which settings in there you can manually flip (I don't have time at the moment).

![image](https://user-images.githubusercontent.com/21368066/165402584-a316405f-f843-4f01-846f-6c6758dd2010.png)

**Comment by fluffynuts** [comment] 2022-04-27 20:56
I've been through this stuff, so unless the "custom level" UI is lying to me, this is not the droid I'm seeking (mine is set to "confirm" for unknown sources). The UI could be lying tho. OTOH, this is a relatively new win11 machine - it's only been up about 2 weeks. I'd expect it to not be super-odd just yet :D

**Comment by rkeithhill** [comment] 2022-04-27 22:13
Store app installation seems ... fickle to me.   Try `winget install slacktechnologies.slack -s winget`.  The default source is typically `msstore`.  So that is where `winget` tries to install from if you don't specify a different source.

**Comment by ItzLevvie** [comment] 2022-04-27 23:11
> The default source is typically `msstore`

This will only happen if the company you work at configured the default source to be `msstore` via Group Policy.

> So that is where winget tries to install from if you don't specify a different source.

WinGet's default source is still `winget` but ever since the `msstore` source rolled out to everyone you now need to be more specific on what package you want if you see "Multiple packages found matching input criteria. Please refine the input." on your terminal.

Previously if you did `winget install ruby` it'll install Ruby (from `winget` source), but since there's a similar app called "RubyGo" you will need to do `winget install RubyInstallerTeam.Ruby` which will allow you to download Ruby instead of a random app called RubyGo.

**Comment by rkeithhill** [comment] 2022-04-27 23:17
> WinGet's default source is still winget

Hmm, this is on my personal PC - no corporate GP:

<img width="359" alt="image" src="https://user-images.githubusercontent.com/5177512/165646402-77563c98-67d8-43fe-bb33-38aa2f4a4568.png">

The `msstore` source is first.  🤷‍♂️

**Comment by Masamune3210** [comment] 2022-04-27 23:18
Pretty sure it's just alphabetical, could be wrong though

**Comment by rkeithhill** [comment] 2022-04-27 23:24
Looking over the docs on the `source` command, I think you're right about the output being alphabetical. I see no mention of order/priority which makes winget a bit different than other pkg systems I've worked with.

**Comment by tyler274** [comment] 2022-05-28 02:37
I'm not on any domain, and this is affecting me now. Even tried disabling everything I could find

**Comment by fluffynuts** [comment] 2022-05-28 19:43
somehow, this is not affecting me any more; `winget` now "just works" (mostly). I'm not at all sure what changed.

**Comment by fluffynuts** [comment] 2022-05-31 07:53
aaand... it's back, trying to `winget upgrade --all` and failing on the gvim installer that it got from github. I've reset all security zones, I've tried elevating, nothing. I'll have to hunt this installer down and run it manually, which I _bet_ will work just fine

**Comment by fluffynuts** [comment] 2022-05-31 07:55
yup, tracked it down within the %LOCALAPPDATA%\Temp\Winget folder, and the installer works just fine :|

**Comment by fluffynuts** [comment] 2022-05-31 07:57
whilst I get that this issue (probably) isn't directly winget's fault, it's really annoying; something that would make it slightly less-so would be if winget printed out the full path to the installer it's trying to run, so it would be a little easier to track down.

I'm also not sure if perhaps changing the download location would help?

**Comment by fluffynuts** [comment] 2022-05-31 08:02
Another thought I've had is perhaps it's related to install type? VIM has a .exe installer, so does Discord (that I had issues with). OTOH, so does the Humble Bundle app, and that installed fine 🤔

**Comment by fluffynuts** [comment] 2022-05-31 09:02
I think that the location of the downloaded artifact may be the problem - changing the environment variable `TMP` to point at another temp location (`C:\tmp`), I could install things just fine. It would seem that perhaps `winget` should rather use a folder outside of the special `%LOCALAPPDATA%\Temp` location as it's being screened differently.

to re-iterate: setting the `TMP` environment variable, at the user level, was enough to bypass the installation issue.

**Comment by Karl-WE** [comment] 2023-01-07 02:05
@fluffynuts for me it reads like a permission issue as if winget is trying to install in a different context.

Your Account is part of local Admin?
Has the Admin group a Standard Name
Are you using local Account or MS Account or Domain Account?

**Comment by fluffynuts** [comment] 2023-01-07 05:42
It's not a permissions issue, since I could run the installer manually. This was so long ago and, iirc, on a different machine. I don't have the issue now, so either it was machine-specific or was "fixed by accident". It seemed like the automated process couldn't run the installer from a temp folder (where I could, from the same account and shell).

**Comment by loosus** [comment] 2023-02-08 15:29
Just adding to the pile: we are seeing this, too, now.  This affects only *.exe installations; it does not affect other installation types.

I can manually install the *.exe files from these directories:

C:\Users\<USERNAME>\
C:\Users\<USERNAME>\AppData\
C:\Users\<USERNAME>\AppData\Local\
C:\Users\<USERNAME>\AppData\Local\Temp\

But I cannot install from this directory:

C:\Users\<USERNAME>\AppData\Local\Temp\WinGet

So it seems to be unique to the WinGet directory.

I am logged in as an administrator.

**Comment by denelon** [comment] 2024-08-02 23:02
We've had several releases of WinGet since this issue was reported. Is this still happening?

**Comment by fluffynuts** [comment] 2024-08-03 18:29
not for me - but I'm also on a new machine, so i've basically had a nuclear win?

**Comment by denelon** [comment] 2024-09-05 22:17
OK, I'm going to go ahead and close this issue since we haven't seen a reproduction report for this in the last month.

**Closed by denelon** 2024-09-05 22:17 UTC
Labels: Help-Wanted, Issue-Bug, Needs-Attention
