### ISSUE TITLE
winget upgrade -all ignores Microsoft Store apps

### ISSUE THREAD

**Issue by ward-horsfall** [microsoft/winget-cli#3378] opened 2023-06-26 00:06 UTC
### Brief description of your issue

Hi,

It seems that Winget upgrade --all does not seem to detect any Microsoft Store apps that need to be upgraded.

It would be good it if can do this. 

Thanks
Ward

### Steps to reproduce

Install Windows 11

### Expected behavior

The store apps to be upgraded

### Actual behavior

It ignores the Store apps

### Environment

```shell
Windows Package Manager v1.2.10691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1848
Package: Microsoft.DesktopAppInstaller v1.17.10691.0
```

**Comment by mdanish-kh** [comment] 2023-06-26 11:04
Duplicate of #2854

**Closed** 2023-06-26 11:04 UTC
Labels: Needs-Triage
