### ISSUE TITLE
Installing apps from MSstore via Winget in system context fails.

### ISSUE THREAD

**Issue by DanHSO** [microsoft/winget-cli#2495] opened 2022-09-05 09:59 UTC
### Brief description of your issue

Installing MSstore apps with Winget in the system context does not work. and is dropping an error.
Installing this way from the Winget repo however work fine.

I have seen some posts about this issue before but none have been reported as a bug report.

### Steps to reproduce

1. Either via script or just browsing to location of Winget.exe. Install the app.

$ResolveWingetPath = Resolve-Path "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_*_x64__8wekyb3d8bbwe"
    if ($ResolveWingetPath){
           $WingetPath = $ResolveWingetPath[-1].Path
    }
$config
cd $wingetpath
.\winget.exe Install -e -h --accept-source-agreements --accept-package-agreements --id 9PLNC7BX90D4 --source msstore

### Expected behavior

Install should go thru

### Actual behavior

Found Dell Display Manager [9PLNC7BX90D4] Version Unknown
This package is provided through Microsoft Store. winget may need to acquire the package from Microsoft Store on behalf of the current user.
Version: Unknown
Publisher: EnTech Taiwan
Description: Dell Display Manager is used to manage a monitor or a group of monitors, allowing manual adjustment of the displayed image, assignment of automatic 
settings, energy management, open window organization, image rotation and other features on select Dell models. 
License: ms-windows-store://pdp/?ProductId=9PLNC7BX90D4
Privacy Url: https://www.dell.com/learn/us/en/uscorp1/policies-privacy
Agreements:
Category: Utilities & tools
Pricing: Free
Free Trial: No
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
Seizure Warning: https://aka.ms/microsoft-store-seizure-warning
Store License Terms: https://aka.ms/microsoft-store-license

Verifying/Requesting package acquisition...
An unexpected error occurred while executing the command: 
0x80070520 : En angitt påloggingsøkt finnes ikke. Den kan allerede være avsluttet

Wich translates to: a specified logon session does not exist. it may already have been terminated

### Environment

```shell
Windows Package Manager v1.3.0
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1889
System Architecture: X64

Logs: %TEMP%\WinGet\defaultState
```

**Comment by Trenly** [comment] 2022-09-05 20:19
Duplicate of #2490

**Closed by Trenly** 2022-09-05 20:19 UTC
Labels: Needs-Triage
