### ISSUE TITLE
Installing a package by its ID results in a Please refine the input message if there is a package with a similar ID

### ISSUE THREAD

**Issue by pranavb** [microsoft/winget-cli#264] opened 2020-05-21 07:57 UTC
# Brief description of your issue
Installing a package by its ID results in a `Please refine the input` message if there is a package with a similar ID.

# Steps to reproduce
```none
winget install Microsoft.dotnet
```

# Expected behavior
.NET Core is installed as `Microsoft.dotnet` is shown to be its ID

# Actual behavior
```none
> winget install Microsoft.dotnet
Multiple apps found matching input criteria. Please refine the input.
Name           Id                        Version
------------------------------------------------
.NET Core      Microsoft.dotnet          3.1.202
.Net Framework Microsoft.dotNetFramework 4.7.1
```

# Environment

```none
Windows Package Manager v0.1.41331 Preview
Windows: Windows.Desktop v10.0.19041.264
Package: Microsoft.DesktopAppInstaller v1.0.41331.0
Windows Package Manager version

Any other software? Had just uninstalled the .NET Framework (older version) with Chocolatey
```

**Comment by Andy-Dawson** [comment] 2020-05-21 08:15
I'm seeing the same for Mozilla.Firefox:

>winget install Mozilla.Firefox
Multiple apps found matching input criteria. Please refine the input.
Name        Id                 Version
----------------------------------------
Firefox     Mozilla.Firefox    75.0
Firefox ESR Mozilla.FirefoxESR 68.8.0esr

>winget install --id Mozilla.Firefox
Multiple apps found matching input criteria. Please refine the input.
Name        Id                 Version
----------------------------------------
Firefox     Mozilla.Firefox    75.0
Firefox ESR Mozilla.FirefoxESR 68.8.0esr

>winget install --name Firefox
Multiple apps found matching input criteria. Please refine the input.
Name        Id                 Version
----------------------------------------
Firefox     Mozilla.Firefox    75.0
Firefox ESR Mozilla.FirefoxESR 68.8.0esr

In addition .specifying '-e' tried to perform the install (after throwing an error about the 7-Zip config info; see attached image), but gave an error:
>winget install -e Mozilla.Firefox
Found Firefox [Mozilla.Firefox]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://cdn.stubdownloader.services.mozilla.com/builds/firefox-stub/en-US/win/4ac1df3ef43bf3cc3eabd0b3dbfe76e8b9d440e4b1da0954ee00e6d079ba0fbf/Firefox%20Installer.exe
  ██████████████████████████████   312 KB /  312 KB
Successfully verified installer hash
Installing ...
Installer failed with exit code: 1
![WInGet FireFox Error](https://user-images.githubusercontent.com/37336467/82538377-926db980-9b43-11ea-809a-d8aa102241c3.png)

**Comment by Sominemo** [comment] 2020-05-21 10:25
Does not reproduce for me
![image](https://user-images.githubusercontent.com/19842935/82550013-8fd08b80-9b66-11ea-9f24-97e0d8ebceb3.png)

**Comment by Andy-Dawson** [comment] 2020-05-21 10:40
I get the error using '-e' for Firefox if not using an admin command prompt (d'oh, might have guessed that!), however the error thrown still references the wrong package.
The other issues are still valid.

**Comment by Sominemo** [comment] 2020-05-21 10:42
> I get the error using '-e' for Firefox if not using an admin command prompt (d'oh, might have guessed that!), however the error thrown still references the wrong package.
> The other issues are still valid.

I wasn't using an elevated command prompt for the screenshot, the installer elevated itself through the UAC prompt. What are your UAC settings?

**Comment by Andy-Dawson** [comment] 2020-05-21 10:59
In this instance, the default (notify me only when applications try to make changes to my computer), and there was no UAC prompt to elevate. My user account on the machine in question has been added as a local admin. The machine is a member of a domain.

**Comment by Dormanil** [comment] 2020-05-21 11:35
Duplicate of #133, `-e` woes with Firefox aside.

**Comment by zachcarp** [comment] 2020-05-28 16:42
It looks like this is a dupe of #133 (and we have multiple apps that are falling in that category). 
#133 is in the backlog as well.

**Comment by zachcarp** [comment] 2020-05-28 16:42
Duplicate of #133

**Closed by zachcarp** 2020-05-28 16:42 UTC
Labels: Needs-Triage
