### ISSUE TITLE
Reload PATH environment variable after package installation

### ISSUE THREAD

**Issue by kimwalisch** [microsoft/winget-cli#531] opened 2020-08-05 08:28 UTC
Hi,

My [Primesieve package](https://github.com/microsoft/winget-pkgs/blob/master/manifests/Primesieve/Primesieve/7.5.yaml) is a command-line tool and its setup (based on Inno Setup) adds its path (```C:\Program Files\Primesieve\bin```) to the ```PATH``` environment variable. However when I install primesieve using ```winget install primesieve``` I cannot immediately use it on the command-line as the PATH environment variable has not been reloaded yet (tested using ```cmd.exe```):

![path-issue](https://user-images.githubusercontent.com/4656219/89388400-42df6880-d704-11ea-900b-6c9325efe113.png)

So I need to close the current terminal window, open a new terminal window and then I can start using my tool. This is quite annoying, on Linux and MacOS you can immediately use a tool after the installation with the package manager has completed.

Is there a known workaround for this issue?

If there is no workaround for this issue yet, I see 2 possible options to fix/improve this issue:

1. Reload the ```PATH``` environment variable after each package installation.
2. Add a yaml manifest option where package maintainers can specify if the ```PATH``` environment variable should be reloaded after the package installation.

**Comment by denelon** [comment] 2020-08-10 20:45
Related to #194 in the sense that we may need to handle PATH reload for that as well.

**Comment by sredna** [comment] 2020-08-20 17:49
There is a Windows broadcast message you can send to tell all running apps that they should reload their environment but Explorer.exe is the only application (AFAIK) that actually cares enough to do it (and it probably uses a undocumented function to do so). Even if most applications did it, cmd.exe would probably be excluded from it by design, you don't want your command interpreter to automatically override your variables at unknown times.

The only documented way for this to actually work would be for winget to exist as a batch file and as wingetReal.exe finishes, it would have to write `set ..` statements into a batch file that the main batch file runs and this would update the parent cmd.exe instance. There are however disadvantages to using a batch file as your main entry-point.

Changing the environment of your parent process by modifying the PEB is undocumented, has multiple race conditions and is probably too much of a hack.

**Comment by kiran94** [comment] 2020-09-02 09:09
Adding that chocolatey ships with a script called [`refreshenv` ](https://github.com/chocolatey/choco/blob/b6495f72d1f2b9901747d857467c4ed3f7306391/src/chocolatey.resources/redirects/RefreshEnv.cmd), I currently use this to refresh my environment variables including `PATH` if I don't want to re-open terminal.

**Comment by ArtexJay** [comment] 2020-11-17 18:26
i think this would be really cool if powershell would then be able to automatically set the path to any installed applications, allowing users to easily open programs like you can do with notepad at the moment.

**Comment by kimwalisch** [comment] 2021-07-10 12:53
This issue is basically identical to issue https://github.com/microsoft/winget-cli/issues/222 (and many other similar issues that have already been closed as duplicate).

**Comment by denelon** [comment] 2021-07-12 16:27
Duplicate of #222

**Closed by denelon** 2021-07-12 16:27 UTC
Labels: Issue-Feature
