### ISSUE TITLE
Winget Export with existing scope 

### ISSUE THREAD

**Issue by kdpuvvadi** [microsoft/winget-cli#2079] opened 2022-04-09 11:13 UTC
### Description of the new feature / enhancement

I've installed VS code with the machine scope. Exported the list of application and when i tried to import that list in a new machine, it's installing application scope as user. i had add `"Scope" : "machine"` manually to install em as machine scope. why not export current scope in json as scope is already in the schema?

**Comment by Trenly** [comment] 2022-04-09 23:47
I believe denelon already addresesed this [here](https://github.com/microsoft/winget-cli/issues/2030#issuecomment-1072527430) making this a duplicate of #2030

**Comment by denelon** [comment] 2022-04-11 19:05
Duplicate of #2030

**Closed by denelon** 2022-04-11 19:05 UTC
Labels: Issue-Feature, Needs-Triage
