### ISSUE TITLE
winget giving me the 404 error

### ISSUE THREAD

**Issue by Oddballalex36** [microsoft/winget-cli#4468] opened 2024-05-10 05:55 UTC
### Brief description of your issue

When i run winget upgrade --all i get a An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404). error

<img width="674" alt="Screenshot 2024-05-10 013718" src="https://github.com/microsoft/winget-cli/assets/163488541/1483ff7b-3855-4c02-bd10-5ab7251835df">

### Steps to reproduce

tried resetting the source, and even used idea from another report and install clink didnt help

### Expected behavior

upgrade my software

### Actual behavior

An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).

### Environment

```shell
Windows Package Manager v1.7.11261
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3527
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.11261.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
```

**Comment by tigerinus** [comment] 2024-05-10 10:46
The same here

**Comment by denelon** [comment] 2024-05-10 15:15
Duplicate of #152915

**Closed** 2024-05-10 15:15 UTC
