### ISSUE TITLE
Winget Search Results are Incorrect

### ISSUE THREAD

**Issue by johnturek** [microsoft/winget-cli#1608] opened 2021-10-18 12:54 UTC
### Brief description of your issue

When searching for something,  search results are showing random (or at least seems to be random) store results as well:

C:\Users\admin>winget install notion
Multiple packages found matching input criteria. Please refine the input.
Name                         Id            Source
--------------------------------------------------
Focalboard: Insiders Edition 9NLN2T0SX9VF  msstore
Notion                       Notion.Notion winget

C:\Users\admin>winget install notion -s winget

### Steps to reproduce

1.  search for something (example Notion)

2.  or attempt to install Notion without defining a source,  you will see a random store result as well
3. 

### Expected behavior

Notion isn't in the store,  so it should only return a winget source. 

### Actual behavior

Displaying a random app from the store, as well as Notion

### Environment

```shell
C:\Users\admin>winget --info
Windows Package Manager v1.1.12702
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22483.1000
Package: Microsoft.DesktopAppInstaller v1.16.12702.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by jedieaston** [comment] 2021-10-18 13:53
Duplicate of https://github.com/microsoft/winget-cli/issues/1523. 

(There are some tips in that thread on how to work around it.)

**Closed as completed** 2021-10-18 15:42 UTC
