### ISSUE TITLE
Package installs have the ability to force an immediate computer restart with no prompt

### ISSUE THREAD

**Issue by joeypshell** [microsoft/winget-cli#490] opened 2020-07-08 16:05 UTC
# Brief description of your issue
Package installs have the ability to force an immediate computer restart with no prompt

# Steps to reproduce
Calibre 4.19.0 (installed previously through winget) was already installed, attempted to re-install using "winget install calibre". Installation was completed successfully, however MsiInstaller was able to immediately choose to restart the system without a prompt.

```
The Windows Installer initiated a system restart to complete or continue the configuration of 'calibre 64bit'.
```

# Expected behavior
Packages installed through winget should either suppress or prompt before a system can be restarted, a restart should not be initiated automatically unless there was an option to explicitly enable this. Even then, the default should be to have this disabled.

# Actual behavior
System is allowed to initiate a restart automatically without a prompt when the installer calls for it.

```
The process msiexec.exe has initiated the restart of computer DESKTOP on behalf of user NT AUTHORITY\SYSTEM for the following reason: No title for this reason could be found
 Reason Code: 0x80030002
 Shutdown Type: restart
 Comment: The Windows Installer initiated a system restart to complete or continue the configuration of 'calibre 64bit'.
```

# Environment

```none
[winget --info]
Windows Package Manager version: v0.1.41331 Preview
Windows: Windows.Desktop version: Windows.Desktop v10.0.19041.329
Package: Microsoft.DesktopAppInstaller version: Microsoft.DesktopAppInstaller v1.0.41331.0

Any other software?
```
Calibre 4.19.0 x64

**Comment by megamorf** [comment] 2020-07-08 22:15
@joeypshell Please add your feedback here instead: #229

**Comment by denelon** [comment] 2020-07-09 00:57
Duplicate of #229

**Closed by denelon** 2020-07-09 00:57 UTC
Labels: Needs-Triage
