### ISSUE TITLE
[issue] the "winget install "App Installer" -s msstore" returns a "0x80004004" error

### ISSUE THREAD

**Issue by Foadsf** [microsoft/winget-cli#2878] opened 2023-01-25 07:07 UTC
I am trying to use the command from [here](https://github.com/microsoft/winget-cli/issues/505#issuecomment-1043261010)

    winget install "App Installer" -s msstore

to let winget update itself. But I get the error message:

> Failed to install or update Microsoft Store package. Error code: 0x80004004

Please let me know the problem and how I can resolve it.

**Comment by denelon** [comment] 2023-01-25 16:30
@Foadsf I've used that method for upgrade (or downgrade) myself a few times. Can you share the output of `winget --info` so I know what version is currently on the system?

You may also need to add "--force": `winget install "App Installer" -s msstore --force`

<img width="867" alt="install appinstaller force" src="https://user-images.githubusercontent.com/61799811/214620230-5a78c5b5-40cf-4390-abdb-f99e30e356f7.png">

**Comment by Foadsf** [comment] 2023-01-26 07:41
Dear @denelon ,

Thanks for the response. The `winget --info` commands return:

~~~
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.2364
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
~~~

and the `winget install "App Installer" -s msstore --force` seems to work, as I get:

~~~
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.2364
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0
~~~

**Comment by denelon** [comment] 2023-01-26 17:41
I'm glad to see it worked for you.

I'm going to cross link this with another Issue so the connection is made with the error and close this as a duplicate.
* #505

Duplicate of #505

**Closed** 2023-01-26 17:41 UTC
Labels: Issue-Bug
