### ISSUE TITLE
Private repository hosting

### ISSUE THREAD

**Issue by ardenercelik** [microsoft/winget-cli#762] opened 2021-02-19 15:27 UTC
I would like to host my personal repository with this tool. Is it possible to provide  packages folder which is not the one in the https://github.com/microsoft/winget-pkgs repository?

Should I build my own instance or is it possible to provide direct substitude for the winget-pkgs folder?

**Comment by megamorf** [comment] 2021-02-19 18:01
Duplicate of:

* #160
* #203
* #213
* #226

/cc @denelon

**Comment by denelon** [comment] 2021-02-22 16:55
Duplicate of #226

**Closed by denelon** 2021-02-22 16:55 UTC
Labels: Issue-Feature, Needs-Triage
