### ISSUE TITLE
Track download progress with `Node.js`

### ISSUE THREAD

**Issue by KK-Designs** [microsoft/winget-cli#2833] opened 2023-01-10 05:34 UTC
How would I track a packages download progress with nodejs `child_process.spawn()` function? Right now I'm only receiving the progress bar after the package is done downloading.

**Comment by Trenly** [comment] 2023-01-10 13:16
Duplicate of https://github.com/microsoft/winget-cli/discussions/2791

**Closed** 2023-01-10 13:16 UTC
Labels: Needs-Triage
