### ISSUE TITLE
winget remove

### ISSUE THREAD

**Issue by AdilHindistan** [microsoft/winget-cli#192] opened 2020-05-19 17:31 UTC
# Description of the new feature/enhancement

It would be great to have a remove option for packages installed via winget

e.g.
winget remove vscode              # remove vscode
winget remove vscode -v 1.x.y  # remove vscode version 1.x.y

**Comment by utybo** [comment] 2020-05-19 17:41
This is probably a duplicate of #121

**Comment by denelon** [comment] 2020-05-19 21:22
Yes, this is a duplicate.

**Closed** 2020-05-19 21:22 UTC
Labels: Issue-Feature
