### ISSUE TITLE
Add an argument to the the Winget upgrade -all command to except packages of being updated

### ISSUE THREAD

**Issue by TSnatch72** [microsoft/winget-cli#1484] opened 2021-09-20 00:42 UTC
# Description of the new feature/enhancement
Currently, you can either upgrade packages one by one or use upgrade -all to update them all in a single command. However, there's situations when one needs to keep an older version of a package for compatibility or stability. **IE:** a second instance of python for running software not compatible with newer version or not wanting to update Oracle Virtualbox to no break compatibility with guest additions. 

I would propose to add an argument that marks the package you name after it as an exception so every other package is updated instead. Also allow multiple exceptions in a single string

# Proposed technical implementation details (optional)
Maybe something like `-b or --but`, `-d or --donot` or `-x or --except`

Extructure would be `winget [upgrade] [--all] [-b] [Package Name, Moniker or ID]`

### Example:
`winget upgrade --all -b Python.3 `

**Comment by denelon** [comment] 2021-09-20 18:46
Duplicate of #476

**Closed by denelon** 2021-09-20 18:46 UTC
Labels: Issue-Feature, Needs-Triage
