### ISSUE TITLE
prevent winget output from being truncated, which removes useful information (e.g. winget --info)

### ISSUE THREAD

**Issue by mattmazzola** [microsoft/winget-cli#4523] opened 2024-06-01 03:28 UTC
### Description of the new feature / enhancement

Certain `winget` commands output text that is truncated.
Alarmingly, this even occurs when output is redirected, such as to a file, which doesn't have a character width display constraint and there is not a reason to truncate.

## Example

```powershell
winget --info | Select-String -Pattern "%LOCALAPPDATA%\\Packages\\Microsoft\.DesktopAppInstaller_[\w]*\\LocalState\\s.*" | ForEach-Object { $_.Matches.Value }
```

```text
%LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settΓÇª
```

Notice what I think is garbled Unicode `ΓÇª` at the end, implying it seems truncated at the byte level and not clean character limit.

As #4521 mentions, because the output is not structured, it already requires hacks to get the desired value from it (see here I am using regex) and even more the value isn't complete which requires more hacks on assumptions based on knowing the full file name is `settings.json`

## Expectation

The output of the above command should the _expanded_ full path 
```text
%LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
```

## Related Issues

#4521 
#4508 

### Proposed technical implementation details

It's not clear how the current output is produced but change that not to truncate.

**Comment by mdanish-kh** [comment] 2024-06-15 11:10
@mattmazzola Is this the same request as https://github.com/microsoft/winget-cli/issues/1653? If so, can we close this issue as duplicate and move the discussion there for better tracking?

[comment]: <[Policy] Needs-Author-Feedback>

**Comment by mdanish-kh** [comment] 2024-06-15 11:11
[Policy] Area-Output

**Comment by mattmazzola** [comment] 2024-06-15 20:05
Yes, I think this is the same request

I think this issue gives better description of the problem, but I see the other issue has more activity.

I think it can be closed if you think appropriate

**Comment by mdanish-kh** [comment] 2024-06-16 11:36
Thank you, please consider adding a comment if you can expand on the issue and giving it a 👍 to raise its priority. I'll close this one out.

Duplicate of #1653

**Closed** 2024-06-16 11:37 UTC
Labels: Issue-Feature, Needs-Attention, Area-Output
