### ISSUE TITLE
Warnings unreadable if PowerShell or Command Prompt background is changed

### ISSUE THREAD

**Issue by iseeghosts** [microsoft/winget-cli#2004] opened 2022-03-06 04:55 UTC
### Brief description of your issue

I prefer whitish/grayish color as background on cmd/pwsh, but setting so affects readability of warnings from winget. I have tried changing colors in PowerShell but none of that seemed to work. And both PowerShell and Command seem to have this issue giving me an impression that it might be winget itself.

PowerShell Output
![image](https://user-images.githubusercontent.com/34771316/156909678-85bc1a8d-998d-4c52-aa96-39978329fce1.png)
if you look closely, the entire output is - 
**Multiple packages found matching input criteria. Please refine the input.** (unreadable because yellow on gray)
Name                Id                  Source
-----------------------------------------------
Microsoft PowerToys XP89DCGQ3K6VLD      msstore
PowerToys (Preview) Microsoft.PowerToys winget

Another simiar case (Command Prompt Output) -
![image](https://user-images.githubusercontent.com/34771316/156909753-b709ba98-b669-43b5-8991-45d408ea4e63.png)
The unreadable text is another warning that says -
**Failed in attempting to update the source: winget
Multiple packages found matching input criteria. Please refine the input.**

### Steps to reproduce

set the background color of cmd/powershell to gray/white

try to install a package that will throw warning for multiple input crteria 

### Expected behavior

readable warnings

### Actual behavior

Unreadable warning due to colors not updating with background color

### Environment

```shell
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.1526
Package: Microsoft.DesktopAppInstaller v1.17.10271.0
```

**Comment by iseeghosts** [comment] 2022-03-06 04:56
I've tried to change the warning colors from profile file for powershell but none of them seem to affect the outcome
![image](https://user-images.githubusercontent.com/34771316/156909837-619289b1-d1d3-4f9c-84e2-68ebdfcc932f.png)

**Comment by vedantmgoyal2009** [comment] 2022-03-06 05:24
* Related to: https://github.com/microsoft/winget-cli/issues/1920

**Comment by denelon** [comment] 2022-03-07 15:51
Duplicate of #1920

**Closed by denelon** 2022-03-07 15:51 UTC
Labels: Needs-Triage
