### ISSUE TITLE
Specify where tool is located for ZIP installers

### ISSUE THREAD

**Issue by heaths** [microsoft/winget-cli#202] opened 2020-05-19 19:08 UTC
For nuget-packaged tool installers, tools are often in a "tools" subdirectory of the .nupkg - a ZIP file using the OPC standard. It would be great if developer could specify the subdirectory that should be added to the `PATH` environment variable, assuming that is within the future scope of this project, as Chocolatey and Scoop already support.

**Comment by denelon** [comment] 2020-05-22 22:50
This looks like it may be a duplicate of #140

**Comment by denelon** [comment] 2020-05-23 05:06
Duplicate of #140

**Closed by denelon** 2020-05-23 05:06 UTC
Labels: Issue-Feature
