### ISSUE TITLE
Possibility to flag a package as broken or out-of-date 

### ISSUE THREAD

**Issue by rhemberger** [microsoft/winget-cli#1380] opened 2021-08-18 12:17 UTC
# Description of the new feature/enhancement
Please implement a way to flag a package as broken or outdated. 
As e.g. in AUR: https://aur.archlinux.org/ or Chocolatey

Prevents useless download and installation attempts.
# Proposed technical implementation details (optional)

Let WinGet ignore these packages.

**Comment by denelon** [comment] 2021-08-19 00:52
Duplicate of #920

**Closed by denelon** 2021-08-19 00:52 UTC
Labels: Needs-Triage
