### ISSUE TITLE
'Upgrade all' upgrades the same package multiple times..

### ISSUE THREAD

**Issue by j-dc** [microsoft/winget-cli#1707] opened 2021-11-15 09:34 UTC
### Brief description of your issue

When executing winget upgrade --all the same application get's updated more then once.

In this case, Visual Studio 2019 enterprise get's updated 3 times!

![image](https://user-images.githubusercontent.com/8330653/141755853-5e05b3e9-c4f3-49c8-8499-723c230dbb01.png)
(the schreenshot shows visual studio, but other programs also have this issue)

### Steps to reproduce

Run winget upgrade --all   

### Expected behavior

All outdated programs should upgrade exactly one time

### Actual behavior

Multiple programs upgrade 2 or even 3 times.  (In the case of the screenshot it was only Visual studio, but other programs have this issue to)

### Environment

```shell
Windows Package Manager v1.1.12702
Windows: Windows.Desktop v10.0.22494.1000
Package: Microsoft.DesktopAppInstaller v1.16.12702.0
```

**Comment by jedieaston** [comment] 2021-11-15 16:20
Can you post the entirety of the output from `winget upgrade --all`? The first couple of lines are printed while it looks for an EULA to print (which seems like a bug if there isn't a EULA to print), but that doesn't necessarily mean it is going to run the upgrade multiple times.

**Comment by j-dc** [comment] 2021-11-15 20:21
Now I have the same output as yours..    But there is always an update to Visual Studio...   The issue should be described very different I guess..         I always see 2 visual studio's, and one installer,     untill there is actually an update.. then I see 3 visual studio's as in my first screenshot..

Actually, I also have this 'always an update available'-issue for openvpnconnect.
![image](https://user-images.githubusercontent.com/8330653/141848102-9d722cec-a0cf-4ee7-bac5-755187eec6d3.png)

**Comment by denelon** [comment] 2021-11-16 00:38
Duplicate of #1075

**Closed by denelon** 2021-11-16 00:38 UTC
Labels: Needs-Triage
