### ISSUE TITLE
winget does not recognize MEGAsync's version.

### ISSUE THREAD

**Issue by KrisSchneider** [microsoft/winget-cli#2319] opened 2022-07-08 16:44 UTC
### Brief description of your issue

Winget does not recognize MEGAsync's version. It always shows as "Unknown".

### Steps to reproduce

1. Open a command line terminal (ex. Windows Terminal), 
2. Paste this command in into the terminal: `winget upgrade` 
3. You should then get this terminal output, 
```shell
PS C:\Users\krist> winget upgrade
Name     Id            Version Available Source
-----------------------------------------------
MEGAsync Mega.MEGASync Unknown 4.6.7.0   winget
1 upgrades available.
```
![(WindowsTerminal)o1B6M8_07-08-2022](https://user-images.githubusercontent.com/101912712/178034735-66bae25f-ccbe-4adc-b200-f49dd0a9ec04.jpg)

### Expected behavior

Winget should recognize MEGAsync's version without any problems.

### Actual behavior

Currently, winget does not recognize MEGASync's version. Even though MEGASync is already updated to the latest version.
![(MEGAsync)j2E2t8_07-08-2022](https://user-images.githubusercontent.com/101912712/178034939-6157c33d-c3b2-4ac9-9f52-5939ecd11a57.jpg)

### Environment

```shell
Windows Package Manager v1.2.11601
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1806
Package: Microsoft.DesktopAppInstaller v1.17.11601.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by ItzLevvie** [comment] 2022-07-08 16:56
Duplicate of https://github.com/microsoft/winget-pkgs/issues/64458

**Closed** 2022-07-08 19:19 UTC
Labels: Resolution-Duplicate
