### ISSUE TITLE
Provide a --keep-going or make download errors non-fatal for 'winget upgrade --all'

### ISSUE THREAD

**Issue by exoosh** [microsoft/winget-cli#2266] opened 2022-06-21 08:27 UTC
### Description of the new feature / enhancement

When using `winget upgrade --all` the mere failure to download an item results in abort. Example:

```
(1/23) Found SumatraPDF [SumatraPDF.SumatraPDF] Version 3.4.6
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://www.sumatrapdfreader.org/dl/rel/3.4.6/SumatraPDF-3.4.6-64-install.exe
An unexpected error occurred while executing the command:
Download request status is not success.
0x801901f4 : Internal server error (500).
```

Given that the download error may be 1.) temporary and 2.) could happen on any which of the upgradable items it seems odd to abort based on a single failure within a larger operation. Think about it this way: if it fails on the first item the current outcome is quite different from when it fails on the last.

Curiously, I already had the issue where an installer failed within the larger `winget upgrade --all` operation and the overall operation kept going.

### Proposed technical implementation details

I propose to either offer something along the lines of a `--keep-going` (short `-k`) switch to the `upgrade` subcommand _or_ to ignore download errors within a larger operation.

**Comment by denelon** [comment] 2022-06-21 14:26
This was addressed by:
* #1442 

It has already been included in the 1.3 preview builds and the 1.3 release candidate build.

Duplicate of #1442

**Closed** 2022-06-21 14:26 UTC
Labels: Issue-Feature, Needs-Triage
