### ISSUE TITLE
Winget list sort option

### ISSUE THREAD

**Issue by Silther** [microsoft/winget-cli#3649] opened 2023-09-21 09:22 UTC
### Description of the new feature / enhancement

Allow us to sort WinGet list results alphabetically.

### Proposed technical implementation details

By default it should sort it alphabetically by name (changeable in settings JSON?),
with `--sort <param>` you can specify if it should sort by name, id, version, tag, source etc.
Use descending/ascending change to change the sort order

**Comment by denelon** [comment] 2023-09-21 17:33
Duplicate of #1155

* #1155

**Closed** 2023-09-21 17:33 UTC
Labels: Issue-Feature
