### ISSUE TITLE
Can't show installed app list and can't do upgrade --all

### ISSUE THREAD

**Issue by gavinn212** [microsoft/winget-cli#2016] opened 2022-03-10 22:56 UTC
### Brief description of your issue

Just stop functioning normally and I didn't change any setting. The log is here, it's trying to get from D drive that I don't even have. I don't understand what he is doing. I tried reinstalling by appx command in Powershell and actually, the app installer upgraded today in ms-store but didn't help.

```shell
2022-03-10 17:51:27.251 [CORE] WinGet, version [1.2.10271], activity [{AFB9A8BE-3425-48E2-A909-5EC65283839B}]
2022-03-10 17:51:27.253 [CORE] OS: Windows.Desktop v10.0.22000.556
2022-03-10 17:51:27.253 [CORE] Command line Args: winget  list
2022-03-10 17:51:27.253 [CORE] Package: Microsoft.DesktopAppInstaller v1.17.10271.0
2022-03-10 17:51:27.253 [CORE] IsCOMCall:0; Caller: winget-cli
2022-03-10 17:51:27.267 [CLI ] WinGet invoked with arguments: 'list'
2022-03-10 17:51:27.267 [CLI ] Found subcommand: list
2022-03-10 17:51:27.268 [CLI ] Leaf command to execute: root:list
2022-03-10 17:51:27.269 [CLI ] Executing command: list
2022-03-10 17:51:27.278 [REPO] GetCurrentSourceRefs: Source named 'microsoft.builtin.desktop.frameworks' from origin Default is hidden and is dropped.
2022-03-10 17:51:27.278 [REPO] Default source requested, multiple sources available, adding all to source references.
2022-03-10 17:51:27.278 [REPO] Adding to source references msstore
2022-03-10 17:51:27.278 [REPO] Adding to source references winget
2022-03-10 17:51:27.279 [REPO] Multiple sources available, creating aggregated source.
2022-03-10 17:51:27.279 [REPO] Adding to aggregated source: msstore
2022-03-10 17:51:27.279 [REPO] Sending http GET request to: https://storeedgefd.dsx.mp.microsoft.com/v9.0/information
2022-03-10 17:51:27.771 [REPO] Response status: 200
2022-03-10 17:51:27.771 [REPO] Sending http GET request to: https://storeedgefd.dsx.mp.microsoft.com/v9.0/information
2022-03-10 17:51:27.975 [REPO] Response status: 200
2022-03-10 17:51:27.976 [REPO] Adding to aggregated source: winget
2022-03-10 17:51:28.000 [CORE] Examining extension: PFN = Microsoft.Winget.Source_8wekyb3d8bbwe, ID = IndexDB
2022-03-10 17:51:28.001 [CORE] Found matching extension.
2022-03-10 17:51:28.063 [REPO] Opening SQLite Index for ImmutableRead at 'C:\Program Files\WindowsApps\Microsoft.Winget.Source_2022.310.2318.109_neutral__8wekyb3d8bbwe\Public\index.db'
2022-03-10 17:51:28.063 [SQL ] Opening SQLite connection: 'file:/C:/Program Files/WindowsApps/Microsoft.Winget.Source_2022.310.2318.109_neutral__8wekyb3d8bbwe/Public/index.db?immutable=1' [1, 40]
2022-03-10 17:51:28.064 [REPO] Opened SQLite Index with version [1.3], last write [2022-03-10 17:18:53.000]
2022-03-10 17:51:28.146 [REPO] Creating PredefinedInstalledSource with filter [None]
2022-03-10 17:51:28.146 [REPO] Creating new SQLite Index [4294967295.4294967295] at ':memory:'
2022-03-10 17:51:28.146 [SQL ] Opening SQLite connection: ':memory:' [6, 0]
2022-03-10 17:51:28.191 [REPO] Examining ARP entries for Machine | X64
2022-03-10 17:51:28.255 [REPO] Examining ARP entries for Machine | X86
2022-03-10 17:51:28.371 [REPO] Examining ARP entries for User | X64
2022-03-10 17:51:28.431 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(184)\WindowsPackageManager.dll!00007FFCBF7D2465: (caller: 00007FFCBF7CEC83) Exception(1) tid(1824) 800700B7 Cannot create a file when that file already exists.


2022-03-10 17:51:28.431 [REPO] Ignoring duplicate ARP entry User|X64|网易有道词典 [网易有道词典]
2022-03-10 17:51:29.274 [REPO] Opening SQLite Index for ReadWrite at 'C:\Users\10951\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\StoreEdgeFD\installed.db'
2022-03-10 17:51:29.274 [SQL ] Opening SQLite connection: 'C:\Users\10951\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\StoreEdgeFD\installed.db' [2, 0]
2022-03-10 17:51:29.277 [REPO] Opened SQLite Index with version [1.3], last write [2022-03-10 17:10:14.000]
2022-03-10 17:51:29.332 [REPO] Opening SQLite Index for ReadWrite at 'C:\Users\10951\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Microsoft.Winget.Source_8wekyb3d8bbwe\installed.db'
2022-03-10 17:51:29.332 [SQL ] Opening SQLite connection: 'C:\Users\10951\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Microsoft.Winget.Source_8wekyb3d8bbwe\installed.db' [2, 0]
2022-03-10 17:51:29.335 [REPO] Opened SQLite Index with version [1.3], last write [2022-03-10 17:33:07.000]
2022-03-10 17:51:29.990 [REPO] Found multiple matches for installed package [Riot Game league_of_legends.live] in source [Microsoft.Winget.Source_8wekyb3d8bbwe] when searching for [Query:[none] Include:ProductCode='riot game league_of_legends.live'[Exact] Include:NormalizedNameAndPublisher='leagueoflegends'+'riotgames'[Exact]]
2022-03-10 17:51:29.990 [REPO]   Checking match with package id: RiotGames.LeagueOfLegends.OC1
2022-03-10 17:51:29.990 [REPO]   Checking match with package id: RiotGames.LeagueOfLegends.NA
2022-03-10 17:51:29.990 [REPO]   Found multiple packages with strong match fields
2022-03-10 17:51:29.990 [REPO]   Appropriate available package could not be determined
2022-03-10 17:51:30.232 [REPO] Did not find a Version {  }
2022-03-10 17:51:30.232 [REPO] Did not find a Version {  }
```

### Steps to reproduce

winget list shows nothing
winget upgrade AND winget upgrade -all shows nothing

### Expected behaviour

show installed list / upgradable list

### Actual behaviour

show nothing

### Environment

```shell
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.556
Package: Microsoft.DesktopAppInstaller v1.17.10271.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by JohnMcPMS** [comment] 2022-03-11 22:50
I think this might be fixed by #1880 which is available already in https://github.com/microsoft/winget-cli/releases/tag/v1.3.431

**Comment by denelon** [comment] 2022-03-12 01:00
@gavinn212 can you confirm?

**Comment by gavinn212** [comment] 2022-03-13 02:44
Just applied for the preview program, and so far the ms store can't even show the "run" button. I will wait to tomorrow to double-check if the update for preview version gonna show up

**Comment by JohnMcPMS** [comment] 2022-03-16 21:30
I don't see any reported crashes that aren't the issue that was fixed in 1.3.  Do you see any Application Crashing Events in the Event Viewer?  Under `Windows Logs` > `Application`, if there are any for winget.exe it would help if you could copy the contents of the Application Error event as well as the `Hashed bucket` from the bottom of the Windows Error Reporting event assoicated with it (shortly afterward in time).

**Comment by gavinn212** [comment] 2022-03-16 22:28
Is this what you looking for?

General:
```shell
Faulting application name: winget.exe, version: 1.18.2202.12001, time stamp: 0x62089478
Faulting module name: WindowsPackageManager.dll, version: 1.18.2202.12001, time stamp: 0x62089421
Exception code: 0xc0000005
Fault offset: 0x000000000012b515
Faulting process ID: 0x427c
Faulting application start time: 0x01d839845cb4f5ca
Faulting application path: C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.18.431.0_x64__8wekyb3d8bbwe\winget.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.18.431.0_x64__8wekyb3d8bbwe\WindowsPackageManager.dll
Report ID: a230f9ca-9f42-408a-8862-eb63227ce3a3
Faulting package full name: Microsoft.DesktopAppInstaller_1.18.431.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: winget
```
Details:
```shell
[-](https://github.com/microsoft/winget-cli/issues/2016#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/microsoft/winget-cli/issues/2016#) <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2022[-](https://github.com/microsoft/winget-cli/issues/2016#)03-16T22:23:05.6404427Z" /> 
  <EventRecordID>28517</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="13756" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>Gavin-Surface</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>winget.exe</Data> 
  <Data>1.18.2202.12001</Data> 
  <Data>62089478</Data> 
  <Data>WindowsPackageManager.dll</Data> 
  <Data>1.18.2202.12001</Data> 
  <Data>62089421</Data> 
  <Data>c0000005</Data> 
  <Data>000000000012b515</Data> 
  <Data>427c</Data> 
  <Data>01d839845cb4f5ca</Data> 
  <Data>C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.18.431.0_x64__8wekyb3d8bbwe\winget.exe</Data> 
  <Data>C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.18.431.0_x64__8wekyb3d8bbwe\WindowsPackageManager.dll</Data> 
  <Data>a230f9ca-9f42-408a-8862-eb63227ce3a3</Data> 
  <Data>Microsoft.DesktopAppInstaller_1.18.431.0_x64__8wekyb3d8bbwe</Data> 
  <Data>winget</Data> 
  </EventData>
  </Event>
```

**Comment by JohnMcPMS** [comment] 2022-03-17 21:35
Thanks, your crash is different and while I'm not sure exactly why it is happening from the data I have, we can mitigate it.

For me or anyone else in the future fixing this, the problem is a null installed version in the composite source search:
https://github.com/microsoft/winget-cli/blob/fa7409ddea676b732309e476c57453006a079c46/src/AppInstallerRepositoryCore/CompositeSource.cpp#L733

We should log and skip packages in this state.

**Closed** 2022-03-24 16:54 UTC
Labels: In-PR, Issue-Bug, Needs-Attention
