### ISSUE TITLE
winget pin list --id flag seems to be nonfunctional

### ISSUE THREAD

**Issue by philixx93** [microsoft/winget-cli#4845] opened 2024-10-02 08:33 UTC
### Brief description of your issue

Tried limiting the search results of `winget pin list` using the `--id` flag. No matter what I set, the result remains the same.

### Steps to reproduce

Powershell: 7.4.5
OS: Windows 10.0.19045
Winget: 1.8.1911

Pin an app eg `winget pin add  --id "Amazon.Corretto.17.JDK"`
Verify `winget pin list`
Try restricting the search `winget pin list --id "sdfdsfsdfdsf"`

### Expected behavior

`winget pin list` returning all pinned apps
`winget pin list --id "Amazon.Corretto.17.JDK"` returns only that one package if it is pinned
`winget pin list --id "sdfdsfsdfdsf"` returning an empty list because the ID is bogus

### Actual behavior

`winget pin list` 
`winget pin list --id "Amazon.Corretto.17.JDK"` 
`winget pin list --id "sdfdsfsdfdsf"` 

All returning the same

![image](https://github.com/user-attachments/assets/72d714c2-0162-42ae-bfc8-da953df0c6ca)

### Environment

```shell
Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.4894
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

**Comment by denelon** [comment] 2024-10-02 15:28
Duplicate of #4340

**Closed** 2024-10-02 15:29 UTC
