### ISSUE TITLE
Error 0x80190194 When Updating Applications

### ISSUE THREAD

**Issue by McJones9631** [microsoft/winget-cli#4471] opened 2024-05-11 16:56 UTC
### Brief description of your issue

I am attempting to run `winget update --all` to update my applications. I have reset my sources and restarted my machine to the same issue.

### Steps to reproduce

`winget update --all`, `winget update --all --accept-package-agreements`

### Expected behavior

Applications would reinstall and update successfully.

### Actual behavior

`An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).`

### Environment

```shell
Windows Package Manager v1.7.11261
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.4355
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.11261.0
```

**Comment by Trenly** [comment] 2024-05-12 12:32
* Duplicate of https://github.com/microsoft/winget-pkgs/issues/152915

**Closed** 2024-05-12 12:33 UTC
