### ISSUE TITLE
Unable to uninstall and reinstall certain packages - Winget metadata in corrupted state. 

### ISSUE THREAD

**Issue by devholland** [microsoft/winget-cli#3458] opened 2023-07-20 22:50 UTC
### Brief description of your issue

I'm unable to uninstall and reinstall the packages `cURL.cURL` and `dandavison.delta`, which I installed a few weeks ago via `winget install [...]`.

When I try to run e.g. `winget uninstall cURL.cURL`, then the process stops at `Starting package uninstall...` and won't ever finish, no matter how long I wait. I have to use <CTRL-C> to cancel the process.

```
$ winget uninstall curl.curl
Found cURL [cURL.cURL]
Starting package uninstall...
```

The application itself seems to be uninstalled, but both `winget list` and the `Add or remove programs` dialog of the Control Panel still shows the package as installed.

When I try to reinstall the package with `winget install --force cURL.cURL`, the same thing happens: the process stops at `Starting package install...` and won't ever finish. There I have to use <CTRL-C> as well to exit the process.

```
$ winget install --force curl.curl
Found cURL [cURL.cURL] Version 8.1.2
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
``` 

Now, I can neither fully uninstall nor reinstall both packages `cURL.cURL` and `dandavison.delta`. What can I do to repair the corrupted state, that my winget is currently in?

### Steps to reproduce

1. Install cURL via `winget install cURL.cURL`
2. Uninstall cURL via `winget uninstall cURL.cURL`
3. Reinstall cURL via `winget install --force cURL.cURL`

Both `uninstall` and `reinstall` won't work anymore.

### Expected behavior

The packages can be fully uninstalled and won't show up anymore with `winget list` and the `Add or remove programs` dialog of the Control Panel.

### Actual behavior

Winget hangs at `Starting package uninstall...` and `Starting package install...` and won't finish the task. The `winget uninstall` results in corrupted metadata, because the packages still show up with `winget list`.

### Environment

```shell
$ winget --info
Windows Package Manager v1.5.1881
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1992
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.1881.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by mdanish-kh** [comment] 2023-07-21 04:33
This looks to be a duplicate of #3279; Can you try the workarounds listed in that issue to see if they solve the problem?

**Comment by mdanish-kh** [comment] 2023-07-21 04:34
[Policy] Portable

**Comment by devholland** [comment] 2023-07-21 14:39
Yes, it looks like it. I'll try the workarounds and report back here.

**Comment by devholland** [comment] 2023-07-21 15:46
I tried the manual removal of the packages as described in https://github.com/microsoft/winget-cli/issues/3279 and it worked. I can now install and uninstall the packages without issues again. Thank you.

**Comment by mdanish-kh** [comment] 2023-07-21 16:14
Glad to hear it! I'll close this issue in favor of that one for tracking purposes

Duplicate of #3279

**Closed** 2023-07-21 16:15 UTC
Labels: Issue-Bug, Portable
