### ISSUE TITLE
Multiple packages with identical ID's.

### ISSUE THREAD

**Issue by deadundead** [microsoft/winget-cli#902] opened 2021-04-26 13:10 UTC
# Brief description of your issue

Cannot install windows terminal due to identical IDs.
# Steps to reproduce
Run
` winget install Microsoft.WindowsTerminal`

# Expected behavior
Installation of Windows Terminal

# Actual behavior

```
C:\WINDOWS\system32> winget install -e Microsoft.WindowsTerminal
Multiple packages found matching input criteria. Please refine the input.
Name             Id
------------------------------------------
Windows Terminal Microsoft.WindowsTerminal
Windows Terminal Microsoft.WindowsTerminal
```

# Environment

```
Windows Package Manager v0.3.11102 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.962
Package: Microsoft.DesktopAppInstaller v1.11.11102.0

```

**Comment by denelon** [comment] 2021-04-26 16:25
@deadundead, this happens when there are two identical package identifiers in two different sources.

You will need to specify the source to disambiguate.

`winget install Microsoft.WindowsTerminal -e -s winget` would use the "default" source.

It looks like we need to clarify the messaging, and display the sources in this case.

**Comment by jedieaston** [comment] 2021-04-27 21:10
Possible duplicate of #840.

**Comment by denelon** [comment] 2021-04-27 22:11
Duplicate of #840

**Closed by denelon** 2021-04-27 22:11 UTC
Labels: Issue-Feature
