### ISSUE TITLE
WinGet source update failes

### ISSUE THREAD

**Issue by BlockyTheDev** [microsoft/winget-cli#3963] opened 2023-12-08 23:23 UTC
### Brief description of your issue

Winget failes at updating the source `winget` with the message `Abgebrochen (== `Cancelled`)`, the source `msstore` is working without problems. A reinstallation didn't help.

[WinGet-2023-12-09-00-16-31.196.log](https://github.com/microsoft/winget-cli/files/13621684/WinGet-2023-12-09-00-16-31.196.log)

### Steps to reproduce

1. Execute the command `winget source update`
2. Look at the result message

### Expected behavior

The source updates for the source `winget` aren't failing.

### Actual behavior

Winget failes at updating the source `winget` with the message `Abgebrochen (== `Cancelled`)`.

### Environment

```shell
Windows-Paket-Manager v1.6.3133
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.22631.2792
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.21.3133.0

WinGet-Verzeichnisse
-----------------------------------------------------------------------------------------------------------------------
Protokolle                                   %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\Local…
Benutzereinstellungen                        %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\Local…
Verzeichnis für portierbare Links (Benutzer) %LOCALAPPDATA%\Microsoft\WinGet\Links
Portables Linkverzeichnis (Computer)         C:\Program Files\WinGet\Links
Portierbarer Paketstamm (Benutzer)           %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portierbarer Paketstamm                      C:\Program Files\WinGet\Packages
Portierbares Paketstamm (x86)                C:\Program Files (x86)\WinGet\Packages
Installationsprogrammdownloads               %USERPROFILE%\Downloads

Links
-----------------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store-Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale

Administratoreinstellung                  Status
-----------------------------------------------------
LocalManifestFiles                        Deaktiviert
BypassCertificatePinningForMicrosoftStore Deaktiviert
InstallerHashOverride                     Deaktiviert
LocalArchiveMalwareScanOverride           Deaktiviert
```

**Comment by PinkSerenity** [comment] 2023-12-08 23:52
Try [https://cdn.winget.microsoft.com/cache](https://cdn.winget.microsoft.com/cache). If it doesn't work and returns an error or downloads a file with a size of 0 Bytes, then it's the CDN acting up again (at least from what I've gathered looking at past issues). I hope it gets resolved, because this is what I see:

This XML file does not appear to have any style information associated with it. The document tree is shown below.

---
```
<Error>
    <script/>
    <Code>ResourceNotFound</Code>
    <Message>The specified resource does not exist. RequestId:a78487da-f01e-004c-7030-2a6e78000000 Time:2023-12-08T23:43:24.3585981Z</Message>
</Error>
```

**Comment by denelon** [comment] 2023-12-09 00:59
Try uninstalling and reinstalling the source.
`winget uninstall Microsoft.Winget.Source_8wekyb3d8bbwe`
Then run `winget source reset --force` as an administrator.

**Comment by trparky** [comment] 2023-12-09 01:22
It's 0 Bytes here, the CDN is broken again.

**Comment by amnweb** [comment] 2023-12-09 09:05
Yeah same here, two days winget does not work, it's something that shouldn't happen often, MS really should monitoring this CDN

**Comment by grubeninspekteur** [comment] 2023-12-09 11:01
Would be great if Winget caught this error and printed something like "malformed package". Or at least print the URL it's downloading from and the number of bytes like `apt update` does.

**Comment by amnweb** [comment] 2023-12-09 11:09
Or give us the option to change the mirror/source or country, because via VPN winget works now.

**Comment by BlockyTheDev** [comment] 2023-12-09 12:18
> Try https://cdn.winget.microsoft.com/cache/source.msix. If it doesn't work and returns an error or downloads a file with a size of 0 Bytes (as it does for me), then it's the CDN acting up again (at least from what I've gathered looking at past issues).

File size of 0 Byte



> Try uninstalling and reinstalling the source. `winget uninstall Microsoft.Winget.Source_8wekyb3d8bbwe` Then run `winget source reset --force` as an administrator.

Same error

**Comment by trparky** [comment] 2023-12-09 12:39
> Yeah same here, two days winget does not work, it's something that shouldn't happen often, MS really should monitoring this CDN

I agree. This is Microsoft here, not some two-bit little company that only has four or five people working for it; this is a global company and if Microsoft expects WinGet to become nothing more than some little hobby project, they need to take it a hell of a lot more serious than they have been.

Come on Microsoft, fix this!

**Comment by MichelMichels** [comment] 2023-12-09 12:58
Same issue here in Belgium. I don't know if this is geographically related.

**Comment by trparky** [comment] 2023-12-09 12:59
Nope, I'm in the US.

**Comment by PinkSerenity** [comment] 2023-12-10 01:23
It's resolved on my end. Interestingly, the WinGet executable that's shipped with [marticliment/WingetUI](https://github.com/marticliment/WingetUI) has worked all the time.

**Comment by BlockyTheDev** [comment] 2023-12-10 13:41
On my side it is fixed, too. I will leave this open as it got the label "Issue-Bug" and I think there should be done something to avoid a so long location-dependent downtime especially in such a big company and/or a better information message instead of the general message that the source couldn't be updated.

**Comment by datdeep** [comment] 2023-12-17 08:12
You can also try the solution in the comment below if none of the other solutions work: https://github.com/microsoft/winget-cli/issues/3652#issuecomment-1857455714

**Comment by amnweb** [comment] 2023-12-17 12:41
> You can also try the solution in the comment below if none of the other solutions work: [#3652 (comment)](https://github.com/microsoft/winget-cli/issues/3652#issuecomment-1857455714)

I believe here it's not a problem on our side, because this domain already resolved with the correct IP. The problem is with the CDN and cache.

**Comment by datdeep** [comment] 2023-12-18 15:57
> > You can also try the solution in the comment below if none of the other solutions work: [#3652 (comment)](https://github.com/microsoft/winget-cli/issues/3652#issuecomment-1857455714)
> 
> I believe here it's not a problem on our side, because this domain already resolved with the correct IP. The problem is with the CDN and cache.

I don't know why but if I turn on WARP VPN or edit host file, everything works normally. Don't know if Microsoft add Vietnam to blocked list 🤣

**Comment by denelon** [comment] 2024-03-06 19:23
I believe this issue has been resolved and was related to CDN issues we were having in the past.

**Closed by denelon** 2024-03-06 19:23 UTC
Labels: Issue-Bug

**Comment by huyz** [comment] 2024-08-18 08:33
@denelon It has not been resolved. This is very simple: all a Microsoft employee needs to repro is to try this from a Vietnam IP: `winget source update winget`.

It's been years. Please, fix this

**Comment by huyz** [comment] 2024-08-18 08:56
Hey everyone in Vietnam, try FPT instead of Viettel.  The FPT connection to Microsoft's CDN works without VPN.

(I don't know about VNPT.)
