### ISSUE TITLE
Command "show" shows completely wrong result

### ISSUE THREAD

**Issue by cnshenj** [microsoft/winget-cli#1555] opened 2021-10-06 20:54 UTC
# Brief description of your issue

Command "show" shows completely wrong result.
# Steps to reproduce

Run `winget show -q Microsoft.VisualStudioCode --id -e`.
It requires an exact match of package ID.
# Expected behavior
Shows the Microsoft.VisualStudioCode package

# Actual behavior

Shows the "Microsoft Photos" package, whose ID (9WZDNCRFJBH4) is completely different from the query.

![image](https://user-images.githubusercontent.com/8441956/136281616-db712bc2-acce-4f44-acef-1d718cd0cf19.png)

# Environment
Windows 11 Enterprise
```none
[winget --info]
Windows Package Manager v1.1.12663
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.194
Package: Microsoft.DesktopAppInstaller v1.16.12663.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by denelon** [comment] 2021-10-06 23:49
Duplicate of #1523 

Related to #1524

**Closed by denelon** 2021-10-06 23:49 UTC
Labels: Needs-Triage
