### ISSUE TITLE
In order to automate installation and updates of packages it would be nice to have standarized versioning in repostiory.

### ISSUE THREAD

**Issue by kaylashields86** [microsoft/winget-cli#656] opened 2020-12-01 17:29 UTC
In order to automate installation and updates of packages it would be nice to have standarized versioning in repostiory.

To check if a package has been updated in repository and if an update should be triggered, a comparison of installed and avalaible versions would be preferable.
I use the System.Version class to do this (seems the correct way). But some packages currently use strange version strings. e.g. Windscibe:
	Name       Id                    Version
	----------------------------------------------
	Windscribe Windscribe.Windscribe 1.83 Build 18

A rule to enforce standarized versioning would make package handling so much easier...
**major.minor.build.revision**

**Environment:**
PS E:\> winget --info
Windows Package Manager v0.1.41331 Vorschau
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19041.264
Package: Microsoft.DesktopAppInstaller v1.0.41331.0

_Originally posted by @KorbenDev in https://github.com/microsoft/winget-cli/discussions/284_

**Comment by jedieaston** [comment] 2020-12-01 23:02
The problem with this is that just about every Windows developer decides to put something different in that box, and enforcing a required versioning system would probably not get many takers (they'd rather just not have manifests). 

We could version manifests, as was suggested in #284. However, winget is designed to be able to upgrade software regardless of whether or not you installed it from winget in the first place (since many people impulse download software from the developer directly and then need an update later), so it may not be able to figure out whether the package is old or not (unless the version number is reliable). So it has to be able to trust the version number on the system at least a little bit (although at least for MSIs it can also check to see if the ProductCode is different, as that means the software installed and the software in the repo are different). Of course, we also run into the problem that some installers are updated regularly and the vendors don't provide the previous installer, so many of the manifests have "version: latest" (which doesn't help at all when you are trying to decide whether or not to update, unless again you get lucky and can check the ProductCode). 

I think the long-term solution to this is for Microsoft to give developers a year of MSDN free in exchange for a pinky swear that they will only package software for Windows inside of MSIs or MSIXs, but that probably isn't that popular :P

**Comment by megamorf** [comment] 2020-12-01 23:08
This is literally a duplicate of #284 so if you want to bump that issue, please comment on the original one instead of creating a redundant ticket that will get closed for being a clone of an existing issue.

/cc @denelon

**Comment by denelon** [comment] 2020-12-01 23:44
Duplicate of #284

**Closed by denelon** 2020-12-01 23:44 UTC
Labels: Needs-Triage
