### ISSUE TITLE
Add index number or arrow up/down actoin for multi result

### ISSUE THREAD

**Issue by hantsy** [microsoft/winget-cli#1716] opened 2021-11-16 05:25 UTC
### Description of the new feature / enhancement

Due to #1715, I would like to use an interactive approach to select the available options for multi results.

* Add a position number for every option, allow user input one to select it
* Add arrow up/down action to select one directly, highlight the selected item, hit enter to confirm it.

**Comment by denelon** [comment] 2021-11-16 16:51
@hantsy this might be a duplicate issue, but I wasn't able to find it with a quick search. If I find it I'll resolve this as a duplicate so the 👍 values we use to help prioritize can be merged into a single issue.

**Comment by jedieaston** [comment] 2021-11-18 16:08
Were you looking for https://github.com/microsoft/winget-cli/issues/1620?

**Comment by denelon** [comment] 2021-11-18 17:49
I've attempted to make it possible for moderators to close duplicates using the "Duplicate of" "#" "XXXX" syntax. (written strangely to avoid regex triggering here. If a moderator would test I'd appreciate it.

@ImJoakim 
@ItzLevvie 
@jedieaston 
@KaranKad 
@OfficailEsco 
@quhxl

**Comment by vedantmgoyal2009** [comment] 2021-11-18 17:56
Duplicate of #1620

**Comment by ImJoakim** [comment] 2021-11-18 17:57
Duplicate of #1620

**Closed by ImJoakim** 2021-11-18 17:57 UTC
Labels: Issue-Feature
