### ISSUE TITLE
Package ids should be unique/case insensitive

### ISSUE THREAD

**Issue by KorbenDev** [microsoft/winget-cli#293] opened 2020-05-22 15:00 UTC
Package ids should be unique and case insensitive.
Otherwise you get package listings like these:

```
PS E:\> winget search gimp
Name Id        Version Matched
------------------------------------
GIMP gimp.gimp 2.10.8  Moniker: gimp
GIMP GIMP.GIMP 2.10.18 Tag: gimp
```

```
PS E:\> winget search coretemp
Name     Id             Version
--------------------------------
CoreTemp alcpu.coretemp 1.15.1.0
CoreTemp alcpu.CoreTemp 1.15.1
```
**Enrionment:**
PS E:\> winget --info
Windows Package Manager v0.1.41331 Vorschau
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19041.264
Package: Microsoft.DesktopAppInstaller v1.0.41331.0

Links:
  Privacy Statement: https://aka.ms/winget-privacy
  License agreement: https://aka.ms/winget-license
  3rd Party Notices: https://aka.ms/winget-3rdPartyNotice
  Homepage:          https://aka.ms/winget

**Comment by KevinLaMS** [comment] 2020-05-23 01:55
Looks like a dupe of 252.  Please upvote
Duplicate of #252

**Closed by KevinLaMS** 2020-05-23 01:55 UTC
Labels: Issue-Bug
