### ISSUE TITLE
Version number for MS Store source should use real number but not latest.

### ISSUE THREAD

**Issue by lychichem** [microsoft/winget-cli#695] opened 2021-01-09 02:27 UTC
As you can see, the version number listed here is `latest`, but your app uses `xxx.xxx.xxx.x`, the two number is not the same so winget believes there is an update but actually not. So, to solve this problem, version number for MS store source should also use numbers but not `latest`.
![image](https://user-images.githubusercontent.com/9316590/104080815-579ccb00-5265-11eb-8ac8-336fb86b90c3.png)

_Originally posted by @lychichem in https://github.com/microsoft/winget-cli/issues/693#issuecomment-757080555_

**Comment by denelon** [comment] 2021-01-11 16:19
Duplicate of #693

**Closed by denelon** 2021-01-11 16:19 UTC
Labels: Needs-Triage
