### ISSUE TITLE
Possibility to pin a package to installed version or a specific semver

### ISSUE THREAD

**Issue by brainz80** [microsoft/winget-cli#978] opened 2021-05-21 11:47 UTC
# Description of the new feature/enhancement
When running `winget upgrade --all` it would be nice if packages would refer to some set semver rules. Eg. I have Node.JS LTS v. 12.22.1 installed. A newer minor or patch release gets released (eg. 12.23.0). I'd like `--all` to upgrade NodeJS to that version and not the latest.

`winget upgrade --all` loses its meaning if every package has to be upgraded independently to be able to specify a version.

# Proposed technical implementation details (optional)

Maybe add something like Chocolatelys pin. Eg. `winget pin nodejs-lts` to completely pin nodejs to the currently installed version. Or `winget pin nodejs-lts --version 12.x` to specify any major release of 12 is a valid upgrade.

**Comment by denelon** [comment] 2021-05-21 15:06
@brainz80 What you are asking for is possible:

```
PS C:\Users\denelon> winget upgrade -?
Windows Package Manager v0.4.11391 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Upgrades the selected package, either found by searching the installed packages list or directly from a manifest. By default, the query must case-insensitively match the id, name, or moniker of the package. Other fields can be used by passing their appropriate option.

usage: winget upgrade [[-q] <query>] [<options>]

The following arguments are available:
  -q,--query        The query used to search for a package

The following options are available:
  -m,--manifest     The path to the manifest of the package
  --id              Filter results by id
  --name            Filter results by name
  --moniker         Filter results by moniker
  -v,--version      Use the specified version; default is the latest version
  -s,--source       Find package using the specified source
  -e,--exact        Find package using exact match
  -i,--interactive  Request interactive installation; user input may be needed
  -h,--silent       Request silent installation
  -o,--log          Log location (if supported)
  --override        Override arguments to be passed on to the installer
  -l,--location     Location to install to (if supported)
  --all             Update all installed packages to latest if available

More help can be found at: https://aka.ms/winget-command-upgrade
```

Try `winget upgrade nodejs-lts -version <version>`

We do have the #476 pin feature in the backlog, and #227 a version specific feature to support semantic versioning.

**Comment by denelon** [comment] 2021-05-21 15:06
Duplicate of #476

**Closed by denelon** 2021-05-21 15:06 UTC
Labels: Issue-Feature, Needs-Triage

**Comment by brainz80** [comment] 2021-08-06 08:08
I'm placing a new comment here. What I want isn't what @denelon mentions. Firstly I don't think e.g. `winget upgrade nodejs-lts --version 12.x` works; but what I'm actually looking for is to be able to **pin** a package to e.g. a specific major version and then when running `winget upgrade --all` have that package upgrade accordingly.

E.g. Having `nodejs-lts` version `12.1.1` installed and running `winget pin --all nodejs-lts --version 12.x` should make it so that when later `winget upgrade --all` is ran it'd check if there is a update available for `nodejs-lts` what matches `12.x` - if the latest update is e.g `16.1.1`, but there is also a `12.1.2` it'd update `nodejs-lts` to that version.

I hope this cleared out what I'm looking for.

**Comment by denelon** [comment] 2021-08-06 15:49
I added some clarity to #476. Suggestions in your comment are an intended part of the desired behavior.
