### ISSUE TITLE
-exclude Application from "winget upgrade --all"

### ISSUE THREAD

**Issue by giuseppebin** [microsoft/winget-cli#3851] opened 2023-11-04 03:22 UTC
### Description of the new feature / enhancement

Can we exclude some app from the "winget upgrade --all" please? Maybe some flag for the apps that can be recognised from the upgrade command? thanks.

**Comment by CoolPlayLin** [comment] 2023-11-04 07:07
Hi @giuseppebin 
Maybe use pin command is a better way to do this? If you don't want to update specific software, you could use 'winget pin <package>' command to prevent its updating.

**Comment by Trenly** [comment] 2023-11-04 13:52
To prevent a package being included in `winget upgrade --all` you can pin the package as @CoolPlayLin mentioned above. 

* Duplicate of #476 
* Duplicate of #3268

**Closed** 2023-11-04 13:53 UTC
Labels: Issue-Feature

**Comment by giuseppebin** [comment] 2023-11-05 04:25
> Hi @giuseppebin Maybe use pin command is a better way to do this? If you don't want to update specific software, you could use `winget pin <package>` command to prevent its updating.

oh I'm so sorry... I searched badly for this.

Many thanks.

This command is what i was looking for:
  ` winget pin add <package>`
and the corollary `winget unpin <package>`

thanks to all.

**Comment by bunam** [comment] 2024-03-11 08:35
pinned app aren't excluded

"1 package(s) ont des épingles qui empêchent la mise à niveau. Utilisez la commande « winget pin » pour afficher et modifier les épingles. L’utilisation de l’argument --include-pinned peut afficher plus de résultats."
