### ISSUE TITLE
upgrade using --id does not filter the right match

### ISSUE THREAD

**Issue by baget** [microsoft/winget-cli#1696] opened 2021-11-11 16:10 UTC
### Brief description of your issue

I'm trying to upgrade an application with their unique ID (using --id) shown by winget, but getting error of "Multiple installed packages found matching input criteria. Please refine the input."

```
[D:\Work]> winget upgrade --id "Audacity.Audacity"
Multiple installed packages found matching input criteria. Please refine the input.
Name           Id
--------------------------------
Audacity       Audacity.Audacity
Audacity 2.1.3 Audacity®_is1

```

I had two version of Audacity in "Program and Features" but according to Winget it is two different IDs
if you remove the old one, issue gone away

### Steps to reproduce

try to upgrade Audacity using --id flag:

`winget upgrade --id "Audacity.Audacity"`

### Expected behavior

Upgrade Audacity

### Actual behavior

return error:
"Multiple installed packages found matching input criteria. Please refine the input."

### Environment

```shell
Windows Package Manager v1.1.12701
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.1348
Package: Microsoft.DesktopAppInstaller v1.16.12701.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
Licence Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

I had two version of Audacity in "Program and Features" but according to Winget it is two different IDs
if you remove the old one, issue gone away
```

**Comment by denelon** [comment] 2021-11-11 16:15
Duplicate of #752
We're looking at this specific situation in a couple of other similarly related issues:

* #1413
* #1192
* #1142
* #752

**Closed by denelon** 2021-11-11 16:15 UTC
Labels: Needs-Triage
