### ISSUE TITLE
winget update

### ISSUE THREAD

**Issue by AdilHindistan** [microsoft/winget-cli#191] opened 2020-05-19 17:26 UTC
# Description of the new feature/enhancement

winget install xyz seems to install an app even if that same version is already installed.
There must a distinction for a new install vs an update of an existing version to a newer one. 

* winget update winget             # updates winget to the latest version
* winget update app1, app2      # updates app1 and app2 to their latest versions in repo
* winget update python==3.8.1 # updates currently install python to version 3.8.1, if it exists in the repo
* winget update --all                  # updates all existing packages to their latest version

**Comment by utybo** [comment] 2020-05-19 17:27
This is probably a duplicate of #120

**Comment by KevinLaMS** [comment] 2020-05-21 00:55
Duplicate of #120

**Closed by KevinLaMS** 2020-05-21 00:55 UTC
Labels: Issue-Feature
