### ISSUE TITLE
Add ability to cache installer downloads

### ISSUE THREAD

**Issue by BahKoo** [microsoft/winget-cli#355] opened 2020-05-28 17:35 UTC
# Description of the new feature/enhancement

Scenario: Multiple computers on the same network are installing the same winget packages. Some of these packages involve large downloads. Even if you were to cache the manifests to a local source, the URLs for the installers would still point to an offsite location unless the manifests are manually edited.

Feature Request: easily create a local source of manifests that works with a store of local installers so that every computer on the network does not need to download the same installers from the external source.

I have created a solution for this problem for chocolatey called [ChocolateStore](https://github.com/BahKoo/ChocolateStore). Chocolatey has since created a solution for this in their architect and business tiers called [Package Internalizer](https://chocolatey.org/docs/features-automatically-recompile-packages). Due to the cleaner structure of winget's manifests compared to Chocolatey's powershell scripts, implementing this feature should be more straight forward than those solutions.

**Comment by A9G-Data-Droid** [comment] 2020-07-20 16:14
This could be a feature of the self hosted repository. You would point all computers to your internal repository that would have a forwarder to other repositories. If it doesn't find the package locally it would forward query Microsoft, like DNS, and then cache the packages in the local repository.

**Comment by cheeseandjamsandwich** [comment] 2021-06-09 05:17
PatchMyPC also has this feature.  To save the downloaded installers.

It also has the feature to only download the selected installers, but not install them.  Which is useful for prepping everything needed for installation on other machines, and may be offline.  The sysadmin shouldn't have to install every software on their pc.

We really should be aiming to prevent duplicate downloads of the same files as much as pos.  Data costs $/time/carbon.

I Always maintain a local/shared cache folder and USB stick of every installer.  This is automatically updated by PMPC each time it runs.

My only job is to weed out the old versions to save space.  Which is totally acceptable.

**Comment by VAllens** [comment] 2022-03-28 02:01
Good idea.
I believe people need it

**Comment by vedantmgoyal2009** [comment] 2022-09-19 16:03
* @denelon duplicate of https://github.com/microsoft/winget-cli/issues/343

**Comment by denelon** [comment] 2022-09-19 16:16
Duplicate of #343

**Closed by denelon** 2022-09-19 16:16 UTC
Labels: Issue-Feature
