### ISSUE TITLE
Winget upgrade does not detect the correct version of an installed package

### ISSUE THREAD

**Issue by trebuh** [microsoft/winget-cli#3883] opened 2023-11-13 14:38 UTC
### Brief description of your issue

Winget does not detect that the latest version of Microsoft Visual C++ 2015-2019 Redistributable (x86) is already installed.

Hence, `winget upgrade --all` always reinstall it.

### Steps to reproduce

```
PS C:\WINDOWS\system32> winget install --id=Microsoft.VCRedist.2015+.x64 -e

Found Microsoft Visual C++ 2015-2022 Redistributable (x64) [Microsoft.VCRedist.2015+.x64] Version 14.38.32919.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.visualstudio.microsoft.com/download/pr/02a6d5c5-3e10-47de-8025-d97a1321d3e3/5F60592799FAE0C82578112D4B621438FFC976AB39D848D8F7623F5705A83E27/VC_redist.x64.exe
  ██████████████████████████████  24.1 MB / 24.1 MB
Successfully verified installer hash
Starting package install...
Successfully installed

PS C:\WINDOWS\system32> winget upgrade --all

Name                                                               Id                           Version       Available     Source
----------------------------------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015-2019 Redistributable (x86) - 14.27.29112 Microsoft.VCRedist.2015+.x64 14.27.29112.0 14.38.32919.0 winget
1 upgrades available.

Installing dependencies:
(1/1) Found Microsoft Visual C++ 2015-2022 Redistributable (x64) [Microsoft.VCRedist.2015+.x64] Version 14.38.32919.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.visualstudio.microsoft.com/download/pr/02a6d5c5-3e10-47de-8025-d97a1321d3e3/5F60592799FAE0C82578112D4B621438FFC976AB39D848D8F7623F5705A83E27/VC_redist.x64.exe
  ██████████████████████████████  24.1 MB / 24.1 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

### Expected behavior

The correct version should be detected, and `winget upgrade --all` should not yield any action.

### Actual behavior

`winget upgrade --all` always install Microsoft Visual C++ 2015-2019 Redistributable (x86)

### Environment

```shell
Windows Package Manager v1.6.2771
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.3570
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.2771.0
```

**Comment by denelon** [comment] 2023-11-13 16:28
Duplicate of #3737

**Closed** 2023-11-13 16:28 UTC
Labels: Needs-Triage
