### ISSUE TITLE
Using WinGet to install package from Windows Terminal in Non-Admin mode causes Command-line alias creation to silently fail

### ISSUE THREAD

**Issue by philip-young** [microsoft/winget-cli#3436] opened 2023-07-14 17:15 UTC
### Brief description of your issue

I tried to install mkcert from winget using the Windows Terminal in non-Admin mode. It seems that even though the package was created successfully, the line indicating that a command line alias was created didn't work. I double checked my PATH environment variable and that correctly was created and pointed to the path of where the package was installed, but when I tried to run the package using the alias 'mkcert' I got an error indicating it couldn't be found.

Eventually I tried running Windows Terminal in Administrator mode and reinstalled the package and it worked.

![image](https://github.com/microsoft/winget-cli/assets/62968356/64d95988-b7e1-4bfe-81e9-f8f794f53a9e)

### Steps to reproduce

In Windows Terminal (non Admin):
```winget install mkcert```
Install successful and command line alias added.
Restart Terminal to load new environment variables.

```mkcert```

(error not found)

### Expected behavior

using the mkcert alias from the command line works successfully.

### Actual behavior

the newly installed package is not found when using the alias, but when using the package name mkcert-xxx-windows-amd64.exe it is found.

### Environment

```shell
Windows Package Manager v1.5.1572
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1848
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.1572.0
```

**Comment by mdanish-kh** [comment] 2023-07-14 17:24
This is because the exe full name is `mkcert-v1.4.4-windows-amd64.exe` and looks like WinGet doesn't rename portables in non-symlinked installations. Not sure if this bug is being tracked separately here in the CLI.

Similar case to https://github.com/microsoft/winget-pkgs/issues/111454 

[Policy] Portable

**Comment by mdanish-kh** [comment] 2023-07-14 17:56
I'll mark this as duplicate of the newly created issue for better tracking of the underlying issue

**Closed** 2023-07-14 17:56 UTC
Labels: Needs-Triage, Portable
