### ISSUE TITLE
`--include-unknown` does not work

### ISSUE THREAD

**Issue by colejohnson66** [microsoft/winget-cli#3477] opened 2023-07-27 13:49 UTC
### Brief description of your issue

As shown in the screenshot, the `--include-unknown` flag does not work. I ran a normal upgrade with `winget upgrade --all`, and, at the end was informed that "32 package(s) have version numbers that cannot be determined." As instructed, I used `--include-unknown` to list them, but I got an empty result.

![A screenshot of Windows Terminal showing invocations of `winget upgrade --include-unknown` and `winget upgrade --all --include-unknown`](https://github.com/microsoft/winget-cli/assets/11381599/c7e787c9-5e2a-465d-8929-32182e87edd5)

### Steps to reproduce

Run `winget upgrade --include-unknown` (and optionally with `--all`) and observe an error message.

### Expected behavior

A list of packages (probably mostly Steam apps/games) that have unknown versions.

### Actual behavior

A message informing me that "[n]o installed package found matching [the] input criteria."

### Environment

```shell
Windows Package Manager (Preview) v1.6.1573-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.23506.1000
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.1573.0

Winget Directories                 
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagΓÇª
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settΓÇª
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages

Links               
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by Trenly** [comment] 2023-07-27 15:07
If you run `winget list`, do any of the packages with version `unknown` have ID's have any information in the `Source` column?

**Comment by denelon** [comment] 2023-07-27 17:20
Duplicate of #2458

**Closed** 2023-07-27 17:20 UTC
Labels: Issue-Bug, Command-Upgrade
