### ISSUE TITLE
winget.exe not running on Server 2019

### ISSUE THREAD

**Issue by HtHNightwolf** [microsoft/winget-cli#1251] opened 2021-07-02 06:38 UTC
# Brief description of your issue
winget.exe Application Alias has been installed but winget itself is not there / is not starting

# Steps to reproduce
I installed the Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle on a Server 2019 with latest updates.

At the first attempts not even an Application Alias was created but after several reinstalls, it finally was there in %localappdata%\Microsoft\WindowsApps

So I started PowerShell but it reports winget is not an executable file or a valid program for this operating system

# Expected behavior
I expect it to install and then be able to run it.

# Actual behavior
winget.exe can not be run
Error Messages screenshot:
https://www.dropbox.com/s/j1tlygpej0wple2/winget%20error.png?dl=0

# Environment
Windows Server 2019 latest patch level

```none
[winget --info]
Fehler beim Ausführen des Programms "winget.exe": Die angegebene ausführbare Datei ist keine gültige Anwendung für
diese Betriebssystemplattform.In Zeile:1 Zeichen:1
+ winget --info
+ ~~~~~~~~~~~~~.
In Zeile:1 Zeichen:1
+ winget --info
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed


```

**Comment by rbarbrow** [comment] 2021-07-02 22:06
does server 2019 have the app store?
I don't know that it can even run the app

**Comment by SlimRG** [comment] 2021-07-03 15:56
Firstly, Windows Server 2019 doesn't have Microsoft Sore (you can install it, but somy dependences will not work)
Secondly, WS 2019 has group politics to powershell, so you can't install mlots of powershell apps.
And in the end - Windows Server 2019 has strong app and firewall malware politics which can prevent use from installation or search packages in powershell.
You can bypass these restrictions, if you are able to work with Windows Server. But if you only starts your way in learning Windows Server - you souldn't use winget and other non-standard solutions for this system

**Comment by NicTanghe** [comment] 2021-07-05 13:22
BIt weird that its not adviced to use winget on servers.

**Comment by github-account1111** [comment] 2021-07-06 06:33
> 
> 
> does server 2019 have the app store?
> I don't know that it can even run the app

Isn't winget supposed to ship to all Windows versions 1809 via Windows Update? It'd be a bummer if we had to sign into a Microsoft account just to be able to use it..

**Comment by denelon** [comment] 2021-07-06 19:11
Duplicate of #144

**Closed by denelon** 2021-07-06 19:11 UTC
