### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by svrooij** [microsoft/winget-cli#3518] opened 2023-08-12 21:29 UTC
### Description of the new feature / enhancement

I'm trying to call Winget from a .NET core app, with a new process and then capturing the output.
But the output for the `show` command is translated to the language of the user, with no way to make it always in English.

I would really like a `--json` switch, that would just output the same data but then as Json.

I also though that the --disable-interactivity switch would disable the spinner and the progress bar, but that is not the case. (Not a problem I just capture all the output and strip the progress mess.)

### Proposed technical implementation details

At the same place that writes the translated output, just do a JsonSerialzer.Serialize instead.

Maybe also allow a way to see the commandline switches from the manifest.

For now I'm thinking of just cloning the packages repo and looking up the data myself, but having an automated way would be preferable.

Also I'm not installing packages this way, I'm only interacting with the manifests.

**Comment by Trenly** [comment] 2023-08-12 21:56
* Duplicate of #1753
* Related to #2032

**Closed** 2023-08-12 21:56 UTC
Labels: Issue-Feature
