### ISSUE TITLE
Install and use it out of the box without add to the PATH manually

### ISSUE THREAD

**Issue by andylizf** [microsoft/winget-cli#2943] opened 2023-02-09 04:52 UTC
### Description of the new feature / enhancement

Auto-add the path of the installing package to the env variable `PATH`.
Like in Linux, what you need is just `sudo apt install gcc` and then you can directly use `gcc`.

**Comment by denelon** [comment] 2023-02-09 16:36
Duplicate of #222

**Closed** 2023-02-09 16:36 UTC
Labels: Issue-Feature, Needs-Triage
