### ISSUE TITLE
When do we begin to see the PowerShell cmdlets?

### ISSUE THREAD

**Issue by doctordns** [microsoft/winget-cli#674] opened 2020-12-29 18:10 UTC
# Description of the new feature/enhancement

We have previously asked for good PowerShell cmdlet support from the WinGet project.
The team have agreed and there is a milestone.  This is good!

Thus far, I have seen no progress, no initial thoughts on how this might work, and no detailed object model or suggested commands.
If the team is to meet that milestone commitment then time is running short (although Covid has probably made any older milestones much more "flexible".

# Proposed technical implementation details (optional)

I suggest some draft thoughts and maybe some proto-commands. Not dissimilar to what happened with Hyper-V cmdlets. An early module was published (that was terrible!) but was quickly transformed into a great tool Iand adopted by the Hyper-V team who did an amazing job). Publish the early thinking, and let the PowerShell community help you to do another great job.

**Comment by megamorf** [comment] 2020-12-31 00:36
Duplicate of #221.

**Comment by doctordns** [comment] 2020-12-31 15:57
It is nor really a duplicate. My issue is asking for early work to be published. Issue #221 is asking for the completion of a fully supported PowerShell module.

Of course, both issues are related - but nevertheless where is the progress against #221? The road map says end-April for full PowerShell support. To have a hope of releasing a good version by then, work has to have started (probably a while ago).  This issue is asking the team to expose their thinking one what they plan to deliver (and by when). 

This issue can be closed once and an initial set of cmdlets are ready, or when the 1st draft of their specification is available. 

And for the avoidance of doubt, my goal is to see a great set of cmdlets that enable IT Professionals to manage the underlying winget feature set. To have good cmdlets with all the qualities of PowerShell but thus far lacking in winget.exe is not an easy task.

**Comment by denelon** [comment] 2021-01-02 19:37
As we get "closer" to the feature set intended for 1.0 we will be ready to look at the proper syntax for cmdlets. I'll likely propose some sort of draft via a gist.

**Comment by denelon** [comment] 2021-01-02 19:38
I also believe we will be able to iterate fairly quickly once we have clear scope. We will also need to continue revising the syntax as new features are developed.

**Comment by doctordns** [comment] 2021-01-02 20:19
I realise you may be new to PowerShell and cmdlets. From nearlhy 17 years experience with PowerShell, I can tell you that building a huge .exe with it's attendant infrastructure, and then trying to back port it to be a great PowerShell modules is going to be very hard work. It's not just a few get/set commands. And the more you bake into the exe, with commands switches etc all designed without thought of the IT Pro), the hard it will hard to do a great job.

You need a strong and complete object model. You need to consider how to overrise things via group policy. YOu need to consider format XML.  These things take a log of work, thought, and iteration.

As for iteration, ask the Hyper-V team how much effort it was to build their module.  I suggest you should be thinking along the linds of 2-3 months per iteration and not less. Please do not underestimate the task. 

As I said, If you are to have any hope of even a mediocre sub-optimal module by April, you should have started by now. A great module will take longer.  This stuff does not spring from the earth fully baked. 

For the avoidance of doubt, I want to se a great module to allow IT Professionals to manage packages using this tool.

**Comment by kilasuit** [comment] 2021-01-17 01:25
> 
> 
> As we get "closer" to the feature set intended for 1.0 we will be ready to look at the proper syntax for cmdlets. I'll likely propose some sort of draft via a gist.

Surely a draft PR (which is what they are for) would make better sense than externalising this to a gist

**Comment by doctordns** [comment] 2021-01-17 10:23
Yes. 

A gist is great for a snippet. But as documentation of an important core feature it is wrong. 
The reality is, or at least appears to be, the winget team and the teams management just doesn't want to do Powershell. 
 
I continue to believe this is a possibly a very good power toy, but not a serious tool for enterprise use. Yet.

**Comment by denelon** [comment] 2021-02-03 22:31
We do want to have a PowerShell cmdlet. Our management supports this as well. We're already looking at some refactoring of the code now to make it easier to support this. There are quite a few substantial changes in the works for the client and the services. It's unlikely that we will land PowerShell in the 1.0 release, but we've already started doing the research and some of the work. Once the new manifest schema and service changes have been done, we will be a step closer. We're building JSON Schemas for everything and we're using them to validate all client side and server side components. That should help standardize the models considerably. We're also building a REST API to enable enterprises to have their own source(s). That will require the client to be able to "speak" JSON.

I'm looking forward to the time when we can collaborate to make sure that we're building the right tools for all of our use cases.

**Comment by doctordns** [comment] 2021-02-04 11:19
What that means, in practice, is that there is a much lower likelihood of any PowerShell cmdlets ever. If you do not factor PowerShell into your early thinking, you are going to find, post V1.0, that PowerShell is too difficult.  A REST API and json is not sufficient. At a very minimum, you need some reference cmdlets that perform at least the basic get/list/find/update/remove features for winget in V.3 (IIRC this is was the milestone) or for V1.

If you leave it till post V1, you are much more likely face the need for changes that impact on backwards compatibility. The experience of docker.exe should be all the lessons you need. WIth docker.exe fully baked, there is virtually no way we'll ever see supported product team based cmdets. With Server 2022 just around the corner that continues, nearly 20 years AFTER Monad.

I strongly urge you to rethink this and keep to the original plan of having Cmdlets in the earlier pre-V1 release if only to give you self the time to bake cmdlet architectures into your code from the get go. Once you ship V1, your hands really are tied - I speak as one with nearly 40 years of working with MS products (I started with DOS 1.0a).

Please do not drop cmdlets.

**Comment by kilasuit** [comment] 2021-02-04 12:13
I personally think that PowerShell commands that wrap around the Winget.exe is fine as long as it returns a converted PowerShell object from the output json by default

**Comment by doctordns** [comment] 2021-02-04 13:04
As long as there is 100% fidelity, that works. But I would have expected the cmdlet would implement the REST API directly. Converting the string output from winget to an object model may be challenging.,

**Comment by kilasuit** [comment] 2021-02-04 13:47
Not really, it just needs a type conversion method that takes the json string input and doesn't need to be a super fancy object that is output either (& the simpler it is the easier it is to maintain and keep current)

**Comment by doctordns** [comment] 2021-02-04 13:52
That sounds an incomplete solution. Why not just do not right and do cmdlets from the get-go. As I have said, If MSFT ship winget 1.0 without cmdlets, there probably never will be cmdlets (c/f docker.exe). The dev team are already pushing out PowerShell to post 1.0 by which time it will probably be too late to actually do decent cmdlets. I just do not get why cmdlets are such a big deal here - they are a natural fit for a product that is meant to _manage_ packages.

**Comment by denelon** [comment] 2021-02-04 18:07
Feedback from the community is what landed PowerShell on the roadmap. When I joined the project, it wasn't in any of the scope documents I read. As mentioned earlier, we're already doing some refactoring to ensure we can deliver a PowerShell cmdlet. I wish there were enough resources to deliver all of the features that have been requested in v1.0, but that isn't the current situation.

**Comment by jantari** [comment] 2021-03-31 07:24
> Feedback from the community is what landed PowerShell on the roadmap. When I joined the project, it wasn't in any of the scope documents I read.

That is absolutely insane. Imagine designing a CLI utility but simultaneously _completely_ forgetting the CLI.

Obviously not blaming you or anyone in particular, on the contrary: thanks for the honesry and engagement. I had just really hoped this would finally be the serious package manager Windows has been missing for the last >25 years and not some imprudent throwaway announcement for a quick press hype.

**Comment by doctordns** [comment] 2021-03-31 10:44
Many of the posters on this repo have pointed out the lack of PowerShell cmdlets. As I have said several times here, making good PowerShell cmdlets does not happen by accident or via some magic XML (c/f cmdlts from WMI via .CDXML) files.

The lack of movement on a good PowerShell module is why I do not recommend winget for serious package management.

**Comment by jbrinkman** [comment] 2021-06-01 11:13
It seems crazy that in 2021, people at MS are building CLI projects that are not PowerShell 1st. PowerShell should not be an afterthought when designing a CLI.

**Comment by soroshsabz** [comment] 2021-06-03 10:14
ITNOA

# Description of the new feature/enhancement

As you can know PowerShell is great Scripting Language for Automation and Administration of system. and it is built by Microsoft, so I think it is very good for winget-cli to get compatible with PowerShell and make native PowerShell [Cmdlet](https://docs.microsoft.com/en-us/powershell/scripting/lang-spec/chapter-13?view=powershell-7.1) and make great integration with [OneGet](https://github.com/OneGet/oneget) platform for provide a native and consistent user experience in Microsoft Ecosystem.

In this area we can see below command instead of Linux legacy CLI style like `winget install foo`

`Install-Package foo`
`Update-Package foo`
`Get-Package foo`

And all of them is object and we can work with them in OOP area with modern and great and consistent experience in PowerShell World.

# Proposed technical implementation details (optional)

I think PowerShell has many guideline and documentation about writing and designing great Cmdlet and modules that winget-cli teams have to follow it for example

[Windows PowerShell Cmdlet Concepts](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/windows-powershell-cmdlet-concepts?view=powershell-7.1)
[Writing a Windows PowerShell Module](https://docs.microsoft.com/en-us/powershell/scripting/developer/module/writing-a-windows-powershell-module?view=powershell-7.1)
[PowerShell Script Module Design: Building Tools to Automate the Process](https://mikefrobbins.com/2018/11/01/powershell-script-module-design-building-tools-to-automate-the-process/)
[Powershell: DSL design patterns](https://powershellexplained.com/2017-03-13-Powershell-DSL-design-patterns/)

**Comment by JustSomeGuyNZ** [comment] 2021-08-21 00:41
I just wanted to add another voice of frustration here. I'm frustrated at the current lack of progress in PowerShell support. I'm frustrated that this project was allowed to come into existence without being PowerShell centric. But mostly I'm frustrated because it should have been the answer to so many sysadmins prayers.. but right now it's about as useful as tits on a bull.

**Comment by denelon** [comment] 2021-08-21 01:45
@JustSomeGuyNZ I'm circulating a draft for the proposed cmdlet nouns and verbs with the PowerShell team currently. I wanted to have them take a look to make sure I didn't do something terribly wrong to begin with. As soon as they have given it the once over, I will be posting the draft specification for community review. We're looking at [crescendo](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.crescendo/?view=ps-modules) so we can do some rapid prototyping and then we will implement native interfaces against the COM API.

**Comment by doctordns** [comment] 2021-08-28 10:30
NIce to see some progress against PowerShell cmdlets.

Some questions:
1. Do you intend to use a noun prefix or appropriate the noun 'package'.? There are already 5 cmdlets in the PackageMangement module. Either you just ask the user to load the right module to get, say, the right **Get-Package**. Alternatively and probably preferably, you would use a noun prefix, like **WG** - so **Get-WGPackage**. Using the noun prefix will, I promise you, eliminate many of the issues you would see in the repo otherwise. The Azure team learned this years ago when they tried to ship a single module that did Azure RM and traditional. It caused endless user confusion which was mainly resolved when they separated the modules. Pleae consider using a noun prefix.
2. What verbs will you settle on. With the current winget,m the following commands are not approved verbs: source,     list, upgrade, hash, validate, settings, feature. I trust that you are not planning on using unapproved verbs? I noted a very long time ago that this could be an issue -it was suggested that the 'command' names align with approved verbs.  Please publish the proposed verbs.
3. Property names - what properties are used with cmdlet parameters and what types/names are they? And what are the output types going to be? The object model of input and output objects would be a great first step, as with this, the cmdlets almost name themselves. As has been pointed out. before. Pleaes provide the object model for the input and output objects. PLEASE do not make everything a string or string array. :-)
4.  What GPO-based policy settings are there for the cmdlets. For example, if you have a command like  **Install-WBPackage -Name FOO-Repository "BadRepo"**, I'd have liked by policy to say no, you can not use THAT repo. That would allow the cmdletrs to follow policy and emit a message saying something like "sorry dave I cant do that"... Please publish the detailed policies and policy hive registry locations.

I look forward to seeing the progress here. Some big design questions still need addressing, imho, and I look forward to it.

**Comment by megamorf** [comment] 2021-08-28 10:44
@doctordns  See #1407

**Comment by doctordns** [comment] 2021-08-28 11:50
-Thanks - i have made comments there. Nice to see this finally progressing!

**Comment by soroshsabz** [comment] 2021-09-02 16:37
Some people working around it personally

https://github.com/ethanbergstrom/WinGet

**Comment by doctordns** [comment] 2021-09-02 16:44
That repo hasn't been touched for 18 months or thereabouts. NOt sure how relevant it is today, as Winget itself has changed.

**Comment by doctordns** [comment] 2021-09-15 15:47
I have learned that the Winget team plan to use Crescendo to build their cmdlets, at least at first. This is very interesting and should get cmdlets out faster. The one HUUUUUUUUUUUUUUUUUUUGE challenge will be to get the objects that are output to be really useful. This is an incredible challenge that I do not for a moment underestimate. Naturally, starting with the objects in the first place would have made so much more sense, but we are where we are. I hope that the WInget team can create some good outputters to make the objects really useful.

**Closed** 2021-12-13 15:12 UTC
Labels: In-PR, Issue-Feature
