### ISSUE TITLE
Install from msstore error

### ISSUE THREAD

**Issue by mangkoran** [microsoft/winget-cli#2052] opened 2022-03-30 10:13 UTC
### Brief description of your issue

Install from msstore returns error.
```
Verifying/Requesting package acquisition...
Verifying/Requesting package acquisition failed: server error'
```

### Steps to reproduce

1. `winget install xxxxxx`, change to any msstore package hash (e.g., WA Beta: 9nbdxk71nk08)

### Expected behavior

Package installed

### Actual behavior

Packaged failed to install.
```
Verifying/Requesting package acquisition...
Verifying/Requesting package acquisition failed: server error
```

### Environment

```shell
Windows: Windows.Desktop v10.0.22000.593
Package: Microsoft.DesktopAppInstaller v1.17.10271.0
```

**Comment by mangkoran** [comment] 2022-03-30 23:00
Just now I tried to install it again and now success. Thus, I cannot reproduce the error again. Should it be closed then?

**Comment by denelon** [comment] 2022-03-30 23:36
I'll close it. Be sure to reopen if you see this again.

**Comment by github-account1111** [comment] 2022-08-18 20:29
Getting the same error with a different Store app.
```
winget install `
            --id 9N4WGH0Z6VHQ `
            --accept-package-agreements `
            --accept-source-agreements `
            --silent
```
It does successfully show the package description.

**Comment by denelon** [comment] 2022-08-18 22:07
I was able to reproduce this error. I've reported it to the Microsoft Store team.

**Comment by Mr-Anonymous75** [comment] 2022-08-25 02:14
I've uploaded my logs to pastebin [here](https://pastebin.com/raw/W2je5iY3).

**Comment by sgrienen** [comment] 2022-08-31 12:10
Same here with MS People app:

------------------------
> winget install 9NBLGGH10PG8
Found Microsoft People [9NBLGGH10PG8] Version Unknown
This package is provided through Microsoft Store. winget may need to acquire the package from Microsoft Store on behalf of the current user.
Version: Unknown
Publisher: Microsoft Corporation
Description: People in Windows 10 puts all the ways you connect with all your friends, family, colleagues, and acquaintances in one place, so it’s faster than ever to keep in touch. Check out what your people are up to across the services they use and choose how you want to connect with them.
License: http://go.microsoft.com/fwlink/?LinkID=530144
Privacy Url: http://go.microsoft.com/fwlink/?LinkID=521839
Copyright: © 2015 Microsoft Corporation.
Agreements:
Category: Utilities & tools
Pricing: Free
Free Trial: No
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
Seizure Warning: https://aka.ms/microsoft-store-seizure-warning
Store License Terms: https://aka.ms/microsoft-store-license

The publisher requires that you view the above information and accept the agreements before installing.
Do you agree to the terms?
[Y] Yes  [N] No: y
Verifying/Requesting package acquisition...
Verifying/Requesting package acquisition failed: server error
------------------------

on Windows 11 (MS Account store blocked, corporate policy)

**Comment by sgrienen** [comment] 2022-09-01 08:48
[WinGet-2022-09-01-10-46-25.968.log](https://github.com/microsoft/winget-cli/files/9468285/WinGet-2022-09-01-10-46-25.968.log)

Attached a verbose log file, in case it helps... same issue with Outlook for Windows (preview)

**Comment by River2906** [comment] 2022-09-15 05:22
Also getting the same error with another store app - Attached the winget logs
[WinGet-2022-09-15-15-11-41.641.log](https://github.com/microsoft/winget-cli/files/9572068/WinGet-2022-09-15-15-11-41.641.log)

**Comment by vctrt1** [comment] 2022-10-04 16:41
this did the trick for me:
echo Y | winget install xxxxxxxx

**Comment by geiszla** [comment] 2022-10-08 14:27
I have the same issue with the Amazon Appstore app.
Logs: [WinGet-2022-10-08-16-17-57.822.log](https://github.com/microsoft/winget-cli/files/9739479/WinGet-2022-10-08-16-17-57.822.log)

**Comment by jtmullen** [comment] 2022-10-12 21:27
Also the same issue with Amazon Appstore:

[WinGet-2022-10-12-14-23-55.485.log](https://github.com/microsoft/winget-cli/files/9768783/WinGet-2022-10-12-14-23-55.485.log)

**Comment by coop3406** [comment] 2023-04-05 22:39
Any Update on this issue?  I'm encountering the issue today and curious what the solution is

Command:
 winget install "Real FTP" --accept-package-agreements  --accept-source-agreements 
--dependency  --source msstore  --verbose-logs

[WinGet-2023-04-05-18-31-34.481.log](https://github.com/microsoft/winget-cli/files/11163596/WinGet-2023-04-05-18-31-34.481.log)

**Comment by koreytm** [comment] 2023-04-06 19:25
Also experiencing this issue...

**Comment by JohnMcPMS** [comment] 2023-04-06 20:47
If you file an issue through Feedback Hub for a Store related category (like `Microsoft Store > Downloading, installing and updating`) and send the link to it, that should collect the data we need to be able to investigate the issue further.  Since it is happening within the Store APIs, we don't have much in the way of useful information in our own log file.

**Comment by koreytm** [comment] 2023-04-06 21:34
Hello @JohnMcPMS - I have created an issue in the Feedback Hub for this. Here is the link to the post:

https://aka.ms/AAk8q10

I attached the verbose log I collected to the issue. If you need anything else, let me know.

**Comment by darrellarbaugh** [comment] 2023-04-12 13:53
Experiencing this as well with winget.  When I use the MSStore GUI, installing the package proceeds without error.  I opened a issue through feedback hub.  https://aka.ms/AAkdo1e.  Here is the snippet of the error:

**Comment by coop3406** [comment] 2023-04-20 07:35
Any update on this issue??

**Comment by denelon** [comment] 2023-04-20 15:22
We've been able to reproduce:
* #3166 

We're working with the Microsoft Store team to see what the root cause is.

**Comment by denelon** [comment] 2023-04-20 17:02
Not yet. That's part of:
* #908 

I don't believe any changes will need to be made to WinGet. It's primarily work we're coordinating with the Microsoft Store team. Please add your 👍 to that issue.

The "msstore" source currently only works for Apps that are "Free" and rated "e" for everyone.

**Closed** 2023-04-28 19:18 UTC
Labels: In-PR, Issue-Bug, msstore
