### ISSUE TITLE
The list showing app details isn't wide enough

### ISSUE THREAD

**Issue by dong-lufei** [microsoft/winget-cli#2842] opened 2023-01-12 12:05 UTC
### Description of the new feature / enhancement

In the information from the winget list, the name and id columns of some applications are very long, all of which are truncated and cannot be read clearly. Neither self-responsive nor max-width

>The width of the following application list is not enough, the information cannot be displayed, and the following are dots
```
Microsoft Visual C++ 2015-2022 Redistr… Microsoft.VCRedist.2015+.x86                               14.34.31931.0                   winget
Microsoft Visual C++ 2015-2022 Redistr… Microsoft.VCRedist.2015+.x64                               14.34.31931.0                   winget
Windows Software Development Kit - Win… Microsoft.WindowsSDK                                       10.0.22000.832    10.0.22621.2  winget
```

**Comment by stephengillie** [comment] 2023-01-12 19:47
Related: 
* https://github.com/microsoft/winget-cli/issues/2603

**Comment by denelon** [comment] 2023-01-12 21:33
Duplicate of #2603

**Closed by denelon** 2023-01-12 21:33 UTC
Labels: Issue-Feature
