### ISSUE TITLE
An unknown error occurred 

### ISSUE THREAD

**Issue by Dukro** [microsoft/winget-cli#1186] opened 2021-06-21 08:38 UTC
PS C:\dukro@CHUWI\tmp> winget install -m C:\dukro@CHUWI\tmp\winget-pkgs\manifests\g\Google\Flutter\Stable\2.2.2\Google.Flutter.Stable.Install.yaml
执行此命令时发生意外错误：
0x8a150004 : Opening manifest failed
PS C:\dukro@CHUWI\tmp>
PS C:\dukro@CHUWI\tmp> winget install  C:\dukro@CHUWI\tmp\winget-pkgs\manifests\g\Google\Flutter\Stable\2.2.2\Google.Flutter.Stable.Install.yaml
找不到与输入条件匹配的程序包。
PS C:\dukro@CHUWI\tmp>

**Comment by KaranKad** [comment] 2021-06-21 17:44
Flutter comes in a `.zip` package and winget-cli currently cannot install from it. https://github.com/microsoft/winget-pkgs/issues/18414#issuecomment-865170498

**Comment by denelon** [comment] 2021-06-21 17:54
Duplicate of #140 Support installing .zip files

**Closed by denelon** 2021-06-21 17:54 UTC
Labels: .zip, Blocking-Issue
