### ISSUE TITLE
Unable to remove package

### ISSUE THREAD

**Issue by sagar297** [microsoft/winget-cli#4678] opened 2024-07-26 10:02 UTC
### Brief description of your issue

Unable to uninstall Gyan.FFmpeg.
Only the latest version of Gyan.FFmpeg is installed.
`winget uninstall Gyan.FFmpeg --all-versions` and `winget uninstall --id Gyan.FFmpeg --version 7.0.1` does not work.

`winget list Gyan.FFmpeg` returns:
```
Name   Id          Version
--------------------------
FFmpeg Gyan.FFmpeg 7.0.1
```

### Log
2024-07-26 13:34:19.676 [REPO] Performing search: Query:[none] Filter:Id='Gyan.FFmpeg'[CaseInsensitive]
2024-07-26 13:34:19.687 [REPO] Finding installed package from available package using system reference search: Query:[none] Include:NormalizedNameAndPublisher='ffmpeg'+'gyan'[Exact]
2024-07-26 13:34:19.687 [REPO] Performing search: Query:[none] Include:NormalizedNameAndPublisher='ffmpeg'+'gyan'[Exact]
2024-07-26 13:34:19.689 [REPO] Performing search: Query:[none] Include:ProductCode='gyan.ffmpeg_microsoft.winget.source_8wekyb3d8bbwe'[Exact] Include:NormalizedNameAndPublisher='ffmpeg'+'gyan'[Exact]
2024-07-26 13:34:19.691 [REPO]  ... installed package [ARP\User\X64\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe] had multiple correlations and is being ignored as a match for [Gyan.FFmpeg]
2024-07-26 13:34:19.691 [CLI ] Search result size: 0
2024-07-26 13:34:19.691 [CLI ] No app found matching input criteria
2024-07-26 13:34:19.733 [CLI ] Terminating context: 0x8a150014 at C:\__w\1\s\external\pkg\src\AppInstallerCLICore\Workflows\WorkflowBase.cpp:3e5

### Steps to reproduce

winget install Gyan.FFmpeg
winget uninstall Gyan.FFmpeg

### Expected behavior

winget should remove the package.

### Actual behavior

No installed package found matching input criteria.

### Environment

```shell
Windows Package Manager (Preview) v1.9.1981-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.26252.5000
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.24.1981.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Enabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

**Comment by denelon** [comment] 2024-07-26 16:16
This issue looks like what got reported in #2949 and is a duplicate of #3279.

* #2949
* #3279

**Closed** 2024-07-26 16:54 UTC
Labels: Resolution-Duplicate

**Comment by sagar297** [comment] 2024-07-26 18:10
> This issue looks like what got reported in #2949 and is a duplicate of #3279.
> 
> * [[Package Issue]: Gyan.FFmpeg does not uninstall correctly #2949](https://github.com/microsoft/winget-cli/issues/2949)
> * [Cannot upgrade/uninstall nested portables coming from an older version of WinGet #3279](https://github.com/microsoft/winget-cli/issues/3279)

The workaround identified in issue #3279 appears ineffective in resolving the issue.
I have the correct version of the software in my system registry.
![image](https://github.com/user-attachments/assets/a63a3e74-a4ee-4d7e-997e-dcfa79a74c97)

I have tried to uninstall the software from the control panel, subsequently reinstall it using winget, and ultimately attempted to uninstall it through winget once again. These measures have failed to produce the desired results.
