### ISSUE TITLE
UniGetUI doesn't see any updates

### ISSUE THREAD

**Issue by hspindel** [microsoft/winget-cli#4614] opened 2024-07-06 00:22 UTC
### Brief description of your issue

WinGetUI updated to UniGetUI.  Previously WinGetUI reported numerous updates available.

Package sources include .NET Tool, Chocolatey and PowerShell.  Same as WinGetUI used to show.

Probably key log entry:

[7/5/2024 5:12:03 PM] Could not initialize Package Manager Winget
[7/5/2024 5:12:03 PM] System.ComponentModel.Win32Exception (5): An error occurred trying to start process 'C:\Users\howard\AppData\Local\Microsoft\WindowsApps\winget.exe' with working directory 'D:\Program Files\UniGetUI'. Access is denied.
                         at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
                         at UniGetUI.PackageEngine.Managers.WingetManager.WinGet.LoadManager() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.WinGet\WinGet.cs:line 495
                         at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.InitializeAsync() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 76

### Steps to reproduce

Just run UniGetUI.

### Expected behavior

List of updateable programs provided.

### Actual behavior

UniGetUI says all programs up-to-date.

### Environment

```shell
winget --info reports access denied.
```

**Comment by Trenly** [comment] 2024-07-06 04:19
This is an issue that needs to be filed on the UniGetUI repo, as it is not an issue with the WinGet CLI.

**Comment by hspindel** [comment] 2024-07-06 05:59
> This is an issue that needs to be filed on the UniGetUI repo, as it is not an issue with the WinGet CLI.

Not sure about that.  The log clearly states that it is WinGet CLI that can't be executed.

**Comment by Masamune3210** [comment] 2024-07-06 08:22
Yes, but as stated, this has nothing to do with winget itself. In fact, the fact that it says that it couldn't execute winget proves this, as winget hasn't even had a chance to DO anything yet. Something on your machine is busted, permissions-wise, or UniGet has a bug in how it tries to execute winget.

**Comment by hspindel** [comment] 2024-07-06 08:28
> Yes, but as stated, this has nothing to do with winget itself. In fact, the fact that it says that it couldn't execute winget proves this, as winget hasn't even had a chance to DO anything yet. Something on your machine is busted, permissions-wise, or UniGet has a bug in how it tries to execute winget.

It has everything to do with winget.  No matter how many times I try to reinstall it and no matter how many guides I try to follow winget always reports access denied.  Yes, I agree something is busted with permissions, but I need a pointer to fix that.

**Comment by mdanish-kh** [comment] 2024-07-06 08:47
Are you able to execute winget commands normally from the terminal without WingetUtil?

Does something like `winget -v` / `winget list` work for you in the terminal?

**Comment by hspindel** [comment] 2024-07-06 09:25
> Are you able to execute winget commands normally from the terminal without WingetUtil?
> 
> Does something like `winget -v` / `winget list` work for you in the terminal?

Attempting winget with any parameters always yields "access is denied."

**Comment by mdanish-kh** [comment] 2024-07-06 10:23
Can you try re-installing WinGet from https://aka.ms/getwinget and check again?

**Comment by Trenly** [comment] 2024-07-06 10:24
> Attempting winget with any parameters always yields "access is denied."

Well, that is a completely different issue than "UniGetUI doesn't see any updates". That would be "WinGet always yields access is denied".

Have you tried re-installing WinGet or updating to the latest version? What version do you have installed ( `Get-AppxPackage *AppInstaller*`)? Are there any logs you can share from WinGet directly (`%localappdata%/Packages/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe/DiagOuptuDir/LocalState`)?

**Comment by hspindel** [comment] 2024-07-06 22:18
Thank you for the reply.

> 
> Have you tried re-installing WinGet or updating to the latest version? What version do you have installed ( `Get-AppxPackage *AppInstaller*`)? Are there any logs you can share from WinGet directly (`%localappdata%/Packages/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe/DiagOuptuDir/LocalState`)?

Reinstalling WinGet doesn't help (multiple tries).

Get-AppxPackage "AppInstaller" reports:

````
Name              : Microsoft.DesktopAppInstaller
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 1.23.1791.0
PackageFullName   : Microsoft.DesktopAppInstaller_1.23.1791.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.23.1791.0_x64__8wekyb3d8bbwe
IsFramework       : False
PackageFamilyName : Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
Dependencies      : {Microsoft.UI.Xaml.2.8_8.2310.30001.0_x64__8wekyb3d8bbwe,
                    Microsoft.VCLibs.140.00.UWPDesktop_14.0.33728.0_x64__8wekyb3d8bbwe,
                    Microsoft.DesktopAppInstaller_1.23.1791.0_neutral_split.scale-100_8wekyb3d8bbwe}
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok
`
```
There is no folder named DiagOutputDir (or anything similar) under %localappdata%/Packages/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe

**Comment by hspindel** [comment] 2024-07-06 22:19
> Can you try re-installing WinGet from https://aka.ms/getwinget and check again?
> 
>     * Related: [ResourceUnavailable: Program 'winget.exe' failed to run: An error occurred trying to start process. Access is denied.At line:1 char:1 #3057](https://github.com/microsoft/winget-cli/issues/3057)

Thank you, but it doesn't work.

**Comment by Trenly** [comment] 2024-07-06 22:25
> There is no folder named DiagOutputDir (or anything similar) under %localappdata%/Packages/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe

Ah, my bad; Is there one called `LocalState`?

**Comment by hspindel** [comment] 2024-07-06 22:56
> 
> Ah, my bad; Is there one called `LocalState`?

No problem.  Yes, there is LocalState.  It has eleven log files in it.  The two most recent are attached.


[AppInstaller-2024-07-06-01-05-13.388.log](https://github.com/user-attachments/files/16117565/AppInstaller-2024-07-06-01-05-13.388.log)


[AppInstaller-2024-07-06-01-05-22.653.log](https://github.com/user-attachments/files/16117566/AppInstaller-2024-07-06-01-05-22.653.log)

**Comment by denelon** [comment] 2024-07-08 14:50
@marticliment, let me know if this is something that should go to UniGetUI or how we can help figure out what's going on here. 😊

**Comment by denelon** [comment] 2024-07-08 14:56
@hspindel do you get any results if you run `winget --info`? If you do, can you share them?

**Comment by marticliment** [comment] 2024-07-08 18:32
> @marticliment, let me know if this is something that should go to UniGetUI or how we can help figure out what's going on here. 😊

I have seen a similar bug report on UniGetUI, but, as said previously, I can't help from UniGetUI.

The way in which the winget.exe is called is from a standard System.Diagnostics.Process instance, without anything weird going on.

My best guess is a misconfiguration with system permissions, since the only change I have done is calling the system winget.exe instead of the bundled winget.exe WingetUI used to use.

**Comment by marticliment** [comment] 2024-07-08 18:37
The relevant issue on UniGetUI is https://github.com/marticliment/UniGetUI/issues/2444

**Comment by hspindel** [comment] 2024-07-09 00:20
> > @marticliment, let
> The way in which the winget.exe is called is from a standard System.Diagnostics.Process instance, without anything weird going on.
> 
> My best guess is a misconfiguration with system permissions, since the only change I have done is calling the system winget.exe instead of the bundled winget.exe WingetUI used to use.

Is there any way we can get a config option for UniGetUI to call the bundled winget it used to use?  When I try that winget.exe from a command line, it successfully reports a version number instead of "access is denied" with the new version.

**Comment by hspindel** [comment] 2024-07-09 00:26
> @hspindel do you get any results if you run `winget --info`? If you do, can you share them?

I get "access is denied" if I run winget from a command line.  However, if I use the winget.exe that came bundled with UniGetUI from a command line it works.

```
D:\Program Files\UniGetUI\winget-cli_x64>winget --info
Windows Package Manager v1.8.1791
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.4529
System Architecture: X64

Winget Directories
---------------------------------------------------------------------------------------------------
Logs                               %TEMP%\WinGet\defaultState
User Settings                      %LOCALAPPDATA%\Microsoft\WinGet\Settings\defaultState\settings.…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled

D:\Program Files\UniGetUI\winget-cli_x64>



```

**Comment by marticliment** [comment] 2024-07-09 07:52
> > > @marticliment, let
> > The way in which the winget.exe is called is from a standard System.Diagnostics.Process instance, without anything weird going on.
> > 
> > My best guess is a misconfiguration with system permissions, since the only change I have done is calling the system winget.exe instead of the bundled winget.exe WingetUI used to use.
> 
> Is there any way we can get a config option for UniGetUI to call the bundled winget it used to use?  When I try that winget.exe from a command line, it successfully reports a version number instead of "access is denied" with the new version.
> 
> 

If you add the UniGetUI bundled winget to path and temporarily remove system winget from path (you can do so from settings) you should be able to test this

**Comment by hspindel** [comment] 2024-07-10 01:41
@marticliment
> If you add the UniGetUI bundled winget to path and temporarily remove system winget from path (you can do so from settings) you should be able to test this

This turned out to be more of an adventure than I expected.  Documenting here in case it helps someone else.

1.  Can't remove system winget from path.  Other apps in the same directory need to be in the path.
2.  Can't add path to UniGetUI's winget.exe to system path first entry (overriding existing path) because the System Path is out of space.
3.  Can't delete winget.exe from the system location.  It's a special file called an app alias.  Wanted to delete the system winget.exe and replace with UniGetUI's winget.exe, but no go.

Eventual solution that works:

1.  Go to PC Settings/Apps.
2.  Click on App Execution Aliases.
3.  Unselect Windows Package Manager Client.  When you do this, winget.exe disappears from the system location.
4.  Open a command window and run winget.  Verify that Windows reports app not found.
5.  Edit my personal environment PATH (which has plenty of free space) and add the path to UniGetUI's version of winget.exe.
6.  Open a command window and run winget.  Verify that it executes properly.
7.  Run UniGetUI.  All is well!

**Comment by denelon** [comment] 2024-07-11 17:46
@hspindel,

Thanks for documenting your work around.

The App Execution Alias is indeed how "winget.exe" from the App Installer MSIX bundle is mapped to the path.

I think there is still something potentially misconfigured on the system if WinGet isn't working after a "clean" install.

Would you be willing to try running the `Repair-WinGetPackageManager -Force -Latest` from the current version of the "Microsoft.WinGet.Client" PowerShell module to see if that fixes the default WinGet instance?

Fair warning: This will likely reinstate the App Execution Alias, so you would have to re-apply your work around if it doesn't work.

**Comment by hspindel** [comment] 2024-07-11 21:05
> Would you be willing to try running the `Repair-WinGetPackageManager -Force -Latest` from the current version of the "Microsoft.WinGet.Client" PowerShell module to see if that fixes the default WinGet instance?

I agree there is something misconfigured, but I haven't been able to find what.

I opened a PowerShell window and entered: 

    Would you be willing to try running the Repair-WinGetPackageManager -Force -Latest from the current version of the "Microsoft.WinGet.Client" PowerShell module to see if that fixes the default WinGet instance?

I agree there is something misconfigured, but I haven't been able to find what.

I opened a PowerShell window and entered:
Repair-WinGetPackageManager -Force -Latest

I may nave missed something, because I didn't understand the part about running this command from the current version of the "Microsoft.WinGet.Client" PowerShell module.  When I entered the PowerShell command, I get the following error:

```
 Repair-WinGetPackageManager -Force -Latest
Repair-WinGetPackageManager : Access is denied
At line:1 char:1
+ Repair-WinGetPackageManager -Force -Latest
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Repair-WinGetPackageManager], Win32Exception
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.WinGet.Client.Commands.RepairWinGetPackag
   eManagerCmdlet
```

----------------------------------------

In other news, a new problem arose.  UniGetUI worked fine for a while with my fixes above.  But it stopped working now.  It hangs displaying "Loading Packages" on the Software Updates page.  On the Installed Packages page, I still see all the expected apps.

Here's the log:

```
[7/11/2024 12:25:37 AM] UniGetUI is up to date
[7/11/2024 12:43:59 AM] Found 1 installed packages from .NET Tool
[7/11/2024 12:44:01 AM] Found 6 installed packages from Chocolatey
[7/11/2024 12:44:03 AM] WinGet installed packages returned zero packages, attempting legacy...
[7/11/2024 12:44:06 AM] Found 1 installed packages from PowerShell
[7/11/2024 12:44:14 AM] Found 628 installed packages from Winget
[7/11/2024 1:25:38 AM] UniGetUI is up to date
[7/11/2024 2:25:38 AM] UniGetUI is up to date
[7/11/2024 3:25:38 AM] UniGetUI is up to date
[7/11/2024 4:25:39 AM] UniGetUI is up to date
[7/11/2024 5:25:39 AM] UniGetUI is up to date
[7/11/2024 6:25:40 AM] UniGetUI is up to date
[7/11/2024 7:25:40 AM] UniGetUI is up to date
[7/11/2024 8:25:40 AM] UniGetUI is up to date
[7/11/2024 9:25:41 AM] UniGetUI is up to date
[7/11/2024 10:25:41 AM] UniGetUI is up to date
[7/11/2024 11:25:41 AM] UniGetUI is up to date
[7/11/2024 12:25:42 PM] UniGetUI is up to date
[7/11/2024 1:25:42 PM] UniGetUI is up to date
[7/11/2024 1:55:33 PM] Found 1 installed packages from .NET Tool
[7/11/2024 1:55:33 PM] WinGet installed packages returned zero packages, attempting legacy...
[7/11/2024 1:55:34 PM] Found 6 installed packages from Chocolatey
[7/11/2024 1:55:35 PM] Found 1 installed packages from PowerShell
[7/11/2024 1:55:43 PM] Found 628 installed packages from Winget
[7/11/2024 2:02:54 PM] Found 1 installed packages from .NET Tool
[7/11/2024 2:02:56 PM] WinGet installed packages returned zero packages, attempting legacy...
[7/11/2024 2:02:56 PM] Found 6 installed packages from Chocolatey
[7/11/2024 2:02:57 PM] Found 1 installed packages from PowerShell
[7/11/2024 2:03:03 PM] Found 628 installed packages from Winget
```

**Comment by marticliment** [comment] 2024-07-11 21:10
As from your UniGetUI logs, the powershell module seems to either not be installed (which is not the case) or not reporting packages.

**Comment by hspindel** [comment] 2024-07-11 21:17
> As from your UniGetUI logs, the powershell module seems to either not be installed (which is not the case) or not reporting packages.

Here's a screen capture showing installed packages.  Powershell seems to be present.  And as I said, this was working and stopped without me changing anything.  What do you suggest I try?

![Screen_071124](https://github.com/user-attachments/assets/e8fee567-c944-49b0-8c78-f350061023be)

**Comment by marticliment** [comment] 2024-07-11 21:53
Packages are shown because UniGetUI is resorting to bundled winget, but the powershell cmdlets are not working (see the bundled winget reported 0 packages lines on log), which makes sense knowing  that the Repair-WinGetPackageManager cmdlet is not working.

If your system winget is not working, neither will the COM APIs (the default method in the latest UniGetUI beta) neither the PowerShell module (which as far as I understand depends on the COM APIs itself). Therefore, no packages are reported and UniGetUI resorts to the bundled winget to show installed packages.

**Comment by hspindel** [comment] 2024-07-11 23:03
> Packages are shown because UniGetUI is resorting to bundled winget, but the powershell cmdlets are not working (see the bundled winget reported 0 packages lines on log), which makes sense knowing that the Repair-WinGetPackageManager cmdlet is not working.
> 
> If your system winget is not working, neither will the COM APIs (the default method in the latest UniGetUI beta) neither the PowerShell module (which as far as I understand depends on the COM APIs itself). Therefore, no packages are reported and UniGetUI resorts to the bundled winget to show installed packages.

Thank you.

I guess I understand, but have no idea how to go about fixing this.

**Comment by hspindel** [comment] 2024-07-12 01:52
> I guess I understand, but have no idea how to go about fixing this.

I got UniGetUI to work again, but I'm not sure which of the following steps I took was the effective one.

1.  In Windowx Programs and Features I disabled and then re-enabled Powershell.
2.  Used the task manager to kill an existing running WingetUI to be sure it restarted fresh.

**Comment by denelon** [comment] 2024-07-12 15:56
Thanks for reporting back. I'm not sure what caused this issue either. If you're able to get a reproduceable scenario, please re-open the bug, or file a new one. Since this seems to have been transient, I'm going to close the issue.

**Closed by denelon** 2024-07-12 15:56 UTC
Labels: Issue-Bug
