### ISSUE TITLE
Add a selector for multiple match found

### ISSUE THREAD

**Issue by SirusCodes** [microsoft/winget-cli#2178] opened 2022-05-22 00:01 UTC
### Description of the new feature / enhancement

The current implementation shows the list of matches available when we try to install a package
![Terminal screenshot of winget install git](https://user-images.githubusercontent.com/50910066/169672680-d9148170-cb4e-479a-93ec-bb86f257bf67.png)

It would be better if we can directly ask the user to select the ID and install it instead of making then write the command again.

**Comment by ItzLevvie** [comment] 2022-05-22 01:11
* Duplicate of https://github.com/microsoft/winget-cli/issues/1620.

**Closed** 2022-05-22 01:45 UTC
Labels: Issue-Feature, Needs-Triage
