### ISSUE TITLE
Reoccurrence of Issue #4141 for IOBit.AdvancedSystemCare version 17.5.0.xxx

### ISSUE THREAD

**Issue by baldgnosis** [microsoft/winget-cli#4631] opened 2024-07-12 10:02 UTC
### Brief description of your issue

winget installs the latest version successfully but keeps appearing as available to update because the registry version and manifest version don't match. 

Previously reported for version 17.2.0 in February 2024 as [#4141.](url=https://github.com/microsoft/winget-cli/issues/4141)

### Steps to reproduce

```
winget install IObit.AdvancedSystemCare
winget update -u
```

### Expected behavior

If the latest version of a package is installed, winget should not list it as available for update. 

### Actual behavior

```
Name                Id                       Version Available  Source
----------------------------------------------------------------------
Advanced SystemCare IObit.AdvancedSystemCare 17.5.0  17.5.0.255 winget
```

### Environment

```shell
Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.26100.1150
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

**Comment by Trenly** [comment] 2024-07-12 13:07
* Duplicate of https://github.com/microsoft/winget-pkgs/issues/162569

**Closed** 2024-07-12 13:07 UTC
