### ISSUE TITLE
Support portable packages with supporting files

### ISSUE THREAD

**Issue by carlescufi** [microsoft/winget-cli#3489] opened 2023-08-01 14:57 UTC
### Description of the new feature / enhancement

Support for portable (i.e. without an installer) applications was added to winget a while back:
https://github.com/microsoft/winget-cli/blob/master/doc/specs/%23182%20-%20Support%20for%20installation%20of%20portable%20standalone%20apps.md

Unfortunately the manifest format does not allow for multiple files to be installed in the system, just a single executable binary. This is an issue for applications that require additional files (eg. a dynamic library or a resource file of some sort).

This is because the link created in `%APPLOCALDATA%\Microsoft\WinGet\Links` is not executed in the context of the installation unzipped folder (for a zip installer): `%LOCALAPPDATA%\Microsoft\Winget\Packages\<package name>`.

### Proposed technical implementation details

Execute the link in the context of the `%LOCALAPPDATA%\Microsoft\Winget\Packages\<package name>` folder.

**Comment by mdanish-kh** [comment] 2023-08-01 15:48
Duplicate of #2711

A not so pretty workaround (as it has the tendency to quickly fill up your PATH variable limit) is to install the application in a non-admin shell with developer mode disabled in Windows. In this case, WinGet cannot create a symlink and will resort to putting the entire package path (i.e., %LOCALAPPDATA%\Microsoft\Winget\Packages\<package name>) into the PATH variable. That way all the required libraries, .dlls will be referenced properly.

**Closed** 2023-08-01 15:48 UTC
Labels: Issue-Feature
