### ISSUE TITLE
Exclude packages from upgrade --all

### ISSUE THREAD

**Issue by Ian-Clark-maintenance** [microsoft/winget-cli#1157] opened 2021-06-12 01:20 UTC
when running winget upgrade --all I run across packages that are having some kind of error or otherwise can't upgrade, and stops the process, it would be nice to be able to specify the name of the troublemaker package by name or regex, so I can streamline upgrading the rest of the packages

users could also use this functionality to automate winget, upgrading packages for security concerns, but excluding packages they rely on for development or other neeeds

# Proposed technical implementation details (optional)

**Comment by Soitora** [comment] 2021-06-14 15:19
Duplicate of #476

**Comment by denelon** [comment] 2021-06-14 15:20
Duplicate of #476

**Closed by denelon** 2021-06-14 15:20 UTC
Labels: Issue-Feature, Needs-Triage

**Comment by xellos81** [comment] 2023-06-07 14:16
my advice is tu use winget ui
there you can select what to update and what not
and there's also chocolatey (and scoop) included
