### ISSUE TITLE
Winget fails to start x64 installer on ARM64 machine

### ISSUE THREAD

**Issue by SJang1** [microsoft/winget-cli#1054] opened 2021-06-01 07:59 UTC
# Brief description of your issue

Winget fails to start install x64 installer on ARM64 machine with windows 10 insider dev build, which is avaliable to run.

# Steps to reproduce
1. Run windows ARM on the machine.
2. Make a manifest with x64 installer program.
3. Try to install using that manifest.

# Expected behavior
It should install without any problem. (x64 is now supported on ARM machine)

# Actual behavior
Fails to start installer with log : `Installer [X64,Exe,Unknown,] not applicable: Machine is not compatible with X64`

# Environment

```none
[system]
M1 Macbook Air with Parallels Desktop

[winget --info]
Windows Package Manager v1.0.11451
Windows: Windows.Desktop v10.0.21343.1000
Package: Microsoft.DesktopAppInstaller v1.11.11451.0
```

**Comment by GeorgeCY2** [comment] 2021-06-01 09:33
of course, you need to use ARM64 since you are using an ARM Processor, NOT X64

**Comment by SJang1** [comment] 2021-06-01 09:35
> of course, you need to use ARM64 since you are using an ARM Processor, NOT x64
You can see Windows blog post that it is available to use
https://blogs.windows.com/windows-insider/2020/12/10/introducing-x64-emulation-in-preview-for-windows-10-on-arm-pcs-to-the-windows-insider-program/

**Comment by GeorgeCY2** [comment] 2021-06-01 10:10
> > of course, you need to use ARM64 since you are using an ARM Processor, NOT x64
> 
> You can see Windows blog post that it is available to use
> https://blogs.windows.com/windows-insider/2020/12/10/introducing-x64-emulation-in-preview-for-windows-10-on-arm-pcs-to-the-windows-insider-program/
> 
> also see the task manager shows running x64 programs :
> ![image](https://user-images.githubusercontent.com/29011440/120302137-8d237d00-c308-11eb-80d6-bec2fe7dec73.png)

ah so kinda like apple's rosetta translation layer. Yeah i would expect some issues to occur, I think you must try running cmd using x64 in order to work

**Comment by SJang1** [comment] 2021-06-01 10:13
> ah so kinda like apple's rosetta translation layer. Yeah i would expect some issues to occur, I think you must try running cmd using x64 in order to work or run pararell desktop on rosetta.

So, the problem it's having is when you run installer using old method (double click to run), runs as x64 without any problem, but having that `Installer [X64,Exe,Unknown,] not applicable: Machine is not compatible with X64` error when trying with this winget

**Comment by JohnMcPMS** [comment] 2021-06-07 17:50
Duplicate of #666

**Closed by JohnMcPMS** 2021-06-07 17:50 UTC
Labels: Issue-Feature
