### ISSUE TITLE
`0x8a15000f : Data required by the source is missing` when running `winget` via OpenSSH-Win32

### ISSUE THREAD

**Issue by tigerinus** [microsoft/winget-cli#2967] opened 2023-02-14 22:58 UTC
### Brief description of your issue

![image](https://user-images.githubusercontent.com/7172560/218882036-30be40c0-6bc3-4577-bd0d-a68dda9c0b06.png)

![image](https://user-images.githubusercontent.com/7172560/218882709-9ec4ce77-bc5b-4a4a-9522-b21334feb30c.png)

### Steps to reproduce

Just try to install or upgrade anything

### Expected behavior

it should just work

### Actual behavior

See the screenshot

### Environment

```shell
winget --info 
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2486
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by denelon** [comment] 2023-02-15 00:11
https://cdn.winget.microsoft.com/cache is expected to return "ResourceNotFound".

The actual file URL for the PreIndexed package is https://cdn.winget.microsoft.com/cache/source.msix.

WinGet will download the source and install it. You can see if it is installed via Windows Apps & Features:
<img width="284" alt="WindowsAppsWinGetSource" src="https://user-images.githubusercontent.com/61799811/218891444-76bea1b3-d4b4-419f-b574-e5fbe5b9355c.png">

The default timeout on the cache is 5 minutes. The settings for the TTL can be changed via `winget settings`.

You could try manually downloading and installing the source package.

If that doesn't work, please share the logs after running a command that would use the index like: `winget search vscode -s winget`. I added the source, so we don't have to dig through the logs for the "msstore" REST calls.

**Comment by denelon** [comment] 2023-02-15 00:13
Looks very similar to:
* #2377

**Comment by tigerinus** [comment] 2023-02-15 21:48
@denelon - I forgot to mention I've been managing this PC via OpenSSH-Win32 all the time.

Today I came to the location of this PC and tried winget from UI and it works.

So this issue happens only when running within a SSH session.

**Comment by denelon** [comment] 2023-02-21 19:39
* Duplicate of #1474

**Closed** 2023-02-21 19:39 UTC
Labels: Issue-Bug
