### ISSUE TITLE
use a different archive extractor

### ISSUE THREAD

**Issue by solomoncyj** [microsoft/winget-cli#4307] opened 2024-03-25 13:02 UTC
### Description of the new feature / enhancement

Winget should use a difent archive extration too, eg 7zip, to extract other types archives, as the windows api only supports zips. furthermore, windows acannot extract lmza type zips

### Proposed technical implementation details

using a dll and a wrapper libary (bit7z). I have tried doing that, but i am getting build errors

**Comment by denelon** [comment] 2024-03-25 15:05
We're looking at support for additional supported types over at:
* #2899

Duplicate of #2899

**Closed** 2024-03-25 15:05 UTC
Labels: Issue-Feature
