### ISSUE TITLE
Sort Results of "List" Command

### ISSUE THREAD

**Issue by helmanfrow** [microsoft/winget-cli#2608] opened 2022-10-19 16:07 UTC
### Description of the new feature / enhancement

It would be nice if I could specify the sort order for the output of the _winget list_ command.
Usually I want to see the results displayed in alphabetic order so I can quickly scan the list and find what I'm looking for.

### Proposed technical implementation details

Something like _winget list --sort a desc_ would be great.

**Comment by Trenly** [comment] 2022-10-19 16:31
Duplicate of #1769

**Closed** 2022-10-19 16:31 UTC
Labels: Issue-Feature, Needs-Triage

**Comment by Trenly** [comment] 2022-10-19 16:33
See also #1352
