### ISSUE TITLE
Cannot Uninstall MiKTeX

### ISSUE THREAD

**Issue by keenbowl3009** [microsoft/winget-cli#1711] opened 2021-11-15 20:14 UTC
### Brief description of your issue

Cannot uninstall the package using the package Id.

### Steps to reproduce

winget install ChristianSchenk.MiKTeX
winget uninstall ChristianSchenk.MiKTeX

### Expected behavior

The system should return exactly to the state it was if miktex was not installed. 

### Actual behavior

When trying to uninstall, I get: 
No installed package found matching input criteria.

### Environment

```shell
Windows: Windows.Desktop v10.0.22000.318
Package: Microsoft.DesktopAppInstaller v1.16.12663.0
```

Edited: Off topic comments removed.

**Comment by tajetaje** [comment] 2021-11-15 20:47
What is the output of winget list

**Comment by keenbowl3009** [comment] 2021-11-15 20:51
> What is the output of winget list

the output of winget list includes MiKTeX.

**Comment by keenbowl3009** [comment] 2021-11-15 20:52
The output of winget uninstall ChristianSchenk.MiKTeX is: 

No installed package found matching input criteria.

**Comment by keenbowl3009** [comment] 2021-11-15 20:54
It's great to know that winget provides the assurance that all packages that were installed with it can be easily uninstalled. 

Winget as a whole is the pinnacle of microsoft software representativeness: 

does not fix the problems, but will likely make them worse.

**Comment by keenbowl3009** [comment] 2021-11-15 21:00
by the way, scoop was literally created to enable portable apps because the community goes out of its way to make sure that installing something through scoop will not permanently break your system, and that scoop packages will just work with each other. 

Winget goes out of it's way to not do anything, and to make sure that microsoft will not do anything to help you as well.

**Comment by JanPokorny** [comment] 2021-11-15 21:42
I was able to reproduce. MikTeX has wrong id after installation:

![image](https://user-images.githubusercontent.com/4580066/141857649-437804fd-5487-4523-a2d3-fcfdf6a0fb2e.png)

![image](https://user-images.githubusercontent.com/4580066/141857682-2ec1c5f1-f714-4630-b60e-35458c698e20.png)

It needs to be uninstalled with `winget uninstall MikTeX`

**Comment by Masamune3210** [comment] 2021-11-15 21:43
Manifest probably has incorrect productid or they changed it recently as I think that is what winget uses currently to detect known installed applications

**Comment by jedieaston** [comment] 2021-11-15 21:52
This will most likely be resolved by https://github.com/microsoft/winget-pkgs/pull/34983.

**Comment by martinmine** [comment] 2021-11-15 22:31
> winget is literally the worst possible package manager that the community could adopt.

Your attempt at shitposting in order to let out your frustration will not be any helpful for improving this software. Your issues might even get deleted as they clearly violate the [code of conduct](https://github.com/microsoft/winget-cli/blob/master/CODE_OF_CONDUCT.md). If winget upsets you that much you create a github account specifically to troll on this repo, I seriously recommend you that you just use Scoop as that is a much better usage of your time.

**Comment by JanPokorny** [comment] 2021-11-15 22:35
@martinmine The issue is actually real. [The autor probably isn't, tho.](https://tineye.com/search/4c619dd9baa2ec8f9a11e2ee6e68f7cdfb1ba8bd?sort=score&order=desc&page=1)

**Comment by martinmine** [comment] 2021-11-15 22:37
@JanPokorny Sure, but the tone and content isn't constructive and is only helpful for OP to let out their frustration. This is counter-productive and if people actually have this issue, now there is the risk it might even get deleted.

**Comment by denelon** [comment] 2021-11-15 22:53
PR merged. Once it's been published, this should be resolved.

**Closed** 2021-11-16 00:28 UTC
Labels: Issue-Bug

**Comment by vividfrog9892** [comment] 2021-11-17 09:49
Once again, microsoft's software quality and products are just awful. https://github.com/microsoft/vscode/issues/137354

**Comment by vividfrog9892** [comment] 2021-11-17 09:50
https://github.com/microsoft/terminal/issues/11772

**Comment by JanPokorny** [comment] 2021-11-17 09:54
I feel sorry for Microsoft open source maintainers that have to deal with this sort of crazy...

**Comment by denelon** [comment] 2021-11-17 16:45
@JanPokorny it comes with the territory. People have a long memory. It's going to take even longer to demonstrate how much we care about open source. I understand the frustration here. As long as it's not directed towards an individual, it's better to let people vent in most cases. There are also several different perspectives on the "right" approach when there are many right approaches.

Most of the community has been very supportive which makes it easier to want to build a better product and be honest about failures and gaps. There is a massive body of work in the world of Linux package management where everything is a file. Things are far more complex when dealing with third party installers and decades of inertia. It's an exciting time to be at Microsoft and have the opportunity to be open about what we're building, and get the customer feedback early and often.

Thank you for your support 😊
