### ISSUE TITLE
Skip packages you don't want to update when running winget upgrade

### ISSUE THREAD

**Issue by sayex** [microsoft/winget-cli#1042] opened 2021-05-31 04:12 UTC
# Description of the new feature/enhancement

 
I have some packages that I don't want to upgrade to the latest version so it would be great to add a settings file to skip the update

# Proposed technical implementation details (optional)

 
when I run `winget upgrade` it will skip any package I have listed in a settings file so I don't have to manually update all packages one by one just to skip one package from updating.

**Comment by denelon** [comment] 2021-06-01 15:50
@sayex I believe this is a Duplicate of #476 Pin a package.

**Closed by denelon** 2021-06-01 15:50 UTC
Labels: Issue-Feature, Needs-Triage
