### ISSUE TITLE
upgraded package keep showing in the upgrade list

### ISSUE THREAD

**Issue by xarthurx** [microsoft/winget-cli#2433] opened 2022-08-09 12:53 UTC
### Brief description of your issue

There are two packages in my system: 
```
Name                        Id                   Version       Available  Source
--------------------------------------------------------------------------------
Logitech G HUB              Logitech.GHUB        2022.6.271036 2022.7.502 winget
Everything 1.4.1.1009 (x64) voidtools.Everything < 1.4.1.1014  1.4.1.1017 winget
```
That winget cannot recognize the upgraded version.

### Steps to reproduce

1. `winget upgrade --all` to upgrade packages.

1. Run the command again.

### Expected behavior

After upgrading, `winget` should recognize the upgraded ones.

### Actual behavior

`winget` does not recognize the upgraded ones.

The img below shows the software has actually been upgraded:
![image](https://user-images.githubusercontent.com/1921878/183651889-1fe33383-9cfc-4b44-859e-afd7d4d46162.png)

### Environment

```shell
Windows Package Manager v1.3.2091
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.795
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2091.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by Trenly** [comment] 2022-08-09 15:06
Duplicate of #2425

**Closed by Trenly** 2022-08-09 15:06 UTC
Labels: Needs-Triage
