### ISSUE TITLE
WebView2 dependency in MSIX fails to install on Azure Windows 11 22H2 Pro Gen2

### ISSUE THREAD

**Issue by AliveDevil** [microsoft/winget-cli#4473] opened 2024-05-13 10:28 UTC
### Brief description of your issue

On Azure Windows 11 22H2 Pro Gen2 VM installation of MSIX fails, when including WebView2 external dependency.
This works fine on non-Azure machines.

### Steps to reproduce

```
<Package>
  <Dependencies>
    <!--
      Refer to Directory.Packages.props (WebView2Version)
      https://learn.microsoft.com/uwp/schemas/appxpackage/uapmanifestschema/element-win32dependencies-externaldependency
    -->
    <win32dependencies:ExternalDependency Name="Microsoft.WebView2" Publisher="CN=Microsoft Windows, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" MinVersion="114.0.1823.32" Optional="false" />
  </Dependencies>
```

### Expected behavior

Installation succeeds by installing WebView2.

### Actual behavior

Installation fails with generic error.

```
[Mon May 13 12:10:21 2024]{9140} PackageDependencyInstaller -> Required missing external dependencies count: 1
[Mon May 13 12:10:21 2024]{9140} GoToState -> GoToDeployingState
[Mon May 13 12:10:21 2024]{9140} MainPage -> Installing Package Dependencies
[Mon May 13 12:10:21 2024]{9140} ProgressReporter -> Package Dependencies Progress
[Mon May 13 12:10:21 2024]{9140} ProgressReporter -> Progress Type: [Installing required frameworks 0%...]
[Mon May 13 12:10:21 2024]{9140} Failed to connect to external dependency catalog
[Mon May 13 12:10:21 2024]{9140} PackageDependencyInstaller -> Reporting error from Windows Package Manager catalog connect - 0x80070005
[Mon May 13 12:10:21 2024]{9140} GoToState -> DeploymentErrorState
[Mon May 13 12:10:21 2024]{9140} Toaster->ShowToast [Error]
[Mon May 13 12:10:21 2024]{9140} Toaster->Toast Error Data [<toast launch="App Installer" activationType="background" duration ="short"><visual><binding template = "ToastGeneric"><text>*** installation failed</text><text>App Installer failed to connect to the winget source for external package dependencies. Please report at https://aka.ms/winget-cli</text></binding></visual></toast>]
```

Log files:
- [AppInstaller-2024-05-13-12-10-13.435.log](https://github.com/microsoft/winget-cli/files/15293017/AppInstaller-2024-05-13-12-10-13.435.log)
- [AppInstaller-2024-05-13-12-10-14.398.log](https://github.com/microsoft/winget-cli/files/15293018/AppInstaller-2024-05-13-12-10-14.398.log)
- [WinGetCOM-2024-05-13-12-10-21.736.log](https://github.com/microsoft/winget-cli/files/15293016/WinGetCOM-2024-05-13-12-10-21.736.log)
- [AppxManifest.xml.txt](https://github.com/microsoft/winget-cli/files/15293015/AppxManifest.xml.txt)

### Environment

<details>
<summary>winget --info</summary>

```shell
Windows Package Manager v1.7.11261
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3527
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.11261.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```
</details>

**Comment by stephengillie** [comment] 2024-05-13 15:54
It sounds like `Microsoft.EdgeWebView2Runtime` might have an issue. Installing it in a WIndows 11 VM ended with:

> 2024-05-13 07:43:52.016 [REPO] Sending http GET request to: https://storeedgefd.dsx.mp.microsoft.com/v9.0/packageManifests/--accept-package-agreements?Market=US
2024-05-13 07:43:52.079 [REPO] Response status: 200
2024-05-13 07:43:52.086 [REPO] Opening database for ReadWrite at 'C:\Users\User\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Microsoft.Winget.Source_8wekyb3d8bbwe\installed.db'
2024-05-13 07:43:52.087 [REPO] Opened SQLite Index with version [1.6], last write [2024-05-13 07:42:19.000]
2024-05-13 07:43:52.108 [CLI ] No app found matching input criteria
2024-05-13 07:43:52.115 [CLI ] Terminating context: 0x8a150014 at C:\__w\1\s\external\pkg\src\AppInstallerCLICore\Workflows\WorkflowBase.cpp:3c8


This should probably be moved to the [winget-pkgs](https://github.com/microsoft/winget-pkgs/issues) repo, because it's only impacting 1 package.

**Comment by AliveDevil** [comment] 2024-05-13 18:09
@Trenly yes, I did try that and AppInstaller refuses to install the package. Can get you the exact error tomorrow morning (CEST).
The Microsoft.WebView2 dependency is supposed to be set like that and the only valid external dependency allowed.

**Comment by stephengillie** [comment] 2024-05-13 18:39
> @stephengillie - on your VM can you try with `--source winget` ? It seems to work on my VM

Yes, `--source winget` caused the install to proceed normally.

Correction to above - I had a bug in my testing setup. Tested again before adding `--source winget`:

```PowerShell
2024-05-13 11:21:20.877 [REPO] Sending http GET request to: https://storeedgefd.dsx.mp.microsoft.com/v9.0/packageManifests/Microsoft.EdgeWebView2Runtime?Market=US
2024-05-13 11:21:20.938 [REPO] Response status: 200
2024-05-13 11:21:20.943 [REPO] Opening database for ReadWrite at 'C:\Users\User\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Microsoft.Winget.Source_8wekyb3d8bbwe\installed.db'
2024-05-13 11:21:20.945 [REPO] Opened SQLite Index with version [1.6], last write [2024-03-19 10:48:19.000]
2024-05-13 11:21:20.967 [REPO] Finding installed package from available package using system reference search: Query:[none] Include:ProductCode='microsoft edgewebview'[Exact] Include:NormalizedNameAndPublisher='microsoftedgewebview2runtime'+'microsoft'[Exact]
2024-05-13 11:21:20.969 [CLI ] Found one app. App id: Microsoft.EdgeWebView2Runtime App name: Microsoft Edge WebView2 Runtime
2024-05-13 11:21:20.969 [CLI ] Found installed package, converting to upgrade flow
2024-05-13 11:21:20.978 [REPO] Attempting to open pinning database: C:\Users\User\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\pinning.db
2024-05-13 11:21:20.978 [REPO] ... opening existing pinning database
2024-05-13 11:21:20.978 [REPO] Opening database for Read at 'C:\Users\User\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\pinning.db'
2024-05-13 11:21:20.979 [REPO] Opened Pinning Index with version [1.0], last write [2024-01-04 12:47:12.000]
2024-05-13 11:21:20.980 [CLI ] Terminating context: 0x8a15002b at C:\__w\1\s\external\pkg\src\AppInstallerCLICore\Workflows\UpdateFlow.cpp:bc
```

**Comment by AliveDevil** [comment] 2024-05-14 07:48
This is the log output with `<win32dependencies:ExternalDependency name="Microsoft.EdgeWebView2Runtime" …`:
[AppInstaller-2024-05-14-09-42-47.739.log](https://github.com/microsoft/winget-cli/files/15304871/AppInstaller-2024-05-14-09-42-47.739.log)
[AppInstaller-2024-05-14-09-42-48.163.log](https://github.com/microsoft/winget-cli/files/15304869/AppInstaller-2024-05-14-09-42-48.163.log)
[WinGetCOM-2024-05-14-09-42-50.156.log](https://github.com/microsoft/winget-cli/files/15304870/WinGetCOM-2024-05-14-09-42-50.156.log)

**Comment by stephengillie** [comment] 2024-05-14 17:25
## TImeline: 

### 48 seconds - Unable to read Group Policy 

> [Tue May 14 09:42:48 2024]{12036} GroupPoliciesAppServiceClient -> Unable to read Group Policy from registry (0x00000002)

[AppInstaller-2024-05-14-09-42-48.163.log](https://github.com/microsoft/winget-cli/files/15304869/AppInstaller-2024-05-14-09-42-48.163.log) 

### 51 seconds - Failed to find dependency

> [Tue May 14 09:42:51 2024]{2068} Failed when attempting to find the external dependency: Microsoft.EdgeWebView2Runtime
[Tue May 14 09:42:51 2024]{2068} PackageDependencyInstaller -> Reporting error from Windows Package Manager package search for Microsoft.EdgeWebView2Runtime - 0xa0040002

[AppInstaller-2024-05-14-09-42-47.739.log](https://github.com/microsoft/winget-cli/files/15304871/AppInstaller-2024-05-14-09-42-47.739.log) 

### 51.047 seconds - File write error: 

> 2024-05-14 09:42:50.802 [REPO] Reading MSI UpgradeCodes
2024-05-14 09:42:50.989 [REPO] Reading MSI UpgradeCodes
2024-05-14 09:42:51.047 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFEB87174CC: (caller: 00007FFEB871E129) Exception(1) tid(20ec) 800700B7 Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist. `A file cannot be created if it already exists.`

[WinGetCOM-2024-05-14-09-42-50.156.log](https://github.com/microsoft/winget-cli/files/15304870/WinGetCOM-2024-05-14-09-42-50.156.log)

**Comment by JohnMcPMS** [comment] 2024-05-14 20:03
Could you try the following on the VM:
```PowerShell
> winget source add test https://cdn.winget.microsoft.com/platform
> winget install Microsoft.WebView2 -s test
```
This is a manual version of what is happening in the background and will hopefully give us better error details.

**Comment by stephengillie** [comment] 2024-05-14 21:32
This was successful in my VM. I'm interested to hear if it was in @AliveDevil's environment also. 

![image](https://github.com/microsoft/winget-cli/assets/114952565/2832aa02-736a-4844-beee-fe7c5ff35c2c)

**Comment by AliveDevil** [comment] 2024-05-15 06:51
The winget installation of WebView2 works, log[^1] attached.

AppInstaller still refuses to install the MSIX with the external dependency:
[AppInstaller-2024-05-15-08-44-28.432.log](https://github.com/microsoft/winget-cli/files/15317347/AppInstaller-2024-05-15-08-44-28.432.log)
[AppInstaller-2024-05-15-08-44-29.298.log](https://github.com/microsoft/winget-cli/files/15317348/AppInstaller-2024-05-15-08-44-29.298.log)

[^1]: [WinGet-2024-05-15-08-42-34.279.log](https://github.com/microsoft/winget-cli/files/15317321/WinGet-2024-05-15-08-42-34.279.log)

**Comment by AliveDevil** [comment] 2024-05-15 16:52
Confirmed: UAC is enabled (and on the default state).
User is member of the local Administrators group.
<details>
<summary>System Screenshot</summary>

![RDP](https://github.com/microsoft/winget-cli/assets/734738/23a15e26-872b-473c-a92b-858c210f241a)

</details>

**Comment by JohnMcPMS** [comment] 2024-05-15 17:23
Everything is pointing at some problem connecting to the COM server (although launching it just fine), and the only known issue would have been the UAC disabled.  It could be the same issue though, just manifesting some other way.

COM traces are likely the best way forward, but they will probably have information similar to what you have been redacting in your responses.  I can tell you how to collect them and you can take a shot at analyzing them, or send them along in a more secure fashion if you are comfortable.

You will need this file:
[tools/COMTrace/ComTrace.wprp](https://github.com/microsoft/winget-cli/blob/e1ee49ec871ea8abee547aa16acc635e47164339/tools/COMTrace/ComTrace.wprp)

Then:
```
[Get AppInstaller ready to Install, but don't Install yet]
> wpr.exe -start <local path to the .wprp file> -filemode
[Click the Install button, wait for it to fail]
> wpr.exe -stop com_trace.etl
```

You can inspect the resulting .etl file with: https://learn.microsoft.com/en-us/windows-hardware/test/wpt/windows-performance-analyzer

This should contain the reason for the failure, probably on the first (chronologically) trace line with the 0x80070005 error (although it is possible that the root cause has some other HRESULT).

**Comment by AliveDevil** [comment] 2024-05-15 17:37
Attached com_trace.etl (unfiltered) for:
- Open AppInstaller of MSIX
- wpr.exe -start
- Click Install
- wpr.exe -stop

[com_trace.zip](https://github.com/microsoft/winget-cli/files/15325046/com_trace.zip)

**Comment by JohnMcPMS** [comment] 2024-05-15 17:54
Yes, it does indeed look like another instance of the same issue, based on:

```
Call security blocked activation call: CLSID:{C53A4F16-787E-42A4-B304-29EFFB4BF597}, Client PID (image):1360 (C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.22.11261.0_x64__8wekyb3d8bbwe\AppInstaller.exe), Server PID (image): 0x254c (C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.22.11261.0_x64__8wekyb3d8bbwe\WindowsPackageManagerServer.exe)
```

@yao-msft was going to be looking at fixing this soon, although it isn't clear what exactly is the ACL mismatch in this case.  I don't think there is a short-term mitigation that you can do beyond simply avoiding the feature.

**Comment by AliveDevil** [comment] 2024-05-15 18:06
Interesting that I ever encountered this now on the Azure image.

My own test VMs - created using [Convert-WindowsImage](https://github.com/MicrosoftDocs/Virtualization-Documentation/tree/main/hyperv-tools/Convert-WindowsImage) - don't exhibit this issue (neither 22621, nor 22631).

**Comment by JohnMcPMS** [comment] 2024-05-15 18:47
Experts suggest a dump of the server process (WindowsPackageManagerServer.exe) if you can get it after the install attempt fails.  Also the contents of `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Ole`, but that is only helpful if the information in the process dump doesn't make sense.

**Comment by JohnMcPMS** [comment] 2024-05-15 19:06
They also suggest killing the server process just before attempting as a test (if it isn't running, then that answers the question as well).

**Comment by AliveDevil** [comment] 2024-05-15 19:20
So, I created the memory dump of WindowsPackageManagerServer, but even compressed this file exceeds the maximum allowed file size (25 MiB) with 33 MiB. Any preferred way of sharing that file?

Steps were:
- Close WindowsPackageManagerServer
- Open MSIX, install
- On error created thread dump with Task Manager

**Comment by AliveDevil** [comment] 2024-05-15 19:51
WindowsPackageManagerServer memory dump, link valid until the end of the week: https://1drv.ms/u/s!AqDF3R6HxnoJjLk_MNE2l2MtonKX0Q?e=ZWmESH

**Comment by JohnMcPMS** [comment] 2024-05-20 18:36
Sorry about the delay, some other things came up.  I think we understand what we have to do to fix this (thank you for the process dump), but now we are curious as to why it is happening.  If you are able and willing, could you confirm whether the WindowsPackageManagerServer process is elevated or not from Task Manager > Details and enabling the `Elevated` column.

**Comment by AliveDevil** [comment] 2024-05-20 19:21
No worries for the delay.

The WindowsPackageManagerServer is indeed elevated.

**Comment by yao-msft** [comment] 2024-06-28 02:03
The issue should be fixed with this pr https://github.com/microsoft/winget-cli/pull/4577
It's included in this pre-release https://github.com/microsoft/winget-cli/releases/tag/v1.8.1762

**Comment by denelon** [comment] 2024-07-09 00:45
@AliveDevil can you confirm if this was fixed in the WinGet 1.8 release?

**Closed** 2024-07-23 02:45 UTC
Labels: Issue-Bug, Needs-Author-Feedback, No-Recent-Activity

**Comment by AliveDevil** [comment] 2024-11-07 13:42
Sorry for the radio silence.
But I've managed to get the exact same error once again on Windows 11 24h2 Enterprise with 1.9:
```
winget --info
Windows-Paket-Manager v1.9.25180
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.26100.2033
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.24.25180.0

WinGet-Verzeichnisse
-----------------------------------------------------------------------------------------------------------------------------------------
Protokolle                                   %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
Benutzereinstellungen                        %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Verzeichnis für portierbare Links (Benutzer) %LOCALAPPDATA%\Microsoft\WinGet\Links
Portables Linkverzeichnis (Computer)         C:\Program Files\WinGet\Links
Portierbarer Paketstamm (Benutzer)           %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portierbarer Paketstamm                      C:\Program Files\WinGet\Packages
Portierbares Paketstamm (x86)                C:\Program Files (x86)\WinGet\Packages
Installationsprogrammdownloads               %USERPROFILE%\Downloads

Links
-----------------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store-Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale

Administratoreinstellung                  Status
-----------------------------------------------------
LocalManifestFiles                        Deaktiviert
BypassCertificatePinningForMicrosoftStore Deaktiviert
InstallerHashOverride                     Deaktiviert
LocalArchiveMalwareScanOverride           Deaktiviert
ProxyCommandLineOptions                   Deaktiviert
DefaultProxy                              Deaktiviert
```

[AppInstaller-2024-11-07-14-31-44.069.log](https://github.com/user-attachments/files/17662250/AppInstaller-2024-11-07-14-31-44.069.log)
[AppInstaller-2024-11-07-14-31-44.374.log](https://github.com/user-attachments/files/17662254/AppInstaller-2024-11-07-14-31-44.374.log)
[WinGetCOM-2024-11-07-14-31-46.951.log](https://github.com/user-attachments/files/17662253/WinGetCOM-2024-11-07-14-31-46.951.log)
[WinGetCOM-2024-11-07-14-31-48.184.log](https://github.com/user-attachments/files/17662251/WinGetCOM-2024-11-07-14-31-48.184.log)
[AppInstaller-2024-11-07-14-31-43.032.log](https://github.com/user-attachments/files/17662252/AppInstaller-2024-11-07-14-31-43.032.log)


When manually running the WebVie2 installer from %Temp%\WinGet\… I'm getting "WebView2 runtime already installed":
![Image](https://github.com/user-attachments/assets/c0726a37-5b63-4b5b-b71b-cc41295525bb)

**Comment by JohnMcPMS** [comment] 2024-11-07 18:15
The WebView2 installer is just a shim that decides which MSI to download and install ([see the evergreen bootstrapper](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution?tabs=dotnetcsharp#the-evergreen-runtime-distribution-mode)).

I will note from the logs that this is much better than before; we are doing everything including attempting to update.

```
-- AppInstaller log --
[Thu Nov  7 14:31:48 2024]{8836} External dependency already installed: Microsoft.WebView2
[Thu Nov  7 14:31:48 2024]{8836} .. with version [122.0.2365.106] which is < the required [127.0.2651.64]; update required

-- WinGetCOM log --
2024-11-07 14:31:48.313 [CLI ] Starting: 'C:\Users\user\AppData\Local\Temp\WinGet\Microsoft.WebView2.Latest\MicrosoftEdgeWebview2Setup.exe' with arguments '/silent /install'
2024-11-07 14:32:00.698 [CLI ] ShellExecute installer failed: 2147747880
```

The new issue is one that has existed for years despite my attempts to get them to change.  The WebView2 evergreen bootstrapper doesn't attempt an update if already installed (as you saw from running it manually).  Here is the public issue: https://github.com/MicrosoftEdge/WebView2Feedback/issues/3524 

At least they changed it to not show UI when we pass `/silent`.

**Comment by Mino5531** [comment] 2024-11-20 09:24
Hi, just for clarification, since our users are starting to experience a very similar problem. Users must update Microsoft Edge manually to resolve this issue or do they just need to update Microsoft WebView2?

**Comment by stephengillie** [comment] 2024-12-19 22:20
Should `Microsoft.EdgeWebView2Runtime` be a dependency?
