### ISSUE TITLE
Cannot install Package using Full Package Id

### ISSUE THREAD

**Issue by cstayyab** [microsoft/winget-cli#434] opened 2020-06-14 20:43 UTC
**Description:**
Even When Full Id is specified WinGet does not install the software.

**Steps to Reproduce:**
1. Open CMD
2. Run this command `winget install Google.Chrome`

**Expected Output:**
It should install Google Chrome because it matched the *exact* Id of Google Chrome.

**Actual Output:**
It displays the list of possible matches which also contains the exact match of the Id provided.
![Output from Winget](https://user-images.githubusercontent.com/29598866/84603641-5101cd00-aea9-11ea-93b7-00afaa382726.png)

**Conclusion:**
If the provided term fully matches an Id of a software then WinGet should install it without any prompt or showing messages.

`

**Comment by denelon** [comment] 2020-06-16 17:31
Duplicate of #292

**Closed by denelon** 2020-06-16 17:31 UTC
Labels: Needs-Triage
