### ISSUE TITLE
winget -import support URL endpoints

### ISSUE THREAD

**Issue by byjrack** [microsoft/winget-cli#3520] opened 2023-08-14 14:30 UTC
### Description of the new feature / enhancement

Trying to figure out ways to syndicate profiles of applications for associates.  I am sort of hacking it in with Intune Company Portal today by including the JSON in the intunewin file, but maintenance is a bit of a pain.

Be great if associates could provide links to a gist or other raw JSON source (supporting authentication a plus) instead of only a file path.

I can have folks also do a git clone, but git client may be part of the profile so becomes a bit of a chicken and egg.  And curl is another option to localize the file, but be great to have it native.

Also going to open an issue on the restsource repo as if import files were first class endpoints than it helps solve a number of these needs.

### Proposed technical implementation details

https://github.com/microsoft/winget-cli/blob/master/src/AppInstallerCLICore/Commands/HashCommand.cpp#L45 basically assumes a local file.  It would need to check if its local or a URL and then use the existing DODownloader to grab the file before creating the inputFile work.

If supporting authenticated destinations things get more complicated.

**Comment by Trenly** [comment] 2023-08-14 14:35
Duplicate of #1118

**Closed** 2023-08-14 14:36 UTC
Labels: Issue-Feature, Needs-Triage
