### ISSUE TITLE
Provide the capability to download and create a cached install location

### ISSUE THREAD

**Issue by noyard** [microsoft/winget-cli#1078] opened 2021-06-02 16:58 UTC
# Description of the new feature/enhancement

Capability to download a copy of the install files.  This will allow to not download the files for each computer (save bandwidth).   

# Proposed technical implementation details (optional)

winget  download Notepad++.Notepad++ \\server\share\NotepadPlus

**Comment by denelon** [comment] 2021-06-02 19:51
Duplicate of #658

**Closed by denelon** 2021-06-02 19:51 UTC
Labels: Issue-Feature, Needs-Triage
