### ISSUE TITLE
Despite using --id Microsoft.VisualStudioCode, winget returns stable and insiders instead of installing the stable version.

### ISSUE THREAD

**Issue by asifmohtesham** [microsoft/winget-cli#512] opened 2020-07-26 18:53 UTC
# Brief description of your issue
Running winget with the ```--id``` parameter returns two results

# Steps to reproduce
```winget install --id Microsoft.VisualStudioCode```

# Expected behavior
Visual Studio Code is expected to be installed

# Actual behavior
Returns a list containing VS Code and Insiders

# Environment

```none
[winget --info]
Windows Package Manager v0.1.41821 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19041.388
Package: Microsoft.DesktopAppInstaller v1.0.41821.0

Links
--------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
Licence Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
```

**Comment by megamorf** [comment] 2020-07-26 23:50
Hey @asifmohtesham, this is being tracked in other issues already so your issue is actually a duplicate of #292. Still, thank you for taking the time to report UX problems. 👍

**Comment by asifmohtesham** [comment] 2020-07-27 00:52
My bad @megamorf , I realised the redundancy after posting it. I'm sorry, just trying to contribute. This was my first bug report on GitHub. 😅

**Comment by denelon** [comment] 2020-07-27 16:36
@asifmohtesham I agree with @megamorf on this one.  Thank you for providing the feedback!

We are very close to having #292 released.

**Comment by denelon** [comment] 2020-07-27 16:36
Duplicate of #292

**Closed by denelon** 2020-07-27 16:36 UTC
Labels: Needs-Triage
