### ISSUE TITLE
Already installed app are not detected

### ISSUE THREAD

**Issue by aavdberg** [microsoft/winget-cli#216] opened 2020-05-19 21:05 UTC
# Brief description of your issue

Have installed Windows Terminal latest version and when run winget install "Windows Terminal" it gets installed again and don't detect that it was already installed.

# Steps to reproduce
run winget install for a application that you have already installed with same version.

# Expected behavior
Detect that app already is installed and give option to abort or overwrite. or text that you have to use extra parameter to overwrite.

# Actual behavior

# Environment

```none
[winget --info]
Windows Package Manager v0.1.41331 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19628.1
Package: Microsoft.DesktopAppInstaller v1.0.41331.0
Any other software?
```

**Comment by dhrrgn** [comment] 2020-05-20 01:58
A lock file, similar to most other "real" package managers, would be a good solution for this. Could have a user winget.lock file that tracks all "packages" installed, which version, etc.

This could also open up other possibilities like sharing lock files in repos and such for developers. Imagine: Onboarding Dev could import/copy the lock file, run something like `winget sync` and have all the apps needed (maybe even something like `winget import devapps.lock`).

**Comment by josh-65** [comment] 2021-05-30 12:20
I think for the sake of batch scripts it should have a toggle that can be put at the start to skip already installed packages. example winget --skipInstalled

**Comment by alex-ong** [comment] 2021-06-09 00:28
I agree with josh-65; default behavior should something logically and without user input. 

If it's already installed the default behaviour should be to re-install over the top, or uninstall/reinstall. 
By default, it installs the latest version. if this is different to what is currently installed, treat it as a different version being specified.

If a different version is specified, what should happen? Some apps support multiple versions installed (e.g. python), other's dont. 

* If it supports multiple versions, it would depend on the version specified.
E.g.
Installed python = 3.7.9, 3.6.2, 3.8.5
`winget install python --version "3.8.9"`
Now we have 4 installed
`winget install python --version "3.8"`
replaces 3.8.5 with 3.8.latest. Note that this relies on #227 first.

* If it only supports one version, then you'd expect it to replace the current installation.

**Comment by hotrungnhan** [comment] 2021-09-11 17:16
Is this sovle ?

**Comment by ItzLevvie** [comment] 2021-10-12 12:13
WinGet relies on Control Panel, so if you're seeing an application that keeps upgrading, it's either because the application doesn't have a version or the application hasn't properly updated the registry.

**Comment by bdistin** [comment] 2021-12-01 18:01
Seems like the issue is just around default behavior, and other behavior could be solved with flags rather than workarounds like uninstalling first. ie:

If it skips by default, and you want to repair the command could be something like `winget install --force`

if it reinstalls by default, and you want it to skip it could be something like `winget install --skipInstalled` like @josh-65 suggested.

**Comment by Beersteddy** [comment] 2021-12-04 12:43
I know is only 18 months since issue reported, but is there any chance to get it sorted?

**Comment by denelon** [comment] 2022-02-18 17:26
We've recently implemented changes to not display when the version is "Unknown" in upgrade and "--include-unknown" to upgrade them. We are working on:
* #1952 

Once we have the matching improved, this will become one of the next features we're looking at. One of the changes we're considering is when a user runs `winget install Microsoft.WindowsTerminal` and the current version is installed, we will inform the user. If the version is newer, then we will inform the user and switch to the "upgrade" behavior. Some installers have specific switches we must pass to them to perform an upgrade as the install would fail (Visual Studio has this behavior).

The "--force" switch will still be honored in either case.

**Comment by henryhooverville** [comment] 2022-05-23 09:11
I'm finding that winget is both really powerful - as all package managers are - but also this particular issue makes it quite impossible to script and manage an estate using scripts with winget to for example install applications and if they are installed to skip the installations. This is particularly visible with MS Teams which will force-close when installing, which you wouldn't want to force using InTune scripts because it would make MS Teams consistently unavailable for end-users.

**Comment by bobbintb** [comment] 2022-08-10 22:48
For the most part, the program not having a version in control panel seems to be an issue. I add a version number via the registry and the program no longer keeps installing. There are a few where they do not have a version number and adding it does not fix the issue. I use the same version number reported by winget.

**Comment by denelon** [comment] 2022-08-10 23:17
Many of the challenges we're trying to work through are related to installers that aren't as robust as we would like them to be. In many cases, we identify classes of issues and attempt to look at ways we can give hints to the client and users via the winget manifest. There are also additional improvements we're making on the validation side to provide better information back to PR authors so they know what metadata to add or when things don't match what was suggested.

Packages that install side-by-side are another problem space we're working on:
* https://github.com/microsoft/winget-cli/issues/2129

We're trying to meet developers where they are in terms of installer technologies and capabilities and determine reasonable default behaviors (and arguments to control behavior). Over time, we're hoping more developers will learn from user feedback associated with the Windows Package Manager to improve experiences.

**Comment by denelon** [comment] 2022-08-10 23:19
We will be working on improvements for packages that are already installed when a user runs `winget install <package>` so we look for an update rather than just blindly installing the same thing again. We would still allow --force, but the default flow would switch to upgrade logic and the user would be informed.

**Comment by denelon** [comment] 2023-02-16 19:45
@aavdberg, I believe this Issue has been resolved with our latest release.

Please confirm 😊

**Comment by KoditkarVedant** [comment] 2023-02-25 09:36
@denelon I have tried - the latest release seems to resolved the issue.

**Closed** 2023-02-27 17:43 UTC
Labels: Issue-Feature, Needs-Author-Feedback
