### ISSUE TITLE
Winget install dont work with extended characters

### ISSUE THREAD

**Issue by lourma** [microsoft/winget-cli#214] opened 2020-05-19 20:54 UTC
# Environment
Windows 10 Pro, Version 2004, OS-version:19041.264
Windows Terminal version (if applicable): 1.0.1401.0

Any other software?
No

# Steps to reproduce
I guess when a not "standard" Ascii character is used in the path.
(ie the ç charater in my username)

# Expected behavior

Installation of Powertoys

# Actual behavior

When trying to install powetoys the following occurs:
Installing ...
Installer failed with exit code: 1223
PS C:\Users\MatsLourenço>

**Comment by yao-msft** [comment] 2020-05-20 00:23
Duplicate of #181

**Closed** 2020-05-20 00:24 UTC
