### ISSUE TITLE
Misleading search results for search/install

### ISSUE THREAD

**Issue by pablotheissen** [microsoft/winget-cli#1571] opened 2021-10-11 06:47 UTC
# Brief description of your issue

# Steps to reproduce
1. Search for Sublime Text: `winget search SublimeText`
```powershell
PS C:\Users\XXX> winget search SublimeText
Name           ID                      Version      Quelle
-----------------------------------------------------------
Sublime Text 4 SublimeHQ.SublimeText.4 4.0.0.411300 winget
Sublime Text 3 SublimeHQ.SublimeText.3 3.2.2        winget
```
2. Try to install Sublime Text: `winget install "SublimeHQ.SublimeText.4"` and be confused by receiving two results
```powershell
PS C:\Users\XXX> winget install "SublimeHQ.SublimeText.4"
Mehrere Pakete mit übereinstimmenden Eingabekriterien gefunden. Bitte verfeinern Sie die Eingabe.
Name                 ID                      Quelle
----------------------------------------------------
4 Guys with Quarters 9NGZXPGG8PK2            msstore
Sublime Text 4       SublimeHQ.SublimeText.4 winget
```
3. Confirm your confusion be doing a second search: `winget search "SublimeHQ.SublimeText.4"`
```powershell
PS C:\Users\XXX> winget search "SublimeHQ.SublimeText.4"
Name           ID                      Version      Quelle
-----------------------------------------------------------
Sublime Text 4 SublimeHQ.SublimeText.4 4.0.0.411300 winget
```

# Expected behavior
* There shouldn't be different search results for `install` and `search`
* There shouldn't be obvious spam

# Actual behavior
* Search results for `install` and `search` differ, see outputs of the two commands above
* There is obvious spam

# Environment

```none
[winget --info]
Windows Package Manager v1.1.12702

Windows: Windows.Desktop v10.0.22000.194
Paket: Microsoft.DesktopAppInstaller v1.16.12702.0
```

I managed to install the correct Sublime Text via `install -e`, but that doesn't seem intuitive to me in this case.

**Comment by denelon** [comment] 2021-10-11 16:02
Duplicate of #1523

**Closed by denelon** 2021-10-11 16:02 UTC
Labels: Needs-Triage
