### ISSUE TITLE
No UnInstaller command available

### ISSUE THREAD

**Issue by evilprince2009** [microsoft/winget-cli#592] opened 2020-10-06 10:19 UTC
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

Till date winget provides `install` command for installing packages from repository. But I see no `uninstall` or `remove` command to remove installed packages. Isn't it a good idea to add a `uninstall` or `remove` command for removing packages from command line rather than doing it manually ?

**Comment by denelon** [comment] 2020-10-06 20:48
Duplicate of #121

**Closed by denelon** 2020-10-06 20:48 UTC
Labels: Issue-Feature, Needs-Triage

**Comment by keenbowl3009** [comment] 2021-11-15 20:22
> Duplicate of #121

Is that the one issue where we're supposed to dump all the "sloppy winget uninstall is broken" types of bugs?

**Comment by EqualDust** [comment] 2021-11-29 14:47
Close all dupes, pretend the feature is implemented = microsoft software product.
