### ISSUE TITLE
`winget upgrade --exact Microsoft.Teams`: Multiple installed packages found matching input criteria.

### ISSUE THREAD

**Issue by fredrikhr** [microsoft/winget-cli#1355] opened 2021-08-09 11:39 UTC
# Brief description of your issue

Unable to use `winget upgrade`, since it reports

> Multiple installed packages found matching input criteria. Please refine the input.

Even when using either/both the `--exact` or `--id` options, `winget` is still not able to disambiguate.

# Steps to reproduce

1. `winget upgrade`

```
Name                          Id                             Version          Available        Source
-----------------------------------------------------------------------------------------------------
Microsoft Teams               Microsoft.Teams                1.4.0.4167       1.4.00.19572     winget
```

2. `winget upgrade Microsoft.Teams`

```
Multiple installed packages found matching input criteria. Please refine the input.
Name            Id
-------------------------------
Microsoft Teams Microsoft.Teams
Microsoft Teams Teams
```

3. `winget upgrade --id Microsoft.Teams`

```
Multiple installed packages found matching input criteria. Please refine the input.
Name            Id
-------------------------------
Microsoft Teams Microsoft.Teams
Microsoft Teams Teams
```

4. `winget upgrade --exact Microsoft.Teams`

```
Multiple installed packages found matching input criteria. Please refine the input.
Name            Id
-------------------------------
Microsoft Teams Microsoft.Teams
Microsoft Teams Teams
```

5. `winget upgrade --exact --id Microsoft.Teams`

```
Multiple installed packages found matching input criteria. Please refine the input.
Name            Id
-------------------------------
Microsoft Teams Microsoft.Teams
Microsoft Teams Teams
```

6. `winget upgrade --id --exact Microsoft.Teams`

```
No installed package found matching input criteria.
```

# Expected behavior

Either step 3, 4 or 5 should be able to disambiguate the input criteria.

# Actual behavior

There is seemingly no way to disambiguate. There is no way for me to upgrade the package using `winget`.

# Notes

This issue is not specific to the `Microsoft.Teams` package. I observe the exact same faulty behaviour for other packages.

# Environment

```none
[winget --info]
Windows Package Manager v1.0.11692
Windows: Windows.Desktop v10.0.19043.1110
Package: Microsoft.DesktopAppInstaller v1.12.11692.0
```

**Comment by jedieaston** [comment] 2021-08-09 13:22
This is a duplicate of https://github.com/microsoft/winget-pkgs/issues/18415, [here's](https://github.com/microsoft/winget-pkgs/issues/18415#issuecomment-865930642) what the current status is.

**Comment by fredrikhr** [comment] 2021-08-10 07:52
@jedieaston 

> This is a duplicate of https://github.com/microsoft/winget-pkgs/issues/18415

I don't think that is entirely true. As I point out in the issue description:

> This issue is not specific to the `Microsoft.Teams` package. I observe the exact same faulty behaviour for other packages.

For example I experience the exact same issue with upgrading the `Microsoft.dotnet` package for the .NET SDK.

**Comment by jedieaston** [comment] 2021-08-10 12:19
`Microsoft.dotnet` is intentional as lots of people install multiple versions of the .NET SDK. What other apps are you experiencing this with?

**Comment by aavdberg** [comment] 2021-08-10 13:19
Have the same problem with Java. 
![image](https://user-images.githubusercontent.com/22030609/128874066-096a52e3-647f-4ada-85b0-fb79dbee21d4.png)

**Comment by aavdberg** [comment] 2021-08-10 13:20
![image](https://user-images.githubusercontent.com/22030609/128874278-8c88856e-b365-4da7-9e8e-f548c0e6a520.png)

**Comment by WrinkleRelease** [comment] 2021-08-10 18:45
This same behavior happened with the Slack package for me. winget would report Slack as needing an upgrade even if `winget upgrade` was run. Running `winget install Slack` installed and entirely new instance of the program with the most current version #. At this point, I had two version existing on the machine, just as @fredrikhr does in his Microsoft Teams example. Furthermore, `winget list --name Slack` produced an identical list view, with one instance having a full ID and one having none. I had to uninstall the older, original instance through **Settings > Apps & Features** as winget kept giving me the 

> Multiple installed packages found

 error when trying to run `winget uninstall --id SlackTechnologies.Slack`, even though only the original instance had that ID.

**Comment by nascentt** [comment] 2021-09-13 11:12
```
 winget upgrade
Name                                  Id                              Version     Available   Source
----------------------------------------------------------------------------------------------------
Plexamp                               plex.Plexamp                    3.4.0       3.5.0       winget
Python 3                              Python.Python.3                 3.9.5150.0  3.9.7150.0  winget
Remote Desktop                        Microsoft.RemoteDesktopClient   1.2.1672.0  1.2.2130.0  winget
PS C:\Code\PowerShell> winget upgrade plex.Plexamp
Multiple installed packages found matching input criteria. Please refine the input.
Name          Id
----------------------------------------------------
Plexamp       plex.Plexamp
Plexamp 3.4.0 {46418f0f-cea3-5740-a7e9-a0166db1e7c4}
PS C:\Code\PowerShell> winget upgrade Python.Python.3
Multiple installed packages found matching input criteria. Please refine the input.
Name                  Id
------------------------------------------------------------
Python 3              Python.Python.3
Python 3.9.5 (32-bit) {708847ae-c2de-49fb-9b85-8d2e9c991358}
PS C:\Code\PowerShell> winget upgrade Microsoft.RemoteDesktopClient
Multiple installed packages found matching input criteria. Please refine the input.
Name           Id
-----------------------------------------------------
Remote Desktop Microsoft.RemoteDesktopClient
Remote Desktop {CD7D52DB-9CB4-49A4-9554-8A229C9F6674}
```

**Comment by VincentVerweij** [comment] 2021-09-13 18:21
Hi there,

I am having the same issue as the author.
Did try `winget upgrade Microsoft.Teams`

Got the following output:
```
Multiple installed packages found matching input criteria. Please refine the input.
Name          Id
----------------------------------------------------
Microsoft Teams Microsoft.Teams
Microsoft Teams Teams
```

I specifically looked at the case, since I've seen in some issue that it is case sensitive.
And I also did try with the -e (--exact) flag, but had no luck with that either.

Another thing that I tried is this command: `winget upgrade --id Microsoft.Teams --version 1.3.0.9267`
Although I am sure about the ID, I am not quite sure whether I should put my current version in the --version flag or the to-be version (took my installed version as that seemed obvious to me to look for a specific version on my computer).

This is what the `winget upgrade` command is showing me:

```
Name                                  Id                              Version     Available   Source
----------------------------------------------------------------------------------------------------
Microsoft Teams                       Microsoft.Teams                 1.3.0.9267  1.4.00.22472  winget
```

**Comment by RobThree** [comment] 2021-09-15 11:49
![image](https://user-images.githubusercontent.com/607888/133427154-f3e15087-ab81-49ff-9f47-723c13494ff6.png)
Same issue here. v1.0.11692

I am also unable to update `Microsoft.dotnet`:
![image](https://user-images.githubusercontent.com/607888/133428019-01511b01-bd75-46d9-900b-380af4bdd395.png)

**Closed** 2021-09-24 00:16 UTC
Labels: Issue-Bug, Area-External
