### ISSUE TITLE
Updating packages resulted in losing taskbar icons

### ISSUE THREAD

**Issue by havrancek** [microsoft/winget-cli#1005] opened 2021-05-27 22:51 UTC
![_problem](https://user-images.githubusercontent.com/11238411/119906378-6521cb80-bf4e-11eb-8af7-01e739496eef.png)

I am a noob using mostly chocolatey, and wanted to see how is microsofts package manager doing... opened it, found a few packages to update and let it do the update... After that I've got what you see on the pic, I completely lost my taskbar icons, clock, date, everything and I can't find a way to restore it

**Comment by denelon** [comment] 2021-05-28 00:36
Can you submit feedback and share the link? https://aka.ms/winget-feedback
That sends logs for us to diagnose.

**Comment by havrancek** [comment] 2021-05-28 08:33
I just did. I just hope for some way to fix it. Now I am stuck as without an arm with this issue.

**Comment by havrancek** [comment] 2021-05-28 20:07
you mean with sfc command? well i tried everything i could find

**Comment by denelon** [comment] 2021-05-28 21:30
Bummer 😢 I feel your pain! 

I really hope we get to the root cause on this quickly. I want to avoid this from hitting anybody else.

**Comment by havrancek** [comment] 2021-05-29 09:10
I would be eternally grateful. Please get to the bottom of this.

**Comment by havrancek** [comment] 2021-05-31 14:25
I have uninstalled KB5003214 and I have my icons back finally

**Comment by denelon** [comment] 2021-06-01 02:04
@havrancek, I'm so glad you found a fix!!! It looks like that was a Windows update. Can you confirm?

I wanted to make sure it wasn't a package in the repository.

**Comment by havrancek** [comment] 2021-06-01 05:54
I dont know what it was, because this issue appeared only after using packages manager update, not windows update, but uninstalling this KB helped. Maybe it is connected, maybe not. But I guess it is up to you to find out, it is out of my reach. I am just happy I have my taskbar with icons back.

**Comment by denelon** [comment] 2021-10-01 21:39
We've published the v1.1 [release candidate](https://github.com/microsoft/winget-cli/releases/tag/v1.1.12653) and updated our [troubleshooting guide](https://github.com/microsoft/winget-cli/tree/master/doc/troubleshooting).

Can you confirm if this is still happening?

**Comment by denelon** [comment] 2022-03-31 17:38
@KerickHowlett,

Can you reproduce this and share logs? Ideally, run the command with "--verbose-logs" so we get more detailed information about what is happening.

**Comment by KerickHowlett** [comment] 2022-03-31 17:43
I would, but I _literally_ just ran a hard reinstall on my computer, because I need my computer running for work... and I didn't think anyone would respond to my post so fast to be honest. 😅

However, I did check the logs in the LocalStateCache from when I ran the update, and I didn't find any errors there.

Most of what I found was it calling a sqlite file labeled as "installed".

**Comment by denelon** [comment] 2022-03-31 17:48
I try to be responsive here 😊.

Let me know if you can reproduce this. I'll label it as "Needs-Author-Feedback". I'll get notifications of any replies before then, otherwise I'll be able to close it in 7 days after that. (2 weeks should be enough time to leave it open).

**Comment by KerickHowlett** [comment] 2022-04-01 14:18
I'll never complain about prompt responsiveness. Haha!

At any case, it appears I may have jumped the gun. The thing with my search icons still cropped up even after a drive formatting & clean re-install of Windows 10 and without ever using winget.

Although, I think I _may_ have figured out what was the problem: From what I can gather, I used CCleaner and Glary Utilities (not at the same time) on my system, and I think it may have deleted those files by mistake. To further compound matters, my OneDrive, for whatever reason, thought it'd be a good idea to sync those files, so no matter how many hard re-installs I did, as soon as OneDrive synced up my file system, it would again remove those icon files.

I'm assuming its because OneDrive prioritizes the file system saved in OneDrive over what's currently in local. Normally, I get that and wouldn't mind so much (even if annoying), but there isn't any available means to fix it -- not even any documentation for a workaround.

Anyway, I hope I'm right on this.

As an attempted fix, I took all the files I wanted to keep in OneDrive and backed them up into my Google Drive before completely wiping the former clean.

Then, just to be on the safe side, I disabled the autorun for OneDrive, so it won't have the chance of synching anything up in case just simply deleting the files within OneDrive wasn't enough.

Once I'm finished re-configuring my machine, I'm gonna create a back-up image of my Windows setup (via the way it used to be done for Windows 7). That way, when I re-enable the sync for OneDrive and it still ends up deleting those icons again, I'll have a save image to fallback on.

(Sadly, just creating and using a Restore Point does not work.)

I'm posting the details for my workaround/possible fix here, so that way if anyone else encounters this issue, they may hopefully find this post to help solve their problem.

**Comment by denelon** [comment] 2022-04-01 14:26
Thanks for sharing! If I see reports like this a few more times, I'll post in our troubleshooting docs, or if you would like, feel free to make a PR 😊

https://github.com/microsoft/winget-cli/tree/master/doc/troubleshooting

**Comment by KerickHowlett** [comment] 2022-04-01 14:46
Sure, but like I said, I don't believe it was caused by winget in my particular case.

I only thought it was, because the outcome of my bug appeared to be identical to this one. It just so happened to be caused by a different source.

Although, I suppose it's possible it was deleted by a combination of winget and some Windows update.

Again, I'm not sure what the ultimate cause of it was.

Nevertheless, I'll be sure to include the workaround to the troubleshoot documentation when I can get around to it. ;)

**Comment by KerickHowlett** [comment] 2022-04-08 16:05
Apologies for not responding sooner, but y'all can close this ticket.

**Closed** 2022-04-08 16:30 UTC
Labels: Issue-Bug, Needs-Author-Feedback

**Comment by CXwudi** [comment] 2023-03-18 04:55
Sorry for disturbing everyone here, but this is happening to me even with current `v1.4.10173` version of winget.

I just updated two apps and now both apps lost their icons. However, their icons are fine in Start menu, or during the preview windows, or using alt-tab. It is only the taskbar that has the icon missing
![image](https://user-images.githubusercontent.com/17377423/226085478-55550d60-0b5a-4c7e-a7eb-3f30b21064dd.png)
