### ISSUE TITLE
`winget update --all` does not automatically update packages

### ISSUE THREAD

**Issue by stallam-unb** [microsoft/winget-cli#4270] opened 2024-03-13 13:10 UTC
### Brief description of your issue

Until recently, running `winget update --all` or `winget upgrade --all` would (barring a couple of exceptions), download any relevant packages and update them automatically. However, recently (maybe for a couple of weeks), it just displays the available updates and just exits.

### Steps to reproduce

Run: `winget update --all`

### Expected behavior

Except to see a list of available candidates followed by downloading the installers and updating the relevant applications.

### Actual behavior

Only printing out the list of available updates and does nothing after.

### Environment

```shell
Windows: Windows.Desktop v10.0.22631.3155
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10582.0
```

**Comment by Trenly** [comment] 2024-03-13 13:14
Try using the pre-release version [v1.7.10661](https://github.com/microsoft/winget-cli/releases/tag/v1.7.10661). This is a known issue in v1.7.10582. If you still run into problems, you can report in the tracking issue here https://github.com/microsoft/winget-cli/issues/4219

Duplicate of https://github.com/microsoft/winget-cli/issues/4219

**Closed** 2024-03-13 13:14 UTC
