### ISSUE TITLE
Skip already installed packages

### ISSUE THREAD

**Issue by josh-65** [microsoft/winget-cli#1061] opened 2021-06-01 17:53 UTC
# Description of the new feature/enhancement
It wastes a lot of time and most of the time reset settings when winget reinstall the same program

# Proposed technical implementation details (optional)
It should look at the package name, author and version to determine if it the same and not install it. It could also say that the package is already installed

**Comment by denelon** [comment] 2021-06-01 22:14
@josh-65 is your comment the result of trying to `winget install` a package already on your system, or was this related to another command like `winget upgrade`?

**Comment by josh-65** [comment] 2021-06-01 22:19
I'm using `winget install`

**Comment by iDolmatov** [comment] 2021-06-01 22:40
I do not agree that the installation should be canceled (skipped).
If you run the classic installer (not MSI or appx) on the system, then you can install the program in the same folder. The behavior of an installer in terms of the presence of a program directly depends on the developer of this installer. This includes saving or overwriting settings.
Here developer can release display a question about again install if an installed program is found. In quiet mode (-q --quiet), suppress the prompt and force reinstallation of the program.

**Comment by iDolmatov** [comment] 2021-06-01 23:29
See also issue https://github.com/microsoft/winget-cli/issues/929 ("winget should not install an already installed package").

**Comment by denelon** [comment] 2022-01-05 22:49
Duplicate of #929

**Closed** 2022-01-05 22:49 UTC
Labels: Issue-Feature, Catalog-Health
