### ISSUE TITLE
Define Download Directory

### ISSUE THREAD

**Issue by teddue** [microsoft/winget-cli#3218] opened 2023-05-04 06:10 UTC
### Description of the new feature / enhancement

I want to globally change the Winget Download Directory

In our company we have to use separate administrator accounts. Because of this about half the apps I wanted to install using winget failed because the AppData Local Directory isn't accessible to the administrator account, 

If one could set the directory oneself it would be way easier to use winget.

**Comment by denelon** [comment] 2023-05-04 22:26
Duplicate of #1208

I changed the title on the other issue to match this title as it's more generic.

**Closed by denelon** 2023-05-04 22:26 UTC
Labels: Issue-Feature, Needs-Triage
