### ISSUE TITLE
Support binary package

### ISSUE THREAD

**Issue by rafee** [microsoft/winget-cli#510] opened 2020-07-23 00:08 UTC
# Description of the new feature/enhancement

Support installation of standalone command line binary package. I am trying to create a manifest for standalone .exe file for terraform. However, winget tries to execute the file after download, which isn't that relevant in case of binary standalone installers.

# Proposed technical implementation details (optional)
 
Support binary installers with specific destination folder.

**Comment by denelon** [comment] 2020-07-23 20:58
Duplicate of #182

**Closed by denelon** 2020-07-23 20:58 UTC
Labels: Needs-Triage
