### ISSUE TITLE
Multiple apps found matching input criteria when trying to install Microsoft.dotnet

### ISSUE THREAD

**Issue by Amoenus** [microsoft/winget-cli#1669] opened 2021-11-03 20:24 UTC
### Brief description of your issue

When I try to update `Microsoft.dotnet`, `winget` does not respect `-e` flag

### Steps to reproduce

Have `dotnet SDK` installed without `winget`

run any of the following:
```Powershell
winget upgrade -e --id "Microsoft.dotnet"
```
```Powershell
winget upgrade --id "Microsoft.dotnet" -e
```
```Powershell
winget upgrade -e "Microsoft .NET SDK"
```
```Powershell
 winget upgrade Microsoft.dotnet
```

### Expected behavior

The flag is respected and update proceeds normally

### Actual behavior

No matter what combination of flags is used the `Multiple installed packages found matching input criteria. Please refine the input.` error is displayed

![image](https://user-images.githubusercontent.com/5391396/140185927-bba72457-9b52-45ae-80d0-c0979983619f.png)

### Environment

```shell
Windows Package Manager v1.1.12702
Windows: Windows.Desktop v10.0.22489.1000
Package: Microsoft.DesktopAppInstaller v1.16.12702.0

====
Conflicting software:
Microsoft .NET SDK               Microsoft.dotnet
Microsoft .NET SDK 5.0.100 (x64) {c0d1830b-4a91-46dc-981e-ebf607e87cfc}
```

**Comment by denelon** [comment] 2021-11-04 14:06
Duplicate of #1142

**Closed by denelon** 2021-11-04 14:06 UTC
Labels: Needs-Triage
