### ISSUE TITLE
Can't detect installed Microsoft Store Win32 (not UWP) apps by ID (example: PowerToys)

### ISSUE THREAD

**Issue by o-l-a-v** [microsoft/winget-cli#1702] opened 2021-11-13 21:13 UTC
#### Background

PowerToys is available in Microsoft Store as Win32 app, with ID ```XP89DCGQ3K6VLD```.

I consider apps that has been submitted and allowed inside Microsoft Store to more safe to install, than what has been submitted to the ```winget-pkgs``` manifest. (Maybe that's a wrongful assumption, but that's not really the point here.) Thus I'd like to to use Microsoft Store ID rather than ```winget-pgks``` ```PackageIdentifier``` where possible.

#### Details

```winget install XP89DCGQ3K6VLD``` works.

```winget list XP89DCGQ3K6VLD``` and ```winget upgrade XP89DCGQ3K6VLD``` does not, winget says "No installed package found matching input criteria".

Instead one have to use ```winget list Microsoft.PowerToys``` and ```winget upgrade Microsoft.PowerToys```.

This seems to be a gap in functionalitym or a not yet thought about scenario. Or is this intended behavior?

### Steps to reproduce

Designed to be run from SYSTEM context, as I'm labbing on automating updates of applications from Intune.

```powershell
#Requires -RunAsAdministrator
<#
    .SYNOPSIS
        Testing limitations with Winget + Microsft Store apps that is not UWP.
#>


# Find winget-cli from SYSTEM context
$Winget = [string](
    '{0}\AppInstallerCLI.exe' -f (
        [System.IO.Directory]::GetDirectories(
            ('{0}\WindowsApps' -f $env:ProgramW6432),
            'Microsoft.DesktopAppInstaller_*x64*_8wekyb3d8bbwe'
        )
    )
)

# Check winget version
cmd /c ('"{0}" --version' -f $Winget)
cmd /c ('"{0}" --info' -f $Winget)

# Check for update
## Does not work
cmd /c ('"{0}" list --id XP89DCGQ3K6VLD' -f $Winget)
## Works
cmd /c ('"{0}" list --id Microsoft.PowerToys' -f $Winget)
cmd /c ('"{0}" upgrade' -f $Winget)

# Install
## Works
cmd /c ('"{0}" install --id XP89DCGQ3K6VLD --silent --accept-package-agreements --accept-source-agreements' -f $Winget)
cmd /c ('"{0}" install --id Microsoft.PowerToys --silent --accept-package-agreements --accept-source-agreements' -f $Winget)

# Update
## Does not work
cmd /c ('"{0}" upgrade --id XP89DCGQ3K6VLD --silent --accept-package-agreements --accept-source-agreements' -f $Winget)
## Works
cmd /c ('"{0}" upgrade --id Microsoft.PowerToys --silent --accept-package-agreements --accept-source-agreements' -f $Winget)
```

### Expected behavior

Preferably Microsoft Store packages that is wrapped up Win32 installers should have a detection rule.

### Actual behavior

```No installed package found matching input criteria.```

### Environment

```shell
PS C:\WINDOWS\system32> cmd /c ('"{0}" --info' -f $Winget)
Windows Package Manager v1.1.0
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.318

Logs: %TEMP%\WinGet

Links               
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

PS C:\WINDOWS\system32>
```

**Comment by denelon** [comment] 2021-11-16 00:32
Duplicate of #1562

**Closed by denelon** 2021-11-16 00:32 UTC
Labels: Needs-Triage
