### ISSUE TITLE
build a new package based on currently installed winget applications

### ISSUE THREAD

**Issue by craigsn** [microsoft/winget-cli#1095] opened 2021-06-03 17:08 UTC
# Description of the new feature/enhancement
It would be very valuable, at least for me, to be able to run a winget command on to get a listing of all of the winget packages that are currently installed on my computer. And then be able to create a package that includes those apps. So  now, if I go to another computer, or upgrade my existing computer, I can just install that package and all of the apps I want are now installed with no other input on my part.

# Proposed technical implementation details (optional)

Something like winget -getinstalled

**Comment by denelon** [comment] 2021-06-03 22:19
@craigsn the `winget export` command and `winget import` commands were designed for this exact use case.

**Comment by denelon** [comment] 2021-06-03 22:19
Duplicate of #220

**Closed by denelon** 2021-06-03 22:19 UTC
Labels: Issue-Feature
