### ISSUE TITLE
Cache installation files when installer fails to get permissions via UAC

### ISSUE THREAD

**Issue by ChSchott** [microsoft/winget-cli#2422] opened 2022-08-05 18:08 UTC
The installation of a package fails when the user doesn't grant permissions via UAC.
To speed up a second installation attempt, especially with large packages, caching of the application files might improve performance.

**Comment by denelon** [comment] 2022-08-05 21:38
Duplicate of #2003

* #2003

**Closed by denelon** 2022-08-05 21:38 UTC
Labels: Needs-Triage
