### ISSUE TITLE
Are there package parameters in Winget for specific applications like in Chocolatey?

### ISSUE THREAD

**Issue by ppvnf** [microsoft/winget-cli#2553] opened 2022-09-26 21:56 UTC
### Brief description of your issue

I think it's easier to explain what I mean by giving an example (VirtualBox). In Chocolatey if I want to install VirtualBox without adding a desktop icon, but enabling the extension pack, I would use  `choco install virtualbox --params "/NoDesktopShortcut /ExtensionPack"`. It's also possible to use `choco info virtualbox` to find out about the parameters of certain package. I am not very experienced with Winget, so I would like to know if it has a similar feature (if it doesn't I would like to know the reason and suggest it to be implemented). I tried `winget show virtualbox` but couldn't find any package parameter. In the [docs ](https://learn.microsoft.com/en-us/windows/package-manager/winget/install) the only similar package parameters I saw were `--locale`, `-l` and `-a`. Thank you in advance.

Related:
https://github.com/microsoft/winget-cli/issues/1403
https://github.com/microsoft/winget-cli/issues/1545

**Comment by ppvnf** [comment] 2022-09-26 22:29
@denelon Maybe I should've posted this on https://github.com/microsoft/winget-cli/issues/1403 instead of creating a new issue (if so please close this one). You are talking about implementing something similar in Winget, right?

**Comment by denelon** [comment] 2022-09-26 22:31
Duplicate of #1403

**Closed by denelon** 2022-09-26 22:31 UTC
Labels: Issue-Docs, Needs-Triage
