### ISSUE TITLE
Visual C++ Forces Restart during `upgrade --all`

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-cli#1424] opened 2021-08-31 23:06 UTC
# Brief description of your issue

# Steps to reproduce
1. Have multiple packages available for upgrade. Ensure one of them is `Microsoft.VC++2013Redist-x64` and that it is not the last one in the list.
2. Run the command `winget upgrade --all --silent`

# Expected behavior
The packages will be installed without restart. If a restart is required upon completion of all upgrades, a timed shutdown should be scheduled 
(e.g the equivalent of `shutdown -r -t 60 -d p:4:2`

\- OR -

The upgrade process will resume after the restart

# Actual behavior
The Visual C++ redistributable is being installed and windows is immediately restarted, interrupting all other upgrades and halting the upgrade process.

# Environment

```none
PS C:\WINDOWS\system32> winget --info
Windows Package Manager v1.0.11692
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.1165
Package: Microsoft.DesktopAppInstaller v1.12.11692.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
--------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
```

```raw
PS C:\WINDOWS\system32> winget upgrade
Name                                            Id                                     Version      Available    Source
-----------------------------------------------------------------------------------------------------------------------
Visual Studio Enterprise 2019                   Microsoft.VisualStudio.2019.Enterprise 16.10.3      16.11.2      winget
TeamViewer                                      TeamViewer.TeamViewer                  15.20.6      15.21.6      winget
obs-virtualcam                                  Fenrirthviti.obs-virtual-cam           Unknown      2.0.5        winget
Microsoft Visual C++ 2013 Redistributable (x64) Microsoft.VC++2013Redist-x64           12.0.30501.0 12.0.40664.0 winget
Node.js                                         OpenJS.NodeJS                          16.6.1       16.8.0       winget
Azure Data Studio                               Microsoft.AzureDataStudio              1.31.1       1.32.0       winget
Microsoft Azure CLI                             Microsoft.AzureCLI                     2.27.0       2.27.2       winget
Microsoft Visual C++ 2013 Redistributable (x86) Microsoft.VC++2013Redist-x86           12.0.30501.0 12.0.40664.0 winget
```
[Logs_Upgrade_All_SIlent.zip](https://github.com/microsoft/winget-cli/files/7087167/Logs_Upgrade_All_SIlent.zip)
[Replicatable With VC++2013Residst-x64.zip](https://github.com/microsoft/winget-cli/files/7087186/Replicatable.With.VC%2B%2B2013Residst-x64.zip)

**Comment by brhahlen** [comment] 2021-09-01 07:49
Same issue here, as well as the fact that after successfully upgrading, it will still be listed as needing an upgrade.

**Comment by quhxl** [comment] 2021-09-01 10:13
> 
> 
> Same issue here, as well as the fact that after successfully upgrading, it will still be listed as needing an upgrade.

This is a mistake we have already encountered. It is related to the fact that VC++2013 does not uninstall older versions, like VC++2015-2019 does. So the update is still shown for the old version, which remains on the PC. However, the new update is already on the PC. We could specify as a parameter that the previous version should be uninstalled, however we are not sure if this will affect the functionality of other programs because they may rely on just that one version of the redistributables. If someone is familiar with the VC++ redistributables and knows if uninstalling doesn't cause problems, this could be fixed too.

**Comment by quhxl** [comment] 2021-09-01 10:15
Also related: #994

**Comment by jedieaston** [comment] 2021-09-01 13:58
As I understand it, binary compatibility is guaranteed for minor versions of the redists, but not major versions (i.e. if an app requires 2013 any version of 2013 will work, but 2015 will not satisfy the requirement). As such, `uninstallPrevious` should be safe.

Citation: https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B#ABI. But winget-cli is written in C++, maybe a maintainer can confirm?

**Comment by denelon** [comment] 2021-09-01 15:29
Duplicate of #229

**Closed by denelon** 2021-09-01 15:29 UTC
Labels: Needs-Triage
