### ISSUE TITLE
Command line option to disable "animations" 

### ISSUE THREAD

**Issue by Delphi251189** [microsoft/winget-cli#4029] opened 2024-01-04 20:42 UTC
### Description of the new feature / enhancement

When CLI output consumed by other apps, it will be nice to reduce output and analyze only payload.
Bellow is log from my application, which checks for update using winget tool.
At first glance it will be obvious what I mean by "ANIMATION" and "PAYLOAD"

![Capture](https://github.com/microsoft/winget-cli/assets/30734336/beb9d71c-369b-4aaf-b6ab-87ff677e3497)

**Comment by Delphi251189** [comment] 2024-01-04 20:46
![Capture](https://github.com/microsoft/winget-cli/assets/30734336/911c6095-e5ee-490e-9ebc-2a0aa84f09bb)

**Comment by Delphi251189** [comment] 2024-01-04 20:51
this is what winget prints to stdout.
of course, it is nice to see in terminal progress bar, download status and any other signs that process still alive, 
but in case when cli tool used by another app, it will be better to have flag like --no-cli-animation

**Comment by mdanish-kh** [comment] 2024-01-04 21:21
For automation scenarios or usage by other applications, consider using the [PowerShell module](https://www.powershellgallery.com/packages/Microsoft.WinGet.Client/1.6.3133.0) or the [COM API](https://github.com/microsoft/winget-cli/blob/master/doc/specs/%23888%20-%20Com%20Api.md)

**Comment by mdanish-kh** [comment] 2024-01-04 21:27
Duplicate of #3494

**Closed** 2024-01-04 21:27 UTC
Labels: Issue-Feature, Needs-Triage
