### ISSUE TITLE
install winget on Server SKU [No applicable app licenses found]

### ISSUE THREAD

**Issue by brwilkinson** [microsoft/winget-cli#776] opened 2021-03-03 20:29 UTC
I would like to install winget on server sku.

windows server 2022

```powershell
# add pre-reqs
Add-AppxPackage -Path F:\source\tools\Microsoft.VCLibs.x64.14.00.Desktop.appx
# add winget
Add-AppxPackage -Path F:\source\tools\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle

get-command winget

CommandType Name       Version Source
----------- ----       ------- ------
Application winget.exe 0.0.0.0 C:\Users\brw\AppData\Local\Microsoft\WindowsApps\winget.exe

winget search p

Program 'winget.exe' failed to run: No applicable app licenses found   At line:1 char:1
```

**Comment by jedieaston** [comment] 2021-03-13 23:08
I can replicate this on Server 2019 with GUI.

**Comment by brwilkinson** [comment] 2021-03-13 23:11
@jedieaston 

I thought I get an unsupported pre-requisites on Server 2019 ? 

Did you install some other packages ? Other than the ones listed above ?

**Comment by jedieaston** [comment] 2021-03-14 17:35
It’s possible my VM is missing updates, but I’ve gotten this error on 2019 when I have the prerequisites installed.

**Comment by matsmcp** [comment] 2021-03-16 10:52
I replicated it on 2022 too. 
Both virtual and Physical servers

**Comment by denelon** [comment] 2021-03-16 17:39
Duplicate of #700

**Closed by denelon** 2021-03-16 17:39 UTC
Labels: Issue-Feature
