### ISSUE TITLE
When upgrading or uninstalling Helix.Helix, winget hangs after "Starting package uninstall..."

### ISSUE THREAD

**Issue by kobakt** [microsoft/winget-cli#3831] opened 2023-10-30 06:07 UTC
### Brief description of your issue

Wanted to upgrade Helix.Helix from 23.05 to 23.10. I ran "winget upgrade Helix.Helix." Everything seemed fine until  winget reaches step "Starting package uninstall..." and then nothing seems to happen. CPU usage of winget seems high, 20%. I tried looking at the logs, and nothing shows once it starts uninstalling. Last log message is just "[CLI ] Successfully extracted archive".

Same happens with "winget uninstall Helix.Helix"

### Steps to reproduce

With Helix.Helix installed, run"winget upgrade Helix.Helix" or "winget uninstall Helix.Helix". Wait till "Starting package uninstall..." appears. Then winget seems to hang.

### Expected behavior

I expected Helix.Helix to upgrade to version 23.10

### Actual behavior

Winget hangs after "Starting package uninstall..." 

Full terminal:
\>winget upgrade Helix.Helix
Found Helix [Helix.Helix] Version 23.10
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package uninstall...

### Environment

```shell
Windows Package Manager (Preview) v1.7.2782-preview
Windows: Windows.Desktop v10.0.22621.2428
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.2782.0

Also happens with the last stable/release v1.6.2771
```

**Comment by BrandonWanHuanSheng** [comment] 2023-10-30 09:27
There is too many file there.

**Comment by mdanish-kh** [comment] 2023-10-30 15:47
@kobakt This may be related:

- https://github.com/microsoft/winget-cli/issues/3279

Can you try the recommendations listed in that issue to see if it helps resolve the issue?

**Comment by kobakt** [comment] 2023-10-31 05:42
Yes, that fixed it.

**Comment by mdanish-kh** [comment] 2023-10-31 05:54
Great! I'll go ahead and mark this as a duplicate of that issue for tracking purposes

Duplicate of #3279

**Closed** 2023-10-31 05:54 UTC
Labels: Issue-Bug
