### ISSUE TITLE
How to hold package update?

### ISSUE THREAD

**Issue by nazar2sfive** [microsoft/winget-cli#1179] opened 2021-06-18 02:09 UTC
![image](https://user-images.githubusercontent.com/12841320/122495630-183f8b00-d00a-11eb-9c69-f663837a7cd1.png)

i want to 

```
winget --hold Mega.MEGASync
winget --upgrade all
```

**Comment by denelon** [comment] 2021-06-18 17:49
Duplicate of #476

**Closed by denelon** 2021-06-18 17:49 UTC
Labels: Needs-Triage
