### ISSUE TITLE
Export/Import apps list

### ISSUE THREAD

**Issue by brunovieira97** [microsoft/winget-cli#220] opened 2020-05-19 21:37 UTC
# Description of the new feature/enhancement

Allow the user to export a list of all currently installed apps from WinGet.

This list can then be imported (with the specific versions too) on WinGet and its apps will be batch installed. Useful for a "dotfiles-based" computer setup, where I just have a winget-apps.json and can set my machine up with a single command.

**Poposed commands:**
 * `winget export <app-list>`
   * Here the user can specify an app list for exporting, or use `--all` or `*` for exporting the entire list.
 * `winget import <file-path>`

---
Edited by denelon:

**Stable Feature**
`winget import packages.json` - installs packages referenced in packages.json (requires sources to be configured).
`winget import -?` - displays help for the import command.

**Experimental Feature**
`winget export packages.json` - generates export file for packages in Add / Remove Programs matching installed sources.
`winget export -?` - displays help for the export command.

Note: export depends on list also being enabled.

`winget features` - displays all experimental features and their status
`winget settings` - launches settings.json to configure settings like experimental features

Edited: experimental status

**Comment by gibfahn** [comment] 2020-05-24 17:43
For an example in other package managers see Homebrew's [brew bundle](https://github.com/Homebrew/homebrew-bundle).

Nice thing about it is it's easy to add support for other tools like [Casks](https://github.com/Homebrew/homebrew-cask), [mas](https://github.com/mas-cli/mas), and [whalebrew](https://github.com/whalebrew/whalebrew), all of which are (or started as) third-party extensions to brew.

**Comment by denelon** [comment] 2020-05-28 16:42
This looks like a duplicate of #155 and #156

**Comment by denelon** [comment] 2021-03-04 00:07
The schema for the import file is located at https://aka.ms/winget-packages.schema.1.0.json

**Comment by denelon** [comment] 2021-03-18 22:40
I'll be publishing a build with "import" enabled next week if testing goes well. I'm publishing a sample file here as a starting point.

```JSON
{
	"$schema" : "https://aka.ms/winget-packages.schema.1.0.json",
	"CreationDate" : "2021- 3-18 13:14:44.599",
	"Sources" : 
	[
		{
			"Packages" : 
			[
				{
					"Id" : "Microsoft.Whiteboard"
				}
			],
			"SourceDetails" : 
			{
				"Argument" : "https://winget.azureedge.net/msstore",
				"Identifier" : "Microsoft.Winget.MSStore.Source_8wekyb3d8bbwe",
				"Name" : "msstore",
				"Type" : "Microsoft.PreIndexed.Package"
			}
		},
		{
			"Packages" : 
			[
				{
					"Id" : "Microsoft.PowerToys"
				}
			],
			"SourceDetails" : 
			{
				"Argument" : "https://winget.azureedge.net/cache",
				"Identifier" : "Microsoft.Winget.Source_8wekyb3d8bbwe",
				"Name" : "winget",
				"Type" : "Microsoft.PreIndexed.Package"
			}
		}
	],
	"WinGetVersion" : "0.2.10771"
}
```

**Comment by denelon** [comment] 2021-03-18 22:41
![WingetImport](https://user-images.githubusercontent.com/61799811/111706906-5ad1ab80-8800-11eb-93a1-9df0a00e33da.gif)

**Comment by denelon** [comment] 2021-04-02 15:10
Note: if you have a terminal or shell in your import, it will restart and interrupt the flow of package installation. I've had success with one of these packages if it's the last one in the list.

**Comment by denelon** [comment] 2021-04-22 18:13
Import was just released as a stable feature https://github.com/microsoft/winget-cli/releases/tag/v-0.3.11102-preview.

**Comment by gioluca2** [comment] 2021-05-04 21:11
Is there a site where I can select apps and create a json file?
On winstall . app you can export only a batch file...

**Comment by denelon** [comment] 2021-05-05 16:14
@MehediH This looks like a request to add support to provide a packages.json file.

@gioluca2 You can enable export in your settings to run an export. Then you can modify that file with the packages you want included for import.

**Comment by quangkieu** [comment] 2021-05-06 04:51
I wonder if export feature could also output list of generic unknown source and its version info from registry if available
How about driver info? As now Windows would like to push to DCH type, I though this type of driver give Windows more info and control.
Or those hidden OEM pre-install programs?

**Comment by denelon** [comment] 2021-05-06 14:15
@quangkieu what scenario would providing the list of applications without a known source address? You've piqued my interest :smile:

**Comment by gioluca2** [comment] 2021-05-06 21:04
> 
> @gioluca2 You can enable export in your settings to run an export. Then you can modify that file with the packages you want included for import.

Sorry but I don't understand which settings are you talking about. Can you help me?

**Comment by denelon** [comment] 2021-05-06 22:01
@gioluca2 you can execute `winget settings` your default .json editor will open. If you have Visual Studio Code configured as your default editor the schema file at the top will help provide auto-complete and context aware help.

You can enable the "export" ("list" is also required) as an experimental feature to generate an initial file to start with:
`winget export packages.json` for example.

Then you can edit the packages listed in that file to build an import.
`winget import packages.json` for example.

Here is a sample for settings.json:

```JSON
{
    "$schema": "https://aka.ms/winget-settings.schema.json",
    "experimentalFeatures": {
        "list": true,
        "export": true
    }
}
```

**Comment by gioluca2** [comment] 2021-05-06 22:23
The command "winget list" returns wrong ids. If I try to import that id I receive error.

**Comment by denelon** [comment] 2021-05-06 23:18
@gioluca2 the "Id" needs to be the same value as "PackageIdentifier" in the v1.0 manifest schema. For example, "7-zip" should be "7zip.7zip"
![7zip](https://user-images.githubusercontent.com/61799811/117376784-b5919600-ae86-11eb-8d3d-80c95b3c172d.png)

**Comment by gioluca2** [comment] 2021-05-06 23:22
And so I have to search all packages one by one...

**Comment by denelon** [comment] 2021-05-06 23:24
We're still working on the logic for list (it drives export and several other features). I've made several changes recently to manifests to improve matching (including 7-zip). We have a client coming out in the next few days with changes implemented to improve matching logic. We will probably continue working on this area. It's the reason "list", "upgrade", "uninstall", and "export" are all still experimental features.

**Comment by Airkro** [comment] 2021-05-12 01:24
will import support interactive to exclude some packages?

**Comment by denelon** [comment] 2021-05-12 15:48
@Airkro feel free to request the feature covering the scenario you are interested in 😄. The initial intent for import was to give a single command to install a set of packages. Most of the users requesting that capability in asks I received were looking for unattended use cases. I think we will want to be able to have commands or arguments (and an import file structure) to support many other scenarios. Several installers don't support silent/unattended behavior. In order to allow those into the repository we need to ensure the silent/unattended scenario works for the other commands in the Windows Package Manager client.

**Comment by gioluca2** [comment] 2021-05-18 09:45
I can't find real ID of bitdefender, ffbatch and office 2019. Can you help me?

**Comment by denelon** [comment] 2021-05-18 14:55
@gioluca, I did a search for all three. "Microsoft.Office" version 16.0.1329.20371 is available. You might need to create a "Help-Wanted" Issues in the https://github.com/microsoft/winget-pkgs repository to ask for the other two packages to be added.

**Closed** 2021-05-20 21:07 UTC
Labels: Experimental, Issue-Feature, Size-L
