### ISSUE TITLE
Winget Import/Export is missing the ability to make use of overrides

### ISSUE THREAD

**Issue by liamfoneill** [microsoft/winget-cli#1849] opened 2022-01-13 14:37 UTC
### Description of the new feature / enhancement

I would like to leverage Winget Import and Export for all of the applications on my machines but for certain applications like Visual Studio 2022, I make use of overrides to enable certain workloads like Azure. Example: 

winget install Microsoft.VisualStudio.2019.Enterprise --silent --override "--wait --quiet --addProductLang En-us --add Microsoft.VisualStudio.Workload.Azure"

However, if I use Winget Export it only exports the package itself but ignores any overrides I used when installing it.

### Proposed technical implementation details

Change the export functionality to include any override strings used when installing the package.

**Comment by jedieaston** [comment] 2022-01-13 15:10
Duplicate of #1512 

(I want this too please)

**Closed by jedieaston** 2022-01-13 15:10 UTC
Labels: Issue-Feature, Needs-Triage
