### ISSUE TITLE
Git is not showing in upgrade

### ISSUE THREAD

**Issue by YsHaNgM** [microsoft/winget-cli#822] opened 2021-03-26 14:39 UTC
# Git is not listed in `winget upgrade`
I have following experimental experimental features enabled:
```
Feature                 Status   Property            Link
-----------------------------------------------------------------------------------
Command Sample          Disabled experimentalCmd     https://aka.ms/winget-settings
Argument Sample         Disabled experimentalArg     https://aka.ms/winget-settings
Microsoft Store Support Disabled experimentalMSStore https://aka.ms/winget-settings
List Command            Enabled  list                https://aka.ms/winget-settings
Upgrade Command         Enabled  upgrade             https://aka.ms/winget-settings
Uninstall Command       Disabled uninstall           https://aka.ms/winget-settings
Import Command          Disabled import              https://aka.ms/winget-settings
Rest Source Support     Disabled restSource          https://aka.ms/winget-settings
```
I have git installed and there's a newer version available:
```
> winget list | sls Git
Git version 2.30.0.2                               Git_is1                                            2.30.0.2
> winget search git.git
Name Id      Version
--------------------
Git  Git.Git 2.31.0
```
This results in git is not able to upgrade.
# Steps to reproduce

With an old version of Git installed. Run `winget upgrade git.git`.

# Expected behavior

Git to be upgrade to the lastest version.
# Actual behavior

Git is not recognised as upgradable.
```
> winget upgrade
Name      Id                  Version Available Source
------------------------------------------------------
PowerToys Microsoft.PowerToys 0.31.1  0.33.1    winget
> winget upgrade git.git
No installed package found matching input criteria.
```

# Environment

```none
Windows Package Manager v0.2.10771 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.867
Package: Microsoft.DesktopAppInstaller v1.11.10771.0
```

**Comment by denelon** [comment] 2021-03-26 14:55
Duplicate of #752

**Closed by denelon** 2021-03-26 14:56 UTC
Labels: Needs-Triage

**Comment by poa00** [comment] 2024-06-22 03:40
The Git package ID is "Git.Git" so I don't think this is a duplicate of #752.  Here, Git specifically is appearing in `winget list` results with a wrong package ID. I am experiencing the same thing now trying to update Git after installing it specifically using the commmand `winget install -e --id Git.Git` and this is what appears in my results now

```console
Git                                Git_is1                          2.45.2.0.1
```
