### ISSUE TITLE
Ability to set a default source in case a package is found on multiple

### ISSUE THREAD

**Issue by Benjin** [microsoft/winget-cli#1837] opened 2022-01-06 19:49 UTC
### Description of the new feature / enhancement

I like that the MS Store can be used as a source, but it's annoying when the same package exists on both, and I have to specify the longname.  e.g. `winget install powershell` becomes `winget install Microsoft.PowerShell` to get that exact match on the winget source's package.  I could remove the MS Store source, but I'd rather not because I think that's valuable.  Instead, I propose:

`winget source set-default winget` or `winget source set-default msstore`

then when I run `winget install powershell`:
* if my default source has it, then it automatically installs from the default
* if default doesn't, but one other does, then it automatically installs from there
* if default doesn't, but multiple others do, then it shows the existing "Multiple packages found matching input criteria. Please refine the input." message

**Comment by jedieaston** [comment] 2022-01-06 21:09
Duplicate of #1488, maybe you want to move your proposal there?

**Closed by jedieaston** 2022-01-06 21:09 UTC
Labels: Issue-Feature, Needs-Triage
