### ISSUE TITLE
The updated path is not the path during installation

### ISSUE THREAD

**Issue by aoaostar** [microsoft/winget-cli#3869] opened 2023-11-09 07:14 UTC
### Brief description of your issue

After installation at the specified installation location `D:\Programs\daily\Tencent\WeCom`, the software is updated and will not be updated in the previously installed path specified.
Instead it will be installed again to the default path `C:\Program Files (x86)\WXWork`

### Steps to reproduce

```
❯ winget uninstall Tencent.WeCom
已找到 企业微信 [Tencent.WeCom]
正在启动程序包卸载...
已成功卸载

❯ winget install Tencent.WeCom -v 4.1.6.6017 --force -l D:\Programs\daily\Tencent\WeCom
已找到 企业微信 [Tencent.WeCom] 版本 4.1.6.6017
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://dldir1v6.qq.com/wework/work_weixin/WeCom_4.1.6.6017.exe
  ██████████████████████████████   403 MB /  403 MB
已成功验证安装程序哈希
正在启动程序包安装...
已成功安装

❯ winget update Tencent.WeCom
已找到 企业微信 [Tencent.WeCom] 版本 4.1.10.6007
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://dldir1v6.qq.com/wework/work_weixin/WeCom_4.1.10.6007.exe
  ██████████████████████████████   443 MB /  443 MB
已成功验证安装程序哈希
正在启动程序包安装...
已成功安装
```

### Expected behavior

What is installed in `D:\Programs\daily\Tencent\WeCom` should be updated in `D:\Programs\daily\Tencent\WeCom`

### Actual behavior

![image](https://github.com/microsoft/winget-cli/assets/86001674/3316db32-bea0-401a-bc32-e5e071ddfe7b)
![image](https://github.com/microsoft/winget-cli/assets/86001674/536a989c-9237-44c1-aa5a-94abbf8da337)
![image](https://github.com/microsoft/winget-cli/assets/86001674/13bcb1d9-3245-47b8-b11b-517ca69bf71f)

### Environment

```shell
❯ winget --info
Windows 程序包管理器 v1.6.2771
版权所有 (C) Microsoft Corporation。保留所有权利。

Windows: Windows.Desktop v10.0.22621.2428
系统体系结构: X64
软件包: Microsoft.DesktopAppInstaller v1.21.2771.0

Winget 目录
-------------------------------------------------------------------------------------------------------------------
日志                   %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
用户设置               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
可移植链接目录(用户)   %LOCALAPPDATA%\Microsoft\WinGet\Links
可移植链接目录(计算机) C:\Program Files\WinGet\Links
可移植包根目录(用户)   %LOCALAPPDATA%\Microsoft\WinGet\Packages
可移植包根目录         C:\Program Files\WinGet\Packages
可移植包根目录 (x86)   C:\Program Files (x86)\WinGet\Packages
安装程序下载           D:\Pluto\Downloads

链接
----------------------------------------------------------------------------
隐私声明             https://aka.ms/winget-privacy
许可协议             https://aka.ms/winget-license
第三方声明           https://aka.ms/winget-3rdPartyNotice
主页                 https://aka.ms/winget
Windows 应用商店条款 https://www.microsoft.com/en-us/storedocs/terms-of-sale

管理员设置                                状态
------------------------------------------------
LocalManifestFiles                        已禁用
BypassCertificatePinningForMicrosoftStore 已禁用
InstallerHashOverride                     已禁用
LocalArchiveMalwareScanOverride           已禁用
```
```

**Comment by mdanish-kh** [comment] 2023-11-09 08:51
Winget currently doesn't have a way to track install locations. It simply downloads and executes the installer with silent and/or custom args specified in the manifest. If the installer supports `--location` switch, passing it in the upgrade may be a workaround

- Duplicate of #1002

See also
- https://github.com/microsoft/winget-cli/issues/3045

**Closed** 2023-11-09 08:51 UTC
