### ISSUE TITLE
Missing Available column from winget list 

### ISSUE THREAD

**Issue by eabase** [microsoft/winget-cli#3219] opened 2023-05-04 10:24 UTC
### Brief description of your issue

Running `winget list` does not show the `Available` column

### Steps to reproduce

From [admin posh]:
`winget list`

### Expected behavior

That the **`Available`** column is shown, even if there are **no** new updates are available (empty) for all packages.

### Actual behavior

No `Available` column

### Environment

OS: `Windows-11 Enterprise` :

```shell
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.1817
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0
```

**Comment by Trenly** [comment] 2023-05-04 11:03
* https://github.com/microsoft/winget-cli/issues/1618

**Comment by eabase** [comment] 2023-05-04 12:09
Note that: 

```bash
# winget upgrade
No installed package found matching input criteria.
```

**Comment by denelon** [comment] 2023-05-04 22:28
Duplicate of #1618
* #1618

Note: If no upgrades are detected, `winget list` does not show the Available column.

**Closed by denelon** 2023-05-04 22:28 UTC
Labels: Needs-Triage
