### ISSUE TITLE
How to skip the Windows 10 account control?

### ISSUE THREAD

**Issue by AlcsPower** [microsoft/winget-cli#330] opened 2020-05-25 17:17 UTC
How to skip the Windows 10 account control?
I see this tool as an alternative for remote installations.

I don't know if there will be any "sudo" command to do administrator level installations.

**Comment by megamorf** [comment] 2020-05-25 19:59
This seems like a duplicate of #271.

**Comment by denelon** [comment] 2020-06-02 03:00
Duplicate of #271

**Closed by denelon** 2020-06-02 03:00 UTC
Labels: Needs-Triage
