### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by william12456** [microsoft/winget-cli#719] opened 2021-01-26 13:03 UTC
I used this software but I needed to upgrade the software but don't have this option.

**Comment by phips0** [comment] 2021-01-26 15:48
I think is a duplicate of #120

**Comment by jedieaston** [comment] 2021-01-26 16:44
What are you trying to upgrade? (upgrade is still experimental, and only works reliably for appx packages in my experience)

**Comment by denelon** [comment] 2021-01-26 18:32
Duplicate of #120

**Closed by denelon** 2021-01-26 18:32 UTC
Labels: Issue-Feature, Needs-Triage
