### ISSUE TITLE
Cache files

### ISSUE THREAD

**Issue by sirinath** [microsoft/winget-cli#3577] opened 2023-09-01 06:48 UTC
### Description of the new feature / enhancement

Can the:
- package list
- download files

When an issue happens rerun the command again with some other parameters. Then the existing downloads can be used. 

### Proposed technical implementation details

Be cached so they don't need to be re downloaded every time.

Add options to:
- keep cached files
- use cached files if available

**Comment by mdanish-kh** [comment] 2023-09-01 06:53
Similar issues:

- https://github.com/microsoft/winget-cli/issues/343
- https://github.com/microsoft/winget-cli/discussions/2911

Duplicate of  #343

**Closed** 2023-09-01 06:53 UTC
Labels: Issue-Feature
