### ISSUE TITLE
Can't figure out how to install terminal

### ISSUE THREAD

**Issue by stevenbrix** [microsoft/winget-cli#440] opened 2020-06-19 02:10 UTC
# Brief description of your issue

I remember being promised that I could just install terminal through a command like:
> winget install terminal

However, I've had no such luck...

# Steps to reproduce

run `winget install terminal`

# Expected behavior

Terminal app downloads and installs

# Actual behavior
```
C:\Users\stevenki>winget install terminal
Multiple apps found matching input criteria. Please refine the input.
Name                     Id                               Version    Matched
----------------------------------------------------------------------------------
Windows Terminal         Microsoft.WindowsTerminal        1.0.1401.0 Tag: terminal
Terminus                 Eugeny.Terminus                  1.0.112    Tag: terminal
Windows Terminal Preview Microsoft.WindowsTerminalPreview 1.0.1401.0
SecureDNS.Terminal       Texnomic.SecureDNS.Terminal      0.3-alpha

C:\Users\stevenki>winget install Windows Terminal
Windows Package Manager v0.1.41331 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Found a positional argument when none was expected : 'Terminal'

Installs the given application

usage: winget install [[-q] <query>] [<options>]

The following arguments are available:
  -q,--query        The query used to search for an app

The following options are available:
  -m,--manifest     The path to the manifest of the application
  --id              Filter results by id
  --name            Filter results by name
  --moniker         Filter results by app moniker
  -v,--version      Use the specified version; default is the latest version
  -s,--source       Find app using the specified source
  -e,--exact        Find app using exact match
  -i,--interactive  Request interactive installation; user input may be needed
  -h,--silent       Request silent installation
  -o,--log          Log location (if supported)
  --override        Override arguments to be passed on to the installer
  -l,--location     Location to install to (if supported)

More help can be found at: https://aka.ms/winget-command-install

C:\Users\stevenki>winget install --name Windows Terminal
Multiple apps found matching input criteria. Please refine the input.
Name                     Id                               Version    Matched
--------------------------------------------------------------------------------------
Windows Terminal         Microsoft.WindowsTerminal        1.0.1401.0 Moniker: Terminal
Windows Terminal Preview Microsoft.WindowsTerminalPreview 1.0.1401.0 Moniker: Terminal

C:\Users\stevenki>winget install --name Windows Terminal --id Microsoft.WindowsTerminal
Multiple apps found matching input criteria. Please refine the input.
Name                     Id                               Version    Matched
--------------------------------------------------------------------------------------
Windows Terminal         Microsoft.WindowsTerminal        1.0.1401.0 Moniker: Terminal
Windows Terminal Preview Microsoft.WindowsTerminalPreview 1.0.1401.0 Moniker: Terminal

C:\Users\stevenki>winget install --name Windows Terminal --id Microsoft.WindowsTerminal --exact
No app found matching input criteria.
```

Queue the sad face, because I still haven't installed terminal 😢 

# Environment

```none
[winget --info]
C:\Users\stevenki>winget --info
Windows Package Manager v0.1.41331 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.18363.900
Package: Microsoft.DesktopAppInstaller v1.0.41331.0

Any other software?
```

**Comment by megamorf** [comment] 2020-06-19 07:45
Please try:

```
winget install --id Microsoft.WindowsTerminal --exact
```

**Comment by denelon** [comment] 2020-06-19 18:44
Thanks @megamorf!
https://github.com/microsoft/winget-cli/issues/292

**Comment by denelon** [comment] 2020-06-19 18:45
Duplicate of #292

**Closed by denelon** 2020-06-19 18:45 UTC
Labels: Needs-Triage
