### ISSUE TITLE
winget install Adobe.AdobeAcrobatReaderDC fails due to multiple packages found?! bc: other sources

### ISSUE THREAD

**Issue by cloudrootab** [microsoft/winget-cli#1531] opened 2021-09-30 08:32 UTC
# Brief description of your issue

When trying to install AcrobatReaderDC, by giving a package-ID. It fails due to finding  (imho) _unrelated_ packages from msstore?! 

![image](https://user-images.githubusercontent.com/62222189/135416742-73c70473-d705-4a1c-a424-c65d6362dc1e.png)

# Steps to reproduce
winget version: v1.1.12702
sources: msstore & winget

winget install Adobe.AdobeAcrobatReaderDC

# Expected behavior
When specifying a package ID, it shouldn't pull obscure other data from msstore. Rather it should realize that ID trumps any weird description-information or simililar.

# Actual behavior
The install fails due to "multiple packages found". 

Passing the "--id" flag, does bypass this behaviour.

# Environment

```none
[winget --info]
Windows Package Manager version v1.1.12702
Windows: Windows.Desktop version  v10.0.22000.194
Package: Microsoft.DesktopAppInstaller version  v1.16.12702.0

Any other software?
```

**Comment by denelon** [comment] 2021-09-30 14:26
Related to #1523
Duplicate of  #1524

>Note: We are making changes to the "**msstore**" source behavior to help address this.

**Closed by denelon** 2021-09-30 14:26 UTC
Labels: Needs-Triage
