### ISSUE TITLE
Uninstall winget-cli

### ISSUE THREAD

**Issue by jonyluke** [microsoft/winget-cli#608] opened 2020-10-13 10:45 UTC
How to uninstall winget after installing it manually from releases?

**Comment by denelon** [comment] 2020-10-13 16:21
Duplicate of #536

**Comment by denelon** [comment] 2020-10-13 16:22
@jonlyluke can you follow #536 and provide a bit more detail like `winget --info`. I'll see where we're at on that issue.

**Closed by denelon** 2020-10-13 16:21 UTC
Labels: Needs-Triage

**Comment by jonyluke** [comment] 2020-10-14 09:05
@denelon
```
winget --info
Windows Package Manager v0.2.2521 Vista previa
Copyright (c) Microsoft Corporation. Todos los derechos reservados.

Windows: Windows.Desktop v10.0.19041.546
Paquete: Microsoft.DesktopAppInstaller v1.11.2521.0

Vínculos
--------------------------------------------------------------
Declaración de privacidad https://aka.ms/winget-privacy
Contrato de licencia      https://aka.ms/winget-license
Avisos de terceros        https://aka.ms/winget-3rdPartyNotice
Página principal          https://aka.ms/winget
```
