### ISSUE TITLE
I'd like to upgrade minor versions only

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#1915] opened 2022-02-09 16:38 UTC
### Description of the new feature / enhancement

I'd like to be able to upgrade minor versions only so I don't get a new major version.

Something like `winget upgrade --all --minor`.

I would be able to upgrade something like Python to a newer minor version without taking a major version.

**Comment by jedieaston** [comment] 2022-02-09 16:41
We've been splitting manifests for major version numbers into different PackageIdentifiers in the community repo (when we notice, I still have to cleanup some of the dotnet bundles). It'd be nice for the client to have knowledge of minor vs major semvers, but at this time, people shouldn't be getting major version updates for Python, Java and Node.

**Comment by Trenly** [comment] 2022-02-09 16:53
@denelon - Sorry if I stole your thunder
![image](https://user-images.githubusercontent.com/12611259/153249720-f31df345-375b-4fe0-86a5-e3e4fade8c85.png)

**Comment by jedieaston** [comment] 2022-02-09 16:56
Duplicate of #1914 

:D

**Closed by jedieaston** 2022-02-09 16:56 UTC
Labels: Issue-Feature, Needs-Triage

**Comment by Trenly** [comment] 2022-02-09 16:57
> Duplicate of #1914
> 
> :D

Wow. Won't even let him close his own issue. The nerve */sarcasm/*

**Comment by denelon** [comment] 2022-02-09 16:58
It's all good.
