### ISSUE TITLE
Add -o/--output-format options for search/show/list to output CSV|JSON and possibly other formats easy to consume by PowerShell

### ISSUE THREAD

**Issue by rkeithhill-keysight** [microsoft/winget-cli#2595] opened 2022-10-13 16:56 UTC
### Description of the new feature / enhancement

Right now it is really hard to convert the output of commands like `winget list ` in PowerShell. Simply trying to sort the output gives corrupted characters in the output e.g.

```powershell
$pkgs = winget list
$pkgs
```
Results in:

<img width="737" alt="image" src="https://user-images.githubusercontent.com/103770981/195656381-7d5f8d54-e100-493f-b4b5-b210738bc8ca.png">

Even if the corrupted chars were fixed, there is rich data in the output that has to be parsed out by PowerShell - what Jeffrey Snover would call "prayer-based parsing".  There is a better way that would benefit not just PowerShell.

Related to #221 

### Proposed technical implementation details

Implement a new parameter to commands that output rich information e.g. search, show and list (and maybe others).  I propose using `-o | --output-format`.  The default output format would be `Table`, to match the current output format. But I would like to see a CSV option that could be used to open the output in Excel or used by PowerShell like so:

```powershell
winget list -o csv | ConvertFrom-Csv | Where-Object Name -match Microsft | Sort-Object Name
```
Furthermore, you could also support a `List` format that would not truncate text e.g.:

```powershell
winget list -o list

Name:      JetBrains ETW Host Service (x64) 
Id:        JetBrains.ReSharper
Version:   < 2022.2.2
Available: 2022.2.3
Source:    winget

Name: ...
....
```

**Comment by rkeithhill-keysight** [comment] 2022-10-13 17:05
BTW there is a native PowerShell format called CLIXML that winget could also output but I'm not sure how widely CLIXML was adopted/used.

**Comment by Trenly** [comment] 2022-10-13 18:26
Duplicate of #1753

**Closed by Trenly** 2022-10-13 18:26 UTC
Labels: Issue-Feature, Needs-Triage
