### ISSUE TITLE
Support for installation of static exe files

### ISSUE THREAD

**Issue by tobiaskohlbau** [microsoft/winget-cli#194] opened 2020-05-19 18:05 UTC
# Description of the new feature/enhancement

In the go world it's very common to distribute static linked executables which are self contained and do not have any particular installer. I've read the spec and if I'm not mistake winget does not have support for this kind of applications.

Would be nice if winget would support such kind of apps. Somehow this is related to #182 and #140 .

# Proposed technical implementation details (optional)

Put the executable into the correct installation folders. Maybe even allow the user to select the place and optional configurations files.

**Comment by denelon** [comment] 2020-05-22 21:47
This looks like a duplicate of #182

**Comment by tobiaskohlbau** [comment] 2020-05-23 09:44
You're right with the exception that this targets the executable itself without a decompression step. I opened this ticket to check if this kind of installation should get it's own `InstallerType`. As `exe` is already reserved for installable executables I could imagine two ways: 

1. New `InstallerType` for this kind of applications.
2. Implicit supported by the `zip` type.

If the solution takes on the first option I could imagine that it's possible to share code with the zip implementation.

If you would move this discussions in the other issue we can close this. Thanks for your work!

**Comment by marcomorain** [comment] 2020-05-23 21:13
👍 I'm looking for this feature to package the CircleCI CLI tool. The app is a single, static binary, that has no need for an installer/uninstaller, it's just an EXE that should be placed on the PATH when installed.

**Comment by koppor** [comment] 2020-05-24 12:16
Another example: [wsay](https://github.com/p-groarke/wsay) --> `wsay.exe` outputing text (Windows equivalent of macOS `say`)

**Comment by aetos382** [comment] 2020-05-26 16:55
Should support renaming downloaded files before putting them in place.

**Comment by crpietschmann** [comment] 2020-09-12 03:15
This would enable winget to be used to "install" [Azure Bicep CLI](https://github.com/Azure/bicep) which is only available as a stand-alone downloaded exe for the tool.

**Comment by denelon** [comment] 2021-03-04 01:19
This looks very similar to #182.

I think they are duplicates of each other.

I believe the ask is to have the ability to download the standalone program (in the form of a .exe) and make it available via the path so that a user can "install" it and use it.

If that is the case, I'd like to close this Issue as a duplicate, but I want to make sure everyone has the time to put their thumbs up on the other issue. 

Are there any objections?

**Comment by tobiaskohlbau** [comment] 2021-03-04 07:11
> You're right with the exception that this targets the executable itself without a decompression step. I opened this ticket to check if this kind of installation should get it's own `InstallerType`. As `exe` is already reserved for installable executables I could imagine two ways:
> 
> 1. New `InstallerType` for this kind of applications.
> 2. Implicit supported by the `zip` type.
> 
> If the solution takes on the first option I could imagine that it's possible to share code with the zip implementation.
> 
> If you would like to move this discussions in the other issue we can close this. Thanks for your work!

I'm totally fine with merging this issue into #182 if the supported case, of putting the executable without the extraction step, is supported by the solution of #182.

**Comment by denelon** [comment] 2021-03-04 16:49
Yes, that is the intention of #182.

Anybody who has put their thumbs up on this issue should also put their thumbs up on #182.

**Closed by denelon** 2021-03-04 16:49 UTC
Labels: Issue-Feature, Needs-Attention, Size-S
