### ISSUE TITLE
Did you change the winget list effect? It doesn't seem to show upgradable installed packages

### ISSUE THREAD

**Issue by dong-lufei** [microsoft/winget-cli#3390] opened 2023-06-29 03:51 UTC
Now how do I know if the 30 or 40 packages I installed have a new version to upgrade

**Comment by robinmalik** [comment] 2023-06-29 09:38
`winget --info`

**Comment by Trenly** [comment] 2023-06-29 12:17
As far as I know, nothing has changed with how the default behavior of the list command works.

You can always use `winget upgrade` to list available upgrades

**Comment by denelon** [comment] 2023-07-01 22:44
WinGet list currently only displays the available version when an update is available.

Duplicate of #1155
* #1155

**Closed by denelon** 2023-07-01 22:44 UTC
Labels: Issue-Bug
