### ISSUE TITLE
winget upgrade --all | Shows same upgrades after just upgrading all. And will attempt to reupgrade same ones

### ISSUE THREAD

**Issue by spragginsdesigns** [microsoft/winget-cli#1508] opened 2021-09-25 04:45 UTC
# Brief description of your issue
Whenever I  use the winget upgrade --all or even --silent after checking with winget upgrade, it just shows all the same ones I literally just upgraded...

# Steps to reproduce
run winget upgrade , then run winget upgrade --all or --silent as well, no matter what it does not work right 

# Expected behavior
winget upgrade --all --silent or without the --silent should upgrade what it can and then show it has been upgraded-

# Actual behavior
Instead, winget upgrade --all or upgrading and then trying to upgrade everything again 

# Environment

```none
Windows Package Manager v1.0.12581
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.194
Package: Microsoft.DesktopAppInstaller v1.16.12581.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Any other software?
Yes, Windows Terminal Preview
```
Windows Terminal Preview - not Windows Terminal, and also Windows 11. But, either way it does this on Windows 10 and also in Windows Terminal.

## Below is some screenshots of me checking for upgrades, upgrading and then it showing me more upgrades again
![Screenshot (466)](https://user-images.githubusercontent.com/43624199/134758440-747b6dc1-69b8-46d1-8722-6fd6c16f98c3.png)
.
![Screenshot (469)](https://user-images.githubusercontent.com/43624199/134758445-a150d36b-9b31-4259-b3ed-ae39980d5f57.png)

**Comment by jedieaston** [comment] 2021-09-25 23:37
Do you have admin rights?

**Comment by spragginsdesigns** [comment] 2021-09-26 00:36
> Do you have admin rights?

Yes, maybe not in these screenshots. But when I get home I will Run As Administrator and post more screenshots. 

I will also do this will PowerShell and Windows Terminal. 

Anything else I should try?

**Comment by jedieaston** [comment] 2021-09-27 15:07
I would try that first, because lots of installers will return 1 if they can't get elevated right. If that doesn't work I can think of something else.

**Comment by spragginsdesigns** [comment] 2021-09-27 23:10
This is my winget settings .json too:

`{
    "$id": "https://aka.ms/winget-settings.schema.json",
    "$schema": "https://json-schema.org/draft/2019-09/schema#",
    "title": "Microsoft's Windows Package Manager Settings Profile Schema",
    "definitions": {
      "Source": {
        "description": "Source repository settings",
        "type": "object",
        "properties": {
          "autoUpdateIntervalInMinutes": {
            "description": "Number of minutes before source update",
            "type": "integer",
            "default": 5,
            "minimum": 0,
            "maximum": 43200
          }
        }
      },
      "Visual": {
        "description": "Visual settings",
        "type": "object",
        "properties": {
          "progressBar": {
            "description": "Progress bar display style",
            "type": "string",
            "enum": [
              "accent",
              "rainbow",
              "plain",
              "retro"
            ]
          }
        }
      },
      "InstallPrefReq": {
        "description": "Shared schema for preferences and requirements",
        "type": "object",
        "properties": {
          "scope": {
            "description": "The scope of a package install",
            "type": "string",
            "enum": [
              "user",
              "machine"
            ],
            "default": "user"
          },
          "locale": {
            "description": "The locales of a package install",
            "type": "array",
            "items": {
              "type": "string",
              "pattern": "^([a-zA-Z]{2}|[iI]-[a-zA-Z]+|[xX]-[a-zA-Z]{1,8})(-[a-zA-Z]{1,8})*$",
              "maxLength": 20
            },
            "minItems": 1,
            "maxItems": 10
          }
        }
      },
      "InstallBehavior": {
        "description": "Install settings",
        "type": "object",
        "properties": {
          "preferences": { "$ref": "#/definitions/InstallPrefReq" },
          "requirements": { "$ref": "#/definitions/InstallPrefReq" }
        }
      },
      "Telemetry": {
        "description": "Telemetry settings",
        "type": "object",
        "properties": {
          "disable": {
            "description": "Controls whether telemetry events are written",
            "type": "boolean",
            "default": false
          }
        }
      },
      "Network": {
        "description": "Network settings",
        "type": "object",
        "properties": {
          "downloader": {
            "description": "Control which download code is used for packages",
            "type": "string",
            "enum": [
              "default",
              "wininet",
              "do"
            ],
            "default": "default"
          },
          "doProgressTimeoutInSeconds": {
            "description": "Number of seconds to wait without progress before fallback",
            "type": "integer",
            "default": 60,
            "minimum": 1,
            "maximum": 600
          }
        }
      },
      "Experimental": {
        "description": "Experimental Features",
        "type": "object",
        "properties": {
          "experimentalCMD": {
            "description": "Reference implementation for an experimental command",
            "type": "boolean",
            "default": true
          },
          "experimentalARG": {
            "description": "Reference implementation for an experimental argument",
            "type": "boolean",
            "default": true
          },
          "experimentalMSStore": {
            "description": "Experimental support for Microsoft Store source",
            "type": "boolean",
            "default": true
          },
          "list": {
            "description": "Enable the list command while it is in development",
            "type": "boolean",
            "default": true
          },
          "upgrade": {
            "description": "Enable the upgrade command while it is in development",
            "type": "boolean",
            "default": true
          },
          "uninstall": {
            "description": "Enable the uninstall command while it is in development",
            "type": "boolean",
            "default": true
          },
          "restSource": {
            "description": "Enable the rest source support while it is in development",
            "type": "boolean",
            "default": true
          }
        }
      }
    },
    "allOf": [
      {
        "properties": {
          "visual": { "$ref": "#/definitions/Visual" }
        },
        "additionalItems": true
      },
      {
        "properties": {
          "source": { "$ref": "#/definitions/Source" }
        },
        "additionalItems": true
      },
      {
        "properties": {
          "installBehavior": { "$ref": "#/definitions/InstallBehavior" }
        },
        "additionalItems": true
      },
      {
        "properties": {
          "telemetry": { "$ref": "#/definitions/Telemetry" }
        },
        "additionalItems": true
      },
      {
        "properties": {
          "network": { "$ref": "#/definitions/Network" }
        },
        "additionalItems": true
      },
      {
        "properties": {
          "experimentalFeatures": { "$ref": "#/definitions/Experimental" }
        },
        "additionalItems": true
      }
    ],
    "additionalProperties": true
  }`

**Comment by jedieaston** [comment] 2021-09-27 23:12
That's the settings schema file, not the way the settings file is supposed to look.

Here's what mine looks like (some of those experimental settings no longer exist, but as a reference):

```
{
    // For documentation on these settings, see: https://aka.ms/winget-settings
    // "source": {
    //    "autoUpdateIntervalInMinutes": 5
    // },
    "visual": {
        "progressBar": "rainbow"
    },
    "experimentalFeatures": {
        "experimentalMSStore": true,
        "list": true,
        "upgrade": true,
        "uninstall": true,
        "export": true
   }
}
```

**Comment by spragginsdesigns** [comment] 2021-09-27 23:13
Sorry, I am unsure why this closed this is a serious issue.

**Comment by spragginsdesigns** [comment] 2021-09-27 23:18
> That's the settings schema file, not the way the settings file is supposed to look.
> 
> Here's what mine looks like (some of those experimental settings no longer exist, but as a reference):
> 
> ```
> {
>     // For documentation on these settings, see: https://aka.ms/winget-settings
>     // "source": {
>     //    "autoUpdateIntervalInMinutes": 5
>     // },
>     "visual": {
>         "progressBar": "rainbow"
>     },
>     "experimentalFeatures": {
>         "experimentalMSStore": true,
>         "list": true,
>         "upgrade": true,
>         "uninstall": true,
>         "export": true
>    }
> }
> ```

Thank you, I changed the settings to yours, except I prefer "accent" for the progress bar, and same issue: 
![image](https://user-images.githubusercontent.com/43624199/134997887-bc9c9c70-7ebd-4573-a430-4ebbb0646939.png)

**Comment by spragginsdesigns** [comment] 2021-09-27 23:24
And Visual Studio Installer fails because it does not need any upgrade, nor any plugins etc.

![image](https://user-images.githubusercontent.com/43624199/134998358-42165db1-2030-4ab6-baab-5b5bc4551218.png)

**Comment by spragginsdesigns** [comment] 2021-09-27 23:25
No matter what it seems I change or do correctly, it just upgrades the same thing, or doesn't upgrade because it already has, or some issue: 

![image](https://user-images.githubusercontent.com/43624199/134998424-0ae14678-83af-4c46-8b13-55d67269daef.png)

**Comment by MylesH85** [comment] 2021-09-28 06:13
Having the same issue here. Keeps updating GOG and Teracopy.

![Screenshot 2021-09-28 081216](https://user-images.githubusercontent.com/66518283/135032994-b992b032-ff23-4c42-bc5c-b36457a24f07.png)

**Comment by jedieaston** [comment] 2021-09-28 12:38
GOG is because of GOG not publishing its version number. Once package pinning is available (https://github.com/microsoft/winget-cli/issues/476), that same functionality will be able to be used to exclude GOG from `winget upgrade --all`.

Vim is because we use different version numbers than Vim so that people can jump to a specific nightly. I don't know if there's really a reason for that (@ImJoakim, if you have an opinion..?) but we can probably stop doing that.

I don't know why Visual Studio is doing that though.

**Comment by spragginsdesigns** [comment] 2021-09-29 21:01
> GOG is because GOG not publishing its version number. Once package pinning is available (#476), that same functionality will be used to exclude GOG from `winget upgrade --all.`
> 
> Vim is because we use different version numbers than Vim so that people can jump to specific nightly. I don't know if there's really a reason for that (@ImJoakim, if you have an opinion..?), but we can probably stop doing that.
> 
> I don't know why Visual Studio is doing that, though.

This has been happening to me since almost the start of winget. I was here several months after it was available for insiders, as I have had Windows 11 installed on my main machine and worked laptop for the last month or so, and I love how more open source Microsoft is getting. Still, this is an issue I would love to explain, or if my settings are wrong, or if everyone has this bug?

**Comment by spragginsdesigns** [comment] 2021-09-29 21:05
# Update from my Work Laptop
## Same thing, winget upgrade --all is broken at the moment for my PC and work laptop, before Windows 11 as well: 
![image](https://user-images.githubusercontent.com/43624199/135348263-c4b5b6b9-e12f-410d-b3f7-80b4811cbe95.png)

**Comment by jedieaston** [comment] 2021-09-29 21:14
Oh, yeah, everyone has these bugs. They are being tracked in #752. There are some planned solutions near the bottom ([here](https://github.com/microsoft/winget-cli/issues/752#issuecomment-915632239)).

**Comment by denelon** [comment] 2021-10-01 20:16
Duplicate of #752

**Closed by denelon** 2021-10-01 20:16 UTC
Labels: Issue-Bug

**Comment by spragginsdesigns** [comment] 2021-10-02 01:31
> @spragginsdesigns we've identified this Issue as a duplicate of another one that already exists. This specific instance is being closed in favor of tracking the concern over on the referenced Issue. Thanks for your report! Be sure to add your 👍 to the other issue to help raise the priority.

Thank you for informing me and also @denelon for pointing me to the correct issue. I will transfer to following and contributing to that issue #.

**Comment by dshot92** [comment] 2023-11-08 08:56
This is still happening!
"NVIDIA CUDA Toolkit 12.3 Nvidia.CUDA" keeps redownloading and reinstalling
