### ISSUE TITLE
Microsoft OneNote PackageIdentifier value fails schema validation

### ISSUE THREAD

**Issue by atrenton** [microsoft/winget-cli#3720] opened 2023-09-30 21:32 UTC
### Brief description of your issue

Search for OneNote reveals the following Id:
![image](https://github.com/microsoft/winget-cli/assets/48064181/5a1c857f-dc28-43f4-8589-ef29e8a6c96b)
Attempting to validate manifest fails using that Id as the PackageIdentifier value:
![image](https://github.com/microsoft/winget-cli/assets/48064181/cdf6c487-fd68-4c9e-ae1e-0a585b004ed9)
See attached installer.yaml file
[atrenton.MyJournal.Notebook.installer.yaml.txt](https://github.com/microsoft/winget-cli/files/12775562/atrenton.MyJournal.Notebook.installer.yaml.txt)

### Steps to reproduce

Use 'wingetcreate new' command to create manifest files
and configure **installer.yaml** file with OneNote as a dependency
```txt
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: XPFFZHVGQWWLHB
```

### Expected behavior

Expected PackageIdentifier for OneNote to be valid.

### Actual behavior

Manifest validation fails.

### Environment

```shell
$ winget --info
Windows Package Manager v1.6.2701
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2283
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.2701.0

Winget Directories
---------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutp…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                D:\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Enabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by Trenly** [comment] 2023-10-01 01:49
This is expected behavior.

* Duplicate of #3271

**Closed** 2023-10-01 01:49 UTC
