### ISSUE TITLE
Winget upgrade not working correctly

### ISSUE THREAD

**Issue by shomilsaini** [microsoft/winget-cli#3517] opened 2023-08-12 15:41 UTC
### Brief description of your issue

![image](https://github.com/microsoft/winget-cli/assets/46788173/d00a148c-8ca2-4907-b72e-8b9989c2e2d5)

### Steps to reproduce

![image](https://github.com/microsoft/winget-cli/assets/46788173/872df3fb-dc48-4343-ba3f-7e1920dae208)

### Expected behavior

Upgrade all the packages

### Actual behavior

![image](https://github.com/microsoft/winget-cli/assets/46788173/81c51d6e-a388-4d7f-a932-3537f1fe27bf)

### Environment

```shell
Windows Package Manager v1.5.1881
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2134
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.1881.0

--------OTHER INFO----------

OS Name	Microsoft Windows 11 Pro
Version	10.0.22621 Build 22621.2134
```

**Comment by Trenly** [comment] 2023-08-12 21:57
@shomilsaini - Can you please share any of your log files?

Also, what is the output of `winget upgrade`? I have a feeling your packages may already be up to date

**Comment by shomilsaini** [comment] 2023-08-13 03:48
> @shomilsaini - Can you please share any of your log files?
> 
> Also, what is the output of `winget upgrade`? I have a feeling your packages may already be up to date

I'm not sure what you mean by that. What I'm trying to show in the screenshot is, if I do winget upgrade -all it says to use --include-unknown, but when I do that there is no upgrade. I even tried different commands with no change in output. I hope this is making sense.

If you would like some logs etc please let me know the commands or location to get them, I'll be happy to provide them.

Thanks

**Comment by Trenly** [comment] 2023-08-13 04:09
> > @shomilsaini - Can you please share any of your log files?
> > Also, what is the output of `winget upgrade`? I have a feeling your packages may already be up to date
> 
> I'm not sure what you mean by that. What I'm trying to show in the screenshot is, if I do winget upgrade -all it says to use --include-unknown, but when I do that there is no upgrade. I even tried different commands with no change in output. I hope this is making sense.
> 
> If you would like some logs etc please let me know the commands or location to get them, I'll be happy to provide them.
> 
> Thanks

Ah, I see. This is a known issue then.


The count of unknown packages is taken before the packages are correlated with available packages from any source. This means a package that has an unnown version but isn’t available from the winget repository or the microsoft store will be counted for the "# packages have versions that cannot be determined" but will be excluded anytime an upgrade is attempted.

* Duplicate of #2458

**Closed** 2023-08-13 04:09 UTC
Labels: Issue-Bug
