### ISSUE TITLE
Please add ignore update function

### ISSUE THREAD

**Issue by FW27623** [microsoft/winget-cli#3107] opened 2023-03-25 12:10 UTC
### Description of the new feature / enhancement

I personally recommend adding the option to ignore updates to shield certain software updates, because some software requires a specific version to run, and there may be problems with the upgrade, and you cannot use the winget upgrade --all command to upgrade all packages with one click, which is not enough convenient.

### Proposed technical implementation details

Personally I recommend adding winget upgrade --ignore <package id> command

**Comment by Trenly** [comment] 2023-03-25 12:44
Duplicate of #476

**Closed by Trenly** 2023-03-25 12:44 UTC
Labels: Issue-Feature, Needs-Triage
