### ISSUE TITLE
[Feature proposal] Conditional parameters

### ISSUE THREAD

**Issue by gvvad** [microsoft/winget-cli#1089] opened 2021-06-03 12:02 UTC
# Description:
Instead of a system of different scenarios (Silent, SilentWithProgress, Interactive...), provide "conditional parameters" which will be added by condition. Some conditions(flags) will be true by default, such as "silent install". But the user can override them, turn them on / off at their own discretion.
This is not a replacement for the existing system, but rather an improvement. Also will be good to add "uninstall" scenario.
# Proposed technical implementation details:
Provide parameters in manifest:
`Installers:`
`...`
`InstallParam: $isSilent{$isVerysilent{/VERYSILENT:/SILENT}} $isUser{/CURRENTUSER:/ALLUSERS} $isIcon{:/NOICONS}`
`UpgradeParam: $isNorestart{/NORESTART} $isLog{$isLogfile{/LOG={logfile}:/LOG}}`
`...`
Provide parameters to winget:
`winget install foo --noicon`
`winget install foo --alluser --noicon --verysilent`
`winget upgrade foo --log`
`winget upgrade foo --log="c:\path\to\logfile.txt"`

**Comment by iDolmatov** [comment] 2021-06-03 19:36
`winget uninstall` already exist.
`winget install <app name> --override` already exist. See also https://github.com/microsoft/winget-cli/issues/239 - the issue of additional recording of switches is being discussed, and not their complete rewriting.

**Comment by gvvad** [comment] 2021-06-03 20:52
> `winget uninstall` already exist.

This command just execute "uninstaller", like you remove program from "Control panel". And there is no way to define parameters in manifest file.
#239 discus about "user custom" parameters. In my opinion this is wrong way. I propose to define a list of parameters that you can optionally pass to installer | uninstaller | upgrader.

**Comment by gvvad** [comment] 2021-06-04 05:38
> The problem with defining a list of parameters is that there is no single set of "standard" switches

Yes, this is the key problem. And I suggest defining a list of the most common flags such as "isSilent", "isRun", "isRestart", "isIcon" etc. And "maintainer" will be able to define them by using special syntax, like:
`$condition{"value if true":"value if false"}`
The user does not know which parameters are supported by this or that installer. Therefore, this task can be delegated to the maintainer.

**Comment by Trenly** [comment] 2022-08-09 00:46
@denelon -
Install, Upgrade, Location, Scope, and Logs already are covered, and uninstall has a more detailed request in #1885. I believe switches for desktop shortcuts are covered in #1045, meaning this issue could be closed for clarity, as all remaining issues are being tracked with more detail?

**Comment by denelon** [comment] 2022-08-09 15:36
@Trenly thanks for digging through this request. I agree. @gvvad please add your 👍to the other issues.

Duplicate of #1885

Related:
* #1885
* #1045

**Closed by denelon** 2022-08-09 15:36 UTC
Labels: Issue-Feature, Area-Manifest
