### ISSUE TITLE
Please update winget msix package Desktop App Installer dependency version

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/winget-cli#3774] opened 2023-10-17 10:11 UTC
### Brief description of your issue

Please update winget msix package Desktop App Installer dependency version

At present, the Microsoft.UI.Xaml version used by the desktop installer of the msix package that winget depends on is 2.7, and the latest version of Microsoft.UI.Xaml is 2.8, and I hope to upgrade the Microsoft.UI.Xaml version to the latest version as soon as possible

![image](https://github.com/microsoft/winget-cli/assets/49179966/4c463105-0a35-4299-a95f-334f3a06bf09)

### Steps to reproduce

None

### Expected behavior

hope to upgrade the Microsoft.UI.Xaml version to the latest version as soon as possible

### Actual behavior

None

### Environment

```shell
See screenshot.
```

**Comment by mdanish-kh** [comment] 2023-10-17 10:26
Duplicate of #3380

**Closed** 2023-10-17 10:26 UTC
