### ISSUE TITLE
`winget upgrade --all --include-unknown` reports that one package is pinned, whereas the feature is not enabled

### ISSUE THREAD

**Issue by sba923** [microsoft/winget-cli#3307] opened 2023-06-03 16:58 UTC
I'm running `winget` v1.4.11071 on Windows 10 `10.0.19045.2965.amd64fre.vb_release.191206-1406`.

As the end of the execution of `winget upgrade --all --include-unknown` I get:

`1 package(s) is pinned and needs to be explicitly upgraded`

whereas the pinning feature is not enabled (not present at all) in my `settings.json`.

Here's the output from `winget --info`:

```text
Windows Package Manager v1.4.11071
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2965
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.11071.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

Here's my `settings.json`:

[settings.zip](https://github.com/microsoft/winget-cli/files/11643262/settings.zip)

**Comment by Trenly** [comment] 2023-06-03 18:35
Duplicate of #3263

**Closed** 2023-06-03 18:35 UTC
Labels: Needs-Triage
