### ISSUE TITLE
`winget upgrade --all` silently skips packages for which an upgrade is available

### ISSUE THREAD

**Issue by sba923** [microsoft/winget-cli#3663] opened 2023-09-24 14:39 UTC
### Brief description of your issue

`winget upgrade --all` starts by enumerating packages for which an upgrade is available.

For instance, in my particular scenario, PowerShell 7.3.6 is present and 7.3.7 is available.

Without explanation, `winget upgrade --all` silently skips that package.

### Steps to reproduce

Run `winget upgrade --all` on a system with PowerShell 7.3.6 installed.

### Expected behavior

PowerShell should be upgraded to 7.3.7.

Or something should be displayed, such as: PowerShell cannot be upgraded due to different installer technology.

### Actual behavior

````
PS❯ winget upgrade --all --verbose-logs
Name                             Id                      Version Available Source
---------------------------------------------------------------------------------
Oh My Posh version 18.9.1        JanDeDobbeleer.OhMyPosh 18.9.1  18.10.1   winget
Microsoft .NET SDK 6.0.317 (x64) Microsoft.DotNet.SDK.6  6.0.317 6.0.414   winget
PowerShell 7.3.6.0-x64           Microsoft.PowerShell    7.3.6.0 7.3.7.0   winget
Microsoft .NET SDK 7.0.203 (x64) Microsoft.DotNet.SDK.7  7.0.203 7.0.401   winget
Microsoft .NET SDK 7.0.308 (x64) Microsoft.DotNet.SDK.7  7.0.308 7.0.401   winget
5 upgrades available.
2 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.
1 package(s) have pins that prevent upgrade. Use the 'winget pin' command to view and edit pins. Using the --include-pinned argument may show more results.

(1/3) Found Oh My Posh [JanDeDobbeleer.OhMyPosh] Version 18.10.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v18.10.1/install-amd64.exe
  ██████████████████████████████  6.19 MB / 6.19 MB
Successfully verified installer hash
Starting package install...
Successfully installed

(2/3) Found Microsoft .NET SDK 6.0 [Microsoft.DotNet.SDK.6] Version 6.0.414
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.414/dotnet-sdk-6.0.414-win-x64.exe
  ██████████████████████████████   197 MB /  197 MB
Successfully verified installer hash
Starting package install...
Successfully installed

(3/3) Found Microsoft .NET SDK 7.0 [Microsoft.DotNet.SDK.7] Version 7.0.401
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.401/dotnet-sdk-7.0.401-win-x64.exe
  ██████████████████████████████   219 MB /  219 MB
Successfully verified installer hash
Starting package install...
Successfully installed

21 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.
````

Here are the logs: 
[WinGet-2023-09-24-16-02-02.027.log.zip](https://github.com/microsoft/winget-cli/files/12708765/WinGet-2023-09-24-16-02-02.027.log.zip)

### Environment

```shell
Windows Package Manager v1.5.2201
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2283
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.2201.0

Winget Directories
----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Dia…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\set…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by mdanish-kh** [comment] 2024-04-11 08:23
Duplicate of #2883

**Closed** 2024-04-11 08:23 UTC
Labels: Issue-Bug, Command-Upgrade
