### ISSUE TITLE
PeaZip install end in error "Installer failed with exit code: 1"

### ISSUE THREAD

**Issue by giorgiotani** [microsoft/winget-cli#199] opened 2020-05-19 18:31 UTC
# Brief description of your issue
winget install peazip ends in error with "Installer failed with exit code: 1"

Launching the command either from command prompt or powershell, from a Windows 10 machine version 10.0.18363.778 (Italian language), the download and hash verification part are successful: 

Downloading https://sourceforge.net/projects/peazip/files/7.2.1/peazip-7.2.1.WIN64.exe/download
  ██████████████████████████████  8.83 MB / 8.83 MB
Successfully verified installer hash

but the installation part immediately dispays a graphical window with message "Accesso negato" (denied access) and the procedure ends with exit code 1:

Installing ...
Installer failed with exit code: 1

As PeaZip installer is unsigned, it would usually display UAC prompt asking to accept installing application from unknown author, which is the step that seems missing installing the application from winget install peazip.
To test the issue further, I've copied the package from winget path to desktop and launched it with doubleclick as a traditional installer: it worked as expected, displaying UAC prompt and then, after clicking Yes on UAC prompt, the installer ran successfully.

The issue does not change if PeaZip is installed or not installed in the system: in both cases winget does not prompts the UAC dialog and fails with exit code 1, and in both cases the very same package that is saved in winget path can be launched with double click, always successfully completing the installation.

EDIT 
Tested a workaround that confirms the nature of the issue is lack of UAC elevation: start powershell with Run as administrator, you are prompted UAC elevation dialog. Once the powershell is running UAC elevated, running winget install peazip completes installation without any issue (silently, without prompting the GUI of the installer, but it is a very minor problem as all options can be customized later).

# Steps to reproduce

Launch winget install peazip from either cmd or powershell

# Expected behavior

The graphic installer of PeaZip should show UAC prompt for accepting installation of unsigned application from unknown author, and after the user click Yes on the UAC dialog, it should be able to complete the installation procedure

# Actual behavior

At the very beginning of the installation stage it is displayed a graphical window (from Giorgiotani.Peazip.7.2.1.exe package) with message "Accesso negato" and the procedure ends with exit code 1
Please note the UAC screen to accept installation of unsigend application is never shown, this is the most likely source of the error as the package, launched as a traditional installer, works without issues (displays UAC prompt, then run successfully).

# Environment

Windows 10 machine 10.0.18363.778 (Italian language)

winget --info

Windows Package Manager v0.1.41331 Anteprima
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.18363.778
Package: Microsoft.DesktopAppInstaller v1.0.41331.0

**Comment by KevinLaMS** [comment] 2020-05-20 23:14
Duplicate of #189.  Looks to be a duplicate reactivate if you disagree.

**Closed by KevinLaMS** 2020-05-20 23:14 UTC
