### ISSUE TITLE
Manual installation succeeded although it sounded like it didn't

### ISSUE THREAD

**Issue by ermshiperete** [microsoft/winget-cli#235] opened 2020-05-20 07:10 UTC
# Brief description of your issue

Confusing message after installation of winget-cli

# Steps to reproduce

I downloaded the installer for winget from the GitHub release page and opened it which started the installation.

# Expected behavior

A message that the installation was successful.

# Actual behavior

I don't remember what dialog message it put up exactly, but it made it sound like it didn't successfully install. (Maybe it said something that I can now install packages with winget. However, I didn't read it carefully and skimming over it made it sound like the installation didn't succeed).

So I went searching on the Internet how I can install a .appxbundle file, followed the steps and was then presented with the message that the App Installer is already installed.

# Environment

```none
Windows Package Manager v0.1.41331 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.18362.836
Package: Microsoft.DesktopAppInstaller v1.0.41331.0
```

**Comment by xtqqczze** [comment] 2020-05-20 13:19
![image](https://user-images.githubusercontent.com/45661989/82450421-97c7f700-9aa4-11ea-86f6-19bf6d9888a9.png)

**Comment by QAInsights** [comment] 2020-05-20 16:03
@xtqqczze I got the exact message as you mentioned. Were you able to install winget-cli successfully? Please clarify.

**Comment by xtqqczze** [comment] 2020-05-20 16:23
@QAInsights I received that message upon installation, but the `winget` command is in fact available on my command line. So even though the mesage is confusing, the installation actually succeeded.

**Comment by QAInsights** [comment] 2020-05-20 17:49
Okay, for me it is not installed properly.

**Comment by QAInsights** [comment] 2020-05-21 02:32
It worked for for me after configuring the PATH in the environment variable.

**Comment by denelon** [comment] 2020-05-28 17:15
Duplicate of #210

**Closed by denelon** 2020-05-28 17:15 UTC

**Comment by ermshiperete** [comment] 2020-05-28 17:30
No, I don't think it's an exact duplicate. The focus of this issue is on the misleading and confusing message.
