### ISSUE TITLE
Winget download step could be smarter to check if there's already downloaded installer and verify hash matches to avoid re-downloads

### ISSUE THREAD

**Issue by yao-msft** [microsoft/winget-cli#1250] opened 2021-07-01 21:05 UTC
Currently every winget installation related command will trigger a new download. In scenarios that a previous install attempt failed, we can make the download step smarter by checking if there's a previous download and verifies hash, if successful, reuse the previous download.

**Comment by denelon** [comment] 2022-09-19 16:32
Duplicate of #343

**Closed by denelon** 2022-09-19 16:32 UTC
Labels: Issue-Feature
