### ISSUE TITLE
Provide a way to opt-out from preview flight

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/winget-cli#1746] opened 2021-11-26 22:21 UTC
### Description of the new feature / enhancement

Many months ago, I signed up for the preview flight of winget via the link in the README here in the repo. At this point I no longer want to be part of the preview flight, but instead get the same version of everything that "normal" users get that haven't signed up.  I would like to have some way to opt-out from the preview flight.

### Proposed technical implementation details

Maybe just another web form where I can submit my MSA email address to be removed from the preview flight?

**Comment by ItzLevvie** [comment] 2021-11-27 13:30
Duplicate of https://github.com/microsoft/winget-cli/discussions/866#discussioncomment-611421.

**Comment by ItzLevvie** [comment] 2021-11-27 13:31
Duplicate of https://github.com/microsoft/winget-cli/discussions/866.

**Comment by denelon** [comment] 2021-11-29 15:32
Duplicate of #866

**Closed by denelon** 2021-11-29 15:32 UTC
Labels: Issue-Feature, Needs-Triage
