### ISSUE TITLE
winget export returns 'Installed package is not available from any source' error

### ISSUE THREAD

**Issue by MEGAF4IL-Git** [microsoft/winget-cli#5092] opened 2024-12-19 20:48 UTC
### Brief description of your issue

Running 'winget export' regardless of how I use '--output' gives me a large output of the error "Installed package is not available from any source", for everything listed for me with 'winget list'. However, I can use other winget commands flawlessly. 
See added .txt for error output.
[winget export output.txt](https://github.com/user-attachments/files/18202943/winget.export.output.txt)

### Steps to reproduce

I have no idea how to reproduce this bug/error. I have not tampered with WinGet, and have not used WinGet prior to 12/18/2024. 
I have only successfully used 'winget upgrade --all'

### Expected behavior

I expect 'winget export' to do what it is intended to do; Create a file meant to be used for 'winget import' as an easy way to install a list of programs installed on the source PC from which 'winget export' was used on.

### Actual behavior

Running 'winget export' regardless of if/how I use '--output' gives me a large output of the error "Installed package is not available from any source".
See added .txt for error output.
[winget export output.txt](https://github.com/user-attachments/files/18202943/winget.export.output.txt)

### Environment

```shell
Windows Package Manager v1.9.25200
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.4602
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.24.25200.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

**Comment by florelis** [comment] 2024-12-19 21:44
"Installed package is not available from any source" is somewhat of an expected error for many packages. winget can detect everything that is installed on your computer, but it only knows how to install the packages defined in the source, typically the community repo or the MS Store.

For example, it would be able to tell you if you have installed SomeSuperCoolPrivateProject, but not how to install it again elsewhere.

In some cases there may be more than one package that looks like it could be the source, so winget can't decide which one to list for the export. (For example, between `Git.Git` and `Microsoft.Git`)

You can also view the winget logs at `%LocalAppData%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir`; that can tell you why a given package was marked as an error

**Comment by florelis** [comment] 2024-12-19 22:21
> Where do I find the exported .json?

At the path you indicate with `--output`

> Is it even spitting out an export regardless of errors?

The messages you see are not hard errors, just warnings. If your terminal supports colors, warnings should be yellow and actual errors are red.

> `Found multiple packages with strong match fields`
> `Appropriate available package could not be determined`

That means you have something installed that could be multiple packages, so we don't know which one to write in the .json. As a made-up example, if you have `FooBar` installed and we know of packages `A.FooBar` and `B.FooBar`, winget cannot decide which one to pick

> There's also these messages in the logs: `Installed package is available. Package Id [app-name], Source [Microsoft.Winget.Source_placeholder]`

These are the ones that ultimately get written to the .json

> Is there a way I can configure WinGet to determine a manually selected "appropriate available package"?

After the export you can manually edit the .json file. Or you can write it from scratch.

> Could I also configure sources if I need to?

Yes, you can do that with the `winget source` commands. If you already added the source you can tell winget to use only that one with the argument `-s <sourcename>`

**Closed as completed** 2024-12-19 22:43 UTC

**Comment by florelis** [comment] 2024-12-19 22:51
> Because it's not the most intuitive thing, nor is it mentioned in detail anywhere I looked; For future reference and for anyone else figuring out WinGet, be sure to follow-up the `-o` or `--output` arguments with the specific desired destination for your .json, including the name you want for the file. For example: `winget export -o C:\Users\username\Desktop\winget-export.json`
> 
> I originally thought I just had to provide the desired filename after -o/--output Not the most intuitive, nor does the documentation I found contain this clarification in specificity. Hopefully this helps others.

Could you clarify what you were expecting or what command you were using originally? Relative paths e.g. `winget export -o my.json`) should work as well as full paths. It would be a bug if it didn't.

**Comment by florelis** [comment] 2024-12-20 00:26
> I now probably have at least a dozen .json's saved wherever the default save location is, which isn't indicated anywhere in the documentation I found before making this thread, unless I missed those details in said documentation.

There is no default save location. The file is saved to whatever the current working directory is. That is standard for command line applications.
Depending on the settings in your terminal/shell, the working directory appears to the left of the command you are typing.

The initial working directory is usually `C:\Users\username\`, or it can be `C:\Windows\System32\` if you're running as admin. If you have changed to a different directory and the shell does not show it, you can get it by using `cd` in batch, or `pwd`/`Get-Location` in PowerShell.

> As for what I was expecting, I thought it would tell me where the .json saved if it succeeds. It does not.

@denelon Just making sure we don't miss this bit of feedback just because the issue is already closed
