### ISSUE TITLE
add standalone installation file for winget then install it with install-package 

### ISSUE THREAD

**Issue by tlsalex** [microsoft/winget-cli#1936] opened 2022-02-14 03:08 UTC
### Description of the new feature / enhancement

I ps remote to a workstation running windows 10 v20h2 via Enter-PSSession, then I try to run winget to install an application, however I find that winget executable is not available, looks like I need to install it from Microsoft App Store. but I am in a ps remote session , I can't do that.

### Proposed technical implementation details

create a standalone winget package (winget.msi) , user can install it with install-package -name path\to\winget\installation\file. user can then use winget.

**Comment by jedieaston** [comment] 2022-02-14 14:16
Duplicate of #1474 (I'm also feeling your pain on this, but it's a upstream Windows issue. My comments [here](https://github.com/microsoft/winget-cli/issues/1929#issuecomment-1036376464) may help explain).

**Closed by jedieaston** 2022-02-14 14:16 UTC
Labels: Issue-Feature, Needs-Triage
