### ISSUE TITLE
Support internalized package repositories

### ISSUE THREAD

**Issue by JoshPhillips59** [microsoft/winget-cli#213] opened 2020-05-19 20:51 UTC
# Support for internalized package repositories

Rather than rely on a public repo would like to have the option to host the packages via artifactory, or others (necus, proget) in as a remote (like choco does)

# Proposed technical implementation details (optional)

Allow me to customize source of winget installs to point to my internal/hosted repo
Ensure it supports the ability to authenticate to said repo
Repo is able to talk to public repo and fetch packages on demand
packages kept up to date on the fly

**Comment by kilasuit** [comment] 2020-05-20 05:08
this should really just be `Support internalised package repositories` as opposed to just being Artifactory as there are many other tooling options in this space like Nexus, Proget etc

**Comment by JoshPhillips59** [comment] 2020-05-20 13:12
Great point, will update

**Comment by denelon** [comment] 2020-05-22 22:59
This might be a duplicate of #118. If you agree, please close this one as a duplicate. If not, feel free to leave this Issue open.

**Comment by megamorf** [comment] 2020-05-23 00:36
Related issues:
* #160 
* #203
* #213
* #226

**Comment by JoshPhillips59** [comment] 2020-05-23 14:49
> This might be a duplicate of #118. If you agree, please close this one as a duplicate. If not, feel free to leave this Issue open.

I don't think having a REST API is the same as supporting these others or intenalzied.  The way the rest one is worded could very well just be the/another MSFT repo.

**Comment by denelon** [comment] 2021-08-06 17:01
@JoshPhillips59 support for private sources is available via the REST API. We have provided a [reference implementation](https://github.com/microsoft/winget-cli-restsource). We're still working on documentation, and a couple of other features mentioned like Authentication [Authn/Authz](https://github.com/microsoft/winget-cli-restsource/issues/37) & [MSA](https://github.com/microsoft/winget-cli-restsource/issues/52). Your last two items should be additional Issues for the reference implementation (you could certainly build a custom interface for those as well).

**Closed by denelon** 2021-08-06 17:01 UTC
Labels: Issue-Feature

**Comment by tb-mtg** [comment] 2023-11-02 22:37
Any updates on this?

**Comment by nascentt** [comment] 2025-06-01 19:25
this was renamed from support artifactory, to support internalized repos and then closed because of rest api, but it still doesnt support artfactory..
