### ISSUE TITLE
winget list --source winget - filtering does not work

### ISSUE THREAD

**Issue by Dobrowit** [microsoft/winget-cli#3990] opened 2023-12-18 08:43 UTC
### Brief description of your issue

Commands:
```
winget list --source winget 
winget list -s winget
```
do not return a filtered list. The list contains all packages. The **--source** and **-s** switches do not work. Only the "Source" column disappears from the resulting list.

### Steps to reproduce

Enter in cmd.exe command:
`winget list --source winget `
or
`winget list -s winget`

### Expected behavior

After issuing the command
`winget list --source winget `
I expect a list that contains items that are labeled "winget" in the "Source" column.

### Actual behavior

Filtering does not work. The list of packages includes all items.

### Environment

```shell
Windows Package Manager v1.6.3421
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.2861
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3421.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by denelon** [comment] 2023-12-18 15:56
Duplicate of #1155 

* #1155

**Closed** 2023-12-18 15:56 UTC
Labels: Needs-Triage
