### ISSUE TITLE
Failed when searching source; results will not be included: msstore

### ISSUE THREAD

**Issue by eccrk** [microsoft/winget-cli#3579] opened 2023-09-02 07:20 UTC
### Brief description of your issue

PS C:\Windows\System32> winget update
Failed when searching source; results will not be included: msstore

Note:
winget update --verbose --logs

does not produce a new log file

### Steps to reproduce

Entirely reproducible 

### Expected behavior

To see results from both winget and msstore

### Actual behavior

Only winget store available 

### Environment

```shell
Windows Package Manager v1.5.2201
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2215
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.2201.0
```

**Comment by mdanish-kh** [comment] 2023-09-02 09:09
Duplicate of #3575

**Closed** 2023-09-02 09:09 UTC
