### ISSUE TITLE
Cannot find MSStore package using winget search

### ISSUE THREAD

**Issue by rkeithhill** [microsoft/winget-cli#1988] opened 2022-03-01 17:49 UTC
### Brief description of your issue

I want to install [NuGet Package Explorer](https://www.microsoft.com/store/productId/9WZDNCRDMDM3) but first I want to find it so I can get its `id` for install.  But so far, my efforts to find this package have been fruitless.

### Steps to reproduce

```
winget search "NuGet Package Explorer"  --source msstore
winget search NuGet --source msstore
```

### Expected behavior

I expect winget search to find this store package.

### Actual behavior

```
> winget search "NuGet Package Explorer" -s msstore
No package found matching input criteria.
```

### Environment

```shell
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.1526
Package: Microsoft.DesktopAppInstaller v1.17.10271.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links               
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by ImJoakim** [comment] 2022-03-01 20:06
It looks like you don't have the `msstore` source, meaning you're unable to search and install packages from `msstore` (for example NuGet Package Explorer as you mentioned). 

You can reset your sources by typing `winget source reset --force` with administrator privileges.

**Comment by rkeithhill** [comment] 2022-03-01 20:12
That's a bit weird given that the msstore is listed as a source and I can find some packages on the store: 

![image](https://user-images.githubusercontent.com/5177512/156241542-7c7c68f3-120e-419e-ba8a-b46d3c0d14ad.png)

**Comment by ImJoakim** [comment] 2022-03-01 20:18
> That's a bit weird given that the msstore is listed as a source and I can find some packages on the store:
> 
> Tried the `winget source reset --force` and it still does not find that package.

That's odd, can you try searching for the ID? `winget search 9WZDNCRDMDM3` and see if anything pops up.

**Comment by denelon** [comment] 2022-03-01 20:48
I was able to reproduce the search for "NuGet Package Explorer" not returning any results. I've contacted the store team to see if we can determine if it's being filtered out of results or if something else is going on.

**Comment by rkeithhill** [comment] 2022-03-01 21:23
@ImJoakim That does work - thanks.

```
> winget search 9WZDNCRDMDM3
Name                   Id           Version Source
----------------------------------------------------
NuGet Package Explorer 9WZDNCRDMDM3 Unknown msstore
```

**Comment by denelon** [comment] 2022-03-07 15:41
We've identified the issue causing the bad search experience. A fix is in progress. It was related to architecture selection at the "msstore" REST source.

**Comment by denelon** [comment] 2022-03-11 15:23
Quick update:

The fix is working in the testing environments. Tentative deployment date is March 15th, 2022.

**Comment by davidanthoff** [comment] 2022-03-11 18:07
Thanks for the update, and I really appreciate this getting fixed.

At the same time, I am wondering about process and timelines in general. For background: we have a new MSIX/Windows Store based installer for the [Julia programming language](https://julialang.org/). We have not yet made it the default installer, but were planning for that in the next few months. At that point, our plan was to make the primary instructions to install Julia on Windows to run `winget install julia -s msstore`. _If_ we had been at that point already, then my understanding is that this incidence would have meant that our primary instructions on how to install Julia on Windows would have been broken and not been working for about two weeks. This would affect new users, all continuous integration workflows that thousands of package developers depend on every day etc. To put it mildly, that would have been a catastrophe. So I guess we are at a tricky cross road now where we are wondering whether the combination of `winget` and Windows Store is actually providing the level of reliability that we need?

I'd just be curios to hear how MS is thinking about this. If say accidentally a version of the Windows Store was deployed that was broken and users couldn't install software, I assume there would be an emergency process in place to just roll that deployment back within a few hours? I can't imagine that such a situation would be allowed to linger for two weeks, right? Are there any plans to move to a similar process for a situation like the bug described in this issue for winget?

I think another way to phrase this is: I think bugs can always happen, but for a large user base piece of software like Julia (best guess is more than a million users at the moment), if we are to adopt something like winget/Store as our main delivery vehicle, I think a downtime of say a few hours or maybe a day at most would still be OK, but really not much more than that. I don't see any scenario where we could take a dependency on something that might just stop working for two weeks...

**Comment by denelon** [comment] 2022-03-11 18:54
@davidandthoff,

Thank you for the background and the critical feedback. I absolutely agree with you. I'm sharing your comments with the various teams involved. I will follow up with more detail.

**Comment by denelon** [comment] 2022-03-21 20:29
@davidandthoff,

The team responsible for the "msstore" source is adding additional testing to their automated suite to include daily response validation for all packages as well as additional end to end testing to ensure this doesn't happen in the future. We've also established a clear process to raise these kinds of issues as high priority if they are detected by other teams as well as ours when Issues have been submitted.

**Closed by denelon** 2022-03-21 20:29 UTC
Labels: Issue-Bug, Resolution-External, msstore

**Comment by StefanKarpinski** [comment] 2025-04-01 16:45
This issue seems to still be happening with the same repercussions as described by @davidanthoff [above](https://github.com/microsoft/winget-cli/issues/1988#issuecomment-1065357247). Except that now `juliaup` is the default way to install and manage Julia versions. In 2022, @denelon wrote:

> We've also established a clear process to raise these kinds of issues as high priority if they are detected by other teams as well as ours when Issues have been submitted.

What is that process? Because it seems like we need it.

**Comment by StefanKarpinski** [comment] 2025-04-01 17:53
Update: the reporter may have been using an older version of winget-cli. It would be great to know what the reporting process is if this does happen in the future though.
