### ISSUE TITLE
winget upgrade --all fails to perform upgrade

### ISSUE THREAD

**Issue by rdavies3** [microsoft/winget-cli#4250] opened 2024-03-07 16:07 UTC
### Brief description of your issue

When running winget upgrade --all, it shows a list of packages to upgrade, but does not actually perform any upgrades.  

### Steps to reproduce

When new packages are availabe, run `winget upgrade --all`.  The list of package(s) to upgrade display, but no upgrades occur.  I can upgrade single packages just fine with `winget upgrade <package>`.

### Expected behavior

All packages with available upgrades should be downloaded and installed (except for specific pinned versions and the like).  

### Actual behavior

List of packages is shown, but no upgrading occurs.

### Environment

```shell
winget --info
Windows Package Manager v1.7.10582
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.2713
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10582.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by denelon** [comment] 2024-03-07 20:55
@rdavies3 can you run with verbose logging and share the logs?

You can append "--verbose-logs --logs" to run the command and launch the folder with the logs.

**Comment by denelon** [comment] 2024-03-07 20:56
Duplicate of #4219 

* #4219

**Closed** 2024-03-07 20:57 UTC
Labels: Issue-Bug
