### ISSUE TITLE
Authentication for sources

### ISSUE THREAD

**Issue by thilojaeggi** [microsoft/winget-cli#3399] opened 2023-07-01 00:02 UTC
### Description of the new feature / enhancement

Currently all package manifests/installers are available to any client that adds a WinGet source, this may be fine for public repos but could be a security concern for private repositories.

Sure you could do IP-limitting on your web server/firewall rules but I think a Winget integrated solution for the REST type would be best.

### Proposed technical implementation details

I suppose this could be solved with using key-pair based authentication?

**Comment by thilojaeggi** [comment] 2023-07-01 06:34
Just to add, I'm willing to give a shot at developing this myself.

**Comment by Trenly** [comment] 2023-07-01 18:30
Duplicate of #1918

**Closed** 2023-07-01 18:31 UTC
Labels: Issue-Feature

**Comment by thilojaeggi** [comment] 2023-10-05 19:07
Is this still being considered/worked on @denelon as I've seen people (against my advice) spin up public facing WinGetty instances and I can technically read out and download their packages?
