### ISSUE TITLE
Skip some app that don't want to be upgraded

### ISSUE THREAD

**Issue by gavinn212** [microsoft/winget-cli#2196] opened 2022-05-28 19:10 UTC
### Description of the new feature / enhancement

Hi, the idea is simple, some cracked software (not proud of that, but they're expensive) won't work once it's upgraded. Or some work requires a specific version of the software. It would be nice to allow users to choose some app that won't check the available upgrade

**Comment by Masamune3210** [comment] 2022-05-29 02:46
App Pinning is what you are looking for and it already has a issue tracking it

**Comment by jedieaston** [comment] 2022-05-31 00:24
Duplicate of https://github.com/microsoft/winget-cli/issues/476

**Comment by jedieaston** [comment] 2022-05-31 00:25
Duplicate of #476

**Closed by jedieaston** 2022-05-31 00:25 UTC
Labels: Issue-Feature, Needs-Triage
