### ISSUE TITLE
winget doesn't waiting for batte.net to complete installation before moving to the next package

### ISSUE THREAD

**Issue by jpbnetley** [microsoft/winget-cli#1111] opened 2021-06-04 20:13 UTC
# Brief description of your issue
When running `winget upgrade --all`
When it gets to Battle.Net, winget doesn't wait for the installer to complete before upgrading the next package.
# Steps to reproduce

Start the terminal as Admin.
If Battle.Net is installed, and at least 1 other package also requires an upgrade run  `winget upgrade --all`
winget will start to upgrade Battle.Net

# Expected behavior

winget waits for for the Battle.Net installer to complete before moving to the next package to upgrade.

# Actual behavior

Once the installer starts, the Battle.Net installer downloads the update separately.
While this is happening, winget states the package is successfully installed
But the Battle.Net installer is still doing the update.
![winget battle net](https://user-images.githubusercontent.com/25173863/120857191-28268c00-c581-11eb-9ae1-cceb61b21281.jpg)

# Environment

```none
[winget --info]
Windows Package Manager version:  v1.0.11451
Windows: Windows.Desktop version: v10.0.19043.985
Package: Microsoft.DesktopAppInstaller version:  v1.11.11451.0

Any other software?
```

I am not sure if I should log this under [winget-cli](https://github.com/microsoft/winget-cli) or under [winget-pkgs](https://github.com/microsoft/winget-pkgs)

**Comment by jpbnetley** [comment] 2021-06-04 20:22
I see something similar was discussed with discord here: https://github.com/microsoft/winget-cli/issues/189#issuecomment-827860443
Might be related.

**Comment by denelon** [comment] 2021-06-04 20:23
@jpbnetley https://github.com/microsoft/winget-cli/issues/418 looks like a possible duplicate.

**Comment by jpbnetley** [comment] 2021-06-04 20:24
> @jpbnetley #418 looks like a possible duplicate.

Yea I think the fix for discord should fix it for Battle.Net.
Not sure if its package specific or if its handled by winget.

If it is the same, I apologise for the inconvenience.
You may close this then :)

**Comment by denelon** [comment] 2021-06-04 20:25
No worries 😊

It's hard to find duplicates in an active project. Not to mention one that spans multiple repositories.

Duplicate of #418

**Closed by denelon** 2021-06-04 20:25 UTC
Labels: Needs-Triage

**Comment by jpbnetley** [comment] 2021-06-04 20:27
@denelon Hats off to you guys keeping track of duplicate issues across multiple repos 👏
