### ISSUE TITLE
Program 'winget.exe' failed to run at line 1 char 1

### ISSUE THREAD

**Issue by raikoug** [microsoft/winget-cli#712] opened 2021-01-23 12:08 UTC
# Brief description of your issue

Typing winget on powershell or cmd just throws error.

# Steps to reproduce

Nothing special, applied to Insider program and tried install new App Manager via microsoft store.

# Expected behavior
Having winget app working

# Actual behavior
Typing winget returns:
```
Program 'winget.exe' failed to run: The system cannot find the file specified
At line:1 char:1
+ winget
+ ~~~~~~.
In riga:1 car:1
+ winget
+ ~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```
I then tried debugging it:

```
PS C:\Users\Admin>Trace-Command -Expression {winget} -Name CommandDiscovery -PSHost | out-null
DEBUG: CommandDiscovery Information: 0 : Looking up command: winget
... skipping all path discovery ...
DEBUG: CommandDiscovery Information: 0 : Command Found: path (C:\Users\Admin\AppData\Local\Microsoft\WindowsApps\winget.exe) is an application with name: winget.exe
DEBUG: CommandDiscovery Information: 0 : Looking up command: Set-StrictMode
DEBUG: CommandDiscovery Information: 0 : Cmdlet found: Set-StrictMode  Microsoft.PowerShell.Commands.SetStrictModeCommand
DEBUG: CommandDiscovery Information: 0 : Looking up command: Set-StrictMode
DEBUG: CommandDiscovery Information: 0 : Cmdlet found: Set-StrictMode  Microsoft.PowerShell.Commands.SetStrictModeCommand
DEBUG: CommandDiscovery Information: 0 : Looking up command: Set-StrictMode
DEBUG: CommandDiscovery Information: 0 : Cmdlet found: Set-StrictMode  Microsoft.PowerShell.Commands.SetStrictModeCommand
DEBUG: CommandDiscovery Information: 0 : Looking up command: Set-StrictMode
DEBUG: CommandDiscovery Information: 0 : Cmdlet found: Set-StrictMode  Microsoft.PowerShell.Commands.SetStrictModeCommand
Program 'winget.exe' failed to run: The system cannot find the file specified
At line:1 char:28
+ Trace-Command -Expression {winget} -Name CommandDiscovery -PSHost | o ...
+                            ~~~~~~.
At line:1 char:28
+ Trace-Command -Expression {winget} -Name CommandDiscovery -PSHost | o ...
+                            ~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

# Environment

```none
[winget --info]
Windows Package Manager version Can't run winget do I can't say it for sure
Windows: Windows.Desktop version 10.0.19042 N/D build 19042 (if this is the value needed)
Package: Microsoft.DesktopAppInstaller version - Windows Store doesn't state the version

Any other software? WSL and hyper-v enabled
```

**Comment by denelon** [comment] 2021-01-25 20:07
There is some calendar time on our hands currently between requesting access to the Windows Package Manager insiders program and getting the update to the "App Installer" in the store. Is this still happening? Have you been able to get the update to the App Installer?

**Comment by freeone3000** [comment] 2021-02-04 16:00
Hi, this is still happening to me. The installer from the github page says a new version is already installed, but I get exactly this error.

**Comment by denelon** [comment] 2021-04-27 21:39
@freeone3000 have you checked to see if you have the App Execution Alias enabled for "winget"?

**Comment by rbeesley** [comment] 2021-05-31 22:42
This is a problem I'm seeing too. I'm on 20H2 and enabled this from joining the  "Windows Package Manager Insider Program." I have the same failure trying to run winget from PowerShell and in a Command Prompt I get the following results:
```
C:\Users\[REDACTED]\AppData\Local\Microsoft\WindowsApps>dir
 Volume in drive C is Local Disk
 Volume Serial Number is 0000-0000

 Directory of C:\Users\[REDACTED]\AppData\Local\Microsoft\WindowsApps

05/29/2021  04:05 PM    <DIR>          Backup
...
05/21/2021  08:24 AM                 0 winget.exe
05/26/2021  12:59 AM                 0 wt.exe
               x File(s)              0 bytes
               y Dir(s)  zzz,zzz,zzz,zzz bytes free

C:\Users\[REDACTED]\AppData\Local\Microsoft\WindowsApps>winget.exe
The system cannot find the file C:\Users\[REDACTED]\AppData\Local\Microsoft\WindowsApps\winget.exe.
```

Windows Package Manager Client (winget.exe) is listed as an App Execution Alias and it is enabled. The version of App Installer installed according to Microsoft Store is version 1.11.11451.0.

**Comment by rbeesley** [comment] 2021-05-31 22:50
And as further assistance to resolving this issue, I toggled the App Execution Alias off, then back on, and it works now. So I believe this should be considered a workaround, but it can be an issue. Other environment concerns which might be related, When I tried to promote the installation of winget, there was a pending reboot. This was also performed from a second account on my system, which while an Administrator account is not the primary account I installed Windows from.

**Comment by denelon** [comment] 2021-06-01 01:58
@rbeesley thanks for the additional context.

**Comment by denelon** [comment] 2021-06-01 22:40
This appears to be related to how Windows is handling some of the package registration. We will have to continue investigating this issue to see if we can identify the root cause and see if there is a fix we can make or work with another team to implement a fix.

**Comment by A9G-Data-Droid** [comment] 2021-06-09 15:53
I'm linking my [post](https://github.com/microsoft/winget-cli/issues/995#issuecomment-857822132) over on a related issue because it seems to be relevant. It's possible that these two issues should be merged.

**Comment by denelon** [comment] 2021-10-01 21:51
@raikoug

We've published the v1.1 [release candidate](https://github.com/microsoft/winget-cli/releases/tag/v1.1.12653) and updated our [troubleshooting guide](https://github.com/microsoft/winget-cli/tree/master/doc/troubleshooting).

Can you confirm if this is still happening?

**Comment by A9G-Data-Droid** [comment] 2021-10-01 22:30
I'm getting the same error after installing the latest version from an administrative PowerShell session.

```
PS C:\WINDOWS\system32> add-appxpackage -Path "C:\Users\snip\Downloads\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle"   

PS C:\WINDOWS\system32> winget
Program 'winget.exe' failed to run: The file cannot be accessed by the systemAt line:1 char:1
+ winget
+ ~~~~~~.
At line:1 char:1
+ winget
+ ~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

PS C:\WINDOWS\system32> Get-AppxPackage microsoft.desktopappinstaller


Name              : Microsoft.DesktopAppInstaller
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 1.16.12653.0
PackageFullName   : Microsoft.DesktopAppInstaller_1.16.12653.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.16.12653.0_x64__8wekyb3d8bbwe
IsFramework       : False
PackageFamilyName : Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
Dependencies      : {Microsoft.VCLibs.140.00.UWPDesktop_14.0.30035.0_x64__8wekyb3d8bbwe, Microsoft.DesktopAppInstaller_1.16.12653.0_neutral_split.scale-100_8wekyb3d8bbwe}
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok
```

**Comment by cccsss01** [comment] 2021-12-25 17:50
I get the same exact thing, and now it looks like I have two:
![image](https://user-images.githubusercontent.com/56396984/147390703-fedb745f-2f69-407d-8727-bd853d31e70b.png)

**Comment by denelon** [comment] 2022-06-21 16:02
https://github.com/microsoft/winget-cli/tree/master/doc/troubleshooting

**Closed by denelon** 2022-06-21 16:02 UTC
Labels: Issue-Bug, Area-External

**Comment by vzabawski** [comment] 2023-11-20 17:03
I had the same issue and I've noticed winget works under regular user, but doesn't work under Administrator. So, running regular Terminal helped me.

**Comment by A9G-Data-Droid** [comment] 2023-11-20 17:13
> I had the same issue and I've noticed winget works under regular user, but doesn't work under Administrator. So, running regular Terminal helped me.

That's the crux: The goal of a package manager is to be able to run `winget upgrade --all` as admin, to update all software on the computer system. If you run as a regular user you can't update all the software. If you run as admin, it just fails. 

You can't use winget to manage software in an enterprise. If you could combine this with InTune you could manage Windows systems in a similar fashion to Linux systems. Linux had package management figured out decades ago, and it's open source. All Microsoft had to do was read the source of [aptitude](https://salsa.debian.org/apt-team/aptitude)
