### ISSUE TITLE
Change the default installation path

### ISSUE THREAD

**Issue by Flokri1** [microsoft/winget-cli#1271] opened 2021-07-11 15:19 UTC
It would be nice if you can change the installation path of the C drive so that you don't always save everything on C but also e.g. on the D: drive.

**Comment by denelon** [comment] 2021-07-12 15:45
@Flokri1 the client supports `-l` or `--location` if the installer supports a different install location. I think we could consider a setting for this behavior also.

**Comment by denelon** [comment] 2021-07-12 15:45
Duplicate of #201

**Closed by denelon** 2021-07-12 15:45 UTC
Labels: Issue-Feature
