### ISSUE TITLE
[Request] Add Fonts Support

### ISSUE THREAD

**Issue by garmede** [microsoft/winget-cli#392] opened 2020-05-20 09:33 UTC
At least i wish Cascadia.

**Comment by TylerLeonhardt** [comment] 2020-12-28 03:32
Need this to resolve https://github.com/tonsky/FiraCode/issues/1177

**Comment by shalva97** [comment] 2021-07-20 12:27
any updates on this?

**Comment by ChungZH** [comment] 2021-08-22 03:21
good idea

**Comment by glen-84** [comment] 2022-02-04 18:17
Duplicate of #166.

**Comment by Trenly** [comment] 2022-02-09 04:32
> Duplicate of #166.

cc @denelon

**Comment by denelon** [comment] 2022-02-09 18:18
Duplicate of #166

**Closed by denelon** 2022-02-09 18:18 UTC
Labels: Issue-Feature
