### ISSUE TITLE
Microsoft Teams [Microsoft.Teams] Another version of this application is already installed

### ISSUE THREAD

**Issue by myokeeh** [microsoft/winget-cli#2323] opened 2022-07-11 01:57 UTC
### Brief description of your issue

Microsoft Teams upgrade/update never succeeds on multiple machines.

`winget upgrade --all`

(6/6) Found Microsoft Teams [Microsoft.Teams] Version 1.5.00.14473
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1638
Installer log is available at: C:\Users\Carlo\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Microsoft.Teams.1.5.00.14473-2022-07-10-18-52-24.677.log
Another version of this application is already installed

### Steps to reproduce

Run `winget upgrade --all` on Windows 11

### Expected behavior

Successful upgrade/update

### Actual behavior

Installer failed with exit code: 1638
Installer log is available at: C:\Users\Carlo\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Microsoft.Teams.1.5.00.14473-2022-07-10-18-52-24.677.log
Another version of this application is already installed

### Environment

```shell
Windows Package Manager v1.3.1872
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.169
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.1872.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
```

**Comment by Trenly** [comment] 2022-07-11 13:27
Duplicate of https://github.com/microsoft/winget-pkgs/issues/61420

**Closed** 2022-07-11 14:41 UTC
Labels: Resolution-Duplicate
