### ISSUE TITLE
Not able to download updates for teams.

### ISSUE THREAD

**Issue by TonkyCZ** [microsoft/winget-cli#1879] opened 2022-01-26 20:22 UTC
### Brief description of your issue

<img width="749" alt="winget" src="https://user-images.githubusercontent.com/64232608/151240034-6a346f26-4fec-455d-aac7-3e6a3223c1f2.png">

### Steps to reproduce

Updateting Microsoft Teams in Windows 11 with teams for W11 and teams for coporations and school.

### Expected behavior

Update the teams by selected ID

### Actual behavior

Unable to update teams.

### Environment

```shell
Windows Package Manager v1.1.13405
Copyright (c) Microsoft Corporation. Všechna práva vyhrazena.

Windows: Windows.Desktop v10.0.22000.376
Balíček: Microsoft.DesktopAppInstaller v1.16.13405.0
```

**Comment by denelon** [comment] 2022-01-29 02:44
Are you getting the same error as reported in https://github.com/microsoft/winget-cli/issues/752#issuecomment-825606893?

This looks like it might be a duplicate.

**Comment by TonkyCZ** [comment] 2022-01-29 23:45
I don't rememer the error code, but it look like the same issue.

**Comment by denelon** [comment] 2022-01-31 17:08
Dulicate of #752

**Comment by denelon** [comment] 2022-01-31 17:34
lol, thanks 😊. 

Duplicate of #752

**Closed by denelon** 2022-01-31 17:34 UTC
Labels: Issue-Bug
