### ISSUE TITLE
There are not enough lists that can be output with the winget export command.

### ISSUE THREAD

**Issue by TakamiChie** [microsoft/winget-cli#1875] opened 2022-01-24 05:32 UTC
### Brief description of your issue

In the list of applications that can be output with the "winget export" command, there are applications installed from winget but not included in the list.

It has also been posted in Windows Feedback.
https://aka.ms/AAfaudn

### Steps to reproduce

1. Run the following command groups:
```powershell
winget install OlegDanilov.RapidEnvironmentEditor
winget install RubyInstallerTeam.Ruby
winget install JRSoftware.InnoSetup
winget install Microsoft.GitCredentialManagerCore
winget install OpenShot.OpenShot
```
2. Run `winget export -o list.json`.
3. Open `list.json` in a text editor.

### Expected behavior

All package IDs installed in step 1 are listed in the JSON file.

### Actual behavior

The information for the package installed in step 1 is not described in the JSON file.

### Environment

```shell
[winget --info]
Windows Package Manager (Preview) v1.2.3411-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1466
パッケージ: Microsoft.DesktopAppInstaller v1.17.3411.0
```

**Comment by jedieaston** [comment] 2022-01-24 13:25
Duplicate of #1274

(I'll crosspost this list of apps over there so we have it too)

**Closed by jedieaston** 2022-01-24 13:25 UTC
Labels: Needs-Triage

**Comment by ItzLevvie** [comment] 2022-01-28 13:48
Fixed `Microsoft.GitCredentialManagerCore` in https://github.com/microsoft/winget-pkgs/pull/43699:
![image](https://user-images.githubusercontent.com/11600822/151557693-580da511-ddf9-4659-84e6-22ded3c6e8ed.png)

Fixed `RubyInstallerTeam.Ruby` in https://github.com/microsoft/winget-pkgs/pull/43698:
![image](https://user-images.githubusercontent.com/11600822/151557918-853ebb10-33ca-43da-bf91-c9045b8bf6b1.png)
