### ISSUE TITLE
Completed upgrades are listed again in upgrades list

### ISSUE THREAD

**Issue by ArunJRK** [microsoft/winget-cli#1519] opened 2021-09-28 17:15 UTC
# Issue Description

I had upgraded lot of packages using winget command and right after the upgrade when I run the upgrade command, I get an output of the same list of softwares which I upgraded earlier.

# Steps to reproduce

I ran the below command and got the following output.

```
PS C:\WINDOWS\system32> winget upgrade --all --silent
Found Thunderbird [Mozilla.Thunderbird] Version 68.8.0
Found Mozilla Thunderbird [Mozilla.Thunderbird] Version 91.1.2
Found Mozilla Thunderbird [Mozilla.Thunderbird] Version 91.1.2
Found PostgreSQL [PostgreSQL.PostgreSQL] Version 13
Found PyCharm Community Edition [JetBrains.PyCharm.Community] Version 212.5284.44
Found Robo 3T [3T.Robo3T] Version 1.4.4
Found TeamViewer [TeamViewer.TeamViewer] Version 15.21.8
Found Unity Hub [UnityTechnologies.UnityHub] Version 2.4.5
Found Zotero [Zotero.Zotero] Version 5.0.96.3
Found MongoDB Server [MongoDB.Server] Version 5.0.2
Found Python 3 [Python.Python.3] Version 3.9.7150.0
Found Microsoft Visual C++ 2013 Redistributable (x86) [Microsoft.VC++2013Redist-x86] Version 12.0.40664.0
Found  [Mozilla.Thunderbird] Version 68.8.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/68.8.0/win32/en-US/Thunderbird%20Setup%2068.8.0.exe
  ██████████████████████████████  38.8 MB / 38.8 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Found  [Mozilla.Thunderbird] Version 91.1.2
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/91.1.2/win64/en-US/Thunderbird%20Setup%2091.1.2.exe
  ██████████████████████████████  53.8 MB / 53.8 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Found  [Mozilla.Thunderbird] Version 91.1.2
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/91.1.2/win64/en-US/Thunderbird%20Setup%2091.1.2.exe
  ██████████████████████████████  53.8 MB / 53.8 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Found  [PostgreSQL.PostgreSQL] Version 13
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://get.enterprisedb.com/postgresql/postgresql-13.3-2-windows-x64.exe
  ██████████████████████████████   262 MB /  262 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Found  [JetBrains.PyCharm.Community] Version 212.5284.44
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://download.jetbrains.com/python/pycharm-community-2021.2.2.exe
  ██████████████████████████████   371 MB /  371 MB
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1223

Found  [3T.Robo3T] Version 1.4.4
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://github.com/Studio3T/robomongo/releases/download/v1.4.4/robo3t-1.4.4-windows-x86_64-e6ac9ec5.exe
  ██████████████████████████████  58.2 MB / 58.2 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Found  [TeamViewer.TeamViewer] Version 15.21.8
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://dl.teamviewer.com/download/version_15x/TeamViewer_Setup_x64.exe
  ██████████████████████████████  33.0 MB / 33.0 MB
Installer hash does not match; this cannot be overridden when running as admin

Found  [UnityTechnologies.UnityHub] Version 2.4.5
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.exe
  ██████████████████████████████  51.5 MB / 51.5 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Found  [Zotero.Zotero] Version 5.0.96.3
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://download.zotero.org/client/release/5.0.96.3/Zotero-5.0.96.3_setup.exe
  ██████████████████████████████  41.4 MB / 41.4 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Found  [MongoDB.Server] Version 5.0.2
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://downloads.mongodb.org/windows/mongodb-windows-x86_64-5.0.2-signed.msi
  ██████████████████████████████   273 MB /  273 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Found  [Python.Python.3] Version 3.9.7150.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://www.python.org/ftp/python/3.9.7/python-3.9.7-amd64.exe
  ██████████████████████████████  27.5 MB / 27.5 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Found  [Microsoft.VC++2013Redist-x86] Version 12.0.40664.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://download.visualstudio.microsoft.com/download/pr/10912113/5da66ddebb0ad32ebd4b922fd82e8e25/vcredist_x86.exe
  ██████████████████████████████  6.20 MB / 6.20 MB
Successfully verified installer hash
Starting package uninstall...
Successfully uninstalled
Starting package install...
Successfully installed
```

# Expected behavior

The updated apps should not be listed again for an upgrade.

# Actual behavior

I ran the `winget upgrade` command but same packages were listed again for upgrade.
```
Name                      Id                          Version      Available    Source
--------------------------------------------------------------------------------------
Google Chrome             Google.Chrome               93.0.4577.82 94.0.4606.61 winget
MongoDB Compass           MongoDB.Compass.Full        1.23.0       1.28.1.0     winget
Mozilla Thunderbird       Mozilla.Thunderbird         60.9.1       91.1.2       winget
Mozilla Thunderbird       Mozilla.Thunderbird         68.8.0       91.1.2       winget
PostgreSQL                PostgreSQL.PostgreSQL       9.5          13           winget
PyCharm Community Edition JetBrains.PyCharm.Community 211.7628.24  212.5284.44  winget
Robo 3T                   3T.Robo3T                   1.4.3        1.4.4        winget
Sourcetree                Atlassian.Sourcetree        3.3.8        3.4.6.0      winget
TeamViewer                TeamViewer.TeamViewer       15.11.6      15.21.8      winget
Unity Hub                 UnityTechnologies.UnityHub  2.2.2        2.4.5        winget
Zotero                    Zotero.Zotero               5.0.73       5.0.96.3     winget
MongoDB Server            MongoDB.Server              4.4.6        5.0.2        winget
Adobe Acrobat Reader DC   Adobe.AdobeAcrobatReaderDC  20.009.20067 21.007.20091 winget
Python 3                  Python.Python.3             3.6.3150.0   3.9.7150.0   winget
14 upgrades available.
```

# Environment

```none
Windows Package Manager v1.0.12576
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.1237
Package: Microsoft.DesktopAppInstaller v1.16.12576.0
```

**Comment by gintuoklis** [comment] 2021-09-30 08:32
I have the same issue with package Toggl.TogglDesktop

Steps to reproduce:
```
winget install Toggl.TogglDesktop
winget upgrade
```

![image](https://user-images.githubusercontent.com/16342128/135416883-74fe5be8-b97c-4bac-a392-3d15db954db1.png)

**Comment by jedieaston** [comment] 2021-09-30 15:11
These issues are being tracked in #752, with some possible solutions listed [here](https://github.com/microsoft/winget-cli/issues/752#issuecomment-915632239).

**Comment by denelon** [comment] 2021-10-01 00:29
Duplicate of #752

**Closed by denelon** 2021-10-01 00:29 UTC
Labels: Issue-Bug
