### ISSUE TITLE
PowerShell CLI Friendly

### ISSUE THREAD

**Issue by soroshsabz** [microsoft/winget-cli#1088] opened 2021-06-03 08:59 UTC
ITNOA

# Description of the new feature/enhancement

As you can know PowerShell is great Scripting Language for Automation and Administration of system. and it is built by Microsoft, so I think it is very good for winget-cli to get compatible with PowerShell and make native PowerShell [Cmdlet](https://docs.microsoft.com/en-us/powershell/scripting/lang-spec/chapter-13?view=powershell-7.1) and make great integration with [OneGet](https://github.com/OneGet/oneget) platform for provide a native and consistent user experience in Microsoft Ecosystem.

In this area we can see below command instead of Linux legacy CLI style like `winget install foo`

`Install-Package foo`
`Update-Package foo`
`Get-Package foo`

And all of them is object and we can work with them in OOP area with modern and great and consistent experience in PowerShell World.

# Proposed technical implementation details (optional)

I think PowerShell has many guideline and documentation about writing and designing great Cmdlet and modules that winget-cli teams have to follow it for example

[Windows PowerShell Cmdlet Concepts](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/windows-powershell-cmdlet-concepts?view=powershell-7.1)
[Writing a Windows PowerShell Module](https://docs.microsoft.com/en-us/powershell/scripting/developer/module/writing-a-windows-powershell-module?view=powershell-7.1)
[PowerShell Script Module Design: Building Tools to Automate the Process](https://mikefrobbins.com/2018/11/01/powershell-script-module-design-building-tools-to-automate-the-process/)
[Powershell: DSL design patterns](https://powershellexplained.com/2017-03-13-Powershell-DSL-design-patterns/)

**Comment by gvvad** [comment] 2021-06-03 10:08
Duplicate of #674

**Closed** 2021-06-03 10:14 UTC
Labels: Issue-Feature, Needs-Triage

**Comment by soroshsabz** [comment] 2021-06-03 11:45
Duplicate of #221
