### ISSUE TITLE
do I have to figure it out for myself?

### ISSUE THREAD

**Issue by henrypp** [microsoft/winget-cli#4033] opened 2024-01-05 20:45 UTC
### Description of the new feature / enhancement

Its for me programmers left what is going after ...???

![sshot-001](https://github.com/microsoft/winget-cli/assets/3902025/f4acfecc-b5fa-4db7-a5dc-55535a899b3d)

and how to "winget install WTF" i need speculate?

**Comment by Trenly** [comment] 2024-01-05 21:07
When going from the preinstalled version of WebView to a manually installed version, it may be necessary to uninstall the older version first because the installer won't have the right permissions to update the preinstalled version.

Try running `winget uninstall Microsoft.EdgeWebView2Runtime && winget install Microsoft.EdgeWebView2Runtime`

**Comment by henrypp** [comment] 2024-01-05 21:54
@Trenly u complete dont understant where problem here_

**Comment by denelon** [comment] 2024-01-05 22:14
@henrypp I'm not sure I understand the Issue or question you're asking. 

From the screenshot it looks like you're trying to install WebView2 using WInGet. WinGet was able to determine a version of WebView2 was already installed on your system, so it switched the intent from "install" to "upgrade" as a convenience.

Unfortunately, as @Trenly pointed out, the preInstalled version of WebView2 can't be upgraded in user context due to permissions. His suggestion should work to remove the preInstalled version and then use WinGet to install the latest version so it can be kept up to date by WinGet from that point forward.

The next command executed was `winget upgrade` which essentially is asking WinGet to show which installed packages have updates available. If the intent was to have WinGet actually perform upgrades, the "--all" argument should be added so the command would be `winget upgrade --all`.
>Note: This would fail for WebView2 due to the reasons stated above.

**Comment by henrypp** [comment] 2024-01-05 22:25
@denelon the complete issue (bug) can be reported in several words: winget displays it found update, but it is not displaying complete name for "winget install".

i think displaying result as a table is not good, because all columns did not displays *complete* names (it stripped by "..."), so i think tables is bullshit for consoles and needed rows or whatever.

as example:
found update:
1)
prog name
prog.name.id
whatever needs displaying, or comments etc.

**Comment by denelon** [comment] 2024-01-05 23:23
OK, thanks for the clarification.

Related to:
* #1653
* #2161
* #2603
* #3071

Duplicate of #1653

**Closed** 2024-01-05 23:23 UTC
Labels: Issue-Feature
