### ISSUE TITLE
Installing an app a second time should skip if already installed

### ISSUE THREAD

**Issue by lythix** [microsoft/winget-cli#272] opened 2020-05-21 13:18 UTC
Issuing an install command for a package should not download and install a package if that version is already installed. 
Some fallback behaviour could be to do a repair, or upgrade. 
If the same version (or the latest version) is installed, there is no reason to re-download and install the app.

**Comment by megamorf** [comment] 2020-05-22 19:33
This is a duplicate of #216.

**Comment by denelon** [comment] 2020-05-28 19:39
Duplicate of #216, and thanks @megamorf

**Closed by denelon** 2020-05-28 19:39 UTC
Labels: Issue-Feature
