### ISSUE TITLE
Winget stuck at Extracting archive... when install zig compiler

### ISSUE THREAD

**Issue by huyhoang160593** [microsoft/winget-cli#3306] opened 2023-06-03 16:50 UTC
### Brief description of your issue

The installer never finish their setup, and the setup alway stuck at Extracting archive... when tried to install

### Steps to reproduce

1. `winget install zig.zig` 
2. wait for eternity

### Expected behavior

the package is installed successfully

### Actual behavior

the installed is stopping for a really long time

### Environment

```shell
Windows Package Manager v1.4.11071
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1778
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.11071.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by denelon** [comment] 2023-06-05 21:24
There are more than 15,000 files in this compressed file. Even when extracting the downloaded file (native Windows extraction support), it takes several minutes for the extraction to complete.
<img width="441" alt="zig zig" src="https://github.com/microsoft/winget-cli/assets/61799811/7dae59d4-e22b-493b-8b1e-7ae75edda657">

**Comment by denelon** [comment] 2023-06-05 21:26
Does the install eventually complete for you or does it fail?

I'm running the install now on my local machine to see if it completes.

**Comment by denelon** [comment] 2023-06-05 22:04
I created the issue to improve the output to help in this scenario.

Since the install succeeded, I'm going to close this issue. Be sure to add your 👍to the other one to help raise its priority.

**Closed by denelon** 2023-06-05 22:04 UTC
Labels: Issue-Bug, Needs-Author-Feedback

**Comment by won3d** [comment] 2023-12-23 02:01
I just ran into this while trying to install for the first time. I had a hunch that it was being limited somehow by Microsoft Defender, so I temporarily disabled it, after which it completely instantly. Not really an ideal workaround, but hopefully useful to someone.

**Comment by zveinn** [comment] 2024-09-26 12:16
just wanted to bump this. Experienced the same slowness on up to date Win11 using Powershell

**Comment by leostera** [comment] 2024-11-15 20:28
Just got the same issue here, it'd be phenomenal to include any form of feedback (even if its just an increasing number for files extracted), so I can at least know this isn't stuck.

**Comment by HowellBP** [comment] 2024-12-30 06:42
> There are more than 15,000 files in this compressed file. Even when extracting the downloaded file (native Windows extraction support), it takes several minutes for the extraction to complete. 

How is Scoop able to extract it in ~30 seconds? Using `scoop install zig` takes about 45 seconds total including fetching the archive over my connection. Is Scoop using a different extraction tool?

**Comment by shishini** [comment] 2025-02-09 01:58
same issue, very suspicious

**Comment by aidan729** [comment] 2025-02-19 23:37
> > There are more than 15,000 files in this compressed file. Even when extracting the downloaded file (native Windows extraction support), it takes several minutes for the extraction to complete.
> 
> How is Scoop able to extract it in ~30 seconds? Using `scoop install zig` takes about 45 seconds total including fetching the archive over my connection. Is Scoop using a different extraction tool?

Because Microsoft lol

**Comment by jmonroynieto** [comment] 2025-03-15 13:28
I normally use linux and had to reluctantly switch to windows for a week. I thought it was highly irregular and when I googled the issue without mentioning zig, this issue is at the top. Lots of us are being thrown for a loop. I agree with the added feedback solution.

**Comment by TeamDman** [comment] 2026-04-04 18:17
<img width="1141" height="342" alt="Image" src="https://github.com/user-attachments/assets/bfa98dad-dd9a-45cd-a2fb-034bf7506f85" />
25 minutes here, not cool :(

**Comment by MixusMinimax** [comment] 2026-06-30 21:25
7zip is orders of magnitude faster than windows's internal extraction. It would be cool if the winget script would detect a 7zip installation and use it instead. in my case, 7zip took 10 seconds to extract the entire file.

This helped though: https://gist.github.com/ardislu/16e44f6a49f8ec0f313b0b849c61580c

it can use tar. On windows. The entire process took 7 seconds.

**Comment by Areha11Fz** [comment] 2026-08-19 20:24
> 7zip is orders of magnitude faster than windows's internal extraction. It would be cool if the winget script would detect a 7zip installation and use it instead. in my case, 7zip took 10 seconds to extract the entire file.
> 
> This helped though: https://gist.github.com/ardislu/16e44f6a49f8ec0f313b0b849c61580c
> 
> it can use tar. On windows. The entire process took 7 seconds.

confirmed works, only took few seconds 👍
