### ISSUE TITLE
HTTP/SOCKS5 proxy support

### ISSUE THREAD

**Issue by yystju** [microsoft/winget-cli#432] opened 2020-06-16 04:33 UTC
# Description of the new feature/enhancement
For now, I am trying to use winget inside China mainland, as the well-known reason, I found I cannot make a simple `winget install graphviz` work... It might be OK after this tool formally released with local repositories installed in China. But I think there will be many windows users who need to use winget behind an enterprise firewall or something like that. So my private guess is: winget need to have a feature to support HTTP(s)/SOCKS5 proxies.
 

# Proposed technical implementation details (optional)
It can be designed to use an extra command line parameter, or to follow the UNIX tools routines of environment variables (like http_proxy, https_proxy, ALL_PROXY, etc.)

**Comment by yystju** [comment] 2020-06-16 04:49
Oh... another proposal is:
Can we have configuration file to configure mirrors or customized repositories?
I am not sure how much Microsoft want to handle the tool and the repository. If the policy is OK for customized repositories, I think a configuration file (like `.gitconfig`, etc.) might be a good thing. If not, I strongly recommend to deploy more repository servers in China...

**Comment by megamorf** [comment] 2020-06-16 13:12
Hey @yystju, thanks for taking the time to report this. Both features have been requested already and could've been found by searching the issues first before creating your own.

For proxy support subscribe to:
* #190

For mirror support subscribe to:
* #316

**Comment by denelon** [comment] 2020-06-17 19:19
Duplicate of #190

**Closed by denelon** 2020-06-17 19:19 UTC
Labels: Issue-Feature, Needs-Triage
