### ISSUE TITLE
x86 & x64 versions of the same software might cause a conflict

### ISSUE THREAD

**Issue by Nivyan** [microsoft/winget-cli#3531] opened 2023-08-17 12:56 UTC
### Brief description of your issue

As an example, if both x86 and x64 libraries of Microsoft .NET or Visual C++ are installed, the versions conflict.

### Steps to reproduce

1. Uninstall both versions.
2. Install either version - observe WinGet reports the correct version.
3. Install the other version - observe WinGet reports an incorrect version.
4. Run winget upgrade --all - observe WinGet downloading and updating the packages, despite them being there already.

**Exceptions:** Depending on the order of installation and method, it might not recognise an update to begin with, but this means that it doesn't consider one version of the package. Additionally, if one manually installs packages in some orders, WinGet will recognise the packages - but still the wrong versions. I haven't found a correlation between which version to install in which order.

### Expected behavior

Expected WinGet to differentiate between the packages.

### Actual behavior

Versions conflict with each other.

### Environment

```shell
Windows Package Manager v1.5.2201
Windows: Windows.Desktop v10.0.19045.3324
Package: Microsoft.DesktopAppInstaller v1.20.2201.0

Packages that's causing the errors:
Microsoft Visual C++ 2015-2022 Redistributable (x64) [Microsoft.VCRedist.2015+.x64]
Microsoft .NET SDK 7.0 [Microsoft.DotNet.SDK.7]
(And their x86 versions)
```

**Comment by Trenly** [comment] 2023-08-17 14:51
This is a known issue with how winget matches Control Panel entries to available packages. The issues tagged with the https://github.com/microsoft/winget-cli/labels/Area-Matching label have a lot of great information about what exactly causes this. At a high level, winget tries to normalize package names by dropping the architecture and the version when trying to match by name, which causes issues when the packages can be installed side by side.

* Duplicate of #2893
* Related to #2129

**Closed** 2023-08-17 14:51 UTC
Labels: Needs-Triage
