### ISSUE TITLE
Exclude app with argument on cmdline

### ISSUE THREAD

**Issue by yonix06** [microsoft/winget-cli#3792] opened 2023-10-19 14:07 UTC
### Description of the new feature / enhancement

Hi, i would like to propose this idea if it has not been proposed yet.

i would like to ba able to exclude certain packet from being updated when i run the following command: winget upgrade --all

The goal is to being able to update all softwares on a machine remotely via winget by running a bat file, and having some critical software being untouched

Regards,
Yo

### Proposed technical implementation details

Maybe with another parameter, like --exclude <Name.of.packet>

**Comment by mdanish-kh** [comment] 2023-10-19 14:10
This can be achieved using [winget pin](https://learn.microsoft.com/en-us/windows/package-manager/winget/pinning) command.

Duplicate of #476

**Closed** 2023-10-19 14:10 UTC
Labels: Issue-Feature, Needs-Triage
