### ISSUE TITLE
Add "Collection" option to group certain packages

### ISSUE THREAD

**Issue by vasilvestre** [microsoft/winget-cli#686] opened 2020-05-23 23:24 UTC
# Description of the new feature/enhancement

I was navigating on "https://winstall.app/" and they have a great multi-choice UI to easily generate a script that installs all you want in "somewhat" once.
I think that Collections should be an existing thing because it's sometimes needed and should be too much. Even public and private list could exist. Eg : "php-dev-packages" contain php-latest php-opcache php-mbstring etc"

# Proposed technical implementation details (optional)

Manifest could now contain of optionable field to create packages. Or maybe another winget-collection that directly use packages from here by default but also using another package via sources

`winget source list
Name   Arg
-----------------------------------------
winget https://winget.azureedge.net/cache`

**Comment by denelon** [comment] 2021-02-04 00:20
Duplicate of #220

**Closed by denelon** 2021-02-04 00:20 UTC
Labels: Issue-Feature
