### ISSUE TITLE
Problem when installing packages und windows user name contains spaces

### ISSUE THREAD

**Issue by PhilippPaetzold** [microsoft/winget-cli#4171] opened 2024-02-15 09:07 UTC
### Brief description of your issue

On my machine my user-name contains spaces and special characters. When installing tools, e.g. `winget install --id junegunn.fzf` they are installed without any complains under ```C:\Users\Costa Möbius\AppData\Local\Microsoft\WinGet\Links\fzf.exe```

Running the tool then results in the following error:
```
>fzf
ResourceUnavailable: Program 'fzf.exe' failed to run: An error occurred trying to start process 'C:\Users\Costa Möbius\AppData\Local\Microsoft\WinGet\Links\fzf.exe' with working directory 'C:\Users\Costa Möbius\Documents\PowerShell'. Der angegebenen Datei ist keine Anwendung zugeordnet.At line:1 char:1
+ fzf
```

Uninstalling the tool with:
```winget uninstall --id junegunn.fzf``` then also fails:

```
>winget uninstall --id junegunn.fzf
Gefunden fzf [junegunn.fzf]
Paket-Deinstallation wird gestartet...
Unerwarteter Fehler beim Ausführen des Befehls:
0x80070490 : Element nicht gefunden.
Deinstallation fehlgeschlagen mit Exitcode: 0x80070490 : Element nicht gefunden.
```
Is there a workaround and how can I uninstall the tool? 

Thank you for your support!

### Steps to reproduce

* Username contains spaces and special characters, e.g. `Costa Möbius` with the userprofile at `C:\Users\Costa Möbius`
* ```winget install --id junegunn.fzf``` installs without issues

### Expected behavior

Calling the tool via `fzf` and uninstalling it again with `winget uninstall --id junegunn.fzf` should work properly.

### Actual behavior

Running does not work:

```
>fzf
ResourceUnavailable: Program 'fzf.exe' failed to run: An error occurred trying to start process 'C:\Users\Costa Möbius\AppData\Local\Microsoft\WinGet\Links\fzf.exe' with working directory 'C:\Users\Costa Möbius\Documents\PowerShell'. Der angegebenen Datei ist keine Anwendung zugeordnet.At line:1 char:1
+ fzf
+ ~~~.
```

nor does uninstalling:

```
>winget uninstall --id junegunn.fzf
Gefunden fzf [junegunn.fzf]
Paket-Deinstallation wird gestartet...
Unerwarteter Fehler beim Ausführen des Befehls:
0x80070490 : Element nicht gefunden.
Deinstallation fehlgeschlagen mit Exitcode: 0x80070490 : Element nicht gefunden.
```

### Environment

```shell
>winget --info
Windows-Paket-Manager v1.6.3482
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.22631.3085
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.21.3482.0

WinGet-Verzeichnisse
-------------------------------------------------------------------------------------------------------------------------------
Protokolle                                   %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Di…
Benutzereinstellungen                        %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\se…
Verzeichnis für portierbare Links (Benutzer) %LOCALAPPDATA%\Microsoft\WinGet\Links
Portables Linkverzeichnis (Computer)         C:\Program Files\WinGet\Links
Portierbarer Paketstamm (Benutzer)           %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portierbarer Paketstamm                      C:\Program Files\WinGet\Packages
Portierbares Paketstamm (x86)                C:\Program Files (x86)\WinGet\Packages
Installationsprogrammdownloads               %USERPROFILE%\Downloads

Links
-----------------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store-Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale

Administratoreinstellung                  Status
-----------------------------------------------------
LocalManifestFiles                        Deaktiviert
BypassCertificatePinningForMicrosoftStore Deaktiviert
InstallerHashOverride                     Deaktiviert
LocalArchiveMalwareScanOverride           Deaktiviert
```

**Comment by Trenly** [comment] 2024-02-15 14:07
Duplicate of https://github.com/microsoft/winget-cli/issues/3312

**Closed** 2024-02-15 14:07 UTC
