### ISSUE TITLE
Installer type 'msi-in-zip'

### ISSUE THREAD

**Issue by rhuijben** [microsoft/winget-cli#2149] opened 2022-05-10 06:01 UTC
### Description of the new feature / enhancement

While it is quite a huge feature request to completely support zip #140 as installer, there are quite a few projects that deliver their existing 'msi installers in a zip file.

One good reason for this, is that .msi files that are not signed create huge warnings when directly installed from Chome/Edge browsers.

This would immediately support a few quite popular packages like Paint.Net without the huge implementation requirements of #140.

### Proposed technical implementation details

The tools to detect the installer type could just check if the file is a zipfile containing just a single '.msi' file.

At a later point there could be some more advanced filters to some other files like a readme or changelog in the same zip file. But for the first version I would recommend a very simple version.

This issue avoids the pitfalls from #140, as the zip can just be extracted to temporary storage and deleted after the install.

**Comment by Trenly** [comment] 2022-05-10 12:30
This is already going to be part of the implementation for Zip, and will be considered as part of #140

There are a few main use cases which will be considered
* Zip file with single installer - This is the exact situation you described, except that winget will not only support MSI but also EXE files
* Zip file with binary - This is the case where a zip file contains a portable app. Portable apps are not supported by the client yet, but the work is in the preview build to be able to install standalone binaries

Take a look at #1242 for how the proposal for Zip may look

**Comment by denelon** [comment] 2022-05-10 19:57
@rhuijben the comments made by @Trenly are correct. The scope of .zip is likely to expand, but our initial implementation will be a .zip file containing one of our currently supported existing installer types.

Duplicate of #140

**Closed by denelon** 2022-05-10 19:57 UTC
Labels: Issue-Feature
