### ISSUE TITLE
Winget does not allow both x64 and x86 versions of a package to be installed

### ISSUE THREAD

**Issue by butterbutts** [microsoft/winget-cli#3010] opened 2023-02-25 22:25 UTC
### Brief description of your issue

Trying to install any of the Visual C++ Redistributables or .Net Redistributables for both x86 and x64 results in winget claiming the package is already installed and cannot be upgraded.
For example, installing the .Net 7 Desktop x64 package and then trying to install the x86 package results in the same error as if you were trying to install the exact same package again. The same thing happens installing x86 first and x64 second, you can only install whichever one comes first.
Using --force allows the install to proceed as expected.

### Steps to reproduce

winget install Microsoft.VCRedist.2015+.x64
Success
winget install Microsoft.VCRedist.2015+.x86
Found an existing package already installed. Trying to upgrade the installed package...
No applicable upgrade found.

### Expected behavior

Winget should install the specified package.

### Actual behavior

Winget believes the package is already installed, even though it is not.

### Environment

```shell
Windows Package Manager v1.4.10173
Windows: Windows.Desktop v10.0.22621.1265
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0
```

**Comment by Trenly** [comment] 2023-02-26 00:48
Duplicate of https://github.com/microsoft/winget-pkgs/issues/97053
Related to #2995 

As a workaround, use `--force` to install the package

**Closed** 2023-02-27 15:13 UTC
