### ISSUE TITLE
interpret special characters in the filesystem, such as "ß", "ä"

### ISSUE THREAD

**Issue by SimHeb** [microsoft/winget-cli#457] opened 2020-06-24 14:04 UTC
# Brief description of your issue

When I try to install any package, winget will use the %AppData% folder which is under the user profile folder. Since I have special characters in that file name, winget can download, but after that not find the downloaded file to install:

![screenshot](https://user-images.githubusercontent.com/49982961/85571204-41664f00-b634-11ea-8461-ebb02d5c16da.png)

# Steps to reproduce

Profile Name with special characters, ß, ä, ...
run winget install vscode-insiders
run winget install ccleaner 
...

# Expected behavior

Should install the given package

# Actual behavior

The error message is: Installer failed with exit code: 1223

# Environment

```none
winget --version
v0.1.41331 Vorschau

```

**Comment by megamorf** [comment] 2020-06-25 06:41
Duplicate of #181

**Comment by denelon** [comment] 2020-06-25 19:02
Duplicate of #181

**Closed by denelon** 2020-06-25 19:03 UTC
Labels: Needs-Triage
