### ISSUE TITLE
Can I get the downloaded package file?

### ISSUE THREAD

**Issue by inkuaxjieng** [microsoft/winget-cli#2821] opened 2023-01-06 01:03 UTC
### Description of the new feature / enhancement

In some places where the network is not good, offline installation is very important. I don't know if the installation package can be kept instead of deleted after installation.

**Comment by denelon** [comment] 2023-01-06 02:49
We're looking at a `winget download` feature to just download packages.

As a workaround, you can use `winget show <packageID.` and download from the URL.

**Comment by denelon** [comment] 2023-02-09 20:06
Duplicate of #658

**Closed by denelon** 2023-02-09 20:06 UTC
Labels: Issue-Feature
