### ISSUE TITLE
1 updates available for a beta version app using the stable version

### ISSUE THREAD

**Issue by maisondasilva** [microsoft/winget-cli#3574] opened 2023-08-31 18:57 UTC
### Brief description of your issue

I have installed Mozilla.Thunderbird 115.2.0 using command winget upgrade show update for version Beta

![image](https://github.com/microsoft/winget-cli/assets/11423362/c5070dcd-4c9c-485a-82d3-30e8118c2eec)

### Steps to reproduce

I have installed Mozilla.Thunderbird 115.2.0 using command winget upgrade show update for version Beta

![image](https://github.com/microsoft/winget-cli/assets/11423362/925ebbc5-fb46-4509-801c-d519d42c1130)

### Expected behavior

Not show update for version Beta

### Actual behavior

Show update for version Beta

### Environment

```shell
PS C:\Users\Maison> winget --info
Windows Package Manager v1.5.2201
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.25941.1000
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.2201.0

Winget Directories
-------------------------------------------------- -------------------------------------------------- ---------------------------
Logs %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User) %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User) %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root C:\Program Files\WinGet\Packages
Portable Package Root (x86) C:\Program Files (x86)\WinGet\Packages

Links
-------------------------------------------------- -----------------------------
Privacy Policy https://aka.ms/winget-privacy
License Agreement https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Home page https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

State Administrator Configuration
-------------------------------------------------- ----
LocalManifestFiles Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride Disabled
LocalArchiveMalwareScanOverride Disabled
PS C:\Users\Maison>
```

**Comment by Trenly** [comment] 2023-08-31 23:10
Duplicate of microsoft/winget-pkgs#117949;

**Closed** 2023-09-01 19:02 UTC
Labels: Needs-Triage
