### ISSUE TITLE
Winget upgrade --all should assume --accept-source-agreements --accept-package-agreements

### ISSUE THREAD

**Issue by rbarbrow** [microsoft/winget-cli#4753] opened 2024-08-25 01:32 UTC
### Description of the new feature / enhancement

To put it as briefly as possible, going from a 3-letter command to a 50-letter command is not intuitive/easy / or helpful with user adoption.

### Proposed technical implementation details

-all should assume agreements and we should have to call out agreements we don't wish to agree to

**Comment by Trenly** [comment] 2024-08-25 13:22
Whlie I agree that there should be some way to set a persistent agreement, I don’t think that this would be the right way to approach it.

If I'm not mistaken, those switches are there for legal purposes - as if a package or source required explicit agreement and it was agreed to automatically, it would cause many potential issues in the area of contract law.

**Comment by rbarbrow** [comment] 2024-08-25 15:53
I think it could be handled with something like --all --y   where y is yes for agreements but it absolutely will do damage to this product if I have to explain to my grandma over the phone that she has to type --accept-source-agreements over the phoen

**Comment by stephengillie** [comment] 2024-08-26 16:44
Could this be set in `settings.json`? Something like:
```
AcceptPackageAgreements:1
AcceptSourceAgreements:1
```

Maybe even:
```
MakeUpgradeAllAcceptAgreements:1
```

**Comment by rbarbrow** [comment] 2024-08-26 17:14
I was thinking something like that but it just adds complexity for scripting



Robert BarbrowHe/Him
Sr. Director of IT
P: 703.213.5224
M: 703.626.9129
markonsolutions.com  |
Connect with me on LinkedIn >>
________________________________

**Comment by Trenly** [comment] 2024-08-27 19:57
@denelon  I was looking through the issues, and this seems to be the same as -
* #2404
* #4336 
* https://github.com/microsoft/winget-cli/discussions/1536#discussioncomment-8966973

**Comment by denelon** [comment] 2024-08-28 01:14
Duplicate of #2404

**Closed** 2024-08-28 01:14 UTC
Labels: Issue-Feature, Area-User-Interface
