### ISSUE TITLE
Package installation fails if there is a non-ASCII character on the username

### ISSUE THREAD

**Issue by CHOSTeam** [microsoft/winget-cli#448] opened 2020-06-20 14:23 UTC
# Brief description of your issue

Package installation fails if there is a non-ASCII character on the username

# Steps to reproduce

Create a local user with non-ASCII characters in the name, and try to install .NET Core Preview.

# Expected behavior

The program is successfully installed.

# Actual behavior

Installer failed with exit code: 1223

```none
Windows cannot find
'C:\Users\Ãtalo\AppData\Local\P...\Microsoft.dotnetPreview.5.0.100-preview.5.20279.10.exe'.
Make sure you typed the name correctly, and then try again.
```

# Environment

```none
[winget --info]
Windows Package Manager v0.1.41331 Preview
Windows: Windows.Desktop v10.0.20150.1000
Package: Microsoft.DesktopAppInstaller v1.0.41331.0
```

**Comment by megamorf** [comment] 2020-06-20 16:49
Duplicate of #181

**Comment by denelon** [comment] 2020-06-22 16:32
Duplicate of #181

**Closed by denelon** 2020-06-22 16:32 UTC
Labels: Needs-Triage
