### ISSUE TITLE
A bug with upgrading Softwares 

### ISSUE THREAD

**Issue by ChesanduC** [microsoft/winget-cli#1550] opened 2021-10-05 13:47 UTC
# Brief description of your issue
I upgraded python 3.9 to latest 3.10 using Winget. It didn't removed the older version. It just downloaded python 3.10 and now I have to versions.
# Steps to reproduce

winget upgrade "Python 3"

# Expected behavior

I expected to older python version to be removed while installing the new version

# Actual behavior

I ended up getting two python versions in my computer and I can't remove the documentations and others of the old version.

# Environment

Windows: Windows.Desktop v10.0.19043.1237

**Comment by jedieaston** [comment] 2021-10-05 15:39
This is intentional behavior on the part of the Python installer, which assumes that you want to keep minor versions.

**Comment by leochras** [comment] 2021-10-05 16:41
There has to be something wrong though. I can't upgrade unless I run `upgrade --all ` and even then it detects the old version and keeps updating.
![image](https://user-images.githubusercontent.com/16163571/136065917-4c0e9821-5fd6-48f7-bb33-9aa6ecb69846.png)

**Comment by jedieaston** [comment] 2021-10-05 16:51
Oh, that's being tracked in #752.

**Comment by leochras** [comment] 2021-10-05 16:55
Also here: https://github.com/microsoft/winget-pkgs/issues/16070

**Comment by denelon** [comment] 2021-10-05 21:06
Duplicate of #752

**Closed by denelon** 2021-10-05 21:06 UTC
Labels: Needs-Triage
