### ISSUE TITLE
'Winget' command does not work

### ISSUE THREAD

**Issue by djhalnon** [microsoft/winget-cli#995] opened 2021-05-26 23:42 UTC
I've installed the App Installer package from the Microsoft Store, however, curiously, I can't run winget. When I do, I get: "'winget' is not recognized as an internal or external command, operable program or batch file." 

Now, I've seen a lot of stuff about paths. Also curiously, though, "%USERPROFILE%\AppData\Local\Microsoft\WindowsApps" is already in my PATH. 

And also curiously, I've searched the entire drive for any file beginning with "winget", and came up with nothing whatsoever. 

I have a feeling this thing never installed, even though it says it did and even though it shows in the Store app as "This product is installed." 

Any solution? Or is this true "beta-ware" that really sometimes just doesn't work, and I should just forget about it?

**Comment by denelon** [comment] 2021-05-27 01:12
@djhalnon If you are not on a Windows Insider build or part of the Windows Package Manager Insider group, it is likely you received the version of the App Installer that does not include the winget client.

https://github.com/microsoft/winget-cli#installing-the-client

You can download and double-click the [installer](https://github.com/microsoft/winget-cli/releases/download/v1.0.11451/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle) from the https://github.com/microsoft/winget-cli/releases page.

Any newer version of the App Installer published to the store will automatically be updated on your system (assuming no Group Policy is blocking the store).

**Comment by arnitdo** [comment] 2021-05-27 03:01
Facing a similar problem here. Installed it from the releases page. Searching the C:\ Drive for 'winget' returns no search results apart from Microsoft Store Search cache files. No application exists in WindowsApps\ as well.

Out of curiosity, what does the AppInstallerCLI.exe executable do? Is that supposed to be winget?

**Comment by mnpenner** [comment] 2021-05-27 03:56
FWIW, I didn't get `winget` either when I went to [the store page](https://www.microsoft.com/en-us/p/app-installer/9nblggh4nns1). Said I already had App Installer. But the [directly install](ms-appinstaller:?source=https://aka.ms/getwinget) link from the blog post seemed to force an update, and now I have it.

**Comment by JoeLyga** [comment] 2021-05-27 19:55
Facing the same issue.  Running winget produces no output in powershell.

**Comment by denelon** [comment] 2021-05-27 20:33
@JoeLyga are you a Windows Package Manager Insider or running a Windows Insider build?
How did you install the "App Installer"?

**Comment by xxxolllllllll** [comment] 2021-05-31 00:58
为啥不直接从github下载最新版本

**Comment by billriess** [comment] 2021-06-01 17:01
I'm also having the no output issue.

**Comment by impossiblynew** [comment] 2021-06-01 20:41
This seems to be the same issue as #502

**Comment by denelon** [comment] 2021-06-01 22:23
The Windows Package Manager is distributed with the "App Installer". Make sure you have the correct version that includes the Windows Package Manager. In PowerShell:

```
PS C:\Users\denelon> Get-AppxPackage microsoft.DesktopAppInstaller


Name              : Microsoft.DesktopAppInstaller
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 1.11.11451.0
PackageFullName   : Microsoft.DesktopAppInstaller_1.11.11451.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.11.11451.0_x64__8wekyb3d8bbwe
IsFramework       : False
PackageFamilyName : Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
Dependencies      : {Microsoft.VCLibs.140.00.UWPDesktop_14.0.29231.0_x64__8wekyb3d8bbwe,
                    Microsoft.DesktopAppInstaller_1.11.11451.0_neutral_split.scale-100_8wekyb3d8bbwe}
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok
```

Check to see that the version is greater than 1.11

If you do have the current version of the AppInstaller, the other areas to check are App Execution Alias settings as well as other troubleshooting steps in #502

**Comment by billriess** [comment] 2021-06-02 01:04
I can confirm that the App Execution Alias is enabled and the `Get-AppxPackage microsoft.DesktopAppInstaller` gives the following results:

```
Name              : Microsoft.DesktopAppInstaller
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 1.11.11451.0
PackageFullName   : Microsoft.DesktopAppInstaller_1.11.11451.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.11.11451.0_x64__8wekyb3d8bbwe
IsFramework       : False
PackageFamilyName : Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
Dependencies      : {Microsoft.VCLibs.140.00.UWPDesktop_14.0.29231.0_x64__8wekyb3d8bbwe,
                    Microsoft.DesktopAppInstaller_1.11.11451.0_neutral_split.scale-125_8wekyb3d8bbwe,
                    Microsoft.DesktopAppInstaller_1.11.11451.0_neutral_split.scale-100_8wekyb3d8bbwe,
                    Microsoft.DesktopAppInstaller_1.11.11451.0_neutral_split.scale-400_8wekyb3d8bbwe}
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok
```

Running `winget` just gives no output. Curiously, the winget.exe is 0 bytes in the WindowsApps folder.

**Comment by billriess** [comment] 2021-06-02 01:29
I was able to fix this by updating my Environment Variables. Adding the full path `C:\Users\%USERPROFILE%\AppData\Local\Microsoft\WindowsApps` seems to resolve the no output issue despite `%USERPROFILE%\AppData\Local\Microsoft\WindowsApps` already existing.

For anyone having no output try adding `C:\Users\%USERPROFILE%\AppData\Local\Microsoft\WindowsApps` to your `Path` Environment Variable.

**Comment by billriess** [comment] 2021-06-02 01:32
Curiously, I noticed that running the `winget` command in a terminal immediately after logging in seems to work. There is likely some interference with another application causing no output. Windows Terminal is installed as is WSL2 with Debian.

**Comment by denelon** [comment] 2021-06-02 02:03
The zero byte file is expected. The App Execution Alias maps winget.exe to the true executable. It acts similar to a symlink in *nix. I haven't seen other reports of interactions with WSL2 or any of the other specific distributions, but I'll keep that in mind as others report similar issues.

**Comment by impossiblynew** [comment] 2021-06-02 02:13
> 
> 
> I noticed that running the `winget` command in a terminal immediately after logging in seems to work. There is likely some interference with another application causing no output. Windows Terminal is installed as is WSL2 with Debian.

Just wanted to say that the same thing happened with me -- winget suddenly started working without me restarting or making any changes in the middle of a PowerShell session, and that I also have Windows Terminal and WSL2.

**Comment by A9G-Data-Droid** [comment] 2021-06-09 15:50
I'm having this same issue. When I look at my App Execution Alias folder (\AppData\Local\Microsoft\WindowsApps) I see the alias pointing here:
```
la---           3/29/2021  8:23 AM              0 winget.exe -> C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.11.2521.0_x64__8wekyb3d8bbwe\AppInstallerCLI.exe
```
If I try to manually run the target of that alias I get:

```
The term 'C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.11.2521.0_x64__8wekyb3d8bbwe\AppInstallerCLI.exe' is not recognized as a name of a cmdlet, function, script file, or executable program.
```

If I try to manually browse to that location and try to run the exe I get an access denied error like this:

```
PS C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.11.11451.0_x64__8wekyb3d8bbwe> .\AppInstaller.exe
ResourceUnavailable: Program 'AppInstaller.exe' failed to run: Access is denied.At line:1 char:1
+ .\AppInstaller.exe
+ ~~~~~~~~~~~~~~~~~~.
```

This is odd because I am running an elevated Administrator PowerShell session when I get the access denied error. I think this might be the root cause for me.

**Comment by arnitdo** [comment] 2021-06-09 15:52
Update : The `winget` command now works, and the executable is located in C:\Windows\System32\. However, upon executing it, I get the following error
```
ResourceUnavailable: Program 'winget.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1 char:1
+ winget
+ ~~~~~~.
```

**Comment by A9G-Data-Droid** [comment] 2021-06-16 16:05
You're stale @msftbot, we need developer action, not bot auto-closing. If a human wants to close the issue they will. Maybe you should be auto-closed.

**Comment by arnitdo** [comment] 2021-06-16 16:18
I think this issue should be permanently kept open until a strong fix is found. It would be great if the bot could have this issue excluded

**Comment by robinhood2014** [comment] 2021-06-16 16:20
To anyone having this issue: You don't have a system utility program like Glary installed, do you? I think if something like Glary is run, it can wreak havoc on critical files and settings needed by winget, thereby damaging winget to the point where there's nothing that can be done about it except initiate a "Reset this PC" operation from Settings > Update & security > Recovery.

**Comment by A9G-Data-Droid** [comment] 2021-06-16 16:25
@robinhood2014 No, I've never heard of Glary. The problem is common for anyone who is logged in to a regular user account and needs to run PowerShell using a separate admin account. This is true of any corporate environment that is following any basic security framework. Microsoft itself should be running this way so I would be surprised if they haven't run in to it internally.

**Comment by robinhood2014** [comment] 2021-06-16 16:29
@A9G-Data-Droid Well, I'm not in a corporate environment but I can say with certainty that it's good practice to have your own user account as a standard user, and have a separate administrator account; that way if a hacker tries to introduce malware into your system, he (or she!) will be discouraged by a UAC prompt requiring an administrator's password. Also, to everyone: Please don't rag on the @msftbot. Instead, let's consider removing the "Needs-Author-Feedback" flag.

**Comment by denelon** [comment] 2021-06-16 16:57
@A9G-Data-Droid there are many reasons users may encounter problems executing `winget`. Generally this falls into a few areas. 

1) The APP Installer on the host machine doesn't include the Windows Package Manager.
2) The App Installer isn't registered for the user (account) attempting to execute `winget`.
3) App Execution Alias isn't enabled for the Windows Package Manager.
4) Something is corrupt or has been modified related to the App Installer (or associated files / path)

When we can clearly isolate the issues and find consistent mechanisms to reproduce them, we work on fixing them, and/or we work on adding documentation. The original author of the issue hasn't responded to this issue to help clarify what they are experiencing and responding to questions.

The bot looks for the "Needs-Author-Feedback" label, and whether the author or another user from the community has responded to the issue. If no activity has happened after 7 days, the issue is labeled "No-Recent-Activity". If there is no activity 7 days after that, then the bot will automatically close the Issue.

This issue has a very broad scope. There isn't likely to be any single solution. With issues like this, we try to break them down into bite sized pieces we can tackle. Many other users with the same "`winget` command does not work" issues have been resolved, and may contain answers for an individual scenario. We try to keep actionable issues open until we can fix them. 

Much of the content on this issue is more of a "discussion". We don't close discussions. 

With this issue, I would try to help the original author as we work towards better answers / guidance. In many cases I get notifications when users comment on closed issues. We are very active here. I try to respond to any questions, or something actionable. Unfortunately, this issue is just too broad in scope to find a single solution. 

My hope with this response is the list of currently known problem spaces will help others find something that resolves their particular issue.

**Comment by aminya** [comment] 2021-08-11 07:31
When I run this command, I get this error:
```
❯ Get-AppxPackage microsoft.DesktopAppInstaller
Get-AppxPackage: The 'Get-AppxPackage' command was found in the module 'Appx', but the module could not be loaded. For more information, run 'Import-Module Appx'.
```

**Comment by aminya** [comment] 2021-08-18 13:12
> @djhalnon this issue has been automatically marked as stale because it has been marked as requiring author feedback but has not had any activity for **7 days**. It will be closed if no further activity occurs **within 7 days of this comment**.

This is not fixed yet.

**Comment by denelon** [comment] 2021-08-18 15:34
@aminya, what version of the App Installer do you have on your machine? Many of the challenges we see with the Windows Package Manager not running are either a version of the App Installer without the Windows Package Manager being installed, or they are related to the user accounts attempting to run `winget`.

**Comment by aminya** [comment] 2021-08-18 15:45
How can I check the version? I am on Windows 11, so I assume everything should be up to date.

**Comment by denelon** [comment] 2021-08-18 15:50
@aminya you can run 
```PowerShell
Get-AppxPackage microsoft.DesktopAppInstaller
```
in PowerShell.

**Comment by billriess** [comment] 2021-08-18 16:03
You can get this error if you have Discord installed. Other applications may cause conflicts as well but I can confirm Discord was an issue for me.

**Comment by aminya** [comment] 2021-08-18 16:36
Here is the result of the command:
```
❯ import-module appx -usewindowspowershell
WARNING: Module appx is loaded in Windows PowerShell using WinPSCompatSession remoting session; please note that all input and output of commands from this module will be deserialized objects. If you want to load this module into PowerShell please use 'Import-Module -SkipEditionCheck' syntax.

❯ Get-AppxPackage microsoft.DesktopAppInstaller

RunspaceId             : *******
Name                   : Microsoft.DesktopAppInstaller
Publisher              : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
PublisherId            : *******
Architecture           : X64
ResourceId             :
Version                : 1.15.11694.0
PackageFamilyName      : Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
PackageFullName        : Microsoft.DesktopAppInstaller_1.15.11694.0_x64__8wekyb3d8bbwe
InstallLocation        : C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.15.11694.0_x64__8wekyb3d8bbwe
IsFramework            : False
PackageUserInformation : {}
IsResourcePackage      : False
IsBundle               : False
IsDevelopmentMode      : False
NonRemovable           : True
Dependencies           : {Microsoft.VCLibs.140.00.UWPDesktop_14.0.30035.0_x64__8wekyb3d8bbwe,
                         Microsoft.DesktopAppInstaller_1.15.11694.0_neutral_split.language-fa_8wekyb3d8bbwe,
                         Microsoft.DesktopAppInstaller_1.15.11694.0_neutral_split.scale-125_8wekyb3d8bbwe,
                         Microsoft.DesktopAppInstaller_1.15.11694.0_neutral_split.scale-100_8wekyb3d8bbwe}
IsPartiallyStaged      : False
SignatureKind          : Store
Status                 : Ok
```

I do have Discord installed. Not sure how that one is related, but I can try uninstalling it.

**Comment by denelon** [comment] 2021-08-18 16:51
@billriess can you describe the scenario a bit more and how you came to identify Discord as a possible cause/correlation?

**Comment by A9G-Data-Droid** [comment] 2021-09-01 22:18
Can we remove the `Needs-Author-Feedback` flag? Who has this power?

**Comment by ItzLevvie** [comment] 2021-09-01 22:19
What happens if you open up Command Prompt with administrator privileges and do `path %LOCALAPPDATA%\Microsoft\WindowsApps`? This will temporarily reset your Command Prompt's %PATH% variable until you close it, so there's no panic involved here by permanently resetting your %PATH% variable.

**Comment by A9G-Data-Droid** [comment] 2021-09-01 22:45
You don't have to modify your path to reach an executable.

You can just run the fully qualified path.

I gave my account explicit `Full Control` permissions to the `WindowsApps` folder.

This is what I see from command prompt:
```
C:\>%LOCALAPPDATA%\Microsoft\WindowsApps\winget.exe
The system cannot execute the specified program.
```

**Comment by A9G-Data-Droid** [comment] 2021-09-01 22:58
@denelon Instead of a troubleshooting guide you should ship a binary that works as expected. That would reduce the "noise" you're hearing about it. There should not be a broad issue with multiple causes.

**Comment by denelon** [comment] 2021-09-01 23:34
@A9G-Data-Droid I'm not able to reproduce this issue. I'm also not closing the issue with "It works on my machine[tm]". There are certainly many causes for software to end up in an inconsistent state. I noticed the text from you GitHub profile "I am an edge case." (I laughed about it. I know the feeling). In this instance, I believe your system is an demonstrating an edge case. 

If you can help us understand what state the system is in, and preferably how the machine got to that state, we can look for a fix. We may not be able to prevent it, and we may not be able to detect it to automatically fix it (or prevent it from ending up in that state), but maybe we can help get it working.

The noise I referred to is other unrelated, but similar in appearance problems. Software is complex. If I was posting an issue like "my car won't start", and many other people said "my car wont start either", it doesn't help solve the problem for "me". Those other messages end up being the "noise" I was referring to.

That's quite different from an issue that says "when a car has no fuel, it won't start". With something like that, maybe a feature like a fuel gauge can be implemented. It might even be enhanced with an audible alert when the fuel is running low.

Similarly, there are several causes to get undesired results when you try to run `winget`. One might not have the correct version of the App Installer, the PATH environment variable may have been modified by a user or another program. The App Execution Alias may be disabled. Any number of other factors might be the cause. That's what I mean with the term "broad". Hundreds of thousands of users have been able to install and run the Windows Package Manager. I've only seen tens of users with the more generic "`winget` command does not work". I want everyone to be able to use the Windows Package Manager, and it's going to take time to figure out the various reasons why it doesn't so we can try and fix the underlying issue,

In some cases, if it can't be automatically fixed, we're going to need troubleshooting guides for those. Have you attempted the in-place upgrade suggested by @ItzLevvie? You might also try installing the [latest](https://github.com/microsoft/winget-cli/releases/tag/v1.0.11692) version of the App Installer.

**Closed** 2021-09-02 00:03 UTC
Labels: Issue-Bug, Needs-Author-Feedback

**Comment by aminya** [comment] 2021-09-02 00:40
Please re-open this issue. It is not still fixed.

**Comment by mshaikhcool** [comment] 2021-09-02 02:18
being Passive-aggressiveness or _seemingly passive-aggressive_(a logical assumption) is not constructive therefore it doesn't help **_anyone._**

now the elephant of the room - 

* see https://github.com/PowerShell/PowerShell/issues/13138#issuecomment-907790696 note that Appx module under the hood calls WinRT apis  and  Powershell is built on .NET , to call WinRT apis from .NET 5 + onwards , each powershell modules has to be ` ComWrappers` compatible ,  we are waiting for like more than one year for windows powershell's appx module team to make those appx modules `ComWrappers` compatible, since it hasn't happened , the logical conclusion we can make is that the Appx or MSIX team is  lazy af.    I encourage everyone to make those extreme "noises" / make sure your voices heard there to wake them up .

* secondly, thing is MSIX  doesn't support SSH,WinRM, per machine install/uninstall , so you can't run as user A while logged in as user B. Winget is MSIX packaged. so winget suffers from that.

**End of the day, all of these pains are coming from the slept MSIX/APPX team, make sure to give them enough nudges in msix packaging repo or microsoft techcommunity msix site, that will be appropriate and logical. let's see how long they can ignore us.**

**Comment by denelon** [comment] 2021-09-02 14:38
@aminya feel free to create a new issue with specifics for the specifics for your scenario. Let the community know what you've attempted so we can help troubleshoot. The original author for this Issue has closed it.

**Comment by heitoreleuterio** [comment] 2022-01-12 04:47
I was with the same problem, winget wasn't works in PowerShell. Microsoft Store said that App Installer was already updated, but it wasn't.
Running the command `Get-AppxPackage microsoft.DesktopAppInstaller` I've the info that current version on my system was actually 1.4, while the current version is 1.16. 

The way I've found to solve this problem was install the current stable version on official Windows Package Manager repository:

https://github.com/microsoft/winget-cli/releases/tag/v1.1.12653

This is the last stable version in 01/12/2021. To install you just need scroll to the bottom of the page in Assets field, and install the `Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle`. This will force update.

**Comment by heitoreleuterio** [comment] 2022-01-12 04:49
I was with the same problem, winget wasn't working in PowerShell. Microsoft Store said that App Installer was already updated, but it wasn't.
Running the command `Get-AppxPackage microsoft.DesktopAppInstaller` I've the info that version on my system was actually 1.4, while the current version is 1.16.

The way I've found to solve this problem was install the current stable version on official Windows Package Manager repository:

https://github.com/microsoft/winget-cli/releases/tag/v1.1.12653

This is the last stable version in 01/12/2021. To install you just need scroll to the bottom of the page in Assets field, and install the `Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle`. This will force update.

**Comment by denelon** [comment] 2022-03-02 20:51
@seanmcd27 the App Installer version and the Windows Package Manager version only share the final part of the version:

```
PS C:\Users\denelon> winget --info
Windows Package Manager (Preview) v1.3.431-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22563.1
Package: Microsoft.DesktopAppInstaller v1.18.431.0
```

The App Installer version for the Windows Package Manager 1.1.z release is 1.16.z
![AppInstaller](https://user-images.githubusercontent.com/61799811/156447445-2b245453-71a0-4bf3-b4be-7f3afb3fa05e.png)

**Comment by wangshanghai240** [comment] 2022-08-02 11:45
我也有同样的问题，是最近才出现的，以前从未出现，我还安装了wsl2运行Ubuntu 22

**Comment by Rainson12** [comment] 2023-05-15 07:31
I am having the same issue here

**Comment by ubeydtalha** [comment] 2023-07-04 20:08
go C:\Users\"[YOUR_USERNAME]"\AppData\Local\Microsoft\WindowsApps

you will find winget there

<img width="482" alt="image" src="https://github.com/microsoft/winget-cli/assets/62707118/1e53fdc3-6055-4416-aa1e-c30abd811fca">

**Comment by emoxam** [comment] 2023-08-07 09:31
> @JoeLyga are you a Windows Package Manager Insider or running a Windows Insider build? How did you install the "App Installer"?

I was at Windows Package Manager Insider, how can i check it ?
It stoped to work a few days ago. Why ?

**Comment by xodotLBO** [comment] 2023-08-17 01:32
After latest app installer update I can't get winget to work
winget : The term 'winget' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
 the spelling of the name, or if a path was included, verify that the path is correct and try again.
 
 I tried re-registering it, editing env. variables, updating everything.. nothing helps.

**Comment by emoxam** [comment] 2023-08-17 06:42
It seems for some reason we need to add this manually to PATH
%userprofile%\AppData\Local\Microsoft\WindowsApps\

**Comment by xodotLBO** [comment] 2023-08-17 09:58
Already did, it didn't do anything.

**Comment by emoxam** [comment] 2023-08-17 10:17
> Already did, it didn't do anything.

It helped me.
I did this because of this

dir %userprofile%\AppData\Local\Microsoft\WindowsApps\ | findstr winget
16.08.2023  12:03                 0 winget.exe

**Comment by xodotLBO** [comment] 2023-08-17 10:25
Well i wish it helped me but doesn't seem to be working as it gives me same error that term winget is not recognized

**Comment by emoxam** [comment] 2023-08-17 10:27
> Well i wish it helped me but doesn't seem to be working as it gives me same error that term winget is not recognized

cd %userprofile%\AppData\Local\Microsoft\WindowsApps\
winget

works ?

show me dir command output if it's not.

**Comment by xodotLBO** [comment] 2023-08-17 10:49
It doesn't work, says the path doesn't exist. 
cd : Cannot find path 'C:\WINDOWS\system32\%userprofile%\AppData\Local\Microsoft\WindowsApps' because it does not exist.

**Comment by emoxam** [comment] 2023-08-17 11:04
> cd %userprofile%\AppData\Local\Microsoft\WindowsApps

It should not be powershell, it should be cmd console while you trying to cd.

What do you mean? What "App execution alias" ?

**Comment by xodotLBO** [comment] 2023-08-17 12:34
> > cd %userprofile%\AppData\Local\Microsoft\WindowsApps
> 
> It should not be powershell, it should be cmd console while you trying to cd.
> 
> What do you mean? What "App execution alias" ?

Works fine in cmd. 
App execution alias is exactly what it says, you can use search bar and see whats it like. I had winget com server, package manager and everything else disabled somehow even tho I didn't touch anything

**Comment by emoxam** [comment] 2023-08-17 12:50
> > > cd %userprofile%\AppData\Local\Microsoft\WindowsApps
> > 
> > 
> > It should not be powershell, it should be cmd console while you trying to cd.
> > What do you mean? What "App execution alias" ?
> 
> Works fine in cmd. App execution alias is exactly what it says, you can use search bar and see whats it like. I had winget com server, package manager and everything else disabled somehow even tho I didn't touch anything

So you just enabled all that is about winget ? And that was the fix ?

**Comment by xodotLBO** [comment] 2023-08-17 12:51
Yea, I enabled everything related to it and now it works fine. I can post a picture if needed. But I never touched these settings, they disabled themselves after the update somehow

**Comment by emoxam** [comment] 2023-08-17 12:52
> Yea, I enabled everything related to it and now it works fine. I can post a picture if needed. But I never touched these settings, they disabled themselves after the update somehow

Can confirm it was disabled too at my colleague PC.

**Comment by ImAhmadAbdullah** [comment] 2024-03-21 00:38
I did this to fix it: `New-Alias -Name winget -Value "C:\Users\User\AppData\Local\Microsoft\WindowsApps\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\winget.exe"`
