### ISSUE TITLE
Winget export not exporting any Store installed apps

### ISSUE THREAD

**Issue by Masamune3210** [microsoft/winget-cli#2307] opened 2022-07-04 20:52 UTC
### Brief description of your issue

When trying to export all currently installed apps, winget claims that no install package is available for any installed store apps, traditional installers show up fine if they exist in the database, but anything installed from the store is not found

### Steps to reproduce

1. Install SysInternals Suite or any Store based app 
2. Try to run winget export <filename>
3. Notice the Store app is stated as not being found in any source and is missing from the exported list

### Expected behavior

Store apps are correctly exported into the final file and can be installed when running import

### Actual behavior

Store apps are currently stated as not found in any source and is missing from the final export, import obviously doesn't install them as it knows nothing about them due to them being missing in the export list

### Environment

```shell
Windows Package Manager (Preview) v1.3.1391-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.160
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.1391.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by Masamune3210** [comment] 2022-07-04 20:53
This happens even on Release version of Windows (22000) so it isn't some Insider issue, and happens even though I have the msstore source enabled

**Comment by denelon** [comment] 2022-07-05 14:28
Duplicate of #1562

**Closed** 2022-07-05 14:28 UTC
Labels: Needs-Triage
