### ISSUE TITLE
By name alphabetical order searches

### ISSUE THREAD

**Issue by josh-65** [microsoft/winget-cli#1036] opened 2021-05-30 19:30 UTC
# Description of the new feature/enhancement
When doing a `winget search` it will display all of the available programs but not in alphabetical order by Name witch makes it harder for me to look through.

# Proposed technical implementation details
It should order it by Name not ID from 0-9 AAA-ZZZ

**Comment by denelon** [comment] 2021-06-01 15:12
@josh-65 the search return order has more to do with what "matched" with a particular field in the manifest. I like the idea of adding some additional arguments for sorting results. This could be arguments, and/or settings.

**Comment by chausner** [comment] 2021-06-21 23:27
This seems to be a duplicate of #142.

**Comment by denelon** [comment] 2021-06-21 23:42
Duplicate of #142

**Closed by denelon** 2021-06-21 23:42 UTC
Labels: Issue-Feature
