### ISSUE TITLE
Multiple installed packages found matching input criteria. Please refine the input

### ISSUE THREAD

**Issue by Jason1269** [microsoft/winget-cli#1784] opened 2021-12-08 18:46 UTC
### Brief description of your issue

Unable to upgrade package when there are more than one with similar names installed on the system even after the other package has been upgraded.

Packages with upgrade issues:

- Microsoft.VC++2015-2022Redist-x86
- Microsoft.VC++2013Redist-x86

No command combination with `-e` `--name` or `--id` worked

### Steps to reproduce

Using package **Microsoft.VC++2015-2022Redist-x86** as example

PS C:\> winget --version

`v1.1.12986`

PS C:\> winget upgrade
```
Name                                         Id                                Version          Available        Source
-----------------------------------------------------------------------------------------------------------------------
Git                                          Git.Git                           2.31.1           2.34.1           winget
Notepad++                                    Notepad++.Notepad++               7.9.5            8.1.9.2          winget
Microsoft OneDrive                           Microsoft.OneDrive                21.160.0808.0002 21.220.1024.0005 winget
Microsoft Visual C++ 2013 Redistributable (… Microsoft.VC++2013Redist-x64      12.0.30501.0     12.0.40664.0     winget
Eclipse Temurin JDK with Hotspot 8           EclipseAdoptium.Temurin.8         8.0.302.8        8.0.312.7        winget
Microsoft Build of OpenJDK with Hotspot 11   Microsoft.OpenJDK.11              11.0.12.7        11.0.13.8        winget
Microsoft Visual C++ 2015-2022 Redistributa… Microsoft.VC++2015-2022Redist-x86 14.30.30704.0    14.31.30818.0    winget
Microsoft Visual C++ 2013 Redistributable (… Microsoft.VC++2013Redist-x86      12.0.40660.0     12.0.40664.0     winget
Microsoft .NET SDK                           Microsoft.dotnet                  5.4.321.52708    6.1.21.52711     winget
Python 3                                     Python.Python.3                   3.9.4150.0       3.10.150.0       winget
Google Chrome                                Google.Chrome                     96.0.4664.45     96.0.4664.93     winget
Microsoft .NET SDK                           Microsoft.dotnet                  5.3.321.37723    6.1.21.52711     winget
Microsoft Visual C++ 2013 Redistributable (… Microsoft.VC++2013Redist-x64      12.0.40660.0     12.0.40664.0     winget
Microsoft Visual C++ 2013 Redistributable (… Microsoft.VC++2013Redist-x86      12.0.30501.0     12.0.40664.0     winget
```
PS C:\> winget upgrade --id Microsoft.VC++2015-2022Redist-x86
```
Multiple installed packages found matching input criteria. Please refine the input.
Name                                                               Id
---------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015-2022 Redistributable (x86)               Microsoft.VC++2015-2022Redist-x86
Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.31.30818 {69becc62-c3d6-4307-9fc5-738d92cdf886}
```
PS C:\> winget upgrade -e --id Microsoft.VC++2015-2022Redist-x86
```
Multiple installed packages found matching input criteria. Please refine the input.
Name                                                               Id
---------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015-2022 Redistributable (x86)               Microsoft.VC++2015-2022Redist-x86
Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.31.30818 {69becc62-c3d6-4307-9fc5-738d92cdf886}
```
PS C:\> winget upgrade --name "Microsoft Visual C++ 2015-2022 Redistributable (x86)"
```
Multiple installed packages found matching input criteria. Please refine the input.
Name                                                               Id
---------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015-2022 Redistributable (x86)               Microsoft.VC++2015-2022Redist-x86
Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.31.30818 {69becc62-c3d6-4307-9fc5-738d92cdf886}
```
PS C:\> winget upgrade -e --name "Microsoft Visual C++ 2015-2022 Redistributable (x86)"
```
Multiple installed packages found matching input criteria. Please refine the input.
Name                                                               Id
---------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015-2022 Redistributable (x86)               Microsoft.VC++2015-2022Redist-x86
Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.31.30818 {69becc62-c3d6-4307-9fc5-738d92cdf886}
```

### Expected behavior

Either one of the command below should have successfully upgraded Microsoft.VC++2015-2022Redist-x86

`winget upgrade --id Microsoft.VC++2015-2022Redist-x86`

`winget upgrade -e --id Microsoft.VC++2015-2022Redist-x86`

`winget upgrade -e "Microsoft Visual C++ 2015-2022 Redistributable (x86)"`

`winget upgrade -e --name "Microsoft Visual C++ 2015-2022 Redistributable (x86)"`

### Actual behavior

Returns message stating there are multiple packages that match criteria with a list of similarly named packages, even when using ID and the IDs of the packages are different

```
Multiple installed packages found matching input criteria. Please refine the input.
Name                                                               Id
---------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015-2022 Redistributable (x86)               Microsoft.VC++2015-2022Redist-x86
Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.31.30818 {69becc62-c3d6-4307-9fc5-738d92cdf886}
```

### Environment

```shell
Windows Package Manager v1.1.12986
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.1348
Package: Microsoft.DesktopAppInstaller v1.16.12986.0
```

**Comment by Toby-Broom** [comment] 2021-12-08 20:39
I also can repo this

**Comment by denelon** [comment] 2021-12-08 23:41
Duplicate of #1413

**Closed by denelon** 2021-12-08 23:41 UTC
Labels: Needs-Triage
