### ISSUE TITLE
Add DocFX tools

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/winget-cli#425] opened 2020-05-30 08:29 UTC
# Description of the new feature/enhancement

DocFX describes a bunch of tools to obtain their program, like chocolatey, [here](https://dotnet.github.io/docfx/tutorial/docfx_getting_started.html#2-use-docfx-as-a-command-line-tool). Would be great to see winget support for this.

**Comment by denelon** [comment] 2020-06-15 22:24
Duplicate of #140

**Closed by denelon** 2020-06-15 22:24 UTC
Labels: Needs-Triage
