### ISSUE TITLE
winget list --source winget should exclude applications with no source

### ISSUE THREAD

**Issue by SiJiL82** [microsoft/winget-cli#1600] opened 2021-10-15 21:08 UTC
### Description of the new feature / enhancement

When explicitly specifying a source to list (`winget list --source winget`), Winget currently includes applications with no source.
e.g.:
![image](https://user-images.githubusercontent.com/65114782/137553616-5b290883-e782-47b2-8516-b0ebb92e06f1.png)
If a source is specified in the command, IMO it should _only_ show applications where that source is matched, not ones that have _no_ source.

**Comment by denelon** [comment] 2021-10-15 23:38
Duplicate of #1155

**Closed by denelon** 2021-10-15 23:38 UTC
Labels: Issue-Feature, Needs-Triage
