### ISSUE TITLE
Symlinked executables have missing dependencies

### ISSUE THREAD

**Issue by sitiom** [microsoft/winget-cli#2889] opened 2023-01-28 00:49 UTC
### Brief description of your issue

Since not all executables are statically built, symlinked executables often have missing dependencies with DLLs. Example:

- https://github.com/microsoft/winget-pkgs/pull/94818

This means dynamically linked executables won't work properly in Winget. There should be a way for Winget to handle this.

https://github.com/microsoft/winget-cli/issues/361#issuecomment-1272492108
> If an app depends on some .dll file within its directory, symbolic links do not work. Also, symbolic links require admin permission.

Possible solution: Use shims, like Scoop or Chocolatey.
- https://github.com/microsoft/winget-cli/issues/361

### Steps to reproduce

1. Checkout https://github.com/microsoft/winget-pkgs/pull/94818
2. Install `Google.Android.SDKPlatformTools`
3. Calling `adb` from the command line silently errors out with no output but calling the direct target executable works.

### Expected behavior

Winget should somehow handle dependencies from symlinks.

### Actual behavior

Executable does not work correctly due to missing DLLs.

### Environment

```shell
Windows Package Manager v1.4.10173

Windows: Windows.Desktop v10.0.22621.1105
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0
```

**Comment by Trenly** [comment] 2023-01-28 01:07
Seems like this is a duplicate of https://github.com/microsoft/winget-cli/issues/2711

**Closed** 2023-01-28 01:11 UTC
Labels: Needs-Triage
