### ISSUE TITLE
winget upgrade --all does nothing even with version Windows Package Manager v1.7.10582

### ISSUE THREAD

**Issue by filzek** [microsoft/winget-cli#4266] opened 2024-03-13 04:37 UTC
### Brief description of your issue

C:\Users\devop>winget repair
Windows Package Manager v1.7.10582
Copyright (c) Microsoft Corporation. All rights reserved.

No package selection argument was provided; see the help for details about finding a package.

Repairs the selected package, either found by searching the installed packages list or directly from a manifest. By default, the query must case-insensitively match the id, name, or moniker of the package. Other fields can be used by passing their appropriate option.

usage: winget repair [[-q] <query>] [<options>]

The following arguments are available:
  -q,--query                           The query used to search for a package

The following options are available:
  -m,--manifest                        The path to the manifest of the package
  --id                                 Filter results by id
  --name                               Filter results by name
  --moniker                            Filter results by moniker
  -v,--version                         Use the specified version; default is the latest version
  --product-code                       Filters using the product code
  -a,--architecture                    Select the architecture
  --scope                              Select installed package scope filter (user or machine)
  -s,--source                          Find package using the specified source
  -i,--interactive                     Request interactive installation; user input may be needed
  -h,--silent                          Request silent installation
  -o,--log                             Log location (if supported)
  --ignore-local-archive-malware-scan  Ignore the malware scan performed as part of installing an archive type package from local manifest
  --accept-source-agreements           Accept all source agreements during source operations
  --accept-package-agreements          Accept all license agreements for packages
  --locale                             Locale to use (BCP47 format)
  --header                             Optional Windows-Package-Manager REST source HTTP header
  --authentication-mode                Specify authentication window preference (silent, silentPreferred or interactive)
  --authentication-account             Specify the account to be used for authentication
  --force                              Direct run the command and continue with non security related issues
  --ignore-security-hash               Ignore the installer hash check failure
  -e,--exact                           Find package using exact match
  -?,--help                            Shows help about the selected command
  --wait                               Prompts the user to press any key before exiting
  --logs,--open-logs                   Open the default logs location
  --verbose,--verbose-logs             Enables verbose logging for winget
  --disable-interactivity              Disable interactive prompts

More help can be found at: https://aka.ms/winget-command-repair

C:\Users\devop>winget upgrade --all
Name                                                   Id                                Version        Available      Source
-----------------------------------------------------------------------------------------------------------------------------
GitHub Desktop                                         GitHub.GitHubDesktop              3.3.9          3.3.11         winget
Google Chrome                                          Google.Chrome                     122.0.6261.113 122.0.6261.129 winget
Postman x86_64 10.23.5                                 Postman.Postman                   10.23.5        10.24.0        winget
SourceTree                                             Atlassian.Sourcetree              3.4.16         3.4.17         winget
WinRAR 6.24 (64-bit)                                   RARLab.WinRAR                     6.24.0         7.00.0         winget
Zoom                                                   Zoom.Zoom                         5.17.10.33775  5.17.11.34827  winget
WinSCP 6.3.1                                           WinSCP.WinSCP                     6.3.1          6.3.2          winget
Microsoft Windows Desktop Runtime - 3.1.32 (x64)       Microsoft.DotNet.DesktopRuntime.7 < 7.0.0        7.0.17         winget
Python Launcher                                        Python.Launcher                   < 3.12.0       3.12.0         winget
Microsoft ASP.NET Core 7.0.7 - Shared Framework (x64)  Microsoft.DotNet.AspNetCore.7     7.0.7          7.0.17         winget
Microsoft ASP.NET Core 7.0.16 - Shared Framework (x64) Microsoft.DotNet.AspNetCore.7     7.0.16         7.0.17         winget
Microsoft Visual Studio Code (User)                    Microsoft.VisualStudioCode        1.86.2         1.87.2         winget
Microsoft .NET Runtime - 6.0.27 (x64)                  Microsoft.DotNet.Runtime.6        6.0.27         6.0.28         winget
Microsoft Windows Desktop Runtime - 7.0.7 (x64)        Microsoft.DotNet.DesktopRuntime.7 7.0.7          7.0.17         winget
Microsoft Windows Desktop Runtime - 7.0.16 (x64)       Microsoft.DotNet.DesktopRuntime.7 7.0.16         7.0.17         winget
17 upgrades available.

The following packages have an upgrade available, but require explicit targeting for upgrade:
Name                         Id              Version      Available            Source
-------------------------------------------------------------------------------------
Microsoft Teams              Microsoft.Teams 1.6.00.35961 23320.3027.2591.1505 winget
Teams Machine-Wide Installer Microsoft.Teams 1.5.0.30767  23320.3027.2591.1505 winget

C:\Users\devop>

### Steps to reproduce

install and try to run 
winget upgrade --all

it list all and does nothing

### Expected behavior

install all packeges avaliable

### Actual behavior

does nothing

### Environment

```shell
C:\Users\devop>winget --info
Windows Package Manager v1.7.10582
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3235
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10582.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by mdanish-kh** [comment] 2024-03-13 04:43
Try using the pre-release version [v1.7.10061](https://github.com/microsoft/winget-cli/releases/tag/v1.7.10661). This is a known issue in v1.7.10582. If you still run into problems, you can report in the tracking issue here https://github.com/microsoft/winget-cli/issues/4219

Duplicate of #4219

**Closed** 2024-03-13 04:43 UTC

**Comment by Sourav9063** [comment] 2024-03-23 00:21
In the Windows search,

type powershell, right-click it, and choose run as administrator.

Execute this command and the issue should be resolved.

`Get-AppxPackage -Name 'Microsoft.DesktopAppInstaller' | Reset-AppxPackage`


Hope that helps, and rely on us for any further inquiries. All the best.
