### ISSUE TITLE
Package size / And few ideas

### ISSUE THREAD

**Issue by Msadr471** [microsoft/winget-cli#1280] opened 2021-07-14 08:52 UTC
# Package size
![image](https://user-images.githubusercontent.com/49529241/125590555-db9e9202-795e-48af-85c4-304e1a182719.png)

Regularly, if along with these explanations and specifications, also show the size of the software package or the size to be downloaded and update the software!
Or ... for example, use the command `winget upgrade -all`  to show these options (size and etc.) and normally it is the same! I mean showing everything about all software that was installed on PC, like a BIG list!

# `winget show`
`winget show "Microsoft Visual Studio Code"`
![image](https://user-images.githubusercontent.com/49529241/125591293-cf18da8f-cd67-43cb-9a84-51c0eb5346d9.png)
**Add these too:**
1. Software size
2. Update size
3. Installation location
4. Installation Date
5. last update
6. User(s)

**Comment by denelon** [comment] 2021-07-14 23:54
Duplicate of #1070 

@Msadr471 most of these look like duplicate asks, or are related to a similar ask like #1070 and #1130.

Install location depends both on the installer and the arguments passed to the client. #345 covers adding a release date.

Please create one request per issue, and check for duplicates. It's much easier to implement and close Issues when they are for a single request 😊. We also try to prioritize what we work on next based on the number of 👍s on the issue. It would be sad to have two Issues for the same thing end up lower in priority because the community support is split across two issues.

**Closed by denelon** 2021-07-14 23:54 UTC
Labels: Issue-Feature
