### ISSUE TITLE
Get an option to stop trimming the output of `winget list`

### ISSUE THREAD

**Issue by EDM115** [microsoft/winget-cli#4743] opened 2024-08-20 15:23 UTC
### Description of the new feature / enhancement

We could have a new switch like `winget list --no-trim` that would output the full names, packages IDs and versions of installed winget packages and stop trimming them to columns of fixed width.  
this would allow someone to have a list of all installed packages so he can reinstall them later easier on a new pc.  
but as it may be complex to do and keep a consistent padding for all lines, a `--json` option could be preferred

**Comment by stephengillie** [comment] 2024-08-20 15:51
As another option, please consider using the PowerShell cmdlets. These return PSObjects which can easily be manipulated:

```
PS C:\ManVal> Find-WinGetPackage edge | where {$_.name -match "Microsoft"}

Name                            Id                            Version        Source
----                            --                            -------        ------
Microsoft Edge Browser          XPFFTQ037JWMHS                Unknown        msstore
Remote Tools for Microsoft Edge 9P6CMFV44ZLT                  Unknown        msstore
Microsoft Edge DevTools Preview 9MZBFRMZ0MNJ                  Unknown        msstore
Microsoft Edge                  Microsoft.Edge                127.0.2651.105 winget
Microsoft Edge Beta             Microsoft.Edge.Beta           128.0.2739.22  winget
Microsoft Edge Canary           Microsoft.Edge.Canary         112.0.1705.0   winget
Microsoft Edge Dev              Microsoft.Edge.Dev            129.0.2766.0   winget
Microsoft Edge WebDriver        Microsoft.EdgeDriver          127.0.2651.105 winget
Microsoft Edge WebView2 Runtime Microsoft.EdgeWebView2Runtime 127.0.2651.105 winget
```

**Comment by Trenly** [comment] 2024-08-20 15:51
If you use the PowerShell Module, `Get-WinGetPackage` will return structured data that includes all the information and can be converted to JSON using other inbuilt PowerShell functions.

###### Duplicate of #1653

**Closed** 2024-08-20 15:51 UTC
Labels: Issue-Feature

**Comment by EDM115** [comment] 2024-08-20 16:03
thanks @Trenly for the tip ❤️
