### ISSUE TITLE
Excluding packages from upgrade --all

### ISSUE THREAD

**Issue by DukeW** [microsoft/winget-cli#1147] opened 2021-06-10 09:44 UTC
# Description of the new feature/enhancement

`winget upgrade --all` is a very good features but it is unusable if you wish to keep an installed package at its currently installed version(s). There should be a way to exclude packages.
A concrete example:
![image](https://user-images.githubusercontent.com/4922350/121502725-1ca3ec80-c9e9-11eb-80f8-1e0f30b12cc3.png)
I don't want to upgrade Unity because I need those specific versions, but I do want to upgrade everything else.

# Proposed technical implementation details (optional)
A new command: `winget hold PKG` that marks the given package to be excluded from `winget upgrade --al` 
A second new command `winget release PKG` to undo said exclusion.

**Comment by denelon** [comment] 2021-06-10 18:29
Duplicate of #476

**Closed by denelon** 2021-06-10 18:29 UTC
Labels: Issue-Feature, Needs-Triage
