### ISSUE TITLE
Winget should support logical packages 

### ISSUE THREAD

**Issue by MattHyman** [microsoft/winget-cli#4345] opened 2024-04-03 05:58 UTC
### Description of the new feature / enhancement

Winget should support logical packages. While it is discussed in #2129 that winget should better support side by side packages, it does not go into how winget should reason about them. For example; today you can only ask to install Microsoft.WindowsSDK.10.0.22621, ideally you would be able to ask to install/upgrade Microsoft.WindowsSDK.10.0, in other words the latest Windows SDK. A similar scenario would be helpful for the Microsoft.GDK.* family of packages. The actual side by side behavior of these packages could be handled by the existing side by side behavior found within each package ID's manifest files. 

As a stretch goal it would be helpful if each logical package could specify how each version is listed in winget search. A sample scenario is how the different Microsoft.GDK.* edition families should be shown in decreasing order, in other words the newest edition family first, instead of the current order which can hide the latest GDK. 

![image](https://github.com/microsoft/winget-cli/assets/1520739/44c54d0c-cb68-4691-bae0-633ee38db15b)

![image](https://github.com/microsoft/winget-cli/assets/1520739/6c175fd5-4222-4487-9f96-418bd270ef9a)

Sample relevant packages: 
- [Microsoft.WindowsSDK.10.0](https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/WindowsSDK/10/0)
- [Microsoft.GDK](https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/GDK)

Relevant Issues:
- #2129

### Proposed technical implementation details

Ideally a YAML file would be placed in the manifest root of the logical package, such as [here for the windows SDK](https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/WindowsSDK/10/0). This YAML file would contain the logical package's ID, its display behavior/ordering and other information necessary for winget to tie its children packages together.

**Comment by Trenly** [comment] 2024-04-03 15:27
Duplicate of #4074

**Closed** 2024-04-03 15:27 UTC
Labels: Issue-Feature
