### ISSUE TITLE
preinstalled apps check and script improvements

### ISSUE THREAD

**Issue by abdoi94** [microsoft/winget-cli#1292] opened 2021-07-17 10:47 UTC
hello everyone,
i have some suggestions about the way winget currently works, and i would like to share it with everyone in here:

**1. check installed package against metadata** 
when i try to install some package winget doesnt check installed package against metadata /repo to see if i have the same version /build, it just proceeds to install anyways, here is an example

![Screenshot 2021-07-17 132407](https://user-images.githubusercontent.com/5349989/126033990-d601f002-9de6-4adc-ac2d-5ee56f14a71c.png)
already running latest powershell build, and it installed it again.

**2. continue to finish a script when a certian package fail**
when a package hash check fails winget just stops everything instead of moving on to the next package, which makes the whole proccess a bit tideous, i have to keep checking if anything fails and re run the scirpt again without it (im aware of force flag)

**3. wrap around new lines in .bat script**
when i did a script to install all the packages i needed it just stops after the first line of commands, meanwhile the same thing on Linux/Arch just keeps going through the lines when i run it with bash... one the other hand oneline commands works fine but they're a bit meh to work with, example [here](https://gist.github.com/abdoi94/ac04e2cf52177998dc5c07b4678f580c)

**Comment by denelon** [comment] 2021-07-19 17:00
@abdoi94 thanks for the feedback. These look like duplicates:
Number 1 looks closest to - Duplicate of #929 or maybe #1061.
Number 2 looks closest to #1273
For number 3, take a look at import / export.

**Closed by denelon** 2021-07-19 17:01 UTC
Labels: Issue-Feature, Needs-Triage
