### ISSUE TITLE
winget upgrade source or instal error rename

### ISSUE THREAD

**Issue by DarkPlasticine** [microsoft/winget-cli#1457] opened 2021-09-11 11:00 UTC
# Brief description of your issue
An unknown error occurs when trying to update or install a any package via winget upgrade or install

# Steps to reproduce

![Снимок экрана 2021-09-11 195854](https://user-images.githubusercontent.com/12997911/132945573-3f65f2c2-90d1-4105-8c12-60bed839d6b7.png)

# Expected behavior

# Actual behavior

# Environment

```none
[winget --info]
Windows Package Manager v1.0.11694
Windows: Windows.Desktop v10.0.22454.1000
Package: Microsoft.DesktopAppInstaller v1.15.11694.0

Any other software?
```

**Comment by jedieaston** [comment] 2021-09-12 19:06
I think this is a duplicate of #1435. Can winget not handle folders with truncated names?

**Comment by denelon** [comment] 2021-10-01 20:20
@DarkPlasticine can you confirm if this has been resolved in the latest release?

#1435 is resolved.

**Comment by denelon** [comment] 2022-06-07 22:10
Duplicate of #1435

**Closed by denelon** 2022-06-07 22:10 UTC
Labels: Issue-Bug, Needs-Author-Feedback
