### ISSUE TITLE
Special chars seem to not be handled correctly when installing packages

### ISSUE THREAD

**Issue by kjo-sdds** [microsoft/winget-cli#4765] opened 2024-08-29 10:03 UTC
### Brief description of your issue

The path that was added to the PATH env variable is wrong ("special" chars )

### Steps to reproduce

1) Have a username (taken from the microsoft account ...) containing a "é" for example
2) winget install Schniz.fnm (for example ... but I've had this issue with other packages, like ffmpeg for instance so I assume problem might not lie in the packages themselves)
3) path gets added with "Ã©" instead of "é"
=> commands are not found ... 

### Expected behavior

handle correctly an "é" !! It's 2024 !!!
(even though I usually avoid accentuated chars ... since it was automatically taken from my Microsoft account ... I didn't have a word ... )

### Actual behavior

added with "Ã©" instead of "é"

### Environment

```shell
winget --info
Gestionnaire de package Windows v1.8.1911
Copyright (c) Microsoft Corporation. Tous droits réservés.

Windows: Windows.Desktop v10.0.22631.4037
Architecture du système : X64
Package : Microsoft.DesktopAppInstaller v1.23.1911.0
```

**Comment by kjo-sdds** [comment] 2024-08-29 10:07
Those issues link to a central issue : 
"Should have been fixed in v0.2.2521"
=> Obviously not ...

**Comment by stephengillie** [comment] 2024-08-29 15:44
This seems very similar to https://github.com/microsoft/winget-cli/issues/3312. and might be a duplicate. 
- The `é` character is mentioned in the [first comment](https://github.com/microsoft/winget-cli/issues/3312#issuecomment-1865973760).

**Comment by denelon** [comment] 2024-08-29 17:01
Duplicate of #3312

**Closed** 2024-08-29 17:01 UTC
Labels: Issue-Bug, Command-Install
