### ISSUE TITLE
winget export/import: support for override/location/custom install parameters

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-cli#3394] opened 2023-06-30 12:34 UTC
### Description of the new feature / enhancement

For example i use --location and --custom parameters while installing some packages:
```
winget install Microsoft.VisualStudioCode --no-upgrade -h --accept-package-agreements --accept-source-agreements --custom "/mergetasks='!runcode,addcontextmenufiles,addcontextmenufolders,associatewithfiles,addtopath'" # https://github.com/microsoft/winget-pkgs/issues/106091
sudo winget install --no-upgrade -h -l ~\Steam Valve.Steam
sudo winget install --no-upgrade -h --accept-package-agreements --accept-source-agreements Git.Git --custom '"/COMPONENTS=`"icons,assoc,assoc_sh,,,,gitlfs,icons\quicklaunch`" /o:SSHOption=ExternalOpenSSH"'
```

It would be nice if winget can memorize them, and write them to json file when i do `winget export -o list.json`, and after i can import this packages will be installed with parameters that i need.

**Comment by denelon** [comment] 2023-06-30 16:38
Duplicate of #3281

**Closed** 2023-06-30 16:38 UTC
Labels: Issue-Feature
