### ISSUE TITLE
winget search -name """" truncates package ID

### ISSUE THREAD

**Issue by andrew-s-taylor** [microsoft/winget-cli#2729] opened 2022-11-30 20:30 UTC
### Brief description of your issue

When listing all Winget packages using winget --name """" (I use it to grid-view output), it truncates the ID on long packages and adds random special characters instead

### Steps to reproduce

In Powershell:
&winget search --name """" | out-gridview

Filter for "Process" and Process Explorer and Process Monitor are both truncated

### Expected behavior

It should display the full ID which works when searching by name

### Actual behavior

It displays truncated IDs

### Environment

```shell
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.1219
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0
```

**Comment by stephengillie** [comment] 2022-12-01 00:27
This might be related to 
* https://github.com/microsoft/winget-cli/issues/1371

**Comment by denelon** [comment] 2022-12-01 00:51
@andrew-s-taylor the output is truncated to fit the terminal width in the CLI. We've got PowerShell modules and cmdlets coming out in the next release which don't truncate the output.

**Comment by ppvnf** [comment] 2022-12-01 10:38
Maybe duplicate of https://github.com/microsoft/winget-cli/issues/2603

**Comment by denelon** [comment] 2022-12-01 17:05
Duplicate of #2603

**Closed** 2022-12-01 17:06 UTC
Labels: Issue-Bug
