### ISSUE TITLE
Package issue updating: Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.36.32532

### ISSUE THREAD

**Issue by parlevjo2** [microsoft/winget-cli#3588] opened 2023-09-04 20:50 UTC
### Brief description of your issue

When winget tries to update "Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.36.32532" it takes the VC_redist.x86.exe executable.

```
winget update "Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.36.32532"
Found Microsoft Visual C++ 2015-2022 Redistributable (x86) [Microsoft.VCRedist.2015+.x86] Version 14.38.32919.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.visualstudio.microsoft.com/download/pr/02a6d5c5-3e10-47de-8025-d97a1321d3e3/AD573D3198853FC71137A88E51ABDE844B84F29B0CE6DD91BBEC661BC0143B36/VC_redist.x86.exe
13.2 MB / 13.2 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

This download [https://download.visualstudio.microsoft.com/download/pr/02a6d5c5-3e10-47de-8025-d97a1321d3e3/AD573D3198853FC71137A88E51ABDE844B84F29B0CE6DD91BBEC661BC0143B36/VC_redist.x86.exe](https://download.visualstudio.microsoft.com/download/pr/02a6d5c5-3e10-47de-8025-d97a1321d3e3/AD573D3198853FC71137A88E51ABDE844B84F29B0CE6DD91BBEC661BC0143B36/VC_redist.x86.exe) is wrong

### Steps to reproduce

`winget update "Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.36.32532"`

### Expected behavior

Update "Microsoft Visual C++ 2015-2022 Redistributable (**x64**) - 14.36.32532"

### Actual behavior

It is updating "Microsoft Visual C++ 2015-2022 Redistributable (**x86**) - 14.36.32532"

### Environment

```shell
Windows: Windows.Desktop v10.0.22621.2134
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.2201.0
```

**Comment by parlevjo2** [comment] 2023-09-04 20:56
The proper update link should be https://download.visualstudio.microsoft.com/download/pr/02a6d5c5-3e10-47de-8025-d97a1321d3e3/5F60592799FAE0C82578112D4B621438FFC976AB39D848D8F7623F5705A83E27/VC_redist.x64.exe
I got that info from https://www.coolexe.com/1194.html and I found that site when search with google for "AD573D3198853FC71137A88E51ABDE844B84F29B0CE6DD91BBEC661BC0143B36"

**Comment by Trenly** [comment] 2023-09-05 03:01
This is a known issue with how installed packages are matched to available manifests.

* Duplicate of #2427 
* Related to #2995 
* Related to #2893
* Related to #2243

**Closed** 2023-09-05 03:02 UTC
Labels: Needs-Triage
