### ISSUE TITLE
Powershell compatibel output for export and/or list

### ISSUE THREAD

**Issue by ChrisNbg** [microsoft/winget-cli#1260] opened 2021-07-06 15:35 UTC
Hello,

i am currently playing around with winget and powershell. I thought it would be nice to create a CSV-List of my PC (and other PC's in an enterprise environment).

So I tested for example
`winget list | fl`

or 

`winget export | Export-csv $Env:Computername.csv -NoTypeInformation -Encoding UTF8 `

but nothing worked here because the output is not an powershell object. So I am not an powershell professional but working with it for since a while...

It would be cool if there was a way to get an object or just the json output directly from "export"... with json I can work...

I made a small work around for this but this is not ideal because i have always to create a file on a system which I have to import again in powershell:

`
#winget export -o .\software-list.csv --include-versions

$Winget = Get-Content -raw -Path .\software-list.csv | ConvertFrom-Json

$list =  @()
foreach ($Sources in $Winget.Sources) {
    $Sources.SourceDetails.name
    foreach ($source_pack in $Sources.Packages) {
        $pack = New-Object PSCustomObject
        $pack | Add-Member -NotePropertyName date           -NotePropertyValue (get-date -f yyyy-dd-MM)
        $pack | Add-Member -NotePropertyName time           -NotePropertyValue (get-date -f HH:mm:ss)
        $pack | Add-Member -NotePropertyName ComputerName   -NotePropertyValue $Env:Computername
        $pack | Add-Member -NotePropertyName Source         -NotePropertyValue $Sources.SourceDetails.name
        $pack | Add-Member -NotePropertyName Package        -NotePropertyValue $source_pack.PackageIdentifier
        $pack | Add-Member -NotePropertyName Pack_Version   -NotePropertyValue $source_pack.Version
        $pack | Add-Member -NotePropertyName Winget_Version -NotePropertyValue $Winget.WinGetVersion
        $list += $pack
    }
}
$list | Format-Table
`

from this list a can make an CSV-Export...
Thank you for now. I like to see this project growing!
With greets from germany
Christian

**Comment by denelon** [comment] 2021-07-07 01:07
Duplicate of #221

**Closed by denelon** 2021-07-07 01:07 UTC
Labels: Needs-Triage
