### ISSUE TITLE
Type Ahead / Auto Complete on winget-cli with common functions

### ISSUE THREAD

**Issue by jerrythiesen** [microsoft/winget-cli#320] opened 2020-05-24 18:23 UTC
# Description of the new feature/enhancement
When using the winget-cli from the Win 10 Command Prompt or Powershell, the basic syntax's of: `search `, `install`, and `help`, should have auto-complete/type-ahead functions similar to Linux/Mac OS's.

![FB163206-E28D-42DE-A009-9AAC1E3A3D44](https://user-images.githubusercontent.com/36054829/82761644-0caf6f80-9dca-11ea-96fc-22708386a589.GIF)
# Proposed technical implementation details (optional)

**Comment by suhailmalik07** [comment] 2020-05-24 18:33
Already mentioned #146 and currently in backlog.

**Comment by denelon** [comment] 2020-06-02 02:51
Duplicate of #146

**Closed by denelon** 2020-06-02 02:51 UTC
Labels: Issue-Feature, Needs-Triage
