### ISSUE TITLE
Installer failed with exit code: 1603

### ISSUE THREAD

**Issue by LucidObscurity** [microsoft/winget-cli#232] opened 2020-05-20 05:14 UTC
# Brief description of your issue

winget install Microsoft.SQLServerManagementStudio
Found SQL Server Management Studio [Microsoft.SQLServerManagementStudio]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://go.microsoft.com/fwlink/?linkid=2125901&clcid=0x409
  ██████████████████████████████   534 MB /  534 MB
Successfully verified installer hash
Installing ...
Installer failed with exit code: 1603
# Steps to reproduce
winget install Microsoft.SQLServerManagementStudio

winget install Microsoft.SQLServerManagementStudio
# Expected behavior
this line not displayed: Installer failed with exit code: 1603

# Actual behavior

# Environment
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.18363 Build 18363
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	ALIENWARE17
System Manufacturer	Alienware
System Model	Alienware 17
System Type	x64-based PC
System SKU	Alienware 17
Processor	Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz, 2401 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Alienware A14, 9/24/2014
SMBIOS Version	2.7
Embedded Controller Version	1.01
BIOS Mode	UEFI
BaseBoard Manufacturer	Alienware
BaseBoard Product	068R5X
BaseBoard Version	A00
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume3
Locale	United States
Hardware Abstraction Layer	Version = "10.0.18362.752"
User Name	ALIENWARE17\Keith
Time Zone	Pacific Daylight Time
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	15.9 GB
Available Physical Memory	8.48 GB
Total Virtual Memory	18.9 GB
Available Virtual Memory	7.48 GB
Page File Space	3.00 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, Secure Boot
Virtualization-based security Services Configured	
Virtualization-based security Services Running	
Device Encryption Support	Reasons for failed automatic device encryption: TPM is not usable, PCR7 binding is not supported, Hardware Security Test Interface failed and device is not Modern Standby, Un-allowed DMA capable bus/device(s) detected, TPM is not usable
A hypervisor has been detected. Features required for Hyper-V will not be displayed.	

```none
[winget --info]
Windows Package Manager version
Windows: Windows.Desktop version
Package: Microsoft.DesktopAppInstaller version

winget --info
Windows Package Manager v0.1.41331 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.18363.836
Package: Microsoft.DesktopAppInstaller v1.0.41331.0
Any other software?
```

**Comment by megamorf** [comment] 2020-05-20 06:32
From my years of software deployment I remember that this error can be caused by a pending Windows reboot which prevents components that are marked for replacement to be updated by yet another installer. Can you run the following script and post its output. ([PSGallery Link](https://www.powershellgallery.com/packages/Test-PendingReboot/1.9), [Source Code](https://www.powershellgallery.com/packages/Test-PendingReboot/1.9/Content/Test-PendingReboot.ps1 ))

```powershell
Install-Script -Name Test-PendingReboot
Test-PendingReboot
```

**Comment by KevinLaMS** [comment] 2020-05-20 23:28
Duplicate of # 248.

**Comment by KevinLaMS** [comment] 2020-05-20 23:40
Duplicate of #248

**Comment by KevinLaMS** [comment] 2020-05-20 23:52
Duplicate of #248

**Closed by KevinLaMS** 2020-05-20 23:52 UTC
