### ISSUE TITLE
Allow specifying partial version number parameter

### ISSUE THREAD

**Issue by burtonrodman** [microsoft/winget-cli#1132] opened 2021-06-07 20:28 UTC
# Description of the new feature/enhancement
Allow specifying a partial version number.  For example for package Microsoft.VisualStudio.2019.Enterprise major and minor version numbers match the "public marketing" versions, but then use build numbers or something past that (like 16.9.31313.27, instead of 16.9.6).  Often I just want to upgrade to the latest patch of a specific major, or major.minor version.

# Proposed technical implementation details (optional)
Please allow specifying version like the following, matching the latest unspecified segments:
`winget install --Id Microsoft.VisualStudio.2019.Enterprise --version 16.9`

**Comment by denelon** [comment] 2021-06-07 21:19
I think you're going to want a combination of #227 and #476. I believe the combination of those makes this a duplicate request. We're also working on #1073 to address the differences between "marketing" versions and "PackageVersion".

**Comment by denelon** [comment] 2021-06-07 21:19
Duplicate of #227

**Closed by denelon** 2021-06-07 21:19 UTC
Labels: Issue-Feature
