### ISSUE TITLE
Error in "winget list .. --source .." filter

### ISSUE THREAD

**Issue by Sebastian-Cerga** [microsoft/winget-cli#1819] opened 2021-12-22 10:53 UTC
### Brief description of your issue

Source list --source option has no filtering effect.

### Steps to reproduce

Currently a command similar to:

`winget list --id Microsoft --source winget`

### Expected behavior

Should filter all packages that include word "Microsoft" in "id" and that have "source" as "winget"

### Actual behavior

Output list (which truncated, by the way - #1653) will also include packages that have source = "".

Example below:

```PS C:\> winget list --id Microsoft --source winget
>Name                          Id                            Version             Available      Source
>-----------------------------------------------------------------------------------------------------
>Microsoft Mouse and Keyboard… Microsoft.MouseandKeyboardCe… 12.181.137.0        13.250.137.0   winget
>Microsoft Visual Studio 2010… Microsoft Visual Studio 2010… 10.0.60724
>..
```

### Environment:

```shell
winget --info
Windows Package Manager v1.1.13405
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.18363.1977
Package: Microsoft.DesktopAppInstaller v1.16.13405.0
```

**Comment by denelon** [comment] 2021-12-28 18:06
Duplicate of #1155

**Closed by denelon** 2021-12-28 18:06 UTC
Labels: Needs-Triage
