### ISSUE TITLE
winget upgrade --all  > install MS C++ > fail

### ISSUE THREAD

**Issue by pleabargain** [microsoft/winget-cli#3177] opened 2023-04-23 05:54 UTC
### Brief description of your issue

run winget upgrade --all
MS c++  is installed

again

run winget upgrade --all
MS c++  is installed again

MS c++ is not being installed properly

### Steps to reproduce

run winget upgrade --all
MS c++  is installed

again

run winget upgrade --all
MS c++  is installed again

MS c++ is not being installed properly

### Expected behavior

install once

### Actual behavior

update not happening

![image](https://user-images.githubusercontent.com/640846/233822260-26204ae5-9e75-4498-b5be-ca3848fa8dc6.png)

### Environment

```shell
C:\Users\denni>winget --info
Windows Package Manager v1.3.2091
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2846
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2091.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by Trenly** [comment] 2023-04-23 12:47
Duplicate of #2995

**Closed** 2023-04-23 12:47 UTC
Labels: Needs-Triage
