### ISSUE TITLE
`winget upgrade --all` reports packages with unknown version numbers, that `--include-unknown` does not list

### ISSUE THREAD

**Issue by sba923** [microsoft/winget-cli#2929] opened 2023-02-06 19:08 UTC
### Brief description of your issue

When running `winget upgrade --all` I get something like

``
10 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.
``

But running `winget upgrade --all --include-unknown` doesn't list anything more...

### Steps to reproduce

Run `winget upgrade --all` followed by `winget upgrade --all --include-unknown`

### Expected behavior

Either no `running `package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.` message, or the second command should list the corresponding packages.

### Actual behavior

![image](https://user-images.githubusercontent.com/12860484/217061755-691bf860-54ab-4d66-aaee-f90cd99d1016.png)

### Environment

```shell
Windows Package Manager (Preview) v1.5.101-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1194
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.101.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by denelon** [comment] 2023-02-06 21:30
@sba923 this may be a case of the reported version and the installed version are unknown.

Can you run `winget list` and see how many packages show the installed version as "blank/null/unknown"?

They would also match with either the "winget" source or the "msstore" source.

**Comment by sba923** [comment] 2023-02-07 08:40
There are exactly 10 entries in `winget list`'s output with `Version == Unknown`

![image](https://user-images.githubusercontent.com/12860484/217194428-2ca2c205-cd9a-42ed-9df6-94f630c40545.png)

**Comment by denelon** [comment] 2023-02-07 17:36
Do you know how many are in the "winget" source or the "msstore" source?

**Comment by sba923** [comment] 2023-02-07 17:47
The "Source" column is empty for all 10 of them.

**Comment by florelis** [comment] 2023-02-07 19:16
I think I know what's happening. We count the number of packages with unknown installed versions too early in the process, but there are other things later that can make them not show on the table when we include packages with unknown versions. It looks like by the point we count a package with unknown version, we have not even checked if it has an available version we could install. I imagine those 10 apps have unknown version, and no available version.

**Comment by sba923** [comment] 2023-02-07 20:30
On another machine, the number is 13. All of them have `Version == Unknown`, 12 have `Source == <empty>` and one has `Source == winget`.

**Comment by denelon** [comment] 2023-02-22 17:01
* Duplicate of #2458

**Closed** 2023-02-22 17:01 UTC
Labels: Issue-Bug, Command-Upgrade

**Comment by petemount** [comment] 2023-09-19 08:59
Hello dudes, after I read this thread I don't think I'll ever use that commando extension because I don't want Winget installing crap that isn't properly registered and has no version information. Althouggh I'm highly interested if there is a command to see this crap so that I can kick it from my system. Any suggestions? I'm fairly new to the Winget at all.

**Comment by Masamune3210** [comment] 2023-09-19 15:09
If your intent is to only have programs that properly manage their registration at all times on your system, you aren't going to have that much to do on your computer.....
It's not the biggest deal in the world, the programs still work just fine and the same thing would happen even if you manually installed the program, it's not a winget-specific thing.

**Comment by GreyLine23** [comment] 2023-09-27 17:29
> I think I know what's happening. We count the number of packages with unknown installed versions too early in the process, but there are other things later that can make them not show on the table when we include packages with unknown versions. It looks like by the point we count a package with unknown version, we have not even checked if it has an available version we could install. I imagine those 10 apps have unknown version, and no available version.

Is there any fix/update for this? We have several machines that have encountered this issue, as well as other machines with the same software loaded to them that don't... It seems more hit and miss really.
