### ISSUE TITLE
 I hope that I can change the default installation location

### ISSUE THREAD

**Issue by yujiahan2018** [microsoft/winget-cli#3609] opened 2023-09-10 06:06 UTC
### Description of the new feature / enhancement

I hope to configure the json file to install the software to the specified drive through winget, and I don't want to install it to C by default

### Proposed technical implementation details

I hope to configure the json file to install the software to the specified drive through winget, and I don't want to install it to C by default

**Comment by Trenly** [comment] 2023-09-10 15:24
Duplicate of #3608

**Closed** 2023-09-10 15:24 UTC
Labels: Issue-Feature
