### ISSUE TITLE
Squirrel Installer doesn't support the option to install for all users

### ISSUE THREAD

**Issue by MehdiRtal** [microsoft/winget-cli#2286] opened 2022-06-29 11:33 UTC
### Description of the new feature / enhancement

Add --scope machine support for squirrel installer.

### Proposed technical implementation details

Instead of looking for an existing machine installer, we can instead invoke the argument --machine.
For more info: https://github.com/Squirrel/Squirrel.Windows/issues/314#issuecomment-100046849

**Comment by denelon** [comment] 2022-06-29 18:48
Duplicate of #372 

Squirrel isn't a top-level supported installer type. We've got several work items related to supporting them. It is possible to add the "--scope machine" argument to the [installer manifest](https://github.com/microsoft/winget-cli/blob/7d86189312e5f1c536d43041abc759ae708d0e81/schemas/JSON/manifests/v1.1.0/manifest.installer.1.1.0.json#L127-L132) for installers that support it.

Related Issues:
* #372 
* #418
* #1748

**Closed** 2022-06-29 18:49 UTC
Labels: Issue-Feature
