### ISSUE TITLE
Deal with packages which provide different ID for different locales

### ISSUE THREAD

**Issue by lychichem** [microsoft/winget-cli#1162] opened 2021-06-12 00:32 UTC
# Description of the new feature/enhancement
Deal with packages which provide different ID for different locales

# Proposed technical implementation details (optional)
Provide a system that can link packages with identical downloadurl (or other things, now I have no idea for other things) but will provide different ID for different locales. An example for this situation is microsoft/winget-pkgs#17085 , now `alibaba.dingtalk` will register itself as `钉钉` for Chinese users and `dingtalk` for foregin users. Maybe `youdao.youdaodict` is the same, but I've never tested it on an English machine.

**Comment by denelon** [comment] 2021-06-14 15:18
Duplicate of #1073

**Closed by denelon** 2021-06-14 15:18 UTC
Labels: Issue-Feature
