### ISSUE TITLE
 No applicable app licenses foundAt line:1

### ISSUE THREAD

**Issue by jakko10** [microsoft/winget-cli#700] opened 2021-01-13 12:08 UTC
# Brief description of the issue

```
PS C:\windows\system32> winget
Program 'winget.exe' failed to run: No applicable app licenses foundAt line:1 char:1
+ winget
+ ~~~~~~.
At line:1 char:1
+ winget
+ ~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedExceptio 
   n
    + FullyQualifiedErrorId : NativeCommandFailed
```

# Steps to reproduce

Windows version; 1809 (OS Build 17763.1637)
Via powershell:
```
Add-AppxPackage Microsoft.VCLibs.140.00.UWPDesktop_14.0.29231.0_x64__8wekyb3d8bbwe
Add-AppxPackage Microsoft.VCLibs.140.00_14.0.29231.0_x64__8wekyb3d8bbwe
Add-AppxPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle
```

# Expected behavior

When I type in winget, I should get the help.

# Actual behavior

```
Program 'winget.exe' failed to run: No applicable app licenses foundAt line:1 char:1
+ winget
+ ~~~~~~.
At line:1 char:1
+ winget
+ ~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedExceptio 
   n
    + FullyQualifiedErrorId : NativeCommandFailed
```

# Environment

```none
[winget --info]
Windows Package Manager version
Windows: Windows.Desktop version
Package: Microsoft.DesktopAppInstaller version

Any other software?
```

**Comment by denelon** [comment] 2021-01-15 18:16
@jakko10 is this computer air-gapped or is it connected to the Internet?

**Comment by jakko10** [comment] 2021-01-15 18:52
> @jakko10 is this computer air-gapped or is it connected to the Internet?

It's connected to the internet.

**Comment by matsmcp** [comment] 2021-03-16 08:52
Spun up a 2022 on my home workstation (that do have Internet access). 
On that one Windows terminal starts so on 2022 it seems to be an internet access issue.

**Comment by denelon** [comment] 2021-03-16 15:45
Thank you for letting us know. We're looking into the issue trying to determine the root cause.

**Comment by brwilkinson** [comment] 2021-03-18 05:54
Recent installs seem to work on Server 2022. Not sure if there was any change.

Will update if future installs also work.

**Comment by matsmcp** [comment] 2021-03-18 11:14
Mine has broken over night. It now says. The system cannot execute the specified program

**Comment by JohnT-MCE** [comment] 2021-04-15 14:40
Still experiencing error

**Comment by denelon** [comment] 2021-04-15 14:43
@JohnT-MCE what version of Windows are you on?
Is it a Windows Insider build?
Is it Windows server?

**Comment by JohnT-MCE** [comment] 2021-04-15 14:46
> @JohnT-MCE what version of Windows are you on?
> Is it a Windows Insider build?
> Is it Windows server?

Windows Server 2022 LTSC 21H2 (Build 20329)

**Comment by denelon** [comment] 2021-04-23 20:50
We need to provide an offline license for server 2022.

Then the command to provision the license would look similar to:

`Add-AppxProvisionedPackage -Online -PackagePath c:\Appx\myPackage.appx -DependencyPackagePath c:\Appx\dependency1\dependencyPackage.appx -LicensePath c:\Appx\myLicense.xml`

**Comment by doctordns** [comment] 2021-04-24 08:44
Why does winget need a license? What is the license for? Is licensing really an issue for developer powertoys like winget?

**Comment by scotbud123** [comment] 2021-05-28 04:28
Do we know what the solution to this is?

It's happening to me on LTSC 2019 (Windows Build Version 1809).

**Comment by tazer4** [comment] 2021-05-29 06:16
So what is Microsoft's answer to this problem?  Were supposed to have one of the most advanced and expensive versions (Enterprise LTSC) not be able to use what is most likely the greatest feature addition Windows has seen in the last 20 years?

**Comment by TheBigBear** [comment] 2021-06-05 21:43
so how does one install winget on server 2022 21H2 ltsc build 20344.1 ?

**Comment by lukasgabriel** [comment] 2021-06-07 14:23
Same here on LTSC 2019 (Windows Build Version 1809).

**Comment by jantari** [comment] 2021-07-05 12:45
In the latest release of winget (v1.0.11692 - [link here](https://github.com/microsoft/winget-cli/releases/tag/v1.0.11692)) Microsoft quietly included a license XML file. I just tried it out and was now able to install and run winget on Server 2022 Preview with:

    Add-AppxProvisionedPackage -Online -PackagePath .\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -LicensePath .\08d8788d59cf47ed9bf42c31e31f8efa_License1.xml -Verbose

After that it just worked. Just a heads up in case anyone else here initially missed this.

**Comment by djpbessems** [comment] 2021-07-05 13:47
Thanks for sharing jantari,
Probably worth noting, that the cmdlet `Add-AppxPackage` does *not* have a -LicensePath parameter, so you have to use `Add-AppxProvisionedPackage`

**Comment by kaspersmjohansen** [comment] 2021-07-05 18:30
Not working here for me. Which version of WS2022 are you using?

**Comment by djpbessems** [comment] 2021-07-06 13:35
For reference, this is the script I've used to install `winget` Windows Server 2019 myself 
(https://code.spamasaurus.com/djpbessems/Packer.Images/src/branch/Server2019/scripts/Install-WinGet.ps1):
```
#Requires -Modules 'NtObjectManager'
[CmdletBinding()]
Param(
    # None
)

# Download dependencies
$AppxDependencies = @(
    @{
        ShortName     = 'vclibs'
        QualifiedName = 'Microsoft.VCLibs.140.00_8wekyb3d8bbwe'
    },
    @{
        ShortName     = 'vclibsuwp'
        QualifiedName = 'Microsoft.VCLibs.140.00.UWPDesktop_8wekyb3d8bbwe'
    }
)
ForEach ($Dependency in $AppxDependencies) {
    $InvokeWebRequestSplat = @{
        Uri             = 'https://store.rg-adguard.net/api/GetFiles'
        Method          = 'POST'
        ContentType     = 'application/x-www-form-urlencoded'
        Body            = "type=PackageFamilyName&url=$($Dependency.QualifiedName)&ring=RP&lang=en-US"
        UseBasicParsing = $True
    }
    $InvokeWebRequestSplat = @{
        Uri     = ((Invoke-WebRequest @InvokeWebRequestSplat).Links | Where-Object {$_.OuterHTML -match '.appx' -and $_.outerHTML -match 'x64'}).href
        OutFile = "$env:temp/$($Dependency.ShortName).appx"
    }
    Invoke-WebRequest @InvokeWebRequestSplat
}
# Download latest release (along with license) from github
$InvokeRestMethodSplat = @{
    Uri    = "https://api.github.com/repos/microsoft/winget-cli/releases/latest"
    Method = 'GET'
}
$LatestRelease = Invoke-RestMethod @InvokeRestMethodSplat
$InvokeWebRequestSplat = @{
    Uri     = ($LatestRelease.assets | Where-Object {$_.name -like '*.msixbundle'}).browser_download_url
    OutFile = "$env:temp\winget.msixbundle"
}
Invoke-WebRequest @InvokeWebRequestSplat
$InvokeWebRequestSplat = @{
    Uri     = ($LatestRelease.assets | Where-Object {$_.name -like '*license*.xml'}).browser_download_url
    OutFile = "$env:temp\wingetlicense.xml"
}
Invoke-WebRequest @InvokeWebRequestSplat

# Install dependencies
$AppxDependencies.ShortName | ForEach-Object {
    $AddAppxPackageSplat = @{
        Path = "$env:temp/$($_).appx"
    }
    Add-AppxPackage @AddAppxPackageSplat
}
# Install winget
$AddAppxProvisionedPackageSplat = @{
    Online = $True
    PackagePath = "$env:temp\winget.msixbundle"
    LicensePath = "$env:temp\wingetlicense.xml"
}
Add-AppxProvisionedPackage @AddAppxProvisionedPackageSplat

# Create reparse point
$SetExecutionAliasSplat = @{
    Path        = "$([System.Environment]::SystemDirectory)\winget.exe"
    PackageName = "Microsoft.DesktopAppInstaller_8wekyb3d8bbwe"
    EntryPoint  = "Microsoft.DesktopAppInstaller_8wekyb3d8bbwe!winget"
    Target      = "$((Get-AppxPackage Microsoft.DesktopAppInstaller).InstallLocation)\AppInstallerCLI.exe"
    AppType     = 'Desktop'
    Version     = 3
}
Set-ExecutionAlias @SetExecutionAliasSplat
& explorer.exe "shell:appsFolder\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe!winget"
```

**Comment by celphogeek** [comment] 2021-08-10 21:32
I was facing this issue today, and what I do to fix was reinstall the following apps and install all Visual C++ Runtime:
Microsoft.NET.Native.Framework.2.2_2.2.29512.0_x64__8wekyb3d8bbwe.appx
Microsoft.NET.Native.Runtime.2.2_2.2.28604.0_x64__8wekyb3d8bbwe.appx
Microsoft.UI.Xaml.2.4_2.42007.9001.0_x64__8wekyb3d8bbwe.appx
Microsoft.VCLibs.140.00_14.0.30035.0_x64__8wekyb3d8bbwe.appx
Microsoft.VCLibs.140.00.UWPDesktop_14.0.30035.0_x64__8wekyb3d8bbwe.appx

The steps to follow is simple
1 - go to https://store.rg-adguard.net/
2 - Paste the link for Desktop App installer in the search box
![image](https://user-images.githubusercontent.com/29079236/128936512-1ba9b44b-53c4-46e9-8266-9419c52ae00b.png)
3 - Download the .Appx files for your system, if your system is x64 search x64 .appx file, for desktop app installer you need download .msixbundle
![image](https://user-images.githubusercontent.com/29079236/128936711-c6bdee95-5249-4fd9-bb8f-5c5499994b15.png)
4 - After download, go to powershell as admin and type Add-AppxPackage LocationOfAppxFile\Microsoft.VCLibs.140.00.UWPDesktop_14.0.30035.0_x64__8wekyb3d8bbwe.appx

example of location: 
Add-AppxPackage C:\Users\%USERPROFILE%\Downloads\Appx\Installer\Microsoft.VCLibs.140.00.UWPDesktop_14.0.30035.0_x64__8wekyb3d8bbwe.appx
Add-AppxPackage C:\Users\%USERPROFILE%\Downloads\Appx\Installer\Microsoft.DesktopAppInstaller_2021.618.1855.0_neutral_~_8wekyb3d8bbwe.msixbundle

Make sure you install VCLibs before install the package of DesktopAppInstaller.

5 - Return to https://store.rg-adguard.net/ and paste the Microsoft Store link
![image](https://user-images.githubusercontent.com/29079236/128937212-10495bc4-32d3-4c8d-9bc6-ca564b454a4f.png)
And download 
Microsoft.NET.Native.Framework.2.2_2.2.29512.0_x64__8wekyb3d8bbwe.appx
Microsoft.NET.Native.Runtime.2.2_2.2.28604.0_x64__8wekyb3d8bbwe.appx
Microsoft.UI.Xaml.2.4_2.42007.9001.0_x64__8wekyb3d8bbwe.appx
Microsoft.VCLibs.140.00_14.0.30035.0_x64__8wekyb3d8bbwe.appx

After downloaded repeat the process showed in the step 4, and them close powershell.

6 - Go to the folder you download the files and double-click all of them except desktop app installer (.msixbundle) and reinstall 
Microsoft.NET.Native.Framework.2.2_2.2.29512.0_x64__8wekyb3d8bbwe.appx
Microsoft.NET.Native.Runtime.2.2_2.2.28604.0_x64__8wekyb3d8bbwe.appx
Microsoft.UI.Xaml.2.4_2.42007.9001.0_x64__8wekyb3d8bbwe.appx
Microsoft.VCLibs.140.00_14.0.30035.0_x64__8wekyb3d8bbwe.appx
Microsoft.VCLibs.140.00.UWPDesktop_14.0.30035.0_x64__8wekyb3d8bbwe.appx

The version of the files could change with time, but the process is the same.

VCLibs.140.00 may require you close the process TextInputApp.exe to install it.

After that I close powershell and them open again and it works.
![image](https://user-images.githubusercontent.com/29079236/128937876-b5f76019-72b8-4aec-a9ee-d61e56882674.png)

**Comment by ItzLevvie** [comment] 2021-08-10 21:57
>Make sure you install VCLibs before install the package of DesktopAppInstaller.

This can be avoided by doing `Add-AppxPackage -Path <PATH_TO_MSIX> -DependencyPath <PATH_TO_APPX>` rather than having to install both of them individually.

For additional parameters, do `help Add-AppxPackage` in PowerShell.

>Microsoft.NET.Native.Framework.2.2_2.2.29512.0_x64__8wekyb3d8bbwe.appx
>Microsoft.NET.Native.Runtime.2.2_2.2.28604.0_x64__8wekyb3d8bbwe.appx
>Microsoft.UI.Xaml.2.4_2.42007.9001.0_x64__8wekyb3d8bbwe.appx
>Microsoft.VCLibs.140.00_14.0.30035.0_x64__8wekyb3d8bbwe.appx

Installing these aren't necessary for App Installer to fully work. Only the UWP Desktop version of VC Libs is the needed dependency.

**Comment by turbcool** [comment] 2021-08-20 08:07
> In the latest release of winget (v1.0.11692 - [link here](https://github.com/microsoft/winget-cli/releases/tag/v1.0.11692)) Microsoft quietly included a license XML file. I just tried it out and was now able to install and run winget on Server 2022 Preview with:
> 
> ```
> Add-AppxProvisionedPackage -Online -PackagePath .\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -LicensePath .\08d8788d59cf47ed9bf42c31e31f8efa_License1.xml -Verbose
> ```
> 
> After that it just worked. Just a heads up in case anyone else here initially missed this.

Thank you, this worked for me (Enterprise LTSC 2019)

**Comment by denelon** [comment] 2021-08-20 16:14
We are not targeting Windows server builds, but the license is included for offline installation. I missed closing this issue when it was added to the release artifacts.

**Closed by denelon** 2021-08-20 16:14 UTC
Labels: Issue-Bug

**Comment by djpbessems** [comment] 2021-08-20 20:41
> We are not targeting Windows server builds, but the license is included for offline installation. I missed closing this issue when it was added to the release artifacts.

To me that sounds like "we're trying to introduce a new tool, but we don't want it to become mainstream, so we'll only support half of our own portfolio of operating systems"

**Comment by denelon** [comment] 2021-08-20 22:37
@djpbessems that was not the intent behind my comment. 

Currently, the Windows server SKUs don't ship with the Microsoft Store client enabled. This creates challenges for updating applications delivered by the Microsoft Store. As the Windows Package Manager ships as a part of the Desktop App Installer, and that is also not generally default on server SKUs, we don't yet have a solid delivery mechanism nor an update mechanism in place today.

We have already started looking at the next evolution for the [Store For Business](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/evolving-the-microsoft-store-for-business-and-education/ba-p/2569423). The future integration with Intune is part of the story as we work towards support across our entire product portfolio.

**Comment by djpbessems** [comment] 2021-08-21 17:12
@denelon Thanks for that clarification!
Just so you know: at my current project, we'd kill for being able to use winget-cli over chocolatey during our Packer builds..., but we're staying away from it as long as we need to adopt different package managers between client and server OS builds

**Comment by doctordns** [comment] 2021-08-22 10:24
I continue to wonder why we have seen zero work on Cmdlets. 

And while Chocolately is not supported, it is probably preferable to winget. Jeffrey Snover used to say "Microsoft is not capable of sustained failure." Not sure it's true, in this case.

**Comment by Masamune3210** [comment] 2021-08-22 21:17
....I mean of course its not complete. Its not in the release build for a reason

**Comment by meiyujack** [comment] 2022-07-05 14:57
Same on LTSC 2021, but thanks~ 

> In the latest release of winget (v1.0.11692 - [link here](https://github.com/microsoft/winget-cli/releases/tag/v1.0.11692)) Microsoft quietly included a license XML file. I just tried it out and was now able to install and run winget on Server 2022 Preview with:
> 
> ```
> Add-AppxProvisionedPackage -Online -PackagePath .\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -LicensePath .\08d8788d59cf47ed9bf42c31e31f8efa_License1.xml -Verbose
> ```
> 
> After that it just worked. Just a heads up in case anyone else here initially missed this.
