### ISSUE TITLE
Winget Repair/Install does not work as system

### ISSUE THREAD

**Issue by Surawsome** [microsoft/winget-cli#4968] opened 2024-11-14 17:07 UTC
### Brief description of your issue

When attempting to run a repair-wingetpackagemanager as system context, winget is always in a good state even when it's outdated and not working. This issue has occurred as a result of the 1.9 update. Previosuly, I was using the prereq links but those stopped working so I started using a new script as part of an SCCM task sequence:
SYSTEM does not recognize -allusers

Install-PackageProvider -Name NuGet -Force | Out-Null 
Unregister-PSRepository -Name PSGallery
Register-PSRepository -Default 
Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted
Install-Module -Name Microsoft.WinGet.Client -Force -Repository PSGallery | Out-Null 
Repair-WinGetPackageManager -Force -Latest -Verbose

### Steps to reproduce

Run the script as system:
Install-PackageProvider -Name NuGet -Force | Out-Null 
Unregister-PSRepository -Name PSGallery
Register-PSRepository -Default 
Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted
Install-Module -Name Microsoft.WinGet.Client -Force -Repository PSGallery | Out-Null 
Repair-WinGetPackageManager -Force -Latest -Verbose

### Expected behavior

The required prerequisites for winget will be installed and the application will be upgraded and start working on new machines

### Actual behavior

Repair-WinGetPackageManager -Force -Latest -Verbose
VERBOSE: Creating MTA thread
VERBOSE: WinGet is in a good state.

winget upgrade
Failed in attempting to update the source: winget
Failed when searching source; results will not be included: winget
No installed package found matching input criteria.

### Environment

```shell
This issue occurs on the following OS:
2019 LTSC
2021 LTSC
2024 LTSC
W11 23H2
W11 24H2
```

**Comment by Surawsome** [comment] 2024-11-14 17:19
Previously, I was using this script that stopped working with the 1.9 update


`Invoke-WebRequest -Uri https://github.com/microsoft/winget-cli/releases/download/v1.9.25180/DesktopAppInstaller_Dependencies.zip -OutFile 'C:\Temp\DesktopAppInstaller_Dependencies.zip'
Expand-Archive 'C:\Temp\DesktopAppInstaller_Dependencies.zip' -DestinationPath 'C:\Temp\DesktopAppInstaller' -force
Invoke-WebRequest -Uri https://github.com/microsoft/winget-cli/releases/download/v1.9.25180/0a769c4da0ae4747ba4ab2f173709ced_License1.xml -OutFile 'C:\Temp\0a769c4da0ae4747ba4ab2f173709ced_License1.xml'
Invoke-WebRequest -Uri https://github.com/microsoft/winget-cli/releases/download/v1.9.25180/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -OutFile 'C:\Temp\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle'

Add-AppProvisionedPackage -Online -PackagePath 'C:\Temp\DesktopAppInstaller\x64\Microsoft.UI.Xaml.2.8_8.2310.30001.0_x64.appx' -SkipLicense
Add-AppProvisionedPackage -Online -PackagePath 'C:\Temp\DesktopAppInstaller\x64\Microsoft.VCLibs.140.00.UWPDesktop_14.0.33728.0_x64.appx' -SkipLicense
Add-AppProvisionedPackage -Online -PackagePath 'C:\Temp\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle' -LicensePath 'C:\Temp\0a769c4da0ae4747ba4ab2f173709ced_License1.xml'`

**Comment by dave-patchblox** [comment] 2024-11-14 18:00
I have seen some strange behavior lately with SYSTEM. I have no idea if this is related to your issue but it might be worth a quick shot. On one of the offending x64 machines, install the EXE version install of VC_redist_x64 (14.40.33816.0) (as administrator). Reattempt the operation that is failing in Winget.

**Comment by Surawsome** [comment] 2024-11-14 18:40
> I have seen some strange behavior lately with SYSTEM. I have no idea if this is related to your issue but it might be worth a quick shot. On one of the offending x64 machines, install the EXE version install of VC_redist_x64 (14.40.33816.0) (as administrator). Reattempt the operation that is failing in Winget.

VC 2015-2022 is already installed when the device is imaged, but I updated it to the latest version using and still same error messages

**Comment by denelon** [comment] 2024-11-14 18:44
If you are attempting to use WinGet in the system context, I'd suggest using the Microsoft.WinGet.Client PowerShell cmdlets rather than attempting to use "winget.exe".

**Comment by denelon** [comment] 2024-11-14 18:47
Duplicate of #4271

**Closed** 2024-11-14 18:47 UTC
Labels: Issue-Bug, Context-System

**Comment by Surawsome** [comment] 2024-11-14 19:01
Here is the error message when attempting to run Install-WinGetPackage Google.Chrome
![Image](https://github.com/user-attachments/assets/01ed2f31-b9d5-4fd1-9529-5d9487b6bebc)
