### ISSUE TITLE
Error Code 0x80070043: The network name cannot be found

### ISSUE THREAD

**Issue by Burkino** [microsoft/winget-cli#2885] opened 2023-01-27 03:27 UTC
### Brief description of your issue

This seems to only apply to `.exe` installers. I have 2 accounts, a User and Administrator account.  
I run `winget install/update <package>` on the User account, and if the installer is a `.exe` and requires administrator I get the "The network name cannot be found" error.  
![image](https://user-images.githubusercontent.com/24849979/215001424-6d86d778-2fca-444c-bfe7-ace6c10ae94e.png)

### Steps to reproduce

1) Create a User account, one that is not an Administrator.
2) On the User account, run `winget install ViGEm.ViGEmBus` (another example I found is `Docker.DockerDesktop`)
3) It will download an installer that is a `.exe` into `%LocalAppData%\Temp\WinGet\???`
4) A UAC prompt will popup (as expected), however after granting permission the install will error

### Expected behavior

I expect it to install the program normally, show the UAC, get permission, continue installing.

### Actual behavior

After the UAC it's showing the "The network name cannot be found" error.

I did find a temporary fix. If you give the `Administrators` group Full Control permissions on the `%LocalAppData%\Temp\WinGet` directory, and then open the `.exe` installer directly (NOT through `winget install/update`), it will continue installing normally. However this is only temporary as the next time you run `winget install/update` the permissions you set on the folder get wiped.

`Me` is the User account, not an Administrator.
![image](https://user-images.githubusercontent.com/24849979/215003445-f67d820f-3eb1-4a81-a13b-4a78477d6500.png)

### Environment

```shell
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1105
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0
```

**Comment by samiksome92** [comment] 2023-02-01 10:13
I can confirm that I have this same issue. Somehow Administrators don't have permission for winget's temp folder.

**Comment by samiksome92** [comment] 2023-02-02 12:49
@denelon Yes. Seems to be the same issue.

**Comment by boozeman** [comment] 2023-02-02 14:57
I can confirm this too.

**Comment by denelon** [comment] 2023-02-02 18:14
I'm going to close this as a Duplicate of #2740.

The issue will still be linked, but it should help make sure we get more 👍 on one issue to help raise priority.

**Closed** 2023-02-02 18:14 UTC
Labels: Issue-Bug
