### ISSUE TITLE
winget not found if connected via ssh

### ISSUE THREAD

**Issue by rseuster** [microsoft/winget-cli#1269] opened 2021-07-10 03:30 UTC
I am thrilled about winget, that seems to be the perfect tool to keep e.g. python installations uptodate ! Way to go!

I have a problem using winget remotely. I installed and enabled openssh on some Windows 10 machines, latest patches applied. I can login via remote desktop and everything is fine. Sometimes, particularly on lower bandwidth connections I prefer to login to those machines via ssh. On those connections I am not able to run winget. 

For both logins, via remote desktop and via ssh
```
where winget
```
resolves to the same location.

path seems to be identical in both cases.

What am I missing to have winget also with on ssh connections ?

puzzled, Rolf

**Comment by denelon** [comment] 2021-07-12 15:43
Duplicate of #513

**Closed** 2021-07-12 15:47 UTC
Labels: Resolution-Duplicate
