### ISSUE TITLE
winget not working

### ISSUE THREAD

**Issue by FatBastard0** [microsoft/winget-cli#4929] opened 2024-10-31 03:30 UTC
### Brief description of your issue

![Image](https://github.com/user-attachments/assets/2004ed35-c808-46ec-8fc1-2dffa8a4da95)
![Image](https://github.com/user-attachments/assets/a04d05a3-0e65-445d-aadb-a268645e1d3d)

### Steps to reproduce

what is going, I get this with all most of the time

### Expected behavior

too work right

### Actual behavior

aee abive

### Environment

WinGet 1.9

**Comment by Trenly** [comment] 2024-10-31 12:48
This looks like a bug with UniGetUI when it tries to install the WinGet Powershell Module, at least based on the screenshots

cc @marticliment

**Comment by marticliment** [comment] 2024-10-31 15:09
Yes, this issue is caused by https://github.com/marticliment/UniGetUI/issues/2814, and is not caused by WinGet.

You can close this issue.

**Closed** 2024-10-31 17:51 UTC
Labels: Area-External
