### ISSUE TITLE
Query labels each line to a numerical value

### ISSUE THREAD

**Issue by Chaython** [microsoft/winget-cli#4252] opened 2024-03-08 04:25 UTC
### Description of the new feature / enhancement

When a query/search is made for a package name, it generates a list of packages...
Rather than having to type in the whole package name or copy/paste. A number should be assigned to each line.
For example currently winget search: 
PS C:\Users\Chay> winget search "windows app"
`
Name                           Id                                 Version Source
----------------------------------------------------------------------------------
Windows App                    9N1F85V9T8BN                       Unknown msstore
Windows App Studio UWP Samples 9NBLGGH4R0W1                       Unknown msstore
LEARN WINDOWS APP EASY         9WZDNCRDC7C7                       Unknown msstore
Windows App Studio Installer   9NBLGGH4QTFX                       Unknown msstore
GoReefers Windows App          9N5ZD6TS2CP7                       Unknown msstore
Windows App Runtime            Microsoft.WindowsAppRuntime.1.4    1.4.3   winget
Windows App Runtime            Microsoft.WindowsAppRuntime.1.3    1.3.3   winget
Windows App SDK                Microsoft.WindowsAppRuntime.1.2    1.2.2   winget
Windows App SDK                Microsoft.WindowsAppRuntime.1.1    1.1.5   winget
Windows App SDK                Microsoft.WindowsAppRuntime.1.0    1.0.4   winget
Windows Application Driver     Microsoft.WindowsApplicationDriver 1.2.1.0 winget
Windows App Runtime            Microsoft.WindowsAppRuntime.1.5    1.5.0   winget
PS C:\Users\Chay> winget install microsoft.windowsappruntime.1.5
`

To install windows app runtime....

No	Name                              	Id                               	Version	Source
----------------------------------------------------------------------------------------------------------
1	Windows App                       	9N1F85V9T8BN                    	 Unknown	msstore
2	Windows App Studio UWP Samples 9NBLGGH4R0W1                   Unknown	msstore
3	LEARN WINDOWS APP EASY             9WZDNCRDC7C7                 Unknown	msstore
4	Windows App Studio Installer       	9NBLGGH4QTFX                    	Unknown	msstore
5	GoReefers Windows App              	9N5ZD6TS2CP7                    	Unknown	msstore
6	Windows App Runtime                	Microsoft.WindowsAppRuntime.1.4  	1.4.3	winget
7	Windows App Runtime                	Microsoft.WindowsAppRuntime.1.3  	1.3.3	winget
8	Windows App SDK                    	Microsoft.WindowsAppRuntime.1.2  	1.2.2	winget
9	Windows App SDK                    	Microsoft.WindowsAppRuntime.1.1  	1.1.5	winget
10	Windows App SDK                   	Microsoft.WindowsAppRuntime.1.0  	1.0.4	winget
11	Windows Application Driver         	Microsoft.WindowsApplicationDriver	1.2.1.0	winget
12	Windows App Runtime                	Microsoft.WindowsAppRuntime.1.5  	1.5.0	winget

PS C:\Users\Chay> winget install No12

**Comment by Trenly** [comment] 2024-03-08 13:34
* Duplicate of https://github.com/microsoft/winget-cli/issues/419
* Related to https://github.com/microsoft/winget-cli/issues/1620
* Related to https://github.com/microsoft/winget-cli/issues/301

**Closed** 2024-03-08 13:34 UTC
Labels: Issue-Feature
