### ISSUE TITLE
MySQL installer does not install packages

### ISSUE THREAD

**Issue by mynameismon** [microsoft/winget-cli#1326] opened 2021-07-27 05:02 UTC
# Brief description of your issue

While installing MySQL via winget, only the installer is installed, and not the packages that are supposed to accompany the installer
# Steps to reproduce
1. Run ``winget install Oracle.MySQL``
2. Navigate to the folder where the installer has been installed and run MySQLInstaller.exe

# Expected behavior
1. The installer should install normally, with the various packages installing as usual

# Actual behavior
1. The installer can not find the required packages for installation
![image](https://user-images.githubusercontent.com/42601474/127098113-0dde2715-ddb2-4f94-9425-3b36863c2088.png)

# Environment

```none
[winget --info]
Windows: Windows.Desktop v10.0.22000.100
Package: Microsoft.DesktopAppInstaller v1.15.11694.0
MySQL version: 8.0.25
```

**Comment by mynameismon** [comment] 2021-07-27 05:09
Apologies, I realised that [Winget Packages](https://github.com/microsoft/winget-pkgs) would be a better place.

**Comment by KevinLaMS** [comment] 2021-07-27 19:20
Duplicate of #https://github.com/microsoft/winget-pkgs/issues/22462

**Closed by KevinLaMS** 2021-07-27 19:20 UTC
Labels: Needs-Triage
