### ISSUE TITLE
Reportedly available upgrade to Microsoft.VC++2008Redist-x86 cannot be installed

### ISSUE THREAD

**Issue by sba923** [microsoft/winget-cli#2010] opened 2022-03-09 17:26 UTC
### Brief description of your issue

`winget upgrade` reports that an upgrade for `Microsoft.VC++2008Redist-x86` is available:

````
PS> winget upgrade | sls -raw 'Name|---|Microsoft\.VC\+\+2008Redist-x86'
Name                                            Id                           Version          Available        Source
---------------------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2008 Redistributable - x86 Microsoft.VC++2008Redist-x86 9.0.30729        9.0.30729.6161   winget
````

That upgrade cannot be installed:

````
PS❯  winget upgrade Microsoft.VC++2008Redist-x86
No applicable update found.
````

### Steps to reproduce

Attempt to upgrade `Microsoft.VC++2008Redist-x86` to version `9.0.30729.6161`when `winget` reports the installed version as `9.0.30729`.

### Expected behavior

`winget` should perform the requested upgrade, or report that the expected version is already installed.

Or: `winget upgrade` should not report an upgrade is available.

### Actual behavior

````
PS❯  winget upgrade Microsoft.VC++2008Redist-x86
No applicable update found.
````

### Environment

```shell
PS❯  winget --info
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.1526
Package: Microsoft.DesktopAppInstaller v1.17.10271.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

PS❯  Get-WindowsVersionViaWinRT.ps1

Key           Value
---           -----
OSVersionFull 10.0.19042.1526.amd64fre.vb_release.191206-1406
FlightRing    Retail
App           pwsh.exe
AppVer        7.2.1.500
DeviceFamily  Windows.Desktop
```

**Comment by denelon** [comment] 2022-03-09 18:35
Duplicate of #1413

**Closed by denelon** 2022-03-09 18:35 UTC
Labels: Needs-Triage

**Comment by sba923** [comment] 2022-03-09 18:42
I had seen #1413 and thought this was different enough, apparently I was wrong.

**Comment by denelon** [comment] 2022-03-09 18:46
@sba923 no worries. The underlying issue is about how we attempt to match "installed" programs with manifests from configured sources. We're depending on the "name" and "version" information we get out of Windows Apps & Features. In many cases, there are "side by side" versions that might either represent a "new" install or an "upgrade" for an existing package. We're doing some heavy lifting to improve the matching heuristic.

Rather than just looking at individual packages like VC++ or .NET SDKs/Runtimes, we're looking at this from a larger perspective. The goal is to address the problem in its entirety rather than trying to fix these one at a time.

**Comment by sba923** [comment] 2022-03-09 18:47
Makes total sense.
