### ISSUE TITLE
power shell

### ISSUE THREAD

**Issue by AparatixX** [microsoft/winget-cli#4579] opened 2024-06-24 21:48 UTC
### Brief description of your issue

<details><summary>Details</summary>
<p>

</p>
</details> 
```[tasklist]
### Tasks
```

**Comment by stephengillie** [comment] 2024-06-26 15:23
Hi @AparatixX,

I'm assuming this is for the WinGet PowerShell module, which includes commands such as `Find-WinGetPackage`. I'm not aware of documentation of this module, and I'm guessing this might be a request for such documentation. 

Additionally, the module's `Get-Help` sections could be more robust:

```PowerShell
PS C:\ManVal> get-help Find-WinGetPackage

NAME
    Find-WinGetPackage

SYNTAX
    Find-WinGetPackage [[-Query] <string[]>] [-Tag <string>] [-Command <string>] [-Count <uint>] [-Id <string>] [-Name <string>] [-Moniker <string>]
    [-Source <string>] [-MatchOption {Equals | EqualsCaseInsensitive | StartsWithCaseInsensitive | ContainsCaseInsensitive}] [<CommonParameters>]


ALIASES
    None


REMARKS
    None

```

**Comment by Trenly** [comment] 2024-06-26 16:31
* Duplicate of #3822

**Closed** 2024-06-26 16:31 UTC
Labels: Issue-Docs
