### ISSUE TITLE
winget upgrade by id and by name not working for Microsoft Visual C++ 2015-2019 Redistributable

### ISSUE THREAD

**Issue by winstonhong15** [microsoft/winget-cli#1658] opened 2021-10-29 02:44 UTC
### Brief description of your issue

I attempted to use `winget upgrade` feature, but it failed to match package Microsoft.VC++2015-2019Redist-x86. `winget upgrade` shows that a newer version of this package is available, but when I use the upgrade command to actually update this package, it cannot match the correct package either using the --name or --id option. 

### Steps to reproduce

Check for updates: 

`PS C:\> winget upgrade`
![image](https://user-images.githubusercontent.com/25347980/139364592-0ef10236-0520-4ca3-b3aa-0366899ed18d.png)

Try update using id:
`PS C:\> winget upgrade --id Microsoft.VC++2015-2019Redist-x86`
![image](https://user-images.githubusercontent.com/25347980/139364641-a06023e6-d19a-4f3f-8be8-5892f7bfc7a4.png)

Try update using name:
`PS C:\> winget upgrade --name "Microsoft Visual C++ 2015-2019 Redistributable (x64)"`
![image](https://user-images.githubusercontent.com/25347980/139364671-779c59fc-e9d9-48a1-98f4-5064c3a9b261.png)

Try update using exact name:
`PS C:\> winget upgrade --name -e "Microsoft Visual C++ 2015-2019 Redistributable (x64)"`
![image](https://user-images.githubusercontent.com/25347980/139364917-59bafeda-7532-4234-a3f0-496092f77049.png)

### Expected behavior

`PS C:\> winget upgrade --id Microsoft.VC++2015-2019Redist-x86` should match to exactly one package. Match by name should also work. 

### Actual behavior

![image](https://user-images.githubusercontent.com/25347980/139363754-4a4aee36-b929-47a4-996c-aba98f9e57d8.png)

### Environment

```shell
Windows Package Manager v1.1.12663
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.258
Package: Microsoft.DesktopAppInstaller v1.16.12663.0
```

**Comment by denelon** [comment] 2021-10-29 21:00
This looks like a duplicate of #1413 

The issue is in the matching logic used to compare what is installed on the machine in App & Features and any manifest available at configured sources (winget in this case). We've got some changes coming with the 1.1 schema to improve matching by adding specific Apps & Features entries.

**Comment by denelon** [comment] 2021-10-29 21:01
Duplicate of #1413

**Closed by denelon** 2021-10-29 21:01 UTC
Labels: Needs-Triage
