### ISSUE TITLE
List packages / Query if package is installed

### ISSUE THREAD

**Issue by DominicBoettger** [microsoft/winget-cli#208] opened 2020-05-19 20:10 UTC
# Description of the new feature/enhancement

It should be possible to list and query for installed packages. For scripting this can be very useful to see if a package has already been installed.

**Comment by dhrrgn** [comment] 2020-05-20 02:12
Duplicate of #119

**Comment by denelon** [comment] 2020-05-22 22:53
Duplicate of #119

**Closed** 2020-05-22 22:53 UTC
Labels: Issue-Feature
