### ISSUE TITLE
Microsoft.PowerShell matches multiple packages

### ISSUE THREAD

**Issue by AgSync-Aaron** [microsoft/winget-cli#1611] opened 2021-10-18 20:51 UTC
Disclaimer: I don't use `winget` very often and I forgot you had to speicify `--id` to install a package by id. 

It seems dangerous that when I "query" for `Microsoft.PowerShell` the package with that ID isn't listed first. In addition, why does that other software even show up? 

When the CLI defaults to query search, I think you should look for IDs first. Meaning if the query matches an ID exactly, prompt to install that package.
```
Did you mean to install the package Microsoft.PowerShell v7.1.5? [Y]es [N]o
```
If the user selects `N` then do the normal query search.

![image](https://user-images.githubusercontent.com/43680940/137803251-d9446653-2911-4432-be2b-4efd75080e06.png)

**Comment by jedieaston** [comment] 2021-10-18 23:54
Duplicate of #1523.

(There are some tips in that thread on how to work around it. hopefully it gets here soon)

**Closed as completed** 2021-10-19 14:31 UTC
