### ISSUE TITLE
Run as SYSTEM user

### ISSUE THREAD

**Issue by STG-Tanner** [microsoft/winget-cli#2490] opened 2022-09-02 13:45 UTC
### Brief description of your issue

Winget fails to run under the SYSTEM account. #548 appears to have been addressed in the 1.3 milestone, yet there is no change in behavior.

### Steps to reproduce

Attempt to execute 'winget' under the SYSTEM user

### Expected behavior

Winget should run normally under SYSTEM

### Actual behavior

Executing 'winget' returns the following:
'winget' is not recognized as an internal or external command, operable program or batch file.

![image](https://user-images.githubusercontent.com/102822322/188159517-cc77be22-adca-4ba3-8b34-739b4ee1d5f5.png)

### Environment

```shell
Windows Package Manager v1.3.2091
Windows: Windows.Desktop v10.0.22000.795
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2091.0
```

**Comment by denelon** [comment] 2022-09-02 16:49
The mechanism for running as system is being implemented as a part of the work we're doing for:

* #215 

We're publishing a NuGet package that exposes an "in proc" COM API. The winget CLI is not directly available in the system context as it is delivered via MSIX in the "App Installer" package.

COM API Specification: - [winget-cli/#888 - Com Api.md at master · microsoft/winget-cli (github.com)](https://github.com/microsoft/winget-cli/blob/master/doc/specs/%23888%20-%20Com%20Api.md)

idl: [winget-cli/PackageManager.idl at master · microsoft/winget-cli (github.com)](https://github.com/microsoft/winget-cli/blob/master/src/Microsoft.Management.Deployment/PackageManager.idl)

Duplicate of #215

**Closed** 2022-09-02 16:49 UTC
Labels: Needs-Triage

**Comment by DanHSO** [comment] 2022-09-05 09:46
Am not sure this one should have been closed.Having the ability to run Winget in the system context opens up the use of other dev tools.
