### ISSUE TITLE
Microsoft .NET SDK 6.0.412 (x64) is detected as Microsoft.DotNet.SDK.7 < 7.0.100

### ISSUE THREAD

**Issue by BrianL-STCU** [microsoft/winget-cli#3480] opened 2023-07-27 23:22 UTC
### Brief description of your issue

**Microsoft .NET SDK 6.0.412 (x64)** is incorrectly identified as `Microsoft.DotNet.SDK.7` version `< 7.0.100`, triggering an install of `Microsoft.DotNet.SDK.7` version `7.0.306` every time I run `winget upgrade --all`, which is already installed.

### Steps to reproduce

`winget upgrade --all`

### Expected behavior

The .NET 6 SDK should be detected as `Microsoft.DotNet.SDK.6` with an accurate version, or ignored.

Before installing a package version, a system check for that package should be made to avoid slowly downloading and installing a large package version that is already installed, in case multiple installations end up mapping to the same package, which has been a recurring issue for winget.

### Actual behavior

The presence of the .NET 6 SDK triggers the reinstall of the .NET 7 SDK each time `winget upgrade --all` is executed.

### Environment

```shell
Windows Package Manager (Preview) v1.5.441-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.3208
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.441.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links               
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by BrianL-STCU** [comment] 2023-07-27 23:30
I'm running in a corporate environment under an unprivileged account, entering privileged account credentials when prompted by the installer. I'm not able to run winget itself under the privileged account, because that results in this error:

```text
Failed when searching source: winget
An unexpected error occurred while executing the command:
0x8a15000f : Data required by the source is missing
```

Even getting that far under that account was a huge battle because winget doesn't have a simple installer. After trying a bunch of suggestions in #1861, I've gotten it only this far.

Under that account, `winget source list` returns:

```text
Name    Argument
-----------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
winget  https://cdn.winget.microsoft.com/cache
```

Under that account, `winget --info` returns:

```text
Windows Package Manager (Preview) v1.5.441-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.3208
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.441.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links               
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Enabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by Trenly** [comment] 2023-07-27 23:44
[Policy] Area-Matching
Duplicate of #3070

**Closed** 2023-07-27 23:44 UTC
Labels: Area-Matching
