### ISSUE TITLE
Unexpected installer title "Update ms-resource:appDisplayName"

### ISSUE THREAD

**Issue by me-and** [microsoft/winget-cli#1719] opened 2021-11-17 12:20 UTC
### Brief description of your issue

When launching the .msixbundle for pre-release v1.1.12701, the title of the window that appears is "Update ms-resource:appDisplayName"; I would expect it to be something more like "Update Windows Package Manager".

This has also been reported using the Feedback Hub as https://aka.ms/AAev6r1

### Steps to reproduce

- Not sure if relevant: get a fresh Windows 11 install, set it to the Windows Insider Dev track, and set the language to English (United Kingdom).
- Download the installer for v1.1.12701 at https://github.com/microsoft/winget-cli/releases/download/v1.1.12701/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
- Run the downloaded file

### Expected behavior

Any text displayed is suitable for user consumption

### Actual behavior

The text includes (presumably) internal-only string references: "ms-resource:appDisplayName"

### Environment

```shell
Windows Package Manager v1.1.12701
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.318
Package: Microsoft.DesktopAppInstaller v1.16.12701.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
Licence Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```
```

**Comment by me-and** [comment] 2021-11-17 12:21
This looks to be the same problem as described in #237, but that bug was apparently closed and fixed, so either this is a regression or that fix didn't fully resolve things.

**Comment by me-and** [comment] 2021-11-17 12:27
And looking a bit further down that old ticket, I can see the problem was apparently the version being upgraded _from_. So it's notable that I hit this on a brand new Windows 11 install, using the [Windows 11 Pro image in Azure](https://portal.azure.com/#create/microsoftwindowsdesktop.windows-11win11-21h2-pro). The only things I had done after creating the new VM were adding a new user account, swapping it to the Windows Insiders Dev channel, and followed the instructions to install the pre-release version of the Windows Desktop App Installer package.

**Comment by denelon** [comment] 2021-11-17 16:16
Thanks so much! I think it has to do with having an older "App Installer" as soon as you upgrade to get the one with the Windows Package Manager that problem should be resolved.  I'll confirm before I close this.

**Comment by jedieaston** [comment] 2021-11-17 16:40
Looks like it works fine once you have winget installed:

![image](https://user-images.githubusercontent.com/21368066/142243136-9947b04b-423f-4e3f-8ed9-ce8bbd1876ba.png)

**Comment by denelon** [comment] 2021-11-17 17:05
Would it be possible for you to run Get-AppxPackage Microsoft.DesktopAppInstaller on a clean instance of that image to help determine which version of the App Installer is installed? I'd like to see if we can either get the image updated, or at least add this as a note to our troubleshooting guide.

**Comment by jedieaston** [comment] 2021-11-17 17:24
This is from the Azure image:

```
PS C:\Users\easton> Get-AppxPackage Microsoft.DesktopAppInstaller


Name              : Microsoft.DesktopAppInstaller
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 1.0.42251.0
PackageFullName   : Microsoft.DesktopAppInstaller_1.0.42251.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.0.42251.0_x64__8wekyb3d8bbwe
IsFramework       : False
PackageFamilyName : Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : True
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok



PS C:\Users\easton>
```

**Comment by denelon** [comment] 2021-11-17 17:45
Awesome! Thanks.

**Comment by BentramLawrence** [comment] 2021-11-29 18:17
yuck, i'm hitting this one too, winget is just awful

**Comment by o-l-a-v** [comment] 2021-12-07 07:44
We also see Windows 11 installations with this issue. They don't seem to auto update "MIcrosoft.DesktopAppInstaller" either, stuck on ```1.0.42251.0``` for weeks, unless the user opens Microsoft Store and search for updates.

I've started playing with ways to mitigate this. So far tried following PowerShell running from Intune in system context:

```powershell
Get-CimInstance -Namespace 'Root\cimv2\mdm\dmmap' -ClassName 'MDM_EnterpriseModernAppManagement_AppManagement01' | Invoke-CimMethod -MethodName 'UpdateScanMethod'
```

Haven't confirmed it fixing the problem yet. If it doesn't, I'll look into using https://store.rg-adguard.net/ to download latest .appx of https://www.microsoft.com/en-us/store/apps/9nblggh4nns1 .

Any other ways to mitigate this? Could it/ will it be fixed with Windows Updates maybe?

**Comment by jedieaston** [comment] 2021-12-07 14:15
Yep, that'll work for now. The GitHub release can be updated by the Microsoft Store, so you shouldn't have to worry about it once you have some version of winget on the system.

**Closed** 2021-12-08 20:50 UTC
Labels: Issue-Bug, Issue-Docs, Area-External

**Comment by ecki** [comment] 2022-02-15 20:08
I have the same problem on my Windows 10. It is Enterprise issued and the AppStore is disabled. What would be the official way to update the Installer without a developer preview? Is there a enterprise download of a released version?

```
Name              : Microsoft.DesktopAppInstaller
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 1.0.30251.0
PackageFullName   : Microsoft.DesktopAppInstaller_1.0.30251.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.0.30251.0_x64__8wekyb3d8bbwe
IsFramework       : False
PackageFamilyName : Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
Dependencies      : {Microsoft.VCLibs.140.00.UWPDesktop_14.0.27629.0_x64__8wekyb3d8bbwe,
                    Microsoft.VCLibs.140.00_14.0.30035.0_x64__8wekyb3d8bbwe,
                    Microsoft.DesktopAppInstaller_1.0.30251.0_neutral_split.language-de_8wekyb3d8bbwe,
                    Microsoft.DesktopAppInstaller_1.0.30251.0_neutral_split.scale-125_8wekyb3d8bbwe}
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok
```

**Comment by jedieaston** [comment] 2022-02-16 17:16
The stable release in [GitHub Releases](https://github.com/microsoft/winget-cli/releases/latest) is the same thing you get from the Microsoft Store, if you want a different download. You'll have to manually keep it up to date though.

**Comment by karlgb** [comment] 2022-04-15 20:59
> I have the same problem on my Windows 10. It is Enterprise issued and the AppStore is disabled. What would be the official way to update the Installer without a developer preview? Is there a enterprise download of a released version?
> 
> ```
> Name              : Microsoft.DesktopAppInstaller
> Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
> Architecture      : X64
> ResourceId        :
> Version           : 1.0.30251.0
> [...]
> ```

@ecki every find a resolution to this? Thanks

**Comment by ecki** [comment] 2022-04-16 00:04
> @ecki ever find a resolution to this? Thanks

No, I did not looked much further. The release version from here is probably good enough but I could not install it because of dependency reasons, (but I also did not spent much time with it as there seems to be some commitment missing behind the whole thing)
