### ISSUE TITLE
How override argument work ?

### ISSUE THREAD

**Issue by MGMehdi** [microsoft/winget-cli#415] opened 2020-06-11 18:58 UTC
Hi, 

I don't find any information about the `override` argument. 

I tried to install vscode with winget like this `winget install vscode -i` to be able access to this window
![image](https://user-images.githubusercontent.com/48625769/84427912-e8ef8480-ac25-11ea-8e8c-4a4b536f58fe.png)
but without success. 

So I was thinking "Maybe I need to pass something to check all boxes" and I looked the manifest file but can't find something usefull

So how to find what kind of parameter I need to pass or how to use the `override` argument ?

Thanks

**Comment by denelon** [comment] 2020-06-11 20:27
Duplicate of #365

**Closed by denelon** 2020-06-11 20:27 UTC
Labels: Issue-Docs, Needs-Triage

**Comment by MGMehdi** [comment] 2020-06-12 10:08
@denelon I don't see in what my question is a duplicate. I already see this issues but it don't answer my question in the title "How override argument work ?"

**Comment by Xeevis** [comment] 2020-06-30 18:10
Since VS Code is using InnoSetup you can pass in parameters with --override instead of clicking checkboxes

> winget install Microsoft.VisualStudioCode -e --override "/verysilent /suppressmsgboxes /tasks=!runCode,desktopicon,quicklaunchicon,addcontextmenufiles,addcontextmenufolders,associatewithfiles,addtopath"

Prepending task with `!` disables it.

**Comment by MisinformedDNA** [comment] 2021-09-25 20:08
@xeevis Where did you get those parameters? Is there a command to determine what parameters are allowed for apps using InnoSetup?

**Comment by Xeevis** [comment] 2021-09-25 21:19
@MisinformedDNA

> Is there a command to determine what parameters are allowed for apps using InnoSetup?

I'm not aware of a way to extract that information from compiled installer.

> Where did you get those parameters?

Directly from the manifest in VS Code repo
https://github.com/microsoft/vscode/blob/8c6e828a8e22cef41f12b35f07a2e6e20b15847d/build/win32/code.iss#L76-L83

**Comment by denelon** [comment] 2021-09-27 15:33
@MGMehdi I missed your reply. The "--override" argument takes the string you pass in and passes that to the installer rather than any of the other switches that would have been passed for silent or silent with progress.

**Comment by andrewdbond** [comment] 2021-11-17 14:32
> Is there a command to determine what parameters are allowed for apps using InnoSetup?

A .iss file corresponding to the one that @Xeevis identified can also be directly extracted from the compiled setup app using http://innounp.sourceforge.net
