### ISSUE TITLE
‘download path setting’ or ‘winget clean’ 

### ISSUE THREAD

**Issue by ganxy1028** [microsoft/winget-cli#534] opened 2020-05-25 02:08 UTC
Will this package ~~downloader~~ manager auto clean its used installers? It seems that users who get this tool from Microsoft Store can not easily clean used installers. It will be good if a `winget clean` command is added, or it may be better that if users can set the download path, so that I will set it in my HDD instead of SSD, and I can clean used installers by myself.

**Comment by megamorf** [comment] 2020-08-11 20:38
Duplicate of #198 and #343 @denelon

**Comment by denelon** [comment] 2020-08-13 16:25
Duplicate of #198

**Closed by denelon** 2020-08-13 16:25 UTC
Labels: Needs-Triage
