### ISSUE TITLE
winget list displays multiple versions of Microsoft Teams even though only one version is installed

### ISSUE THREAD

**Issue by USMA56795** [microsoft/winget-cli#1228] opened 2021-06-28 19:59 UTC
# Brief description of your issue
`winget list "Microsoft.Teams"` displays an old version of Teams if the Microsoft Teams machine wide installer was used.
# Steps to reproduce

1. Use the [Microsoft Teams machine wide installer](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment) to install a not-current version of Teams.
2. Upgrade Teams.  Let it upgrade itself, or use `winget upgrade "Microsoft.Teams"`.
3. Run `winget list "Microsoft.Teams"`.
4. Observe that it detects two (2) distinct installations, even though only one exists.

# Expected behavior
`winget list` should detect a single instance of Microsoft Teams if only one (1) instance is installed.

# Actual behavior
`winget list` displays two instances of Microsoft Teams even if only one (1) instance is installed.

# Environment

```none
[winget --info]
Windows Package Manager version v1.0.11692
Windows: Windows.Desktop version 21H1 (OS Build 19043.1052)
Package: Microsoft.DesktopAppInstaller version 1.4.00.11161

Any other software? Nope.
```
![USMA56795_2021-06-28_195938_UTC](https://user-images.githubusercontent.com/53479999/123696624-ea3c2100-d829-11eb-902d-e9d8b188b486.png)

**Comment by miguelanjo** [comment] 2021-06-29 07:16
Similar case, some more information:
![image](https://user-images.githubusercontent.com/40229929/123753661-62eabe00-d8ba-11eb-924b-aec79bdb8cee.png)

If I try `winget install "Microsoft.Teams"` then I get an error window:
![image](https://user-images.githubusercontent.com/40229929/123753801-857cd700-d8ba-11eb-83e6-fd20d8f24066.png)

**Comment by jedieaston** [comment] 2021-06-29 23:37
This is a duplicate of microsoft/winget-pkgs#18415, [here's](https://github.com/microsoft/winget-pkgs/issues/18415#issuecomment-865930642) an explanation of the current status (basically it has to do partially with Teams managing its own updates and partially to do with the way Teams installs its machine-wide installer. hopefully the open issues for the CLI allow us to fix this).

**Comment by denelon** [comment] 2021-10-01 20:58
Duplicate of #18415

**Closed by denelon** 2021-10-01 20:58 UTC
Labels: Issue-Bug, Area-External
