### ISSUE TITLE
Some version numbers have too much info

### ISSUE THREAD

**Issue by lychichem** [microsoft/winget-cli#979] opened 2021-05-21 09:58 UTC
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue
Some version numbers listed in winget source are too long for apps really installed on end-users' machine, for example, VSCode.
# Steps to reproduce
1. Install Microsoft.VIsualStudioCode by using `winget install Microsoft.VisualStudioCode --scope machine --override '/silent /TASKS="addcontextmenufiles,addcontextmenufolders,associatewithfiles,addtopath"'`.
2. Run` winget source update` to fetch the latest winget source.
3. Run `winget upgrade` to show all updatable packages.

# Expected behavior
Microsoft.VSCode should not be listed, as it is the latest version.

# Actual behavior
Microsoft.VSCode is listed.
![image](https://user-images.githubusercontent.com/9316590/119119590-e87a8300-ba5d-11eb-9c05-b8da7d31427d.png)

# Environment
```none
[winget --info]
Windows Package Manager version: v0.4.11391
Windows: Windows.Desktop version: 19043.1021 x64 Pro zh-CN version
Package: Microsoft.DesktopAppInstaller version: 1.11.11391.0

Any other software?
```
Microsoft.VSCode

**Comment by denelon** [comment] 2021-05-21 15:01
Duplicate of #976

**Closed by denelon** 2021-05-21 15:01 UTC
