### ISSUE TITLE
Create Start Shortcut for portable apps

### ISSUE THREAD

**Issue by nicola02nb** [microsoft/winget-cli#4930] opened 2024-10-31 10:41 UTC
### Description of the new feature / enhancement

Some poratble apps may have a GUI, and it would ver usefull for users that aren't too much familiar with CLI, having a Start Menu shortcut created (Or even a desktop one..)

### Proposed technical implementation details

My Idea is to add a tag into the installer schema for only portable apps, something like `PortableCommandShortcut`, where it's value may be:

- a `string`, if `empty` (by default) no shortcuts are created, else a shortcut named like the `string` value is created
- a `boolean`, if `False` (by default) no shortcuts are created, else a shortcut named like the `PackageName` value is created

I should point out that th shortcut will be linked to the main `.exe` of the package.

And add also :

- an interactive prompt to [wingetcreate](https://github.com/microsoft/winget-create) to help with the input of this value when a portable program is detected
- Shortcut deletion when program is uninstalled

Some more options that can be implemented:

- Creating the shortcut into a Start folder name like `Publisher` value
- If the Package contains more executable(neve found one atm), add the possibility to create multiple shortcuts with different names under a folder named like the `PackageName` value

**Comment by Trenly** [comment] 2024-10-31 12:44
Duplicate of #2299

**Closed as completed** 2024-10-31 12:45 UTC
Labels: Issue-Feature, Resolution-Duplicate
