### ISSUE TITLE
Unable to install any packages due to invalid path error

### ISSUE THREAD

**Issue by kollster** [microsoft/winget-cli#480] opened 2020-07-05 20:19 UTC
# Brief description of your issue

I cannot install any package using winget. I have a theory that winget parses scandinavian special characters æ, ø and å in user profile folder name incorrectly, and therefore it is unable to find and execute the downloaded packages as it looks for the wrong path. See Actual behavior below.
# Steps to reproduce

1. Have a Windows user profile with the letter "ø" in the user profile folder name, e.g.
![image](https://user-images.githubusercontent.com/3436707/86541316-2f29c200-bf0c-11ea-87a7-20776f97137a.png)

2. Open a Windows Terminal cmd tab. 
3. Execute ```winget install Microsoft.dotnetPreview``` (or choose any other package - the behavior is the same).

# Expected behavior

I expect the package to be installed.

# Actual behavior

The package is downloaded, 
![image](https://user-images.githubusercontent.com/3436707/86541054-0acce600-bf0a-11ea-97ee-3ab2d697e0d1.png)

but winget cannot find it. It could be that it parses Scandinavian characters such as æ, ø and å in profile folder name incorrectly. See the error message below - it translates "ø" to some other characters:
![image](https://user-images.githubusercontent.com/3436707/86541041-ec66ea80-bf09-11ea-8b86-015fad108759.png)

I am able to find the downloaded package in my profile folder:
![image](https://user-images.githubusercontent.com/3436707/86541196-4b792f00-bf0b-11ea-8bfe-5f3bd9695ab8.png)

# Environment

```none
[winget --info]
Windows Package Manager v0.1.41331 Eksempel
Windows: Windows.Desktop v10.0.18363.900
Package: Microsoft.DesktopAppInstaller v1.0.41331.0
```

**Comment by megamorf** [comment] 2020-07-06 20:31
@denelon Duplicate of #181

**Comment by denelon** [comment] 2020-07-07 16:18
Duplicate of #181

**Closed by denelon** 2020-07-07 16:18 UTC
