### ISSUE TITLE
Add the ability to install or update several packages in the same command

### ISSUE THREAD

**Issue by zakaria-shahen** [microsoft/winget-cli#1811] opened 2021-12-17 10:24 UTC
### Description of the new feature / enhancement

What if I want to install/upgrade multiple packages in the same time.
To do this now, you must write a command for each package
It would be great if multiple packages were installed/upgraded in one command..

### Proposed technical implementation details

Now:
```sh
winget install --id Microsoft.WindowsTerminal;
winget install --id Microsoft.PowerShell;
winget install --id Microsoft.VisualStudioCode;
```
Feature:
```sh
winget install --id Microsoft.WindowsTerminal  Microsoft.PowerShell Microsoft.VisualStudioCode
# upgrade command
winget upgrade --id Microsoft.WindowsTerminal  Microsoft.PowerShell Microsoft.VisualStudioCode
```

**Comment by ItzLevvie** [comment] 2021-12-17 10:45
Duplicate of https://github.com/microsoft/winget-cli/issues/219

**Comment by denelon** [comment] 2021-12-20 17:34
Duplicate of #219

**Closed by denelon** 2021-12-20 17:34 UTC
Labels: Issue-Feature, Needs-Triage
