### ISSUE TITLE
App Installer crash when install application by double click Appx file.

### ISSUE THREAD

**Issue by prpjzz** [microsoft/winget-cli#5010] opened 2024-11-26 01:23 UTC
### Brief description of your issue

I have a problem installing an application manually without going through PowerShell with the Add-appxpackage command. When I run File msixbundle or appx and press Update, the application crashes immediately.

### Steps to reproduce

1. Open msixbundle file (ex: Microsoft.WindowsTerminal_1.21.3231.0_8wekyb3d8bbwe.msixbundle)
2. Click install (or Update)
3. App Installer crashes immediately.

### Expected behavior

App Installer not crash, and install return successful or error with missing dependencies.

### Actual behavior

App Installer crashes immediately.

### Environment

```shell
Windows Package Manager (Preview) v1.10.40-preview
Microsoft.DesktopAppInstaller v1.25.40.0
```

**Comment by prpjzz** [comment] 2024-11-26 01:27
This is a event viewer when App Installer crash:



> Faulting application name: AppInstaller.exe, version: 1.25.40.0, time stamp: 0x672e77ff
Faulting module name: AppInstaller.exe, version: 1.25.40.0, time stamp: 0x672e77ff
Exception code: 0x80000003
Fault offset: 0x00000000000131e5
Faulting process id: 0x1324
Faulting application start time: 0x01db3fa082275baf
Faulting application path: C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.25.40.0_x64__8wekyb3d8bbwe\AppInstaller.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.25.40.0_x64__8wekyb3d8bbwe\AppInstaller.exe
Report Id: 5bd2f9d9-aa41-42d0-8a12-11be414c8fc2
Faulting package full name: Microsoft.DesktopAppInstaller_1.25.40.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

**Comment by florelis** [comment] 2024-11-26 18:21
Could you share the App Installer logs? They are in `%LocalAppData%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\` with the name `AppInstaller-<timestamp>.log`. Before sharing, please review and remove any sensitive information that may appear in the file (most likely just usernames in file paths, or private URIs for the package)

**Comment by prpjzz** [comment] 2024-11-27 05:48
I think my OS has problem, I try to another device and not error.

But this is a App Installer log:
[AppInstaller-2024-11-27-08-38-49.085.log](https://github.com/user-attachments/files/17929681/AppInstaller-2024-11-27-08-38-49.085.log)
[AppInstaller-2024-11-27-08-38-49.209.log](https://github.com/user-attachments/files/17929679/AppInstaller-2024-11-27-08-38-49.209.log)
[AppInstaller-2024-11-27-08-38-48.778.log](https://github.com/user-attachments/files/17929680/AppInstaller-2024-11-27-08-38-48.778.log)

**Comment by denelon** [comment] 2024-11-30 18:18
There was an issue with an upstream dependency: 
* #5005

**Comment by denelon** [comment] 2024-11-30 18:19
Duplicate of #5005

**Closed** 2024-11-30 18:19 UTC
Labels: Issue-Bug, Area-External
