### ISSUE TITLE
Upgrade available but not installable

### ISSUE THREAD

**Issue by WereCatf** [microsoft/winget-cli#1476] opened 2021-09-17 05:36 UTC
# Brief description of your issue
Winget shows an item as having a newer version available, but when attempting to do an upgrade, winget fails with a complaint about no upgrades available.

# Steps to reproduce

Install older LibreOffice, attempt to upgrade it.

# Expected behavior

Well, winget is supposed to install the upgrade as usual.

# Actual behavior

Winget currently shows e.g. LibreOffice 7.1.5.2 as having been installed and 7.2.0.4 being the latest version, but issuing 'winget upgrade libreoffice' or 'winget upgrade libreoffice.libreoffice' only comes back with a complaint that no upgrades are available. You have to uninstall LibreOffice, then install it again in order to get the latest version.

I have stumbled upon other ones that show the same issue as well, but I can't remember what they were off the top of my head, so, for now, I am only referring to LibreOffice.

# Environment

Windows Package Manager v1.0.12576 (not really relevant, since this applies to earlier versions as well)
Windows: Windows.Desktop v10.0.19042.1237
Package: Microsoft.DesktopAppInstaller v1.16.12576.0

**Comment by jedieaston** [comment] 2021-09-17 13:21
This will hopefully? be fixed with WinGet 1.1. It's due to the first issue in [this list](https://github.com/microsoft/winget-cli/issues/752#issuecomment-915632239).

**Comment by denelon** [comment] 2021-09-17 14:13
Duplicate of #752 

We've started work on the new v1.1 schema. There are a few steps and some sequencing involved, but the work is in progress. The problem is usually one of different installer tech, or matching with the installed package in Apps & Features.

**Closed by denelon** 2021-09-17 14:13 UTC
Labels: Needs-Triage
