### ISSUE TITLE
Provide ability to use multiple internal manifest for closed networks

### ISSUE THREAD

**Issue by binarylandscapes** [microsoft/winget-cli#404] opened 2020-06-05 22:10 UTC
# Provide the ability to add additional connections to manifests for internal enterprise apps as well as creating an internal manifest for apps copied to offline networks from internet.

* Use Case 1: A company develops and produces windows applications not for public use but internal or customer only but infrastructure teams wishes to deploy the app internally on corporate network with winget-cli along side public apps from internet.

* Use Case 2: Closed networks or classified systems have no external connections to internet but wish to use winget-cli method for installation of internet based apps or internally developed possibly classified applications

# Being able to add connections to additional git repositories and being able to add them individually based on branch name for development and automation. Unknown if there is another format that could be loaded into binary repositories like JFrog Artifactory or something. But the over goal would be similar to docker setup. You can create your own internal docker manifests and just add the connection along side public manifests from docker and rhel.

**Comment by megamorf** [comment] 2020-06-07 21:17
Duplicate of:
* #160 
* #203
* #213
* #226

**Comment by denelon** [comment] 2020-06-11 20:32
Duplicate of #213

**Closed by denelon** 2020-06-11 20:32 UTC
Labels: Issue-Feature, Needs-Triage
