### ISSUE TITLE
Support non-installer .exe (Direct download or via Pwsh script)

### ISSUE THREAD

**Issue by MichelDiz** [microsoft/winget-cli#298] opened 2020-05-22 17:31 UTC
# Description of the new feature/enhancement

Some companies maintain windows binaries without an installation package. But perfectly valid. I would like to be able to use Winget to install such a package without the need to create a .msi or similar. (which would make the process more complex and difficult to maintain)

Something like Homebrew. But focusing on the Windows context.

# Proposed technical implementation details (optional)

e.g:
> OBS. Windows, today, has native support for TAR.

### Via YAML

```YAML
Id: Dgraph-io.Dgraph
Publisher: Dgraph Labs Inc.
Name: Dgraph
Description: Fast, Distributed Graph DB.
Version: 20.03.0
Homepage: https://dgraph.io
Tags: Go,Graph,DB
License: Apache 2.0
LicenseUrl: https://raw.githubusercontent.com/dgraph-io/dgraph/master/licenses/DCL.txt
InstallerType: gz # enumeration of supported installer types (exe, msi, msix, zip, tar, gz, ps1)
Installers:
  - Arch: x64 # enumeration of supported architectures
    URL: https://github.com/dgraph-io/dgraph/releases/download/v20.03.0/dgraph-windows-amd64.tar.gz
    Sha256: string # SHA256 calculated from installer
    InstallerType: manual
    pathToInstall: "%SystemDrive%\program files\dgraph-io\"
# ManifestVersion: 0.1.0
```

### Via PS1

```YAML
InstallerType: ps1 # enumeration of supported installer types (exe, msi, msix, zip, tar, gz, ps1)
Installers:
  - Arch: x64 # enumeration of supported architectures
    URL: https://raw.githubusercontent.com/dgraph-io/install-scripts/master/install.ps1
    Sha256: string # SHA256 would be calculated in a TMP path with the downloaded .exe via install.ps1
# ManifestVersion: 0.1.0
```

**Comment by koppor** [comment] 2020-05-24 13:06
Seems to be a refinement of https://github.com/microsoft/winget-cli/issues/182.

Strongly related: 

- https://github.com/microsoft/winget-cli/issues/194 (which just asks for support of downloading `.exe` files and copying it to some directory reachable from the `PATH`).
- https://github.com/microsoft/winget-cli/issues/140 (which asks for some unzipping. The discussion is interesting)
- https://github.com/microsoft/winget-pkgs/issues/174 (which asks for zip files)
- https://github.com/microsoft/winget-cli/issues/182 (asks for support of portable apps; which are typically contained in a .zip archive)

**Comment by denelon** [comment] 2021-08-06 16:52
@MichelDiz this looks like a Duplicate of #182. We do plan to support portable/standalone applications and .zip in a similar manner. The intent would be to have the Windows Package Manager generate entries in Apps & Features so we can make sure the path is maintained, and we can perform upgrades.

**Closed by denelon** 2021-08-06 16:52 UTC
Labels: Issue-Feature
