### ISSUE TITLE
Winget Defaultstate folders under user profiles does not have admin or system permission. cannot be deleted with user profile deletion 

### ISSUE THREAD

**Issue by selimfelex** [microsoft/winget-cli#3365] opened 2023-06-20 09:20 UTC
### Brief description of your issue

user profiles aren't being deleted properly from sysdm.cpl or when trying to manually delete the user profiles within the C:\Users directory   when the machine has Winget installed and enrolled via Intune to install software.
The following folder path remains following profile deletion due to permissions which prevents the top level user profile folder from being removed:
 
C:\Users\%username%\appdata\local\microsoft\winget\state\defaultstate
 the permissions on the winget defaultstate folder are meant to be set without the local administrators group or system access rights
ssue happens only when winget is installed and used to install apps via intune (when the machine is enrolled into intune and has some software to be installed via new store in intune )
then we have these folders which has admin and system permission on top of it 

![AdminSystemPermission](https://github.com/microsoft/winget-cli/assets/40806184/81cf5903-3b37-4e1d-b9b8-91d32afeae4c)

 
but if we go one level deeper in the folders we can see that only the current user has permission (no system or admin permission ) so that those folders remain when user tried to delete profile and causing new folder for profile when the user logs in again ending up filling the c:\users folders with a lot of repeated names and numbers because the winget folder cannot be deleted  by admin as he do not have permission on it 

![UserPermission2](https://github.com/microsoft/winget-cli/assets/40806184/e8a8be70-cad2-40db-9c0a-c8ae4f4976fc)

 Parent folder has a system and administrator full control but it is not reflected to the inside folder.

### Steps to reproduce

1) Enroll a Windows 10 21H2 device into Intune.
2) Assign an application from the New Store to a test user, this will force WinGet to install to allow the app you've assigned to be downloaded and installed once you've logged in with the test user.
3) Logon with the test user that has the app assigned to them and ensure the app has been downloaded and installed.
5) these folders and files  will be created 
C:\Users\%username%\AppData\Local\Microsoft\WinGet\Settings\defaultState\sources_metadata
C:\Users\%username%AppData\Local\Microsoft\WinGet\State\defaultState\StoreEdgeFD\installed.db
if we check the permissions on Default state folders , we will find only the current user has permission , no system or administrator permissions 
files are attached below

4) Logon with another account and attempt to delete the profile of the test account from system properties. The test account profile folder (C\Users\testuser) should remain with the WinGet folder within.

[WinGet.zip](https://github.com/microsoft/winget-cli/files/11798207/WinGet.zip)

### Expected behavior

these folders named Defaultstate under winget folder should have a system and administrator permission so it can be deleted if we need to delete the profiles and clean up the C:\users  folder

### Actual behavior

the profile gets deleted from the system however the the user profile folder under c:\users still exist and cannot be deleted because   wingt defaultstate folders still resides on it and cannot be deleted because of admin and system permissions missing , to delete them we need to set the permission manually to take ownership then delete profile 

### Environment

```shell
windows 10 21H2
Version of App Installer is 1.19.10173.0
Installed version of Winget v1.4.10173
```

**Comment by Sabster** [comment] 2023-06-23 17:29
We have run into this same issue - using delprof.exe; we did find a sort of workaround using a script that changes the WinGet folder and allows us to delete it (this was working with US Cloud)

**Comment by GuillaumeLaquerriere** [comment] 2023-06-27 22:46
Also experiencing the same issue.

Windows 10 21H2 v10.0.19044.3086
Winget v1.4.11071
Package v1.19.11071.0

**Comment by MarkMae** [comment] 2023-06-28 05:27
...and here the same one too.

Windows 10 Enterprise 21H2 (10.0.19041.3086)
 Winget v1.4.11071

**Comment by selimfelex** [comment] 2023-07-13 16:04
I have checked the version.
![image](https://github.com/microsoft/winget-cli/assets/40806184/c009c27b-fad4-48a6-a972-e1c8f0157c45)
however i can see the same files and folders still has no admin or system permission , do  i need to uninstall then install

**Comment by 7ep3s** [comment] 2023-07-14 09:28
I'm using this to fix the ACLs on my machines

`$ACL_error_state = $true
function fix-WingetACL{

    $Error.Clear()
    $ErrorActionPreference = "SilentlyContinue"
    $SYSTEM = ([wmi]"win32_SID.SID='S-1-5-18'").referenceddomainname + "\" +([wmi]"win32_SID.SID='S-1-5-18'").accountname
    $ADMINISTRATORS = ([wmi]"win32_SID.SID='S-1-5-32-544'").referenceddomainname + "\" +([wmi]"win32_SID.SID='S-1-5-32-544'").accountname
    $paths = get-childitem "C:\users\*\appdata\local\microsoft\winget" -Recurse | select -ExpandProperty fullname

    ForEach ($path in $paths) {

        $Acl = Get-Acl $path

        $Ar_system = New-Object System.Security.AccessControl.FileSystemAccessRule($SYSTEM, "FullControl", "Allow")
        $Ar_administrators = New-Object System.Security.AccessControl.FileSystemAccessRule($ADMINISTRATORS, "FullControl", "Allow")

        $Acl.AddAccessRule($Ar_system)
        $Acl.AddAccessRule($Ar_administrators)

        #Write-Host $path

        Set-Acl -Path $path -AclObject $Acl

    }

    if($error) {return $true} else {return $false}
}

while ($ACL_error_state) {

    $ACL_error_state = fix-WingetACL
}`

**Comment by 7ep3s** [comment] 2023-07-14 10:10
Can confirm I'm on 1.5.1572 and the ACLs were still incorrect.
Simple to remediate with a script.

https://gist.github.com/7ep3s/94c8f0e98769e0af5dca75ac53262158

**Comment by denelon** [comment] 2023-07-19 15:33
Thanks for confirming this is still a bug.

**Comment by Smith-Rick** [comment] 2023-09-05 20:44
This is still a bug for us as well

**Comment by yao-msft** [comment] 2023-09-05 21:17
> This is still a bug for us as well

This is fixed from winget side, the fix is scheduled to be released with winget v1.6. But Intune uses a copy of winget binaries, intune teams needs to update their copy and push out a new client release to truly fix the issue. The issue is closed automatically by github when linked pr is merged, I'll reopen the issue for tracking purpose.

**Comment by IntuneAdmin** [comment] 2023-09-07 06:43
@7ep3s 

Should this script hook work if you haven't explicitly installed WINGET but are using it with an Intune deploy from the Windows Store (new)? App deployment.

We ran your script but it doesn't work for us in this situation.

**Comment by IntuneAdmin** [comment] 2023-09-07 06:44
> intune remediation package scripts for those who are still looking for a way to address this in their env while the bug is fixed https://github.com/7ep3s/IntuneRemediationScripts/tree/main/WingetACLRemediation

Should this script hook work if you haven't explicitly installed WINGET but are using it with an Intune deploy from the Windows Store (new)? App deployment.

We ran your script but it doesn't work for us in this situation.

**Comment by 7ep3s** [comment] 2023-09-07 08:22
> > intune remediation package scripts for those who are still looking for a way to address this in their env while the bug is fixed https://github.com/7ep3s/IntuneRemediationScripts/tree/main/WingetACLRemediation
> 
> Should this script work if you haven't explicitly installed WINGET but are using it with an Intune deploy from the Windows Store (new)? App deployment.
> 
> We ran your script but it doesn't work for us in this situation.

Thank you for the feedback.
That is interesting. 
We don't install Winget separately and we use the new package manager integration for our Intune windows app deployments. We have not had (or at least I haven't heard of) any issues with profile deletes due to permissions since I rolled this out.
Maybe it's time I look at the related device status report. :)

**Comment by Smith-Rick** [comment] 2023-09-18 14:45
> > This is still a bug for us as well
> 
> This is fixed from winget side, the fix is scheduled to be released with winget v1.6. But Intune uses a copy of winget binaries, intune teams needs to update their copy and push out a new client release to truly fix the issue. The issue is closed automatically by github when linked pr is merged, I'll reopen the issue for tracking purpose.

Does the InTune team have an ETA for when they will have fixed their end? We have several thousand shared devices at our hospital with the GPO for Windows to clean up old local profiles. This GPO is trying to do its job, but then Windows can't clean up the device and we run into issues. It would be good if we could go back to the various support teams and give them an ETA on a permanenet fix.

**Comment by IntuneAdmin** [comment] 2023-09-19 07:17
> > > This is still a bug for us as well
> > 
> > 
> > This is fixed from winget side, the fix is scheduled to be released with winget v1.6. But Intune uses a copy of winget binaries, intune teams needs to update their copy and push out a new client release to truly fix the issue. The issue is closed automatically by github when linked pr is merged, I'll reopen the issue for tracking purpose.
> 
> Does the InTune team have an ETA for when they will have fixed their end? We have several thousand shared devices at our hospital with the GPO for Windows to clean up old local profiles. This GPO is trying to do its job, but then Windows can't clean up the device and we run into issues. It would be good if we could go back to the various support teams and give them an ETA on a permanenet fix.

Have you rolled out the remediation scripts from [7ep3s](https://github.com/7ep3s)?

**Comment by 7ep3s** [comment] 2023-09-19 10:42
> > > > This is still a bug for us as well
> > > 
> > > 
> > > This is fixed from winget side, the fix is scheduled to be released with winget v1.6. But Intune uses a copy of winget binaries, intune teams needs to update their copy and push out a new client release to truly fix the issue. The issue is closed automatically by github when linked pr is merged, I'll reopen the issue for tracking purpose.
> > 
> > 
> > Does the InTune team have an ETA for when they will have fixed their end? We have several thousand shared devices at our hospital with the GPO for Windows to clean up old local profiles. This GPO is trying to do its job, but then Windows can't clean up the device and we run into issues. It would be good if we could go back to the various support teams and give them an ETA on a permanenet fix.
> 
> Have you rolled out the remediation scripts from [7ep3s](https://github.com/7ep3s)?

did you figure out why they were not working for you?

**Comment by IntuneAdmin** [comment] 2023-09-19 18:04
> > > > > This is still a bug for us as well
> > > > 
> > > > 
> > > > This is fixed from winget side, the fix is scheduled to be released with winget v1.6. But Intune uses a copy of winget binaries, intune teams needs to update their copy and push out a new client release to truly fix the issue. The issue is closed automatically by github when linked pr is merged, I'll reopen the issue for tracking purpose.
> > > 
> > > 
> > > Does the InTune team have an ETA for when they will have fixed their end? We have several thousand shared devices at our hospital with the GPO for Windows to clean up old local profiles. This GPO is trying to do its job, but then Windows can't clean up the device and we run into issues. It would be good if we could go back to the various support teams and give them an ETA on a permanenet fix.
> > 
> > 
> > Have you rolled out the remediation scripts from [7ep3s](https://github.com/7ep3s)?
> 
> did you figure out why they were not working for you?

Yes, this was user error, manually running the script did not go well. Everything works fine via your detect and remediation script.

What we are still encountering is that TEMP profiles have sometimes been created. I also detect and remove this with a detect and remediation script (I can share this tomorrow)

The only problem I still have because of these issues is that the Intune prolicy that throws away the user profiles does this after 30 days from the "Win32_UserProfile" but the user profile folder remains.

I can delete this by running a detect and remediation script which deletes the C:\user folder older than 30 days, but here there is a good chance that I will also delete folders where the Win32_UserProfile still exists if the remediation script is earlier than the shared profile delete. from Intune. Unfortunately I don't have a good solution for this yet.

any good idea for this?

**Comment by 7ep3s** [comment] 2023-09-19 18:14
> The only problem I still have because of these issues is that the Intune prolicy that throws away the user profiles does this after 30 days from the "Win32_UserProfile" but the old user profile folder remains. (before the ACL rights are set correctly So)

in my experience this can happen if there are locks on some files that are within the profile folder.
we have the same problem, probably because of the plethora of security agents running on our workstations.
setting up some housekeeping scheduled task that runs on boot or user logon might help with this issue.

I have a quite effective solution that can nuke stale profiles but not sure about temp profile folders.
I can publish it tomorrow after sanitizing it.

**Comment by IntuneAdmin** [comment] 2023-09-19 18:33
that would be great!

**Comment by IntuneAdmin** [comment] 2023-09-19 18:33
> > The only problem I still have because of these issues is that the Intune prolicy that throws away the user profiles does this after 30 days from the "Win32_UserProfile" but the old user profile folder remains. (before the ACL rights are set correctly So)
> 
> in my experience this can happen if there are locks on some files that are within the profile folder. we have the same problem, probably because of the plethora of security agents running on our workstations. setting up some housekeeping scheduled task that runs on boot or user logon might help with this issue.
> 
> I have a quite effective solution that can nuke stale profiles but not sure about temp profile folders. I can publish it tomorrow after sanitizing it.

That would be great!

**Comment by 7ep3s** [comment] 2023-09-20 15:51
> > > The only problem I still have because of these issues is that the Intune prolicy that throws away the user profiles does this after 30 days from the "Win32_UserProfile" but the old user profile folder remains. (before the ACL rights are set correctly So)
> > 
> > 
> > in my experience this can happen if there are locks on some files that are within the profile folder. we have the same problem, probably because of the plethora of security agents running on our workstations. setting up some housekeeping scheduled task that runs on boot or user logon might help with this issue.
> > I have a quite effective solution that can nuke stale profiles but not sure about temp profile folders. I can publish it tomorrow after sanitizing it.
> 
> That would be great!

https://github.com/7ep3s/SCCM_Intune_PowerShell/tree/main/StaleUserProfileRemover

**Comment by selimfelex** [comment] 2023-10-03 08:04
> This is fixed from winget side, the fix is scheduled to be released with winget v1.6. But Intune uses a copy of winget binaries, intune teams needs to update their copy and push out a new client release to truly fix the issue

Hello @IntuneAdmin , do we have an update for the issue

**Comment by IntuneAdmin** [comment] 2023-10-03 08:16
> > This is fixed from winget side, the fix is scheduled to be released with winget v1.6. But Intune uses a copy of winget binaries, intune teams needs to update their copy and push out a new client release to truly fix the issue
> 
> Hello @IntuneAdmin , do we have an update for the issue

Where do you get the information that it has been fixed?
I don't have an update, I'm a "user" IntuneAdmin is just my nickname. I have no influence on the process at Microsoft / WinGet 😬

**Comment by selimfelex** [comment] 2023-10-03 08:52
hello @IntuneAdmin  , this info was mentioned by @yao-msft on his update , so i thought you are the official Intune as you were replying to the thread , so Dear @yao-msft do we have any update from Intune team

**Comment by yao-msft** [comment] 2023-10-03 23:48
We will release a new winget library after our winget 1.6 stable release is out (probably in 1-2 weeks). After that I'll ask intune to take in the new library (not sure how long that'll take to end customer delivery). But I'll report back when I have rough dates. Thanks.

**Comment by IntuneAdmin** [comment] 2023-10-24 19:12
> We will release a new winget library after our winget 1.6 stable release is out (probably in 1-2 weeks). After that I'll ask intune to take in the new library (not sure how long that'll take to end customer delivery). But I'll report back when I have rough dates. Thanks.

Any update?

**Comment by yao-msft** [comment] 2023-10-24 19:39
Intune team has taken the winget 1.6 library update. It should be in next Intune client update.

**Comment by IntuneAdmin** [comment] 2023-10-24 19:54
> Intune team has taken the winget 1.6 library update. It should be in next Intune client update.

Nice! Do you know when the next Intune client update is?

**Comment by selimfelex** [comment] 2023-11-02 13:30
Hello @yao-msft , thanks for the update , do you have any update from Intune team

**Comment by denelon** [comment] 2023-11-02 16:14
@RDMacLachlan do you by chance have any idea when this might roll out?

**Closed** 2023-11-02 16:13 UTC
Labels: In-PR, Issue-Bug

**Comment by selimfelex** [comment] 2023-11-26 13:52
Hello @denelon @RDMacLachlan  , is there any update regarding the Intune Team rollout

**Comment by IntuneAdmin** [comment] 2023-11-27 07:55
> Hello @denelon @RDMacLachlan , is there any update regarding the Intune Team rollout!

The Intune Support Team told me that Winget 1.6 is released in the Intune 2311 update “last week”

**Comment by NekoJonez** [comment] 2023-11-28 09:21
I'm still experiencing this issue on my endpoint joined devices. I'm running winget v1.6.3133. 
On shared devices, I can't deleted all the user accounts to create space on the hard drive because of this. Me and my coworker have to go to the advanced security settings and change the owner of the folder to "DEVICE\Administrators" and check both boxes  (So, the subfolders & files are included) before we can actually remove the folders.

Is there something I'm missing?

**Comment by 7ep3s** [comment] 2023-11-28 10:20
> I'm still experiencing this issue on my endpoint joined devices. I'm running winget v1.6.3133. On shared devices, I can't deleted all the user accounts to create space on the hard drive because of this. Me and my coworker have to go to the advanced security settings and change the owner of the folder to "DEVICE\Administrators" and check both boxes (So, the subfolders & files are included) before we can actually remove the folders.
> 
> Is there something I'm missing?
> 
> @yao-msft

try my remediation package https://github.com/microsoft/winget-cli/issues/3365#issuecomment-1708304778

**Comment by NekoJonez** [comment] 2023-11-28 10:23
> > I'm still experiencing this issue on my endpoint joined devices. I'm running winget v1.6.3133. On shared devices, I can't deleted all the user accounts to create space on the hard drive because of this. Me and my coworker have to go to the advanced security settings and change the owner of the folder to "DEVICE\Administrators" and check both boxes (So, the subfolders & files are included) before we can actually remove the folders.
> > Is there something I'm missing?
> > @yao-msft
> 
> try my remediation package [#3365 (comment)](https://github.com/microsoft/winget-cli/issues/3365#issuecomment-1708304778)

And how does that work? Do I need to run that on the computers with problems? Which one of the two scripts? 
So, updating to the latest version of WinGet won't work?

**Comment by 7ep3s** [comment] 2023-11-28 10:45
> > > I'm still experiencing this issue on my endpoint joined devices. I'm running winget v1.6.3133. On shared devices, I can't deleted all the user accounts to create space on the hard drive because of this. Me and my coworker have to go to the advanced security settings and change the owner of the folder to "DEVICE\Administrators" and check both boxes (So, the subfolders & files are included) before we can actually remove the folders.
> > > Is there something I'm missing?
> > > @yao-msft
> > 
> > 
> > try my remediation package [#3365 (comment)](https://github.com/microsoft/winget-cli/issues/3365#issuecomment-1708304778)
> 
> And how does that work? Do I need to run that on the computers with problems? Which one of the two scripts? So, updating to the latest version of WinGet won't work?

https://learn.microsoft.com/en-us/mem/intune/fundamentals/remediations

or use it as sccm configuration baseline, in that case might need to change the exit code output in the detection script to return $true or $false

**Comment by jbuettner00** [comment] 2023-11-28 19:29
> > > > I'm still experiencing this issue on my endpoint joined devices. I'm running winget v1.6.3133. On shared devices, I can't deleted all the user accounts to create space on the hard drive because of this. Me and my coworker have to go to the advanced security settings and change the owner of the folder to "DEVICE\Administrators" and check both boxes (So, the subfolders & files are included) before we can actually remove the folders.
> > > > Is there something I'm missing?
> > > > @yao-msft
> > > 
> > > 
> > > try my remediation package [#3365 (comment)](https://github.com/microsoft/winget-cli/issues/3365#issuecomment-1708304778)
> > 
> > 
> > And how does that work? Do I need to run that on the computers with problems? Which one of the two scripts? So, updating to the latest version of WinGet won't work?
> 
> https://learn.microsoft.com/en-us/mem/intune/fundamentals/remediations
> 
> or use it as sccm configuration baseline, in that case might need to change the exit code output in the detection script to return $true or $false
> 
> EDIT: idk if winget updating to latest version fixes the ACLs, or having the latest version from ground zero just means you won't have ACL issues with the state folder on the new builds but I do know that since I implemented that script package in our env when the bug was originally discovered, we have no problem purging user profiles.

We are also still have this problem after updating winget to v1.6. I would say that this is not truly fixed if we have to continue to run the remediation scripts.

**Comment by yao-msft** [comment] 2023-11-28 20:46
This is not fixed by just updating to latest winget v1.6. Intune takes a copy of winget code and distribute with Intune client update. It's only fixed after Intune releases a new client update, which is in about 1 month last I heard.

**Comment by jbuettner00** [comment] 2023-11-28 20:51
> > Hello @denelon @RDMacLachlan , is there any update regarding the Intune Team rollout!
> 
> The Intune Support Team told me that Winget 1.6 is released in the Intune 2311 update “last week”

And according to this I thought the update was in the Winget 1.6 release last week.
![image](https://github.com/microsoft/winget-cli/assets/58002498/c34639f7-6446-4221-bdda-1113e7824f6e)
Is this not the 2311 update?

**Comment by NekoJonez** [comment] 2023-11-28 21:00
> This is not fixed by just updating to latest winget v1.6 package. Intune takes a copy of winget code and distribute with Intune client update. It's only fixed after Intune releases a new client update. @IntuneAdmin mentioned the Intune support team says it's released with Intune 2311 last week. Please let us know if the issue still exists after updating to Intune 2311 client.

How does one check/update that version?

**Comment by yao-msft** [comment] 2023-11-28 21:03
The winget dlls (for intune consumption) are under "C:\Program Files (x86)\Microsoft Intune Management Extension". Checking the version of Microsoft.Management.Deployment.InProc.dll should be sufficient.

**Comment by NekoJonez** [comment] 2023-11-28 21:04
> The winget dlls (for intune consumption) are under "C:\Program Files (x86)\Microsoft Intune Management Extension". Checking the version of Microsoft.Management.Deployment.InProc.dll should be sufficient.

And how does one update or does that go automatically?

**Comment by yao-msft** [comment] 2023-11-28 21:07
Sorry I'm not an expert on Intune client distribution but it should be updated automatically.

**Comment by NekoJonez** [comment] 2023-11-28 21:09
Excellent. So if it is still an issue under the latest version, so I ask to reopen this issue or create my own?

**Comment by yao-msft** [comment] 2023-11-28 21:11
By the way, the winget code (for Intune) should have been invoked at least once (like installing some app through Intune, etc) to take effect. If it does not work, please reopen the issue. Thanks.

**Comment by jbuettner00** [comment] 2023-11-28 21:12
> The winget dlls (for intune consumption) are under "C:\Program Files (x86)\Microsoft Intune Management Extension". Checking the version of Microsoft.Management.Deployment.InProc.dll should be sufficient.

![image](https://github.com/microsoft/winget-cli/assets/58002498/616dbf2f-255c-4cc2-a79d-9c3331890448)

Looks like this has not updated yet then.

**Comment by 7ep3s** [comment] 2023-11-29 09:48
> > This is not fixed by just updating to latest winget v1.6 package. Intune takes a copy of winget code and distribute with Intune client update. It's only fixed after Intune releases a new client update. @IntuneAdmin mentioned the Intune support team says it's released with Intune 2311 last week. Please let us know if the issue still exists after updating to Intune 2311 client.
> 
> How does one check/update that version?

I think once your MS Tenant has Intune release 2311, your clients will update automatically, not aware of any way to force that. You can check your service release in Intune/Tenant Administration.

**Comment by NekoJonez** [comment] 2023-11-29 12:09
> Sorry I'm not an expert on Intune client distribution but it should be updated automatically.

Currently running 2304. My tennant is running 2311, is there a way to force an update so I can test if the fix works? Since, it's getting really annoying & time consuming.

**Comment by 7ep3s** [comment] 2023-11-29 13:00
> > Sorry I'm not an expert on Intune client distribution but it should be updated automatically.
> 
> Currently running 2304. My tennant is running 2311, is there a way to force an update so I can test if the fix works? Since, it's getting really annoying & time consuming.

realistically I think the only thing you can do is ask your MS rep when your tenant will get 2311

**Comment by 7ep3s** [comment] 2023-11-29 13:02
> > Sorry I'm not an expert on Intune client distribution but it should be updated automatically.
> 
> Currently running 2304. My tennant is running 2311, is there a way to force an update so I can test if the fix works? Since, it's getting really annoying & time consuming.

try this https://www.reddit.com/r/Intune/comments/108zlx3/intune_management_extension_not_updating/

**Comment by jbuettner00** [comment] 2023-11-29 15:05
> > > Sorry I'm not an expert on Intune client distribution but it should be updated automatically.
> > 
> > 
> > Currently running 2304. My tennant is running 2311, is there a way to force an update so I can test if the fix works? Since, it's getting really annoying & time consuming.
> 
> try this https://www.reddit.com/r/Intune/comments/108zlx3/intune_management_extension_not_updating/

Ok tried that, here is the link I used: https://naprodimedatapri.azureedge.net/IntuneWindowsAgent.msi

Now the version of Microsoft.Management.Deployment.InProc.dll is updated to this:
![image](https://github.com/microsoft/winget-cli/assets/58002498/56595936-4cd4-4465-9893-dfcf3435afcf)

So that worked to force the update, now I will see if the fix works.

**Comment by NekoJonez** [comment] 2023-11-29 15:06
> > > > Sorry I'm not an expert on Intune client distribution but it should be updated automatically.
> > > 
> > > 
> > > Currently running 2304. My tennant is running 2311, is there a way to force an update so I can test if the fix works? Since, it's getting really annoying & time consuming.
> > 
> > 
> > try this https://www.reddit.com/r/Intune/comments/108zlx3/intune_management_extension_not_updating/
> 
> Ok tried that, here is the link I used: https://naprodimedatapri.azureedge.net/IntuneWindowsAgent.msi
> 
> Now the version of Microsoft.Management.Deployment.InProc.dll is updated to this: ![image](https://private-user-images.githubusercontent.com/58002498/286639429-56595936-4cd4-4465-9893-dfcf3435afcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNzA2NDksIm5iZiI6MTcwMTI3MDM0OSwicGF0aCI6Ii81ODAwMjQ5OC8yODY2Mzk0MjktNTY1OTU5MzYtNGNkNC00NDY1LTk4OTMtZGZjZjM0MzVhZmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE1MDU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NjJiY2E5MWQwZTk3YjA4YWY4ZWZiMjkzNDhmYjhlOGYyOGNiZjAwNzljZDM3YzRmMTRiYmUwNjAwMzgxMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YWGZlqU1GrDupZDb__fqkvBjTHkjCaDnZigcODpmJjg)
> 
> So that worked to force the update, now I will see if the fix works.

Same here. But we need 2311 and that's 2310... Yeah. I think that's the issue.

**Comment by NekoJonez** [comment] 2023-11-29 15:22
I stil have the bug tho.

**Comment by 7ep3s** [comment] 2023-11-29 16:28
> I stil have the bug tho.

https://github.com/microsoft/winget-cli/issues/3365#issuecomment-1830754352
try to install something from the portal or push something to the device that uses winget (so a Microsoft Store App(new) application), that should invoke the intune extensions winget binaries, then see if it's still bugged

**Comment by jbuettner00** [comment] 2023-11-29 17:08
> I stil have the bug tho.

Did you delete and re-create the user profile with the bug? I ran the remediate scripts then deleted the domain user profile with the bug, then re-logged in with that username to re-create the domain user profile. Once the Winget folder was created in C:\Users\%username%\appdata\local\microsoft\, I logged in with a local admin user and was able to successfully delete the domain user profile from sysdm.cpl and verified the user profile folder was completely removed from C:\Users.

**Comment by 7ep3s** [comment] 2023-11-29 17:33
> > I stil have the bug tho.
> 
> Did you delete and re-create the user profile with the bug? I ran the remediate scripts then deleted the domain user profile with the bug, then re-logged in with that username to re-create the domain user profile. Once the Winget folder was created in C:\Users%username%\appdata\local\microsoft, I logged in with a local admin user and was able to successfully delete the domain user profile from sysdm.cpl and verified the user profile folder was completely removed from C:\Users.

the point is that if the winget fix from intune 2311 is effective, they should not have to run the scripts

**Comment by NekoJonez** [comment] 2023-11-29 17:43
> > > I stil have the bug tho.
> > 
> > Did you delete and re-create the user profile with the bug? I ran the remediate scripts then deleted the domain user profile with the bug, then re-logged in with that username to re-create the domain user profile. Once the Winget folder was created in C:\Users%username%\appdata\local\microsoft, I logged in with a local admin user and was able to successfully delete the domain user profile from sysdm.cpl and verified the user profile folder was completely removed from C:\Users.
> 
> the point is that if the winget fix from intune 2311 is effective, they should not have to run the scripts

Exactly. Currently, I rather have a solution like that instead of trying to debug it with a script. I personally never used remidation in Intune and I want to avoid making mistakes especially when user data is involved in the prep week for the exam period next week.

After that I might have some more time to learn about this. 

Anyhow, not throwing any stones at anyones work. Thanks for the help but my current situation is more of fixing it yesterday instead of trying to learn something... :/

**Comment by yao-msft** [comment] 2023-11-29 20:01
> It seems like newly created profiles after this upgrade do not have the bug, is it possible that it does not fix pre-existing profiles?

After winget related operation is invoked as pre-existing profile user, the code should reset the folder permission to give full control to admin and system (on that user's path). It needs to be invoked for each pre-existing user.

**Comment by NekoJonez** [comment] 2023-11-30 08:03
I pushed a new app, I downloaded something via the company portal ... no luck. Even on freshly installed laptops that we connect with Intune, still 2304. Whilst our tennant uses 2311. 
Is the only thing we have now is to wait or what else can I troubleshoot?

**Comment by selimfelex** [comment] 2024-01-10 16:50
@yao-msft can we have someone from Intune team to help in the Intune fix  status - and if that will help in the pre-existing users

**Comment by yao-msft** [comment] 2024-01-24 23:27
@nikyusof Would you be able to help answer customer questions?

**Comment by selimfelex** [comment] 2024-02-08 15:08
@yao-msft it seems the issue is corrected if you try to access the files from local admins only  , but if you try to access it from an Intune user account (which is a member of device administrates )  which should have the same group permissson the issue still persists even if the ACL is correct, but they still cannot access the winget defaultstate folder  ,

**Comment by yao-msft** [comment] 2024-02-14 01:08
Winget currently uses following sid for admins
auto adminSID = wil::make_static_sid(SECURITY_NT_AUTHORITY, **SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_ADMINS**);

My change gives back the above security groups (admins) full access. Is Intune user account part of that group? My change was to fix a regression after we applied explicit ACLs. If the Intune user account is not part of that group, I feel it's not the regression I fixed.
Can you check which security group Intune user is in (on a local machine)? If it's standard user, then we cannot add it back due to internal security review. If it's some other group we missed, we should evaluate and add to winget's explicit ACL logic.

**Comment by selimfelex** [comment] 2024-02-15 11:37
Hello @yao-msft  
I can confirm that the permission is shown correct in the folders and the local admin (not Intune can access the defaultstate folder of other users and can delete them when he deletes the user from the system 
- the wired thing that we cannot do that from the Intune account logged in to the machine and they are also a member of  the local admins of the machines )
- I was able to reproduce with 2 users (Intune accounts) for example first user is (Selim) and second user is (Selim2)
- if you login with  user (Selim2)  and try to access the defaultstate folder of the other Intune  user ( Selim)   you will hit the issue with access denied 
-
![image](https://github.com/microsoft/winget-cli/assets/40806184/326db01d-fc7b-4f25-8e32-9b9c093a1bfe)
![image](https://github.com/microsoft/winget-cli/assets/40806184/f25a2f19-7f16-42a9-b389-ebf380b10eb6)
if we check the user (Selim2) we can see it is a part of local administrators 
![image](https://github.com/microsoft/winget-cli/assets/40806184/1161cd6f-9c82-4dd1-9d41-6549b0230ae8)
and the permission is correct on the folder 
![image](https://github.com/microsoft/winget-cli/assets/40806184/b7f57d68-8084-44f6-bf84-2b69463c1b1e)

and i can confirm also the Intune user is a part of the local administrators 
![image](https://github.com/microsoft/winget-cli/assets/40806184/add255d1-d609-4ddb-ae8a-6b06932cb7ff)

so in brief , the issue still appear within Inutne Users accounts only , they cannot access eachothers defaultstate folder althogh the permission is corrected after your fix 
- the issue does not appear if you login with Local Administrator (not Intune) after the fix it is corrected and local admin have a full access and can delete users and folder successfully 
- so we need to know why Intune admins still have the issue while they have the same permissions !!
- the main target is the ability to clean up old users data profiles using Intune admin task in a busy envirnments which is hard to do it manually 
- let me know if we can connect internally to show you the re-pro lab

**Comment by yao-msft** [comment] 2024-02-17 00:26
Thanks for the detailed info, @selimfelex . I feel this permission issue is outside of winget code's scope. Looks like winget sets the folder permission correctly, but certain admin account has permission issues. @nikyusof, do you have any insight on how Intune account is configured? I'll also raise this issue to Intune team in our sync meeting next week.

**Comment by selimfelex** [comment] 2024-04-02 15:41
Hello @yao-msft  , i could confirm the issue is resolved , the last operations on my last comment  was related  to UAC and it is working when you click on Continue and it is not related to the permission issue we had 
thanks for your co-opration
