### ISSUE TITLE
`winget pin list` shows no pins configured

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-cli#2973] opened 2023-02-16 02:46 UTC
### Brief description of your issue

I added a pin, the pin is recognized by winget upgrade. `winget pin list` shows no pins configured

I did note that this does not happen on my other machine, and the pins are listed accurately

### Steps to reproduce

`winget pin list`

### Expected behavior

Pins to be listed

### Actual behavior

[Add Pin - WinGet-2023-02-15-20-37-27.383.log](https://github.com/microsoft/winget-cli/files/10751634/WinGet-2023-02-15-20-37-27.383.log)
[Upgrade - WinGet-2023-02-15-20-38-09.246.log](https://github.com/microsoft/winget-cli/files/10751630/WinGet-2023-02-15-20-38-09.246.log)
[List Pin - WinGet-2023-02-15-20-38-20.560.log](https://github.com/microsoft/winget-cli/files/10751629/WinGet-2023-02-15-20-38-20.560.log)

```
PS D:\Git\winget-pkgs> winget upgrade --verbose-logs
Name                              Id                                     Version        Available
-----------------------------------------------------------------------------------------------------
AutoHotkey 1.1.36.01              Lexikos.AutoHotkey                     1.1.36.01      2.0.2
CCleaner                          Piriform.CCleaner                      6.08           6.08.10255
Git                               Git.Git                                2.39.1         2.39.2
Microsoft Visual Studio Installer Microsoft.VisualStudio.2019.BuildTools 3.4.2246.31370 16.11.23
Microsoft .NET SDK 6.0.406 (x86)  Microsoft.DotNet.SDK.5                 > 5.0.408      6.0.406
Microsoft Edge                    Microsoft.Edge                         110.0.1587.41  110.0.1587.46
CORSAIR iCUE 4 Software           Corsair.iCUE.4                         4.32.129       4.33.138
Microsoft .NET SDK 6.0.406 (x64)  Microsoft.DotNet.SDK.5                 > 5.0.408      6.0.406
8 upgrades available.
2 package(s) have pins that prevent upgrade. Use the 'winget pin' command to view and edit pins. Using the --include-pinned argument may show more results.
PS D:\Git\winget-pkgs> winget pin list --verbose-logs
There are no pins configured.
```

### Environment

```shell
PS D:\Git\winget-pkgs> winget --info
Windows Package Manager (Preview) v1.5.441-preview       
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.2604
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.441.0       

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Enabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by Trenly** [comment] 2023-02-16 02:48
Also, here is a screenshot of my pinning.db; If it would help to have the actual file, please let me know -
![image](https://user-images.githubusercontent.com/12611259/219255489-de976f4c-4741-4ff4-b771-814e52853aa6.png)

**Comment by florelis** [comment] 2023-02-16 21:30
This looks like a duplicate of #2974

**Closed by florelis** 2023-02-16 21:30 UTC
Labels: Issue-Bug
