### ISSUE TITLE
Problem with upgrade command

### ISSUE THREAD

**Issue by Lanerun** [microsoft/winget-cli#4225] opened 2024-03-03 22:42 UTC
### Brief description of your issue

WinGet Upgrade states Microsoft.VCRedist.2013.x86 as outdated, however when running the WinGet Upgrade command on it, no update is found. See image for reference. 

![image](https://github.com/microsoft/winget-cli/assets/155983714/45f905eb-5336-4308-9733-6c4fcbc6c9eb)

### Steps to reproduce

Run WinGet Upgrade
WinGet shows various programs as out-of-date, one of them being Microsoft.VCRedist.2013.x86
Attempt to update Microsoft.VCRedist.2013.x86 using WinGet
WinGet does not find any updates for the program. 

### Expected behavior

Microsoft.VCRedist.2013.x86 is successfully updated.

### Actual behavior

Microsoft.VCRedist.2013.x86 isn't updated by the command. 

### Environment

```shell
Windows Package Manager (Preview) v1.8.532-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.26058.1300
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.532.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by o-l-a-v** [comment] 2024-03-04 08:01
Seems like a duplicate of #4219.

A workaround is to reset Winget. You'll loose all settings, including pinned apps. I wrote about it here:

* https://github.com/microsoft/winget-cli/issues/4219#issuecomment-1975125826

**Comment by avicarmi** [comment] 2024-03-04 08:30
your workaround did not work for me, but as far as I can tell, msstore and winget are down:

`> winget --version`
```
v1.7.10582
```

`> winget source list`
``` 
Name    Argument
-----------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
winget  https://cdn.winget.microsoft.com/cache
``` 

trying msstore in browser gives:

```html
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<script/>
<Message>No HTTP resource was found that matches the request URI 'https://useast.storeedgefd-origin.xbetservices.akadns.net/v9.0'.</Message>
</Error>
``` 

and similarly for winget

```html
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<script/>
<Code>ResourceNotFound</Code>
<Message>The specified resource does not exist. RequestId:91cdae92-d01e-0079-2209-6ec02d000000 Time:2024-03-04T07:56:23.9195966Z</Message>
</Error>
```

**Comment by Trenly** [comment] 2024-03-04 15:24
What is the output of `winget list 'vcredist'`

**Comment by Lanerun** [comment] 2024-03-04 18:12
> What is the output of `winget list 'Microsoft Visual C++'`

```
C:\Users\lanerun>winget list 'Microsoft Visual C++
Windows Package Manager (Preview) v1.8.532-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Found a positional argument when none was expected: 'Visual'
```

**Comment by denelon** [comment] 2024-03-04 18:24
@Lanerun no worries. We were all new to GitHub at some point.

The output you shared above is missing the closing quotation mark after "C++".

Try running "installing" the source.msix. That will update the local cache of packages, and I suspect that's what got corrupted.

**Comment by Lanerun** [comment] 2024-03-04 19:04
> This may be my error too; I usually use single quotations since that's what PowerShell works best with, but double quotes may be needed when using cmd, or bash

I see. I was running it in command prompt, so that seems to have been the issue. With double quotations the command works, and displays the following output:

```
C:\Users\lanerun>winget list "Microsoft Visual C++"
Name                                      Id                                         Version        Available    Source
-----------------------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2010  x64 Redistrib… Microsoft.VCRedist.2010.x64                10.0.40219                  winget
Microsoft Visual C++ 2008 Redistributabl… Microsoft.VCRedist.2008.x64                9.0.30729.6161              winget
Microsoft Visual C++ 2013 Redistributabl… Microsoft.VCRedist.2013.x86                12.0.40664.0                winget
Microsoft Visual C++ 2013 Redistributabl… Microsoft.VCRedist.2013.x86                12.0.30501.0   12.0.40664.0 winget
Microsoft Visual C++ 2012 Redistributabl… Microsoft.VCRedist.2012.x86                11.0.61030.0                winget
Microsoft Visual C++ 2015-2022 Redistrib… Microsoft.VCRedist.2015+.x86               14.38.33135.0               winget
Microsoft Visual C++ 2008 Redistributabl… Microsoft.VCRedist.2008.x86                9.0.30729.6161              winget
Microsoft Visual C++ 2013 Redistributabl… Microsoft.VCRedist.2013.x86                12.0.40664.0                winget
Microsoft Visual C++ 2015-2022 Redistrib… Microsoft.VCRedist.2015+.x64               14.38.33135.0               winget
Microsoft Visual C++ 2012 Redistributabl… Microsoft.VCRedist.2012.x64                11.0.61030.0                winget
Microsoft Visual C++ 2010  x86 Redistrib… Microsoft.VCRedist.2010.x86                10.0.40219                  winget
Microsoft Visual C++ 2015 UWP Desktop Ru… Microsoft.VCLibs.Desktop.14                14.0.33519.0                winget
Microsoft Visual C++ 2015 UWP Runtime Pa… Microsoft.VCLibs.140.00_8wekyb3d8bbwe      14.0.33519.0
Microsoft Visual C++ 2013 UWP Desktop Ru… Microsoft.VCLibs.120.00.UWPDesktop_8wekyb… 12.0.40653.0
Microsoft Visual C++ 2012 UWP Desktop Ru… Microsoft.VCLibs.110.00.UWPDesktop_8wekyb… 11.0.61135.0

```

**Comment by Trenly** [comment] 2024-03-04 19:29
Got it! This is a known issue where having two applications installed side-by-side causes an upgrade loop to occur. 
```
Microsoft Visual C++ 2013 Redistributabl… Microsoft.VCRedist.2013.x86                12.0.40664.0                winget
Microsoft Visual C++ 2013 Redistributabl… Microsoft.VCRedist.2013.x86                12.0.30501.0   12.0.40664.0 winget
```
From these two lines, it's clear that both `12.0.40664.0`	and `12.0.30501.0` are installed. This is an issue where when running `winget upgrade` to list available upgrades, WinGet sees that `12.0.30501.0` is installed and can be upgraded, but when running `winget upgrade Microsoft.VCRedist.2012.x86`, it then realizes that `12.0.40664.0` is already installed and that there is nothing to upgrade.

* Related to https://github.com/microsoft/winget-cli/issues/2129
* Duplicate of microsoft/winget-pkgs#118664

**Closed** 2024-03-04 19:29 UTC
Labels: Issue-Bug, Side-by-Side

**Comment by avicarmi** [comment] 2024-03-05 05:45
> The source URLs don't have any content at their root. The winget source is at https://cdn.winget.microsoft.com/cache/source.msix and the msstore expects a path for one of the RESTful endpoints.

yes, I realized that later on...

found out by looking at the log file that the error is WinHttpSendRequest: 12030 

it means incompatible SSL protocol was encountered, but I do not know how to fix it...
