### ISSUE TITLE
Support chaining multiple apps / ids on `--install`

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/winget-cli#2479] opened 2022-08-29 09:20 UTC
### Description of the new feature / enhancement

Currently when I want to install more than one app in one go, I have to do something like 

```ps
winget install --id=Microsoft.VisualStudio.2022.Professional -e  ; winget install --id=Microsoft.AzureCosmosEmulator -e  ; winget install --id=Microsoft.AzureStorageEmulator -e  ; winget install --id=OpenJS.NodeJS.LTS -e  ; winget install --id=Git.Git -e  ; winget install --id=Microsoft.PowerShell -e ; winget install --id=Docker.DockerDesktop -e  ; winget install --id=Microsoft.AzureStorageExplorer -e 
```` 

What I want to do is 

```ps
winget install --id=Microsoft.VisualStudio.2022.Professional -e --id=Microsoft.AzureCosmosEmulator -e --id=Microsoft.AzureStorageEmulator -e --id=OpenJS.NodeJS.LTS -e --id=Git.Git -e --id=Microsoft.PowerShell -e --id=Docker.DockerDesktop -e --id=Microsoft.AzureStorageExplorer -e
```

instead.

This is kind of similar to https://github.com/microsoft/winget-cli/issues/2478 but for the install command.

**Comment by denelon** [comment] 2022-08-29 18:02
Duplicate of #219

**Closed by denelon** 2022-08-29 18:02 UTC
Labels: Issue-Feature, Needs-Triage
