### ISSUE TITLE
`winget list --source winget` does not seem to be filtering by the source column

### ISSUE THREAD

**Issue by corvusblack** [microsoft/winget-cli#1450] opened 2021-09-09 21:48 UTC
# Brief description of your issue

Apologies in advance if I might be misunderstanding something. 

When I do `winget list`, I see a bunch of applications with some of them having `winget` in the Source column. I wanted to list only applications that use `winget`. However when I do `winget list --source winget`, I still see applications that don't use winget. I thought `winget list --source winget` would only list the applications using winget based on this line in the usage documentation for `winget list`:

>   -s,--source  Find package using the specified source

# Steps to reproduce

Enter the command `winget list --source winget` 

# Expected behavior

Only applications with `winget` in the Source column would be listed

# Actual behavior

Applications are listed with and without `winget` in the Source column.

# Environment

```none
Windows Package Manager v1.0.11692
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.1165
Package: Microsoft.DesktopAppInstaller v1.12.11692.0
```

**Comment by denelon** [comment] 2021-09-09 22:46
Duplicate of #1155

**Closed by denelon** 2021-09-09 22:46 UTC
Labels: Needs-Triage
