### ISSUE TITLE
Support for enterprise application install/update

### ISSUE THREAD

**Issue by CookeDanny** [microsoft/winget-cli#193] opened 2020-05-19 17:39 UTC
Would love to see integration with Intune/MEM to globally push and update supported applications

**Comment by bbarry** [comment] 2020-05-19 18:47
And/or the ability to maintain a package list of installables at an org level. 

Ex: vscode is an approved package, go ahead and install it...

once installed, Intune/MEM/GFI/... keeps the installed packages up to date (vs code might be a bad example because it self updates but still if you never open it, it never updates).

**Comment by vedantmgoyal2009** [comment] 2022-09-06 15:38
@trenly Duplicate of https://github.com/microsoft/winget-cli/issues/215

**Comment by vedantmgoyal2009** [comment] 2022-09-06 15:38
cc @denelon

**Comment by denelon** [comment] 2022-09-06 16:21
Duplicate of #215

**Closed by denelon** 2022-09-06 16:21 UTC
Labels: Issue-Feature
