### ISSUE TITLE
winget list fails to narrow down results by source

### ISSUE THREAD

**Issue by kamenminkov** [microsoft/winget-cli#1525] opened 2021-09-29 18:32 UTC
# Brief description of your issue
```winget list --source winget``` doesn't narrow down by source.
# Steps to reproduce

Issue the command `winget list --source winget`.

# Expected behavior

I expect only packages installed by winget to be listed.

# Actual behavior

All software installed on the system is listed - with only some of the rows saying `winget` in the `Source` column.

Sample output:
```none
> winget list --source winget
Name                                              Id                                                Version             Available     Source
--------------------------------------------------------------------------------------------------------------------------------------------
Notepads                                          JackieLiu.NotepadsApp                             1.4.5.0
QuickLook                                         21090PaddyXu.QuickLook_egxr34yet59cg              3.7.0.0
Windows Driver Package - Godox Corporation (libu… 22A4D5BDE26E8D87BFECC3820CF4F82FAF3904D1          10/02/2010 1.2.2.0
Visual Studio Build Tools 2017                    30cb271d                                          15.9.28307.1146
NVM for Windows 1.1.7                             40078385-F676-4C61-9A9C-F9028599D6D3_is1          1.1.7
EarTrumpet                                        40459File-New-Project.EarTrumpet_1sdd7yawvg6ne    2.1.8.0
Files - Preview                                   Files-Community.Files                             1.5.2.0
Fluent Terminal                                   53621FSApps.FluentTerminal_87x1pks76srcp          0.6.1.0
Windows Driver Package - Phase One A/S (WinUSB) … 5D536C8BAC29754ACD7E2AFB52D1C2B1EA169BE6          09/18/2017 1.14.0.0
YAML Generator for Windows Package Manager        62961PeterTorr.WinGetYAMLGenerator_06hnt7wnqw60w  1.6.1.0
7-Zip 21.02 alpha (x64)                           7-Zip                                             21.02 alpha
Vuze                                              8461-7759-5462-8226                               5.6.1.0
Fiddler Everywhere                                Telerik.FiddlerEverywhere                         1.5.1               2.0.3         winget
AMD Ryzen Master                                  AMD.RyzenMaster                                   2.6.0.1702          2.8.0.1937    winget
AMD Chipset Software                              AMD_Chipset_IODrivers                             2.13.27.501
Android Studio                                    Google.AndroidStudio                              1.0                 2020.3        winget
AutoHotkey                                        Lexikos.AutoHotkey                                1.1.33.00           1.1.33.09     winget
BleachBit                                         BleachBit.BleachBit                               4.4.0.1929
Blisk                                             Blisk                                             10.1.262.114
Ubuntu                                            CanonicalGroupLimited.UbuntuonWindows_79rhkp1fnd… 2004.2021.825.0
Chromium                                          eloston.ungoogled-chromium                        80.0.3950.0         89.0.4389.114 winget
Docker Desktop                                    Docker.DockerDesktop                              3.3.3               4.0.1         winget
Exact Audio Copy                                  AndreWiethoff.ExactAudioCopy                      1.3                 1.6           winget
FAHClient                                         FAHClient                                         7.5.1
FileZilla Client                                  TimKosse.FileZillaClient                          3.23.0.2            3.55.1        winget
Firefox Developer Edition                         Mozilla.FirefoxDeveloperEdition                   74.0                93.0b9        winget
...
```

# Environment

```none
[winget --info]
Windows Package Manager v1.0.12576
Windows: Windows.Desktop v10.0.21390.2025
Package: Microsoft.DesktopAppInstaller v1.16.12576.0

```

**Comment by jedieaston** [comment] 2021-09-29 22:48
`--source` means what source you want winget to match applications against, not where apps were installed from. winget doesn't actually know what apps it installed vs which were installed from another source (at least, not right now).

**Comment by denelon** [comment] 2021-09-29 22:55
@kamenminkov,

The current behavior is by design. We have a feature coming up to improve the experience.
Several users have had the same expectation, so we're changing it.

Duplicate of #1155

**Closed by denelon** 2021-09-29 22:55 UTC
Labels: Needs-Triage
