### ISSUE TITLE
Winget doesn't automatically adds a Git environment variable after installing Git in Windows 11

### ISSUE THREAD

**Issue by protyay** [microsoft/winget-cli#2815] opened 2023-01-04 18:51 UTC
### Description of the new feature / enhancement

When executing the following command
`winget install -e --id Git.Git` , the latest version of Git is installed but no git command can be executed because the environment variable` PATH` is not modified to include the Git installation folder. 

### Proposed technical implementation details

We can choose to modify the `PATH` variable and append the Git installation folder to enhance the user experience.

**Comment by denelon** [comment] 2023-01-04 18:59
Related to:
* https://github.com/microsoft/winget-cli/issues/2781
* https://github.com/microsoft/winget-cli/issues/2521
* https://github.com/microsoft/winget-pkgs/issues/62326

We're looking at another issue related to environment variables like "Path" that don't get refreshed in an active session. If a package has a dependency on another one and it needs to be on the path for the "primary" package to install, the primary package will fail.

In your particular example, if you close the "terminal" and re-open to get the environment variables updated, are you able to call git?

**Comment by protyay** [comment] 2023-01-05 15:02
Thanks for replying. Nope, even after restarting the terminal (and in my case, the machine) doesn't add the appropriate `git` executable to the `PATH` env.

**Comment by denelon** [comment] 2023-01-05 19:01
I haven't encountered this issue or been able to reproduce it. The "installer" is responsible for adding Path entries. WinGet only adds portable (and in the next version .zip based portable) packages to the path. If you perform a "manual" uninstall and then run `winget install git.git` does it still not add the path entry?

If no, which version of git.git was installed, and can you share the logs?

The log location is visible via `winget info` as well as the version of WinGet and the architecture. That information could also be helpful. There is also an experimental feature in preview versions that can be enabled to add "--open-logs" to the command which will open the log directory if the feature is enabled.

**Comment by denelon** [comment] 2023-01-05 19:30
Example PR:
* https://github.com/microsoft/winget-pkgs/pull/90517

Related Issue:
* https://github.com/microsoft/winget-pkgs/issues/90650

**Comment by denelon** [comment] 2023-02-09 16:35
Duplicate of #222

**Closed** 2023-02-09 16:36 UTC
Labels: Issue-Feature
