### ISSUE TITLE
Ability to exclude from winget upgrade --all

### ISSUE THREAD

**Issue by AliqQim** [microsoft/winget-cli#3268] opened 2023-05-24 10:46 UTC
### Description of the new feature / enhancement

I would like to be able to exclude certain applications from being affected by this command: "winget upgrade --all"

### Proposed technical implementation details

"winget exclude ~path~"

**Comment by mdanish-kh** [comment] 2023-05-24 11:03
Duplicate of #476

Pin a package feature is available in the preview version of WinGet. Please upgrade to latest preview version of WinGet from https://aka.ms/getwingetpreview, enable [pinning in experimental features](https://github.com/microsoft/winget-cli/blob/master/doc/Settings.md#pinning) and give `winget pin` command a try

**Comment by Trenly** [comment] 2023-05-24 12:37
See above

**Closed** 2023-05-24 12:38 UTC
Labels: Issue-Feature, Needs-Triage

**Comment by rastislavbodorik** [comment] 2024-10-31 09:52
All related issues included this one has been closed with circular duplication reference without resolution
