### ISSUE TITLE
winget upgrade does not respect the scope used on installation

### ISSUE THREAD

**Issue by JanDeDobbeleer** [microsoft/winget-cli#5099] opened 2024-12-28 16:35 UTC
### Brief description of your issue

When using winget install in a non-elevated terminal, the installation is done with `scope: user`. However, when using upgrade immediately after in the same terminal window, the scope is identified as `system`.

#### Install v27.17.0

```
winget install JanDeDobbeleer.OhMyPosh -v 24.17.0
```

```
2024-12-28 17:24:43.631 [CLI ] Starting installer selection.
2024-12-28 17:24:43.631 [CLI ] Installer [X64,msi,Machine,] is current best choice
2024-12-28 17:24:43.631 [CLI ] Installer [X64,msi,User,] is better [strong] than [X64,msi,Machine,] due to: Scope
2024-12-28 17:24:43.631 [CLI ] Installer [X64,msi,User,] is current best choice
2024-12-28 17:24:43.631 [CLI ] Installer [X64,msi,User,] is better [strong] than [X86,msi,Machine,] due to: Scope
2024-12-28 17:24:43.631 [CLI ] Installer [X64,msi,User,] is better [weak] than [X86,msi,User,] due to: Machine Architecture
2024-12-28 17:24:43.631 [CLI ] Installer [X64,msi,User,] is better [strong] than [Arm64,msi,Machine,] due to: Scope
2024-12-28 17:24:43.631 [CLI ] Installer [Arm64,msi,User,] is better [strong] than [X64,msi,User,] due to: Machine Architecture
2024-12-28 17:24:43.631 [CLI ] Installer [Arm64,msi,User,] is current best choice
2024-12-28 17:24:43.631 [CLI ] Completed installer selection.
2024-12-28 17:24:43.631 [CLI ] Selected installer Architecture: 4
2024-12-28 17:24:43.631 [CLI ] Selected installer URL: https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v24.17.0/install-arm64.msi
2024-12-28 17:24:43.631 [CLI ] Selected installer InstallerType: msi
2024-12-28 17:24:43.631 [CLI ] Selected installer Scope: User
```

#### Upgrade to latest

```
winget upgrade JanDeDobbeleer.OhMyposh
```

```
2024-12-28 17:26:57.914 [CLI ] Starting installer selection.
2024-12-28 17:26:57.914 [CLI ] Installer [X64,msi,Machine,] is current best choice
2024-12-28 17:26:57.914 [CLI ] Installer [X64,msi,User,] not applicable: Installer scope does not match currently installed scope: User != Machine
2024-12-28 17:26:57.914 [CLI ] Installer [X64,msi,Machine,] is better [weak] than [X86,msi,Machine,] due to: Machine Architecture
2024-12-28 17:26:57.914 [CLI ] Installer [X86,msi,User,] not applicable: Installer scope does not match currently installed scope: User != Machine
2024-12-28 17:26:57.914 [CLI ] Installer [Arm64,msi,Machine,] is better [strong] than [X64,msi,Machine,] due to: Machine Architecture
2024-12-28 17:26:57.914 [CLI ] Installer [Arm64,msi,Machine,] is current best choice
2024-12-28 17:26:57.914 [CLI ] Installer [Arm64,msi,User,] not applicable: Installer scope does not match currently installed scope: User != Machine
2024-12-28 17:26:57.914 [CLI ] Completed installer selection.
2024-12-28 17:26:57.914 [CLI ] Selected installer Architecture: 4
2024-12-28 17:26:57.914 [CLI ] Selected installer URL: https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v24.17.1/install-arm64.msi
2024-12-28 17:26:57.914 [CLI ] Selected installer InstallerType: msi
2024-12-28 17:26:57.914 [CLI ] Selected installer Scope: Machine
```

### Expected behavior

It should also identify `Installer [Arm64,msi,User,] is current best choice` on upgrade.

### Actual behavior

It identifies `Installer [Arm64,msi,Machine,] is current best choice`.

Full logs below.

[WinGet-2024-12-28-17-26-54.424.log](https://github.com/user-attachments/files/18266807/WinGet-2024-12-28-17-26-54.424.log)
[WinGet-2024-12-28-17-24-39.755.log](https://github.com/user-attachments/files/18266808/WinGet-2024-12-28-17-24-39.755.log)

### Environment

```shell
Windows Package Manager v1.9.25200
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.26100.2605
System Architecture: Arm64
Package: Microsoft.DesktopAppInstaller v1.24.25200.0

Winget Directories                 
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagΓÇª
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settΓÇª
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links               
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

**Comment by litmowise** [comment] 2024-12-29 05:49
I have this related problem, using the `winget upgrade` command to upgrade a software programme results in two different versions.

![Image](https://github.com/user-attachments/assets/5f027249-c258-4f82-bf0d-a69c5d90b788)

**Comment by litmowise** [comment] 2024-12-29 06:02
Updating with the `winget upgrade `command also results in one more set of environment variables.

First installation

> current user env
> C:\Users\xxx\AppData\Local\Programs\oh-my-posh\themes\
> C:\Users\xxx\AppData\Local\Programs\oh-my-posh\bin\

After updating

> local machine env (system env)
> C:\Program Files (x86)\oh-my-posh\themes\
> C:\C:\Program Files (x86)\oh-my-posh\bin\

**Comment by JanDeDobbeleer** [comment] 2024-12-29 07:02
> Updating with the winget upgrade command also results in one more set of environment variables.

@litmowise that's a side effect of the issue described above.

**Comment by litmowise** [comment] 2024-12-29 09:23
@JanDeDobbeleer Thank you, I know.

**Comment by mdanish-kh** [comment] 2024-12-29 09:47
This is a known issue with MSI / WiX installers where they would put uninstall entries in `HKEY_LOCAL_MACHINE` instead of `HKEY_CURRENT_USER` in the registry for user scoped installs. WinGet relies on the registry location to determine the installed scope. There's an open issue in the repo https://github.com/microsoft/winget-cli/issues/3011 which suggests WinGet could have a better way to handle these scenarios

[comment]: <[Policy] Area-Scope>

**Comment by davidldennison** [comment] 2024-12-29 10:51
I was actually going to make an issue for this @denelon as I have this issue described with oh-my-posh as well as with other installations. I've been waiting until I had an example where I could submit to the Feedback Hub.

However, this might extend further into an issue of Winget not respecting paths and custom install locations, even sometimes failing to install into a custom directory using winget commands as it will just default back the installers preferred default location.

Will try and get an example soon!

**Comment by mdanish-kh** [comment] 2024-12-29 11:49
This issue is not specific to oh-my-posh, but applies generally to most MSIs. I'll close this as duplicate of #3011 

Duplicate of #3011

**Closed** 2024-12-29 11:49 UTC
Labels: Issue-Bug, Command-Upgrade, Area-Scope

**Comment by JanDeDobbeleer** [comment] 2024-12-29 12:52
@mdanish-kh is there anything I can change to the installer to force the identification?

**Comment by mdanish-kh** [comment] 2024-12-29 13:06
https://github.com/microsoft/winget-cli/issues/3011#issuecomment-1445714683 or https://stackoverflow.com/questions/32273217/how-and-why-installation-per-user-manages-to-write-to-hklm may offer some more hints

**Comment by mdanish-kh** [comment] 2024-12-29 13:13
> 3. Use winget upgrade with --force parameter. This tells WinGet to ignore the scope mismatch and just continue with installation, but may not be feasible or immediately obvious to all users

I should also mention that with this you'll have to also explicitly target the user scope installer, as by default WinGet will assume the current installation is `Machine`

so: `winget upgrade JanDeDobbeleer.OhMyPosh --scope user --force`

**Comment by mdanish-kh** [comment] 2024-12-29 13:14
> 3. Use winget upgrade with --force parameter. This tells WinGet to ignore the scope mismatch and just continue with installation, but may not be feasible or immediately obvious to all users

I should also mention that here you'll have to explicitly target the user scope installer, as by default WinGet will assume the current installation is `Machine`

so: `winget upgrade JanDeDobbeleer.OhMyPosh --scope user --force`

**Comment by JanDeDobbeleer** [comment] 2024-12-29 13:58
@mdanish-kh shouldn't that also work without the `--force` parameter in that case?

**Comment by mdanish-kh** [comment] 2024-12-29 14:45
@JanDeDobbeleer No - Scope is treated as a requirement (instead of a preference) to be matched in case of upgrade. If WinGet detects current installation as `Machine`, doing `winget upgrade --scope user` would fail with `No applicable upgrade found` unless you explicitly ask WinGet to ignore the requirement with `--force`

**Comment by Dilant** [comment] 2024-12-30 08:33
@mdanish-kh Tried `winget upgrade JanDeDobbeleer.OhMyPosh --scope user --force` and it didn't work for me. It still says "no package found matching input criteria".

```
# Dilant @ Dilant-PC in ~ [16:28:11]
$ winget --version
v1.9.25200

# Dilant @ Dilant-PC in ~ [16:32:33]
$ winget upgrade JanDeDobbeleer.OhMyPosh --scope user --force
找不到与输入条件匹配的已安装程序包。
```

**Comment by JanDeDobbeleer** [comment] 2024-12-30 08:40
> It still says "no package found matching input criteria".

@Dilant same for me, this is a really annoying bug TBH.

@mdanish-kh this issue has been open for almost 2 years and seems rather fundamental for a package manager to get right. I would expect that when using `--scope user` this only implies to use the correctly provided flags in the manifest, and not go on some sort of magic hunt to determine what to do. 

@denelon something we can do about this? I would be bummed to have to go back to the Inno installer simply because of this bug.

**Comment by denelon** [comment] 2024-12-30 16:44
I'll talk with the team about this "class" of issue today

I'll put some notes over in:
* #3011

**Comment by JanDeDobbeleer** [comment] 2024-12-30 16:58
@denelon if there's something we can do installer side to facilitate the correct detection, let me know. Registry values can be set rather easily. That way it doesn't matter if the user installed using winget, upgraded manually etc...

**Comment by denelon** [comment] 2024-12-31 16:41
@JanDeDobbeleer yes, you should be able to get the installer to write the keys to HKCU for user and to HKLM for a system wide install. The package manifest would need to have two "installers" one with each scope. WinGet would default to "user" unless the scope was passed to WinGet. For the upgrade flow, WinGet would inspect the registry to run the upgrade flow appropriately afterwards to match the currently installed scope.

**Comment by JanDeDobbeleer** [comment] 2025-01-03 10:17
@denelon I'm trying to hack this in, but even when adding the registry information to `HKCU`, winget still thinks it's machine scope. I am unable to remove these from `HKLM` as that would require elevation and this is done by `msiexec`. I do not understand why winget needs to magically identify this when you know which scope was used by the user previously (or fallback to the same logic you use on install).
