### ISSUE TITLE
Package-related dependencies

### ISSUE THREAD

**Issue by renatoassis01** [microsoft/winget-cli#332] opened 2020-05-25 23:08 UTC
check and install package-related dependencies. For example, when installing powerToys, also install the donet dependency. Perhaps a property in the manifest indicating which dependencies

**Comment by suhailmalik07** [comment] 2020-05-26 03:55
duplicate of #163

**Comment by renatoassis01** [comment] 2020-05-26 14:38
tks @suhailmalik07

**Comment by renatoassis01** [comment] 2020-05-26 14:39
duplicate of #163

**Closed** 2020-05-26 14:39 UTC
Labels: Issue-Feature, Needs-Triage
