### ISSUE TITLE
Error: Unable to write to C:/... IT policies may be restricting access to this folder

### ISSUE THREAD

**Issue by Juknum** [microsoft/winget-cli#1128] opened 2021-06-07 08:59 UTC
# Brief description of your issue

Each time I make `winget upgrade --all`, when the download ends, I get a window error saying: **Installation has failed: Unable to write to C:\ProgramData\julie IT policies may be restricting access to this folder**
![image](https://user-images.githubusercontent.com/49886317/120936613-fd673f80-c708-11eb-8aa4-491ad616a043.png)

The worse there is that winget is telling me that the upgrade succeed but in facts, it doesn't:
![image](https://user-images.githubusercontent.com/49886317/120936561-be38ee80-c708-11eb-937d-c133f858cacb.png)
Winget is writting that the software has been "correctly installed" (Installé Correctement in the screenshot) but they still show up when doing `winget upgrade`:
![image](https://user-images.githubusercontent.com/49886317/120936678-5afb8c00-c709-11eb-80d4-1a90beacaae9.png)

# Steps to reproduce

1. Open a command prompt as Administrator (the default one from Windows 10)
2. Type `winget upgrade --all`
3. See the errors window everywhere
4. Make `winget upgrade` and see that nothing has been updated

# Expected behavior

A working command or a way to disable IT policies?

# Actual behavior

Already explained in the description

# Environment

```none
Windows Package Manager v1.0.11451
Windows: Windows.Desktop v10.0.19042.985
Package: Microsoft.DesktopAppInstaller v1.11.11451.0

Any other software?
```
Can I ask what do you expect by _any other software?_ ? Like anything related to winget? Then no.

**Comment by denelon** [comment] 2021-06-07 16:51
@Juknum is this an enterprise managed machine?  I've seen several issues related to Discord. You might want to search for some of those other issues here in the CLI repository as well as the pkgs repository. It would also help if you could share your logs, or submit a [Feedback](https://aka.ms/winget-feedback) and share the link so we can look at the logs internally.

**Comment by Juknum** [comment] 2021-06-07 17:34
> @Juknum is this an enterprise managed machine? I've seen several issues related to Discord. You might want to search for some of those other issues here in the CLI repository as well as the pkgs repository. It would also help if you could share your logs, or submit a [Feedback](https://aka.ms/winget-feedback) and share the link so we can look at the logs internally.

No it's my own machine, doesn't seems to be related to Discord since it also hapen with other software I have.
I've made a feedback with the link you provided: [here](https://aka.ms/AAcu6tc)

**Comment by Juknum** [comment] 2021-06-10 22:37
I've tried this option but it doesn't worked for me, I still have the IT policies error
![image](https://user-images.githubusercontent.com/49886317/121605449-b5b81f00-ca4c-11eb-9111-0578db29764d.png)

I've also tried [this](https://github.com/microsoft/winget-cli/issues/189#issuecomment-855291465) but it's telling me that `Get-AppxPackage` is not a command (I might be dumb ? xd)

**Comment by denelon** [comment] 2021-06-10 22:43
Did you run it in "Windows Powershell" with the blue background, not "Windows Terminal in PowerShell"?

**Comment by denelon** [comment] 2021-06-10 22:45
@Karl-WE does this look like what you've encountered?

**Comment by Karl-WE** [comment] 2021-06-10 23:41
Hi @denelon no this is not the one that is familiar what we talked about recently. 
@Juknum issue though, yes I have seen these weird msgbox and path **unrelated** to winget.

There is a problem with his folder redirection caused by Onedrive known folder move.
it happens when a user does cause redirection loops (there is hole somewhere)

I understand this is no support forum yet for the sake of solving this (hopefully)

@Juknum 
0. have a full system image backup (Macrium reflect free or sorts)
1. close onedrive 
2. check your registry for user shell folder paths if they are all ok https://support.microsoft.com/en-us/topic/how-to-redirect-user-shell-folders-to-a-specified-path-by-using-profile-maker-ed6289ae-1f9c-b874-4e8c-20d23ea65b2e

https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-2000-server/cc962613(v=technet.10)?redirectedfrom=MSDN

3. correct the paths where needed make sure that you double check the path it needs to accessible via cmd otherwise you might cause more troubles

4. consider to edit folders back to original positions c:\users\username\foldername in File Explorer refresh view several times and delete orrecreate the folders. 
When all set all shell folders should be - accessible, have a tab called "Path". if not this folder is no longer a proper shell folder

![image](https://user-images.githubusercontent.com/45657752/121610331-1009ad80-ca56-11eb-9424-489e3cf50d78.png)

5. 
some trivia: https://devblogs.microsoft.com/oldnewthing/20031103-00/?p=41973

**Comment by denelon** [comment] 2021-06-11 15:35
@Karl-WE thanks for adding clarity, a possible workaround, and for me... Useless trivia is kind of my kryptonite. I was compelled to read that blog post. 

I am simply amazed at the amount of knowledge in this community!

**Comment by Karl-WE** [comment] 2021-06-11 23:12
all welcome. The community helps me with my job every day and it would without community there would be no blogs and no Ask Dr. Google (better do so for tech than health issues). I hope Julian @Juknum can find the reason for this and most of all report back the possible cause and solution to power up our XP.

**Comment by Juknum** [comment] 2022-04-16 10:26
Sorry for this late response. I have reset my computer and installed windows 11 and didn't tried anything with winget yet 💀

**Comment by denelon** [comment] 2022-06-21 16:45
@Juknum are you still having this problem?

I'm marking this as Area-External based on the input from @Karl-WE related to the OneDrive path redirection behavior. I'm not sure if there is something else we can do in Windows Package Manager to diagnose / repair this. It may end up being something we need to add to the troubleshooting guide if this is still happening.

**Comment by denelon** [comment] 2022-11-15 21:23
We haven't had any other reports of this happening, and as it does not appear to be related to the WinGet client, I'm going to go ahead and close this issue.

**Closed by denelon** 2022-11-15 21:23 UTC
Labels: Issue-Bug, Needs-Author-Feedback, No-Recent-Activity, Resolution-External
