### ISSUE TITLE
Failed in attempting to update the source: winget

### ISSUE THREAD

**Issue by R-Adrian** [microsoft/winget-cli#2807] opened 2022-12-28 09:35 UTC
### Brief description of your issue

this seems to be the same issue as #2666 (locked issue) and it is still happening.

- i have upgraded winget to the latest preview version from GitHub (currently v1.4.3531)
- i have done a source reset --force
- i have changed internet connection to a secondary ISP

nothing helps.
**It seems to me that it is a CDN replication issue somewhere because on multiple runs of  winget upgrade --verbose-logs i get wildly different values for the age of the reference manifests and winget will consider them as already expired.**

run 1:
2022-12-28 10:51:25.495 [REPO] Adding to source references winget
2022-12-28 10:51:25.495 [REPO] Source past auto update time [5 mins]; it has been at least 5 mins

2022-12-28 10:51:25.497 [CORE] Setting action: Set, Type: Standard, Name: sources_metadata
2022-12-28 10:51:25.501 [REPO] Source past auto update time [5 mins]; it has been at least 27870291 mins

run 2:
2022-12-28 11:08:23.874 [REPO] Adding to source references winget
2022-12-28 11:08:23.874 [REPO] Source past auto update time [5 mins]; it has been at least 16 mins

2022-12-28 11:08:23.878 [CORE] Setting action: Set, Type: Standard, Name: sources_metadata
2022-12-28 11:08:23.885 [REPO] Source past auto update time [5 mins]; it has been at least 27870308 mins

run 3:
2022-12-28 11:20:05.340 [REPO] Adding to source references winget
2022-12-28 11:20:05.341 [REPO] Source past auto update time [5 mins]; it has been at least 11 mins

2022-12-28 11:20:05.344 [CORE] Setting action: Set, Type: Standard, Name: sources_metadata
2022-12-28 11:20:05.348 [REPO] Source past auto update time [5 mins]; it has been at least 27870320 mins

run 4:
2022-12-28 11:29:03.966 [REPO] Adding to source references winget
2022-12-28 11:29:03.967 [REPO] Source past auto update time [5 mins]; it has been at least 8 mins

2022-12-28 11:29:03.969 [CORE] Setting action: Set, Type: Standard, Name: sources_metadata
2022-12-28 11:29:03.983 [REPO] Source past auto update time [5 mins]; it has been at least 27870329 mins

sample log below in the details section:

<details>

```
2022-12-28 10:51:25.435 [CORE] WinGet, version [1.4.3531], activity [{E5A08D36-7D52-4987-AFBF-5F368FC81BE8}]
2022-12-28 10:51:25.436 [CORE] OS: Windows.Desktop v10.0.19045.2364
2022-12-28 10:51:25.436 [CORE] Command line Args: winget  upgrade --verbose-logs
2022-12-28 10:51:25.436 [CORE] Package: Microsoft.DesktopAppInstaller v1.19.3531.0
2022-12-28 10:51:25.436 [CORE] IsCOMCall:0; Caller: winget-cli
2022-12-28 10:51:25.473 [CLI ] WinGet invoked with arguments: 'upgrade' '--verbose-logs'
2022-12-28 10:51:25.474 [CLI ] Found subcommand: upgrade
2022-12-28 10:51:25.474 [CLI ] Leaf command to execute: root:upgrade
2022-12-28 10:51:25.486 [CORE] Setting action: Get, Type: Secure, Name: admin_settings
2022-12-28 10:51:25.490 [CORE] Admin settings was not found
2022-12-28 10:51:25.490 [CORE] Setting action: Get, Type: Secure, Name: admin_settings
2022-12-28 10:51:25.490 [CORE] Admin settings was not found
2022-12-28 10:51:25.491 [CORE] Setting action: Get, Type: Secure, Name: admin_settings
2022-12-28 10:51:25.491 [CORE] Admin settings was not found
2022-12-28 10:51:25.491 [CLI ] Executing command: upgrade
2022-12-28 10:51:25.491 [REPO] Additional sources GP is not enabled.
2022-12-28 10:51:25.491 [CORE] Setting action: Get, Type: Secure, Name: user_sources
2022-12-28 10:51:25.492 [CORE] Setting action: Get, Type: Secure, Name: admin_settings
2022-12-28 10:51:25.492 [CORE] Admin settings was not found
2022-12-28 10:51:25.493 [CORE] Adding chain to pinning configuration [Microsoft Store Source]:
DigiCert Global Root G2 : PublicKey
  Microsoft Azure TLS Issuing CA 01 : Subject | Issuer
    sfdataservice.microsoft.com : Subject | Issuer
2022-12-28 10:51:25.493 [CORE] Setting action: Get, Type: Standard, Name: sources_metadata
2022-12-28 10:51:25.494 [YAML] Detected UTF-8
2022-12-28 10:51:25.494 [REPO] GetCurrentSourceRefs: Source named 'microsoft.builtin.desktop.frameworks' from origin Default is hidden and is dropped.
2022-12-28 10:51:25.494 [REPO] Default source requested, multiple sources available, adding all to source references.
2022-12-28 10:51:25.495 [REPO] Adding to source references msstore
2022-12-28 10:51:25.495 [REPO] Adding to source references winget
2022-12-28 10:51:25.495 [REPO] Source past auto update time [5 mins]; it has been at least 5 mins
2022-12-28 10:51:25.495 [REPO] Additional sources GP is not enabled.
2022-12-28 10:51:25.495 [CORE] Setting action: Get, Type: Secure, Name: user_sources
2022-12-28 10:51:25.496 [CORE] Setting action: Get, Type: Secure, Name: admin_settings
2022-12-28 10:51:25.496 [CORE] Admin settings was not found
2022-12-28 10:51:25.496 [CORE] Adding chain to pinning configuration [Microsoft Store Source]:
DigiCert Global Root G2 : PublicKey
  Microsoft Azure TLS Issuing CA 01 : Subject | Issuer
    sfdataservice.microsoft.com : Subject | Issuer
2022-12-28 10:51:25.496 [CORE] Setting action: Get, Type: Standard, Name: sources_metadata
2022-12-28 10:51:25.496 [YAML] Detected UTF-8
2022-12-28 10:51:25.497 [CORE] Setting action: Set, Type: Standard, Name: sources_metadata
2022-12-28 10:51:25.501 [REPO] Source past auto update time [5 mins]; it has been at least 27870291 mins
2022-12-28 10:51:25.908 [FAIL] WindowsPackageManager.dll!00007FFC9E6ABF22: ReturnHr(1) tid(509c) 80072F7D     Msg:[winrt::hresult_error: An error occurred in the secure channel support] 

2022-12-28 10:51:25.908 [FAIL] WindowsPackageManager.dll!00007FFC9E533CF1: LogHr(2) tid(509c) 80072F7D 
2022-12-28 10:51:25.908 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(53)\WindowsPackageManager.dll!00007FFC9E6B7451: (caller: 00007FFC9E5806FE) LogHr(3) tid(509c) 80072F7D     Msg:[winrt::hresult_error: An error occurred in the secure channel support] 

2022-12-28 10:51:25.909 [REPO] Source add/update failed, waiting a bit and retrying: winget
2022-12-28 10:54:28.597 [FAIL] WindowsPackageManager.dll!00007FFC9E6ABF22: ReturnHr(2) tid(509c) 80072F7D     Msg:[winrt::hresult_error: An error occurred in the secure channel support] 

2022-12-28 10:54:28.597 [FAIL] WindowsPackageManager.dll!00007FFC9E533CF1: LogHr(5) tid(509c) 80072F7D 
2022-12-28 10:54:28.598 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(540)\WindowsPackageManager.dll!00007FFC9E6B6A33: (caller: 00007FFC9E478B3D) LogHr(6) tid(509c) 80072F7D     Msg:[winrt::hresult_error: An error occurred in the secure channel support] 

2022-12-28 10:54:28.598 [REPO] Failed to update source: winget
2022-12-28 10:54:28.598 [REPO] Multiple sources available, creating aggregated source.
2022-12-28 10:54:28.598 [REPO] Adding to aggregated source: msstore
2022-12-28 10:54:28.599 [REPO] Custom header not found.
2022-12-28 10:54:28.599 [REPO] Sending http GET request to: https://storeedgefd.dsx.mp.microsoft.com/v9.0/information
2022-12-28 10:54:28.599 [REPO] Http GET request details:
GET / HTTP/1.1

Content-Type: application/json

User-Agent: winget-cli WindowsPackageManager/1.4.3531 DesktopAppInstaller/Microsoft.DesktopAppInstaller v1.19.3531.0




2022-12-28 10:54:28.777 [REPO] Response status: 200
2022-12-28 10:54:28.777 [REPO] Response details:
HTTP/1.1 200 OK

Cache-Control: max-age=0, no-cache, no-store

Connection: keep-alive

Content-Length: 853

Content-Type: application/json; charset=utf-8

Date: Wed, 28 Dec 2022 08:54:28 GMT

Expires: Wed, 28 Dec 2022 08:54:28 GMT

MS-CV: 4OOUlbnuhU282TjE.0

Pragma: no-cache

Server: Microsoft-HTTPAPI/2.0

X-OSG-Served-By: Torus-WESTEUROPE_LEGACY00000M_1.0.0.0



{"$type":"Microsoft.Marketplace.Storefront.StoreEdgeFD.BusinessLogic.Response.PackageMetadata.PackageMetadataResponse, StoreEdgeFD","Data":{"$type":"Microsoft.Marketplace.Storefront.StoreEdgeFD.BusinessLogic.Response.PackageMetadata.PackageMetadataData, StoreEdgeFD","SourceIdentifier":"StoreEdgeFD","SourceAgreements":{"$type":"Microsoft.Marketplace.Storefront.StoreEdgeFD.BusinessLogic.Response.PackageMetadata.SourceAgreements, StoreEdgeFD","AgreementsIdentifier":"StoreEdgeFD","Agreements":[{"$type":"Microsoft.Marketplace.Storefront.StoreEdgeFD.BusinessLogic.Response.PackageManifest.AgreementDetail, StoreEdgeFD","AgreementLabel":"Terms of Transaction","AgreementUrl":"https://aka.ms/microsoft-store-terms-of-transaction"}]},"ServerSupportedVersions":["1.0.0","1.1.0"],"RequiredQueryParameters":["market"],"RequiredPackageMatchFields":["market"]}}
2022-12-28 10:54:28.778 [REPO] Custom header not found.
2022-12-28 10:54:28.778 [REPO] Sending http GET request to: https://storeedgefd.dsx.mp.microsoft.com/v9.0/information
2022-12-28 10:54:28.778 [REPO] Http GET request details:
GET / HTTP/1.1

Content-Type: application/json

User-Agent: winget-cli WindowsPackageManager/1.4.3531 DesktopAppInstaller/Microsoft.DesktopAppInstaller v1.19.3531.0




2022-12-28 10:54:28.862 [REPO] Response status: 200
2022-12-28 10:54:28.862 [REPO] Response details:
HTTP/1.1 200 OK

Cache-Control: max-age=0, no-cache, no-store

Connection: keep-alive

Content-Length: 853

Content-Type: application/json; charset=utf-8

Date: Wed, 28 Dec 2022 08:54:28 GMT

Expires: Wed, 28 Dec 2022 08:54:28 GMT

MS-CV: V75va1c/uUORkiKL.0

Pragma: no-cache

Server: Microsoft-HTTPAPI/2.0

X-OSG-Served-By: Torus-WESTEUROPE_Legacy00000E_1.0.0.0



{"$type":"Microsoft.Marketplace.Storefront.StoreEdgeFD.BusinessLogic.Response.PackageMetadata.PackageMetadataResponse, StoreEdgeFD","Data":{"$type":"Microsoft.Marketplace.Storefront.StoreEdgeFD.BusinessLogic.Response.PackageMetadata.PackageMetadataData, StoreEdgeFD","SourceIdentifier":"StoreEdgeFD","SourceAgreements":{"$type":"Microsoft.Marketplace.Storefront.StoreEdgeFD.BusinessLogic.Response.PackageMetadata.SourceAgreements, StoreEdgeFD","AgreementsIdentifier":"StoreEdgeFD","Agreements":[{"$type":"Microsoft.Marketplace.Storefront.StoreEdgeFD.BusinessLogic.Response.PackageManifest.AgreementDetail, StoreEdgeFD","AgreementLabel":"Terms of Transaction","AgreementUrl":"https://aka.ms/microsoft-store-terms-of-transaction"}]},"ServerSupportedVersions":["1.0.0","1.1.0"],"RequiredQueryParameters":["market"],"RequiredPackageMatchFields":["market"]}}
2022-12-28 10:54:28.863 [REPO] Adding to aggregated source: winget
2022-12-28 10:54:28.904 [CORE] Examining extension: PFN = Microsoft.Winget.Source_8wekyb3d8bbwe, ID = IndexDB
2022-12-28 10:54:28.904 [CORE] Found matching extension.
2022-12-28 10:54:29.008 [REPO] Opening SQLite Index for ImmutableRead at 'C:\Program Files\WindowsApps\Microsoft.Winget.Source_2022.1124.954.73_neutral__8wekyb3d8bbwe\Public\index.db'
2022-12-28 10:54:29.008 [SQL ] Opening SQLite connection #1: 'C:\Program Files\WindowsApps\Microsoft.Winget.Source_2022.1124.954.73_neutral__8wekyb3d8bbwe\Public\index.db' [1, 40]
2022-12-28 10:54:29.009 [SQL ] Preparing statement #1-1: select [value] from [metadata] where [name] = ?
2022-12-28 10:54:29.010 [SQL ] Binding statement #1-1: 1 => majorVersion
2022-12-28 10:54:29.010 [SQL ] Stepping statement #1-1
2022-12-28 10:54:29.011 [SQL ] Statement #1-1 has data
2022-12-28 10:54:29.011 [SQL ] Preparing statement #1-2: select [value] from [metadata] where [name] = ?
2022-12-28 10:54:29.011 [SQL ] Binding statement #1-2: 1 => minorVersion
2022-12-28 10:54:29.011 [SQL ] Stepping statement #1-2
2022-12-28 10:54:29.011 [SQL ] Statement #1-2 has data
2022-12-28 10:54:29.011 [SQL ] Enabling ICU
2022-12-28 10:54:29.011 [SQL ] Preparing statement #1-3: select [value] from [metadata] where [name] = ?
2022-12-28 10:54:29.011 [SQL ] Binding statement #1-3: 1 => lastwritetime
2022-12-28 10:54:29.011 [SQL ] Stepping statement #1-3
2022-12-28 10:54:29.012 [SQL ] Statement #1-3 has data
2022-12-28 10:54:29.012 [REPO] Opened SQLite Index with version [1.6], last write [2022-11-24 10:53:42.000]
2022-12-28 10:54:29.408 [CLI ] Checking Source agreements for source: msstore
2022-12-28 10:54:29.409 [REPO] Additional sources GP is not enabled.
2022-12-28 10:54:29.409 [CORE] Setting action: Get, Type: Secure, Name: user_sources
2022-12-28 10:54:29.409 [CORE] Setting action: Get, Type: Secure, Name: admin_settings
2022-12-28 10:54:29.409 [CORE] Admin settings was not found
2022-12-28 10:54:29.409 [CORE] Adding chain to pinning configuration [Microsoft Store Source]:
DigiCert Global Root G2 : PublicKey
  Microsoft Azure TLS Issuing CA 01 : Subject | Issuer
    sfdataservice.microsoft.com : Subject | Issuer
2022-12-28 10:54:29.410 [CORE] Setting action: Get, Type: Standard, Name: sources_metadata
2022-12-28 10:54:29.410 [YAML] Detected UTF-8
2022-12-28 10:54:29.410 [CLI ] Source agreements satisfied. Source: msstore
2022-12-28 10:54:29.410 [CLI ] Checking Source agreements for source: winget
2022-12-28 10:54:29.411 [REPO] Additional sources GP is not enabled.
2022-12-28 10:54:29.411 [CORE] Setting action: Get, Type: Secure, Name: user_sources
2022-12-28 10:54:29.411 [CORE] Setting action: Get, Type: Secure, Name: admin_settings
2022-12-28 10:54:29.411 [CORE] Admin settings was not found
2022-12-28 10:54:29.412 [CORE] Adding chain to pinning configuration [Microsoft Store Source]:
DigiCert Global Root G2 : PublicKey
  Microsoft Azure TLS Issuing CA 01 : Subject | Issuer
    sfdataservice.microsoft.com : Subject | Issuer
2022-12-28 10:54:29.412 [CORE] Setting action: Get, Type: Standard, Name: sources_metadata
2022-12-28 10:54:29.412 [YAML] Detected UTF-8
2022-12-28 10:54:29.413 [CLI ] Source agreements satisfied. Source: winget
2022-12-28 10:54:29.413 [REPO] Creating PredefinedInstalledSource with filter [None]
2022-12-28 10:54:29.413 [REPO] Creating new SQLite Index [4294967295.4294967295] at ':memory:'
2022-12-28 10:54:29.413 [SQL ] Opening SQLite connection #2: ':memory:' [6, 0]
2022-12-28 10:54:29.414 [SQL ] Preparing statement #2-4: 
CREATE TABLE [metadata](
    [name] TEXT PRIMARY KEY NOT NULL,
    [value] TEXT NOT NULL)

2022-12-28 10:54:29.414 [SQL ] Stepping statement #2-4
2022-12-28 10:54:29.415 [SQL ] Statement #2-4 has completed
2022-12-28 10:54:29.415 [SQL ] Enabling ICU
2022-12-28 10:54:29.521 [SQL ] Preparing statement #2-5: SAVEPOINT [sqliteindex_createnew]
2022-12-28 10:54:29.521 [SQL ] Preparing statement #2-6: ROLLBACK TO [sqliteindex_createnew]
2022-12-28 10:54:29.521 [SQL ] Preparing statement #2-7: RELEASE [sqliteindex_createnew]
2022-12-28 10:54:29.521 [SQL ] Begin savepoint: sqliteindex_createnew
2022-12-28 10:54:29.521 [SQL ] Stepping statement #2-5
2022-12-28 10:54:29.522 [SQL ] Statement #2-5 has completed
2022-12-28 10:54:29.522 [SQL ] Preparing statement #2-8: SAVEPOINT [version_setschemaversion]
2022-12-28 10:54:29.522 [SQL ] Preparing statement #2-9: ROLLBACK TO [version_setschemaversion]
2022-12-28 10:54:29.522 [SQL ] Preparing statement #2-10: RELEASE [version_setschemaversion]
2022-12-28 10:54:29.522 [SQL ] Begin savepoint: version_setschemaversion
2022-12-28 10:54:29.522 [SQL ] Stepping statement #2-8
2022-12-28 10:54:29.522 [SQL ] Statement #2-8 has completed
2022-12-28 10:54:29.522 [SQL ] Preparing statement #2-11: insert or replace into [metadata] ([name], [value]) values (?, ?)
2022-12-28 10:54:29.522 [SQL ] Binding statement #2-11: 1 => majorVersion
2022-12-28 10:54:29.522 [SQL ] Binding statement #2-11: 2 => 1
2022-12-28 10:54:29.522 [SQL ] Stepping statement #2-11
2022-12-28 10:54:29.522 [SQL ] Statement #2-11 has completed
2022-12-28 10:54:29.522 [SQL ] Preparing statement #2-12: insert or replace into [metadata] ([name], [value]) values (?, ?)
2022-12-28 10:54:29.522 [SQL ] Binding statement #2-12: 1 => minorVersion
2022-12-28 10:54:29.522 [SQL ] Binding statement #2-12: 2 => 6
2022-12-28 10:54:29.522 [SQL ] Stepping statement #2-12
2022-12-28 10:54:29.522 [SQL ] Statement #2-12 has completed
2022-12-28 10:54:29.522 [SQL ] Commit savepoint: version_setschemaversion
2022-12-28 10:54:29.522 [SQL ] Stepping statement #2-10
2022-12-28 10:54:29.522 [SQL ] Statement #2-10 has completed
2022-12-28 10:54:29.522 [SQL ] Preparing statement #2-13: SAVEPOINT [createtables_v1_6]
2022-12-28 10:54:29.522 [SQL ] Preparing statement #2-14: ROLLBACK TO [createtables_v1_6]
2022-12-28 10:54:29.522 [SQL ] Preparing statement #2-15: RELEASE [createtables_v1_6]
2022-12-28 10:54:29.523 [SQL ] Begin savepoint: createtables_v1_6
2022-12-28 10:54:29.523 [SQL ] Stepping statement #2-13
2022-12-28 10:54:29.523 [SQL ] Statement #2-13 has completed
2022-12-28 10:54:29.523 [SQL ] Preparing statement #2-16: SAVEPOINT [createtables_v1_5]
2022-12-28 10:54:29.523 [SQL ] Preparing statement #2-17: ROLLBACK TO [createtables_v1_5]
2022-12-28 10:54:29.523 [SQL ] Preparing statement #2-18: RELEASE [createtables_v1_5]
2022-12-28 10:54:29.523 [SQL ] Begin savepoint: createtables_v1_5
2022-12-28 10:54:29.523 [SQL ] Stepping statement #2-16
2022-12-28 10:54:29.523 [SQL ] Statement #2-16 has completed
2022-12-28 10:54:29.523 [SQL ] Preparing statement #2-19: SAVEPOINT [createtables_v1_4]
2022-12-28 10:54:29.523 [SQL ] Preparing statement #2-20: ROLLBACK TO [createtables_v1_4]
2022-12-28 10:54:29.523 [SQL ] Preparing statement #2-21: RELEASE [createtables_v1_4]
2022-12-28 10:54:29.523 [SQL ] Begin savepoint: createtables_v1_4
2022-12-28 10:54:29.523 [SQL ] Stepping statement #2-19
2022-12-28 10:54:29.523 [SQL ] Statement #2-19 has completed
2022-12-28 10:54:29.523 [SQL ] Preparing statement #2-22: SAVEPOINT [createtables_v1_3]
2022-12-28 10:54:29.523 [SQL ] Preparing statement #2-23: ROLLBACK TO [createtables_v1_3]
2022-12-28 10:54:29.523 [SQL ] Preparing statement #2-24: RELEASE [createtables_v1_3]
2022-12-28 10:54:29.523 [SQL ] Begin savepoint: createtables_v1_3
2022-12-28 10:54:29.523 [SQL ] Stepping statement #2-22
2022-12-28 10:54:29.523 [SQL ] Statement #2-22 has completed
2022-12-28 10:54:29.523 [SQL ] Preparing statement #2-25: SAVEPOINT [createtables_v1_2]
2022-12-28 10:54:29.524 [SQL ] Preparing statement #2-26: ROLLBACK TO [createtables_v1_2]
2022-12-28 10:54:29.524 [SQL ] Preparing statement #2-27: RELEASE [createtables_v1_2]
2022-12-28 10:54:29.524 [SQL ] Begin savepoint: createtables_v1_2
2022-12-28 10:54:29.524 [SQL ] Stepping statement #2-25
2022-12-28 10:54:29.524 [SQL ] Statement #2-25 has completed
2022-12-28 10:54:29.524 [SQL ] Preparing statement #2-28: SAVEPOINT [createtables_v1_1]
2022-12-28 10:54:29.524 [SQL ] Preparing statement #2-29: ROLLBACK TO [createtables_v1_1]
2022-12-28 10:54:29.524 [SQL ] Preparing statement #2-30: RELEASE [createtables_v1_1]
2022-12-28 10:54:29.524 [SQL ] Begin savepoint: createtables_v1_1
2022-12-28 10:54:29.524 [SQL ] Stepping statement #2-28
2022-12-28 10:54:29.524 [SQL ] Statement #2-28 has completed
2022-12-28 10:54:29.524 [SQL ] Preparing statement #2-31: SAVEPOINT [ids_create_v1_1]
2022-12-28 10:54:29.524 [SQL ] Preparing statement #2-32: ROLLBACK TO [ids_create_v1_1]
2022-12-28 10:54:29.524 [SQL ] Preparing statement #2-33: RELEASE [ids_create_v1_1]
2022-12-28 10:54:29.524 [SQL ] Begin savepoint: ids_create_v1_1
2022-12-28 10:54:29.524 [SQL ] Stepping statement #2-31
2022-12-28 10:54:29.524 [SQL ] Statement #2-31 has completed
2022-12-28 10:54:29.524 [SQL ] Preparing statement #2-34: CREATE TABLE [ids](rowid INTEGER PRIMARY KEY, [id] TEXT NOT NULL)
2022-12-28 10:54:29.524 [SQL ] Stepping statement #2-34
2022-12-28 10:54:29.525 [SQL ] Statement #2-34 has completed
2022-12-28 10:54:29.525 [SQL ] Preparing statement #2-35: CREATE UNIQUE INDEX [ids_pkindex] ON [ids]([id])
2022-12-28 10:54:29.525 [SQL ] Stepping statement #2-35
2022-12-28 10:54:29.525 [SQL ] Statement #2-35 has completed
2022-12-28 10:54:29.525 [SQL ] Commit savepoint: ids_create_v1_1
2022-12-28 10:54:29.525 [SQL ] Stepping statement #2-33
2022-12-28 10:54:29.525 [SQL ] Statement #2-33 has completed
2022-12-28 10:54:29.526 [SQL ] Preparing statement #2-36: SAVEPOINT [names_create_v1_1]
2022-12-28 10:54:29.526 [SQL ] Preparing statement #2-37: ROLLBACK TO [names_create_v1_1]
2022-12-28 10:54:29.526 [SQL ] Preparing statement #2-38: RELEASE [names_create_v1_1]
2022-12-28 10:54:29.526 [SQL ] Begin savepoint: names_create_v1_1
2022-12-28 10:54:29.526 [SQL ] Stepping statement #2-36
2022-12-28 10:54:29.526 [SQL ] Statement #2-36 has completed
2022-12-28 10:54:29.526 [SQL ] Preparing statement #2-39: CREATE TABLE [names](rowid INTEGER PRIMARY KEY, [name] TEXT NOT NULL)
2022-12-28 10:54:29.526 [SQL ] Stepping statement #2-39
2022-12-28 10:54:29.526 [SQL ] Statement #2-39 has completed
2022-12-28 10:54:29.526 [SQL ] Preparing statement #2-40: CREATE UNIQUE INDEX [names_pkindex] ON [names]([name])
2022-12-28 10:54:29.527 [SQL ] Stepping statement #2-40
2022-12-28 10:54:29.527 [SQL ] Statement #2-40 has completed
2022-12-28 10:54:29.527 [SQL ] Commit savepoint: names_create_v1_1
2022-12-28 10:54:29.527 [SQL ] Stepping statement #2-38
2022-12-28 10:54:29.527 [SQL ] Statement #2-38 has completed
2022-12-28 10:54:29.527 [SQL ] Preparing statement #2-41: SAVEPOINT [monikers_create_v1_1]
2022-12-28 10:54:29.527 [SQL ] Preparing statement #2-42: ROLLBACK TO [monikers_create_v1_1]
2022-12-28 10:54:29.527 [SQL ] Preparing statement #2-43: RELEASE [monikers_create_v1_1]
2022-12-28 10:54:29.527 [SQL ] Begin savepoint: monikers_create_v1_1
2022-12-28 10:54:29.527 [SQL ] Stepping statement #2-41
2022-12-28 10:54:29.528 [SQL ] Statement #2-41 has completed
2022-12-28 10:54:29.528 [SQL ] Preparing statement #2-44: CREATE TABLE [monikers](rowid INTEGER PRIMARY KEY, [moniker] TEXT NOT NULL)
2022-12-28 10:54:29.528 [SQL ] Stepping statement #2-44
2022-12-28 10:54:29.529 [SQL ] Statement #2-44 has completed
2022-12-28 10:54:29.529 [SQL ] Preparing statement #2-45: CREATE UNIQUE INDEX [monikers_pkindex] ON [monikers]([moniker])
2022-12-28 10:54:29.529 [SQL ] Stepping statement #2-45
2022-12-28 10:54:29.530 [SQL ] Statement #2-45 has completed
2022-12-28 10:54:29.530 [SQL ] Commit savepoint: monikers_create_v1_1
2022-12-28 10:54:29.530 [SQL ] Stepping statement #2-43
2022-12-28 10:54:29.530 [SQL ] Statement #2-43 has completed
2022-12-28 10:54:29.530 [SQL ] Preparing statement #2-46: SAVEPOINT [versions_create_v1_1]
2022-12-28 10:54:29.530 [SQL ] Preparing statement #2-47: ROLLBACK TO [versions_create_v1_1]
2022-12-28 10:54:29.530 [SQL ] Preparing statement #2-48: RELEASE [versions_create_v1_1]
2022-12-28 10:54:29.530 [SQL ] Begin savepoint: versions_create_v1_1
2022-12-28 10:54:29.530 [SQL ] Stepping statement #2-46
2022-12-28 10:54:29.530 [SQL ] Statement #2-46 has completed
2022-12-28 10:54:29.530 [SQL ] Preparing statement #2-49: CREATE TABLE [versions](rowid INTEGER PRIMARY KEY, [version] TEXT NOT NULL)
2022-12-28 10:54:29.531 [SQL ] Stepping statement #2-49
2022-12-28 10:54:29.531 [SQL ] Statement #2-49 has completed
2022-12-28 10:54:29.531 [SQL ] Preparing statement #2-50: CREATE UNIQUE INDEX [versions_pkindex] ON [versions]([version])
2022-12-28 10:54:29.531 [SQL ] Stepping statement #2-50
2022-12-28 10:54:29.532 [SQL ] Statement #2-50 has completed
2022-12-28 10:54:29.533 [SQL ] Commit savepoint: versions_create_v1_1
2022-12-28 10:54:29.533 [SQL ] Stepping statement #2-48
2022-12-28 10:54:29.533 [SQL ] Statement #2-48 has completed
2022-12-28 10:54:29.533 [SQL ] Preparing statement #2-51: SAVEPOINT [channels_create_v1_1]
2022-12-28 10:54:29.533 [SQL ] Preparing statement #2-52: ROLLBACK TO [channels_create_v1_1]
2022-12-28 10:54:29.533 [SQL ] Preparing statement #2-53: RELEASE [channels_create_v1_1]
2022-12-28 10:54:29.533 [SQL ] Begin savepoint: channels_create_v1_1
2022-12-28 10:54:29.533 [SQL ] Stepping statement #2-51
[... snipped remaining lines as they are not relevant ...]
```
</details>

### Steps to reproduce

not sure how to to reproduce, seems to be a CDN replication issue

### Expected behavior

just works

### Actual behavior

error message:  Failed in attempting to update the source: winget

### Environment

```shell
C:\WINDOWS\system32>winget --info
Windows Package Manager v1.4.3531
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2364
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.3531.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

and the settings.json file is the default one:

```

{
    "$schema": "https://aka.ms/winget-settings.schema.json",

    // For documentation on these settings, see: https://aka.ms/winget-settings
    // "source": {
    //    "autoUpdateIntervalInMinutes": 5
    // },
}
```

**Comment by denelon** [comment] 2022-12-28 18:59
Duplicate of #2718 

We've pinned Issue 2718 to track these intermittent issues where the CDN is serving a zero-byte file.

**Closed by denelon** 2022-12-28 18:59 UTC
Labels: Needs-Triage
