### ISSUE TITLE
winget import with app store apps always returns msstore source not installed

### ISSUE THREAD

**Issue by VArterJr** [microsoft/winget-cli#1556] opened 2021-10-07 00:32 UTC
# Brief description of your issue
With the new GA Windows 11 Enterprise ISO (22000.194) running the below command does not work with the json file that worked on Win 11 beta and Win 10 with latest winget. I even tried using the leading-edge version (1.1.12701) and adding msstore experimental settings back to the winget settings file. It always generates the message: "Source required for import is not installed: msstore"

`winget import -i mylifstofapps.json`

I've confirmed with `winget source list` that it is enabled. I can also force a manual of items one by one with winget commands like below and they work. It is only the import that just doesn't seem to work on any machine with the GA of Win 11.

`winget source list`

Name    Argument
-----------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
winget  https://winget.azureedge.net/cache

# Steps to reproduce
Be on Win 11 Enterprise 22000.194 and either the GA shipping version of winget with Win 11 or the latest 1.1.12701. Import a json file that has any number of msstore source items to install. Those same items install fine with `winget install`.

# Expected behavior
Since it worked on Win 11 beta and Win 10 with the latest winget, I would expect it to work here too. I've scoured what documentation there is and don't see any changes in format of the import file that would make a difference.

# Actual behavior
The import with fail with `Source required for import is not installed: msstore` unless you remove the section for that source in your json file to import.

# Environment

```none
Windows Package Manager v1.1.12701
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.194
Package: Microsoft.DesktopAppInstaller v1.16.12701.0

Any other software? Microsoft Office (current 365 version)
```

**Comment by JohnMcPMS** [comment] 2021-10-07 18:01
> The import command should work, but it's likely you would need to use the "Id" value from the current search results to get import to install the correct package from the msstore source.

Yes, please post your import file.  It is most likely behind the scenes changes between experimental and release that have caused that one string to be invalid now.

> Edit: something else interesting I found while investigating this is that `winget export` doesn't export apps installed from the Microsoft Store since it can't find them.

Spoilers; I'm doing work right now that will at least enable this to work for things installed from the Store via winget (and some from the Store app itself; its complicated).

**Comment by VArterJr** [comment] 2021-10-08 16:44
Here is an example (smaller than my real one). Please note I've tried this URL for the Argument in Source included in the json file as well as what `winget source list` shows which is https://storeedgefd.dsx.mp.microsoft.com/v9.0. Neither works
[teststoreapps.json.txt](https://github.com/microsoft/winget-cli/files/7312920/teststoreapps.json.txt) 

(Note: I had to change file name to .txt to upload it here.)

**Comment by VArterJr** [comment] 2021-10-11 16:10
OK. This ticket can be closed. Do you want me to close it with comment or will someone from the team?

**Comment by denelon** [comment] 2021-10-11 16:15
Duplicate of #1562

**Closed by denelon** 2021-10-11 16:15 UTC
Labels: Issue-Bug, msstore
