### ISSUE TITLE
Upgrading all leads to reinstalling of the same package several times

### ISSUE THREAD

**Issue by aarjav24** [microsoft/winget-cli#1388] opened 2021-08-21 09:27 UTC
# Brief description of your issue
When using the command "winget upgrade --all", two packages get upgraded, or the latest version gets installed. When running the command again, the same process is repeated instead of notifying that there are no upgrades available.

# Steps to reproduce
As stated above, just use the command "winget upgrade --all" more than once and you'll see the same set of packages either being upgraded or reinstalled to their latest versions.

# Expected behavior
A message should display saying that upgrades aren't available.

# Actual behavior
Same packages are being reinstalled or upgraded over and over again.
# Environment

```none
[winget --info]
Windows Package Manager version
Windows: Windows.Desktop version
Package: Microsoft.DesktopAppInstaller version

Any other software?
```

![image](https://user-images.githubusercontent.com/68058926/130317425-06398eb5-9f61-4781-94a1-ab4ac11f6f9e.png)

**Comment by denelon** [comment] 2021-08-23 15:49
Duplicate of #1075

**Closed by denelon** 2021-08-23 15:49 UTC
Labels: Needs-Triage
