### ISSUE TITLE
Implement self update for manual installer

### ISSUE THREAD

**Issue by maljaroudi** [microsoft/winget-cli#1353] opened 2021-08-06 18:24 UTC
# Description of the new feature/enhancement
Currently, the only "good" way to install winget is through the app store. However, in comparison to other operating systems package managers or even applications such as chocolatey, users can install the latest version through the package manager itself.

Microsoft Store may be a solution to automatic updates, but relying on another app to update the package manager is not a good approach, especially since Microsoft Store isn't the best software when it comes to installing applications on multiple users or for silent installation for example.

The idea is to add winget inside winget such that users can simply upgrade the package manager using 
`winget upgrade winget` command.

**Comment by ImJoakim** [comment] 2021-08-06 18:29
Duplicate of #505

**Closed** 2021-08-06 18:32 UTC
Labels: Issue-Feature, Needs-Triage
