### ISSUE TITLE
winget upgrade --all aways tries to upgrade vscode

### ISSUE THREAD

**Issue by LuanVSO** [microsoft/winget-cli#976] opened 2021-05-20 22:02 UTC
# Brief description of your issue
Winget always sees vscode as if it is not up-to-date. i think it is because the version number on the manifest includes the commit id, but the version reported back from `Winget list` doesn't.

# Steps to reproduce

```
winget install vscode --scope machine
```
```
winget list vscode
```
# Expected behavior

Winget should detect that the most recent version of vscode is already installed

# Actual behavior

it thinks there's a new update for vscode

# Environment

```none
Windows Package Manager version: v0.4.11391
Windows: Windows.Desktop version: v10.0.19043.985
Package: Microsoft.DesktopAppInstaller version: v1.11.11391.0

Any other software?
Visual Studio Code
```
# Recommended fix
just remove the commit id from the version number in the manifest

**Comment by denelon** [comment] 2021-05-20 22:36
@LuanVSO this is primarily related to the version numbers in the manifest with a four part identifier and the entry in Add/Remove Programs having a three part identifier. I moved this Issue to the client to see if this might be something generic we need to consider in the client when we do our comparisons for tracking what version of a package we installed vs. what we see in Add/Remove programs. This could likely be addressed by modifying the "PackageVersion" in the manifest, but I want to give the Visual Studio Code team an opportunity to evaluate before changing their manifests.

**Comment by OfficialEsco** [comment] 2021-05-21 10:46
Should this thread maybe include other Packages that do the same since winget upgrade is out of experimental and actually works?

![image](https://user-images.githubusercontent.com/15158490/119124591-1dbcac00-ba31-11eb-89cf-80d8b07af125.png)
7-Zip version `21.01-alpha` is being selected over `21.02 alpha`
Battle.net and Portmaster don't show a version, which then leads to a Unknown download loop
CPU-Z is dumb and released a update with the same version number/download link, easy manifest fix aslong as someone don't submit it again..

**Comment by denelon** [comment] 2021-05-21 14:57
@OfficialEsco, We use alpha sort on each token in the version string. If the 21.02 alpha is updated to 21.02-alpha it should work.

**Comment by chausner** [comment] 2021-05-21 16:20
I have encountered a similar case with Anvil Studio:

> Anvil Studio                 WillowSoftware.AnvilStudio            20.12.03         2020.12.03        winget

The official version string is 2020.12.03 which is also what's in the manifest but the version in Add/Remove programs is 20.12.03. Changing the version format in the manifest accordingly is no long-term solution, I think, as somebody else might change it again with an update, breaking it. Maybe an alternative version field could help in the manifest with the format to use to correlate entries in Add/Remove Programs.

**Comment by chausner** [comment] 2021-05-21 16:31
I think some of these issues could potentially be detected automatically in CI during manifest creation. After installing a program, it could be checked whether the program added an entry to Add/Remove Programs with a version number that matches the one in the manifest, and if not require the version to be adapted or require the specification of an alternative version field.

**Comment by denelon** [comment] 2021-05-21 17:00
@chausner, that's a great idea! You mind creating that as a [Feature Request/Idea](https://github.com/microsoft/winget-cli/issues/new/choose) in the winget-pkgs repository?

**Comment by chausner** [comment] 2021-05-21 18:21
> @chausner, that's a great idea! You mind creating that as a [Feature Request/Idea](https://github.com/microsoft/winget-cli/issues/new/choose) in the winget-pkgs repository?

I created https://github.com/microsoft/winget-pkgs/issues/13620 and https://github.com/microsoft/winget-pkgs/issues/13622.

**Comment by OfficialEsco** [comment] 2021-05-22 11:45
@denelon i renamed the 7ZipAlpha manifest #13613 and its still upgrading to 21.01-alpha
![image](https://user-images.githubusercontent.com/15158490/119225329-73fa1f80-bb03-11eb-881e-7306c080e114.png)

Can it be because 21.01 is installed as exe?

**Comment by jedieaston** [comment] 2021-05-22 22:25
@lszomoru Is there a particular reason the four part identifier is used at all for VSCode? In release notes they only ever use the three part one. I can understand for Insiders (since you want to tie it back to the commit in microsoft/code), but not for stable.

**Comment by denelon** [comment] 2021-05-23 18:40
@OfficialEsco we do try to ensure to use the same "InstallerType" used previously. We're running into a similar challenge with PowerToys as it is an .msi file inside of a .exe that performs bootstrapping work.

**Comment by jedieaston** [comment] 2021-05-24 12:51
I know I said this somewhere else, but once we get dependency support, we should see if the PowerToys team would be willing to supply a standalone MSI for WinGet so we can upgrade it the usual way. I need to open an issue about that when I have a second...

**Comment by psychelzh** [comment] 2021-05-24 14:46
Other programs that are constantly been upgraded:

* Amazon Kindle [Amazon.Kindle]
* LockHunter [CrystalRich.LockHunter]
* TechPowerUp GPU-Z [TechPowerUp.GPU-Z]
* Visual Studio Code [Microsoft.VisualStudioCode]

What's more, TechPowerUp GPU-Z is installed twice.

![image](https://user-images.githubusercontent.com/13306020/119364846-ede7ff80-bce1-11eb-9c0e-411a35cf6808.png)

**Comment by denelon** [comment] 2021-05-24 14:53
@psychelzh I've seen a few installers that support "side by side" install for different versions. I'm wondering if a previous call to upgrade actually "upgraded" more than one of them. Could you submit feedback ([Windows]+[f] - "Apps" & "Windows Package Manager") and share the link here so we can look at logs?

**Comment by psychelzh** [comment] 2021-05-24 15:14
@denelon Is it this: https://aka.ms/AAco74f

**Comment by Shatungoo** [comment] 2021-05-24 20:53
Some other apps. Most of them from MS, and maybe 10+ apps from another vendors was successfully updated:

Mozilla.FirefoxDeveloperEdition -it was updated to latest version, but i still have it in upgrade command
Microsoft.VisualStudioCode  - it was updated, but winget tries to upgrade it one more time
Microsoft.Teams - it was updated to latest version, but still in the list, the second upgrade command failed
Microsoft.PowerToys    -upgrade didn't start at all        
Microsoft.dotnetRuntime   -upgrade was successfull but i still have an old version. This was discussed in previous ticket, but it was closed as fixed (https://github.com/microsoft/winget-cli/issues/752#issuecomment-840049327)

Logs:
[DiagOutputDir.zip](https://github.com/microsoft/winget-cli/files/6534903/DiagOutputDir.zip)
       

`PS C:\Users\Leanid_Miron> winget -v
v0.4.11391 Preview
PS C:\Users\Leanid_Miron> winget upgrade --all
Found Microsoft Teams [Microsoft.Teams]
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://statics.teams.cdn.office.net/production-windows-x64/1.4.00.11161/Teams_windows_x64.msi
  ██████████████████████████████   107 MB /  107 MB
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1638
Installer log is available at: C:\Users\Leanid_Miron\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Microsoft.Teams.1.4.00.11161-2021-05-24-23-32-41.501.log

Found Visual Studio Code [Microsoft.VisualStudioCode]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://az764295.vo.msecnd.net/stable/054a9295330880ed74ceaedda236253b4f39a335/VSCodeSetup-x64-1.56.2.exe
  ██████████████████████████████  76.3 MB / 76.3 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Found .NET Core Runtime [Microsoft.dotnetRuntime]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.visualstudio.microsoft.com/download/pr/6279dc90-f437-4481-82a5-73dd9f97da06/6519ef44735fd31115b9b1a81d6ff1e8/windowsdesktop-runtime-5.0.6-win-x64.exe
  ██████████████████████████████  51.9 MB / 51.9 MB
Successfully verified installer hash
Starting package install...
Successfully installed

PS C:\Users\Leanid_Miron> winget upgrade
Name                      Id                              Version      Available         Source
-----------------------------------------------------------------------------------------------
Firefox Developer Edition Mozilla.FirefoxDeveloperEdition 89.0         89.0b9            winget
Microsoft Teams           Microsoft.Teams                 1.2.0.19260  1.4.00.11161      winget
Visual Studio Code        Microsoft.VisualStudioCode      1.56.2       1.56.2.054a929533 winget
PowerToys                 Microsoft.PowerToys             0.31.2       0.37.2            winget
.NET Core Runtime         Microsoft.dotnetRuntime         3.1.11.29516 5.0.6.30021       winget`

**Comment by Karl-WE** [comment] 2021-05-25 20:09
as on topic of VSC I can repro it.
There is no error on upgrade but the root cause seems to be this wrong version number in the YAML. 
Was same for Zoom.Zoom (fixed at the moment)

![image](https://user-images.githubusercontent.com/45657752/119561694-ca868880-bda5-11eb-8505-6004568528ee.png)

**Comment by OfficialEsco** [comment] 2021-05-25 20:52
@Karl-WE These issues mainly comes from Bots updating Packages with weird/inconsistent version number in the download link/after install...

I see you've struggled with 7-Zip too, which comes from us replacing the EXE installer with the MSI installer (since people here would prefer a MSI install), however @denelon explained in this thread that WinGet will try to use the same InstallerType, so for future manifests we will have to add the MSI as Primary and the EXE as Secondary so the upgrade works..

**Comment by Karl-WE** [comment] 2021-05-25 21:36
Makes sense thank you @OfficialEsco

**Comment by leonardder** [comment] 2021-05-27 06:22
I have a similar issue with the NVAccess.NVDA package, though it incists on downgrading. I have version 'alpha-22934,e05715d3' installed whereas winget tries to upgrade (or rather downgrade) to version 2020.4, which is the most recent version.
Now my question is, how does winget determine the installed version? It seems that the Version, VersionMajor and VersionMinor fields in the uninstall registry key are ignored. Also what might make it more difficult for winget is that NVDA has a 4 part version scheme for its full version, e.g. 2021.2.0.22934 for the version with display version alpha-22934,e05715d3.

See also https://github.com/nvaccess/nvda/issues/12469

**Comment by narnaud** [comment] 2021-05-27 13:17
I see multiple issues myself, see here:

![image](https://user-images.githubusercontent.com/469305/119832298-56abc380-befe-11eb-9ee0-4351f5588884.png)

1) RocketChat and OpenVPN do not upgrade, when I explicitely ask one to upgrade, there's the text: "No applicable update found."

2) Blender is constantly updating, even if it's already in version 2.92.0 (could be a problem from Blender installer)

3) The rest is always updated all the time

**Comment by OfficialEsco** [comment] 2021-05-27 15:12
@narnaud
* Rocket.Chat probably failed because there was no exe installer available.
* OpenVPN is failing because 2.4.9 is installed as EXE and 4.5+ does not release EXE's anymore.
* VS Pro, VS Code and MS Teams might have a machinewide installer which is not updated all the time (Your user installed which you use is tho)
* Blender ill take a look at soon

**Comment by narnaud** [comment] 2021-05-28 04:30
@OfficialEsco Thank you, that fixes most of the issues, I still have VS Code and VS Pro reinstalling, will try to understand why later.

**Comment by jedieaston** [comment] 2021-06-02 14:37
I've proposed a solution in #1073.

**Comment by lszomoru** [comment] 2021-06-23 09:06
I have made the necessary changes to the pipeline that publishes the Visual Studio Code winget package. We have dropped the 4th segment of the version number, so now the version in the winget manifest matches the version number in add/remote programs.

@denelon, can you please go ahead and close the issue as I do not seem to have the necessary permissions. Thanks!

**Comment by denelon** [comment] 2021-06-23 15:40
@lszomoru thank you for making the changes!

**Closed by denelon** 2021-06-23 15:40 UTC
Labels: Catalog-Health, Issue-Bug
