### ISSUE TITLE
Package dependency is not available mid-installation

### ISSUE THREAD

**Issue by hamnarauf** [microsoft/winget-cli#3668] opened 2023-09-25 05:43 UTC
### Brief description of your issue

Installing Dev Home in a fresh installation of Windows 11 fails due to a dependency error. Winget downloads the dependency but it is not being recognized and throws an error.

![image](https://github.com/microsoft/winget-cli/assets/77397009/3766be62-fc1e-4a7a-805a-413f0d712e38)

Even though winget downloads and installs the dependency, the logs show that the installation still fails due to missing dependency
[WinGet-2023-09-24-17-33-48.170.log](https://github.com/microsoft/winget-cli/files/12711499/WinGet-2023-09-24-17-33-48.170.log)

Relevant logs snippet

```text
2023-09-24 17:35:10.896 [CLI ] Starting: 'C:\Users\HAMNAR~1\AppData\Local\Temp\WinGet\Microsoft.WindowsAppRuntime.1.3.1.3.2\windowsappruntimeinstall-x64.exe' with arguments ''
2023-09-24 17:35:34.157 [REPO] Creating PredefinedInstalledSource with filter [ARP]
2023-09-24 17:35:34.157 [REPO] Creating new SQLite Index with version [Latest] at ':memory:'
2023-09-24 17:35:34.157 [SQL ] Opening SQLite connection #10: ':memory:' [6, 0]
2023-09-24 17:35:34.331 [REPO] Reading MSI UpgradeCodes
2023-09-24 17:35:34.375 [REPO] Examining ARP entries for Machine | X64
2023-09-24 17:35:34.543 [REPO] Examining ARP entries for Machine | X86
2023-09-24 17:35:34.726 [REPO] Reading MSI UpgradeCodes
2023-09-24 17:35:34.760 [REPO] Examining ARP entries for User | X64
2023-09-24 17:35:35.087 [CLI ] During package install, 0 changes to ARP were observed, 0 matches were found for the package, and 0 packages were in both
2023-09-24 17:35:35.087 [CLI ] No single entry was determined to be associated with the package
2023-09-24 17:35:35.114 [REPO] Opening SQLite Index for ReadWrite at 'C:\Users\Hamna Rauf\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Microsoft.Winget.Source_8wekyb3d8bbwe\installed.db'
2023-09-24 17:35:35.114 [SQL ] Opening SQLite connection #11: 'C:\Users\Hamna Rauf\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Microsoft.Winget.Source_8wekyb3d8bbwe\installed.db' [2, 0]
2023-09-24 17:35:35.117 [REPO] Opened SQLite Index with version [1.3], last write [2023-08-31 15:02:29.000]
2023-09-24 17:35:35.266 [CLI ] Removing installer: C:\Users\HAMNAR~1\AppData\Local\Temp\WinGet\Microsoft.WindowsAppRuntime.1.3.1.3.2\windowsappruntimeinstall-x64.exe
2023-09-24 17:35:35.295 [CLI ] Successfully refreshed process PATH environment variable.
2023-09-24 17:35:55.658 [CLI ] Installer hash verified
2023-09-24 17:35:56.674 [CORE] Starting StagePackageAsync operation #0: https://github.com/microsoft/devhome/releases/download/v0.503.261.0/Windows.DevHome_0.503.261.0.msixbundle
2023-09-24 17:35:56.676 [CORE] Begin waiting for operation #0
2023-09-24 17:35:56.676 [CORE] Begin blocking for operation #0
2023-09-24 17:39:35.779 [CORE] Successfully completed #0
2023-09-24 17:39:35.780 [CORE] Starting RegisterPackageByFullNameAsync operation #1: Microsoft.Windows.DevHome_0.503.261.0_neutral_~_8wekyb3d8bbwe
2023-09-24 17:39:35.818 [CORE] Begin waiting for operation #1
2023-09-24 17:39:35.818 [CORE] Begin blocking for operation #1
2023-09-24 17:39:35.957 [CORE] Deployment operation #1: Windows cannot install package Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.WindowsAppRuntime.1.3" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 3000.934.1904.0, along with this package to install.
2023-09-24 17:39:35.957 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(191)\WindowsPackageManager.dll!00007FF8270C3311: (caller: 00007FF827018E80) Exception(4) tid(479c) 80073CF3 Package failed updates, dependency or conflict validation.

2023-09-24 17:39:35.958 [CORE] Starting RemovePackage operation #2: Microsoft.Windows.DevHome_0.503.261.0_neutral_~_8wekyb3d8bbwe
2023-09-24 17:39:35.978 [CORE] Begin waiting for operation #2
2023-09-24 17:39:35.978 [CORE] Begin blocking for operation #2
2023-09-24 17:39:37.906 [CORE] Successfully completed #2
2023-09-24 17:39:37.938 [CLI ] MSIX installer failed: 2147958003
2023-09-24 17:39:37.945 [CLI ] Terminating context: 0x8a150104 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\InstallFlow.cpp:1fa

```

### Steps to reproduce

1. Do a fresh install of Windows 11.
2. Install the latest preview version of winget.
3. `winget install Microsoft.DevHome`

### Expected behavior

Installation without error.

### Actual behavior

Installation fails due to missing dependency.

### Environment

```shell
~ winget --info
Windows Package Manager (Preview) v1.7.2491-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1702
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.2491.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Enabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by mdanish-kh** [comment] 2023-09-25 07:11
[Policy] Dependencies
[Policy] Command-Install

**Comment by mdanish-kh** [comment] 2023-09-25 19:37
The logs say that the min dependency version is `3000.934.1904.0` and looking at winget-pkgs, the version is at [3000.882.2207.0](https://github.com/microsoft/winget-pkgs/blob/f53c5636e88ca58bd51cf3d91a23478979f4a501/manifests/m/Microsoft/WindowsAppRuntime/1/3/1.3.2/Microsoft.WindowsAppRuntime.1.3.installer.yaml#L11-L14)

Looks like we need to update the package over at winget-pkgs

**Comment by denelon** [comment] 2023-09-25 23:24
@hamnarauf it looks like the PR was merged and published.
Can you confirm this is working correctly now?

**Comment by hamnarauf** [comment] 2023-09-26 10:14
> @hamnarauf it looks like the PR was merged and published. Can you confirm this is working correctly now?

Even with the new dependency:

![image](https://github.com/microsoft/winget-cli/assets/77397009/171eb6a1-32ad-488f-a4b0-889b8df08b66)

[WinGet-2023-09-26-09-17-07.198.log](https://github.com/microsoft/winget-cli/files/12726188/WinGet-2023-09-26-09-17-07.198.log)

**Comment by mdanish-kh** [comment] 2023-09-26 13:17
I could also reproduce this in a clean VM. It looks like there's another issue with the dependency i.e., WindowsAppRuntime where it requires elevation for a complete install. Running the installer manually in user mode shows this:

![image](https://github.com/microsoft/winget-cli/assets/88161975/21146e13-3268-4d26-8a62-bcd11b5f58db)



Verified that the installation is successful if you manually install the dependency with admin rights (then install devhome in user shell) or run the command `winget install devhome` in an admin terminal. This looks like we need to add `ElevationRequirement: elevationRequired` to WindowsAppRuntime manifest. I have no way to test if the ElevationRequirement will be honored in a dependency scenario but let's see if it is after merging it in the manifest and then installing devhome...

**Comment by denelon** [comment] 2023-09-26 18:34
New possibly related issue:
* https://github.com/microsoft/winget-cli/issues/3671

**Comment by mdanish-kh** [comment] 2023-09-27 05:02
> I have no way to test if the ElevationRequirement will be honored in a dependency scenario but let's see if it is after merging it in the manifest and then installing devhome...

The PR for adding ElevationRequirement has been merged, and it looks like the ElevationRequirement is being honored properly and subsequent installation of devhome is successful in a clean VM. This is resolved at my end. @hamnarauf Can you please confirm the same?

![image](https://github.com/microsoft/winget-cli/assets/88161975/040c5888-e1d0-4873-93e5-31a9aea8de6d)

**Closed** 2023-09-27 18:10 UTC
Labels: Issue-Bug, Needs-Author-Feedback, Dependencies, Command-Install
