### ISSUE TITLE
Upgrade Microsoft.PowerToys is not working

### ISSUE THREAD

**Issue by dperez83** [microsoft/winget-cli#1801] opened 2021-12-15 05:09 UTC
### Brief description of your issue

Upgrade Microsoft.PowerToys is not working

![image](https://user-images.githubusercontent.com/42227137/146126737-60abbad9-f7a4-4867-a1c0-dd8b00809eb2.png)

### Steps to reproduce

Have PowerToys (Preview) Microsoft.PowerToys 0.49.1 and try to upgrade to 0.51.1 using winget upgrade --id Microsoft.PowerToys

### Expected behavior

Update Microsoft.PowerToys

### Actual behavior

"No applicable update found." message.

### Environment

```shell
C:\Users\dpz83>winget --info
Windows Package Manager v1.1.13405
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1415
Package: Microsoft.DesktopAppInstaller v1.16.13405.0
```

**Comment by denelon** [comment] 2021-12-15 23:23
Duplicate of #752

The good news is the fix is in progress:

#1796

**Closed by denelon** 2021-12-15 23:24 UTC
Labels: Needs-Triage
