### ISSUE TITLE
`winget uninstall ### --version ###` does not uninstall the target version

### ISSUE THREAD

**Issue by RichardWhitfield** [microsoft/winget-cli#2990] opened 2023-02-20 23:56 UTC
### Brief description of your issue

I was trying to remove an old .Net SDK to reinstall (repair).  Neither the `-v` nor the `--version` flag targetted the version to uninstall and the latest version was targetted instead meaning that I had to run the command twice to get to the version I wanted to uninstall and then reinstall both.
![image](https://user-images.githubusercontent.com/17287260/220214533-bc3d6e93-01b6-4dbf-a2ce-d3e11bec622a.png)

### Steps to reproduce

Try to uninstall a specific version of a product, the .Net SDK was where I had the issue:

1. `winget install Microsoft.DotNet.SDK.7 --version 7.0.103`
2. `winget install Microsoft.DotNet.SDK.7`
3. `winget uninstall Microsoft.DotNet.SDK.7 --version 7.0.103`

### Expected behavior

Uninstall specified version when flag is set

### Actual behavior

Uninstalls latest version

### Environment

```shell
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1265
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0
```

**Comment by Trenly** [comment] 2023-02-21 01:01
* https://github.com/microsoft/winget-cli/issues/1886

**Comment by denelon** [comment] 2023-02-21 18:14
Duplicate of #1886

**Closed** 2023-02-21 18:14 UTC
Labels: Needs-Triage
