### ISSUE TITLE
Visual studio installs unwanted components

### ISSUE THREAD

**Issue by puppetSpace** [microsoft/winget-cli#408] opened 2020-06-07 08:00 UTC
# Brief description of your issue
Visual studio installs some components like python development, UWP development, ...

# Steps to reproduce
- open command prompt
- run: `winget install Microsoft.VisualStudio.Enterprise`

# Expected behavior
Installs blank visual studio. Users should install components that he wants

# Actual behavior
Visual studio installs unwanted components

# Environment

```none
[winget --info]
Windows Package Manager version
Windows: Windows.Desktop v10.0.18363.836
Package: Microsoft.DesktopAppInstaller v1.0.41331.0

Any other software?
```

**Comment by megamorf** [comment] 2020-06-07 20:56
This issue seems to be asking for exactly the same as #363 making it a potential duplicate.

**Comment by denelon** [comment] 2020-06-11 22:25
Duplicate of #363

**Closed by denelon** 2020-06-11 22:25 UTC
Labels: Needs-Triage
