### ISSUE TITLE
Upgrading Microsoft.dotnet fails when multiple major versions are installed side-by-side

### ISSUE THREAD

**Issue by sba923** [microsoft/winget-cli#2011] opened 2022-03-09 17:37 UTC
### Brief description of your issue

When both .NET 5.x and 6.x are installed side-by-side, `winget upgrade` incorrectly reports that 5.x should be upgraded to 6.x, and upgrading just fails.

### Steps to reproduce

Starting conditions:

````
PS❯  winget list --name 'Microsoft .NET SDK'
Name                                                Id                                     Version       Available     Source
-----------------------------------------------------------------------------------------------------------------------------
Microsoft .NET SDK                                  Microsoft.dotnet                       6.1.222.6914  6.1.322.12413 winget
Microsoft .NET SDK 6.0.200 (x64) from Visual Studio {00D9D07C-9962-4CBB-9AA2-9EF1383B5B2D} 6.2.22.10605
Microsoft .NET SDK                                  Microsoft.dotnet                       5.1.120.60105 6.1.322.12413 winget
````

````
PS❯  winget upgrade | sls -raw 'Name|---|dotnet'
Name                                            Id                           Version          Available        Source
---------------------------------------------------------------------------------------------------------------------
Microsoft .NET SDK                              Microsoft.dotnet             6.1.222.6914     6.1.322.12413    winget
Microsoft .NET SDK                              Microsoft.dotnet             5.1.120.60105    6.1.322.12413    winget
````

### Expected behavior

`winget upgrade microsoft.dotnet` should complain that there are two packages installed with that id

There should be a means to scope the request to either 5.x or 6.x

.NET 6.x should be upgraded to the latest version.

### Actual behavior

````
PS❯  winget upgrade microsoft.dotnet
No installed package found matching input criteria.
````

### Environment

```shell
PS❯  winget --info
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.1526
Package: Microsoft.DesktopAppInstaller v1.17.10271.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

PS❯  Get-WindowsVersionViaWinRT.ps1

Key           Value
---           -----
OSVersionFull 10.0.19042.1526.amd64fre.vb_release.191206-1406
FlightRing    Retail
App           pwsh.exe
AppVer        7.2.1.500
DeviceFamily  Windows.Desktop
```

**Comment by denelon** [comment] 2022-03-09 18:37
Related to:
* #1413 
Duplicate of #752

**Closed by denelon** 2022-03-09 18:37 UTC
Labels: Needs-Triage

**Comment by sba923** [comment] 2022-03-09 18:43
Apparently you have decided to combine all related issues in to #1413.

I thought this was different enough, my bad.

**Comment by denelon** [comment] 2022-03-09 18:49
@sba923, it can be quite difficult to get to the root of some of these. Thank you for the detailed report. Each of these duplicates gets linked to help make sure we have more good data on specific examples, so we can make sure we have enough test cases to validate the fix. We really appreciate the time it took to give us the explicit data necessary to identify packages with this kind of behavior.
