### ISSUE TITLE
winget source update causes error 0x800700B7

### ISSUE THREAD

**Issue by brl0** [microsoft/winget-cli#640] opened 2020-11-10 20:35 UTC
# Brief description of your issue

When I attempt to search for a package, list packages, or update sources, the command fails with an error.

# Steps to reproduce

`winget source update`

# Expected behavior

Expecting command to execute without error.

# Actual behavior

```
An unexpected error occurred while executing the command:
Install failed: An internal error occurred with error 0x800700B7. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues.
0x800700b7 : Cannot create a file when that file already exists.
```

# Environment

```none
[winget --info]
Windows Package Manager v0.2.2941 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.610
Package: Microsoft.DesktopAppInstaller v1.11.2941.0
```

**Comment by denelon** [comment] 2021-01-07 00:57
Is this issue still happening?

**Comment by brl0** [comment] 2021-01-07 15:21
It is no longer happening to me after reinstalling Windows.

**Comment by Karl-WE** [comment] 2021-08-14 10:52
@denelon I am still expierencing this on my dads pc

scenario: 
Windows: Windows.Desktop v10.0.22000.132
Paket: Microsoft.DesktopAppInstaller v1.15.11694.0

error happens on executing: winget upgrade

1 user with local admin rights winget executed as this user with local admin rights and Windows Terminal with admin rights


Logfile

`021-08-14 12:51:46.197 [CORE] Subkey 'Software\Policies\Microsoft\Windows\AppInstaller' was not found
2021-08-14 12:51:46.197 [CORE] Setting action: Get, Type: UserFile, Name: settings.json
2021-08-14 12:51:46.207 [CORE] Setting action: Get, Type: UserFile, Name: settings.json.backup
2021-08-14 12:51:46.216 [CORE] Valid settings file not found. Using default values.
2021-08-14 12:51:46.217 [CORE] WinGet, version [1.0.11694], activity [{D507AD97-5EEA-49E2-8E55-4E0F0E94C7E8}]
2021-08-14 12:51:46.217 [CORE] OS: Windows.Desktop v10.0.22000.132
2021-08-14 12:51:46.217 [CORE] Command line Args: "C:\Users\servi\AppData\Local\Microsoft\WindowsApps\winget.exe" upgrade
2021-08-14 12:51:46.218 [CORE] Package: Microsoft.DesktopAppInstaller v1.15.11694.0
2021-08-14 12:51:46.218 [CORE] IsCOMCall:0; Caller: winget-cli
2021-08-14 12:51:46.225 [CLI ] WinGet invoked with arguments: 'upgrade'
2021-08-14 12:51:46.225 [CLI ] Found subcommand: upgrade
2021-08-14 12:51:46.225 [CLI ] Leaf command to execute: root:upgrade
2021-08-14 12:51:46.225 [CLI ] Executing command: upgrade
2021-08-14 12:51:46.226 [CORE] Setting action: Get, Type: Secure, Name: user_sources
2021-08-14 12:51:46.239 [CORE] Setting action: Get, Type: Standard, Name: sources_metadata
2021-08-14 12:51:46.240 [REPO] Default source requested, multiple sources available, creating aggregated source.
2021-08-14 12:51:46.240 [REPO] Adding to aggregated source: winget
2021-08-14 12:51:46.240 [REPO] Source past auto update time [5 mins]; it has been at least 6 mins
2021-08-14 12:51:47.621 [CORE] Examining extension: PFN = Microsoft.Winget.Source_8wekyb3d8bbwe, ID = IndexDB
2021-08-14 12:51:47.622 [CORE] Found matching extension.
2021-08-14 12:51:47.630 [REPO] Remote source data was not newer than existing, no update needed
2021-08-14 12:51:47.691 [CORE] Examining extension: PFN = Microsoft.Winget.Source_8wekyb3d8bbwe, ID = IndexDB
2021-08-14 12:51:47.691 [CORE] Found matching extension.
2021-08-14 12:51:47.759 [REPO] Opening SQLite Index for ImmutableRead at 'C:\Program Files\WindowsApps\Microsoft.Winget.Source_2021.814.512.342_neutral__8wekyb3d8bbwe\Public\index.db'
2021-08-14 12:51:47.759 [SQL ] Opening SQLite connection: 'file:/C:/Program Files/WindowsApps/Microsoft.Winget.Source_2021.814.512.342_neutral__8wekyb3d8bbwe/Public/index.db?immutable=1' [1, 40]
2021-08-14 12:51:47.761 [REPO] Opened SQLite Index with version [1.3], last write [2021-08-14 06:12:04.000]
2021-08-14 12:51:47.873 [REPO] Adding to aggregated source: newstore
2021-08-14 12:51:47.873 [REPO] Source past auto update time [5 mins]; it has been at least 6 mins
2021-08-14 12:51:48.090 [CORE] Setting action: Set, Type: Standard, Name: sources_metadata
2021-08-14 12:51:48.214 [REPO] Creating PredefinedInstalledSource with filter [None]
2021-08-14 12:51:48.214 [REPO] Creating new SQLite Index [4294967295.4294967295] at ':memory:'
2021-08-14 12:51:48.214 [SQL ] Opening SQLite connection: ':memory:' [6, 0]
2021-08-14 12:51:48.308 [REPO] Examining ARP entries for Machine | X64
2021-08-14 12:51:48.353 [REPO] Examining ARP entries for Machine | X86
2021-08-14 12:51:48.393 [REPO] Examining ARP entries for User | X64
2021-08-14 12:51:48.704 [FAIL] E:\BA\98\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(184)\AppInstallerCLI.exe!00007FF7F7D70B45: (caller: 00007FF7F7D6CD33) Exception(1) tid(287c) 800700B7 Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist.


2021-08-14 12:51:48.872 [CLI ] Caught wil::ResultException: E:\BA\98\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(184)\AppInstallerCLI.exe!00007FF7F7D70B45: (caller: 00007FF7F7D6CD33) Exception(1) tid(287c) 800700B7 Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist.

`

**Comment by Karl-WE** [comment] 2021-08-14 11:05
@denelon I think I have found the root cause.
This will / can happen if a computer has more than one user. 

Using winget logged on user1  the error comes up
using winget logged on with user2 winget upgrade does not throw an issue.

Proposal: Winget appx should be deployed system wide for all user accounts. 
if a new user is created it should be provisioned similar to other system appx like calc etc.

currently winget is a per user installation as per design of appx. if I install winget on a user that has no local admin rights this error might spawn.

i have seen also different scenarios where winget was not executable in the user context where it was not specificially installed. means if I install winget in user1 on Windows 10 it i cannot run winget with user2. for Windows 11 (or here) this seems to be different.

**Comment by denelon** [comment] 2021-08-18 01:15
@Karl-WE thanks for digging into this one! We may not be able to change the behavior for the MSIX package, but at least we might be able to provide a better error in the short term.

**Comment by Karl-WE** [comment] 2021-08-18 16:05
Thanks for reopening and working on a remediation @denelon. If there is anything I could provide or test a private build please let me know.

**Comment by yao-msft** [comment] 2021-09-16 19:37
I think it's fixed as part of this commit, where we change to use package full name instead of package family name for installed packages indexing, this will avoid duplicate entries causing ERROR_ALREADY_EXISTS
https://github.com/microsoft/winget-cli/pull/1395/files#diff-1d47bcf6a8ced8a2bf524dafe8086d9c7105d9cf7c942bd14254a99e18e1b36a

**Comment by Karl-WE** [comment] 2021-09-17 18:54
@yao-msft please let know if there is a release that should test.

**Comment by yao-msft** [comment] 2021-09-17 19:33
Hi @Karl-We The fix is merged but not released yet, I'll definitely update this thread when it's released. Thanks.

**Comment by denelon** [comment] 2021-09-21 21:19
@Karl-WE this should be in the current Pre-release version here at GitHub.

**Closed by denelon** 2021-09-21 21:19 UTC
Labels: Issue-Bug

**Comment by Karl-WE** [comment] 2021-09-22 23:52
I will check and report back if there if it is fixed in my scenario. Thanks for the quick fix @yao-msft @denelon

**Comment by Karl-WE** [comment] 2021-09-22 23:54
just to be sure it is this release? 
https://github.com/microsoft/winget-cli/releases/tag/v1.0.12576 @denelon

**Comment by yao-msft** [comment] 2021-09-22 23:58
Yes, this v1.0.12576 release should contain the fix. Please feel free to reopen the issue if it's not working for your scenario. Thanks.

**Comment by Karl-WE** [comment] 2021-09-23 00:56
I will do so. If I can confirm you might want to add it to fixed issues list in the release history

**Comment by Karl-WE** [comment] 2021-09-28 18:15
@denelon can confirm the issue is gone with 1.0.12576

**Comment by Ascendor** [comment] 2023-02-20 20:58
I do see this exact issue now. 

winget upgrade results in error 0x800700b7

Log file says:
2023-02-20 21:54:20.978 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(190)\WindowsPackageManager.dll!00007FFFD256B1AD: (caller: 00007FFFD2571449) Exception(1) tid(61c8) 800700B7 Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist.

Anything I can do about it?
