### ISSUE TITLE
Winget is detecting msvc 2015-2022 redistributable x64 as x86

### ISSUE THREAD

**Issue by hez2010** [microsoft/winget-cli#3716] opened 2023-09-30 06:51 UTC
### Brief description of your issue

Winget is detecting msvc 2015-2022 redistributable x64 as x86.

I'm seeing this appearing in the list:

```
名前                                                               ID
---------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.36.32532 Microsoft.VCRedist.2015+.x86
```

### Steps to reproduce

```
winget list
```

### Expected behavior

```
名前                                                               ID
---------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.36.32532 Microsoft.VCRedist.2015+.x64
```

### Actual behavior

```
名前                                                               ID
---------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.36.32532 Microsoft.VCRedist.2015+.x86
```

### Environment

```shell
`winget --info`:


Windows パッケージ マネージャー (プレビュー) v1.7.2711-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.2361
システム アーキテクチャ: X64
パッケージ: Microsoft.DesktopAppInstaller v1.22.2711.0

Winget ディレクトリ
-----------------------------------------------------------------------------------------------------------------------
ログ                                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalSta…
ユーザー設定                              %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalSta…
ポータブル リンク ディレクトリ (ユーザー) %LOCALAPPDATA%\Microsoft\WinGet\Links
ポータブル リンク ディレクトリ (マシン)   C:\Program Files\WinGet\Links
ポータブル パッケージ ルート (ユーザー)   %LOCALAPPDATA%\Microsoft\WinGet\Packages
ポータブル パッケージ ルート              C:\Program Files\WinGet\Packages
ポータブル パッケージ ルート (x86)        C:\Program Files (x86)\WinGet\Packages
インストーラのダウンロード                %USERPROFILE%\Downloads

リンク
-----------------------------------------------------------------------------------
プライバシーに関する声明    https://aka.ms/winget-privacy
使用許諾契約                https://aka.ms/winget-license
サード パーティに関する通知 https://aka.ms/winget-3rdPartyNotice
ホーム ページ               https://aka.ms/winget
Windows ストアの使用条件    https://www.microsoft.com/en-us/storedocs/terms-of-sale

管理者設定                                状態
----------------------------------------------
LocalManifestFiles                        無効
BypassCertificatePinningForMicrosoftStore 無効
InstallerHashOverride                     無効
LocalArchiveMalwareScanOverride           無効
```
```

**Comment by Trenly** [comment] 2023-09-30 15:15
* Duplicate of #2893

**Closed** 2023-09-30 15:15 UTC
Labels: Area-Matching
