### ISSUE TITLE
apps version not correctly getted?

### ISSUE THREAD

**Issue by luoshengming** [microsoft/winget-cli#4459] opened 2024-05-08 08:15 UTC
### Brief description of your issue

The version numbers of the two software listed below are incorrect, even if I have upgraded to the latest version.
<img width="463" alt="1715155785052" src="https://github.com/microsoft/winget-cli/assets/26688766/2ba72e97-e99e-42b6-af24-569f4244ab30">

### Steps to reproduce

run winget UPGRADE --include-unknown --rainbow

### Expected behavior

Correctly display the software version number

### Actual behavior

work

### Environment

```shell
Windows: Windows.Desktop v10.0.22631.3527
Arquitectura del sistema: X64
Paquete: Microsoft.DesktopAppInstaller v1.22.11261.0
```

**Comment by Trenly** [comment] 2024-05-08 13:56
This issue is caused by a version mapping in the Manifests over at winget-pkgs. I've linked PRs which will resolve this issue

**Comment by Trenly** [comment] 2024-05-09 02:47
Close with reason: Linked PRs merged; Issue should be resolved now

**Closed** 2024-05-09 02:48 UTC
Labels: Issue-Bug
