### ISSUE TITLE
winget client issue, source update failed

### ISSUE THREAD

**Issue by drshtmstry** [microsoft/winget-cli#3691] opened 2023-09-27 14:00 UTC
### Brief description of your issue

After receiving new update (windows co-pilot update) winget is not working.

`winget source update --force` didn't resolve. Same with source reset.
In apps & features, app installer (winget) is not showing up.

[WinGet-2023-09-27-19-22-06.441.log](https://github.com/microsoft/winget-cli/files/12739449/WinGet-2023-09-27-19-22-06.441.log)
[WinGet-2023-09-27-19-24-20.184.log](https://github.com/microsoft/winget-cli/files/12739452/WinGet-2023-09-27-19-24-20.184.log)
![Screenshot 2023-09-27 192504](https://github.com/microsoft/winget-cli/assets/145197941/b39c8e1b-4f0f-4c9a-ab63-aa172fe13171)

### Steps to reproduce

`winget upgrade`

### Expected behavior

upgrade pacakage

### Actual behavior

```PS C:\Users\drsht> winget upgrade
Failed in attempting to update the source: winget
No installed package found matching input criteria.
PS C:\Users\drsht> winget source update
Updating all sources...
Updating source: msstore...
Done
Updating source: winget...
Cancelled
```

### Environment

```shell
PS C:\Users\drsht> winget --info
Windows Package Manager v1.6.2631
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1702
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.2631.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by Trenly** [comment] 2023-09-27 14:41
Duplicate of #3687

**Closed** 2023-09-27 14:41 UTC
