### ISSUE TITLE
winget upgrade  Cyotek.WebCopy installs additional versions

### ISSUE THREAD

**Issue by nascentt** [microsoft/winget-cli#1376] opened 2021-08-18 09:36 UTC
when using  winget upgrade Cyotek.WebCopy
winget intalls a new version and then leaves the old version so you end up with two entries in add/remove/rpograms

# Brief description of your issue

# Steps to reproduce

winget upgrade Cyotek.WebCopy

# Expected behavior

updated version only left installed

# Actual behavior

multiple versions of product installed

# Environment

```winget --info
Windows Package Manager v1.0.11692
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.1165
Package: Microsoft.DesktopAppInstaller v1.12.11692.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
--------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
Licence Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
```
![cyotek winget](https://user-images.githubusercontent.com/1145722/129875313-445ee872-f64e-49da-9e8b-3503040710a5.png)

**Comment by denelon** [comment] 2021-08-19 00:57
Duplicate of #1212

**Closed by denelon** 2021-08-19 00:57 UTC
Labels: Needs-Triage
