### ISSUE TITLE
Microsoft.VC++2015Redist-x86 Cannot Upgrade

### ISSUE THREAD

**Issue by hl2guide** [microsoft/winget-cli#1820] opened 2021-12-22 11:45 UTC
### Brief description of your issue

Inability to upgrade Microsoft Visual C++ 2015 Redistributable (x86).

ID: Microsoft.VC++2015Redist-x86

Installed Version: 14.0.24215.1

Available Version: 14.0.24516.0

### Steps to reproduce

* Have Microsoft Visual C++ 2015 Redistributable (x86) 14.0.24215.1 installed
* Run Command: `winget upgrade`
Output is:
```
Name                                            Id                           Version      Available    Source
-------------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015 Redistributable (x86) Microsoft.VC++2015Redist-x86 14.0.24215.1 14.0.24516.0 winget
1 upgrades available.
```

* Run Command `winget upgrade Microsoft.VC++2015Redist-x86`
Output is:
```
Name                                                         Id
---------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015 Redistributable (x86)              Microsoft.VC++2015Redist-x86
Microsoft Visual C++ 2015 Redistributable (x64) - 14.0.24516 {b8e12890-118d-4721-8e54-05d978086712}
```

### Expected behavior

Specific ID is shown and allows upgrade. (is the available version invalid?)

### Actual behavior

Endless loop of finding the package.

Note: `winget install --id=Microsoft.VC++2015Redist-x86  -e` works as an override.

### Environment

```shell
Windows 10 Pro 21H2
Winget: 1.1.13405
```

**Comment by icy-comet** [comment] 2021-12-23 09:41
+1

I am noticing the same issue on both Windows 10 and Windows 11 machines. Specifying `--exact` parameter doesn't work either for upgrade. Although, I also have the x64 package installed alongside the x86 one.

- Installed winget version: `v1.1.13405`
- Installed `Microsoft.VC++2015Redist-x86` version: `14.30.30704.0`

**Comment by FurtadoPires** [comment] 2021-12-23 12:44
Same happens with other versions like
```
Microsoft Visual C++ 2015-2022 Redistributable (x… Microsoft.VC++2015-2022Redist-x64 14.31.30818.0 14.31.30919.0
Microsoft Visual C++ 2015-2022 Redistributable (x… Microsoft.VC++2015-2022Redist-x86 14.31.30818.0 14.31.30919.0
```

Winget: v1.1.13405
Powershell: 7.2.1
Window 11 21H2

**Comment by OfficialEsco** [comment] 2021-12-23 21:38
another related issue https://github.com/microsoft/winget-pkgs/issues/27935 + waiting for another feature

The answer to these issues: https://github.com/microsoft/winget-cli/issues/1658#issuecomment-955044811 and https://github.com/microsoft/winget-cli/issues/1413#issuecomment-949764994

I've been playing around with Schema 1.1.0 however I'm not sure how that would fix the issue?
I'm guessing he means like this for EACH version
```
AppsAndFeaturesEntries:
  - DisplayName: Microsoft Visual C++ 2015-2019 Redistributable (x86) - 14.29.30135
```
instead of
```
AppsAndFeaturesEntries:
  - DisplayName: Microsoft Visual C++ 2015-2019 Redistributable (x86)
```
However that would break any version we don't have a manifest on
@denelon

**Comment by FurtadoPires** [comment] 2021-12-23 21:50
> Same happens with other versions like
> 
> ```
> Microsoft Visual C++ 2015-2022 Redistributable (x… Microsoft.VC++2015-2022Redist-x64 14.31.30818.0 14.31.30919.0
> Microsoft Visual C++ 2015-2022 Redistributable (x… Microsoft.VC++2015-2022Redist-x86 14.31.30818.0 14.31.30919.0
> ```
> 
> Winget: v1.1.13405 Powershell: 7.2.1 Window 11 21H2

Worked when I used `winget upgrade --all` but not if I try to upgrade individually

**Comment by jedieaston** [comment] 2021-12-23 23:21
It’s difficult to know without the implementation for AppsAndFeaturesEntries being in the client. I don’t know if they plan on using that data to fix this upgrade issue or not.

**Comment by denelon** [comment] 2021-12-28 18:07
Duplicate of #1413 

We are working on additional logic to help with matching. VC++ will very likely be part of the test cases for this.

**Closed by denelon** 2021-12-28 18:07 UTC
Labels: Needs-Triage
