### ISSUE TITLE
`winget upgrade --all` lists and silently skips app with different installer technology

### ISSUE THREAD

**Issue by sba923** [microsoft/winget-cli#3817] opened 2023-10-27 05:28 UTC
### Brief description of your issue

When an upgrade for an application is available, but with a different installer technology, `winget upgrade --all` lists the app but skips it silently:

![image](https://github.com/microsoft/winget-cli/assets/12860484/57462671-bc00-4ede-8348-b88baf7d7887)

Here are the logs: 
[WinGet-2023-10-27-TrackerSoftware.PDF-XChangeEditor.zip](https://github.com/microsoft/winget-cli/files/13185214/WinGet-2023-10-27-TrackerSoftware.PDF-XChangeEditor.zip)

### Steps to reproduce

1. Install TrackerSoftware.PDF-XChangeEditor using the EXE installer from https://www.pdf-xchange.com/product/downloads.
2. run `winget upgrade --all`

### Expected behavior

`winget upgrade --all` should attempt to upgrade the app and complain that it can't with the standard "_A newer version was found, but the install technology is different from the current version installed. Please uninstall the package and install the newer version._" message.

### Actual behavior

`winget upgrade --all` silently skips the app:

![image](https://github.com/microsoft/winget-cli/assets/12860484/25921993-e7e3-478d-b6ed-e3ae6dce19de)

### Environment

```shell
Windows Package Manager v1.6.2771
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2428
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.2771.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by mdanish-kh** [comment] 2024-04-11 08:29
Duplicate of #2883

**Closed** 2024-04-11 08:29 UTC
Labels: Issue-Feature, Command-Upgrade
