### ISSUE TITLE
Incorrect versions for apps that do selfupdate

### ISSUE THREAD

**Issue by ZeeWanderer** [microsoft/winget-cli#1181] opened 2021-06-18 14:57 UTC
# Brief description of your issue

It seems that apps like Discord, Epic Games Launcher or Ubisoft Connect do not update their registered version on selfupdate so winget sees only version registered on first install and incorrectly reports them as out of date.

# Expected behavior
winget should derive correct versions for all packages.

# Actual behavior

some package versions are derived incorrectly

# Environment

```none
Windows Package Manager v1.0.11451
Windows: Windows.Desktop v10.0.19043.1055
Package: Microsoft.DesktopAppInstaller v1.11.11451.0
```

**Comment by denelon** [comment] 2021-06-18 18:01
Duplicate of #1163

**Closed by denelon** 2021-06-18 18:01 UTC
Labels: Needs-Triage
