### ISSUE TITLE
0x801901f4 : Internal server error (500) when I try to execute winget list and winget install (Source is down)

### ISSUE THREAD

**Issue by Fukubi** [microsoft/winget-cli#1437] opened 2021-09-06 13:39 UTC
# Brief description of your issue

When I try to execute winget list or winget install command I get an 0x801901f4 : Internal error in server (500) error.
# Steps to reproduce

Execute winget list, winget install.
```
[winget list]
Ocorreu um erro inesperado ao executar o comando:
0x801901f4 : Erro interno de servidor (500).

[winget install Mozilla.Firefox]
Ocorreu um erro inesperado ao executar o comando:
0x801901f4 : Erro interno de servidor (500).
```

# Expected behavior

List installed apps (with winget list) or install a new app (with winget install)

# Actual behavior

Throw an internal server error

# Environment

```none
[winget --info]
Windows Package Manager v1.0.11694
Copyright (c) Microsoft Corporation. Todos os direitos reservados.

Windows: Windows.Desktop v10.0.22000.176
Pacote: Microsoft.DesktopAppInstaller v1.15.11694.0

Registros: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
```

**Comment by jedieaston** [comment] 2021-09-06 13:41
https://github.com/microsoft/winget-cli/issues/1349#issuecomment-913651947

**Comment by Fukubi** [comment] 2021-09-06 14:06
With ```--source winget``` it works perfectly

**Comment by jedieaston** [comment] 2021-09-06 14:18
Can you reopen this? It's the only issue noting that the source is down.

**Comment by Fukubi** [comment] 2021-09-06 15:02
Yeah, no problem.

**Comment by leochras** [comment] 2021-09-07 09:03
I just turned on my machine and also got this error..
![image](https://user-images.githubusercontent.com/16163571/132316909-9d10fad4-8ff6-41b3-a7d3-cb751c643a5b.png)

**Comment by Caticer** [comment] 2021-09-07 12:38
I have same issue + I can't download apps from microsoft store too

**Comment by feoh** [comment] 2021-09-08 03:53
Same here and it's super frustrating. Reproduced on both a System76 Thelio and a Lenovo Thinkpad T15 gen2 both running Windows 11 Insiders Beta/latest update.

I submitted feedback at: https://aka.ms/AAdr7rh

**Comment by yooakim** [comment] 2021-09-08 07:17
I have the same issue as well, frustrating.

```
PS C:\Users\joakim.westin> winget --info
Windows Package Manager v1.0.11694
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.176
Package: Microsoft.DesktopAppInstaller v1.15.11694.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
--------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
Licence Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
```

![image](https://user-images.githubusercontent.com/862546/132463901-2f9ead42-dd08-4da8-b75c-8aabcf179b2d.png)

**Comment by danyalahmed** [comment] 2021-09-08 08:09
I am facing same issue, as mentioned above for now --source winget seems to work

**Comment by JovanPetrovic** [comment] 2021-09-08 08:36
Update the Microsoft Store, using Microsoft Store - and that should resolve the issue, at least it worked for me.

**Comment by jedieaston** [comment] 2021-09-08 13:40
@denelon should this issue be moved to [microsoft/winget-cli-restsource](https://github.com/microsoft/winget-cli-restsource)? I don't know who's responsible for making sure the store source is up...

**Comment by denelon** [comment] 2021-09-08 15:30
@jedieaston the REST source for the store packages is a different internal package. We've already contacted them regarding the 500 errors. @Fukubi thanks for reopening this. There was a small misunderstanding when implementing the API. I believe the issue for the errors has been resolved, but I wanted to keep this open so we can make sure to do a better job handling these kinds of issues in the client.

**Comment by denelon** [comment] 2021-09-08 15:41
@Fukubi is there an update to the Microsoft Store application available? Can you share what version you have? I believe it's under App settings when you select the account logged into the store in the top right corner.

**Comment by jedieaston** [comment] 2021-09-08 16:33
I'm currently also having the issue. My Microsoft Store version is 22109.1401.3.0 (there aren't any updates available).

Also:
```
Windows Package Manager v1.0.11694
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.176
Package: Microsoft.DesktopAppInstaller v1.15.11694.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
--------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget

```

**Comment by Fukubi** [comment] 2021-09-08 17:32
@denelon I don't have any updates in the MS Store, maybe it's because I'm using the preview version?

Here's the version details that you asked

![image](https://user-images.githubusercontent.com/59181380/132556897-47cfa451-2aaa-4021-88fe-27e16239cc5e.png)

And about the internal server error, I still have it 

```
[winget list]
Ocorreu um erro inesperado ao executar o comando:
0x801901f4 : Erro interno de servidor (500).
```

**Comment by denelon** [comment] 2021-09-08 17:49
Thanks for the data points! It looks like we may have another release coming for the experimental store source in the next day or two. It was not built with the reference implementation, so we're working through some design decisions and legacy systems.

For a bit more transparency, the engineering team working on the store source is working through some technical limitations on how some of the search criteria works. The current implementation is tightly coupled with the search UI in the Microsoft Store. This is likely to have a very long lead time (many months) to get where we want it to be for command-line scenarios supporting the Windows Package Manager.

**Comment by i-zanis** [comment] 2021-09-08 21:31
I am current facing in the same issue (W11).

**Comment by denelon** [comment] 2021-09-08 21:35
In addition to the `-s winget` workaround to avoid the responses from the store source, you may also disable the experimental feature to improve productivity.

**Comment by feoh** [comment] 2021-09-08 21:53
@denelon Thanks and pardon my ignorance but how do we disable the experimental feature?

**Comment by denelon** [comment] 2021-09-08 21:55
@feoh, no worries. You can see what features are enabled via `winget features`.

You can set the value to "false" in your settings file. I set Visual Studio Code as my default .json editor. Run `winget settings` to open up the file. Be sure to save it before running `winget` again.

**Comment by adrianghc** [comment] 2021-09-08 22:05
> In addition to the `-s winget` workaround to avoid the responses from the store source, you may also disable the experimental feature to improve productivity.

I'm having this problem despite having that feature disabled.

**Comment by denelon** [comment] 2021-09-08 23:07
@adrianghc if you run `winget source list` with the experimental store disabled, you should only see the default "winget" source. Can you confirm?

**Comment by adrianghc** [comment] 2021-09-08 23:10
> @adrianghc if you run `winget source list` with the experimental store disabled, you should only see the default "winget" source. Can you confirm?

Well, no, I do get this:

```
Name     Argument
------------------------------------------------------
winget   https://winget.azureedge.net/cache
newstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
```

But I do get this for `winget features`:

```
Funktion                Status      Eigenschaft         Link
--------------------------------------------------------------------------------------
Microsoft Store Support Deaktiviert experimentalMSStore https://aka.ms/winget-settings
Packaged API Support    Aktiviert   packagedAPI         https://aka.ms/winget-settings
```

**Comment by denelon** [comment] 2021-09-08 23:25
@adrianghc you can `winget source remove newstore`. It still gets a "tombstone" so it shouldn't show back up unless you disable/reenable the experimental store and then do a `winget source reset --force` from an elevated prompt.

**Comment by adrianghc** [comment] 2021-09-09 00:25
So if I understand this right, the default when not setting the experimental store flag should be that winget is the only source? Why does newstore not get removed automatically when disabling the feature?

**Comment by adrianghc** [comment] 2021-09-09 00:26
So if I understand this right, the default when not setting the experimental store flag should be that winget is the only source? Why does newstore not get removed automatically when disabling the feature?

**Comment by denelon** [comment] 2021-09-09 00:34
@adrianghc, I think it's a bug. Which version are you using?  Would you mind sharing the output from `winget info` in the [bug](https://github.com/microsoft/winget-cli/issues/1446)?

**Comment by Jaifroid** [comment] 2021-09-09 00:36
Just to add to this that I'm getting the same issue on Windows 11 (latest Beta insider - 22000.176). I have never enabled the newstore source for this and it's not in my winget settings.

![image](https://user-images.githubusercontent.com/4304337/132603208-c7605634-d0c6-4c29-946a-a5dccf3c9524.png)

**Comment by adrianghc** [comment] 2021-09-09 00:38
> @adrianghc, I think it's a bug. Which version are you using? Would you mind sharing the output from `winget info` in the [bug](https://github.com/microsoft/winget-cli/issues/1446)?

Sure thing, done.

**Comment by denelon** [comment] 2021-09-09 00:39
@Jaifroid can you share the output from `winget source list` and `winget features`?

**Comment by Jaifroid** [comment] 2021-09-09 00:41
> @Jaifroid can you share the output from `winget source list` and `winget features`?
Here you go:
```
PS C:\Users\gkant> winget source list
Name     Argument
------------------------------------------------------
winget   https://winget.azureedge.net/cache
newstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
PS C:\Users\gkant> winget features
The following experimental features are in progress.
They can be configured through the settings file 'winget settings'.

Feature                 Status   Property            Link
-----------------------------------------------------------------------------------
Microsoft Store Support Disabled experimentalMSStore https://aka.ms/winget-settings
Packaged API Support    Enabled  packagedAPI         https://aka.ms/winget-settings
```

**Comment by feoh** [comment] 2021-09-09 01:43
> @feoh, no worries. You can see what features are enabled via `winget features`.
> 
> You can set the value to "false" in your settings file. I set Visual Studio Code as my default .json editor. Run `winget settings` to open up the file. Be sure to save it before running `winget` again.

Sorry to jump into the pig-pile, but I added the following as per the docs to my winget settings:
```
    "experimentalFeatures": {
       "experimentalCmd": false,
       "experimentalArg": false
    },
    "experimentalFeatures": {
       "experimentalMSStore": false
    }
```

and I still get the exact same error.

**Comment by voltagex** [comment] 2021-09-09 02:40
Fiddler shows the following

```POST https://storeedgefd.dsx.mp.microsoft.com/v9.0/manifestSearch HTTP/1.1
Connection: Keep-Alive
Content-Type: application/json
User-Agent: cpprestsdk/2.10.18
Version: 1.0.0
Content-Length: 519
Host: storeedgefd.dsx.mp.microsoft.com

{"Inclusions":[{"PackageMatchField":"PackageFamilyName","RequestMatch":{"KeyWord":"firefox","MatchType":"Exact"}},{"PackageMatchField":"ProductCode","RequestMatch":{"KeyWord":"firefox","MatchType":"Exact"}},{"PackageMatchField":"PackageIdentifier","RequestMatch":{"KeyWord":"firefox","MatchType":"CaseInsensitive"}},{"PackageMatchField":"PackageName","RequestMatch":{"KeyWord":"firefox","MatchType":"CaseInsensitive"}},{"PackageMatchField":"Moniker","RequestMatch":{"KeyWord":"firefox","MatchType":"CaseInsensitive"}}]}
HTTP/1.1 500 Internal Server Error
Content-Length: 296
Content-Type: application/json; charset=utf-8
Server: Microsoft-HTTPAPI/2.0
X-OSG-Served-By: SOUTHEASTASIA_Legacy00003D_1.0.0.0
MS-CV: ZbX0ovP+hkm22Zu9.0
Vary: Accept-Encoding
Expires: Thu, 09 Sep 2021 02:38:15 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Thu, 09 Sep 2021 02:38:15 GMT
Connection: close

{"code":"UnknownServerError","data":[],"details":[],"innererror":{"code":"UnknownServerError","data":[],"details":[],"message":"Object reference not set to an instance of an object.","source":"StoreEdgeFD"},"message":"Object reference not set to an instance of an object.","source":"StoreEdgeFD"}

```

**Comment by Fukubi** [comment] 2021-09-09 11:55
It looks like it's fixed, it's working normally here even without the ```-s winget``` and with the newstore source on.

**Comment by adrianghc** [comment] 2021-09-09 11:58
I reset the sources to check and unfortunately, it still doesn't seem to work for me. Maybe it's a regional thing?

**Comment by Jaifroid** [comment] 2021-09-09 11:59
> It looks like it's fixed, it's working normally here even without the `-s winget` and with the newstore source on.

Not fixed for me.

![image](https://user-images.githubusercontent.com/4304337/132681781-e493e8b5-9d6a-4e85-86b4-846dd5d6abb6.png)

**Comment by ItzLevvie** [comment] 2021-09-09 11:59
> Just to add to this that I'm getting the same issue on Windows 11 (latest Beta insider - 22000.176). I have never enabled the newstore source for this and it's not in my winget settings.
> 
> ![image](https://user-images.githubusercontent.com/4304337/132603208-c7605634-d0c6-4c29-946a-a5dccf3c9524.png)

newstore is enabled by default on Windows 11.

You can fix it by doing `winget source remove newstore`

**Comment by Fukubi** [comment] 2021-09-09 11:59
Maybe? I'm in Brazil using the windows 11, want me to send some infos?

**Comment by adrianghc** [comment] 2021-09-09 12:00
> The `newstore` source is added by default on Windows 11.
> 
> You can fix it by doing `winget source remove newstore`

Do you know if this is by design or if it's a bug?

**Comment by adrianghc** [comment] 2021-09-09 12:02
> Maybe? I'm in Brazil using the windows 11, want me to send some infos?

If it's a regional thing (e.g. because of new server code that needs to roll out across all regions) it should work for everybody at some point, so I'll just check again later.

**Comment by Jaifroid** [comment] 2021-09-09 12:02
> The `newstore` source is added by default in WinGet on Windows 11 devices.
> 
> You can temporarily fix it by doing `winget source remove newstore`

That fixed it in Windows 11, thanks @ItzLevvie.

![image](https://user-images.githubusercontent.com/4304337/132682226-cb505a85-e4ca-432d-8e3b-95b79062f075.png)

**Comment by Jaifroid** [comment] 2021-09-09 12:13
> Do you know if this is by design or if it's a bug?

Not an answer to the question, but I think it's fine for the Microsoft Store to be an available source by default, so long as winget doesn't bomb out if it can't reach one of the stores. It should give a message that the store is unavailable but still install if the right ID or moniker has been set for a package in the main winget repo.

I would like to be able to set a moniker for the MIcrosoft Store version, so there's no confusion between the packages. The MS Store version will auto-update, so would be the superior choice in principle, but only if I can set different monikers for the different packages. The one in the winget repo is signed with our org's cert. The one in the MS Store is signed with the MS Store cert.

**Comment by feoh** [comment] 2021-09-09 15:49
+1 this started working for me this morning as well. Thanks to whoever brought it back to life! Having to remember --source winget was a drag :)

**Comment by cloudrootab** [comment] 2021-09-17 07:33
I removed the newstore, since it made winget all but unusable (who has time to input --source _every_ time!?). However, I'm trying to add it back again since people are saying it started working again (and it's also working on my laptop). But trying to addit results in the same Internal server error (500)

> winget source add newstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
Adding source:
  newstore -> https://storeedgefd.dsx.mp.microsoft.com/v9.0
An unexpected error occurred while executing the command:
Internal server error (500).

**Comment by Jaifroid** [comment] 2021-09-17 07:35
> I removed the newstore, since it made winget all but unusable (who has time to input --source _every_ time!?). However, I'm trying to add it back again since people are saying it started working again (and it's also working on my laptop). But trying to addit results in the same Internal server error (500)

I have the same issue.

**Comment by jedieaston** [comment] 2021-09-17 13:19
I think you need to add `-t Microsoft.Rest`.

`winget source add -t Microsoft.Rest -n newstore https://storeedgefd.dsx.mp.microsoft.com/v9.0` worked for me.

**Comment by cloudrootab** [comment] 2021-09-17 13:25
> I think you need to add `-t Microsoft.Rest`.
> 
> `winget source add -t Microsoft.Rest -n newstore https://storeedgefd.dsx.mp.microsoft.com/v9.0` worked for me.

Can confirm that it worked. But imho, it's surprising that this was necessary. 'winget source list' doesn't mention "Type" anywhere. So it's far from obvious that this flag needs to be added. Especially since the error code didn't mention it either.

**Comment by Jaifroid** [comment] 2021-09-17 13:30
> I think you need to add `-t Microsoft.Rest`.
> 
> `winget source add -t Microsoft.Rest -n newstore https://storeedgefd.dsx.mp.microsoft.com/v9.0` worked for me.

Also works for me. Thanks!

**Comment by denelon** [comment] 2021-09-17 14:14
You can also run `winget source reset` to have the client attempt resolving source related issues and add "default" sources back.

**Closed** 2021-09-18 06:38 UTC
Labels: Issue-Bug
