### ISSUE TITLE
SSH winget error 

### ISSUE THREAD

**Issue by belveruski** [microsoft/winget-cli#597] opened 2020-10-07 21:23 UTC
winget command through SSH give me this error:

```bash
$ ssh user@192.168.1.107
PS C:\Users\user> winget
Program 'winget.exe' failed to run: The file cannot be accessed by the systemAt line:1 char:1
+ winget
+ ~~~~~~.
At line:1 char:1
+ winget
+ ~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
 ```

Winget information:

```bash
Windows Package Manager v0.2.2521 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19041.508
Package: Microsoft.DesktopAppInstaller v1.11.2521.0
```

**Comment by megamorf** [comment] 2020-10-08 15:11
Duplicate of #513 

/cc @denelon

**Comment by denelon** [comment] 2020-10-08 16:23
Duplicate of #513

**Closed by denelon** 2020-10-08 16:23 UTC
Labels: Needs-Triage
