### ISSUE TITLE
Support for installers inside of a .zip file

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#859] opened 2021-04-12 16:12 UTC
# Install packages delivered as a compressed installer

Some publishers provide a compressed file with an installer inside. This feature would enable a user to install such a package.
For example: https://github.com/microsoft/winget-pkgs/issues/9891#issuecomment-817896382

# Proposed technical implementation details (optional)

The manifest would need to be able to identify this type of installer. The client would be able to download the file, verify the file, extract the installer, and execute the installer.

Related to:
* #140

**Comment by sanyer** [comment] 2021-04-12 16:15
There is also an edge case when publisher packs installer in folder inside zip file.
MSIAfterburner from msi.com, for example, has this structure: `MSIAfterburnerSetup.zip\4.6.3\MSIAfterburnerSetup463.exe`

**Comment by the-j0k3r** [comment] 2021-04-21 09:44
Isnt this a duplicate of https://github.com/microsoft/winget-cli/issues/140

**Comment by superusercode** [comment] 2021-04-28 23:36
> 
> 
> Isnt this a duplicate of #140

Not a duplicate, since this is concerning an installable executable inside a zip rather than one you can just run.

**Comment by Trenly** [comment] 2022-09-28 17:36
@denelon - Resolved?

**Closed** 2022-09-28 17:52 UTC
Labels: Issue-Feature
