### ISSUE TITLE
Microsoft Teams Upgrade is available but fails to install

### ISSUE THREAD

**Issue by yooakim** [microsoft/winget-cli#2050] opened 2022-03-30 05:04 UTC
### Brief description of your issue

When I run `winget upgrade`  I am told there is a new version of Teams available, but when I try to upgrade it fails, the logs are attached.

[WinGet-Microsoft.Teams.1.5.00.5967-2022-03-30-06-59-54.024.log](https://github.com/microsoft/winget-cli/files/8377145/WinGet-Microsoft.Teams.1.5.00.5967-2022-03-30-06-59-54.024.log)
[WinGet-2022-03-30-06-59-50.768.log](https://github.com/microsoft/winget-cli/files/8377146/WinGet-2022-03-30-06-59-50.768.log)

### Steps to reproduce

```
C:\>winget upgrade
Name            Id              Version     Available   Source
--------------------------------------------------------------
Microsoft Teams Microsoft.Teams 1.4.0.32771 1.5.00.5967 winget
1 upgrades available.

C:\>winget upgrade Microsoft.Teams --verbose-logs
Found Microsoft Teams [Microsoft.Teams] Version 1.5.00.5967
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1638
Installer log is available at: C:\Users\yooak\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Microsoft.Teams.1.5.00.5967-2022-03-30-06-59-54.024.log
Another version of this application is already installed.
```

### Expected behavior

I expected my Teams to be upgraded.

### Actual behavior

I receive the message `Another version of this application is already installed`

### Environment

```shell
C:\>winget --info
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.556
Package: Microsoft.DesktopAppInstaller v1.17.10271.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by Trenly** [comment] 2022-03-30 12:35
* Duplicate of #752

**Closed** 2022-03-30 15:12 UTC
Labels: Needs-Triage
