### ISSUE TITLE
Winget search "keyword" gives pacakge but winget list "keyword" does not

### ISSUE THREAD

**Issue by Trance-Paradox** [microsoft/winget-cli#826] opened 2021-03-29 13:53 UTC
# Brief description of your issue
winget search vscode 
This lists all version of vscode.

winget list vscode
This does not list the version of vscode installed on my system.

Also the name is changed after install.

# Expected behavior

winget list vscode 
This should list all the versions of vscode installed in the system.

# Environment

```none
[winget --info]
Windows Package Manager version : v0.2.10771 Preview
Windows: Windows.Desktop v10.0.19042.867
Package: Microsoft.DesktopAppInstaller v1.11.10771.0

Any other software?
```
![winget](https://user-images.githubusercontent.com/54877610/112847498-c2bba800-90c4-11eb-9089-f25b602197f7.JPG)

**Comment by denelon** [comment] 2021-03-29 15:17
@Trance-Paradox, what data do you believe is missing or incorrect? It appears version 1.54.3 is the version listed in search, as well as list on your machine.

**Comment by Trance-Paradox** [comment] 2021-03-29 15:28
When I list using "vscode";
No such application is found
Also when listed with moniker "vscode-system-x64"
No such application is found
![winget1](https://user-images.githubusercontent.com/54877610/112859433-770efb80-90d0-11eb-837f-4bc07e0827be.JPG)

**Comment by denelon** [comment] 2021-03-29 15:35
Ahh, I see the confusion. The "List" command is referencing programs installed on Windows from "Add/Remove Programs". Unfortunately, the "moniker" attribute (from the Windows Package Manager manifest) is not part of the package installed in "Add/Remove Programs" in Windows.

The "moniker" construct is included in a manifest for the Windows Package Manager to help with "search".

I understand your ask much better now. Thank you for the example. I'll add the "Issue-Feature" label now.

**Comment by Trance-Paradox** [comment] 2021-03-29 15:42
> Ahh, I see the confusion. The "List" command is referencing programs installed on Windows from "Add/Remove Programs". Unfortunately, the "moniker" attribute (from the Windows Package Manager manifest) is not part of the package installed in "Add/Remove Programs" in Windows.
> 
> The "moniker" construct is included in a manifest for the Windows Package Manager to help with "search".
> 
> I understand your ask much better now. Thank you for the example. I'll add the "Issue-Feature" label now.

Thank you. I understand the way packages are listed in Windows package manager manifest and in the add/remove program is different. That's why the name is also different.

**Comment by ecovio1** [comment] 2021-03-29 18:55
@denelon   
the _core issue_ is **people want to use all the winget commands** (eg:`install/uninstall/upgrade/list`) **using a package's    tag/moniker**, which is currently limited to only `install` command. 

for example here,  Visual Studio Code's tag **"VS Code"** supported only for the `install` command but other commands `list/uninstall` don't support it.

see here [for another example](https://github.com/microsoft/winget-cli/discussions/806#discussioncomment-496611) 
people get confused when the _same_ tag name used for `install` can't be used for `uninstall`.

**Comment by dougied76** [comment] 2021-04-27 02:39
7-Zip, Adobe Reader, all good examples.

**Comment by denelon** [comment] 2021-05-07 14:15
From @ecovio:

today I do winget search "keyword" ;
then winget install "same keyword" ;
but can't do winget list/upgrade/uninstall "same keyword" ;

as annoying as that
I have to first winget list ,
then winget uninstall <a packageName from list> one by one .
which is extremely annoying.
please support using "same keyword" among all commands.

not sure of it being duplicate of #826 , seemed this issue to be bit overlooked.
this issue will surely become a confusion unless addressed.

**Comment by denelon** [comment] 2021-05-07 14:16
Today `winget list <string>` does a substring search on values in ARP. We need to improve the matching for list, and we need to check manifest meta-data for search results so we find packages installed in ARP based on additional meta-data from manifests.

**Comment by ecovio1** [comment] 2021-05-07 15:31
Undoubtedly this request is one of **_the most_**  crucial/important feature request expected to be completed .

**Comment by ecovio1** [comment] 2021-05-07 15:33
Undoubtedly this request is one of **_the most_**  crucial/important feature request expected to be completed .
as this is indeed a basic feature of a proper package manager.

**Comment by Trance-Paradox** [comment] 2021-05-08 12:21
Is the naming issue also a reason why winget cannot detect a version change in upgrade command?

**Comment by denelon** [comment] 2021-06-03 20:45
This was implemented as a part of the correlation between "Add / Remove Programs" and manifests from available source(s).

**Closed by denelon** 2021-06-03 20:45 UTC
Labels: Issue-Feature
