### ISSUE TITLE
Ability to update all applications installed with latest

### ISSUE THREAD

**Issue by binarylandscapes** [microsoft/winget-cli#405] opened 2020-06-05 22:19 UTC
# Just adding ability to run additional flags that accomplish knowing what is installed currently, compare to what is available, and if a newer version is available to update to it. This should be able to be done for individual packages and for all installed packages.

Example: I already had powertoys 0.18.1 installed via winter. I would like to run `winget update powertoys` and be prompted to confirm upgrade from 0.18.1 to 0.18.2, and it upgrades. I would also like to run `winget update powertoys --confirm $False` or something similar but accomplishes the goal of upgrading with no user interaction to upgrade. In similar example run `winget update --all --confirm $False` to do same for all installed pkgs. Basically all the normal features of a package manager, if this feature request isn't already written.

# Proposed technical implementation details (optional)

**Comment by megamorf** [comment] 2020-06-07 21:14
Duplicate of #120

**Comment by denelon** [comment] 2020-06-11 20:33
Duplicate of #120

**Closed by denelon** 2020-06-11 20:33 UTC
Labels: Issue-Feature, Needs-Triage
