### ISSUE TITLE
winget downloading wrong version .NET SDK and get stuck/crashes after couple of minutes

### ISSUE THREAD

**Issue by Possemaster** [microsoft/winget-cli#2135] opened 2022-04-30 05:15 UTC
Winget gets stuck at downloading dotnet-sdk-6.0.202-win-x64.exe while I have 6.2.222.17207 installed.
If I try the download link separately it seems to be down.
Also the winget upgrade --all does not continue with the next 5 updates of other  software as it just "crashes"/ closes the Terminal screen after 3 of 4 minutes.

Below is what it is trying to do;
`(2/7) Found Microsoft .NET SDK [Microsoft.dotnet] Version 6.2.222.17207
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.202/dotnet-sdk-6.0.202-win-x64.exe`

![image](https://user-images.githubusercontent.com/7541145/166092238-06d9b37a-e9b3-477d-aaf7-34718d8a6a57.png)

**Comment by Trenly** [comment] 2022-04-30 16:16
Duplicate of #2105

**Comment by denelon** [comment] 2022-05-02 20:51
Duplicate of #2105 

The bug with a single upgrade failing during `upgrade --all` should be fixed now. It will be available in the next release.

**Closed by denelon** 2022-05-02 20:51 UTC
Labels: Needs-Triage
