### ISSUE TITLE
How to choose package or version

### ISSUE THREAD

**Issue by martonx** [microsoft/winget-cli#504] opened 2020-07-18 09:19 UTC
For example when I want to install powershell, I use this command:

winget install Microsoft.PowerShell

And I got preview and normal packages, and this message: "Multiple apps found matching input criteria. Please refine the input."

So what's next? How can I refine the input? There is no documentation about this.

**Comment by doctordns** [comment] 2020-07-18 10:10
To Install PowerShell - use the Install-PowerShell command from the PowerShell GitHub repository.

See https://github.com/PowerShell/PowerShell/blob/master/tools/install-powershell.ps1-README.md for details

Also, take a look at: https://github.com/doctordns/Wiley20/blob/master/01%20-%20Setting%20up%20V7%20environment/1.1%20Install%20PowerShell%207.ps1 which is a more workmanlike approach.

**Comment by megamorf** [comment] 2020-07-18 19:39
> So what's next? How can I refine the input? There is no documentation about this.

Sorry, but that is simply not true `winget install --help` / `winget install -?` or the docs (<https://docs.microsoft.com/windows/package-manager/winget/install#options>) list all relevant options and a quick issue search would've shown you the syntax:

```sh
winget install <id> --exact
winget install <id> --exact --version 1.2.3
```

**Comment by denelon** [comment] 2020-07-20 16:24
Duplicate of #282

**Closed by denelon** 2020-07-20 16:24 UTC
Labels: Issue-Docs, Needs-Triage
