### ISSUE TITLE
Winget sees a package to update even the new version is installed side-by-ide

### ISSUE THREAD

**Issue by msgdelm** [microsoft/winget-cli#1693] opened 2021-11-10 17:30 UTC
### Brief description of your issue

Running 'winget upgrade', shows me 'Microsoft .NET SDK' and 'Microsoft Visual C++ 2015-2022 Redistributable (x64)' to be upgraded.
Looking at versions already installed, the available version is already installed.

![image](https://user-images.githubusercontent.com/72152679/141162809-464f5295-7bb0-4864-a43a-4c5df4842d70.png)

### Steps to reproduce

Install several versions of the .NET SDK.

### Expected behavior

The new version being already installed side-by-side, it should'nt be showned as to be upgrade.

### Actual behavior

The package is always seen as to be upgraded.

### Environment

```shell
Windows Package Manager v1.1.12663
Copyright (c) Microsoft Corporation. Tous droits réservés.

Windows: Windows.Desktop v10.0.22000.318
Package: Microsoft.DesktopAppInstaller v1.16.12663.0

Journaux: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
```

**Comment by denelon** [comment] 2021-11-11 16:11
Duplicate of #1413 
We're looking at this specific situation in a couple of other issues:

* #1413
* #1192
* #1142
* #752

**Closed by denelon** 2021-11-11 16:11 UTC
Labels: Needs-Triage

**Comment by dafunks** [comment] 2022-06-27 18:56
This is still an issue. I dont think it ever got fixed. Currently showing version 14.30.30704.0 is installed but always showing 14.32.31326.0

No matter how many times I update it always shows which makes doing a full `winget upgrade -h --all` annoying as it always downloads and upgrades even though it isnt needed. 

Maybe something new has been added to stop this or some bypass?

**Comment by denelon** [comment] 2022-06-27 23:34
@dafunks

This issue was marked as a duplicate of:

* #1413 

That issue hasn't been closed yet. For "side-by-side" packages, we need to check if the latest is installed, and not show it as a potential upgrade for an older version currently installed on the system.
