### ISSUE TITLE
Multiple apps found matching input criteria when trying to install PowerShell 7.0.1

### ISSUE THREAD

**Issue by AdilHindistan** [microsoft/winget-cli#282] opened 2020-05-22 01:43 UTC
# Brief description of your issue
When I try to install PowerShell 7.0.1, winget cannot seem to locate the correct one

# Steps to reproduce
None of these work
winget install PowerShell
winget install Powershell
winget install Microsoft.Powershell
winget install --id Microsoft.Powershell --version 7.0.1

# Expected behavior

It should pick up Powershell 7.0.1 (btw, that should have been named PowerShell not Powershell)

# Actual behavior
I get the following:
```None
Multiple apps found matching input criteria. Please refine the input.
Name               Id                           Version
---------------------------------------------------------------
Powershell         Microsoft.Powershell         7.0.1
PowerShell-Preview Microsoft.PowerShell-Preview 7.1.0-preview.3
```

# Environment

```none
PS C:\Users\adil> winget --info
Windows Package Manager v0.1.41331 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.18363.836
Package: Microsoft.DesktopAppInstaller v1.0.41331.0

Links:
  Privacy Statement: https://aka.ms/winget-privacy
  License agreement: https://aka.ms/winget-license
  3rd Party Notices: https://aka.ms/winget-3rdPartyNotice
  Homepage:          https://aka.ms/winget


```

**Comment by CPUTek1** [comment] 2020-05-22 03:11
I have the same issue trying to Install FireFox.

**Comment by SteveL-MSFT** [comment] 2020-05-22 03:31
It seems that if there is an exact match, then that should be installed.

**Comment by kramfs** [comment] 2020-05-22 07:27
I was able to install or upgrade PowerShell using the exact match parameter
`winget install -e Microsoft.Powershell -v 7.0.1`

**Comment by doctordns** [comment] 2020-05-22 07:52
A better solution to installing PowerShell7 is to use the install-powershell command in power shell's github repo. It gives you much more flexibility. It can also be remoted over PS Remoting, which winget appears to not handle.

**Comment by kramfs** [comment] 2020-05-22 08:02
> A better solution to installing PowerShell7 is to use the install-powershell command in power shell's github repo. It gives you much more flexibility. It can also be remoted over PS Remoting, which winget appears to not handle.

Good point but I believed winget was designed in similar functionality to apt utility, meaning you have to be on the server/machine in some form to use it. I guess you can use PS and winget together to extend that functionality...my 2c

**Comment by marvinpuethe** [comment] 2020-05-22 09:06
I ran into the same problem today. I would expect it to be interactive like:

"Multiple packages matched your query. Please select one of the following:
[1] Microsoft.Powershell
[2] Microsoft.PowerShell-Preview"

Anyway thanks for the awesome work 💪

**Comment by Elohirr** [comment] 2020-05-22 19:51
This worked fine about 2 days ago, but the 7.1.0 preview version was not available at that time.  Unfortunately, I am not having any success using the '-e' switch either. :(

**Comment by sahammer** [comment] 2020-05-22 21:51
Ran into this same issue as well.

 `winget install -e Microsoft.Powershell` did work for me but these circumstances should probably be handled a bit cleaner with perhaps a selection list or some other method. 

Thanks for the great work on this!

**Comment by AdilHindistan** [comment] 2020-05-23 17:43
> I ran into the same problem today. I would expect it to be interactive like:
> 
> "Multiple packages matched your query. Please select one of the following:
> [1] Microsoft.Powershell
> [2] Microsoft.PowerShell-Preview"
> 
> Anyway thanks for the awesome work

The problem is, preview version should not even come up when the version is specified. Names are similar but versions are different. It's as if version is totally ignored.

**Comment by chelnak** [comment] 2020-05-23 19:08
`winget install -e Microsoft.Powershell` doesn't work here.

**Comment by doctordns** [comment] 2020-05-23 19:16
How would I discover -e. And what does '-e' mean? 
A bad UI.

**Comment by chelnak** [comment] 2020-05-23 19:19
`winget install --info`

**Comment by orta** [comment] 2020-05-24 17:21
I had a similar problem trying to install Discord

```
PS C:\Users\orta> winget
Windows Package Manager v0.1.41331 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

WinGet command line utility enables installing applications from the command line.
usage: winget [<command>] [<options>]

The following commands are available:
  install   Installs the given application
  show      Shows info about an application
  search    Find and show basic info of apps
  hash      Helper to hash installer files
  validate  Validates a manifest file

For more details on a specific command, pass it the help argument. [-?]

The following options are available:
  -v,--version  Display the version of the tool
  --info        Display general info of the tool

More help can be found at: https://aka.ms/winget-command-help

PS C:\Users\orta> winget install discord
Multiple apps found matching input criteria. Please refine the input.
Name           Id                    Version
--------------------------------------------
Discord        Discord.Discord       0.0.306
Discord Canary Discord.DiscordCanary 0.0.264

PS C:\Users\orta> winget install discord.discord
Multiple apps found matching input criteria. Please refine the input.
Name           Id                    Version
--------------------------------------------
Discord        Discord.Discord       0.0.306
Discord Canary Discord.DiscordCanary 0.0.264
PS C:\Users\orta> winget install Discord.Discord
Multiple apps found matching input criteria. Please refine the input.
--------------------------------------------
Discord        Discord.Discord       0.0.306
Discord Canary Discord.DiscordCanary 0.0.264

PS C:\Users\orta> winget install --help
Windows Package Manager v0.1.41331 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Installs the given application

usage: winget install [[-q] <query>] [<options>]

The following arguments are available:
  -q,--query        The query used to search for an app

The following options are available:
  -m,--manifest     The path to the manifest of the application
  --id              Filter results by id
  --name            Filter results by name
  --moniker         Filter results by app moniker
  -v,--version      Use the specified version; default is the latest version
  -s,--source       Find app using the specified source
  -e,--exact        Find app using exact match
  -i,--interactive  Request interactive installation; user input may be needed
  -h,--silent       Request silent installation
  -o,--log          Log location (if supported)
  --override        Override arguments to be passed on to the installer
  -l,--location     Location to install to (if supported)

More help can be found at: https://aka.ms/winget-command-install

PS C:\Users\orta> winget install --id Discord.Discord
Multiple apps found matching input criteria. Please refine the input.
Name           Id                    Version
--------------------------------------------
Discord        Discord.Discord       0.0.306
Discord Canary Discord.DiscordCanary 0.0.264
```

( and I kinda left it at that and installed it manually )

**Comment by AdilHindistan** [comment] 2020-05-24 17:42
@orta it would probably work if you used 
`winget install --exact Discord.Discord` or `winget install -e Discord.Discord`

problem is that:
1) -e option is not obvious
2) It's Case sensitive, and that's not obvious either
both of these are documentation problems. If winget team took a clue from PowerShell team and actually created a help that's useful, with examples, people could have discovered how to do these.

There are other problems though, mainly disregard for version. I cannot think of any good reason why this should not work:
`winget install --id Discord.Discord --version 0.0.306`

that's nuts!

**Comment by JulianChow94** [comment] 2020-05-26 04:11
My takeaway here is the semantic text being used here. Right now `winget install` behaves **exactly** like `winget show` at times where it can't find an exact output.

`install` is a command, the verb is specific in nature and implicitly suggests that it expects an exact match. The install command should `fail` when a exact match cannot be picked out (with appropriate messaging).

**Comment by doctordns** [comment] 2020-05-26 08:46
How does Winget KNOW that I do not want both versions loaded? I have two versions of Snagit, Multiple versions of.NET, etc.
And if 'install' is a verb, then 'show' should be 'get'.
From my phone so apologies for the typos.
!

________________________________

**Comment by TravisEz13** [comment] 2020-05-26 21:00
BTW
```
winget install -e Microsoft.Powershell
```

will install 7.0.0

to install the latest run

```
winget install -e Microsoft.PowerShell
```

**Comment by abshirahmed** [comment] 2020-05-30 15:58
> BTW
> 
> ```
> winget install -e Microsoft.Powershell
> ```
> 
> will install 7.0.0
> 
> to install the latest run
> 
> ```
> winget install --id Microsoft.PowerShell -e
> ```
> 
> This worked for me, but others have reported that it didn't work (I see a PR has been made to make this work):
> 
> ```
> winget install -e Microsoft.PowerShell
> ```

I had that issue and `winget install Microsoft.PowerShell -e` worked like a charm

**Comment by AbdulMufeez-code** [comment] 2020-06-01 12:44
same issue with me but installing git through winget

**Comment by alecxvs** [comment] 2020-06-03 01:34
I ran into this issue specifically with terminal; I saw on one of the [blogs about winget](https://devblogs.microsoft.com/commandline/windows-package-manager-preview/) suggesting i could simply "winget install terminal" and I was very excited to try this 😅 

I think one solution (to these specific packages) is to exclude preview/prerelease packages unless a flag is provided. Notify that prereleases are available if you insist, but unless a user is explicitly trying to install a prerelease, listing it in the default query may not be helpful.

Although hiding the preview is a solution for now, if someone comes along with SuperTerminal or TerminalX, users will have the exact same issue again, needing to qualify "Microsoft.WindowsTerminal" (it's a lot to type, relative to other package managers, `terminal` is a lot more concise and memorable!). I imagine some kind of name aliasing for packages or prompting the user to ask about a best match (unless it's run non-interactively) would be better long term solutions.

**Comment by SubhamK108** [comment] 2020-06-03 12:55
At the moment, when installing apps with multiple search results, the following nomenclature is working perfectly:

`winget install --name <appName> -e`

Note that the <appName> is Case Sensitive !

**Comment by denelon** [comment] 2020-06-04 16:25
@SubhamK108 Thanks for the short solution.

#292 is part of the fix for this issue.

**Comment by TravisLRiffle** [comment] 2020-06-11 08:18
> I was able to install or upgrade PowerShell using the exact match parameter
> `winget install -e Microsoft.Powershell`

This also worked for me, although I did get an error with Google Chrome about the "installer hash verification failed."  Everything else worked great.

**Comment by amos-ortal** [comment] 2020-06-16 17:04
> I was able to install or upgrade PowerShell using the exact match parameter
> `winget install -e Microsoft.Powershell`

The documentation/help is not clear about -e which is too bad and easy to fix

**Comment by Sciroccogti** [comment] 2020-06-18 04:38
> `winget install -e Microsoft.PowerShell` doesn't work.
> 
> `winget install -e Microsoft.Powershell` **does** work.
> 
> The search is case sensitive! ([microsoft/winget-pkgs#884](https://github.com/microsoft/winget-pkgs/pull/884))

However, now things have changed:
`winget install -e Microsoft.PowerShell` **does** work while `winget install -e Microsoft.Powershell` doesn't work.

**Comment by plipowczan** [comment] 2020-06-23 08:04
@Sciroccogti The same for me.

**Comment by Sciroccogti** [comment] 2020-06-23 10:44
> @Sciroccogti The same for me. However at the end of installation I received a message "Installation abandoned". Nevertheless the installation completed successfully.

Oh yes I received that message as well, but I was running the powershell installation in powershell itself, so I think it's normal for it to be 'abandoned'.

**Comment by robinwilson16** [comment] 2020-07-01 20:01
Same issue trying to install Terminal as others have stated:

```
winget install Microsoft.WindowsTerminal
```

Fails with:
```
Multiple apps found matching input criteria. Please refine the input.
Name                     Id                               Version
--------------------------------------------------------------------
Windows Terminal         Microsoft.WindowsTerminal        1.0.1401.0
Windows Terminal Preview Microsoft.WindowsTerminalPreview 1.1.1671.0
```

Workaround confirmed working using the -e:
```
winget install -e Microsoft.WindowsTerminal
```

Using this as install button is broken in Microsoft Store again and re-registering app-x packages is failing this time.

**Comment by ggggpy** [comment] 2020-07-18 13:01
`winget install --id<appID> -e`

**Comment by taikodrum** [comment] 2020-07-20 16:20
Like the others, I'm having the same sort of issue 

`winget install Google.Chrome`

outputs this
```
Multiple apps found matching input criteria. Please refine the input.
Name        Id                Version
------------------------------------------
Chrome      Google.Chrome     84.0.4147.89
Chrome Beta Google.ChromeBeta 84.0.4147.38
```

Only was able to work with the -e flag
`winget install -e Google.Chrome`

If package IDs were unique, shouldn't the install command default to ID for seamless usage?

**Comment by denelon** [comment] 2020-07-20 16:26
There were a few steps involved in getting a solution to this Issue. We are using some of the same codebase on the server to build the database of apps. The issue is that a substring wasn't being treated as an "exact" match for show or install. We're testing a version of the client that will hopefully provide a resolution.

**Comment by robinwilson16** [comment] 2020-07-21 07:40
Also in the screenshot above is it a bit strange that Chrome Beta is actually an older version than Chrome non-beta. Does this mean repos are not yet kept up to date?

**Comment by denelon** [comment] 2020-08-11 18:35
@AdilHindistan this Issue should be resolved with the current release of the client (v0.1.42101 Preview). The matching criteria for `show` and `install` are identical and will lock on an "exact" string match. The matching criteria for search is still more broad to help locate packages with matching substrings.

**Comment by denelon** [comment] 2020-08-11 18:36
Fixed in https://github.com/microsoft/winget-cli/releases/tag/v0.1.42101-preview

**Closed by denelon** 2020-08-11 18:36 UTC
Labels: Issue-Feature

**Comment by pressRtowin** [comment] 2021-06-02 19:45
I have a similar issue trying to upgrade Plexamp. I'm not sure why but it detects multiple instances on my system.

```
Multiple installed packages found matching input criteria. Please refine the input.
Name          Id
----------------------------------------------------
Plexamp       Plex.Plexamp
Plexamp 3.4.4 {46418f0f-cea3-5740-a7e9-a0166db1e7c4}
```

You'd think `winget upgrade Plex.Plexamp -e` or `winget upgrade -e Plex.Plexamp` (both similar to suggestions listed above) would work, but they don't. Neither do `winget upgrade --id Plex.Plexamp -e` nor winget upgrade --name Plexamp -e`. Driving me crazy honestly.

**Comment by denelon** [comment] 2021-06-02 19:58
@pressRtowin what is the output for `winget list plexamp` and `winget upgrade`?

**Comment by pressRtowin** [comment] 2021-06-02 20:24
@denelon


```
Name    Id           Version Available Source
---------------------------------------------
Plexamp Plex.Plexamp 3.4.6
Plexamp Plex.Plexamp 3.4.4   3.4.6     winget
```

The second line is from running `winget install --id Plex.Plexamp -e` which worked unlike `upgrade`. `winget upgrade` only shows 'Plexamp             Plex.Plexamp                 3.4.4    3.4.6         winget' now since running that, but before it showed something similar (without winget as the source). It never displayed the {windowsappIDnonsense} version in the upgrade list.

**Comment by denelon** [comment] 2021-06-02 23:14
Is it working correctly now?

I've run into cases where a package installed two instances in Add/Remove Programs. The Cura program is an .exe installer that doesn't "upgrade" it just installs the new version beside the old one. I had 4.8.0 on my machine, and I ran `winget upgrade`. It then installed the 4.9.1 version, and now when I run `winget list cura` you see the old one looks like an upgrade is available, and the new one is current.

```
 winget list cura
Name           Id             Version Available Source
------------------------------------------------------
Ultimaker Cura Ultimaker.Cura 4.8.0   4.9.1     winget
Ultimaker Cura Ultimaker.Cura 4.9.1
```

**Comment by pressRtowin** [comment] 2021-06-03 20:49
Nothing has changed.

**Comment by denelon** [comment] 2021-06-03 20:54
@pressRtowin I just tested:


```
PS C:\Users\denelon> winget search PowerShell
Name                      Id                                  Version         Match           Source
----------------------------------------------------------------------------------------------------
PowerShell                Microsoft.PowerShell                7.1.3                           winget
Windows Terminal Preview  Microsoft.WindowsTerminalPreview    1.9.1445.0      Tag: PowerShell winget
Windows Terminal          Microsoft.WindowsTerminal           1.8.1444.0      Tag: powershell winget
PowerShell-Preview        Microsoft.PowerShell-Preview        7.2.0-preview.6 Tag: powershell winget
EasyConnect               lstratman.easyconnect               3.1.0.105       Tag: powershell winget
Oh My Posh                JanDeDobbeleer.OhMyPosh             3.160.1         Tag: PowerShell winget
PowerShell Preview (MSIX) Microsoft.PowerShell-Preview-MSIX   7.0.2                           winget
PowerShell Universal      IronmanSoftware.PowerShellUniversal 1.4.0                           winget
PS C:\Users\denelon> winget install PowerShell
Found PowerShell [Microsoft.PowerShell]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/PowerShell/PowerShell/releases/download/v7.1.3/PowerShell-7.1.3-win-x64.msi
  ██████████████████████████████  95.0 MB / 95.0 MB
Successfully verified installer hash
Starting package install...
Successfully installed
PS C:\Users\denelon>
```

What version of the Windows Package Manager are you running?

**Comment by pressRtowin** [comment] 2021-06-03 21:08
`Windows Package Manager v1.0.11451`

**Comment by denelon** [comment] 2021-06-03 22:37
@pressRtowin can you share output like I did from the same two commands? I'd like to see what might be different.

**Comment by pressRtowin** [comment] 2021-06-03 22:45
I have no issues installing powershell...

**Comment by denelon** [comment] 2021-06-03 22:56
@pressRtowin it looks like two instances of Plexamp were installed on your system. That's the same as the "Cura" example I have above. I don't know if the Plexamp installer actually recognizes the earlier version and upgrades it or if it is designed to support "side by side" installation. Some packages are designed with this intentional behaviors. For packages that aren't, you might need to have the manifest modified for the "UpgradeBehavior" to specify uninstall to remove the "older" version before installing the "newer" version.

**Comment by pressRtowin** [comment] 2021-06-03 23:02
@denelon Doesn't really explain why winget is giving a "Please refine the input." error and not some type of installation error, especially when I'm specifying an exact match using the ID fields which are clearly different in the two matches that it finds. The duplicate IDs in `winget list plexamp` would've only been a thing after I ran the install command but I was having the same error before that.

**Comment by denelon** [comment] 2021-06-03 23:10
Generally, the "Please refine the input" error happens when the client needs the user to disambiguate between multiple options. This happens several places in the code. If the -id is not distinctly identifying the package manifest or a "single" entry in "Add / Remove Programs" this happens. I believe what is happening is either the two entries in "Add / Remove Programs" aren't unique enough (I think there is work here in the client), or for some reason more than one manifest matched some set of criteria. This may be similar to https://github.com/microsoft/winget-pkgs/discussions/16038

**Comment by SiJiL82** [comment] 2021-06-14 12:16
Getting a similar situation trying to upgrade the .NET 5.0 SDK. Because I also have the 6.0 preview, it picks that up too, and returns "refine the input" even if I specify the ID of the 5.0 package:

`C:\> winget upgrade --id Microsoft.dotnet
Multiple installed packages found matching input criteria. Please refine the input.
Name                                               Id
-----------------------------------------------------------------------------------------
Microsoft .NET SDK                                 Microsoft.dotnet
Microsoft .NET SDK 6.0.100-preview.4.21255.9 (x64) {e0100246-937c-4ed6-b71f-2e37cf75fe43}`

**Comment by nascentt** [comment] 2021-08-28 12:57
This issue still exists:

PS C:\WINDOWS\system32> winget upgrade
Name                         Id                             Version     Available   Source
------------------------------------------------------------------------------------------
TeamViewer                   TeamViewer.TeamViewer          15.21.5     15.21.6     winget
TeraCopy                     CodeSector.TeraCopy            3.8.2       3.8.5       winget
Plexamp                      plex.Plexamp                   3.4.0       3.5.0       winget
Python 3                     Python.Python.3                3.9.5150.0  3.9.6150.0  winget

PS C:\WINDOWS\system32> winget upgrade codesector.teracopy
Multiple installed packages found matching input criteria. Please refine the input.
Name                   Id
------------------------------------------
TeraCopy               CodeSector.TeraCopy
TeraCopy version 3.8.2 TeraCopy_is1

PS C:\WINDOWS\system32> winget upgrade python.python.3
Multiple installed packages found matching input criteria. Please refine the input.
Name                  Id
------------------------------------------------------------
Python 3              Python.Python.3
Python 3.9.5 (32-bit) {708847ae-c2de-49fb-9b85-8d2e9c991358}

PS C:\WINDOWS\system32> winget upgrade plex.plexamp
Multiple installed packages found matching input criteria. Please refine the input.
Name          Id
----------------------------------------------------
Plexamp       plex.Plexamp
Plexamp 3.4.0 {46418f0f-cea3-5740-a7e9-a0166db1e7c4}

**Comment by SiJiL82** [comment] 2021-09-07 19:08
Any news on this - it's rendering winget basically unusable for alot of packages, in part because "exact" doesn't seem to mean exact at all. For example:

`winget upgrade -e "Microsoft Visual C++ 2013 Redistributable (x86)"
Multiple installed packages found matching input criteria. Please refine the input.
Name                                                         Id
---------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2013 Redistributable (x86)              Microsoft.VC++2013Redist-x86
Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.40664 {042d26ef-3dbe-4c25-95d3-4c1b11b235a7}`

I've include "x86" in my name parameter, so why is it "exactly" matching the x64 version?

**Comment by robross0606** [comment] 2021-09-11 16:26
This is _still_ not working for `upgrade` command:
```
C:\Users\me>winget upgrade -e Python.Python.3
Multiple installed packages found matching input criteria. Please refine the input.
Name                   Id
-------------------------------------------------------------
Python 3               Python.Python.3
Python 2.7.18 (64-bit) {A5F504DF-2ED9-4A2D-A2F3-9D2750DD42D6}

C:\Users\me>winget show -e Python.Python.3
Found Python 3 [Python.Python.3]
Version: 3.9.7150.0
Publisher: Python Software Foundation
Author: Python Software Foundation
Moniker: python3
Description: Python is a programming language that lets you work more quickly and integrate your systems more effectively.
Homepage: https://www.python.org
License: PSF LICENSE AGREEMENT FOR PYTHON
License Url: https://docs.python.org/3/license.html
Installer:
  Type: Burn
  Locale: en-US
  Download Url: https://www.python.org/ftp/python/3.9.7/python-3.9.7-amd64.exe
  SHA256: 3f63f4c77a6da13f9bae715eb6644a48bd5f900601e0f1f233862e8ca1a96dd8

C:\Users\me>winget upgrade --id Python.Python.3 -e
Multiple installed packages found matching input criteria. Please refine the input.
Name                   Id
-------------------------------------------------------------
Python 3               Python.Python.3
Python 2.7.18 (64-bit) {A5F504DF-2ED9-4A2D-A2F3-9D2750DD42D6}
```

**Comment by VincentVerweij** [comment] 2021-09-13 18:11
Stumbled upon this issue when trying to perform `winget upgrade Microsoft.Teams`.
It is giving me the following output:
```
Multiple installed packages found matching input criteria. Please refine the input.
Name            Id
-------------------------------
Microsoft Teams Microsoft.Teams
Microsoft Teams Teams
```

I did see in this discussion issue that people are mentioning to use the -e flag (or --exact), but when doing so I still get the same output as mentioned above.

I also looked at the casing as this seems to be case sensitive, but no luck there either.

**Comment by Elias-Graf** [comment] 2021-09-23 14:06
```txt
C:\Users\Elias> winget uninstall Toinane.Colorpicker
Multiple installed packages found matching input criteria. Please refine the input.
Name              Id
--------------------------------------------------------
Colorpicker       Toinane.Colorpicker
Colorpicker 2.0.3 {2fa01720-ea93-5692-9697-66fad2caf3bf}
C:\Users\Elias> winget uninstall -e --id Toinane.Colorpicker
Multiple installed packages found matching input criteria. Please refine the input.
Name              Id
--------------------------------------------------------
Colorpicker       Toinane.Colorpicker
Colorpicker 2.0.3 {2fa01720-ea93-5692-9697-66fad2caf3bf}
```

**Comment by denelon** [comment] 2021-10-21 14:35
This issue was related to PowerShell and the "install" command. 

There are various reasons why the winget client is having trouble with disambiguation. I've created a couple of new issues for specific impacted scenarios so we can isolate and resolve them. In some cases, the problem needs to be fixed in the manifest, or the package installer itself rather than the winget client.

We need specific actionable issues so we can isolate the cause(s), and resolve them. Some of the Issues are too broad and generic to be confident they have been resolved. Sadly when those are encountered, we end up with multiple reports of something that isn't quite the same. In those cases, I have been trying to create discrete Issues to identify the specific scenario impacted.

There are a few exceptions, and in those cases, I close the original as a duplicate, and refer to another issue we're working on. Sometimes one fix impacts multiple different scenarios.

I blogged about some [tips](https://devblogs.microsoft.com/commandline/windows-package-manager-1-1/#customization-tips) with using multiple sources.

**Comment by FLevent29** [comment] 2021-12-10 16:02
```powershell
PS C:\> winget upgrade -e --id 'Microsoft.VC++2015-2022Redist-x86'
Multiple installed packages found matching input criteria. Please refine the input.
Name                                                               Id
---------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015-2022 Redistributable (x86)               Microsoft.VC++2015-2022Redist-x86
Microsoft Visual C++ 2015-2019 Redistributable (x64) - 14.29.30135 {fa7f6d52-f85e-48ef-8f56-a37268aa5772}
PS C:\>
```

Regardless whether it's even worth updating this package, how does one get more specific than this?

**Comment by denelon** [comment] 2021-12-10 16:59
@FLevent29 this is a bug. We're working on additional schema changes to better match what we see in Apps & Features. This is one of our prime test cases for ensuring the matching logic is improved. The schema has been updated, now we need to do the work in the client to leverage the fields. Please add your 👍 to #980.

**Comment by ageekhere** [comment] 2022-01-21 23:56
`Microsoft Visual C++ 2008 Redistributable - x86 Microsoft.VC++2008Redist-x86 9.0.30729.4148 9.0.30729.6161 winget
Microsoft Visual C++ 2008 Redistributable - x64 Microsoft.VC++2008Redist-x64 9.0.30729.4148 9.0.30729.6161 winget
2 upgrades available.

winget upgrade Microsoft.VC++2008Redist-x86

Multiple installed packages found matching input criteria. Please refine the input.
Name                                                           Id
-----------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2008 Redistributable - x86                Microsoft.VC++2008Redist-x86
Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.6161 {9BE518E6-ECC6-35A9-88E4-87755C07200F}
Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.4148 {4B6C7001-C7D6-3710-913E-5BC23FCE91E6}
Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.6161 {5FCE6D76-F5DC-37AB-B2B8-22AB8CEDB1D4}
Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.17   {9A25302D-30C0-39D9-BD6F-21E6EC160475}`

I will also leave this here in the hope that it will get fixed

**Comment by spicycoder** [comment] 2022-02-19 18:06
Facing same with Python 2 & .NET SDK

```ps1
👽  winget upgrade -e Python.Python.2
Multiple installed packages found matching input criteria. Please refine the input.
Name                   Id
-------------------------------------------------------------
Python 2               Python.Python.2
Python 2.7.18 (64-bit) {A5F504DF-2ED9-4A2D-A2F3-9D2750DD42D6}
```

```ps1
👽  winget upgrade -e Microsoft.dotnet
Multiple installed packages found matching input criteria. Please refine the input.
Name                             Id
-----------------------------------------------------------------------
Microsoft .NET SDK               Microsoft.dotnet
Microsoft .NET SDK 5.0.405 (x64) {343a89ec-9510-4063-9421-b0767cc25d40}
```

amazing tool btw, thanks

**Comment by LogicBypass** [comment] 2023-04-16 10:55
People just follow the recommendation! Example:
```
 winget install --name PowerShell --exact --source winget
Multiple packages found matching input criteria. **Please refine the input.**
Name               Id                           Source
------------------------------------------------------
PowerShell Preview Microsoft.PowerShell.Preview winget
PowerShell         Microsoft.PowerShell         winget 
```

**REFINE THE INPUT!** Use Id, version, or anything that distinguishes the package.
Example:
`winget install --name PowerShell --exact --Id Microsoft.PowerShell --source winget`

**Comment by SuperBartimus** [comment] 2023-10-11 16:45
I'm seeing this as well:
`
winget upgrade --include-unknown
Name                                                   Id                            Version        Available     Source
------------------------------------------------------------------------------------------------------------------------
Google Chrome                                          Google.Chrome                 117.0.5938.150 118.0.5993.71 winget
Windows Terminal                                       Microsoft.WindowsTerminal     1.18.2681.0    1.18.2822.0   winget
OBS Studio                                             OBSProject.OBSStudio          29.0.2         29.1.3        winget
Google Chrome                                          Google.Chrome                 117.0.5938.150 118.0.5993.71 winget
Microsoft ASP.NET Core 3.1.32 - Shared Framework (x64) Microsoft.DotNet.AspNetCore.6 < 6.0.5        6.0.23        winget
5 upgrades available.
`
I then perform:
`
Winget upgrade --disable-interactivity --force --id google.chrome
Found Google Chrome [Google.Chrome] Version 118.0.5993.71
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi
  ██████████████████████████████   103 MB /  103 MB
Successfully verified installer hash
Starting package install...
Successfully installed
`
and then going back to:
`
winget upgrade --include-unknown
Name                                                   Id                            Version        Available     Source
------------------------------------------------------------------------------------------------------------------------
Google Chrome                                          Google.Chrome                 117.0.5938.150 118.0.5993.71 winget
Windows Terminal                                       Microsoft.WindowsTerminal     1.18.2681.0    1.18.2822.0   winget
OBS Studio                                             OBSProject.OBSStudio          29.0.2         29.1.3        winget
Microsoft ASP.NET Core 3.1.32 - Shared Framework (x64) Microsoft.DotNet.AspNetCore.6 < 6.0.5        6.0.23        winget
4 upgrades available.
`
You can see it upgraded one of them. If I do the the upgrade command again, I get this:
`
Winget upgrade --disable-interactivity --force --id Google.Chrome
No available upgrade found.
No newer package versions are available from the configured sources.
`
And if I issue this command, this is the result:
`
Winget upgrade --disable-interactivity --force --name "Google Chrome"
Multiple installed packages found matching input criteria. Please refine the input.
Name          Id
---------------------------
Google Chrome Google.Chrome
Google Chrome Google.Chrome
`

Using the --exact flag doesn't help.

I'm also experiencing this issue with `Microsoft.DotNet.AspNetCore.6`

**Comment by LogicBypass** [comment] 2023-10-14 20:03
@SuperBartimus
And again...
Your output:
```
Name                                                  Id                            Version        Available     Source
------------------------------------------------------------------------------------------------------------------------
Google Chrome                                      Google.Chrome                 117.0.5938.150   118.0.5993.71 winget
```
You can notice the DIFFERENCE in the output, you have the version "117.0.5938.150" while the NEWER version is "118.0.5993.71"
What is the PROBLEM with DEFINING THE VERSION in your command?

`winget upgrade --name "Google Chrome" --version 118.0.5993.71`

**REFINE THE INPUT! Use Id, version, or anything that distinguishes the package.**
