### ISSUE TITLE
Shorthand Versions of Commands

### ISSUE THREAD

**Issue by murnux** [microsoft/winget-cli#204] opened 2020-05-19 19:22 UTC
# Description of the new feature/enhancement

Currently to install a package, you would type `winget install <package>`

I think it's always good for package managers to help users save on as much typing as possible, thus I would like to propose 'shorthand' versions of the winget commands, so for example for install we would have: `winget in <package>`

I believe this is a very handy feature from package managers such as **dnf** and **zypper**.

# Proposed technical implementation details (optional)

I need to familiarize myself with the code more, but I would presume this is an easy fix and am happy to look into it as time allows.

**Comment by Atemu** [comment] 2020-05-19 19:45
Pacman-style commands would also be great.

In case you're unfamiliar with Arch's Pacman, syncing the repos, upgrading all installed packages and install <pkgname> can be done in a simple and concise `pacman -Syu <pkgname>`.

See https://www.archlinux.org/pacman/pacman.8.html#_sync_options_apply_to_em_s_em_a_id_so_a

**Comment by utybo** [comment] 2020-05-19 20:10
I find pacman's syntax to be very unclear and confusing. One letter shortcuts like `winget i` for `winget install` seem to be much clearer. Also, does winget even have a "sync" step?

**Comment by denelon** [comment] 2020-05-19 21:28
We're already working on Autocomplete [tab] in PowerShell. Would that help?

**Comment by denelon** [comment] 2020-05-19 21:29
#146

**Comment by utybo** [comment] 2020-05-19 21:33
It would help, yes, and I guess users could always just make their own aliases (e.g. wgi for winget install)

**Comment by murnux** [comment] 2020-05-19 21:36
> 
> 
> We're already working on Autocomplete [tab] in PowerShell. Would that help?

Yes that seems like a good way to go about it, thanks!

**Comment by denelon** [comment] 2020-05-19 22:39
Duplicate of #146

**Closed by denelon** 2020-05-19 22:39 UTC
Labels: Issue-Feature
