### ISSUE TITLE
Powershell ConvertTo-Json Pipe

### ISSUE THREAD

**Issue by danielehrhardt** [microsoft/winget-cli#1039] opened 2021-05-31 00:07 UTC
# Description of the new feature/enhancement
It would be nice if the `winget list` command could be piped to the ConvertTo-Json Powershell Pipe

Current Behavior:
```
[
    "   \b-\b ",
    "Name                                 ID                                    Version               Verf├╝gbar       Quelle",
    "-----------------------------------------------------------------------------------------------------------------------",
    "Streamlabs OBS                       Streamlabs.StreamlabsOBS              1.0.7                 1.1.2           winget",
    "Inspect 0.6.
```

# Proposed technical implementation details (optional)
`winget list | ConvertTo-Json`

**Comment by denelon** [comment] 2021-06-01 15:36
@danielehrhardt native PowerShell support is on the backlog. We're going to start working on some preview cmdlets. Take a look at the backlog and be sure to 👍 the features you feel are important. I'm going to close this as a duplicate of native PowerShell support.

**Comment by denelon** [comment] 2021-06-01 15:37
Duplicate of #221 Add Native PowerShell Support

**Closed by denelon** 2021-06-01 15:37 UTC
Labels: Issue-Feature

**Comment by danielehrhardt** [comment] 2021-06-01 15:47
> @danielehrhardt we've identified this Issue as a duplicate of another one that already exists. This specific instance is being closed in favor of tracking the concern over on the referenced Issue. Thanks for your report! Be sure to add your 👍 to the other issue to help raise the priority.

You should comment the duplicated issue here for better search results.
