### ISSUE TITLE
Failed in attempting to update the source: winget, LTSC

### ISSUE THREAD

**Issue by dehlong** [microsoft/winget-cli#3692] opened 2023-09-27 15:36 UTC
### Brief description of your issue

I am running windows 2021 enterprise IOT ltsc and I installed winget via the official guide:https://learn.microsoft.com/en-us/windows/iot/iot-enterprise/deployment/install-winget-windows-iot as I do not have MS store, nor do I plan to install it.

Each time I run the command, I get:
Failed in attempting to update the source: winget

However, rest of the functions are normal. I managed to install an application, uninstall an application and even update all of them.

### Steps to reproduce

Install winget of my version to LTSC.

### Expected behavior

No error message at the beginning

### Actual behavior

![image](https://github.com/microsoft/winget-cli/assets/112163027/ad4faf59-b5a6-4760-8126-da5446425dab)

### Environment

```shell
Windows Package Manager v1.6.2631
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.3448
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.2631.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by mdanish-kh** [comment] 2023-09-27 15:43
Duplicate of #3687

**Closed** 2023-09-27 15:43 UTC
