### ISSUE TITLE
Some localized strings are missing spaces between format placeholders

### ISSUE THREAD

**Issue by chausner** [microsoft/winget-cli#3560] opened 2023-08-26 22:54 UTC
### Brief description of your issue

In all languages except English, the resource strings "Usage" and "InstalledPackageVersionNotAvailable" are missing spaces between the string format placeholders {0}, {1} etc. This leads to missing spaces when these strings are printed.

### Steps to reproduce

Run `winget export` on a German system. It outputs:
> Schreibt eine Liste der installierten Pakete in eine Datei. Die Pakete können dann mit dem Befehl "import" installiert werden.
>
> Verwendung: wingetexport [-o] \<output\> [\<Optionen\>]
>
> ...

Note the missing space between "winget" and "export".

### Expected behavior

It should print
> Verwendung: winget export [-o] \<output\> [\<Optionen\>]

### Actual behavior

There are missing spaces.

### Environment

```shell
Windows-Paket-Manager (Vorschau) v1.6.2291-preview
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.22631.2199
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.21.2291.0
```

**Comment by Trenly** [comment] 2023-08-27 01:19
* Duplicate of https://github.com/microsoft/winget-cli/issues/3412

**Closed** 2023-08-27 13:07 UTC
Labels: In-PR, Needs-Triage
