### ISSUE TITLE
Please support usage of  winget [<commands>] "same keyword" 

### ISSUE THREAD

**Issue by ecovio1** [microsoft/winget-cli#935] opened 2021-05-07 09:26 UTC
# Description of the new feature/enhancement

today I do `winget search "keyword"` ; 
then `winget install "same keyword" `; 
but can't do `winget list/upgrade/uninstall "same keyword" `;  

as annoying as that 
I have to first  `winget list `, 
then `winget uninstall <a packageName from list> `one by one . 
which is extremely annoying. 
please support using `"same keyword"` among all commands.

not sure of it being duplicate of #826 , seemed this issue to be bit overlooked. 
this issue will surely become a confusion unless addressed.

**Comment by denelon** [comment] 2021-05-07 14:13
Be sure to thumbs up #826

**Comment by denelon** [comment] 2021-05-07 14:13
Duplicate of #826

**Closed by denelon** 2021-05-07 14:13 UTC
Labels: Issue-Feature, Needs-Triage
