### ISSUE TITLE
Microsoft.VC++2008Redist-x86/x64 Cannot Upgrade

### ISSUE THREAD

**Issue by zakariajo** [microsoft/winget-cli#1823] opened 2021-12-28 14:04 UTC
### Brief description of your issue

Inability to upgrade Microsoft Visual C++ 2008 Redistributable x86 and x64

ID: Microsoft.VC++2008Redist-x86 Version : 9.0.30729.4148 
ID: Microsoft.VC++2008Redist-x64
Version : 9.0.30729.4148  
Available : 9.0.30729.6161
Source : winget

### Steps to reproduce

have Microsoft VC++ 2008Redist x86 or x64

- **Run Command** : winget upgrade  

- **Output :** 

C:\Users\pc>winget upgrade
Name                                            Id                           Version        Available      Source

Microsoft Visual C++ 2008 Redistributable - x86 Microsoft.VC++2008Redist-x86 9.0.30729.4148 9.0.30729.6161 winget
Microsoft Visual C++ 2008 Redistributable - x64 Microsoft.VC++2008Redist-x64 9.0.30729.4148 9.0.30729.6161 winget
2 upgrades available.

- **Run command** : winget upgrade --all

- **Output** : 

C:\Users\pc>winget upgrade --all
No applicable update found.

same problem using ID 

### Expected behavior

Specific ID is shown and allows upgrade. 

### Actual behavior

Endless loop of finding the package.

### Environment

```shell
Windows Package Manager (Preview) v1.2.3411-preview
Windows: Windows.Desktop v10.0.19044.1415
Package: Microsoft.DesktopAppInstaller v1.17.3411.0
```

**Comment by denelon** [comment] 2021-12-28 18:08
Duplicate of #1413

**Closed by denelon** 2021-12-28 18:09 UTC
Labels: Needs-Triage
