### ISSUE TITLE
Wrong + duplicate detected upgrades

### ISSUE THREAD

**Issue by igorskyflyer** [microsoft/winget-cli#3289] opened 2023-05-30 20:56 UTC
### Brief description of your issue

I have both `Microsoft Visual C++ 2015-2019 (x86)` and `Microsoft Visual C++ 2015-2022 (x64)` redistributables installed on my system. WinGet detects upgrades for both of them but the issue is that it identifies them both as `Microsoft.VCRedist.2015+.x64`, while one of them is for x86, see image.

<div align="center">
	<img src="https://github.com/microsoft/winget-cli/assets/20957750/6c0938b8-d2ae-4bc8-b94e-0b26ee122ad3" alt="WinGet, CLI, redistributable, c#">
	<p>Checking for upgrades</p>
	<br>
	<img src="https://github.com/microsoft/winget-cli/assets/20957750/cdb96a3d-3f8f-4dd9-9811-96d0300c0364" alt="WinGet, CLI, redistributable, c#">
	<p>After (successful) install</p>
</div>

Also, this is related to one of my previous issues (#3248), the redistributable at the latter image `x86` (still) never actually upgrdes.

### Steps to reproduce

1. Try to upgrade `Microsoft Visual C++ 2015-2019 (x86)` and `Microsoft Visual C++ 2015-2022 (x64)`

### Expected behavior

Both redistributables should be detected separately and upgraded successfully.

### Actual behavior

Both versions are detected as x64.

### Environment

```shell
Windows: Windows.Desktop v10.0.19045.3031
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0
```

**Comment by pleabargain** [comment] 2023-05-31 08:17
same
![image](https://github.com/microsoft/winget-cli/assets/640846/fb872798-709c-48da-82c4-5bc656ab6a3b)

**Comment by denelon** [comment] 2023-05-31 15:35
Duplicate of #2893

**Closed** 2023-05-31 15:35 UTC
Labels: Area-Matching
