### ISSUE TITLE
WhatsApp unable to install as it cannot write to C:\ProgramData

### ISSUE THREAD

**Issue by TheRndCoder** [microsoft/winget-cli#269] opened 2020-05-21 11:22 UTC
# Brief description of your issue
When trying to install WhatsApp from the winget command, it is able to download the executable but then it fails with the following error message:

![image](https://user-images.githubusercontent.com/25141697/82554116-8de4d900-9b22-11ea-9cab-3ca73b2acadb.png)

At the same time you'll run into this error message on command line:

```
An unexpected error occurred while executing the command:
remove: Access is denied.: "C:\Users\<User>\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\TempState\WinGet\WhatsApp.WhatsApp.2.2019.8.exe"
```

# Steps to reproduce

Open Windows Terminal, then run command 'winget install whatsapp', the app will download but fail to install

# Expected behavior

WhatsApp should download properly and install

# Actual behavior

The app is able to download, hash is properly verified but fails to install in Windows

# Environment

```none
[winget --info]
Windows Package Manager v0.1.41331 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19041.264
Package: Microsoft.DesktopAppInstaller v1.0.41331.0

Any other software?
Not applicable
```

**Comment by jedieaston** [comment] 2020-05-21 20:13
Do you have admin rights on the system you are testing on?

**Comment by TheRndCoder** [comment] 2020-05-21 20:21
@jedieaston I do, in fact if I try to run winget as administrator and try to install WhatsApp that way, the app refuses to install anyway

**Comment by dmex** [comment] 2020-05-22 18:29
This is the same issue as #254 

Remove the low integrity level from the installer and it'll successfully install: 
`icacls WhatsApp.WhatsApp.2.2019.8.exe /setintegritylevel M`

**Comment by zachcarp** [comment] 2020-05-28 16:49
Duplicate of #254

**Comment by zachcarp** [comment] 2020-05-28 16:50
@dmex Thanks for tracking down the duplicate.

**Closed by zachcarp** 2020-05-28 16:49 UTC
Labels: Needs-Triage
