### ISSUE TITLE
Python always gets upgraded, even when new and old versions are installed side-by-side

### ISSUE THREAD

**Issue by SamuelMarks** [microsoft/winget-cli#3541] opened 2023-08-20 16:47 UTC
### Brief description of your issue

One can install side-by-side, e.g., from https://github.com/adang1345/PythonWindows or even python.org

### Steps to reproduce

0. Install multiple versions, e.g., 3.6,3.7,3.8,3.9,3.10,3.11
1. Run `winget update --all --include-unknown`

### Expected behavior

It shouldn't upgrade if the latest versions already exists

### Actual behavior

It removes my older versions

### Environment

```shell
Windows Package Manager v1.5.2201
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2134
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.2201.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by Trenly** [comment] 2023-08-21 11:44
* Duplicate of #1392 
* Related to #2129

**Closed** 2023-08-21 11:44 UTC
Labels: Needs-Triage
