### ISSUE TITLE
Windows Package Manager Server runs on high CPU

### ISSUE THREAD

**Issue by MarvinNorway** [microsoft/winget-cli#3667] opened 2023-09-25 01:13 UTC
### Brief description of your issue

I'm not sure if this is the right place to report this, but the "WinGET COM Server" with a child process of "WindowsPackageManagerServer.exe" is using up a lot of CPU on my system.
When killed, it just respawns immediately.

I'm not the only one with this issue:
https://www.reddit.com/r/techsupport/comments/162dj42/what_is_winget_com_server/

### Steps to reproduce

Not sure how to reproduce.

### Expected behavior

It shouldn't run on high CPU for extended periods of time.

### Actual behavior

It runs on super high CPU all the time.

### Environment

```shell
Microsoft.DesktopAppInstaller_1.20.2201.0_x64__8wekyb3d8bbwe
WindowsPackageManagerServer.exe version 1.20.2308.8001-v1.20WPMv1.5

Hope that helps...
```

**Comment by sba923** [comment] 2023-09-25 07:45
Same here. The process keeps running after I close its parent (a `pwsh.exe` instance). I can't copy the log from `%LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir` 'cos it's locked.

**Comment by MozPri** [comment] 2023-09-28 07:49
Same here. WindowsPackageManagerServer.exe is using 25% of the CPU and can't be killed.
Microsoft.DesktopAppInstaller_1.21.2701.0

**Comment by PartedLine** [comment] 2023-09-28 18:56
Same here, rather not have my OS frying my CPU

**Comment by saggitar** [comment] 2023-09-28 19:09
Same here ...

**Comment by HyP3r-** [comment] 2023-09-29 10:24
It is the same with me... when I end the process it is restarted immediately.

**Comment by MarvinNorway** [comment] 2023-09-29 10:26
Not sure if it helps anyone, but I left it running over night, and then it was quite the next day.
It happened one more time 1-2 days later, during the day, but I went out for a bit, and when I came back, it was over, as well.
Since then, it has been quiet. Would still be nice to know what the process does and if there's a way to stop this behavior...

**Comment by chylex** [comment] 2023-09-30 15:10
Mine has started crashing constantly, trying to stop it just restarts it and crashes again... how do I get rid of this???

![obrazek](https://github.com/microsoft/winget-cli/assets/3685160/09c11de2-534c-441d-ae8f-897dc6917d5c)

**Comment by gibbed** [comment] 2023-09-30 15:14
> Mine has started crashing constantly, trying to stop it just restarts it and crashes again... how do I get rid of this???
> 
> ![obrazek](https://user-images.githubusercontent.com/3685160/271780720-09c11de2-534c-441d-ae8f-897dc6917d5c.png)

Had this same issue. You've got a pretty outdated version, update "App Installer" via the MS store or WinGet and the problem should go away.

**Comment by chylex** [comment] 2023-09-30 15:20
I have taken ownership of the file, disabled inheritance of permissions, and left the permissions like this:

![obrazek](https://github.com/microsoft/winget-cli/assets/3685160/01bbbfd8-c315-4180-bf2b-4e4356e8a42b)

Permissions on my user are Read and Write, but not Read & Execute:

![obrazek](https://github.com/microsoft/winget-cli/assets/3685160/0dd67fe3-d86e-413c-8ac9-4bc60eaa228c)

Now the exe is no longer able to launch or restart itself, and I'm not getting spammed with errors anymore.

**Comment by MagicAndre1981** [comment] 2023-09-30 20:38
Install the **Windows Performance Toolkit** from the [Windows ADK](https://go.microsoft.com/fwlink/?linkid=2243390) (unselect all other entries) and capture a ETW trace by running `WPRUI.exe`, select `First Level Triage` and `CPU Usage` and click on `Start`. Capture 30-60s of the CPU usage, click `Save` to save the ETL (make sure you select the checkbox "`Compress`" to make the ETL file smaller). 

Zip the ETL + PDB Folder(s) and share the zip via OneDrive link here.

**Comment by nimairsh** [comment] 2023-10-01 14:40
mine is using 10-15%. Here's the [link](https://1drv.ms/u/s!AnBi6n6OaWhoiXxvaLN806t4N9D-?e=4JSmOP) to my etl+pdb if it helps.

**Comment by MagicAndre1981** [comment] 2023-10-01 16:24
> mine is using 10-15%. 

[CPU Usage (Sampled)](https://learn.microsoft.com/en-us/windows-hardware/test/wpt/cpu-analysis#cpu-usage-sampled-graph) is somehow missing, precise stack shows usage of WindowsPackageManager.dll, but the PDB is missing, so a team member which has access to the PDB should take a look at it.

**Comment by eduarddejong** [comment] 2023-10-01 20:48
I can report a high CPU issue as well. It was running for a really long time at high 100%, while I am running a pretty modern desktop system.

However after a lot of minutes, it eventually stopped and went quiet, without any intervention by me (I deliberately decided to wait a log time to see if it would eventually stop indeed).

This gives me the impression that the process does not truely hang an infinate loop, but that it's performing some task just really, really inefficiently (is it doing some kind of super heavy search, like through the entire registry or something?).
And if that's something on a scheduled base, it might come back again (no idea yet) on other moments, impacting performance at unexpected moments on the user's system.

**Comment by denelon** [comment] 2023-10-01 22:37
We believe we've identified the source of the high CPU events. We're looking to make changes in WinGet to lower the impact as well as working with partner teams to help make their calls and calling pattern more efficient.

**Comment by ViPeR5000** [comment] 2023-10-02 12:28
Same here  :(

**Comment by ondalin** [comment] 2023-10-03 22:32
hello all

i just noticed this program today, also taking much cpu, after i removed some office updates from yesterday, it went away; will keep an eye on task manager, but since removing the updates and a reboot and while creating the account here and typing, the program didnt came back so far.

**Comment by ondalin** [comment] 2023-10-04 00:29
update, it came back. damn

**Comment by mediser** [comment] 2023-10-04 02:02
hello there, I have the same problem, could anyone solve it??

**Comment by mediser** [comment] 2023-10-04 02:38
> hello there, I have the same problem, could anyone solve it??

The last time I had this problem, what I did was restart Windows and after that it worked fine, at least until now...

**Comment by ktrance** [comment] 2023-10-04 06:25
> We believe we've identified the source of the high CPU events. We're looking to make changes in WinGet to lower the impact as well as working with partner teams to help make their calls and calling pattern more efficient.

Ok, you have an ETA on a fix for this? And please, not one that "lowers the impact", but one that fixes the issue.

**Comment by chvogel** [comment] 2023-10-04 07:53
Same issue here. Started pretty much right after booting up, on a machine that I haven't used since last Friday.

Process has accumulated about 10min of CPU time (100% usage on a single core) and as I am writing this, it has now finally stopped.


I know this is like talking to a wall, but the amount of "random" background processes with zero UI indication of what is happening has really gotten out of hand in recent years. The more stuff constantly running on the background, the bigger the potential of things going wrong or eating up CPU time for no apparent reason.

Yes, user experience (in terms application performance) is not affected too much since most code still runs single-threaded and modern computers are routinely equipped with more than half a dozen cores. But especially on mobile/laptop devices, this causes a large nuisance due to high noise (for no visible reason), causing distraction and reduced battery life.

**Comment by ondalin** [comment] 2023-10-05 00:29
what else seems to have dialed this down was to right click  the sub process in task manager, go to details, right click again, set priority, below normal, reboot and when it came back, it didnt take as much cpu as before.

**Comment by drankinatty** [comment] 2023-10-05 06:56
This problem hit today on a box that was just started and had not been up since last week. Seems like an update is to blame. `WindowsPackageManagerServer.exe` has been running for hours cycling between 5 and 25 percent CPU relentlessly:

![windowspackagemanagerserver-cpu](https://github.com/microsoft/winget-cli/assets/9997638/642aca43-68a0-4824-93c2-7ef74621783b)

The problem appears to be its continual connection with akami and an IP at `13.107.213.57`, see, e.g.

![windowspackagemanagerserver-network](https://github.com/microsoft/winget-cli/assets/9997638/c5867874-1055-466e-841c-cd9482634196)

Edge and MS Office 365 were two of the updates I saw come by. This needs to be fixed.

**Comment by joedf** [comment] 2023-10-07 15:28
This is very bad behaviour. Background update processes should never be this disruptive... This is bad oversight...

**Comment by Pootleris** [comment] 2023-10-08 15:18
same porcodio

**Comment by rerigam** [comment] 2023-10-09 09:27
How to uninstall the modern App WinGET: open PowerShell as admin and enter the following command:
get-appxpackage *Microsoft.DesktopAppInstaller* | remove-appxpackage

**Comment by moritzluedtke** [comment] 2023-10-13 11:13
> PS: i don't know why but the editor removed 2 asterisks from the command above, one before Microsoft and one after AppInstaller. You must insert them.

They disappear because these text windows accept markdown. So the asterix is interpreted as making the text between them bold. To avoid this, just put code statement into backticks.

So a statement like this `something.Method()` can be achieved by typing in `` `something.Method()` ``.

**Comment by Girofox** [comment] 2023-10-17 21:22
Possible steps to reproduce:
`control panel - system and security - security and maintenance, under maintenance trigger automatic maintenance`

**Comment by bdgit** [comment] 2023-10-19 10:45
This morning I came across this while updating Visual Studio 2022 from 17.7.4 to 17.7.5.
- I had just booted up.
- Launched Visual Studio Installer and started the update for 2022.
- While update was running, launched File Explorer to perform a little file organization.

While naming folders or files (via create new folder, rename folder, rename file, etc.), **File Explorer kept losing focus**.  A bit random, but mostly too quick for me to lock in the naming.

Eventually discovered it could WinGet COM Server (WindowsPackageManagerServer.exe) as the CPU is getting pinned by it.

**Comment by SanderBouwhuis** [comment] 2023-10-26 06:17
I also updated Visual Studio 2022 from v17.7.4 to v17.7.5 yesterday and I'm also encountering this problem.
MICROSOFT, WHERE ARE YOU? PLEASE SOLVE THIS CLEAR PROBLEM.

**Comment by raphaelcardoso** [comment] 2023-10-30 02:22
I updated Visual Studio 2022 from v17.7.4 to v17.7.6 two days ago and have since encountered the following symptoms:

- High CPU consumption by the WindowsPackageManagerServer.exe process.
- When I terminate the WindowsPackageManagerServer.exe process, it immediately restarts.
- I'm not sure how to access the debug symbols for this binary, so I see many function addresses in the call stack and few names. However, this one is related to 99% of the activity:
  - WindowsPackageManagerConfigurationCompleteOutOfProcessFactoryInitialization (WindowsPackageManager.dll)
- Here are some files that have exhibited high disk activity for approximately 40 minutes:
  - Log
    - %LocalAppData%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGetCOM-2023-10-27-07-28-54.727.log
  - SQlite
    - %LocalAppData%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\pinning.db
    - %LocalAppData%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\StoreEdgeFD\installed.db
    - %LocalAppData%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Microsoft.Winget.Source_8wekyb3d8bbwe\installed.db
- File details:
  - WindowsPackageManagerServer.exe
  - File version: 1.21.2309.29001
  - Product version: 1.21.230929001-v1.21WPMv1.6

**Comment by Girofox** [comment] 2023-10-30 07:23
Isn't DesktopAppInstaller just the App for winget.exe? So removing it does keep Winget or not?

**Comment by Girofox** [comment] 2023-10-30 10:54
By the way this is my folder of the Logfiles, insane how many the WinGetCOM was triggered the last days. I was wondering why my cpu temp was higher than usual. According to the logfiles a taskhostfw.exe triggers that, so a task in Task Scheduler must be the trigger but don't know which task.
![image](https://github.com/microsoft/winget-cli/assets/43116061/57ed6fa4-e8e7-40e4-b203-5fbbaa34f5c6)

**Comment by Girofox** [comment] 2023-10-30 11:01
This is an excerpt from one of the log, it looks like winget is constantly scanning for applications and is writing into installed.db database.
![image](https://github.com/microsoft/winget-cli/assets/43116061/e15e30ce-1969-4a5f-bc09-09ce654dee5f)

**Comment by raphaelcardoso** [comment] 2023-10-30 13:25
The high resource consumption issue is likely related to the recent Visual Studio update. Considering the behavior and the timing, it might be due to a bug in the Windows Package Manager component responsible for package inventory, causing it to go into a loop when encountering a particular character in an attribute that can't parse correctly. The Visual Studio Installer may have installed the unusual package.
My temporary solution has been to suspend the process.

**Comment by Girofox** [comment] 2023-10-30 14:23
After renaming the folder `%LocalAppData%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe` with suffix "_bak" the command `winget update` rebuild the whole folder and so far no more high cpu usage is occuring. It seems there may be a problem with the various database files inside that folder. Looked into them with DB Browser for SQLite and there were entries with already removed programs.

**Comment by sba923** [comment] 2023-10-30 14:25
> ### Possible workaround:
> After renaming the folder `%LocalAppData%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe` with suffix "_bak" the command `winget update` rebuild the whole folder and so far no more high cpu usage is occuring.
> 
> It seems there may be a problem with the various database files inside that folder. Looked into them with DB Browser for SQLite and there were entries with already removed programs.

Interesting.

Thanks for sharing.

**Comment by Girofox** [comment] 2023-10-30 14:37
Hopefully this stays after VS Studio updates. I will look into `%LocalAppData%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbw\LocalState\DiagOutputDir` regularly now and check if there occur many logs in a single a day. Of course this is just a relatively dirty workaround and not a complete fix but deleting a folder from `AppData\Local\Packages` is not really dangerous because the folders get recreated anyway. Renaming is definitely a safe way.

**Comment by raphaelcardoso** [comment] 2023-10-30 22:05
If you find it useful, I can provide copies of the databases or any other files you might need. Just let me know how to share the files.

**Comment by ktrance** [comment] 2023-10-31 07:44
@denelon Its now about a month since you wrote that you believe you found the problem. Could you please tells us when can we expect a fix for this?

Everyday I have to sit next to a machine with the fan going crazy, its like getting tinnitus.

**Comment by MozPri** [comment] 2023-10-31 08:04
@ktrance Take ownership of WindowsPackageManagerServer.exe file and then rename or delete it.

**Comment by ktrance** [comment] 2023-10-31 08:09
> @ktrance Take ownership of WindowsPackageManagerServer.exe file and then rename or delete it.

No, I want fix, not a hack

**Comment by drankinatty** [comment] 2023-10-31 08:49
Agreed. Effectively deleting the file on individual machine for those users just smart enough to know how to take ownership of a system file and renaming it is not a solution. It leaves every other windows user stuck with the problem. Good lord. Think of the 99.9+% of the installed base that has no clue about hacking file permissions. Think of your grandmother or grandfather or child puzzled, concerned there computer is broken because it is busy for hours on end.

**Comment by juniortarcisio** [comment] 2023-11-02 03:09
While there's no patch/solution, another option is simply "suspend" the process using windows resource monitor, instead of killing it.

**Comment by denelon** [comment] 2023-11-02 20:16
Hey all. We've identified an area where we can reduce the CPU utilization for this calling pattern. We're working on an update, and we'll publish it as soon as it's ready.

**Comment by Girofox** [comment] 2023-11-03 11:59
Ok, this is weird, I found another possible trigger:

- Open "Windows Backup" app, then manually start process by clicking "Back Up".

In my case the logfile in `AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir` topped out at 1.5 Mb when the process eventually terminated.

![image](https://github.com/microsoft/winget-cli/assets/43116061/d2161ae2-027f-465c-a799-a0e0783d976a)

**Comment by son0nline** [comment] 2023-11-03 17:41
WindowsPackageManagerServer.exe always uses above 10% cpu and can't be killed.

![image](https://github.com/microsoft/winget-cli/assets/8395344/890f1369-98ce-48c8-8c6a-c5e096c9bf9b)

**Comment by denelon** [comment] 2023-11-03 18:00
Hey all, we've identified a couple of areas where we're able to make substantial improvements in the client. Our initial testing is showing a solid reduction in the time it takes for these processes to complete. It amounts to 5/6 of the time. Something on the order of ~1000 ms per iteration to ~130 ms per iteration on the hardware we're testing on. I'm expecting we will push this update out early next week if the remaining testing all passes.

**Comment by sba923** [comment] 2023-11-03 18:38
> Hey all, we've identified a couple of areas where we're able to make substantial improvements in the client. Our initial testing is showing a solid reduction in the time it takes for these processes to complete. It amounts to 5/6 of the time. Something on the order of ~1000 ms per iteration to ~130 ms per iteration on the hardware we're testing on. I'm expecting we will push this update out early next week if the remaining testing all passes.

Good job! Do you have an explanation for the fact it doesn't affect most machines? What is (are) the trigger(s) for that CPU consumption?

**Comment by MagicAndre1981** [comment] 2023-11-03 18:44
> Good job! Do you have an explanation for the fact it doesn't affect most machines? What is (are) the trigger(s) for that CPU consumption?

this is what I also would like to know. I run winget daily and never saw such a high CPU usage. I run it from classic cmd.exe on x64 Windows 10/11 German.

**Comment by raphaelcardoso** [comment] 2023-11-03 18:58
> Hey all, we've identified a couple of areas where we're able to make substantial improvements in the client. Our initial testing is showing a solid reduction in the time it takes for these processes to complete. It amounts to 5/6 of the time. Something on the order of ~1000 ms per iteration to ~130 ms per iteration on the hardware we're testing on. I'm expecting we will push this update out early next week if the remaining testing all passes.

I appreciate the optimization effort, and the initial results look promising.
However, based on the observed behavior, even with a 99.9% load reduction, it will still be an unacceptable load.
I suspect there may still be an underlying bug contributing to this.
Is there any connection between the Visual Studio update and the issue we're observing, or is it just a coincidence?

**Comment by SanderBouwhuis** [comment] 2023-11-03 19:19
Like @raphaelcardoso I'm sceptical. For me, the process hung for at least 30 minutes before I managed to finally kill it by uninstalling some things. Endless loop * 1/6 is still an endless loop.

**Comment by raphaelcardoso** [comment] 2023-11-04 00:14
### [OFF-TOPIC]
Shifting the focus here, in situations like this where it's causing a single logical processor to run at 100% capacity (25% of my CPU), there should be a fast, automated rollback process.

It might be achievable using components already implemented in advanced technologies like Click-to-Run, containers, MDM, or the Microsoft Store.

In an emergency, authors of Microsoft Store apps should be able to revert to a previous version almost instantaneously, triggering a deployment as lightweight as sending low-priority push notifications and symlink swapping.

**Comment by jyoberle** [comment] 2023-11-04 20:42
> How to remove the modern App WinGET: open PowerShell as admin and enter the following command: "get-appxpackage **Microsoft.DesktopAppInstaller** | remove-appxpackage"
> 
> PS: i don't know why but the editor removed 2 asterisks from the command above, one before Microsoft and one after AppInstaller. You must insert them.

I tried this command and after a few minutes I had no more Internet! I had to reinstall Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle (downloaded thanks to my phone) to get Internet back

**Comment by MagicAndre1981** [comment] 2023-11-08 07:01
ok, Microsoft made some changes in #3808 to improve it my caching RegEx calls. I also got this cpu usage now but only for a shorter time after running winget upgrade and here I saw icu regex calls. So hopefully we get this fix sone in an update.

**Comment by Girofox** [comment] 2023-11-08 11:13
For me WindowsPackageManagerServer.exe runs 10 minutes on my laptop with around 25 % cpu usage when i manually trigger backup in `Windows Backup` app, `winget upgrade` never was an issue in my case.

![image](https://github.com/microsoft/winget-cli/assets/43116061/12f18f84-8c6b-4028-8008-f1c1b82cd2a7)

**Comment by SanderBouwhuis** [comment] 2023-11-08 21:13
> > How to remove the modern App WinGET: open PowerShell as admin and enter the following command: "get-appxpackage **Microsoft.DesktopAppInstaller** | remove-appxpackage"
> > PS: i don't know why but the editor removed 2 asterisks from the command above, one before Microsoft and one after AppInstaller. You must insert them.
> 
> I tried this command and after a few minutes I had no more Internet! I had to reinstall Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle (downloaded thanks to my phone) to get Internet back

I didn't encounter this problem after uninstalling this package.
Did you try to restart?

**Comment by jyoberle** [comment] 2023-11-08 21:42
No, I didn't try a restart.

**Comment by anonymous-explorer** [comment] 2023-11-10 10:59
Windows 10 Pro.
Windows Package Manager uses one logical CPU (I have 2 cores, 4 logical CPUs and it uses 25% of the total CPU). It does not use any Disk I/O and almost no network.
I always log in with non-admin user.

Restarting Windows and logging in with Administrator account solves the problem. Some process (Wsappx ...) runs for less than a minute with a high CPU usage and then CPU usage returns to normal.

After restarting with normal user "Please wait" appears (some update are being installed?) and runs fine until the next Windows update.

**Comment by Girofox** [comment] 2023-11-10 12:38
Ok, that sounds very interesting, seems like something inside Windows "fixes" itself running with admin account.

Do you mean a normal admin account or the "true" admin account of Windows by running `Net user Administrator /active: yes` in command line? Because my regular user account already has admin rights but user account control gets triggered.

What happens when you open `Windows Backup` app and manually start backup there? Does that trigger the 25 percent cpu usage process?

**Comment by denelon** [comment] 2023-11-10 17:52
Hey all, we've almost completed our internal testing.

We will publish the update here at GitHub (for people actively seeking the update) and to Windows Insider Beta and Windows Insider Release Preview. After a few days of feedback, this will be pushed out to everyone.

**Comment by denelon** [comment] 2023-11-11 00:38
https://github.com/microsoft/winget-cli/releases/tag/v1.6.3133

**Comment by Girofox** [comment] 2023-11-11 15:41
This looks promising, downgraded from pre-release version to `v1.6.3133` and I can confirm the issue seems gone!

CPU usage of _WindowsPackageManagerServer.exe_ now stays below 10 % and finishes in less than 2 minutes. I used SystemInformer for that graph, Process Explorer should work too.

Downgrading was a bit complicated and commands `winget list` and `winget upgrade` only worked after deleting the .db file in `%LocalAppData%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Microsoft.Winget.Source_8wekyb3d8bbwe`, this database seems to store which packages you recently installed via winget.

![image](https://github.com/microsoft/winget-cli/assets/43116061/862b596f-67b5-4b7f-a367-5b7383376324)

**Comment by sba923** [comment] 2023-11-11 17:09
> Hey all, we've almost completed our internal testing.
> 
> We will publish the update here at GitHub (for people actively seeking the update) and to Windows Insider Beta and Windows Insider Release Preview. After a few days of feedback, this will be pushed out to everyone.

Terrific.

Would you mind sharing the exact PR / commits for curious minds who want to understand what was going on? 😜

**Comment by sba923** [comment] 2023-11-11 17:21
> Hey all, we've almost completed our internal testing.
> 
> We will publish the update here at GitHub (for people actively seeking the update) and to Windows Insider Beta and Windows Insider Release Preview. After a few days of feedback, this will be pushed out to everyone.

@denelon  Would you mind sharing the exact PR / commits for curious minds who want to understand what was going on? 😜

**Comment by MagicAndre1981** [comment] 2023-11-11 19:16
> Would you mind sharing the exact PR / commits for curious minds who want to understand what was going on? 😜

https://github.com/microsoft/winget-cli/commit/296a53dbedffabfd14b60f43e1a7abae0200cb75

**Comment by drankinatty** [comment] 2023-11-11 20:11
Thank you for the link to the note on Performance Improvements related to caching. However, the note does not explain all of the network communications to akami that are associated with the package manager issue. I looked again last night in Resource Explorer while this issue was taking place, and while low in bandwidth, there was continual transmission to/from the microsoft akami servers. Windows already knows what updates have been downloaded and what updates are needed, and the updating has all been done before this package manager behavior kicks in. So what is this stream of network traffic with akami that your caching is indented to benefit?

Adding that information to the [296a53d](https://github.com/microsoft/winget-cli/commit/296a53dbedffabfd14b60f43e1a7abae0200cb75) link would be very helpful.

**Comment by denelon** [comment] 2023-11-13 16:05
We will be working on getting a 1.7-preview version with the improved performance changes out next.

**Closed** 2024-06-11 23:08 UTC
Labels: Issue-Bug, Area-Performance
