### ISSUE TITLE
RDCMan is installed with broken file permissions

### ISSUE THREAD

**Issue by lazynooblet** [microsoft/winget-cli#3220] opened 2023-05-04 15:49 UTC
### Brief description of your issue

When installing at machine scope, the file is installed at `"C:\Program Files\WinGet\Packages\Microsoft.Sysinternals.RDCMan_Microsoft.Winget.Source_8wekyb3d8bbwe\RDCMan.exe"`, which has inheritance enabled, **but** the inheritance is broken, as only SYSTEM & CurrentUser have propogated to the file.

When installing via Intune, which runs as SYSTEM, you end up with only SYSTEM having access to the file.

Looking at the parent folder, `"C:\Program Files\WinGet\Packages\Microsoft.Sysinternals.RDCMan_Microsoft.Winget.Source_8wekyb3d8bbwe\"`, there are multiple permissions

```
> Get-Acl "C:\Program Files\WinGet\Packages\Microsoft.Sysinternals.RDCMan_Microsoft.Winget.Source_8wekyb3d8bbwe" | Select -ExpandProperty Access | Select -Unique IdentityReference
IdentityReference
-----------------
NT SERVICE\TrustedInstaller
NT AUTHORITY\SYSTEM
BUILTIN\Administrators
BUILTIN\Users
CREATOR OWNER
APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES
APPLICATION PACKAGE AUTHORITY\ALL RESTRICTED APP PACKAGES
```

Permission inheritance is enabled, but the file only receives

```
> Get-Acl "C:\Program Files\WinGet\Packages\Microsoft.Sysinternals.RDCMan_Microsoft.Winget.Source_8wekyb3d8bbwe\RDCMan.exe" | Select -ExpandProperty Access | Select -Unique IdentityReference

IdentityReference
-----------------
NT AUTHORITY\SYSTEM
```

I'm thinking this is a symptom if the file being downloaded in one location and then moved to another.

### Steps to reproduce

```
> winget install Microsoft.Sysinternals.RDCMan --scope=machine
> Get-Acl "C:\Program Files\WinGet\Packages\Microsoft.Sysinternals.RDCMan_Microsoft.Winget.Source_8wekyb3d8bbwe\RDCMan.exe" | Select -ExpandProperty Access

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : DOMAIN\CurrentUser
IsInherited       : True
InheritanceFlags  : None
PropagationFlags  : None

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : NT AUTHORITY\SYSTEM
IsInherited       : True
InheritanceFlags  : None
PropagationFlags  : None
```

### Expected behavior

The downloaded file is accessible by all users "READ AND EXECUTE"

### Actual behavior

The downloaded file is only accessible by SYSTEM + CurrentUser

### Environment

```shell
> winget --info
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1555
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0
```

**Comment by denelon** [comment] 2023-05-04 22:29
Duplicate of #3210 

* #3210

**Closed by denelon** 2023-05-04 22:29 UTC
Labels: Needs-Triage

**Comment by lazynooblet** [comment] 2023-05-04 22:36
That's actually a different issue entirely, but no worries 😃
