### ISSUE TITLE
How to update/upgrade the installed packages as a batch job?

### ISSUE THREAD

**Issue by qiyuqi** [microsoft/winget-cli#590] opened 2020-10-02 16:59 UTC
# Description of the new feature/enhancement
1. As a package manager, `winget` should have the function of package version management, which could
  - list the outdated packages which had installed in the local system and registed in the package-repository with `update`;
  - upgrade the specific or all outdated package as a batch job on the background with `upgrade [package-name]`.

# Proposed technical implementation details (optional)

**Comment by OfficialEsco** [comment] 2020-10-02 23:00
Its already planed and in the Roadmap. https://github.com/microsoft/winget-cli/blob/master/doc/windows-package-manager-v1-roadmap.md

**Comment by Suirtimed** [comment] 2020-10-05 15:54
https://github.com/microsoft/winget-cli/issues/119 "List" is in progress. https://github.com/microsoft/winget-cli/issues/120 "Upgrade" will follow next. https://github.com/microsoft/winget-cli/issues/212 auto-update is in the backlog. We haven't determined how best to handle making sure we do the right thing in terms of auto-update. Some people want to have everything auto-updated "all the time". Some packages need to be "pinned" https://github.com/microsoft/winget-cli/issues/476 so they don't update until the user explicitly does so. Some users don't want auto-update at all.

**Comment by Suirtimed** [comment] 2020-10-05 15:55
Duplicate of #119

**Comment by denelon** [comment] 2020-10-05 15:57
Duplicate of #119

**Closed by denelon** 2020-10-05 15:57 UTC
Labels: Issue-Feature, Needs-Triage
