### ISSUE TITLE
Latest source (2020.630) is blocked by SmartScreen

### ISSUE THREAD

**Issue by huoyaoyuan** [microsoft/winget-cli#475] opened 2020-07-01 07:18 UTC
# Brief description of your issue

I was able to use winget yesterday night (UTC+8, the source version should be 2020.629 then).
Today, when I try to use `winget search` or `winget source update`, the operation will fail with 0x80073d1b: SmartScreen reputation check failed.

# Environment

```none
[winget --info]
Windows Package Manager v0.1.41331 preview
Windows: Windows.Desktop v10.0.18363.900
Package: Microsoft.DesktopAppInstaller v1.0.41331.0

The blocked source package version: Microsoft.Winget.Source_2020.630.2349.618_neutral__8wekyb3d8bbwe.msix

Windows Defender version:
Anti-malware client 4.18.2005.5
Engine 1.1.17200.2
Anti-virus 1.319.551.0
Anti-spy 1.319.551.0
Updated at 2020/7/1 13:47 UTC+8
```

**Comment by KevinLaMS** [comment] 2020-07-01 16:46
@huoyaoyuan Thanks for the report.  I have not been able to reproduce this locally.  I am reaching out to the SmartScreen team to understand why you may have a different experience.

**Comment by astroshot** [comment] 2020-07-09 12:36
I have this problem, too...

**Comment by denelon** [comment] 2020-07-15 16:04
@huoyaoyuan and @astroshot we updated the client to a new version. Can you confirm this is happening to you on:

Windows Package Manager v0.1.41821 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19604.1000
Package: Microsoft.DesktopAppInstaller v1.0.41821.0

**Comment by huoyaoyuan** [comment] 2020-07-15 16:21
@denelon The issue disappeared immediately at the next day. I guess that the fingerprint of package at 6.30 has accidentally matched some malware, thus blocked by SmartScreen.

**Comment by astroshot** [comment] 2020-07-16 14:38
> 
> 
> @huoyaoyuan and @astroshot we updated the client to a new version. Can you confirm this is happening to you on:
> 
> Windows Package Manager v0.1.41821 Preview
> Copyright (c) Microsoft Corporation. All rights reserved.
> 
> Windows: Windows.Desktop v10.0.19604.1000
> Package: Microsoft.DesktopAppInstaller v1.0.41821.0

```
Loading personal and system profiles took 813ms.
E:\Projects ❯ winget search silver                                                                             22:32:42
Name                Id            Version
-----------------------------------------
The Silver Searcher JFLarvoire.Ag 2.2.3
E:\Projects ❯ winget --version                                                                                 22:33:34
v0.1.41331 Preview
```
@denelon

I did nothing but it seems the issue has gone... 
I guess the reason was that some sever of is down?

**Comment by astroshot** [comment] 2020-07-16 14:41
```
E:\Projects ❯ winget search silver                                                                           ⨯ 22:39:34
Name                Id            Version
-----------------------------------------
The Silver Searcher JFLarvoire.Ag 2.2.3
E:\Projects ❯ winget --version                                                                                 22:39:45
v0.1.41821 Preview
E:\Projects ❯
```

winget updated.

**Comment by denelon** [comment] 2020-07-17 00:40
@huoyaoyuan and @astroshot thanks for responding. I'm going to go ahead and close this issue as it appears to be resolved. If you run into any further trouble like this, feel free to re-open the issue or create a new one.

**Closed by denelon** 2020-07-17 00:40 UTC
Labels: Issue-Bug, Needs-Attention
