### ISSUE TITLE
Add prompt to restart shell or reload the PATH variable

### ISSUE THREAD

**Issue by manishprivet** [microsoft/winget-cli#1085] opened 2021-06-03 04:40 UTC
# Description of the new feature/enhancement

As of right now, upon installing a package, the PATH is not getting updated right away, and it requires us to restart shell in order to try the installed package.
![image](https://user-images.githubusercontent.com/54291836/120587815-b0a70e80-c453-11eb-8dd0-8fc9b245b5e1.png)

# Proposed technical implementation details (optional)

We can add a prompt to restart the shell in order to try the newly installed package, or we can reload the PATH variable on the end of every successful install

**Comment by denelon** [comment] 2021-06-03 23:05
Duplicate of #222

**Closed by denelon** 2021-06-03 23:06 UTC
Labels: Issue-Feature, Needs-Triage
