### ISSUE TITLE
Please add Download Size of packages

### ISSUE THREAD

**Issue by UseYourGadgets1** [microsoft/winget-cli#1542] opened 2021-10-02 05:35 UTC
# Description of the new feature/enhancement
Please add "Download Size" of packages in "winget show <package>" command.

# Proposed technical implementation details (optional)

![Screenshot (32)](https://user-images.githubusercontent.com/86790286/135704966-c30d4c91-aebe-4a5f-9cb9-51805c91689a.png)

**Comment by denelon** [comment] 2021-10-04 15:47
Duplicate of #1070

Related to:
* #1070
* #1130

**Closed by denelon** 2021-10-04 15:47 UTC
Labels: Issue-Feature, Needs-Triage
