### ISSUE TITLE
Winget does nothing on a clean Win11Pro install.

### ISSUE THREAD

**Issue by jasonswearingen** [microsoft/winget-cli#4187] opened 2024-02-21 14:17 UTC
### Brief description of your issue

running winget commands such as `winget install firefox` does nothing.   It shows a blue spinner for a moment and then exits to prompt.

### Steps to reproduce

this occurred yesterday (Feb 2024). I have a new install of Win11 Pro, v23H2 os build 22631.3155. I did a fresh install using internet sources.

winget shows a v1.2.10691

`winget source list` shows:
```
Name    Argument
-----------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
winget  https://winget.azureedge.net/cache
```

The `https://winget.azureedge.net/cache` above seems to be the problem.  This appears to be a known issue.  

- Following some suggestions on solutions, this needs to be changed to `https://cdn.winget.microsoft.com/cache`.  trying to remove the bad source works, but running winget source add -n winget -a https://cdn.winget.microsoft.com/cache fails (no error, just no source added).
- If I try to run winget install "App Installer" -s msstore --force it only finds "LG Monitor App Installer". The one I seem to want has id  Microsoft.AppInstaller but is not on msstore so can't install it.
- There seems to be no obvious way for an end-user to upgrade winget.  It's not listed on the MsStore.

## Workaround

It turns out the above mentioned "App Installer" is still on msstore.  I found a link to it (here https://apps.microsoft.com/detail/9NBLGGH4NNS1) . it's a hidden package so you have to have a link to find it. I used the ID of it found in the URL to install it, and now winget works and I can install stuff properly. Here's the command you can use to install it (the solution):

**`winget install -s msstore --id 9NBLGGH4NNS1`**

with that, I am able to use winget properly.

### Expected behavior

Critical failures in winget:

1. winget should work from a clean install of windows. (it does not)
1. If it does not work, it should provide actionable information explaining to the end user what the problem is. (It does not)
1. When the problem is identified, You should be able to change the source to a valid one. (You can not)
1. When the problem is identified, you should be able to upgrade winget to a new version.  (You can not).

### Actual behavior

running a command specifying source as `msstore` works.   but using winget sources does not, also not explicitly specifying source does not.   For example:  running a command such as  `winget install firefox` turns the prompt blue and nothing else (likely it crashes in the middle of animating a spinner).

Related issues (all closed without actually solving the issue)
- https://github.com/microsoft/winget-cli/issues/1656
- https://github.com/microsoft/winget-cli/issues/3832
- https://github.com/microsoft/winget-cli/issues/3652
- https://github.com/ChrisTitusTech/winutil/issues/1082

### Environment

```shell
- Fresh install of Windows 11 Pro from direct msft internet sources (Feb 2024):  v`23H2` os build `22631.3155`
- winget showed `v1.2.10691`
```

**Comment by Trenly** [comment] 2024-02-21 15:58
@jasonswearingen - You will need to update your version of WinGet since the original CDN which was hardcoded into version 1.2 has been retired.

* https://github.com/microsoft/winget-cli/issues/3652

Duplicate of #4018

**Closed** 2024-02-21 15:58 UTC
Labels: Issue-Bug, Command-Source

**Comment by jasonswearingen** [comment] 2024-02-21 16:54
> @jasonswearingen - You will need to update your version of WinGet since the original CDN which was hardcoded into version 1.2 has been retired. You can download the latest version of WinGet from the GitHub releases page, or update AppInstaller through the Microsoft Store

Yes, I solved my issue (the workaround I mention in the issue).  However your suggestions are inadequate  for most people:

> You can download the latest version of WinGet from the GitHub releases page
- it's unrealistic for end-users to figure out this is required
- There are many `https://github.com/microsoft/winget-*` repositories to pick from
- if you mean https://github.com/microsoft/winget-cli/releases/tag/v1.6.3482 there is no clear instruction on how an end user would upgrade.

> or update AppInstaller through the Microsoft Store
There is no such AppInstaller available on the Microsoft Store.   The package exists but it is hidden (not searchable).  Plus how would a user know to find this if they didn't already know?


My point is that this is terrible user experieince.  This issue was supposed to be fixed 6 months ago, but it's still occurring on fresh installs, and non-power users can not figure out solutions.

**Comment by n-WN** [comment] 2024-04-22 08:57
does not work

```powershell
PS C:\Users> sudo winget source reset
如果指定了--force 选项，则将重置以下源：
名称    参数
-----------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
winget  https://cdn.winget.microsoft.com/cache
PS C:\Users> sudo winget source reset --force
正在重置所有源...完成
PS C:\Users> sudo winget install -s msstore --id 9NBLGGH4NNS1
打开源时失败;如果问题仍然存在，请尝试"source reset"命令。
执行此命令时发生意外错误：
0x8a15005e : The server certificate did not match any of the expected values.
PS C:\Users>
```
