### ISSUE TITLE
winget list Application name is trimmed

### ISSUE THREAD

**Issue by aabuhasna** [microsoft/winget-cli#4454] opened 2024-05-07 14:00 UTC
### Brief description of your issue

When using winget --list it will display ... at the end of package name

Microsoft Visual C++ 2015-2022 Redistributable (x86) … Microsoft.VCRedist.2015+.x86                         XXXXXX       YYYYYY winget

### Steps to reproduce

install and  application with a long name, then execute winget list

### Expected behavior

show full application name

### Actual behavior

Application name is trimmed

### Environment

```shell
winget version: v1.7.11132
Windows Package Manager v1.7.11132
Windows.Desktop v10.0.22621.3447
```

**Comment by denelon** [comment] 2024-05-07 20:00
Duplicate of #2603

* #2603

**Closed** 2024-05-07 20:00 UTC
