### ISSUE TITLE
Upgrade - Fetch current location and reinstall package there

### ISSUE THREAD

**Issue by sin-fx** [microsoft/winget-cli#3446] opened 2023-07-18 02:20 UTC
### Description of the new feature / enhancement

After running winget upgrade, it show that several packages could be upgraded. So I decided to upgrade the Vagrant package by executing the command: **winget upgrade Hashicorp.Vagrant**

The old installation was remove, which was expected and a new one was installed. However, where it was installed surprised me a little bit. It was different from the old location that was manually installed by me.

Since winget allows you to pass arguments to installation on where a package is to be installed. I assumed that by issuing an upgrade command, it would persist the path and install the new package in the same location.

### Proposed technical implementation details

When the upgrade command is executed, it should fetch the location of the current package. The new package being installed should be installed at that location.

**Comment by Trenly** [comment] 2023-07-18 12:03
Duplicate of #3045

**Closed** 2023-07-18 12:03 UTC
Labels: Issue-Feature
