### ISSUE TITLE
Uninstall with version does not work.

### ISSUE THREAD

**Issue by danielniccoli** [microsoft/winget-cli#2529] opened 2022-09-18 14:33 UTC
### Brief description of your issue

Uninstalling a specific version does not work.

### Steps to reproduce

```
PS C:\> winget list element

Name    Id              Version Available Source
------------------------------------------------
Element Element.Element 1.11.5            winget
Element Element.Element 1.10.1  1.11.5    winget

PS C:\> winget uninstall Element --version 1.10.1

Multiple installed packages found matching input criteria. Please refine the input.
Name    Id
-----------------------
Element Element.Element
Element Element.Element
```

### Expected behavior

Should uninstall app with specific version.

### Actual behavior

Error `Multiple installed packages found matching input criteria. Please refine the input.` despite providing uniquely identifiable query parameters.

### Environment

```shell
Windows Package Manager (Preview) v1.4.2161-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.978
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.2161.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links               
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```
```

**Comment by Trenly** [comment] 2022-09-18 16:51
Duplicate of #1886

**Closed by Trenly** 2022-09-18 16:51 UTC
Labels: Needs-Triage

**Comment by danielniccoli** [comment] 2022-09-18 17:26
@Trenly the bug you mentioned has different behaviour, than the bug I filed. It is not a duplicate. Please compare the actual behaviour of both issues.

**Comment by Trenly** [comment] 2022-09-18 17:51
@danielniccoli - It is the same root issue that the `--version` switch does not work.  Regarding the "specific behavior" it could also be considered the same as #2509 if you're looking specifically at the fact that it can't refine the input.

Even if you weren't experiencing the issue where the input can't be refined, there would still be the root cause that the version switch doesn't currently work with uninstall.

**Comment by danielniccoli** [comment] 2022-09-18 18:38
I'm glad you could identify the root cause.
