### ISSUE TITLE
Feature request: placeholders in version numbers

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/winget-cli#636] opened 2020-11-05 10:37 UTC
# Description of the new feature/enhancement

I would like to be able to install the most recent version of Python 3.8.

# Proposed technical implementation details (optional)

```
install Python.Python --version 3.8.*
```

**Comment by denelon** [comment] 2020-11-05 16:03
Duplicate of #227

**Comment by denelon** [comment] 2020-11-05 16:03
@bersbersbers thanks for submitting the issue. I know the name of the other work item is a bit confusing, but I believe it is exactly what you are looking for. You can follow that issue.

**Closed by denelon** 2020-11-05 16:03 UTC
Labels: Issue-Feature, Needs-Triage
