### ISSUE TITLE
The id and name options does not participate the filter as expected.

### ISSUE THREAD

**Issue by hantsy** [microsoft/winget-cli#1715] opened 2021-11-16 05:18 UTC
### Brief description of your issue

Add the id and name but no effects there.

### Steps to reproduce

```bash
> winget upgrade "Microsoft.VC++2015-2022Redist-x86"
Multiple installed packages found matching input criteria. Please refine the input.
Name                                                               Id
---------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015-2022 Redistributable (x86)               Microsoft.VC++2015-2022Redist-x86
Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.30.30704 {57a73df6-4ba9-4c1d-bbbb-517289ff6c13}
```
```bash
> winget upgrade --id "Microsoft.VC++2015-2022Redist-x86" --name "Microsoft Visual C++ 2015-2022 Redistributable (x86)"
Multiple installed packages found matching input criteria. Please refine the input.
Name                                                               Id
---------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015-2022 Redistributable (x86)               Microsoft.VC++2015-2022Redist-x86
Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.30.30704 {57a73df6-4ba9-4c1d-bbbb-517289ff6c13}
```

### Expected behavior

Filter by id and name

### Actual behavior

No any effects applied

### Environment

```shell
winget --info
Windows Package Manager v1.1.12701
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.1348
Package: Microsoft.DesktopAppInstaller v1.16.12701.0
```

**Comment by denelon** [comment] 2021-11-16 16:49
Duplicate of #1413

**Closed by denelon** 2021-11-16 16:49 UTC
Labels: Needs-Triage
