### ISSUE TITLE
WinDirStat.WinDirStat: Unknown version

### ISSUE THREAD

**Issue by AdamJel** [microsoft/winget-cli#1970] opened 2022-02-23 13:31 UTC
### Brief description of your issue

After winget installs the WinDirStat package, its version is unknown and therefor cannot be updated.

### Steps to reproduce

```powershell
❯ winget install --name "WinDirStat" -h
Found WinDirStat [WinDirStat.WinDirStat] Version 1.1.2
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://sourceforge.net/projects/windirstat/files/windirstat/1.1.2%20installer%20re-release%20%28more%20languages%21%29/windirstat1_1_2_setup.exe/download
  ██████████████████████████████   630 KB /  630 KB
Successfully verified installer hash
Starting package install...
Successfully installed
❯
❯
❯ winget upgrade
Name       Id                      Version              Available
----------------------------------------------------------------------------
WinDirStat WinDirStat.WinDirStat   Unknown              1.1.2
❯
❯
❯ winget upgrade --name "WinDirstat" -h
This packages version number cannot be determined. To upgrade it anyway, add the argument --include-unknown to your previous command.
❯
❯
❯ winget upgrade --name "WinDirStat" -h --include-unknown
No applicable update found.
❯
```

### Expected behavior

...

### Actual behavior

...

### Environment

```shell
Windows Package Manager (Preview) v1.3.431-preview
Windows: Windows.Desktop v10.0.19044.1566
Package: Microsoft.DesktopAppInstaller v1.18.431.0
```

**Comment by OfficialEsco** [comment] 2022-02-23 13:54
This is a newly discovered issue
Related issue
* https://github.com/microsoft/winget-pkgs/issues/47655
* https://github.com/microsoft/winget-pkgs/issues/47777

[Current Manifest](https://github.com/microsoft/winget-pkgs/blob/ebe9da1320907ec226c3fd2fc4f620e85f3c0a1f/manifests/w/WinDirStat/WinDirStat/1.1.2/WinDirStat.WinDirStat.installer.yaml)

<details>
<summary>Click for Log</summary>
<br>

```
2022-02-23 14:44:42.496 [CORE] WinGet, version [1.3.431-preview], activity [{8E8947A7-7D57-4036-94C2-FAB3485A995C}]
2022-02-23 14:44:42.496 [CORE] OS: Windows.Desktop v10.0.22000.493
2022-02-23 14:44:42.496 [CORE] Command line Args: "C:\Users\User\AppData\Local\Microsoft\WindowsApps\winget.exe" upgrade windirstat --include-unknown
2022-02-23 14:44:42.496 [CORE] Package: Microsoft.DesktopAppInstaller v1.18.431.0
2022-02-23 14:44:42.496 [CORE] IsCOMCall:0; Caller: winget-cli
2022-02-23 14:44:42.500 [CLI ] WinGet invoked with arguments: 'upgrade' 'windirstat' '--include-unknown'
2022-02-23 14:44:42.500 [CLI ] Found subcommand: upgrade
2022-02-23 14:44:42.500 [CLI ] Leaf command to execute: root:upgrade
2022-02-23 14:44:42.501 [CLI ] Executing command: upgrade
2022-02-23 14:44:42.501 [REPO] Source named 'msstore' is already defined at origin User. The source from origin Default is dropped.
2022-02-23 14:44:42.501 [REPO] GetCurrentSourceRefs: Source named 'msstore' from origin User is hidden and is dropped.
2022-02-23 14:44:42.501 [REPO] GetCurrentSourceRefs: Source named 'microsoft.builtin.desktop.frameworks' from origin Default is hidden and is dropped.
2022-02-23 14:44:42.501 [REPO] Default source requested, only 1 source available, using the only source: winget
2022-02-23 14:44:42.502 [REPO] Source named 'msstore' is already defined at origin User. The source from origin Default is dropped.
2022-02-23 14:44:42.502 [REPO] Named source requested, found: winget
2022-02-23 14:44:42.502 [REPO] Source named 'msstore' is already defined at origin User. The source from origin Default is dropped.
2022-02-23 14:44:42.510 [CORE] Examining extension: PFN = Microsoft.Winget.Source_8wekyb3d8bbwe, ID = IndexDB
2022-02-23 14:44:42.510 [CORE] Found matching extension.
2022-02-23 14:44:42.523 [REPO] Opening SQLite Index for ImmutableRead at 'C:\Program Files\WindowsApps\Microsoft.Winget.Source_2022.223.1113.482_neutral__8wekyb3d8bbwe\Public\index.db'
2022-02-23 14:44:42.523 [SQL ] Opening SQLite connection: 'file:/C:/Program Files/WindowsApps/Microsoft.Winget.Source_2022.223.1113.482_neutral__8wekyb3d8bbwe/Public/index.db?immutable=1' [1, 40]
2022-02-23 14:44:42.523 [REPO] Opened SQLite Index with version [1.3], last write [2022-02-23 11:13:15.000]
2022-02-23 14:44:42.606 [REPO] Source named 'msstore' is already defined at origin User. The source from origin Default is dropped.
2022-02-23 14:44:42.607 [REPO] Source named 'msstore' is already defined at origin User. The source from origin Default is dropped.
2022-02-23 14:44:42.607 [REPO] Creating PredefinedInstalledSource with filter [None]
2022-02-23 14:44:42.607 [REPO] Creating new SQLite Index [4294967295.4294967295] at ':memory:'
2022-02-23 14:44:42.607 [SQL ] Opening SQLite connection: ':memory:' [6, 0]
2022-02-23 14:44:42.648 [REPO] Examining ARP entries for Machine | X64
2022-02-23 14:44:42.650 [REPO] Examining ARP entries for Machine | X86
2022-02-23 14:44:42.651 [REPO] Examining ARP entries for User | X64
2022-02-23 14:44:42.720 [REPO] Opening SQLite Index for ReadWrite at 'C:\Users\User\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Microsoft.Winget.Source_8wekyb3d8bbwe\installed.db'
2022-02-23 14:44:42.720 [SQL ] Opening SQLite connection: 'C:\Users\User\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Microsoft.Winget.Source_8wekyb3d8bbwe\installed.db' [2, 0]
2022-02-23 14:44:42.721 [REPO] Opened SQLite Index with version [1.3], last write [2022-02-23 14:41:22.000]
2022-02-23 14:44:42.775 [CLI ] Found one app. App id: WinDirStat.WinDirStat App name: WinDirStat
2022-02-23 14:44:42.777 [REPO] Downloading manifest
2022-02-23 14:44:42.777 [CORE] WinINet downloading from url: https://winget.azureedge.net/cache/manifests/w/WinDirStat/WinDirStat/1.1.2/1994-WinDirStat.WinDirStat.yaml
2022-02-23 14:44:42.790 [CORE] Download hash: cb459d69db4ccb31289dac82d77f6439782e3f9e3754b91f7cee6db06df3e587
2022-02-23 14:44:42.790 [CORE] Download completed.
2022-02-23 14:44:42.790 [CLI ] Starting installer selection.
2022-02-23 14:44:42.790 [CLI ] Installer [X86,nullsoft,Machine,] not applicable: Installer scope does not match currently installed scope: Machine != User
2022-02-23 14:44:42.796 [CLI ] Terminating context: 0x8a15002b at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\UpdateFlow.cpp:7c
```

</details>

<details>
<summary>Click for Pictures</summary>
<br>

Prompts for Administrator on install
![VirtualBoxVM_6NqIrKNQZU](https://user-images.githubusercontent.com/15158490/155332603-6afc890c-17c8-4c72-93cd-1af48c3b3ddb.png)

Installed to `C:\Program Files (x86)\WinDirStat`
![VirtualBoxVM_0cilsmNJDW](https://user-images.githubusercontent.com/15158490/155332609-74ded00f-7857-457c-bde3-1f6a862fa920.png)

Registry key at `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\WinDirStat`
instead of `HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\WinDirStat`
![VirtualBoxVM_BI9yFU7lq1](https://user-images.githubusercontent.com/15158490/155332617-9c28d590-b21f-4897-8e1a-efd2efad8409.png)


</details>

**Comment by denelon** [comment] 2022-02-23 22:44
The package isn't reporting a version number to Windows Apps & Features.

Duplicate of #1943 

The other issue is:
* #1939

**Closed** 2022-02-23 22:44 UTC
Labels: Issue-Bug, Area-External
