### ISSUE TITLE
If there are multiple matches for an input criteria, let users select the correct package via arrow keys

### ISSUE THREAD

**Issue by bdbch** [microsoft/winget-cli#3834] opened 2023-10-31 12:35 UTC
### Description of the new feature / enhancement

Lets say you want to install Blender via Winget and you run `winget install blender` because that would make the most sense, currently you'll get the response

```bash
Name        ID                            Source
-------------------------------------------------
Blender     9PP3C07GTVRH                  msstore
Blender     BlenderFoundation.Blender     winget
Blender LTS BlenderFoundation.Blender.LTS winget
```

and you need to rerun the winget command with the exact ID. It would be nice if there were multiple occurences for a package name, let the users use the arrow keys afterwards to pick the wanted package without any unnecessary command inputs.

Here is an example on how it could look like:

![Example screenshot of a list selection prompt](https://camo.githubusercontent.com/61a2d06601cf57261784ce01d1d37653864e391c5da5953948503b4026cfc6cc/68747470733a2f2f63646e2e7261776769742e636f6d2f53426f7564726961732f496e7175697265722e6a732f323861653833333762613531643933653335396566346637656532346537396236393839383936322f6173736574732f73637265656e73686f74732f6c6973742e737667)

**Comment by Trenly** [comment] 2023-10-31 13:23
* Duplicate of #1620

**Closed** 2023-10-31 13:24 UTC
Labels: Issue-Feature, Needs-Triage
