### ISSUE TITLE
Winget upgrade package, No applicable update found

### ISSUE THREAD

**Issue by kdpuvvadi** [microsoft/winget-cli#1191] opened 2021-06-19 19:36 UTC
# Brief description of your issue

 if i run `winget upgraded packagename` & update available, it should update the package but it shows No applicable update found even though it's showing the newer version available. 

# Steps to reproduce

`winget upgrade ` list of the available updates
`winget upgrade --all` or `winget upgrade Python.Python.3` 

# Expected behavior

It should update the actual selected package or all incase of `--all`

# Actual behavior

throws `No applicable update found` and if i run `winget install packagename` then installs the update. 

# Environment

Windows 10 Enterprise 21H1 build 19043.1055
Experience Pack 120.2212.2020.0

```none
[winget --info]
Windows Package Manager v1.0.11451
Windows: Windows.Desktop v10.0.19043.1055
Package: Microsoft.DesktopAppInstaller v1.11.11451.0
```

**Comment by KaranKad** [comment] 2021-06-21 17:19
This issue might be related to [winget-pkgs](https://github.com/microsoft/winget-pkgs)
@kdpuvvadi Did you first install install Firefox from it's website using exe installer or from winget?

I was able to replicate this issue by installing old version of Firefox using `exe` installer and then trying `winget upgrade Mozilla.Firefox`
```
❯ winget upgrade
Name                              Id                      Version      Available   Source
-----------------------------------------------------------------------------------------
Mozilla Firefox                   Mozilla.Firefox         89.0         89.0.1      winget
Winamp                            Radionomy.Winamp        5.8          5.8         winget
Microsoft Windows Desktop Runtime Microsoft.dotnetRuntime 5.0.6.30021  5.0.7.30113 winget
TechPowerUp GPU-Z                 TechPowerUp.GPU-Z       Unknown      2.40.0      winget
Microsoft Windows Desktop Runtime Microsoft.dotnetRuntime 3.1.15.30014 5.0.7.30113 winget

❯ winget upgrade Mozilla.Firefox
No applicable update found.
```
WinGet's Firefox manifest only contains msi installer so that might be the issue.

**Comment by denelon** [comment] 2021-06-21 17:22
@KaranKad thanks for figuring this one out. We do try to avoid updating a package with a different "InstallerType".

**Comment by OfficialEsco** [comment] 2021-06-21 17:26
winget CLI need to explain this instead of `No applicable update found.`. A better reporting would most likely help solve most of these issues since we could narrow it down.

**Comment by denelon** [comment] 2021-06-21 22:45
https://github.com/microsoft/winget-cli/issues/1196

**Comment by kdpuvvadi** [comment] 2021-06-22 02:56
> This issue might be related to [winget-pkgs](https://github.com/microsoft/winget-pkgs)
> @kdpuvvadi Did you first install Firefox from it's website using exe installer or from winget?
 
only installed it from winget. as others in the screenshot.

**Comment by KaranKad** [comment] 2021-06-22 07:38
@denelon It actually does not upgrade even if previously installed using `msi` installer. Now I installed old version of firefox from winget which installs from `msi` installer and then tried `winget upgrade Mozilla.Firefox` which should install next version from `msi` installer but it throws `No applicable update found.`. Looks like the problem might be related to winget-cli after all. 😅
```
❯  winget install firefox -v 89.0
Found Mozilla Firefox [Mozilla.Firefox]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download-installer.cdn.mozilla.net/pub/firefox/releases/89.0/win64/en-US/Firefox%20Setup%2089.0.msi
  ██████████████████████████████  53.4 MB / 53.4 MB
Successfully verified installer hash
Starting package install...
Successfully installed

❯  winget upgrade
Name                              Id                      Version      Available   Source
-----------------------------------------------------------------------------------------
Mozilla Firefox                   Mozilla.Firefox         89.0         89.0.1      winget

❯  winget upgrade Mozilla.Firefox
No applicable update found.
```

**Comment by kdpuvvadi** [comment] 2021-06-22 09:02
@KaranKad I've just tested that. reults the same. it might the issue with cli. 

```
❯ winget install Mozilla.Firefox -v 84.0
Found Firefox [Mozilla.Firefox]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download-installer.cdn.mozilla.net/pub/firefox/releases/84.0/win64/en-US/Firefox%20Setup%2084.0.msi
  ██████████████████████████████  55.2 MB / 55.2 MB
Successfully verified installer hash
Starting package install...
Successfully installed

❯ winget upgrade
Name                              Id                          Version      Available   Source
---------------------------------------------------------------------------------------------
Mozilla Firefox             Mozilla.Firefox             84.0         89.0.1      winget

❯ winget upgrade firefox
No applicable update found.
```

**Comment by kdpuvvadi** [comment] 2021-06-22 09:09
And `winget install firefox` installs the latest version though. 

```
❯ winget install firefox
Found Mozilla Firefox [Mozilla.Firefox]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download-installer.cdn.mozilla.net/pub/firefox/releases/89.0.1/win64/en-US/Firefox%20Setup%2089.0.1.msi
  ██████████████████████████████  53.3 MB / 53.3 MB
Successfully verified installer hash
Starting package install...
Successfully installed

```

**Comment by OfficialEsco** [comment] 2021-06-22 09:51
Can actually confirm this is happening on a PC which i installed Firefox on via Winget before, the issue might be the ProductCode on the Firefox MSI installer which is not changing?

**Comment by bcrod** [comment] 2021-06-23 20:43
Somehow the winget has this problem when the app doesn't provide the version number to windows. Or is it just me?

![image](https://user-images.githubusercontent.com/26559476/123165156-3e21c100-d44a-11eb-97c3-d3a37d068397.png)
![image](https://user-images.githubusercontent.com/26559476/123165220-54c81800-d44a-11eb-880a-ca97ce3fde93.png)
![image](https://user-images.githubusercontent.com/26559476/123165253-61e50700-d44a-11eb-973a-849fa848ddc6.png)

**Comment by bcrod** [comment] 2021-06-23 21:09
The solution for me was to edit reg (HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall) and  create the missing "DisplayVersion" keys.

**Comment by cloudrootab** [comment] 2021-06-24 08:38
> The solution for me was to edit reg (HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall) and  create the missing "DisplayVersion" keys.

For me the program (Gog.Galaxy in this case) was located in HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall

But adding the 'DisplayVersion' key, did in fact make winget see that it doesn't need to download the same installer over and over again.. Not sure of what will happen after an upgrade though.

**Comment by OfficialEsco** [comment] 2021-06-24 08:47
> Not sure of what will happen after an upgrade though.

```
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget install GOG.Galaxy --version 2.0.35.19
Found GOG Galaxy [GOG.Galaxy]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://content-system.gog.com/open_link/download?path=/open/galaxy/client/2.0.35.19/setup_galaxy_2.0.35.19a.exe
  ██████████████████████████████   231 MB /  231 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```


```
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget upgrade
Name           Id             Version     Available   Source
------------------------------------------------------------
Microsoft Edge Microsoft.Edge 89.0.774.68 91.0.864.54 winget
GOG Galaxy     GOG.Galaxy     Unknown     2.0.37.384  winget
```
Registry Workarond
```
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget upgrade
Name           Id             Version     Available   Source
------------------------------------------------------------
Microsoft Edge Microsoft.Edge 89.0.774.68 91.0.864.54 winget
GOG Galaxy     GOG.Galaxy     2.0.35.19   2.0.37.384  winget
```


```
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget upgrade GOG.Galaxy
Found GOG Galaxy [GOG.Galaxy]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://content-system.gog.com/open_link/download?path=/open/galaxy/client/2.0.37.384/setup_galaxy_2.0.37.384.exe
  ██████████████████████████████   273 MB /  273 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

```
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget upgrade
Name           Id             Version     Available   Source
------------------------------------------------------------
Microsoft Edge Microsoft.Edge 89.0.774.68 91.0.864.54 winget
GOG Galaxy     GOG.Galaxy     Unknown     2.0.37.384  winget
```

**Comment by bcrod** [comment] 2021-06-25 04:05
Winget should also read and extract the application's version directly from the executable (specific metadata) and make the comparison if other methods fail or if the version is "unknown". GOG.exe has this metadata.

**Comment by bcrod** [comment] 2021-06-25 04:15
Lockhunter developers email me and provide a new version and now shows correctly the version number in the windows uninstall menu. I think for the "unknown" version problem the solution is this.

![image](https://user-images.githubusercontent.com/26559476/123368567-68f73c80-d552-11eb-9166-e0a60b135ca5.png)

**Comment by bcrod** [comment] 2021-06-25 04:18
Lockhunter developers email me and provide a new version and now shows correctly the version number in the windows uninstall menu. I think for the "unknown" version problem the solution is this.

![image](https://user-images.githubusercontent.com/26559476/123368986-313cc480-d553-11eb-9d0c-f85167eb4772.png)

**Comment by chausner** [comment] 2021-06-28 23:11
I am having the same issue with WinRAR. Attempting to upgrade it shows "No applicable update found".
```
Name                         ID                                    Version         Verfügbar       Quelle
----------------------------------------------------------------------------------------------------------
WinRAR                       RARLab.WinRAR                         6.01.0          6.02.0          winget
```
My installation does have the right version number in ARP but the title does not match what winget expects:
![image](https://user-images.githubusercontent.com/15180557/123714468-a58aa700-d876-11eb-8383-a877cef94a40.png)
I don't remember whether I originally installed it via winget or another installer.

**Comment by kdpuvvadi** [comment] 2021-06-29 04:20
Just observed something. If you are upgrading all with `--all` & the installation is not silent and for some reason any of the upgrading apps launches itself after upgrade, the above persists. as @OfficialEsco said Firefox has different product codes but here i've a problem with powertoys. 

```
❯ winget upgrade
Name                Id                  Version Available Source
----------------------------------------------------------------
Thonny              AivarAnnamaa.Thonny 3.3.10  3.3.11    winget
PowerToys (Preview) Microsoft.PowerToys 0.37.2  0.41.2    winget

❯ winget upgrade --all
Found Postman [Postman.Postman]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dl.pstmn.io/download/version/8.7.0/win64
  ██████████████████████████████   111 MB /  111 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Found Thonny [AivarAnnamaa.Thonny]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/thonny/thonny/releases/download/v3.3.11/thonny-3.3.11.exe
  ██████████████████████████████  17.0 MB / 17.0 MB
Successfully verified installer hash
Starting package install...
Successfully installed
``` 
If you see above, postman update does not appear when checking for updates with `winget upgrade` but when upgrading all with `winget upgrade --all` postman starts installing and as soon as postman launches upgrade stops. I was able upgrade powertoys on different pc but here i can't. Here installer is `exe` though.

**Comment by OfficialEsco** [comment] 2021-06-29 08:17
@chausner
> I am having the same issue with WinRAR. Attempting to upgrade it shows "No applicable update found".

What Language link did you install WinRAR with? (Or what language is your WinRAR in?) Each language have a different installer for some dumb reason and they don't release at the same time...

@kdpuvvadi
I just looked into Postman and realized the InstallerType and InstallerSwitches was wrong (it won't start after updating now).. However i didn't get a update from `winget upgrade --all`, but this might be a winget-cli issue.

>  I was able upgrade powertoys on different pc but here i can't. Here installer is exe though.

I don't see why this is happening, there is no x86, there is no different locales, the ProductCode should have been updated 10 hours ago, try `winget source update; winget upgrade Microsoft.Powertoys` again

**Comment by cloudrootab** [comment] 2021-06-29 09:12
> winget source update; winget upgrade Microsoft.Powertoys

```
winget source update && winget upgrade && winget upgrade Microsoft.PowerToys
Updating all sources...
Updating source: winget
Done
Name                Id                  Version Available Source
----------------------------------------------------------------
Google Cloud SDK    Google.CloudSDK     Unknown 346.0.0   winget
PowerToys (Preview) Microsoft.PowerToys 0.41.2  0.41.3    winget
No applicable update found.
```

This was done in an administrator command line, 11:09 29th-Juni (CEST)

**Comment by jedieaston** [comment] 2021-06-29 11:46
I think PowerToys has issues because their exe runs an MSI (although I'm not 100% sure, I've experienced this issue though).

**Comment by denelon** [comment] 2021-06-29 14:48
@cloudrootab we've identified one of the issues with PowerToys is the installer behavior. The installer is a .msi wrapped up in a .exe. The .exe does some work to manage dependencies, and then the MSI installs PowerToys. When the Windows Package Manager does the comparison for the package, it sees the mismatch between the .exe installer in the manifest and the MSI as the installer type in Add / Remove Programs. The current behavior is to halt installation. We're working with the PowerToys team to identify any other issues so we can make the appropriate changes to improve this behavior.

**Comment by chausner** [comment] 2021-06-29 16:05
> What Language link did you install WinRAR with? (Or what language is your WinRAR in?) Each language have a different installer for some dumb reason and they don't release at the same time...

My WinRAR installation is in German.

**Comment by OfficialEsco** [comment] 2021-06-30 15:51
> > What Language link did you install WinRAR with? (Or what language is your WinRAR in?) Each language have a different installer for some dumb reason and they don't release at the same time...
> 
> My WinRAR installation is in German.

I forgot to answer this multiple times 🤦‍♂️ German is actually in the manifest, the installer was just not released when i updated WinRAR, the German locale got added yesterday in https://github.com/microsoft/winget-pkgs/pull/19300, there should be a simpler way since the locales gets available at different times.. as you can see `ja-JP` is still not updated to the latest version

**Comment by chausner** [comment] 2021-06-30 19:41
> > > What Language link did you install WinRAR with? (Or what language is your WinRAR in?) Each language have a different installer for some dumb reason and they don't release at the same time...
> > 
> > 
> > My WinRAR installation is in German.
> 
German is actually in the manifest, the installer was just not released when i updated WinRAR, the German locale got added yesterday in [microsoft/winget-pkgs#19300](https://github.com/microsoft/winget-pkgs/pull/19300)

I see, thanks for the clarification! I can confirm it upgraded successfully today when I retried.

**Comment by auanasgheps** [comment] 2021-07-07 16:46
Hi, I have a similar issue with VMware workstation. Installed with Winget, shows the update with `winget upgrade` but is unable to find it when I execute winget upgrade VMware.WorkstationPro.

Should I open a new case? This program does not have language installers like WinRar does.

**Comment by OfficialEsco** [comment] 2021-07-07 17:59
> Hi, I have a similar issue with VMware Workstation. Originally installed some months ago with Winget, shows the update with `winget upgrade` but is unable to find it when I execute winget upgrade VMware.WorkstationPro.
> 
> Should I open a new case? This program does not have language installers like WinRar does.

Try once https://github.com/microsoft/winget-pkgs/pull/20134 gets merged, might have been the architecture.
However it seems weird, its detected as x64 and a user installation, but the exe is a x86 and a machine wide install...

**Comment by auanasgheps** [comment] 2021-07-07 21:59
> 
> 
> > Hi, I have a similar issue with VMware Workstation. Originally installed some months ago with Winget, shows the update with `winget upgrade` but is unable to find it when I execute winget upgrade VMware.WorkstationPro.
> > Should I open a new case? This program does not have language installers like WinRar does.
> 
> Try once [microsoft/winget-pkgs#20134](https://github.com/microsoft/winget-pkgs/pull/20134) gets merged, might have been the architecture.
> However it seems weird, its detected as x64 and a user installation, but the exe is a x86 and a machine wide install...

Right, thanks, I'll try once merged! I'm surprised it's a 32 bit installer actually.

**Comment by leochras** [comment] 2021-07-26 06:28
![image](https://user-images.githubusercontent.com/16163571/126942845-370f450c-498b-4eca-868e-c2888fc14db3.png)
I think this is related to this issue..

**Comment by OfficialEsco** [comment] 2021-07-26 06:30
> I think this is related to this issue..

Try running Terminal as Administrator, exit code 1 usually means access denied

**Comment by leochras** [comment] 2021-07-26 06:34
> > I think this is related to this issue..
> 
> Try running Terminal as Administrator, exit code 1 usually means access denied

![image](https://user-images.githubusercontent.com/16163571/126943505-4fd951a6-7918-478c-85c9-1ae030a56abb.png)
Still failing, but with another error..

**Comment by ImJoakim** [comment] 2021-07-26 06:36
> > > I think this is related to this issue..
> > 
> > 
> > Try running Terminal as Administrator, exit code 1 usually means access denied
> 
> Still failing, but with another error..

Try rebooting your computer.

**Comment by OfficialEsco** [comment] 2021-07-26 06:38
> > > > I think this is related to this issue..
> > > 
> > > 
> > > Try running Terminal as Administrator, exit code 1 usually means access denied
> > 
> > 
> > Still failing, but with another error..
> 
> Try rebooting your computer.

Exit code 3010 actually means reboot required yes😁

Does it install correctly? If so we can add that exit code as valid exit code

**Comment by leochras** [comment] 2021-07-26 06:41
> > > > > I think this is related to this issue..
> > > > 
> > > > 
> > > > Try running Terminal as Administrator, exit code 1 usually means access denied
> > > 
> > > 
> > > Still failing, but with another error..
> > 
> > 
> > Try rebooting your computer.
> 
> Exit code 3010 actually means reboot required yes😁
> 
> Does it install correctly? If so we can add that exit code as valid exit code

Why doesn't it say that right in the command line? 

Anyway, winget doesn't list the update anymore, but when I open VirtualBox it says that there is a newer version available (Same version winget upgraded to)

**Comment by leochras** [comment] 2021-07-26 10:49
> > > > > I think this is related to this issue..
> > > > 
> > > > 
> > > > Try running Terminal as Administrator, exit code 1 usually means access denied
> > > 
> > > 
> > > Still failing, but with another error..
> > 
> > 
> > Try rebooting your computer.
> 
> Exit code 3010 actually means reboot required yes😁
> 
> Does it install correctly? If so we can add that exit code as valid exit code

Yes, but winget should not handle this as error. It should just say something like: "To finish the installation, a reboot is required. Reboot now? (y/n)"

**Comment by ImJoakim** [comment] 2021-07-26 10:52
> Yes, but winget should not handle this as error. It should just say something like: "To finish the installation, a reboot is required. Reboot now? (y/n)"

It's currently on the To-Do list, more info can be found in this issue: https://github.com/microsoft/winget-cli/issues/994#issue-903025739

**Comment by OfficialEsco** [comment] 2021-07-26 10:53
> Why doesn't it say that right in the command line?
>
> Yes, but winget should not handle this as error. It should just say something like: "To finish the installation, a reboot is required. Reboot now? (y/n)"

Tell that to all the different exit codes different softwares can have

**Comment by USMA56795** [comment] 2021-07-29 02:12
In case it's helpful, I can confirm that "Unknown" seems to be shown for applications that don't register their version with Windows.  The two packages that stick out for me are `Blizzard.BattleNet` and `GOG.Galaxy`.


![2021-07-29_020707_UTC](https://user-images.githubusercontent.com/53479999/127420634-0d33340f-4b09-4884-b9f7-1c39deb68663.png)

![2021-07-29_021113_UTC](https://user-images.githubusercontent.com/53479999/127420758-35c27962-3f62-425a-9489-5695b348f9ec.png)

![2021-07-29_021222_UTC](https://user-images.githubusercontent.com/53479999/127420836-d75bf637-32dd-4e52-a56c-55e6c6f0b00a.png)

![2021-07-29_021200_UTC](https://user-images.githubusercontent.com/53479999/127420844-d1b2b7d9-4bb8-4604-8570-3842069b1944.png)

**Comment by KaranKad** [comment] 2021-07-30 14:48
`Oracle.JavaRuntimeEnvironment` has similar issue
![image](https://user-images.githubusercontent.com/71691514/127670633-2011c40b-5cc8-4034-a0f5-e5089f947594.png)

**Comment by nascentt** [comment] 2021-09-13 11:13
```
winget upgrade
Name                                  Id                              Version     Available   Source
----------------------------------------------------------------------------------------------------
4K Video Downloader                   OpenMedia.4KVideoDownloader     4.15.0.4160 4.17.2.4460 winget
PS C:\Code\PowerShell> winget upgrade OpenMedia.4KVideoDownloader
No applicable update found.
```

**Comment by OfficialEsco** [comment] 2021-09-13 11:37
@nascentt can you check the log at `%LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir` ?
If the path does not work use `winget --info`

**Comment by nascentt** [comment] 2021-09-13 11:46
> @nascentt can you check the log at `%LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir` ?
> If the path does not work use `winget --info`

[WinGet-2021-09-13-12-12-54.790.log](https://github.com/microsoft/winget-cli/files/7153975/WinGet-2021-09-13-12-12-54.790.log)

**Comment by ItzLevvie** [comment] 2021-09-13 11:53
By looking at the error logs, you likely installed `4kvideodownloader_4.15.0_x64_online.exe`?

The packages only includes the offline MSI installer at the moment.

**Comment by OfficialEsco** [comment] 2021-09-13 11:54
```
2021-09-13 12:12:56.282 [CLI ] Installer [X64,Msi,Machine,en-US] not applicable: Installed package type is not compatible with Msi
2021-09-13 12:12:56.282 [CLI ] Installer [X86,Msi,Machine,en-US] not applicable: Installed package type is not compatible with Msi
```

It appears you've used the Online Installer which a exe/burn
https://dl.4kdownload.com/app/4kvideodownloader_4.17.2_online.exe

This should be a easy fix if it supports silent install

**Comment by strandloper** [comment] 2021-10-17 19:25
It even happens with Microsoft's own packages just tried to upgrade Powertoys and despite winget showing there is an update available it fails to upgrade.
![image](https://user-images.githubusercontent.com/668433/137641972-b0bca738-6219-463e-96b9-9c8eaad9ec73.png)

**Closed** 2021-11-18 22:47 UTC
Labels: Issue-Bug

**Comment by leochras** [comment] 2021-11-22 08:13
7-Zip has this problem:
![image](https://user-images.githubusercontent.com/16163571/142825956-dc991e91-1239-4263-b4af-61be28766835.png)

**Comment by OfficialEsco** [comment] 2021-11-22 08:19
Currently only the EXE is released.

**Comment by leochras** [comment] 2021-11-22 08:25
> Currently only the EXE is released.

This shouldn't be a problem right? Reinstalling does work btw

**Comment by OfficialEsco** [comment] 2021-11-22 08:53
> we look at the installer type used for the current installation. If the new installer type doesn't match, we don't upgrade. I'm not sure how many times this scenario happens, so there may be more than one way to deal with it. I'll create a new issue.

https://github.com/microsoft/winget-cli/pull/1649

According to that commit you should be asked if you want to replace the MSI with the EXE, however its not even implemented in version `1.2.3131-preview`, so maybe it will be in the full version of 1.2 which is ETA 31 December (Unknown)

**Comment by Nishith-Savla** [comment] 2022-01-07 18:33
Any update yet? I'm facing the same issue...

**Comment by Romanitho** [comment] 2022-02-21 17:06
Same here :/

**Comment by OfficialEsco** [comment] 2022-02-22 19:00
These issues should be worked around in https://github.com/microsoft/winget-cli/releases/tag/v1.3.431

**Comment by Nishith-Savla** [comment] 2022-02-23 10:07
> These issues should be worked around in https://github.com/microsoft/winget-cli/releases/tag/v1.3.431 The Cryptomator issue: #1640

This doesn't appear to have fixed yet....
![image](https://user-images.githubusercontent.com/63643696/155298337-70de0112-a3d5-4211-b5b9-4f6d98030b9a.png)

**Comment by OfficialEsco** [comment] 2022-02-23 10:29
I can’t seem to find that package mentioned in this thread but it looks like a easy fix

For any future relevant issues/info please read my comment from a different thread https://github.com/microsoft/winget-cli/issues/752#issuecomment-1048293063

**Comment by bboysnick5** [comment] 2022-03-19 07:40
So go 1.18 is out and winget does show 1.18 with search command. But cannot upgrade. [interesting] (as it's more verbose and easier to type plus more programming like than emoji)

**Comment by digulla** [comment] 2022-06-08 13:55
Please provide more details in the error message when winget thinks it can't update (like "app was installed manually; please uninstall, first").

**Comment by lmachegger** [comment] 2022-06-26 13:40
I have the same issue "No applicable update found." for the package PostgreSQL.PostgreSQL. 
Even when I freshly install this package, it shows an available update, but when trying to update I get "no applicable update found." Broken packages like this make `winget upgrade --all` completely unusable for me.

```
# m4chei WORKSTATION ~ [15:35:32]
❯ winget install PostgreSQL.PostgreSQL
Found PostgreSQL 14 [PostgreSQL.PostgreSQL] Version 14
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://get.enterprisedb.com/postgresql/postgresql-14.1-1-windows-x64.exe
  ██████████████████████████████   284 MB /  284 MB
Successfully verified installer hash
Starting package install...
Successfully installed
# m4chei WORKSTATION ~ [15:38:05]
❯ winget upgrade
Name               Id                    Version  Available   Source
--------------------------------------------------------------------
PostgreSQL 14      PostgreSQL.PostgreSQL 9.5      14          winget
heroku             Heroku.HerokuCLI      Unknown  7.53.0.0    winget
Python 2           Python.Python.2       2.7.150  2.7.18150   winget
SharpKeys          RandyRants.SharpKeys  3.9.2000 3.9.4000    winget
VMware Workstation VMware.WorkstationPro 16.1.2   16.2.3      winget
Python 3           Python.Python.3       3.4.4150 3.10.5150.0 winget
6 upgrades available.
# m4chei WORKSTATION ~ [15:38:20]
❯ winget upgrade PostgreSQL.PostgreSQL
No applicable update found.
# m4chei WORKSTATION ~ [15:38:30]
❯
```

**Comment by OfficialEsco** [comment] 2022-06-27 08:00
@lmachegger you have PostgreSQL 9.5 installed somewhere else on your computer and/or remaining registry strings from PostgreSQL 9.5.

However we could probably split the major versions into different folders(packages) as they can be installed side by side

Use RevoUninstaller to actually get a clean install.

**Comment by insurgent** [comment] 2022-11-12 05:54
Also same issue with trying to update MS VCRedist:
![WingetIssue](https://user-images.githubusercontent.com/10741/201459589-4aa702d2-abbb-4add-ab07-1e48db9b9e08.jpg)

**Comment by emoxam** [comment] 2023-01-04 12:27
The same problem with
**winget upgrade --id="Logitech.LGS" -e**
A newer version was found, but the install technology is different from the current version installed. Please uninstall the package and install the newer version.
**winget upgrade** --id="ParadoxInteractive.ParadoxLauncher" -e
No applicable update found.


**winget upgrade**
Name                                              Id                                 Version      Available      Source
-----------------------------------------------------------------------------------------------------------------------
Google Chrome                                     Google.Chrome                      60.0.3112.78 108.0.5359.125 winget
Monkey's Audio x64                                MonkeysAudio.MonkeysAudio          8.03         9.04           winget
Notepad++ (32-bit x86)                            Notepad++.Notepad++                7.9.1        8.4.8          winget
Microsoft Visual C++ 2013 Redistributable (x64) … Microsoft.VCRedist.2013.x64        12.0.30501.0 12.0.40664.0   winget
Punto Switcher 4.2.6                              Yandex.PuntoSwitcher               4.2.6.1275   4.4.4.489      winget
Logitech Gaming Software 5.10                     Logitech.LGS                       5.10.127     9.04.28        winget
Royal TS 6.01.50504.0                             RoyalApps.RoyalTS                  6.1.50504.0  6.1.51214.0    winget
Telegram Desktop                                  Telegram.TelegramDesktop           4.3.2        4.4.1          winget
Paradox Launcher v2                               ParadoxInteractive.ParadoxLauncher 2.1.0        2.4.0          winget
NVIDIA GeForce Experience 3.24.0.135              Nvidia.GeForceExperience           3.24.0.135   3.26.0.154     winget
NVIDIA GeForce NOW 2.0.47.115                     Nvidia.GeForceNow                  2.0.47.115   2.0.47.125     winget
Epic Games Launcher                               EpicGames.EpicGamesLauncher        1.2.17.0     1.3.23.0       winget
Microsoft Visual C++ 2013 Redistributable (x86) … Microsoft.VCRedist.2013.x86        12.0.30501.0 12.0.40664.0   winget
13 upgrades available.

**Comment by JTellington** [comment] 2023-03-14 19:25
If you are trying to upgrade PowerShell and you use the Terminal application, it is possible that winget installs _**are**_ being downloaded - but are being stored in the Terminal application as an additional profile. This is what happened to me. I installed an updated PowerShell and the **$PSVersionTable** command kept returning the same 5.XX version after I used winget to upgrade to 7.XX. I think it'll be sooooo awesome if MS consolidated all CLI to the _**Terminal**_ application 🙃. If not possible, at least integrate the products a bit better. As of right now -  Terminal, Powershell, Powershell Preview all seem to behave somewhat independently.

**Comment by Masamune3210** [comment] 2023-03-14 19:38
The PowerShell that you download and install has to be separate from the in-box version because they are managed, updated, and handled in general differently from each other.

**Comment by BADF00D** [comment] 2023-06-05 04:46
This still seems to be a problem: 
```
PS C:\Users\user> $PSVersionTable.PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      3      4

PS C:\Users\user> winget --version
v1.4.11071
PS C:\Users\user> winget upgrade
Name                                                              Id                                    Version       Available     Source
------------------------------------------------------------------------------------------------------------------------------------------
NVM for Windows 1.1.10                                            CoreyButler.NVMforWindows             1.1.10        1.1.11        winget
Visual Studio Community 2022                                      Microsoft.VisualStudio.2022.Community 17.5.4        17.6.2        winget
JetBrains Rider 2022.3.2                                          JetBrains.Rider                       2022.3.2      2023.1        winget
Microsoft Visual C++ 2015-2022 Redistributable (x86) - 14.34.319… Microsoft.VCRedist.2015+.x64          14.34.31931.0 14.36.32532.0 winget
JetBrains ETW Host Service (x64)                                  JetBrains.ReSharper                   > 2022.2.2    2022.3.3      winget
OpenSSL 3.0.8 (64-bit)                                            ShiningLight.OpenSSL                  1.0.0         3.1.1         winget
6 upgrades available.
3 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.
PS C:\Users\user> winget upgrade --id Microsoft.VisualStudio.2022.Community
No applicable upgrade found.
PS C:\Users\user> winget upgrade --id Microsoft.VCRedist.2015+.x64
No applicable upgrade found.
PS C:\Users\user>
```

**Comment by rafaelelter** [comment] 2023-06-26 15:28
I was having this issue with the Microsoft Visual C++ 2013 Redistributable (x86) package. I figured out that winget was correctly showing that the package had an available upgrade, but it was showing the wrong id when listing the available upgrades. It was using the id of the x64 version, which was already upgraded. Once I used the correct id, the problem was solved.

<pre>
PS C:\> winget upgrade
Name                                                Id                             Version        Available      Source
-----------------------------------------------------------------------------------------------------------------------
Windows PC Health Check                             Microsoft.WindowsPCHealthCheck 3.1.2109.29003 3.7.2204.15001 winget
Microsoft Visual C++ 2013 Redistributable (x86) - … <b>Microsoft.VCRedist.2013.x64</b>    12.0.30501.0   12.0.40664.0   winget
2 upgrades available.

PS C:\>  winget list Microsoft.VCRedist.2013
Name                                                       Id                          Version      Available    Source
-----------------------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.40… Microsoft.VCRedist.2013.x64 12.0.40664.0              winget
Microsoft Visual C++ 2013 Redistributable (x86) - 12.0.30… <b>Microsoft.VCRedist.2013.x86</b> 12.0.30501.0 12.0.40664.0 winget
</pre>

**Comment by denelon** [comment] 2023-06-26 15:31
Hey all, this issue was closed. Take a look at [open Issues with the "Area-Matching" label](https://github.com/microsoft/winget-cli/issues?q=is%3Aissue+is%3Aopen+label%3Aarea-matching) to see current gaps and work in progress.

**Comment by JoydeepMallick** [comment] 2024-02-08 10:21
> # Brief description of your issue
> if i run `winget upgraded packagename` & update available, it should update the package but it shows No applicable update found even though it's showing the newer version available.
> 
> # Steps to reproduce
> `winget upgrade ` list of the available updates `winget upgrade --all` or `winget upgrade Python.Python.3`
> 
> # Expected behavior
> It should update the actual selected package or all incase of `--all`
> 
> # Actual behavior
> throws `No applicable update found` and if i run `winget install packagename` then installs the update.
> 
> # Environment
> Windows 10 Enterprise 21H1 build 19043.1055 Experience Pack 120.2212.2020.0
> 
> ```
> [winget --info]
> Windows Package Manager v1.0.11451
> Windows: Windows.Desktop v10.0.19043.1055
> Package: Microsoft.DesktopAppInstaller v1.11.11451.0
> ```

Check this out :- https://github.com/microsoft/winget-cli/issues/1191

This command did help me:-
```bash
winget uninstall Microsoft.Winget.Source_8wekyb3d8bbwe 
winget source reset --force
```
