### ISSUE TITLE
winget keeps redownloading/installing the same version

### ISSUE THREAD

**Issue by myokeeh** [microsoft/winget-cli#2250] opened 2022-06-17 17:01 UTC
I've noticed that when I `winget upgrade --all`, a couple items always show up with the same version and winget downloads them and reinstalls them.

Ultimaker Cura [Ultimaker.Cura] Version 5.0.0
CrystalDiskInfo (I can't remember the version)

_Originally posted by @myokeeh in https://github.com/microsoft/winget-cli/discussions/2248_

**Comment by denelon** [comment] 2022-06-17 22:16
Duplicate of #752 

The second paragraph explains what is happening in this case.
Cura doesn't perform an upgrade. It installs the newer version. The reason the manifest hasn't been modified to "uninstallPrevious" is because Cura has settings that users might want to keep. So the Windows Package Manager sees the earlier version is still installed on the system and is attempting to upgrade it. We're going to add more logic such that if the latest version is already installed on the system it won't try to update the earlier version.

The version is included in the name, so you can `winget list cura` and `winget uninstall "Ultimaker Cura <version>"` to remove the version you want removed.

Trivia: Ultimaker.Cura was one of the first packages in the repository (even before public preview).

**Closed by denelon** 2022-06-17 22:16 UTC
Labels: Needs-Triage
