### ISSUE TITLE
Option to specify files or folder that should be added to the PATH after install

### ISSUE THREAD

**Issue by SonOfDiablo** [microsoft/winget-cli#1153] opened 2021-06-11 14:58 UTC
# Description of the new feature/enhancement

This request is for an optional entry in the manifest that lists files or folders that should be added to the PATH after installing a given application.

As an example I tried installing nmap with WinGet and naturally wanted to run the program afterwards, but it was not added to my PATH and as such I couldn't just use it.
I know many installers does this themselves, but it would be a great option for those that doesn't.

An alternative option could be a shim solution like https://github.com/lukesampson/scoop does, however this does cause some issues at times.

# Proposed technical implementation details (optional)

**Comment by denelon** [comment] 2021-06-11 16:46
@SonOfDiablo take a look at #222. This might be a duplicate.

**Comment by SonOfDiablo** [comment] 2021-06-11 16:55
> @SonOfDiablo take a look at #222. This might be a duplicate.

Oh.. I didn't even think about that, yea that is the issue I had.
But my Feature Suggestion still stands, I guess it will specially become relevant once https://github.com/microsoft/winget-cli/issues/182 and/or https://github.com/microsoft/winget-cli/issues/140 gets implemented since they won't have installers to handle the PATH.

**Comment by denelon** [comment] 2021-06-11 17:00
@SonOfDiablo we are planning to "build" a mechanism to get them (#182 and #140) treated as "installed" in Add / Remove Programs. We're expecting plenty of edge cases to deal with, but we will track the path when we install them. That should allow `winget upgrade` and `winget uninstall` to work.

**Comment by SonOfDiablo** [comment] 2021-06-11 17:02
> @SonOfDiablo we are planning to "build" a mechanism to get them (#182 and #140) treated as "installed" in Add / Remove Programs. We're expecting plenty of edge cases to deal with, but we will track the path when we install them. That should allow `winget upgrade` and `winget uninstall` to work.

Gotcha, guess this issue can be closed then :)

**Comment by denelon** [comment] 2021-06-11 17:02
Duplicate of #222

**Closed by denelon** 2021-06-11 17:02 UTC
Labels: Issue-Feature
