### ISSUE TITLE
Clear Package Cache Option

### ISSUE THREAD

**Issue by 6h4n3m** [microsoft/winget-cli#198] opened 2020-05-19 18:25 UTC
Should probably add an option to clear package cache, with a switch to only clear packages on uninstalled apps?

As of right now, it appears packages are cached and properly used for subsequent installs, but there should be an option for clear package caches just in case users need the used space.

**Comment by scadu** [comment] 2021-04-23 06:44
Adding a config option to set the number of versions kept could be also helpful. With default as 3, it could be possible to do rollback quite easily if needed.

**Comment by rvxfahim** [comment] 2022-06-18 14:21
is this feature implemented already ?
how do i clean it manually ? where is the location of downloaded installers ?

**Comment by ItzLevvie** [comment] 2022-06-18 19:02
> is this feature implemented already ? how do i clean it manually ? where is the location of downloaded installers ?

In the latest versions of WinGet installers are automatically deleted after a successful install.

Installers are downloaded to `%TEMP%\WinGet` = `C:\Users\%USERNAME%\AppData\Local\Temp\WinGet`

**Comment by vedantmgoyal2009** [comment] 2022-09-19 16:24
* @denelon can be merged with https://github.com/microsoft/winget-cli/issues/343.

**Comment by denelon** [comment] 2022-09-19 16:28
Duplicate of #343

**Closed by denelon** 2022-09-19 16:28 UTC
Labels: Issue-Feature
