### ISSUE TITLE
winget update exclusion list

### ISSUE THREAD

**Issue by rajeshjaga** [microsoft/winget-cli#4452] opened 2024-05-07 05:05 UTC
### Description of the new feature / enhancement

While using the command `winget update` to update the all apps there are few apps we would like to hold back from updating.
It would be great to pass in a list of app ids or app names that should be excluded from the winget update.

### Proposed technical implementation details

Take in an array/list and diff them with the app updates available, take the excluded list from that are available only in the updates available and update only this list

**Comment by Trenly** [comment] 2024-05-07 11:16
You can exclude apps from winget upgrade using the [`winget pin`](https://learn.microsoft.com/en-us/windows/package-manager/winget/pinning) command

**Comment by denelon** [comment] 2024-05-07 20:02
Duplicate of #1703 
* #1703

**Closed** 2024-05-07 20:02 UTC
Labels: Issue-Feature, Command-Upgrade
