### ISSUE TITLE
Hold back certain packages when running `winget upgrade --all`

### ISSUE THREAD

**Issue by Wiikend92** [microsoft/winget-cli#3567] opened 2023-08-29 09:01 UTC
### Description of the new feature / enhancement

It would be nice to have a way to lock certain package versions and be able to hold them back during `winget upgrade --all`. If you for some reason need to use a specific version of a piece of software, and a new version is released to winget, you can't enjoy the benefit of the `--all` option the way winget works today.

For instance, I'm a web developer, and to mirror the production environment as much as possible, I'm using the same database version as our production environment, which is not the latest version. However, if I do `winget upgrade --all`, this package will be upgraded, so using that command is no longer an option. I have to upgrade every single other package one by one, which is a real pain.

### Proposed technical implementation details

There must be some way to mark packages to hold them back like when using **apt-mark**:
`apt-mark hold <package-name>`

The list of desired versions for each package can be saved to some kind of version definition manifest similar to how Composer in PHP does it using **JSON**:
```
{
    "versionLocks": {
        "MariaDB.Server": "10.5.17",
        "Microsoft.Edge": "116.*"
}
```

Or you could bake it into the existing registry I expect you're already using by just adding a property "version" which has * as default for latest, and being able to specify versions like above. I don't know the inner mechanics of `winget`, but this should be highly doable in some way. We're already able to install specific versions of packages, so applying that version to each package installation invoked by `winget update --all` should also be possible.

**Comment by mdanish-kh** [comment] 2023-08-29 15:10
This can be achieved through [winget pin](https://learn.microsoft.com/en-us/windows/package-manager/winget/pinning) command.

Duplicate of #476

**Closed** 2023-08-29 15:10 UTC
Labels: Issue-Feature, Needs-Triage

**Comment by Wiikend92** [comment] 2023-08-31 18:05
Oh wow, I can't believe my research didn't find this feature! I was searching for "lock version" and "specify version" instead of "pin version". I still find it weird that this feature didn't show up even once during my googling, as it seems to have existed since around January? Sorry to bother you guys with a duplicate, and thank you for the nudge in the right direction!
