### ISSUE TITLE


unstall

### ISSUE THREAD

**Issue by PuPe1408** [microsoft/winget-cli#668] opened 2020-12-19 07:39 UTC
# Brief description of your issue

# Steps to reproduce

# Expected behavior

# Actual behavior

# Environment

```none
[winget --info]
Windows Package Manager version
Windows: Windows.Desktop version
Package: Microsoft.DesktopAppInstaller version

Any other software?
```

**Comment by megamorf** [comment] 2020-12-22 09:38
This issue is unusable and therefore should be closed.

**Comment by denelon** [comment] 2020-12-26 20:15
Duplicate of #121

**Closed by denelon** 2020-12-26 20:16 UTC
Labels: Needs-Triage
