### ISSUE TITLE
`winget install` should optionally upgrade only if a newer version is available

### ISSUE THREAD

**Issue by matbech** [microsoft/winget-cli#1411] opened 2021-08-29 01:07 UTC
# Description of the new feature/enhancement
As a user I want to ensure that the latest version of package X is installed, whether this package is already installed (and optionally needs to be upgraded) or not. If the package is already installed and an upgrade is available, the upgrade should be done. If no upgrade is available, the package should not be reinstalled (which is currently the case with winget install). If the package is not installed, it should be installed.

To achieve this goal with the current implementation, I have to first run:
`winget upgrade X`
if the command fails with
"No installed package found matching input criteria."
ERRORLEVEL = -1978335212
Then I install the package with:
`winget install X`

If I call `winget install X`, the package will be reinstalled, even if the latest version of the package is already installed.

# Proposed technical implementation details (optional)
I propose an additional command line switch `--upgrade` for the `winget install` command. If the switch is enabled, then the install command should only install (upgrade) the package if a newer version is available.

**Comment by sanamhub** [comment] 2021-10-22 02:48
### I agree on it with @matbech

If the package is already installed and an upgrade is available, the upgrade should be done. If no upgrade is available, the package should not be reinstalled (which is currently the case with `winget install`). If the package is not installed, it should be installed.

WPM would be much welcome or adds much value to Windows Ecosystem as a Package Manager after implementation of these things @denelon

**Comment by denelon** [comment] 2022-01-05 22:59
This may be a duplicate.

See
* #929

**Comment by denelon** [comment] 2022-08-05 18:48
Duplicate of #929

**Closed by denelon** 2022-08-05 18:48 UTC
Labels: Issue-Feature
