### ISSUE TITLE
Add a verbose mode/switch for `winget install` or a dependency analysis feature to SHOUT out dependencies missing

### ISSUE THREAD

**Issue by CGQAQ** [microsoft/winget-cli#468] opened 2020-06-24 21:48 UTC
# Description of the new feature/enhancement

Add a verbose mode/switch for `winget install` or a dependency analysis feature to SHOUT out dependencies missing instead of doing this

![image](https://user-images.githubusercontent.com/15936231/85631068-6b0c8e00-b6a7-11ea-8441-56c62f3dc738.png)
![image](https://user-images.githubusercontent.com/15936231/85632085-37cafe80-b6a9-11ea-98ad-4a1c1e5a1544.png)

If he didn't mention [that](https://github.com/microsoft/winget-pkgs/pull/1103#issuecomment-649003395), I don't possibly knowing that!  

BTW, I can't even realize it by manually download the link inside the YAML config file and install it because it installed perfectly without saying I do not have VC runtime
![image](https://user-images.githubusercontent.com/15936231/85632683-58e01f00-b6aa-11ea-8c4a-e04d53ba13d9.png)

**Comment by denelon** [comment] 2020-06-29 16:54
This issue includes #163 and #161

**Comment by denelon** [comment] 2020-06-29 16:54
Duplicate of #163

**Closed by denelon** 2020-06-29 16:54 UTC
Labels: Needs-Triage
