### ISSUE TITLE
System-Wide winget installer

### ISSUE THREAD

**Issue by TreeBranches** [microsoft/winget-cli#1724] opened 2021-11-18 16:28 UTC
### Description of the new feature / enhancement

I was preparing to automate our environments app deployment to make better use of the Windows Store through winget, with the following command to install the Windows Terminal (and therefore leave the Store to keep it up to date so that I don't have to);

`winget install --id 9N0DX20HK701 --source msstore --accept-source-agreements --accept-package-agreements --silent`

However, I immediately hit a brick wall

`winget : The term 'winget' is not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

Looking into it, the winget application, for some reason, installs itself by default in `%localappdata%\Microsoft\WindowsApps`

As deployment uses the Windows' NTAUTH\System account, becomes worthless for our environment and we're stuck with manual msiexec installs.

### Proposed technical implementation details

Migrate winget away from `%localappdata%` and into a more system-wide location to match other command line/system  applications, such as msiexec. So putting it in `%SYSTEMROOT%` or `%SYSTEMROOT%\System32` for example.

**Comment by jedieaston** [comment] 2021-11-18 17:03
Apparently this is an MSIX issue, not a winget issue: https://github.com/microsoft/winget-cli/issues/1627.

**Comment by denelon** [comment] 2021-11-18 18:01
Duplicate of #1627

**Closed by denelon** 2021-11-18 18:01 UTC
Labels: Issue-Feature, Needs-Triage
