### ISSUE TITLE
When downloading the software installation package from the HTTP server, do you support multi-thread download and resumable download?

### ISSUE THREAD

**Issue by masx200** [microsoft/winget-cli#319] opened 2020-05-24 16:29 UTC
# Description of the new feature/enhancement

When downloading the software installation package from the HTTP server, do you support multi-thread download and resumable download?

Does it support HTTP2 and HTTP over quic protocols?

# Proposed technical implementation details (optional)

**Comment by megamorf** [comment] 2020-05-26 15:54
Relates to:
* #151
* #225

**Comment by denelon** [comment] 2020-06-02 02:51
Duplicate of #225

**Closed by denelon** 2020-06-02 02:51 UTC
Labels: Issue-Feature, Needs-Triage
