### ISSUE TITLE
Winget Error 0x87af0001 SQL Logic Error or Missing Database

### ISSUE THREAD

**Issue by TonicStark** [microsoft/winget-cli#2262] opened 2022-06-20 20:15 UTC
### Brief description of your issue

So, I came up to this error while trying to update some packages required for styling my terminal. It runs all the commands but after loading and performing them, this error come up and it's like I've done nothing. So I can't use winget

### Steps to reproduce

For me all types of commands, like:
`winget upgrade --all`
`winget upgrade <package_name>`
`winget list`
`winget install <package_name>`

### Expected behavior

Winget runs the specified command without errors

### Actual behavior

Getting:
```
An unexpected error occurred while executing the command:
SQL logic error
0x87af0001: SQL error or missing database
```

### Environment

```shell
[Winget --info]
v1.2.10941
Windows: Windows.Desktop v10.0.22000.739
Package: Microsoft.DesktopAppInstaller v1.17.10941.0
```

**Comment by denelon** [comment] 2022-06-20 20:54
Have you tried `winget source reset --force` in an administrative prompt?

**Comment by TonicStark** [comment] 2022-06-20 21:06
Yes, I already done this. I tried to restore and reset but nothing changed. I also tried now, but it doesn't work.

**Comment by TonicStark** [comment] 2022-06-20 21:12
If it can help, I already search similar problems, and I found the #1999 Issue which seems to be the problem I also have, in fact I commented on it a few hours ago. I tried the advice they give but they didn't worked.

**Comment by denelon** [comment] 2022-06-20 21:48
Duplicate of #1999

**Comment by TonicStark** [comment] 2022-06-20 21:51
So, because it's a duplicate, we can continue our conversation on #1999?

**Closed** 2022-06-20 21:52 UTC
Labels: Issue-Bug, Needs-Author-Feedback, Resolution-Duplicate
