### ISSUE TITLE
winget show command should show if an application is already installed

### ISSUE THREAD

**Issue by besmirzanaj** [microsoft/winget-cli#930] opened 2021-05-05 21:16 UTC
# Description of the new feature/enhancement
`winget show <software>` should show and display if the <software> is already installed.

# Proposed technical implementation details (optional)
when running `winget show <software>` add a keg key or a config file that will mark that `<software>` as installed and show as command output that the package is either `not available (not found)`, `available` or `installed`. Right now this status of the app is missing:

```
PS C:\Windows\system32> winget show "Visual Studio Code"
Found Visual Studio Code [Microsoft.VisualStudioCode]
Version: 1.55.2.3c4e3df9e8
Publisher: Microsoft
Moniker: vscode
Description: Visual Studio Code is a code editor redefined and optimized for building and debugging modern web and cloud applications. Visual Studio Code is free and available on your favorite platform - Linux, macOS, and Windows.
Homepage: https://code.visualstudio.com
License: MIT
License Url: https://github.com/microsoft/vscode/blob/main/LICENSE.txt
Installer:
  Type: Inno
  Download Url: https://az764295.vo.msecnd.net/stable/3c4e3df9e89829dce27b7b5c24508306b151f30d/VSCodeUserSetup-x64-1.55.2.exe
  SHA256: 85b2c5357b4901623ae1ac4644270f797b240745052a7df5fb4be686f2780f7b
```

**Comment by denelon** [comment] 2021-05-05 21:40
I believe you can already do this with `winget list <package>`. One caveat is that we don't treat the list search the same way we do with looking at manifest meta-data like tags, moniker etc.

**Comment by denelon** [comment] 2021-05-05 21:42
Duplicate of #826

**Closed by denelon** 2021-05-05 21:42 UTC
Labels: Issue-Feature, Needs-Triage
