### ISSUE TITLE
Add download count to every package

### ISSUE THREAD

**Issue by upintheairsheep** [microsoft/winget-cli#3042] opened 2023-03-03 20:34 UTC
### Description of the new feature / enhancement

Please add a download count and possibly percentage-based statistics (windows version, country or us state, machine downloaded from, manufacturer, cpu vendor, gpu vendor, and architecture) to the winget package manager, that is retrievable when "winget stats (package)" is entered. This will make it easy to see which packages are the most downloaded, and for businesses to see whether if their apps are succeeding.

### Proposed technical implementation details

When downloading the installer, send an api request to a microsoft server showing that the app was downloaded along with basic statistics.

**Comment by upintheairsheep** [comment] 2023-03-03 20:36
There is a --no-api-count or something flag to disable the api request.

**Comment by mdanish-kh** [comment] 2023-03-03 20:38
Related to

- https://github.com/microsoft/winget-pkgs/discussions/39736

**Comment by denelon** [comment] 2024-03-06 19:00
Duplicate of #1238 
* #1238

**Closed by denelon** 2024-03-06 19:00 UTC
Labels: Issue-Feature
