### ISSUE TITLE
winget upgrade --all exits with File System Error

### ISSUE THREAD

**Issue by Marcuse7** [microsoft/winget-cli#4277] opened 2024-03-16 10:40 UTC
### Brief description of your issue

The command `winget upgrade --all` does not start upgrade installations

### Steps to reproduce

Start Terminal
Execute command `winget upgrade --all`

### Expected behavior

Package installations are executed

### Actual behavior

_winget_ lists packages that can be updated but exits with -1073741819 (File System Error):

```
Name                                     Id                               Version  Available   Source
-----------------------------------------------------------------------------------------------------
ExifTool version 12.77_64                OliverBetz.ExifTool              12.77    12.78       winget
GitHub Desktop                           GitHub.GitHubDesktop             3.3.9    3.3.11      winget
IntelliJ IDEA Community Edition 2023.3.4 JetBrains.IntelliJIDEA.Community 2023.3.4 2023.3.5    winget
MediaInfo 24.01                          MediaArea.MediaInfo.GUI          24.01    24.01.1     winget
WinSCP 6.3.1                             WinSCP.WinSCP                    6.3.1    6.3.2       winget
blender                                  BlenderFoundation.Blender        3.6.5    4.0.2       winget
Microsoft Visual Studio Code (User)      Microsoft.VisualStudioCode       1.87.0   1.87.2      winget
4K Video Downloader+                     OpenMedia.4KVideoDownloader      1.0.1.19 4.29.0.5640 winget
FileBot                                  PointPlanck.FileBot              5.1.2    5.1.3       winget
JOSM                                     OpenStreetMap.Josm               18513    18969       winget
11 upgrades available.

The following packages have an upgrade available, but require explicit targeting for upgrade:
Name            Id              Version      Available            Source
------------------------------------------------------------------------
Microsoft Teams Microsoft.Teams 1.6.00.22378 23320.3027.2591.1505 winget
3 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.
```

Logs:
[WinGetCOM-2024-03-16-11-09-58.817.zip](https://github.com/microsoft/winget-cli/files/14623248/WinGetCOM-2024-03-16-11-09-58.817.zip)

This issue could be related to #2869 .

### Environment

```shell
Windows Package Manager (Preview) v1.8.532-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.4170
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.532.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                P:\Users\Markus\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Enabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by Trenly** [comment] 2024-03-16 12:58
Try using version [v1.7.10661](https://github.com/microsoft/winget-cli/releases/tag/v1.7.10661). This is a known issue in v1.7.10582 and v1.8.532-preview (which was created a few hours after the release of 1.7.10582). If you still run into problems, please let me know.

Duplicate of #4219

**Closed** 2024-03-16 12:58 UTC
