### ISSUE TITLE
keep cache of downloaded packages 

### ISSUE THREAD

**Issue by elswerky** [microsoft/winget-cli#2003] opened 2022-03-05 18:57 UTC
### Description of the new feature / enhancement

Can you please update winget to keep cache of downlaoded packages and installers 

i tried to find where downloaded isntallers are in C partition but didn't find them 

so please ADD option to save these cache downlaoded packages vai winget  and add option to choose path for this cache location 

for example i may choose a folder in D: partition to downlaod cache packages to be able to save them for future installs if i want

**Comment by elvary** [comment] 2022-08-28 06:52
interested, im having problem running "git" command in windows terminal because winget would automatically select the default options throughout the installation process, whether or not git commands can be run within command prompt depends on one critical step called "adjusting your path evironment" in that installation process, which was inconveniently chosen: https://stackoverflow.com/a/34321267
therefore being able to locate and manually re-run the .exe file would be more convenient

**Comment by Masamune3210** [comment] 2022-08-28 07:25
In a perfect world, you wouldnt have to go hunting for the installer to fix this, the option should be exposed as a flag by the installer and the manifest would just have it in the switches just like the silent flag is, but either the flag isn't exposed or the manifest doesn't have the switch

**Comment by denelon** [comment] 2022-09-19 16:27
Duplicate of #343

**Closed by denelon** 2022-09-19 16:27 UTC
Labels: Issue-Feature
