### ISSUE TITLE
How do I ignore a package update

### ISSUE THREAD

**Issue by AirBashX** [microsoft/winget-cli#1908] opened 2022-02-07 02:30 UTC
### Description of the new feature / enhancement

I have a few software I don't want to update.When I update all software, can I ignore the update of these software?

**Comment by KaranKad** [comment] 2022-02-07 14:44
Duplicate of https://github.com/microsoft/winget-cli/issues/1439

**Comment by denelon** [comment] 2022-02-07 15:52
Duplicate of https://github.com/microsoft/winget-cli/issues/1439

Related to:
* #476

**Closed** 2022-02-07 15:53 UTC
Labels: Issue-Feature, Resolution-Duplicate
