### ISSUE TITLE
Please make it, so that attended installations work with the package manager.

### ISSUE THREAD

**Issue by TechPhoenix-89** [microsoft/winget-cli#1106] opened 2021-06-04 15:08 UTC
Whenever, I make an attended installation package, it just doesn't work. 

it, pops up the wizard, or window, and I will do the necessary steps and the installations, 

Most program installations have an attended installation, so it would be useful, if we have all types of installations work with winget.

If it is made that if the specific program is an attended installation type, the window, or the wizard pops up, it works us through the setup, and the installation is done.

**Comment by denelon** [comment] 2021-06-04 16:32
Duplicate of #910

**Closed by denelon** 2021-06-04 16:32 UTC
Labels: Issue-Feature, Needs-Triage
