### ISSUE TITLE
Create a way to update packages that have been installed with winget using "winget update" 

### ISSUE THREAD

**Issue by 215carlos** [microsoft/winget-cli#894] opened 2021-04-23 17:03 UTC
# Description of the new feature/enhancement
Create a way to update packages that have been installed with winget using "winget update  packageName" 

# Proposed technical implementation details (optional)
There are many updates that happen to packages all the time. It would be great to include a way have the option to update the package that was installed to the latest version. 

The "widget update packageName" would get the package updated to the latest version of such package.

**Comment by denelon** [comment] 2021-04-23 18:46
@215carlos the feature you are looking for is `winget upgrade`. It's currently an experimental feature. Just execute `winget features` to see what is available. You can enable the settings by modifying your settings.json file. If you execute `winget settings` your default .json editor will launch. If you have Visual Studio Code configured for this, the JSON schema will provide tooltips and auto-complete.

**Comment by denelon** [comment] 2021-04-23 18:46
Duplicate of #120

**Closed by denelon** 2021-04-23 18:46 UTC
Labels: Issue-Feature, Needs-Triage
