### ISSUE TITLE
`winget upgrade RealVNC.VNCViewer` pulls 32-bit installer on 64-bit machine, resulting in failure

### ISSUE THREAD

**Issue by sba923** [microsoft/winget-cli#3653] opened 2023-09-22 04:45 UTC
### Brief description of your issue

`winget upgrade RealVNC.VNCViewer` fails to upgrade 64-bit version 7.5.1.50075 to 64-bit version 7.6.0.50657, because it pulls a 32-bit installer.

### Steps to reproduce

Run `winget upgrade RealVNC.VNCViewer` on a machine where version 7.5.1.50075 of the application is installed.

### Expected behavior

The application should be upgraded to version 7.6.0.50657 as reported by `winget list RealVNC.VNCViewer`:

````
PS❯ winget list RealVNC.VNCViewer
Name                 Id                Version     Available   Source
---------------------------------------------------------------------
RealVNC Viewer 7.5.1 RealVNC.VNCViewer 7.5.1.50075 7.6.0.50657 winget
````

### Actual behavior

````
PS❯ winget upgrade RealVNC.VNCViewer
Found VNC Viewer [RealVNC.VNCViewer] Version 7.6.0.50657
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Installer failed with exit code: 1603
Installer log is available at: C:\Users\<REDACTED>\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-RealVNC.VNCViewer.7.6.0.50657-2023-09-22-06-43-55.116.log
NativeCommandExitException: Program "winget.exe" ended with non-zero exit code: -1978335226.
````

Here are the logs: 
[WinGet-2023-09-22-06-36-34.075.zip](https://github.com/microsoft/winget-cli/files/12696836/WinGet-2023-09-22-06-36-34.075.zip)

### Environment

```shell
Windows Package Manager v1.5.2201
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2283
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.2201.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by Trenly** [comment] 2023-09-22 08:15
Looking at this, it seems that the MSI is the installer being selected. I looked at the website
```
2023-09-22 06:36:35.813 [CLI ] Starting installer selection.
2023-09-22 06:36:35.813 [CLI ] Installer [X86,exe,Machine,] is current best choice
2023-09-22 06:36:35.813 [CLI ] Installer [X64,exe,Machine,] is better than [X86,exe,Machine,] due to: Machine Architecture
2023-09-22 06:36:35.813 [CLI ] Installer [X64,exe,Machine,] is current best choice
2023-09-22 06:36:35.813 [CLI ] Installer [X86,portable,Unknown,] not applicable: Installed package type 'msi' is not compatible with installer type portable, or with accepted type(s) unknown
2023-09-22 06:36:35.813 [CLI ] Installer [X64,portable,Unknown,] not applicable: Installed package type 'msi' is not compatible with installer type portable
2023-09-22 06:36:35.813 [CLI ] Installer [X86,msi,Unknown,] is better than [X64,exe,Machine,] due to: Installed Type
2023-09-22 06:36:35.813 [CLI ] Installer [X86,msi,Unknown,] is current best choice
2023-09-22 06:36:35.813 [CLI ] Installer [X86,msi,Unknown,] is better than [X64,wix,Unknown,] due to: Installed Type
2023-09-22 06:36:35.813 [CLI ] Completed installer selection.
2023-09-22 06:36:35.813 [CLI ] Selected installer Architecture: 1
2023-09-22 06:36:35.813 [CLI ] Selected installer URL: https://downloads.realvnc.com/download/file/viewer.files/VNC-Viewer-7.6.0-Windows-msi.zip
2023-09-22 06:36:35.813 [CLI ] Selected installer InstallerType: msi
2023-09-22 06:36:35.813 [CLI ] Selected installer Scope: Unknown
```

I see that it specifically is choosing MSI over WIX because it sees the current install is an MSI, despite WIX also being an MSI.

* Caused by #2565 

-----

I'll see if the manifest can be updated to consider both of them as MSI as a temporary fix

**Comment by Trenly** [comment] 2023-09-22 13:04
> Isn't there a MSI for the 64-bit version?

There is, and it is in the manifest. However, its built using WIX, and the winget client doesn’t intepret WIX and MSI to be the same installer type for purposes of an upgrade even though they are.

**Comment by denelon** [comment] 2023-09-22 15:08
Duplicate of #2265

I've moved #2265 one into the 1.7 milestone.

**Closed** 2023-09-22 15:08 UTC
Labels: Needs-Triage

**Comment by sba923** [comment] 2023-09-29 17:42
Fix confirmed

````
(4/4) Found RealVNC Viewer [RealVNC.VNCViewer] Version 7.6.1.50931
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://downloads.realvnc.com/download/file/viewer.files/VNC-Viewer-7.6.1-Windows.exe
  ██████████████████████████████  11.0 MB / 11.0 MB
Successfully verified installer hash
Starting package install...
Successfully installed
````


Thanks!
