### ISSUE TITLE
Installing APPX package from the Store as --scope machine installs to the [system] user only, not as a provisioned AppX Package as it should be

### ISSUE THREAD

**Issue by bthorpkt** [microsoft/winget-cli#4748] opened 2024-08-22 14:26 UTC
### Brief description of your issue

Using PowerShell to orchestrate winget via SCCM (NT\SYSTEM) account I'd expect WinGet to download the AppX package and provision it system wide when the flag to set the scope of system is used. This would give all users access via registration of the app to the package.

Instead, from what I can tell it just installs the appx as the NT\SYSTEM user and gives up.

### Steps to reproduce

PowerShell on a system with Winget installed;
psexec cmd -i -s to run as system
powershell to jump to powershell command prompt

$AppName = "9NTXR16HNW1T" # PowerBI Microsoft Store Edition
winget install --exact $AppName --silent --accept-package-agreements --accept-source-agreements --scope machine

### Expected behavior

Something similar to downloading the PowerBI AppX Package and doing this:
Add-AppxProvisionedPackage -SkipLicense -Online -PackagePath "Microsoft.MicrosoftPowerBIDesktop_2.129.1229.0_x64__8wekyb3d8bbwe.Appx"

### Actual behavior

App is not provisioned system wide, nor is it registered to all users of the system past, present or future. May install in the non interactive System account on a machine.

### Environment

```shell
Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.4780
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled

Configuration Manager Current Branch
PowerShell native build for Windows 10 22H2 / Windows 11 23H2
```

**Comment by bthorpkt** [comment] 2024-08-22 18:39
#3553 is similar or the same. You can merge?

**Comment by denelon** [comment] 2024-08-28 01:10
Duplicate of #3553

**Closed** 2024-08-28 01:10 UTC
