### ISSUE TITLE
winget

### ISSUE THREAD

**Issue by BentramLawrence** [microsoft/winget-cli#1751] opened 2021-11-29 18:12 UTC
### Brief description of your issue

awful winget does not have texlive install. 

provide tex live quality build for free voluntarily. 

a true open community would quickly provide great latex install tex live which is used by sharelatex. 

but windows is user hostile, and awful with open source. 

### Steps to reproduce

winget install texlive

### Expected behavior

install texlive build that works great out of the bux supports everything no bugs no awful windows microsoft bad engineering behavior

### Actual behavior

hate winget, it makes windows feel even more like windows - broken, unpredictable, scary, opaque (as opposed to transparent), full of broken things and leftovers

### Environment

```shell
idk
```

**Comment by BentramLawrence** [comment] 2021-11-29 18:14
everyone I know that gets exposed to winget will quicky get even more frustrated and even more hateful and spiteful of microsoft and msft software in general. waste of time, always, extremely user hostile and breaks stuff

**Comment by denelon** [comment] 2021-11-29 18:17
Duplicate of https://github.com/microsoft/winget-pkgs/issues/34998

**Closed** 2021-11-29 18:18 UTC
Labels: Resolution-Duplicate

**Comment by BentramLawrence** [comment] 2021-11-29 18:26
hadn't seen that issue, why is msft winget package team so hostile to users?
