### ISSUE TITLE
Incorrect Microsoft .NET SDK version

### ISSUE THREAD

**Issue by jahvari** [microsoft/winget-cli#3014] opened 2023-02-27 14:30 UTC
### Brief description of your issue

Winget think that there is a newer version of Microsoft .NET SDK version 6 available when there is not. 

### Steps to reproduce

![Capture1](https://user-images.githubusercontent.com/75337667/221590267-08e400bd-11b3-40e3-a94d-a785e47fa05d.PNG)

Here is a screenshot of the latest version from Microsoft's download page.

### Expected behavior

It should not attempt to upgrade or show a new version. 

### Actual behavior

![Capture](https://user-images.githubusercontent.com/75337667/221590214-368c4686-78e5-4903-957f-2ec327201ef0.PNG)

It attempts to update the current version.

### Environment

```shell
C:\WINDOWS\system32>winget --info
Windows Package Manager (Preview) v1.5.441-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.2486
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.441.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by ItzLevvie** [comment] 2023-02-27 14:54
It's a bug in the website because the release notes point to https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.14/6.0.14.md

https://dotnet.microsoft.com/en-us/download & https://dotnet.microsoft.com/en-us/download/dotnet/6.0 both point to 6.0.406

**Comment by ItzLevvie** [comment] 2023-02-27 15:03
cc @mthalman: Do you know anyone who can update the URLs in https://dotnet.microsoft.com/en-us/download/visual-studio-sdks under `Visual Studio 2022 SDK`?

![image](https://user-images.githubusercontent.com/11600822/221599196-dd2dc21f-cb81-4795-a8ef-4c452e2b7836.png)

Download URL for x64 points to 6.0.309
Download URL for x86 points to 6.0.309
Download URL for arm64 points to 6.0.406

**Comment by mthalman** [comment] 2023-02-27 15:14
@rbhanda - Can you help out here? Where is dotnet.microsoft.com getting this information from? Is the release.json not defined correctly?

**Comment by rbhanda** [comment] 2023-02-27 16:14
I checked our json and they are pointing to the latest sdk. May be @mairaw can help here

**Comment by aetonsi** [comment] 2023-04-18 20:55
I think i have the same issue with `Microsoft.DotNet.SDK.3_1`.
Version 3.1.426 is already installed, but it keeps reinstalling it.
```log
Name                                  Id                       Version   Available Source
-----------------------------------------------------------------------------------------
Microsoft .NET Core SDK 3.1.302 (x64) Microsoft.DotNet.SDK.3_1 < 3.1.419 3.1.426   winget
```
Also the name says "3.1.302", but it's incorrect.

**Comment by aetonsi** [comment] 2023-04-18 20:58
--- nb: completely uninstalling and reinstalling the package didn't do anything.

**Comment by mairaw** [comment] 2023-04-20 04:24
Let me check why .NET 6 is showing different SDK versions on the site. But it all comes from the releases.json file. We might just have a bad logic somewhere.

**Comment by mairaw** [comment] 2023-04-20 05:25
@rbhanda I logged an issue for our site but I think the root cause is missing information on the releases.json files for 6.0

The VS info is missing for certain releases since 6.0.404. 
Compare 6.0.403 entry 
https://github.com/dotnet/core/blob/main/release-notes/6.0/releases.json#L3593

with 6.0.404 for example
https://github.com/dotnet/core/blob/main/release-notes/6.0/releases.json#L2903

From what I can see in the upload logic, if the VS version supported for x64 and x86 is null, then it assumes the SDK is not tied to a specific VS version (it has a note that this was true for pre-2.1 versions).
We could certainly review the upload logic there to see what's still true or not, but I think if you add the missing VS information to releases.json, the issue on the site should be fixed.

**Comment by mairaw** [comment] 2023-04-21 22:56
I made a change on the website that will now show the same version for all three arch values. Since the 4.0.8 version is not attached to a VS version on the releases.json, showing the 311 version is the right thing to do in this case, for now. If the releases.json is changed, then we'll display the latest version attached to a VS version.

**Comment by aetonsi** [comment] 2023-04-28 06:37
@mairaw sorry i am not understanding, you said that about the 311 version so i guess you're talking about my problem.
Can i do something to "fix" the update problem?

**Comment by aetonsi** [comment] 2023-04-28 07:02
Waaaait a minute!
I **now** have both the `3.1.302 (x64)` **and** `3.1.426 (x64)` installed side by side, in the control panel!
I have no idea why... i actually don't even know what software/windows update installed them (i'm guessing Visual Studio Community 2022?).
Anyway i just uninstalled `3.1.302 (x64)` and now `winget upgrade` doesn't show the update available anymore. So nevermind @mairaw about what i said in the previous message.
I'll let you know if it comes back (meaning if `3.1.302 (x64)` gets reinstalled by something).

If anyone knows, can i somehow trace what installed the SDKs? i don't know, maybe with the Event Viewer?

**Comment by denelon** [comment] 2024-07-09 00:48
WinGet 1.8 has improved support for "side-by-side" packages.
Is this still an issue with the latest version of the client?

**Closed** 2024-07-23 02:45 UTC
Labels: Issue-Bug, Needs-Author-Feedback, No-Recent-Activity, Area-External
