### ISSUE TITLE
Additional  switch for downloading only

### ISSUE THREAD

**Issue by N0rimaki** [microsoft/winget-cli#1044] opened 2021-05-31 09:55 UTC
# Description of the new feature/enhancement

I would wanna import a list or trigger a single action for only downloading the packages. Not further installation process should be triggered.
Older Versions should deleted from the target folder.
This could be very usefull for keeping all sotware-install-packages on the latest version for offline installations.

# Proposed technical implementation details (optional)

The switch can be used on import or single actions. 
e.g.
`C:\winget download -o "C:\temp" VLC`

This example would download the latetst .msi package of VLC on the path c:temp and delete an older version of the file if it exist.

**Comment by denelon** [comment] 2021-06-01 21:53
Duplicate of #658

**Closed by denelon** 2021-06-01 21:53 UTC
Labels: Issue-Feature, Needs-Triage
