### ISSUE TITLE
Newer Version of a package, but no Update

### ISSUE THREAD

**Issue by eidylon** [microsoft/winget-cli#1928] opened 2022-02-11 15:20 UTC
### Brief description of your issue

I'm not sure if this is actually an issue with the CLI, or with the specific package, but seems like it should be handled better by the cli regardless, so figured I'd start here. 

On several occasions (though only one right now) I've had apps where `winget upgrade` tells me there is an updated version, and the version numbers support this. But then when I run an upgrade command on the package in question, it tells me `No applicable update found.` 

The package currently doing this is StefansTools.grepWin . 

### Steps to reproduce

Running `winget upgrade` shows a newer version: 

```
Name                                            Id                           Version        Available      Source
-----------------------------------------------------------------------------------------------------------------
grepWin                                         StefansTools.grepWin         2.0.1054       2.0.1098       winget
```

Running `winget upgrade StefansTools.grepWin` yields no upgrade.

```
C:\>winget upgrade StefansTools.grepWin
No applicable update found.
```

### Expected behavior

It would upgrade to the new version. 

Or at least give a better reason why it didn't. (
    Maybe installed is 64-bit and the winget source is 32-bit? 
    Or some other reason? 
    Who knows.
)

### Actual behavior

It says there is no upgrade.

### Environment

```shell
Windows Package Manager v1.1.13405
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1526
Package: Microsoft.DesktopAppInstaller v1.16.13405.0
```

**Comment by jedieaston** [comment] 2022-02-11 15:24
Duplicate of #1640

(but thanks for finding us another test case!)

**Closed by jedieaston** 2022-02-11 15:24 UTC
Labels: Needs-Triage
