### ISSUE TITLE
Failed install when part of name matches multiple apps

### ISSUE THREAD

**Issue by ET3117** [microsoft/winget-cli#439] opened 2020-06-18 22:09 UTC
# Brief description of your issue

Attempts to install several packages have failed with the error message "Multiple apps found matching input criteria. Please refine the input."

# Steps to reproduce
PS C:\WINDOWS\system32> winget install --name "Git"
Multiple apps found matching input criteria. Please refine the input.
Name                                    Id                                       Version
------------------------------------------------------------------------------------------
Git                                     Git.Git                                  2.27.0
Logitech Harmony Remote                 Logitech.Harmony                         1.0.1.308
GitHub Desktop                          GitHub.GitHubDesktop                     2.5.2
GitHub CLI                              GitHub.cli                               0.9.0
AdobeDigitalEditions                    Adobe.AdobeDigitalEditions               4.5.11
MicrosoftGitCredentialManagerforWindows Microsoft.GitCredentialManagerforWindows 1.20.0
Git Large File Storage                  GitHub.GitLFS                            2.11.0
Git Extensions                          GitExtensionsTeam.GitExtensions          3.4.1
Gitter IM                               Gitlab.Gitter.IM                         4.1.0
GitKraken                               Axosoft.GitKraken                        7.0.0
TortoiseGit                             TortoiseGit.TortoiseGit                  2.10.0.2
GitLFS                                  Git.GitLFS                               2.11.0
Snagit                                  TechSmith.Snagit                         6.10.34
GitHubReleaseNotes                      StefHeyenrath.GitHubReleaseNotes         1.0.5.3
Logitech Gaming Software                Logitech.LGS                             9.02.65
PS C:\WINDOWS\system32> winget install --id "Git.Git"
Multiple apps found matching input criteria. Please refine the input.
Name   Id         Version
-------------------------
Git    Git.Git    2.27.0
GitLFS Git.GitLFS 2.11.0
PS C:\WINDOWS\system32> winget install --id "Git.Git" --version 2.27.0
Multiple apps found matching input criteria. Please refine the input.
Name   Id         Version
-------------------------
Git    Git.Git    2.27.0
GitLFS Git.GitLFS 2.11.0
# Expected behavior

Expected that the system would match using an exact name match.

# Actual behavior

Even when trying using quotes or other criteria, the system failed to install.

# Environment

Windows Package Manager v0.1.41331 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.18363.900
Package: Microsoft.DesktopAppInstaller v1.0.41331.0

Any other software?
New system - nearly clean.

**Comment by denelon** [comment] 2020-06-18 23:16
Duplicate of #292

**Closed by denelon** 2020-06-18 23:16 UTC
Labels: Needs-Triage
