### ISSUE TITLE
Upgrading package by id error

### ISSUE THREAD

**Issue by dperez83** [microsoft/winget-cli#1829] opened 2022-01-02 19:25 UTC
### Brief description of your issue

Upgrading package by id returns "Multiple installed packages found matching input criteria. Please refine the input." error.

### Steps to reproduce

```
PS C:\Users\dpz83> winget upgrade
Name                                               Id                                Version       Available     Source
-----------------------------------------------------------------------------------------------------------------------
NTLite                                             Nlitesoft.NTLite                  2.1.2.8074    2.3.2.8526    winget
PowerToys (Preview)                                Microsoft.PowerToys               0.49.1        0.51.1        winget
Microsoft Visual C++ 2015-2022 Redistributable (x… Microsoft.VC++2015-2022Redist-x86 14.30.30704.0 14.31.30919.0 winget
Microsoft .NET SDK                                 Microsoft.dotnet                  5.4.421.57211 6.1.121.56904 winget
Microsoft Visual C++ 2015-2019 Redistributable (x… Microsoft.VC++2015-2019Redist-x64 14.28.29913.0 14.29.30139.0 winget
Microsoft .NET SDK                                 Microsoft.dotnet                  5.3.321.37723 6.1.121.56904 winget
Python 3                                           Python.Python.3                   3.8.5150.0    3.10.1150.0   winget
7 upgrades available.
PS C:\Users\dpz83>
PS C:\Users\dpz83> winget upgrade --id Microsoft.VC++2015-2022Redist-x86
Multiple installed packages found matching input criteria. Please refine the input.
Name                                                               Id
---------------------------------------------------------------------------------------------------------
Microsoft Visual C++ 2015-2022 Redistributable (x86)               Microsoft.VC++2015-2022Redist-x86
Microsoft Visual C++ 2015-2019 Redistributable (x64) - 14.28.29913 {855e31d2-9031-46e1-b06d-c9d7777deefb}
PS C:\Users\dpz83>
```

### Expected behavior

Upgrade the package with the id "Microsoft.VC++2015-2022Redist-x86".

### Actual behavior

"Multiple installed packages found matching input criteria. Please refine the input." error.

### Environment

```shell
Windows Package Manager v1.1.13405
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.376
Package: Microsoft.DesktopAppInstaller v1.16.13405.0
```

**Comment by denelon** [comment] 2022-01-03 17:44
Duplicate of #1413

**Closed by denelon** 2022-01-03 17:44 UTC
Labels: Needs-Triage
